### ISSUE TITLE
Is there a way to serialize the context synchronously?

### ISSUE THREAD

**Issue by 0xpablo** [getsentry/sentry-cocoa#1002]
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> 5.3

_sentry-cocoa installed with:_
- [x] Swift Package Manager

Version of sentry-cocoa:
**6.2.1**

---
I have following issue:

We are replacing some `fatalErrors` in our app with a function that does the following:

```
             SentrySDK.configureScope { scope in
                scope.setContext(value: value, key: key)
            }
            SentrySDK.crash()
            fatalError("Unreachable")
```

This helps us capture some context when we crash, while allowing the function to return `Never`.

I was reviewing a couple crashes we received after we implemented that function, and they contained no info. After taking a look at Sentry's source, I saw this: https://github.com/getsentry/sentry-cocoa/blob/c9b7cbe228f70cca0f383e3b5156ff1e97457af3/Sources/Sentry/SentryCrashIntegration.m#L187

Serialization of the scope is async, so that's probably why we are losing that context. Is there a way to synchronize that or a workaround? I guess that sleeping a bit before crashing could fix the issue but I wonder if there is a better solution.

Thanks

**Comment by philipphofmann** [comment]
Hey @0xpablo, 
currently, there is no way to serialize the scope to SentryCrash synchronously. When the scope is quite big the serialization can take some time and can block the calling thread, which could be the main thread. We have plans to speed up the whole synchronization of the scope to SentryCrash, see https://github.com/getsentry/sentry-cocoa/issues/991, but I can't give you an ETA. If we do it properly we should be able to make it synchronous again.

Sleeping could work, but it is definitely not an optimal solution. You could as well create your own event, add your context there and then call `SentrySDK.capture(event: event)`, but the downside is that you still get a crash event from `SentrySDK.crash()`, which you could discard in `beforeSend`.

**Comment by 0xpablo** [comment]
Hey @philipphofmann, thanks for the suggestion, I will try that in the meantime! 🙂
