### ISSUE TITLE
Incorrect MacOS Version for Mac Catalyst Application

### ISSUE THREAD

**Issue by allright** [getsentry/sentry-cocoa#1009]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Crash on Mac Catalyst applications shows incorrectly (look at the picture attached)

## Steps to Reproduce

Just generate crash on Mac

### What you expected to happen

device.family = macOS (instead of iOS)
os = macOS 11.2.3  (instead of 14.4)

[What you think should be happening]
![image](https://user-images.githubusercontent.com/374572/111793975-d3a33700-88d6-11eb-98fc-f018ac0cab14.png)

**Comment by philipphofmann** [comment]
Thanks, @allright for reporting this. I can easily reproduce this issue.

**Comment by bruno-garcia** [comment]
We released another beta with this fix: https://github.com/getsentry/sentry-cocoa/releases/tag/7.0.0-beta.1
It's getting pushed to cocoapods right now too.

Thanks again for trying it out and please let us know if you find any other issues.
