### ISSUE TITLE
Question: Is there a way to determine if Sentry has been started or not?

### ISSUE THREAD

**Issue by hisaac** [getsentry/sentry-cocoa#1050]
Version of sentry-cocoa:
**5.2.2**

Does the `SentrySDK` offer any way to quickly detect if Sentry has been started or not? I was hoping for a simple boolean value I could check, like

```objc
[SentrySDK isStarted];
```

Or is there some other way to dig into it and determine if it's currently running or not?

**Comment by bruno-garcia** [comment]
There's nothing built in. But at the call site of `SentrySDK.start` you could set a boolean flag somewhere in your app. And then look that one up

**Comment by borninla** [comment]
I could be wrong, but I believe this is coming in 7.0.0. 

Not sure about a direct boolean check, but there was talk about adding the ability to start and end a Sentry session.

**Comment by hisaac** [comment]
Thanks @bruno-garcia and @borninla. We're currently setting a boolean within our code like @bruno-garcia mentioned, but was hoping there was a Sentry-controlled value we could check. For now, we'll proceed as is. 👍
