### ISSUE TITLE
Add cacheDirPath to Options

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1051]
The SDK uses the `Library/Cache` folder caching [SDK](https://github.com/getsentry/sentry-cocoa/blob/52226f32a1616c1a6245112e3b6a2d49a07bb484/Sources/Sentry/SentryFileManager.m#L46-L52) and [SentryCrash](https://github.com/getsentry/sentry-cocoa/blob/52226f32a1616c1a6245112e3b6a2d49a07bb484/Sources/SentryCrash/Recording/SentryCrash.m#L70-L85) data. The downside of this is that the OS might delete data in this folder when it needs more disk space or the user can as well delete these caches. We can add something like a `cacheDirPath`, as we already have it in [sentry-java](https://github.com/getsentry/sentry-java/blob/75a87428fee926621ac397a6ffdeff2499caea8e/sentry/src/main/java/io/sentry/SentryOptions.java#L112) to give our users the possibility to change the location of our cache data. A customer of ours already [requested this](https://sentry.slack.com/archives/CP4UUUF1S/p1618498065281300).

**Comment by bruno-garcia** [comment]
Name used in other SDKs:

`sentry-native`: `sentry_options_set_database_path`
`sentry-android/java`: `cacheDirPath`
`sentry-dotnet`: `CacheDirectoryPath`

**Comment by philipphofmann** [comment]
The Swift and Objective-C way to go would be to name it `cacheDirectoryPath`.

**Comment by mattjohnsonpint** [comment]
It's not absolutely required, as long as the cache paths are distinct between the different SDKs so they don't step on each other.  But being able to specify the cache path gives me better control over that.

**Comment by philipphofmann** [comment]
We found a workaround for .NET, and we don't need to align with the other SDKs just to align. To keep the SDK smaller and simpler, we close this for now. We can always reopen if needed.
