### ISSUE TITLE
Report App Hangs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1052]
The [watchdog](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/identifying_the_cause_of_common_crashes/addressing_watchdog_terminations) can terminate an app when it is not responsive for a few seconds. This results in a hard crash with the code `0x8badf00d` ("ate bad food"). Having the app hanging for a few seconds and being terminated by the watchdog is a bad user experience. It would be beneficial for our users to detect shorter unresponsiveness of the app before leading to a crash to improve their apps. We could give them the possibility to configure a threshold in milliseconds for the unresponsiveness of their app and send an event to Sentry when the app hangs longer than the configured threshold.

https://getsentry.atlassian.net/browse/MOBILE-256

**Comment by marandaneto** [comment]
similar to Android ANR, we probably need to investigate grouping when doing this as it can't be too noisy either.

**Comment by philipphofmann** [comment]
Maybe we can use a [CADisplayLink](https://stackoverflow.com/questions/26888434/how-many-ways-to-calculate-the-fps-frames-per-second-of-an-ios-app-programmati/33976924#33976924) on iOS, Mac  Catalyst, and tvOS and a [CVDisplayLink](https://stackoverflow.com/questions/14158743/alternative-of-cadisplaylink-for-mac-os-x/14165842#14165842) on macOS to be able to detect this.

**Comment by philipphofmann** [comment]
We already use CADisplayLink for detecting slow and frozen frames. We could use this logic to detect the app not being responsive.

**Comment by philipphofmann** [comment]
This could be solved with a `CFRunLoopObserver` as pointed out here https://github.com/getsentry/sentry-cocoa/issues/1645#issuecomment-1021370702.

**Comment by philipphofmann** [comment]
Update the docs added with [this PR](https://github.com/getsentry/sentry-docs/pull/4645).

**Comment by philipphofmann** [comment]
We recently added the [SentryANRTrackingIntegration](https://github.com/getsentry/sentry-cocoa/blob/f47a953a1b2d0fcecb31e6f0793a47a97e6e4df4/Sources/Sentry/SentryANRTrackingIntegration.m), which contains an algorithm for detecting ANRs. We only need to send the proper ANR events to Sentry. At the moment, our `StrackTraceBuilder` can only fetch stack traces of the current thread. It would be acceptable to capture ANRs with only the stacktrace of the main thread for the beginning.

**Comment by philipphofmann** [comment]
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m seems like a duplicate implementation. We should consider removing it when fixing this issue.

**Comment by brustolin** [comment]
Right know, the scope of this feature will be to create an event every time the app becomes unresponsive for X amount of time.

A future improvement would be to report in the next session if the app crashed because it was unresponsive for too long and was killed by the watchdog. We can even include the event id that was created in the previous session so that Sentry can link these two events together.

**Comment by philipphofmann** [comment]
Remove note on `Main thread deadlock (experimental)` in https://docs.sentry.io/platforms/apple/guides/ios/ and replace it with ANR detection. 

We should remove https://github.com/getsentry/sentry-cocoa/blob/c06c857ff90589996b75f63ce289038ffbb29c24/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m after finishing this PR, as it's a duplicate of our ANR logic.

**Comment by bruno-garcia** [comment]
App Hanging event should include `handled:false` if we know the app is crashing, or if we are creating the event on restart.
If we're only sending an event that the app is hanging but it can possibly recover from it, then it should be `handled:true` (as in: non-fatal, since there's no 'crashed:true')

**Comment by bruno-garcia** [comment]
Could we use the details from the previous App Hang event to augment that fatal event? Basically keep App Hang events around so that in the event of a restart where we detect it was killed due to App Hang, we merge the events into a Fatal?

**Comment by philipphofmann** [comment]
> Could we use the details from the previous App Hang event to augment that fatal event? Basically keep App Hang events around so that in the event of a restart where we detect it was killed due to App Hang, we merge the events into a Fatal?

Yes, we could, but it is some extra logic. That's a great idea.

**Comment by bruno-garcia** [comment]
Had to be reverted. Tracking on: https://github.com/getsentry/sentry-cocoa/pull/1906
