### ISSUE TITLE
SentryTransaction.h can't be found?

### ISSUE THREAD

**Issue by stuffmc** [getsentry/sentry-cocoa#1070]
When I try to integrate `7.0.0-beta.0` this way in `Package.swift` (from a Package itself):

```
dependencies: [
        .package(name: "Sentry", url: "https://github.com/getsentry/sentry-cocoa.git", from: "7.0.0-beta.0"),
(...)
    targets: [
        .target(
            name: "MyApp",
            dependencies: [
                "Sentry",
(...)
```
This is what I've got...

`~/Library/Developer/Xcode/DerivedData/MyApp-dkvqkhmiuwguoehaikzxuapvpjsv/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryTransaction.m:1:9: In file included from /Users/mc/Library/Developer/Xcode/DerivedData/MyApp-dkvqkhmiuwguoehaikzxuapvpjsv/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryTransaction.m:1:`

**Comment by bruno-garcia** [comment]
@stuffmc thanks for raising. I was able to install it with SPM.
Next version should sort it out. Either another beta or perhaps already GA.

**Comment by bruno-garcia** [comment]
We released another beta with this fix: https://github.com/getsentry/sentry-cocoa/releases/tag/7.0.0-beta.1
It's getting pushed to cocoapods right now too.

Thanks again for trying it out and please let us know if you find any other issues.
