### ISSUE TITLE
Fix all "Double-quoted include in framework header, expected angle-bracketed instead" warnings

### ISSUE THREAD

**Issue by lmmenge** [getsentry/sentry-cocoa#1072]
### Environment

How do you use Sentry?
On-premise (21.3.0)

Which SDK and version?
iOS 6.2.1

### Steps to Reproduce

1. Install Xcode 12.5
2. Create a new project or upgrade a new project's configurations to Xcode 12.5's recommended settings
3. Integrate Sentry's iOS SDK
4. Make a build

### Expected Result

There should be no warnings.

### Actual Result

Xcode 12.5 will suggest turning on by-default the following warning: CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=YES.

```
Warns when a quoted include is used instead of a framework style include in a framework header.
```

Turning it on throws warnings for all the places the Sentry framework is using a project (quote) include instead of a framework (angle bracket) import.

**Comment by philipphofmann** [comment]
Thanks for opening up this issue @lmmenge. Unfortunately, this isn't an easy fix, and I don't have an ETA for this right now.

**Comment by lmmenge** [comment]
@philipphofmann if you need a sample project for reproducing this: https://github.com/lmmenge/sentry-double-quote

Building it in Xcode 13 should output plenty of warnings.
