### ISSUE TITLE
Ability to not group specific issues

### ISSUE THREAD

**Issue by borninla** [getsentry/sentry-cocoa#1085]
### Request

It would be nice to allow the SDK user to turn off grouping for specific issues.

### Example / Problem

For example, our app lets a user report feedback whenever they want. When they press "submit", we fire `SentrySDK.capture(...)` to send an event up to us. However, since the last function on the stack frame is an in-app call to send the event, every user feedback issue is grouped under the same event. This makes it difficult to parse through individual feedback requests. We _could_ solve this issue by adding Issue Grouping rules, but if the function name changes in the future we would have to remember to change it in the rule, which could lead to some messy issues in the future.

### Proposed Solution

It would be nice to include a flag on the `Scope` type that can be defaulted to true (allow grouping) but should allow you to set it to false (disable grouping). Below is an example of the intended use.

```
let userMessage = "The UI looks glitchy here"

SentrySDK.capture(message: userMessage) { scope in
   scope.shouldGroup = false
}
```

**Comment by philipphofmann** [comment]
Hey @borninla, sorry for the late response.

The way grouping is built now wouldn't support such a feature you requested. You would somehow need to specify which part of the stacktrace needs to be ignored for grouping. That is already possible with [Issue Grouping Rules](https://docs.sentry.io/platforms/apple/data-management/event-grouping/stack-trace-rules/) like you pointed out. We don't have plans to add such logic to the SDKs at the moment. You can add multiple rules or make use of patterns, so you are safe if someone renames this in the future. Maybe add a comment above to make sure nobody renames the function or class where you do this. 

Maybe take a look at [SDK Fingerprinting](https://docs.sentry.io/platforms/apple/data-management/event-grouping/sdk-fingerprinting/#basic-example). You can define SDK side fingerprint rules there.

The user feedback section in Sentry gives you the ability to go through each user feedback. Maybe you didn't see it yet.
<img width="771" alt="Screen Shot 2021-05-03 at 16 48 47" src="https://user-images.githubusercontent.com/2443292/116891840-7c131d80-ac2f-11eb-93d4-694681704145.png">

Thanks for explaining your use case. We will keep it in mind when working on grouping.

**Comment by philipphofmann** [comment]
I guess your question is answered @borninla, so I'm going to close this now.
