### ISSUE TITLE
Expose DebugImage list for Hybrid SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1089]
Hybrid SDKs that require symbolication would need the debug image list for symbolication.
https://github.com/getsentry/sentry-dart/issues/433

Sentry Cocoa already loads it internally, the idea is that it also offers a public API so Hybrid SDKs can use it.

See for example sentry-native API
https://github.com/getsentry/sentry-native/blob/06d436096653925e5d7a493e413c9981ce7c5f1c/include/sentry.h#L1031-L1037

**Comment by philipphofmann** [comment]
We already have the [`SentryDebugMetaBuilder`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryDebugMetaBuilder.h). Would that work for you @marandaneto? Of course, we can provide a nicer API for it.

**Comment by marandaneto** [comment]
if its a public API, it's already possible to not get blocked by it, but it depends on `SentryCrashDefaultBinaryImageProvider`, so ideally, a method that encapsulates this and returns only a list of `DebugImage` instead of the `DebugMeta` itself, as I'm not interested in the `sdkInfo` field for example.

**Comment by philipphofmann** [comment]
I just found out we have a bit of a conflict in the SentryCocoa SDK with `DebugMeta` and `DebugImages`. `SentryDebugMeta` is in fact [DebugImages](https://develop.sentry.dev/sdk/event-payloads/debugmeta#debug-images). I added a https://github.com/getsentry/sentry-cocoa/discussions/1094#discussioncomment-674063 to fix this in 8.0.0.

We just need the `initWithBinaryImageProvider` for testing so I can make this constructor internal. When we make `SentryDebugMetaBuilder` you can just initialize it and call `buildDebugMeta`. I can open up a PR for this.
