### ISSUE TITLE
Disable / Enable crash reporting while the app is running

### ISSUE THREAD

**Issue by alpennec** [getsentry/sentry-cocoa#1093]
@philipphofmann is this new feature [(Add start and endSession to SentrySDK)](https://github.com/getsentry/sentry-cocoa/pull/1021) the way to enable / disable sending crashs to Sentry if a user disables crash reports in the app? I'm not really sure about the flow because when we start the SDK, we can specify the `options.enabled =` flag, but how can we then update it afterwards? Should we use the `SentrySDK.close()` method when the user switch off, and call again the `SentrySDK.start { options in }` if the user switch on?

**Comment by philipphofmann** [comment]
Hi @alpennec, these two methods start and end sessions for [release health](https://docs.sentry.io/platforms/apple/configuration/releases/). We should improve the code docs on these methods.

When starting you can use the `options.enabled` flag. You can use `SentrySDK.close()` to turn the SDK off.

**Comment by alpennec** [comment]
Thanks @philipphofmann for the help and documentation improvement!

**Comment by borninla** [comment]
Is there a way to check if a session is currently running before calling `SentrySDK.startSession()` to potentially restart one you didn't want to?
