### ISSUE TITLE
perf: Caching loaded symbols list

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1096]
What is the impact to dynamic libraries loaded after the list is cached? What's the approach taken by sentry-native/android?

**Comment by bruno-garcia** [comment]
Is there a hook from the OS that triggers when a new dynamic library is loaded? That could be used to invalidate the cache.
Without such hook having that data cached would mean possibly reporting the incorrect library list.

**Comment by marandaneto** [comment]
maybe there's something like Java JNI -> https://docs.oracle.com/javase/9/docs/specs/jni/invocation.html#jni_onload

**Comment by philipphofmann** [comment]
We could add a cache here https://github.com/getsentry/sentry-cocoa/blob/055a5200ccd4bf9d27305f0d9574fbcc8e5900f0/Sources/Sentry/SentryDebugImageProvider.m#L39-L51

Worth pointing out that this is called for every capture call.

Before we do that, we should investigate how heavy the call to `SentryDebugImageProvider` is. Maybe it's very fast and the benefit of adding a cache is not worth it because cache invalidation could cause problems.

**Comment by philipphofmann** [comment]
Some quick research tells me it takes around 5 ms on a MacBook Air with M1, which is unacceptable. We should implement a cache.

**Comment by philipphofmann** [comment]
Inside SentryCrash we call `_dyld_image_count()`. The [docs state](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dyld.3.html)

> _dyld_image_count() returns the current number of images mapped in by
>      dyld. Note that using this count to iterate all images is not thread
>      safe, because another thread may be adding or removing images during the
>      iteration.

This means images can be removed, so the cache approach with the `getImageCount` might not be sufficient.

**Comment by philipphofmann** [comment]
We could use _dyld_register_func_for_add_image and _dyld_register_func_for_remove_image to be notified when new images are added or removed o invalidate the cache. We already use the first function here https://github.com/getsentry/sentry-cocoa/blob/e47eea57ef97e9b1a949a230b74219587619c33f/Sources/SentryCrash/Recording/Tools/fishhook.c#L260

**Comment by philipphofmann** [comment]
Doing this properly could fix https://github.com/getsentry/sentry-cocoa/issues/1892.

**Comment by philipphofmann** [comment]
Blocked by https://github.com/getsentry/sentry-cocoa/issues/1892, see https://github.com/getsentry/sentry-cocoa/pull/1965#issuecomment-1237080465. 

Please reopen https://github.com/getsentry/sentry-cocoa/pull/1965, as it has some helpful information.
