### ISSUE TITLE
Change SentryUser Swift name to something other than User

### ISSUE THREAD

**Issue by colinhumber** [getsentry/sentry-cocoa#1100]
The Obj-C `SentryUser` has a Swift name of `User` via `NS_SWIFT_NAME(User)`. `User` is an incredibly common class name in apps, and having this renamed to `User` in Swift causes a lot more issues than it needs to. If I have a class that uses both Sentry and my own `User` class, I need to explicitly use `MyModule.User` in order to avoid naming conflicts.

I understand this would be a breaking change, but using the Sentry framework should provide as few roadblocks to using our own code as possible. Thanks!

**Comment by philipphofmann** [comment]
Ah, if you just opened up this issue a few days earlier 😁. We just shipped 7.0.0. I add this to 8.0.0, so we can discuss this in the next major. I agree with you that we should change this. Thanks for pointing it out.

**Comment by colinhumber** [comment]
Awesome! Glad it's on the roadmap!

**Comment by philipphofmann** [comment]
Maybe we could use a protocol and some subclassing to not make this a breaking change.

**Comment by philipphofmann** [comment]
Closed with https://github.com/getsentry/sentry-cocoa/pull/2403.
