### ISSUE TITLE
Sentry.h:45:1: umbrella header for module 'Sentry' does not include header 'SentryMechanismMeta.h'

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#1101]
Keep seeing this build warning

`Sentry.h:45:1: umbrella header for module 'Sentry' does not include header 'SentryMechanismMeta.h'`

Integrating using SwiftPM
Xcode 12.5, Xcode 12.4 and probably earlier

**Comment by philipphofmann** [comment]
Thanks for reporting this, @gabors. I'm pretty sure #1102 is solving your problem. What's a bit weird, though, is that I can actually set up a project with SPM, and it compiles and runs for me. Can you maybe provide more details on your setup to help me to get a repro?

**Comment by philipphofmann** [comment]
Oh, now I can. Caching was the issue.

**Comment by philipphofmann** [comment]
Please try with https://github.com/getsentry/sentry-cocoa/releases/tag/7.0.2 and reopen if it doesn't work for you.
