### ISSUE TITLE
Enrich every event with device and app context

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1104]
Currently, the `SentryCrashIntegration` configures the `Scope` of the current `Hub` with the device and app data.
https://github.com/getsentry/sentry-cocoa/blob/b46bdabe0aacf42cc4786856f0940ec653919ab4/Sources/Sentry/SentryCrashIntegration.m#L133-L136

This has the disadvantage when creating a `Hub` manually the client doesn't enrich the event with device and app data. Java uses an EventProcessor to achieve this. 

This came up because we made `Sentry.currentHub` private in 7.0.0 and a user used this method just to initialize a Hub with the scope of the `currentHub`, see https://github.com/getsentry/sentry-cocoa/issues/434#issuecomment-830011500.

**Comment by marandaneto** [comment]
using an `EventProcessor` also has its disadvantages, these trade-offs should be discussed before going forward though.

**Comment by philipphofmann** [comment]
Instead of using an event processor, we could do this in prepare event https://github.com/getsentry/sentry-cocoa/blob/b1ce7c5cd4cbb16a0c97ca417b0891831b779b84/Sources/Sentry/SentryClient.m#L418
