### ISSUE TITLE
Sending log event manually?

### ISSUE THREAD

**Issue by basememara** [getsentry/sentry-cocoa#1112]
I'd like to send event manually to Sentry. For example, my logger is sprinkled throughout my app, where I call `debug`, `info`, `warning`, and `error` levels without the app crashing. If a user reports an issue, I can review the log trail and see what their steps were to identify or reproduce the issue.

I tried using [breadcrumbs](https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/breadcrumbs/), but it seems that only gets attached to crashes.

Is there a way to send issue, events, or logs o Sentry? I'm looking to send log events similar to [DataDog](https://www.datadoghq.com/product/log-management/) or [Papertrail](https://www.papertrail.com). Is this possible with Sentry, maybe even with raw HTTP posts requests without the SDK?

**Comment by danimal** [comment]
You can log a non-fatal error with an `Event`. Something like this is what has been successful for us. Depending on how many users you have and how many events you’re seeing you may want to configure some sort of rate limiting in there so you don't overwhelm your Sentry reporting with events. We also tag each kind of non-fatal that we're logging with a unique tag for that call site so we can search and sort them easier in the web UI later.

```swift
public func logNonFatalError(message: String, tag: SentryTag, additionalInfo: [String: String] = [:]) {
  let event = Sentry.Event(level: .info)
  event.message = SentryMessage(formatted: message)
  SentrySDK.capture(event: event) { scope in
    scope.setTag(value: tag.value, key: tag.key)
    scope.setExtras(additionalInfo)
  }
}
```

**Comment by vg-identance** [comment]
Are there any way to remove manual log function like `logNonFatalError ...` from stacktrace?

**Comment by philipphofmann** [comment]
Thanks, @danimal, for the answer and your insightful use case. @basememara, the SDKs adds breadcrumbs to every event in the Client. I think they should do the job for you.

@danimal, you can also do it like this. No need to create the event manually unless you want to modify the level.
```swift
SentrySDK.capture(message: "Yeah captured a message") { scope in
    scope.setTag(value: "tag.value", key: "tag.key")
    scope.setExtras(additionalInfo)
}
```

**Comment by philipphofmann** [comment]
> Are there any way to remove manual log function like `logNonFatalError ...` from stacktrace?

@vg-identance, this question is off-topic. Do you mind opening up another issue for that, please?

**Comment by vg-identance** [comment]
@philipphofmann actually find way using `beforeSend` so I don't, sorry.

**Comment by philipphofmann** [comment]
I consider this question as answered. Feel free to open the issue again.
