### ISSUE TITLE
Sentry Can't Serialize Date in Scope Context Value ("Invalid JSON")

### ISSUE THREAD

**Issue by cstigler** [getsentry/sentry-cocoa#1113]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
macOS SDK 7.0.3 (also tested with the same issue on 6.x)

### Steps to Reproduce
0. Start sentry using `SentrySDK startWithConfigureOptions` (I am using no particularly special options)
1. Use `configureScope:` to `setContextValue:` to a dictionary value which contains a date value. In my actual app's case, it's reading `NSUserDefaults`, but a repro case would be:
```
    NSDictionary* dict = @{ @"myDateValue": [NSDate date], @"myOtherValue": @"a good string" };
    [SentrySDK configureScope:^(SentryScope * _Nonnull scope) {
        [scope setContextValue: dict forKey: @"MyFavoriteDict"];
    }];
```
2. Send an error using `SentrySDK captureError`

### Expected Result

The date value would be serialized into a string and the context would appear properly in Sentry.

### Actual Result

- I see a log message in the console saying `Sentry - Error:: Invalid JSON`
- When I go to the Sentry website to look at the error, it shows a `sentry.event` saying "A value set to the context or sdk is not serializable. Dropping context and sdk.", and none of my context is shown - not even the other non-date values.

**Comment by philipphofmann** [comment]
Thanks for opening this issue, @cstigler.

The Client applies the Scope to the Event, and we don't sanitize the context of the event when serializing it with `sentry_sanitize` in here https://github.com/getsentry/sentry-cocoa/blob/80681aceb96a84bf804388038dd5376798c82c7a/Sources/Sentry/SentryEvent.m#L133

This should be an easy fix, but I have to check first if this could cause problems.

**Comment by philipphofmann** [comment]
@kevinrenskers, using `sentry_sanitize` shouldn't cause any problems. I can't remember why I thought it would.
