### ISSUE TITLE
the name of method `-unsignedLongLongValue` should start with prefix `sentry_` in your category `SentryUnsignedLongLongValue`

### ISSUE THREAD

**Issue by iwill** [getsentry/sentry-cocoa#1117]
### Environment

How do you use Sentry?
self-hosted

Which SDK and version?
Sentry-Cocoa (6.2.1)

### Steps to Reproduce

1. In my Podfile:
pod 'mob_sharesdk', :inhibit_warnings => true
pod 'Sentry', '~> 6.2'
2. Run `pod install`
3. Build in Xcode

### Expected Result

Success without any error or warning.

### Actual Result

Got a warning: "Method '-unsignedLongLongValue' in category from /.../Pods/mob_sharesdk/ShareSDK/ShareSDK.framework/ShareSDK conflicts with same method from another category"

### Reason

Both `Sentry` and `mob_sharesdk` declared a method named `-unsignedLongLongValue` for `NSString` in category.

### How to Fix

Generally, the name of method `-unsignedLongLongValue` should start with prefix `sentry_` in your category `SentryUnsignedLongLongValue`. `mob_sharesdk` should do the same, I will also report a bug for them.

But I can't sure how do you use the method, if you don't know/care whether the object is `NSString` or `NSNumber`, you can make categories for both of them:

```objc
@interface NSString (SentryUnsignedLongLongValue)
- (unsigned long long)sentry_unsignedLongLongValue;
@end

@implementation NSString (SentryUnsignedLongLongValue)
- (unsigned long long)sentry_unsignedLongLongValue {
    return strtoull([self UTF8String], NULL, 0);
}

@interface NSNumber (SentryUnsignedLongLongValue)
- (unsigned long long)sentry_unsignedLongLongValue;
@end

@implementation NSNumber (SentryUnsignedLongLongValue)
- (unsigned long long)sentry_unsignedLongLongValue {
    return [self unsignedLongLongValue];
}

@end

```

and always use `-sentry_unsignedLongLongValue`.

**Comment by philipphofmann** [comment]
Thanks for reporting this, @iwill. Can you update to 7.x.x, or do you need a hotfix for this on 6.2.x?

**Comment by iwill** [comment]
Got the same warning by updating to 7.0.3, and I tried commit a pull request #1119 to resolve it just a moment ago.

I am glad to update to 7.x.x if it's stable.

**Comment by iwill** [comment]
@philipphofmann 🚀

**Comment by philipphofmann** [comment]
I'm trying to ship a patch today. Thanks for the info.
