### ISSUE TITLE
Enable/disable Sentry at runtime?

### ISSUE THREAD

**Issue by gereons** [getsentry/sentry-cocoa#1130]
Up until v7.x, it was possible to enable / disable Sentry at runtime using

    SentrySDK.currentHub().getClient()?.options.enabled = sentryEnabled

(see e.g. https://github.com/getsentry/sentry-cocoa/issues/419 and https://github.com/getsentry/sentry-cocoa/issues/809)

Now, with `currentHub()` removed from the public API, is there an alternate way to achieve this same effect?

**Comment by philipphofmann** [comment]
Yes, you can use `SentrySDK.close()`.

**Comment by gereons** [comment]
Thanks for the quick reply!
