### ISSUE TITLE
Align Option for Auto UI Performance Instrumentation with Android

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1135]
On Android, we have `enableAutoActivityLifecycleTracing` so we could name it `enableAutoViewControllerLifecycleTracing`.
https://github.com/getsentry/sentry-cocoa/blob/ff24da47d4f8464e35a0e9d6e542adeaa4c6afa8/Sources/Sentry/Public/SentryOptions.h#L164

We also need to rename SentryUIPerformanceTracker accordingly. For more details checkout https://github.com/getsentry/sentry-cocoa/pull/1105#discussion_r639596143

**Comment by bruno-garcia** [comment]
It's easier to go fine grained later but for now it's probably simpler to have a single option to control all built-in auto instrumentation which will be on by default (anyway tracing sample rate must be set to start getting data in)

**Comment by philipphofmann** [comment]
We agreed to call the flag `enableAutoPerformanceTracking` to control both UIViewController and HTTP tracing.

**Comment by philipphofmann** [comment]
Please also update the [docs](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/) accordingly.
