### ISSUE TITLE
reportUserException in 7.x.x version

### ISSUE THREAD

**Issue by dyomin-d** [getsentry/sentry-cocoa#1143]
### Issue

I have upgraded Sentry version from 4.x.x to 7.x.x. One of the parts of my code consisted of the following command:
```
Client.shared?.reportUserException(
                "",
                reason: reason,
                language: "",
                lineOfCode: "",
                stackTrace: stackTrace,
                logAllThreads: true,
                terminateProgram: true
            )
```
The main idea was to crash the app once the event is sent. However, there are no alternatives of this function in the newest version. If I use just `SentrySDK.crash() `, it won't send my custom error. Let me know how I may implement the same logic with the current version or please add this possibility in a new version.

**Comment by philipphofmann** [comment]
Hi, maybe `SentrySDK.captureException()` is what you are looking for?

**Comment by dyomin-d** [comment]
Thank you for the comment. I am currently using `SentrySDK.capture(exception: )` , however:
1. It isn't possible to crash the app during the capturing. 
2. Also, I can't set language, stackTrace and etc. properly, only via setExtras but in fact it doesn't pass the data like it has been earlier.

**Comment by philipphofmann** [comment]
If you want to crash the app you can use `SentrySDK.crash()`. To add context to an event, please make use of the Scope. For more details please read our [migration guide](https://docs.sentry.io/platforms/apple/migration/#capturemessage-with-tagsenvironmentextra).

**Comment by philipphofmann** [comment]
I consider this question as answered. Feel free to open the issue again.

**Comment by dyomin-d** [comment]
I am afraid that` SentrySDK.crash()` doesn't fulfill our needs. It just crashes the app with default logs. However, I have used reportUserException with crash inside for different purposes e.g. get the breadcrumbs, stackTrace.  

You may check the differences how it worked on 4.X.X version and the one with `SentrySDK.crash()`

**Comment by philipphofmann** [comment]
Hey @dyomin-d, 

the whole SDK concept changed a lot from 4.x.x to 7.x.x. You don't need to specify, the reason, language, lineOfCode, stackTrace, and logAllThreads anymore, if you enable `SentryOptions.attachStacktrace`, which is enabled by default when using `captureException`. If you want to make sure, that your event is sent before crashing you would have to call `SentrySDK.flush()`, which we didn't implement yet. You can upvote here https://github.com/getsentry/sentry-cocoa/issues/1013 to give this a higher priority.

**Comment by philipphofmann** [comment]
Maybe you can describe your use case a bit better so I can maybe point out another solution. I don't fully understand why you want to terminate your application after you captured an error.
