### ISSUE TITLE
Add Dependency Container

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1146]
We currently use multiple instances of `SentryDefaultCurrentDateProvider`, `SentryCrashAdapter`, etc., across the SDK, while we could only use one to minimize the memory footprint. So let's fix this by adding some dependency container that returns only one instance of these classes.

**Comment by bruno-garcia** [comment]
Couldn't we get around with a singleton pattern for those adapters?
Basically this: https://github.com/getsentry/sentry-dotnet/blob/1c04f4c610758e95160b1c8d000951ef5b318275/src/Sentry/Internal/AppDomainAdapter.cs#L19-L26

**Comment by philipphofmann** [comment]
We agreed in https://github.com/getsentry/sentry-cocoa/pull/1155 to use the singleton pattern instead.
