### ISSUE TITLE
Fix saving app state

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1149]
Don't only update the app state in SentryOutOfMemoryTracker. If this integration is removed, the app start tracking doesn't work properly.

**Comment by philipphofmann** [comment]
We could create an extra integration for storing the app state and `SentryOutOfMemoryTracker` would only read the app state.

**Comment by kevinrenskers** [comment]
> We could create an extra integration for storing the app state

Doesn't that just move the problem, not fix it? Then that new integration might be removed. 🤔

Or would it be an integration that users can't enable/disable, we automatically enable it if OOM or SentryAppStartTracker is enabled? (There are no other bits and pieces that need the app state, right?)

**Comment by philipphofmann** [comment]
Maybe then, not an extra integration. Another class that both `SentryOutOfMemoryTracker` and `AppStartTracker` use.
