### ISSUE TITLE
Unable to build SDK for tvOS on arm64

### ISSUE THREAD

**Issue by NachoSoto** [getsentry/sentry-cocoa#1156]
### Environment

CocoaPods:
`pod 'Sentry', '~> 7.1'`

Which SDK and version?
`Sentry 7.1.3`

### Steps to Reproduce

Archiving my app, Sentry fails to build using CocoaPods for tvOS.

### Actual Result

<img width="488" alt="Screen Shot 2021-06-07 at 14 14 28" src="https://user-images.githubusercontent.com/685609/121015151-f25cef80-c79a-11eb-95b1-ea5a128051db.png">

**Comment by philipphofmann** [comment]
I just tried it with an empty sample and it works for me. This is my Podfile
```ruby
platform :tvos, '14.0'
use_frameworks! 

target 'tvOS-Cocoa' do
    pod 'Sentry'
end
```

Can you, @NachoSoto, maybe give us more context, so we can reproduce your issue.

**Comment by NachoSoto** [comment]
That's exactly my set up. Using `Xcode 12.5 (12E262`. I wonder if something is messed up in my environment?

**Comment by philipphofmann** [comment]
I use `Xcode 12.5 (12E262)` as well. Which mac and macOS are you on?

**Comment by NachoSoto** [comment]
<img width="313" alt="Screen Shot 2021-06-07 at 16 17 01" src="https://user-images.githubusercontent.com/685609/121032686-cbf38000-c7ab-11eb-8b3c-398a8f9ef5db.png">

**Comment by philipphofmann** [comment]
Similar to mine, so the Mac and macOS shouldn't be the problem.

**Comment by NachoSoto** [comment]
Are you building for `arm64` though? I only noticed this when I archived "Any tvOS device":

<img width="592" alt="Screen Shot 2021-06-07 at 16 25 36" src="https://user-images.githubusercontent.com/685609/121034040-feea4380-c7ac-11eb-85a1-90443727709a.png">

**Comment by philipphofmann** [comment]
Yes, I am building for arm64. Your first screenshot complains when compiling for `arm64e`, which confuses me because this works for iOS. It looks like we are not reading the values correctly from `darwin_arm_thread_state64` in [SentryCrashCPU_arm64.c](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c). 

Do you have a special setup for your project? Can you try it with a fresh, clean sample project?

**Comment by NachoSoto** [comment]
Well yeah, `arm64e`. 
> It looks like we are not reading the values correctly from `darwin_arm_thread_state64` in `SentryCrashCPU_arm64.c`.

That would explain the issue then?

---

I'll try in a clean project as soon as I can:
```
The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.
```
😜

**Comment by NachoSoto** [comment]
Okay I found the issue. I still had this hack in my `Podfile`:
```
config.build_settings['ARCHS'] = '$(ARCHS_STANDARD_64_BIT)'
```

Which was making it build for `arm64e`. I disabled that for `tvOS` dependencies and it all works now.
Thanks for your pointer and your help!
