### ISSUE TITLE
Add session id to events and transactions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1161]
Set the session_id as a tag in events. This will allow us to see all events that happened during a session.

Related: https://github.com/getsentry/sentry-java/issues/1416

**Comment by philipphofmann** [comment]
This adds high cardinality and might be closed cause of that.

**Comment by bruno-garcia** [comment]
Last we talked with @mitsuhiko we were leaning towards not adding this

**Comment by bruno-garcia** [comment]
We decided not to do this due to the high cardinality value and low impact
