### ISSUE TITLE
feat: Support custom frame rate for FrameRenderMeasuring

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1165]
The preferred frame rate can be changed with [preferredFramesPerSecond](https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond) on the `CADisplayLink`. We could check the preferredFramesPerSeconds and adapt the desired frame rate in SentryFramesTracker accordingly.

It might be worth checking out other ways of defining custom frame rates as well, see https://developer.apple.com/library/archive/technotes/tn2460/_index.html. Maybe it makes sense to offer a way to configure the current frame rate.

**Comment by bruno-garcia** [comment]
Seems like a nice to have. I wonder if this affects many users. Lets see if we get any 👍 on this issue from users that are affected by this

**Comment by philipphofmann** [comment]
As preferredFramesPerSecond is deprecated now https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond, this is an edge case and nobody ever asked for this feature, we close it.

**Comment by philipphofmann** [comment]
When a user would use its own [preferredFramesPerSecond](https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond) on the CADisplayLink, like this

```Swift
let displaylink = CADisplayLink(target: self, selector:#selector(step))
displaylink.add(to: .current, forMode: .default)
displaylink.preferredFramesPerSecond = 30
    
func step(displaylink: CADisplayLink) {
    let actualFramesPerSecond = 1 / (displaylink.targetTimestamp - displaylink.timestamp)
    print(actualFramesPerSecond)
}
```

Our `CADisplayLink` used in the `SentryFramesTracker` still gets 60 fps by using `let actualFramesPerSecond = 1 / (displaylink.targetTimestamp - displaylink.timestamp)`. In order to make this work, we would need to provide an option.
