### ISSUE TITLE
Update Package.swift to resolve SPM warnings

### ISSUE THREAD

**Issue by rshimoda** [getsentry/sentry-cocoa#1166]
If Sentry is integrated into Xcode project via SPM, there are 4 warnings that are caused by the following part of `Package.swift` file:
```
.target(
            name: "Sentry",
            path: "Sources",
            **exclude: [
                "Samples", 
                "scripts",
                "Tests",
                "Utils"
            ],**
            sources: [
                "Sentry/",
                "SentryCrash/"
            ],
```

As of version 7.1.3, there aren't any sub-directories listed in `exclude` in `Sentry/` and thus they cannot be found. 
I suggest removing the `exclude` part of "Sentry" target (in `Package.swift`) to resolve these warnings.

Thanks for reading and your attention!

Please reach me for more details if needed, I'm glad to help!

**Comment by philipphofmann** [comment]
Was fixed with https://github.com/getsentry/sentry-cocoa/pull/1169
