### ISSUE TITLE
Sanitize Event.context

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1189]
The `SentryEvent.context` is [not sanitized](https://github.com/getsentry/sentry-cocoa/blob/2bfbbcdc11f84efd54498120e882d42e8bedd30e/Sources/Sentry/SentryEvent.m#L133) during serialization. Anybody could throw garbage on `SentryEvent.context`, which is not properly serialized then. We could fix this by calling [`sentry_sanitize`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/NSDictionary+SentrySanitize.h) on it.

**Comment by kevinrenskers** [comment]
This was done quite some time ago :)

https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryEvent.m#L142
