### ISSUE TITLE
sentry 6.x report crash when the app is manually killed

### ISSUE THREAD

**Issue by Luffy19960106** [getsentry/sentry-cocoa#1191]
### Environment

iOS

Which SDK and version? 

iOS  6.0.11

### Steps to Reproduce

I manual kill App, and then senty report a crash, like this:
SIGABRT: xxx > xxx(487,0x108ad1840) malloc: *** error for object 0x10babac00: pointer being freed was not allocated

but is not crash or wild pointer, I just kill App

and when I use sentry 5.x, I do not have this problem。I only meet this problem when I upgrade sentry from 5.x to  6.0.11

**Comment by philipphofmann** [comment]
Hey @Luffy19960106, 
Thanks for reaching out to us. Can you give us a bit more context on when this happens, please? 
Can you try updating to the latest version of 6.x and let us know if the problem is still there?

**Comment by RenatoSerra22** [comment]
Having the exact same issue in React native iOS https://github.com/getsentry/sentry-react-native/issues/1633

**Comment by Luffy19960106** [comment]
sorry，I final positioning is the issue of repeated release in C code.
