### ISSUE TITLE
Set synthetic field 

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1192]
The [exception interface](https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism) of the event payload defines a field `synthetic`, which doesn't exist in the SDK. This messes up grouping and should be added to the SDK. Since this has an impact on grouping, we have to bump a major for this.

**Comment by marandaneto** [comment]
this field should also be set to `true` whenever there's a stack trace, eg, segfault etc

**Comment by philipphofmann** [comment]
Maybe talk to @untitaker before shipping this.

**Comment by untitaker** [comment]
greetings. in which cases do you want to set the field? I believe setting it in all cases is wrong.

**Comment by philipphofmann** [comment]
I can't remember why I created this issue. If you tell me we shouldn't use the field, I'm happy to close the issue.

**Comment by untitaker** [comment]
Ah right. So we have two classes of exceptions in cocoa as far as I remember:

1. the ones where the current thread's stacktrace is reported as exception stack (nserror?)
2. genuine exceptions that actually hold a stacktrace produced from the exception bubbling up (nsexception?)

number (1) is the case where I believe we should set synthetic

we currently detect nserror on the server and set synthetic ourselves, but I believe the SDKs should set this property themselves, because this approach of doing a bunch of pattern-matching on the server doesn't scale with amount of platforms

**Comment by marandaneto** [comment]
> I can't remember why I created this issue. If you, @untitaker, tell me we shouldn't use the field, I'm happy to close the issue.

This issue came up after talking to @mitsuhiko 
Native events should set the `synthetic` field when captured by signal handlers.
The reason is described in the [docs](https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism).

**Comment by philipphofmann** [comment]
Thanks, @marandaneto and @untitaker for the info.

**Comment by philipphofmann** [comment]
Setting `synthetic=true` for NSErrors breaks grouping by NSErrors domain and code. @untitaker, where on the server do you think you set `synthetic=true` for NSError?

According to the [develop docs](https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism)

> Sentry will then try to use other information (top in-app frame function) rather than exception type and value in the UI for the primary event display.

We definitely don't want this for NSError. We want domain and code for primary event display. I currently can't think of any events where we would have to set `synthetic=true`. Maybe MetricKit events could use that field.

**Comment by untitaker** [comment]
@mitsuhiko @danielkhan 

I think we can close this. NSError is indeed not a synthetic exception, and the server does not detect it as synthetic exception.

**Comment by marandaneto** [comment]
This item came from @mitsuhiko and it was not related to `NSError`, I don't remember exactly which type of exceptions in Cocoa should be marked as `synthetic` tho.

**Comment by philipphofmann** [comment]
We didn't find any places to set the synthetic field in the SDK. MetricKit events will use the `synthetic` field. According to @mitsuhiko, grouping has room for improvement as we receive complaints about it through customer support regularly, which is unrelated to this issue.
