### ISSUE TITLE
Remove default MIME content type for attachment

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1196]
The SDK sets the default MIME content type to `application/octet-stream`, see https://github.com/getsentry/sentry-cocoa/blob/dd9501e8903260019f5b0fe05e73f25093201df2/Sources/Sentry/SentryAttachment.m#L6
The content_type is optional for the [envelope item attachment spec](https://github.com/getsentry/sentry-cocoa/blob/dd9501e8903260019f5b0fe05e73f25093201df2/Sources/Sentry/SentryAttachment.m#L6) and the backend defaults to `application/octet-stream` anyways. Therefore we can remove setting the default on the client-side and let the backend set the default instead.

**Comment by brustolin** [comment]
Solved by #2443
