### ISSUE TITLE
HTTP Request Breadcrumbs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1197]
With https://github.com/getsentry/sentry-cocoa/pull/1178 we add auto performance instrumentation for HTTP requests. Having this in place it should be rather "easy" to add breadcrumbs for HTTP requests as this is an [expected feature](https://develop.sentry.dev/sdk/features/#http-client-integrations) for SDKs.

**Comment by bruno-garcia** [comment]
Makes sense to me. It's just a one-liner (or in Objective-C, a 34 liner) 

Already done in Dart:

https://github.com/getsentry/sentry-dart/blob/679dce91d23ebcf2c0ee405add942685c32d3a20/dart/lib/src/http_client/sentry_http_client.dart#L100-L102

And OkHttp also:
https://github.com/getsentry/sentry-java/blob/aca78d9ca024c75225e59c36e35622055d2f6cbf/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L53-L60

Seems like we are not doing that on .NET: https://github.com/getsentry/sentry-dotnet/blob/00be88cb4be7f190e54694dcb836b6dd38eb6941/src/Sentry/SentryHttpMessageHandler.cs

One point to discuss is the idea of overlaying crumbs on the span list (time series) as 'marker span' (the timestamp works as a start and end timestamp so 0ms).
If we go that route it would be better to avoid adding them, but at the same time, in the event of an error, we'd want to get that information.

**Comment by lucas-zimerman** [comment]
I didn't notice on the above SDKs nor the doc, but some SDKs add the status code to the Request breadcrumb and I think that's a nice addition to the logged information.

Example from an Angular application:
![image](https://user-images.githubusercontent.com/8229322/125086153-b8d11a00-e0a1-11eb-83e1-807a521c08f7.png)

**Comment by bruno-garcia** [comment]
we definitely need the response status code when available. Just saying there was an HTTP request without saying the result of it is very limited

**Comment by bruno-garcia** [comment]
`status_code` added to spec, see getsentry/develop#376
