### ISSUE TITLE
Method to get the app start measurement afterwards for Hybrid SDKs

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-cocoa#1208]
We will need a method, maybe `getAppStartTime`, that can be called from hybrid SDKs sometime regardless of the init call, that is called to get the app start measurement.

This would include:
1. The app start type (warm, cold, etc)
2. The app start initial time
3. The app start finish time

**Comment by philipphofmann** [comment]
This should be easy. I can expose that information in `PrivateSentrySDKOnly`.
