### ISSUE TITLE
Compile failure with C99 (with suggested patch)

### ISSUE THREAD

**Issue by venkatd** [getsentry/sentry-cocoa#1210]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
7.1.3

### Steps to Reproduce
Try to compile any app on Sentry with C99 enabled

### Expected Result
It should compile and run the app as expected

### Actual Result
It gets stuck with a compile error:

I am trying to compile my Flutter app. It fails with the following error:
```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
/Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:29:9: warning: implicit declaration of function 'free' is invalid in C99 [-Wimplicit-function-declaration]
        free(bt);
        ^
/Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:29:9: warning: this function declaration is not a prototype [-Wstrict-prototypes]
/Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:29:9: error: conflicting types for 'free'
In module 'Darwin' imported from /Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashThread.h:34:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/malloc/_malloc.h:42:7: note: previous declaration is here
void     free(void *);
         ^
/Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:131:41: warning: implicitly declaring library function 'malloc' with type 'void *(unsigned long)' [-Wimplicit-function-declaration]
    sentrycrash_async_backtrace_t *bt = malloc(sizeof(sentrycrash_async_backtrace_t));
                                        ^
/Users/venkat/code/turtle-frontend/packages/turtle_app/macos/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:131:41: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
3 warnings and 1 error generated.
note: Using new build system
note: Planning build
note: Constructing build description
** BUILD FAILED **
```

If I add `#include <stdlib.h>` to `SentryHook.c`, the compile error goes away. I assume this is because with `C99` enabled, `free` can't implicitly be referenced. It has to be imported from `stdlib.h`

Would it be safe/acceptable to explicitly add this import so that this library can build on my machine? This missing import is the part in the entire codebase that causes compilation to fail.

Here's what the patch I'm using as a workaround:
```
--- Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c
+++ Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c
@@ -6,6 +6,7 @@
 #include <execinfo.h>
 #include <mach/mach.h>
 #include <pthread.h>
+#include <stdlib.h>
 
 static bool hooks_active = true;
 ```

In my `post_install` hook in the `Podfile` I run `patch -p0 < Diffs/SentryHook.m.diff` to ensure my app is able to compile with Sentry enabled.

**Comment by philipphofmann** [comment]
Thanks for opening up this issue, @venkatd. I have trouble reproducing this. When changing the C Language Dialect to C99 in Xcode for our sample projects, the compilation succeeds. How do you include Sentry in your Flutter project?

**Comment by venkatd** [comment]
Here is a gist with our pubspec, Podfile, and their respective lock files:

https://gist.github.com/venkatd/6467e733ee718aca874bb6425e41bebf

Would there be anything else that could help you reproduce?

And putting this error aside, is `#include <stdlib.h>` an acceptable code enhancement?

I noticed it's included in other parts of this codebase, so perhaps it's not a bad idea to explicitly include stdlib when functions from there are being used? In this case, `free` is part of `stdlib` but it's not being explicitly imported.

In XCode, clicking jump to definition when it's explicitly imported takes me right to the definition. If there is no explicit import, I get a menu to disambiguate where to jump to:

![image](https://user-images.githubusercontent.com/220686/124649064-9fd82700-de5d-11eb-95d5-665966dcb656.png)

**Comment by brustolin** [comment]
@venkatd any reason you are using the cocoa version of SentrySDK instead of the Dart version?

**Comment by venkatd** [comment]
@brustolin we are using the Flutter version, but in order to allow for native stack trace reporting, the official Flutter version internally uses the cocoa version on iOS and MacOS platforms.

**Comment by philipphofmann** [comment]
Thanks for the explanation, @venkatd. Adding `#include <stdlib.h>` is not the problem. I want to find a way to reproduce it, so we can find a way to test this in CI, so it doesn't happen in the future again. Fixing this is easy, but if I don't add validation now, I'm sure we won't do it soon.

**Comment by venkatd** [comment]
@philipphofmann good point.

What could I do to help reproduce this? Next week I could spend some time to see if I can figure out what compile command is bring run from the cli.

I noticed that the library in our XCode was marked as glibc. Perhaps that target may help reproduce? I'm confused because it was a C99 error.

Also noticing that there's the flag `-Wimplicit-function-declaration` that triggered the error. Perhaps that flag is necessary? Or some targets have that enabled by default?

**Comment by philipphofmann** [comment]
I played around a bit with compiler flags and didn't find a way to reproduce it. Anyway, let's just add the import for now to fix the issue.

**Comment by venkatd** [comment]
Thanks for the fix @philipphofmann !
