### ISSUE TITLE
Discover whether SDK is started or not.

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#1218]
With SentrySDK's new `close()`, it is now possible to shut down Sentry and start it at will to conform to user preferences and consent.  That's great.

However, there is no way to find out what Sentry's current state is to determine whether it needs to be started, or is already running.

This request is related to #809 and the closed #700.

Finally, the API is currently a little ambiguous. There is `SentrySDK.close()` and there is also passing a `nil` to the `dsn`, and there is also setting `enabled` to `false`. Either the API should be unambiguous (eg. make `dsn` non-optional and remove `enabled`) or clarify the distinction between them and `close()`.

**Comment by philipphofmann** [comment]
Thanks, @lhunath for opening up this issue. Indeed there is no straightforward way to identify whether the SDK is started/enabled or not. We can add `SentrySDK.isEnabled`, like we have it in [Java](https://github.com/getsentry/sentry-java/blob/59328b0463bd1070e7a31143fcc3916144352098/sentry/src/main/java/io/sentry/Sentry.java#L60-L62), or [.NET](https://github.com/getsentry/sentry-dotnet/blob/1b7e3c8740d3096391a9f8c1b7ee94d68a88ba2b/src/Sentry/SentrySdk.cs#L146).
