### ISSUE TITLE
Out of memory termination should include whether the app was in the foreground or background.

### ISSUE THREAD

**Issue by CraigSiemens** [getsentry/sentry-cocoa#1221]
The criticality of the app being terminated can be very different based on whether it was in the foreground or the background and the type of app.

For an app that does no background processing, being terminated while in the background generally means the user has opened up more apps that the system would like to give memory to. So while it'd be nice for an app to live forever in the background, it can be out of the apps control.

However if the app is terminated while it's in the foreground, that should only happen if the app is actively using too much memory. In that cause the severity of the termination is way higher since the user would see it as a crash.

---

Since v7.0 added out of memory reporting, it'd be really nice to be able to tell these two situations apart.

It'd also be nice if there were options that could customize the level issues use based on the app state. So an app could set foreground OOM terminations to be `fatal`, but background ones could be `info`.

**Comment by philipphofmann** [comment]
OOMs are only reported if the app was in the foreground; see [docs](https://docs.sentry.io/platforms/apple/configuration/out-of-memory/). We can't reliably detect OOMs if the app was in the background.
