### ISSUE TITLE
Uploading dSYM never completes

### ISSUE THREAD

**Issue by maharjanaman** [getsentry/sentry-cocoa#1227]
### Environment

How do you use Sentry?
Tried on both,
sentry.io &
Self-hosted/on-premise version 21.6

Which SDK and version?
Swift 5

I follow steps from [sentry doc](https://docs.sentry.io/platforms/apple/guides/ios/) and am using `sentry-cli` to upload dSYM. The upload script provided runs but the upload never seems to be completed. I've check debug files on project settings in sentry but it's empty.

<img width="356" alt="Screen Shot 2021-07-16 at 12 08 30" src="https://user-images.githubusercontent.com/14164484/125903545-cbd379da-21bb-4622-807c-382bac77c477.png">

I chose to go with `Without Bitcode` even when I've bitcode enable on the project. Will this cause an issue?

**Comment by philipphofmann** [comment]
Hey @maharjanaman, did you also set the `SENTRY_URL` environment variable to instruct the tool to connect to your server instead of sentry.io, as explained in the last section of [the docs](SENTRY_URL environment variable to instruct the tool to connect to your server)?

**Comment by philipphofmann** [comment]
It seems like people using our [Fastlane Plugin](https://github.com/getsentry/sentry-fastlane-plugin/issues/39) have a similar issue. This seems to be related to https://github.com/getsentry/sentry-cli/issues/988

**Comment by philipphofmann** [comment]
@maharjanaman, it also doesn't work for me when trying it in Xcode, but it works when I upload the dSYMs from the command line like this: `sentry-cli upload-dif macOS-Sample.xcarchive`. As this seems to be an issue with sentry-cli, let's move the discussion to https://github.com/getsentry/sentry-cli/issues/988.
