### ISSUE TITLE
I need to send crash logs to multiple different DSNs, but only one can be set here

### ISSUE THREAD

**Issue by 18233135268** [getsentry/sentry-cocoa#1232]
The documentation for the iOS configuration doesn't seem to outline how to use multiple DSNs.
  NSDictionary *dic = @{
        @"dsn":@"",
        @"debug":@"false"
    };
   [SentrySDK startWithOptions:dic];
The reasoning behind wanting multiple DNS is because I need to send crash information to multiple DSNs.

Is this possible?

**Comment by philipphofmann** [comment]
Yes, this is possible, but you have to interact with Hubs instead of the static SDK. The downside is that when manually initializing the hub, you lose device context data. We are aware of this issue https://github.com/getsentry/sentry-cocoa/issues/1104, but I can't give you an ETA for fixing this.

```Swift
let options1 = Options()
options1.dsn = "myFirstDSN"
let hub1 = SentryHub(client: Client(options: options1), andScope: nil)
hub1.capture(message: "hello")

let options2 = Options()
options2.dsn = "mySecondDSN"
let hub2 = SentryHub(client: Client(options: options2), andScope: nil)
hub2.capture(message: "hello")
```

**Comment by philipphofmann** [comment]
I forgot to mention, that all the integrations, like breadcrumbs, release health, hard crashes, OOM, etc. only work with the static API as we install them there.

**Comment by philipphofmann** [comment]
As no further comments were made, I consider this question as answered. Please feel free to open it again.
