### ISSUE TITLE
Add more device context

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1235]
Events from iOS have less device context than, for example, events from Android. We can add more.

## iOS
```JSON
"device": {
      "family": "iOS",
      "model": "iPhone13,2",
      "model_id": "D53gAP",
      "memory_size": 3883876352,
      "free_memory": 88358912,
      "usable_memory": 2271002624,
      "storage_size": 63870980096,
      "boot_time": "2021-07-19T18:15:30Z",
      "timezone": "CEST",
      "type": "device"
}
```

## Android

```JSON
"device": {
      "name": "Pixel 2 XL",
      "family": "Pixel",
      "model": "Pixel 2 XL",
      "model_id": "RP1A.201005.004.A1",
      "battery_level": 100.0,
      "orientation": "portrait",
      "manufacturer": "Google",
      "brand": "google",
      "screen_density": 3.5,
      "screen_dpi": 560,
      "online": true,
      "charging": true,
      "low_memory": false,
      "simulator": false,
      "memory_size": 3839954944,
      "free_memory": 2134429696,
      "storage_size": 55782412288,
      "free_storage": 46677245952,
      "boot_time": "2021-07-19T11:13:52.575Z",
      "timezone": "Europe/Vienna",
      "archs": [
        "arm64-v8a",
        "armeabi-v7a",
        "armeabi"
      ],
      "battery_temperature": 30.6,
      "connection_type": "wifi",
      "id": "9cd59ebb-583b-474b-8ad1-15af30ba62d1",
      "language": "en_US",
      "screen_height_pixels": 2712,
      "screen_width_pixels": 1440,
      "type": "device"
}
```

**Comment by bruno-garcia** [comment]
Unity also has some things that might be unique to that SDK.
Ultimately we try to keep those documented/aligned here:

https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context

We could benefit from a table SDK x Spec so we can spot anything we're missing in the spec and opportunities for new info in SDKs.

**Comment by bruno-garcia** [comment]
Some potential reference (cross platform libs):

https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials

https://github.com/fluttercommunity/plus_plugins

**Comment by philipphofmann** [comment]
The following repo might be helpful for getting the connection type https://github.com/Isuru-Nanayakkara/Reach

**Comment by bruno-garcia** [comment]
This came up in the context of React Native, a work around there was:

Use a library such as:  https://github.com/react-native-netinfo/react-native-netinfo and use our SDK to add the data. Like:
```
NetInfo.addEventListener(state => {
  Sentry.setTag("connection_type", state.type);
  Sentry.setTag("is_connected", state.isConnected);
});
```

**Comment by kevinrenskers** [comment]
iOS:

``` JSON
"device": {
  "family": "iOS",
  "model": "iPhone13,1",
  "model_id": "D52gAP",
  "arch": "arm64",
  "memory_size": 3863298048,
  "free_memory": 84934656,
  "usable_memory": 2587443200,
  "storage_size": 63870980096,
  "boot_time": "2022-09-12T05:45:21Z",
  "locale": "en_NL",
  "type": "device"
},
```

But we also have this:

``` JSON
"culture": {
  "calendar": "Gregorian Calendar",
  "display_name": "English (Netherlands)",
  "is_24_hour_format": true,
  "locale": "en_NL",
  "timezone": "Europe/Amsterdam",
  "type": "culture"
},
```

Most interesting to add:

- battery_level
- orientation
- charging
- screen_height_pixels
- screen_width_pixels
- free_storage

Not so useful:

- name: do you really need to know the name of the device? Plus that usually has PII, like "Kevin Renskers' iPhone"
- manufacturer and brand: always Apple anyway

Not sure about usefulness or feasibility:

- low_memory: we report the available memory, but how would we know if that's low or not? 
- online / connection_type: do we want to use Apple's Reachability class for this? It's quite low level code, and not the most reliable in my experience. Most people use a third-party ObjC wrapper for this stuff.
- screen_density: there is no API for this for iOS, so we'd have to hardcode them based on device type
- battery_temperature: impossible, there is no public API for this, and since iOS 10 beta 1 [access to raw data is removed as well](https://github.com/eldade/UIDeviceListener)
- screen_dpi: we can get the scale, but not the DPI without hardcoding them based on device type

**Comment by philipphofmann** [comment]
> online / connection_type: do we want to use Apple's Reachability class for this? 
We definitely don't want to add a third party library for such a small feature. Either we use their approach and give them credit, or we use the Apple's Reachability class, or we don't do it.

> screen_density
I think it's not that important on iOS as the variety of devices is not so big. You usually know what the density is.

> battery_temperature
Let's drop it then.

> screen_dpi
See screen_density.

**Comment by chaseklingelzen** [comment]
Hi @kevinrenskers, I saw [your pr](https://github.com/getsentry/sentry-cocoa/pull/2190) was merged. I'm specifically interested in the device properties for iOS. 

I am particularly interested in free_memory and usable_memory from this blob you added above:

```JSON
"device": {
  "family": "iOS",
  "model": "iPhone13,1",
  "model_id": "D52gAP",
  "arch": "arm64",
  "memory_size": 3863298048,
  "free_memory": 84934656,
  "usable_memory": 2587443200,
  "storage_size": 63870980096,
  "boot_time": "2022-09-12T05:45:21Z",
  "locale": "en_NL",
  "type": "device"
},
```

When I look at a Sentry issue (see screenshot below), I do see usable memory, but I do not see free memory. Do we have access to free memory? 

<img width="1294" alt="Screenshot 2024-01-04 at 5 03 04 PM" src="https://github.com/getsentry/sentry-cocoa/assets/94926620/463f1f29-d797-4409-b0e0-aa1c89d5eae9">

**Comment by philipphofmann** [comment]
I see free_memory being displayed as `Free Memory` in the screenshot below.

![CleanShot 2024-01-05 at 11 16 56@2x](https://github.com/getsentry/sentry-cocoa/assets/2443292/f11a9b44-2e2a-4db8-b34e-ad48e7f868ae)

It should be displayed, @chaseklingelzen. FYI, @kevinrenskers is not working anymore on this repo.

**Comment by chaseklingelzen** [comment]
> I see free_memory being displayed as `Free Memory` in the screenshot below.
> 
> ![CleanShot 2024-01-05 at 11 16 56@2x](https://private-user-images.githubusercontent.com/2443292/294460757-f11a9b44-2e2a-4db8-b34e-ad48e7f868ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Njk3MjgsIm5iZiI6MTcwNDQ2OTQyOCwicGF0aCI6Ii8yNDQzMjkyLzI5NDQ2MDc1Ny1mMTFhOWI0NC0yZTJhLTRkYjgtYjM0ZS1hZDQ4ZTdmODY4YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTU0MzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJjN2VlYzk3NzJjZDI4MTI4NzY4YjJjMWE2YmNhNTM3NDdkZjRlOGU0NjczYzA0ODE2YzFmODA4Y2Y2NjExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KUu7hnn7BR-f-OxJtXUTDZnyjbov8yX0WgPDtUa1aN4)
> 
> It should be displayed, @chaseklingelzen. FYI, @kevinrenskers is not working anymore on this repo.

Hi @philipphofmann thanks for letting me know about Kevin. Interesting... I do see Free Memory on Sentry issues that are not watchdog termination issues. I suppose it would make sense that free memory doesn't show on watchdog termination issues because the issue is related to being out of memory. Does that seem reasonable as to why it isn't showing up on watchdog termination issues?

**Comment by philipphofmann** [comment]
> I suppose it would make sense that free memory doesn't show on watchdog termination issues because the issue is related to being out of memory. Does that seem reasonable as to why it isn't showing up on watchdog termination issues?

Yes, exactly. I opened a PR to clarify that in the docs https://github.com/getsentry/sentry-docs/pull/8847.
