### ISSUE TITLE
sentry-react-native fails to compile because of syntax issues

### ISSUE THREAD

**Issue by sreuter** [getsentry/sentry-cocoa#1248]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native 2.6.0

### Steps to Reproduce

Add module to managed (Expo 42) project and run `yarn run:ios`.

### Expected Result

Build succeeds.

### Actual Result

Build fails.

```
› Compiling Pods/Sentry » SentryHook.c

❌  (ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:55:9)

  53 |     if (__atomic_fetch_add(&bt->refcount, -1, __ATOMIC_SEQ_CST) == 1) {
  54 |         sentrycrash__async_backtrace_decref(bt->async_caller);
> 55 |         free(bt);
     |         ^ implicit declaration of function 'free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  56 |     }
  57 | }
  58 | 


❌  (ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:55:9)

  53 |     if (__atomic_fetch_add(&bt->refcount, -1, __ATOMIC_SEQ_CST) == 1) {
  54 |         sentrycrash__async_backtrace_decref(bt->async_caller);
> 55 |         free(bt);
     |         ^ missing '#include <malloc/_malloc.h>'; declaration of 'free' must be imported from module 'Darwin.malloc._malloc' before it is required
  56 |     }
  57 | }
  58 | 


❌  (ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:55:9)

  53 |     if (__atomic_fetch_add(&bt->refcount, -1, __ATOMIC_SEQ_CST) == 1) {
  54 |         sentrycrash__async_backtrace_decref(bt->async_caller);
> 55 |         free(bt);
     |         ^ conflicting types for 'free'
  56 |     }
  57 | }
  58 | 


❌  (ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryHook.c:62:41)

  60 | sentrycrash__async_backtrace_capture(void)
  61 | {
> 62 |     sentrycrash_async_backtrace_t *bt = malloc(sizeof(sentrycrash_async_backtrace_t));
     |                                         ^ implicitly declaring library function 'malloc' with type 'void *' [-Werror,-Wimplicit-function-declaration]
  63 |     bt->refcount = 1;
  64 | 
  65 |     bt->len = backtrace(bt->backtrace, MAX_BACKTRACE_FRAMES);

› Compiling Pods/Sentry » SentryGlobalEventProcessor.m
› Compiling Pods/Sentry » SentryFrameRemover.m
› Compiling Pods/Sentry » SentryFrameInAppLogic.m
› Compiling Pods/Sentry » SentryFrame.m
› Compiling Pods/Sentry » SentryFileManager.m

› 4 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
```

**Comment by d-patira** [comment]
Any idea when will this be fixed?

**Comment by bruno-garcia** [comment]
Thanks for raising @d-patira 

What version of xcode do you have installed? And what is the min iOS version you are targeting?

**Comment by d-patira** [comment]
@bruno-garcia 
Xcode Version -> 11.4
iOS Deployment target: 10.0
I am not sure, whether we have the flexibility to share the repo link or zip package. Let me check and get back to you

**Comment by d-patira** [comment]
Also, Given below is one other commit, which dragged attention of our iOS developer:
https://github.com/getsentry/sentry-cocoa/pull/1224/commits/823864b0bdb2a2635e3c5247254ca21ec24dd267

@bruno-garcia 
I just needed your help in knowing about the next release plan, when will this fix be available?

**Comment by Swatinem** [comment]
```
missing '#include <malloc/_malloc.h>'; declaration of 'free' must be imported from module 'Darwin.malloc._malloc' before it is required
```

Maybe this is some kind of xcode specific issue, usually `malloc` and `free` come from `stdlib.h`, which is right there:

https://github.com/getsentry/sentry-cocoa/blob/1f9ec1815fa0fefff0cc5936e70b809b4127026e/Sources/SentryCrash/Recording/Tools/SentryHook.c#L9

**Comment by d-patira** [comment]
@Swatinem 
That include line was added as a part of below commit.
https://github.com/getsentry/sentry-cocoa/commit/823864b0bdb2a2635e3c5247254ca21ec24dd267
Will this commit be included in the latest version of sentry-react-native, 2.6.0 ?

**Comment by Swatinem** [comment]
You are absolutely right, I was a bit confused by which version is used where. So this either needs to roll forward, or has to be backported to a patch release.

**Comment by philipphofmann** [comment]
As pointed out, this should be fixed with https://github.com/getsentry/sentry-cocoa/commit/823864b0bdb2a2635e3c5247254ca21ec24dd267. This should be in the release 2.7.0 of React-Native, which is currently in beta. I think we plan to release this next week, but I can't guarantee that.
