### ISSUE TITLE
False Out Of Memory Crash Reports when using `exit(0)`

### ISSUE THREAD

**Issue by jweg29** [getsentry/sentry-cocoa#1252]
### Environment

How do you use Sentry?
Native iOS application

Which SDK and version?
cocoa 7.1.3

### Steps to Reproduce

1. Run code path in app that uses `exit(0)`

### Expected Result

Should not receive a Sentry Out Of Memory crash report since the application terminated expectedly and was not out of memory.

### Actual Result

Sentry generates an out of memory crash report.

![image](https://user-images.githubusercontent.com/1434000/127054630-b8b46282-d00a-4e10-bbfd-4e2ad48f3704.png)

**Comment by philipphofmann** [comment]
Why are you calling `exit(0)`? This will just close the app and looks like a crash to the user. According to [Apple](https://developer.apple.com/library/archive/qa/qa1561/_index.html), you shouldn't do this. Apple could reject your app because of that.

**Comment by jweg29** [comment]
It's related to an internal feature in our enterprise app that requires the application to restart. We prompt the user, the app terminates, and then when the app is restarted the feature is enabled.

**Comment by philipphofmann** [comment]
You could post a `UIApplicationWillTerminateNotification` as the SDK, then would assume the app terminated normally. The current problem is that we update the app state on a background thread, which we could also move to the main thread as the app is terminating anyways. Would that work for you?

**Comment by jweg29** [comment]
Yep that sounds like a workable solution
