### ISSUE TITLE
Make SpanContext Immutable

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1254]
The `SpanContext` is currently mutable which it shouldn't be. In [.NET](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/SpanContext.cs) it is not mutable. Furthermore, tags are duplicate in `Span` and `SpanContext`. They should be in the `Span` and be removed from the `SpanContext`.

**Comment by brustolin** [comment]
In .NET Span implements ISpanContext.
Maybe SpanContext in cocoa should became a protocol with only getters, and Span implements this protocol and add the setters?

**Comment by bruno-garcia** [comment]
@marandaneto fyi since we talked about this wrt to Dart

**Comment by brustolin** [comment]
Solved by #2408
