### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by underthestars-zhy** [getsentry/sentry-cocoa#1270]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
swift 5.4 centos

### Steps to Reproduce

1. I use centos
2. i run `swift build`

### Expected Result

nothing

What you thought would happen.

### Actual Result

```
/root/api/.build/checkouts/sentry-cocoa/Sources/SentryCrash/Reporting/Tools/SentryCrashCString.h:27:9: fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by philipphofmann** [comment]
Hi, @underthestars-zhy; thanks for reaching out to us. Unfortunately, we currently don't support Linux. We also don't have plans to add support soon. Please upvote if you want the support for Linux.

**Comment by stsandro** [comment]
Support for Linux would be really nice 😎.

I'm doing a lot with AWS Lambda. Currently most of my Lambda functions use Python as runtime, which is supported by the [Sentry Python SDK](https://docs.sentry.io/platforms/python/guides/aws-lambda/). There is support for writing Lambda functions in Swift via the [Swift AWS Lambda Runtime](https://github.com/swift-server/swift-aws-lambda-runtime). It works great, although it is still in alpha or even pre alpha. I have a handful of Swift Lambda functions running in production and they are doing fine. There is a lot of potential in this. Many App developers need some form of backend/server/API and being able to write this in Swift, while doing the monitoring with the same tool (Sentry) you already use for your app, would be awesome. Apple itself seems to be quite fond of running Swift Lambda functions as they hired one of the main developers of the Swift AWS Lambda Runtime and there is even a session of running Lambda functions with Swift from WWDC 2020 ([Use Swift on AWS Lambda with Xcode](https://developer.apple.com/videos/play/wwdc2020/10644/)).

What is the main blocker for Linux support?

**Comment by philipphofmann** [comment]
The blocker is that our SDK is mainly written in Objective-C and C and not Swift. The support for Objective-C on Linux is not the best, and we use plenty of libraries that are only available on Apple. For proper Linux and Windows support, we need some restructuring and rewrites of our SDK.

**Comment by philipphofmann** [comment]
> Vapor and the rest of the improvements and market adoption in the server-side Swift space

Thanks for the input, @Sherlouk. Would you happen to have any data backing this up?

**Comment by Sherlouk** [comment]
What data are you exactly asking for? 

I'm not suggesting Swift is competing with JavaScript for server-side language of the year - but the number of applications built in it continues to increase. 

Many companies including Sky, BBC, and Apple themselves are writing apps using Vapor (via Core Team)

Over 40% of Swift packages are now Linux compatible (via SwiftPackageIndex)

Amazon have their Lambda functions, and continue to put a lot of hard work into maintaining their SDKs with Linux support.

The size of the server-side working groups, and the number of the people registered for the community Discord is constantly growing.

It's impossible to deny that it isn't improving and relative adoption isn't increasing.

Support for Distributed Tracing is nearly at a complete v1 (but works elegantly even in its current form, with metrics and logging having great support for a while using OpenTelemetry, Prometheus and other tooling.

**Comment by philipphofmann** [comment]
To support Linux, we would need to do a significant rewrite and refactoring of our SDK, as already mentioned in https://github.com/getsentry/sentry-cocoa/issues/1270#issuecomment-924845327. We would need to refactor core components such as Hub, Client, Transport, Scope, RateLimiting, Tracer, Span, Transactions, etc. to Swift, structure the SDK in a way we have a plain Swift core library, and plugin in things like SentryCrash, UIViewController instrumentation, etc. depending on the platform. We are sorry to tell you that we are currently not at a point to put much effort into covering a relatively small market share especially compared to iOS. So we can be honest and transparent that this will not happen in the near future and close this issue. You can still upvote to let us know you would like to have this support, and maybe we change our minds in the future.

If anybody is motivated, you could write an implementation of a simple Swift-only SDK by following the unified API guidelines of our [development docs](https://develop.sentry.dev/sdk/unified-api/). We would be happy to support that initiative and might maintain such a repository in the future.
