### ISSUE TITLE
SDK doesn't send crash if a user field contains too much data

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1274]
### Environment

Cocoa SDK 7.2.0

### Steps to Reproduce

Put a string with 10 MB to the user.

```Swift
let user = Sentry.User(userId: "1")
let size = 1024 * 1024 / 10;
var longString = ""
for _ in 0...size {
    longString.append("h")
}
user.data = [ "extra_long": longString]
SentrySDK.setUser(user)
```

Then cause a crash.

### Expected Result

The SDK should discard the field and send the crash report to Sentry.

### Actual Result

The logs print
```
ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
ERROR: SentryCrashC.c (277): char *sentrycrash_readReport(int64_t): Failed to fixup report ID 1b800000
```

The crash report contains an error explaining the JSON data is too long.
```json
"sentry_sdk_scope": {
    "user": {
        "data": {
            "user": {
                "error": "Invalid JSON data: Data too long",
                "json_data": "{\"data\":{\"extra_long\":\"h ... h\"},\"email\":\"tony1@example.com\",\"id\":\"1\"}"
            }
        },
        "user": {

        }
    }
}
```

**Comment by philipphofmann** [comment]
We have a rate limit for events of [1 MB on Relay](https://develop.sentry.dev/sdk/envelopes/#size-limits). Maybe we should do some checks when adding any data and drop large data.

**Comment by marandaneto** [comment]
similar to https://github.com/getsentry/sentry-java/issues/910

**Comment by bruno-garcia** [comment]
This quarter we're (The web team /cc @rhcarvalho) are adding metrics to SDKs so we can figure out how much of a problem this is. We can go from there to prioritize this and pick the ideal solution.

**Comment by bruno-garcia** [comment]
We decided not to truncate it for a few reasons:

* The max size of the payload changes overtime 
* Truncating can affect the device performance negatively
* We can truncate user field but multiple other areas of the event can be the cultprit such as breadcrumbs
* The goal is to surface stats first so users can identify what areas are causing it and address the data before adding to Sentry's SDK
