### ISSUE TITLE
Testing out a sync tool

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1280]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by bruno-garcia** [comment]
didn't work 😢

**Comment by philipphofmann** [comment]
Best issue ever 😁
