### ISSUE TITLE
Auto UI Generated Transaction should have status OK

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1282]
### Environment

Sentry-Cocoa 7.2.2

### Steps to Reproduce

Let the SDK capture any auto UI instrumented transaction.

### Expected Result

Transaction finishes with status `OK`.

### Actual Result

Transaction finishes with status `unknown`.

**Comment by marandaneto** [comment]
yes, but only set to `SpanStatus.OK` if there is no status set -> https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java#L218-L223

**Comment by philipphofmann** [comment]
Please also update the screenshots for the documentation after merging this PR.

**Comment by philipphofmann** [comment]
Was fixed with https://github.com/getsentry/sentry-cocoa/pull/1439
