### ISSUE TITLE
Umbrella header for module 'Sentry' does not include header 'SentryScreenFrames.h' when building with SPM

### ISSUE THREAD

**Issue by mqln** [getsentry/sentry-cocoa#1283]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Cocoa SDK 7.2.2, Xcode 12.5

### Steps to Reproduce

When I try to install Sentry 7.2.2 via SPM, I get an error that the umbrella header doesn't include `SentryScreenFrames.h`.

Here's what my Package.resolved looks like:

```json
      {
        "package": "Sentry",
        "repositoryURL": "https://github.com/getsentry/sentry-cocoa",
        "state": {
          "branch": null,
          "revision": "a9c1f7fb5451cdaf414c1f4e02b609fa188c730b",
          "version": "7.2.2"
        }
```

### Expected Result

My project with Sentry would compile successfully.

### Actual Result

A series of fatal errors are encountered, seemingly stemming from the umbrella header not including `SentryScreenFrames.h`.

![image](https://user-images.githubusercontent.com/1429466/130759485-7bd90f0a-a788-41b4-8480-02973e92c2f9.png)

**Comment by philipphofmann** [comment]
Thanks, @mqln, for reporting this. We have a GitHub job, that should avoid such errors, but it doesn't fail, see https://github.com/getsentry/sentry-cocoa/runs/3410408117?check_suite_focus=true. I can reproduce this and will fix it.
