### ISSUE TITLE
Vulnerability issues in the source code Unchecked Return Value

### ISSUE THREAD

**Issue by nbadiganti** [getsentry/sentry-cocoa#1285]
### Source code Vulnerabilities
We came across few issues in the library code which might lead to app crashes or it does not check the return value from a method or function. 
It is recommended to add null checks in the below source code files, hence raising a bug issue.

Issue name - **Unchecked Return Value** 
https://cwe.mitre.org/data/definitions/252.html

**Sourcecode file & line number for the issue**
SentryCrashMonitor_Signal.c: 151
SentryCrashCachedData.c: 71
SentryCrashCachedData.c: 68
SentryCrashCachedData.c: 70
SentryCrashJSONCodecObjC.m: 126
SentryCrashFileUtils.c: 157
SentryCrashCachedData.c: 68
SentryCrashCachedData.c: 69
SentryCrashCachedData.c: 71
SentryCrashCachedData.c: 70
SentryCrashLogger.c: 291

**Comment by philipphofmann** [comment]
Can you maybe open up a PR for fixing these issues @nbadiganti?

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.
