### ISSUE TITLE
Versions 7.2.x cause crash - AVAggregateAssetDownloadTask does not support currentRequest property

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#1293]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
iOS via SPM all versions 7.2.x, prior versions work fine.

### Steps to Reproduce

1. Integrated Sentry iOS via SPM
2. Start an AVAggregateAssetDownloadTask

### Expected Result

Expected the app to not crash, like with every version below 7.2.0, for example 7.1.4 worked fine

### Actual Result

App crashes:

**Fatal | NSGenericException UIInputWindowController 
AVAggregateAssetDownloadTask does not support currentRequest property**

```
NSGenericException: AVAggregateAssetDownloadTask does not support currentRequest property
  ?, in __exceptionPreprocess
  ?, in objc_exception_throw
  ?, in _CFNetworkErrorGetLocalizedDescription
  ?, in -[SentryNetworkTracker urlSessionTaskResume:]
  ?, in __53+[SentryNetworkSwizzling swizzleURLSessionTaskResume]_block_invoke_2
...
(10 additional frame(s) were not displayed)

**Comment by bruno-garcia** [comment]
Does this happen with7.2.2? There were 2 bug fixed done due to sizzling releases in 7.2.0 and 7.2.1

**Comment by gabors** [comment]
Hi @bruno-garcia 
I tried all 7.2.x versions up to 7.2.3. 
They all crash.

**Comment by philipphofmann** [comment]
Thanks for reporting this @gabors 💯 .

**Comment by jsivanes** [comment]
Hello  I would like to wake up this bug, it's steel not working!
Have the same Crash on currentRequest from AVAggregateAssetDownloadTask

Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
iOS via CocoaPod all versions 7., prior versions work fine.

Steps to Reproduce

Start an AVAggregateAssetDownloadTask with aggregateAssetDownloadTaskWithURLAsset from AVAssetDownloadURLSession

Actual Result

App crashes:

Fatal | NSGenericException 
AVAggregateAssetDownloadTask does not support currentRequest property

**Comment by brustolin** [comment]
Hello @jsivanes.

Which version of the SDK are you using?

**Comment by jsivanes** [comment]
Sorry I'm on 7.5.4.

**Comment by brustolin** [comment]
Thanks for reporting this @jsivanes 
A solution is coming soon.

**Comment by gabors** [comment]
Is this specific to Cocoapods integration?

I'm using SPM and didn't see any crashes since it was initially fixed. 
But as far as I recall I have swizzling disabled.

**Comment by philipphofmann** [comment]
I think this was fixed with https://github.com/getsentry/sentry-cocoa/pull/1523 in `7.6.1` @jsivanes, please let us know if you still see the issue in `7.6.1.`.
