### ISSUE TITLE
7.2.4 app crash on launch on iOS 13.5

### ISSUE THREAD

**Issue by FelixHerrmann** [getsentry/sentry-cocoa#1296]
### Environment

Sentry-Cocoa 7.2.4

### Steps to Reproduce

Start app with Sentry SDK on iOS 13.5

### Expected Result

No crash.

### Actual Result

App crashes immediately, no issue with 7.2.3 on iOS 13.5.

7.2.4 works fine on iOS 14!

<img width="1171" alt="Bildschirmfoto 2021-08-31 um 06 05 21" src="https://user-images.githubusercontent.com/42500484/131440023-724fe459-2fac-44e2-be33-05de096534eb.png">

**Comment by philipphofmann** [comment]
Thanks for reporting this, @FelixHerrmann. Can you confirm that this only happens on a jailbroken device or also a normal iOS device with iOS 13.5?

**Comment by FelixHerrmann** [comment]
Normal too!

<img width="1170" alt="Bildschirmfoto 2021-08-31 um 07 40 42" src="https://user-images.githubusercontent.com/42500484/131448335-17ed5251-aff2-4cc8-838a-4a84644b4168.png">

**Comment by philipphofmann** [comment]
Thanks, I can also now reproduce it on a simulator. I'm a bit confused at the moment because the error states that `NSURLSessionConfiguration` doesn't have [`HTTPAdditionalHeaders`](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411532-httpadditionalheaders). I can't find anything related to that on the docs.

**Comment by FelixHerrmann** [comment]
I compared the runtime headers and it looks like the **NSURLSessionConfiguration** changed a lot with iOS 14. There is no _HTTPAdditionalHeaders_ instance method on iOS 13, only the property.

[iOS 14 NSURLSessionConfiguration](https://developer.limneos.net/index.php?ios=14.4&framework=CFNetwork.framework&header=NSURLSessionConfiguration.h)

[iOS 13 NSURLSessionConfiguration](https://developer.limneos.net/index.php?ios=13.1.3&framework=CFNetwork.framework&header=NSURLSessionConfiguration.h)

**Comment by philipphofmann** [comment]
Yes, that could be the problem, I guess. I also see that under the hood, they are different. On iOS 13, I get a `__NSCFURLSessionConfiguration_Mutable` and on iOS 14, I get a `NSURLSessionConfiguration`. Thanks for the info.

**Comment by FelixHerrmann** [comment]
No problem 🤠

**Comment by philipphofmann** [comment]
In case you are interested in the proper fix, @FelixHerrmann: https://github.com/getsentry/sentry-cocoa/pull/1302.

**Comment by FelixHerrmann** [comment]
Great, thanks for the quick fix @philipphofmann 🤝

**Comment by philipphofmann** [comment]
> Great, thanks for the quick fix @philipphofmann 🤝

Thanks for reporting this crucial bug.
