### ISSUE TITLE
Include unfinished spans in transactions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1303]
When a transaction is finished, the SDK tries to send the data to Sentry.
If an open Span (one that was not finished) exist in that transaction, the SDK removes that span before sending the data to Sentry.

That was done because [Sentry will discard the transaction if unfinished spans are included](https://github.com/getsentry/relay/blob/569678659bac656d6c4a6edcbdf3381677b5eaa2/relay-general/src/store/transactions.rs#L110-L130). More context on this thread: https://github.com/getsentry/develop/issues/274

An alternative solution used by the JavaScript SDK is to complete those spans with the timestamp of the finishing transaction and setting the status to `timeline_exceeded`. We should align with this approach as it shows something was going on even though it wasn't completed during the transaction.

Java: https://github.com/getsentry/sentry-java/issues/1690
.NET: https://github.com/getsentry/sentry-dotnet/issues/1182

**Comment by bruno-garcia** [comment]
Reopening as the goal is to stop modifying the span status (or removing it for that matter) if a span is not finished.
Relay will take care of it: https://github.com/getsentry/relay/issues/1244
Related .NET issue: https://github.com/getsentry/sentry-dotnet/issues/1182

Worth noting once we revert the change here we'll need to notify the minimum Self Hosted version required since the old version of Relay dropped transactions completely if they had an unfinished span (reason why all SDKs compensated that with dropping or lying about a span being finished)

**Comment by philipphofmann** [comment]
@bruno-garcia, wouldn't it be better to open another issue for reverting this change?

**Comment by philipphofmann** [comment]
This was done with https://github.com/getsentry/sentry-cocoa/pull/1592.
