### ISSUE TITLE
Fix transaction serialization

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1311]
The transaction payload currently contains too many fields. It should only contain the following fields as pointed out in the [docs](https://develop.sentry.dev/sdk/event-payloads/transaction/#examples):
```json
{
  "contexts": {
    "trace": {
      "op": "navigation",
      "description": "User clicked on <Link />",
      "trace_id": "743ad8bbfdd84e99bc38b4729e2864de",
      "span_id": "a0cfbde2bdff3adc",
      "status": "ok",
      "parent_span_id": "99659d76b7cdae94"
    }
  }
}
```

Currently, the transaction also contains `tags`, `data`, `sampled`, and `type` inside the trace, which is incorrect.
```json
"trace": {
    "trace_id": "49f353338d544068a4e756e7a60be2cc",
    "span_id": "e27c1c9aa5ae435d",
    "op": "some operation",
    "status": "unknown",
    "data": {
        "Some": 1234
    },
    "sampled": "true",
    "start_timestamp": 1630567805.2823582,
    "tags": {
        "Awesome": "Sentry"
    },
    "timestamp": 1630567805.846662,
    "type": "trace"
}
```

When doing this change, we need to make sure that we keep `tags` and `data` in the serialization of the span:

```json
{
  "spans": [
    {
      "start_timestamp": 1588601261.481961,
      "description": "GET /sockjs-node/info",
      "tags": {
        "http.status_code": "200"
      },
      "timestamp": 1588601261.488901,
      "parent_span_id": "b0e6f15b45c36b12",
      "trace_id": "1e57b752bc6e4544bbaa246cd1d05dee",
      "op": "http",
      "data": {
        "url": "http://localhost:8080/sockjs-node/info?t=1588601703755",
        "status_code": 200,
        "type": "xhr",
        "method": "GET"
      },
      "span_id": "b01b9f6349558cd1"
    }
  ]
}
```

Clarified:
 * The `tags` should be on the top level of the transaction.

Where to put:
* `data`
* `sampled`
* `type`

**Comment by marandaneto** [comment]
ideally, the `trace` object isn't of the type `SentrySpanContext` but rather a new one called `SentryTraceContext`, an option is that `SentrySpanContext` inherits from `SentryTraceContext` since they share some fields but they don't necessarily are the same thing, so inheritance maybe isn't the best option either.

**Comment by philipphofmann** [comment]
The serialization of data works fine. I think that also sampled and type are fine. We only need to fix tags.
