### ISSUE TITLE
SentryOptions tracesSampleRate not work.

### ISSUE THREAD

**Issue by ZeroOnet** [getsentry/sentry-cocoa#1314]
### Environment

How do you use Sentry?
self-hosted.

Which SDK and version?
sentry-cocoa: 'Sentry', '7.1.3'

### Steps to Reproduce

Define your transactions and set tracesSampleRate to 0.01.

### Expected Result

Upload sampled transactions.

### Actual Result

Upload all transactions.

**Comment by marandaneto** [comment]
@ZeroOnet thanks for reporting, have you tried the latest version? https://github.com/getsentry/sentry-cocoa/releases/tag/7.2.7

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-cocoa/releases/tag/7.2.8
