### ISSUE TITLE
crash in -[SentryCrash setUserInfo:]

### ISSUE THREAD

**Issue by otusweb** [getsentry/sentry-cocoa#1319]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

I'm not sure :-)
Here is the crash log: https://sentry.io/share/issue/ef36f178bcff485789d6aabe590d7ab3/
I'm happy to answer any question about the code, but the crash data does not get me many clues

### Expected Result

No crash 

### Actual Result

https://sentry.io/share/issue/ef36f178bcff485789d6aabe590d7ab3/

**Comment by marandaneto** [comment]
@otusweb thanks for reporting, we'll have a look at it

**Comment by marandaneto** [comment]
cc @philipphofmann

**Comment by philipphofmann** [comment]
Hey @otusweb, can you please give us more context on this issue please? You stated that you use JavaScript 5.11.1 and .NET 1.2.0. Can you please let me know which Cocoa version you use? We have done several bug fixes since you opened this issue. It could be that it is already fixed now.

**Comment by marandaneto** [comment]
@philipphofmann you can trace back the Cocoa version and stack trace by opening the linked issue (issue description) on sentry, Crash happens on SentryCrashJSONCodecObjC#encodeObject

**Comment by marandaneto** [comment]
@otusweb does your app call `SentryCrash setUserInfo` manually? what's the data type/structure of your objects?

**Comment by philipphofmann** [comment]
I think this should be fixed with #1193 in 7.2.0. Feel free to reopen this issue @otusweb if it still exists.
