### ISSUE TITLE
setup COCOAPODS_TRUNK_TOKEN for Automated CocoaPod releases

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1320]
https://medium.com/swlh/automated-cocoapod-releases-with-github-actions-8526dd4535c7

otherwise, Craft can't release it in non attended mode, it should be under https://github.com/getsentry/publish

**Comment by philipphofmann** [comment]
Do we still need this @marandaneto ? We already do our releases with getsentry/publish.

**Comment by marandaneto** [comment]
it was done under https://github.com/getsentry/publish
