### ISSUE TITLE
Flag for Disabling HTTP Instrumentation

### ISSUE THREAD

**Issue by triplef** [getsentry/sentry-cocoa#1327]
Is there a way to disable _only_ the [HTTP Instrumentation](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#http-instrumentation), but keep the other kinds of instrumentation (UIViewController etc.), or otherwise filter out the HTTP logs from breadcrumbs?

Our app makes a lot of network requests, which litter the breadcrumbs and rarely help with debugging. However, UIViewController instrumentation can be helpful so we’d like to keep it. Unfortunately there only seems to be a single flag `enableAutoPerformanceTracking` to control all instrumentation.

**Comment by triplef** [comment]
Swizzling the swizzler does the trick, but would still be nice to have a config option for this:

```objc
Class networkSwizzlingClass = NSClassFromString(@"SentryNetworkSwizzling");
if (networkSwizzlingClass) {
	IMP emptyImplementation = imp_implementationWithBlock(^{});
	Method startMethod = class_getClassMethod(networkSwizzlingClass, @selector(start));
	class_replaceMethod(networkSwizzlingClass, @selector(start), emptyImplementation, method_getTypeEncoding(startMethod));
	Method stopMethod = class_getClassMethod(networkSwizzlingClass, @selector(stop));
	class_replaceMethod(networkSwizzlingClass, @selector(stop), emptyImplementation, method_getTypeEncoding(stopMethod));
}
```

**Comment by triplef** [comment]
I found an (official?) way to disable networking instrumentation:
```objc
[SentrySDK startWithConfigureOptions:^(SentryOptions *options) {
	NSMutableArray *integrations = [options.integrations mutableCopy];
	[integrations removeObject:@"SentryNetworkTrackingIntegration"];
	options.integrations = integrations;
}];
```

**Comment by marandaneto** [comment]
yes, removing integrations is possible, it's documented here -> https://docs.sentry.io/platforms/apple/configuration/integrations/default/ but the `SentryNetworkTrackingIntegration` isn't there yet, good catch.

@philipphofmann should we add it?

**Comment by brustolin** [comment]
Maybe the solution for this should be a flag in SentryOptions. Today we have one flag for all tracking integrations.

**Comment by marandaneto** [comment]
SentryOptions#enableNetworkTracking would be nice, if we document how to remove the integration is also fine

**Comment by philipphofmann** [comment]
If we add `SentryOptions.enableNetworkTracking`, we should also add flags for app start and slow and frozen frames to be consistent. So then would add:
* enableNetworkTracking
* enableAppStartMeasuring
* enableFramesMeasuring

What do you think, @bruno-garcia, @marandaneto, and @brustolin?

**Comment by marandaneto** [comment]
All in for `enableNetworkTracking`, the other 2 not sure since they are just measurements, and we can always add later if its necessary
