### ISSUE TITLE
Expose SDK diagnostic logger to hybrid SDKs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1333]
The Unity SDK has some logic that would benefit from SDK logging. The logic is in an Objective-C file right before calling into the cocoa SDK. We'd like to access the SDK logger which already has the level defined via `SentrySDK.start`. 

It's not a goal to expose `SentryLog` to customers as this can be a bit confusing. The logger exists to diagnose issues with the SDK and not to log things into Sentry.

**Comment by philipphofmann** [comment]
Why don't you create your own logger that uses `NSLog` as `SentryLog` does?

**Comment by marandaneto** [comment]
you could add the `logger` to SentryOptions if not yet and hold the reference when `SentrySDK.start` is called, but if you need to log stuff even before calling `SentrySDK.start`, it won't work and creating its own Logger would be the way to go.

**Comment by bruno-garcia** [comment]
Diagnostic logger respects the level we set in the SDK. So when we configure it to be `info` or higher, it doesn't get as spammy. It's also only logging when `debug=true` and we don't have options at that point in the code, but the SDK would be initialized (or not which means no logging) so ideally we'd rely on the diagnostic logger. That's how we have it on .NET/Unity, Java/Android and Dart/Flutter.

We anyway just avoided logging altogether, so problem solved ;)

**Comment by philipphofmann** [comment]
> We anyway just avoided logging altogether, so problem solved ;)

Should we close the issue then?
