### ISSUE TITLE
Handle UUID changes in device for false positive OOM

### ISSUE THREAD

**Issue by aguilarpgc** [getsentry/sentry-cocoa#1334]
As Apple mention (https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) for UUID:

> The value in this property remains the same while the app (or another app from the same vendor) is installed on the iOS device. The value changes when the user deletes all of that vendor’s apps from the device and subsequently reinstalls one or more of them. The value can also change when installing test builds using Xcode or when installing an app on a device using ad-hoc distribution. Therefore, if your app stores the value of this property anywhere, you should gracefully handle situations where the identifier changes.

That would mean adding this scenario in `SentryOutOfMemoryLogic`:
If the UUID changed then return NO, if it hasn't changed then continues with the next validations.
 
My question is if you plan to add this scenario in `SentryOutOfMemoryLogic.m`?

**Comment by marandaneto** [comment]
looks like a fair thing to check as well

**Comment by aguilarpgc** [comment]
Hi, thanks for the response.
Do you agree If I make the implementation? or you guys will be considering doing yourselves?

**Comment by marandaneto** [comment]
@aguilarpgc a PR would be awesome
