### ISSUE TITLE
SIGSEGV crash at the start of app

### ISSUE THREAD

**Issue by spirit221** [getsentry/sentry-cocoa#1335]
Which SDK and version?
Sentry (4.5.0):

### Steps to Reproduce

App crash at the start 

### Expected Result

Implied no crash
The number of users with current crash is not large

### Actual Result
Below is stacktrace of crash
Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x1e4bb6378 _platform_strcmp + 8
1  Sentry                         0x10a03adc4 sentrycrashobjc_objectType + 906 (SentryCrashObjC.c:906)
2  Sentry                         0x10a03ed84 writeMemoryContentsIfNotable + 823 (SentryCrashReport.c:823)
3  Sentry                         0x10a03d3a8 writeThread + 1009 (SentryCrashReport.c:1009)
4  Sentry                         0x10a03ddf8 writeAllThreads + 1243 (SentryCrashReport.c:1243)
5  Sentry                         0x10a03dbf4 sentrycrashreport_writeStandardReport + 1756 (SentryCrashReport.c:1756)
6  Sentry                         0x10a02c884 onCrash + 111 (SentryCrashC.c:111)
7  Sentry                         0x10a036b8c sentrycrashcm_handleException + 249 (SentryCrashMonitor.c:249)
8  Sentry                         0x10a039048 handleSignal + 108 (SentryCrashMonitor_Signal.c:108)
9  libsystem_platform.dylib       0x1e4bb5d90 _sigtramp + 52
10 UIKitCore                      0x19e7c1744 _classWithImplementationOfSelector + 100
11 UIKitCore                      0x19e7c1744 _classWithImplementationOfSelector + 100
12 UIKitCore                      0x19e7be5d4 PushNextClassForSettingIMP + 312
13 UIKitCore                      0x19e7beee0 TaggingAppearanceObjectSetterIMP + 48
14 UIKitCore                      0x19f05e310 __22-[UILabel _commonInit]_block_invoke_2 + 200
15 UIKitCore                      0x19f0e4cf0 +[UIView _performSystemAppearanceModifications:] + 68
16 UIKitCore                      0x19f05e14c -[UILabel _commonInit] + 372
17 UIKitCore                      0x19f05e548 -[UILabel initWithFrame:] + 60
18 UIKitCore                      0x19e590cac -[UIButtonLabel _initWithFrame:button:] + 100
19 UIKitCore                      0x19e59f490 -[UIButton _newLabelWithFrame:] + 84
20 UIKitCore                      0x19e59f610 -[UIButton _setupTitleViewRequestingLayout:] + 120
21 UIKitCore                      0x19e59c93c -[UIButton _viewForBaselineLayout] + 84
22 UIKitCore                      0x19e59c8b0 -[UIButton viewForLastBaselineLayout] + 100
23 UIKitCore                      0x19f0e4610 -[UIView _hasBaseline] + 28
24 UIKitCore                      0x19f0e46e0 -[UIView _shouldInvalidateBaselineConstraintsForSize:oldSize:] + 48
25 UIKitCore                      0x19f0fcc98 -[UIView(Geometry) setBounds:] + 144
26 UIKitCore                      0x19e594a28 -[UIButton setBounds:] + 112
27 UIKitCore                      0x19f0fc3b0 -[UIView(Geometry) _applyISEngineLayoutValuesToBoundsOnly:] + 532
28 UIKitCore                      0x19f0fc790 -[UIView(Geometry) _resizeWithOldSuperviewSize:] + 152
29 UIKitCore                      0x19f0fbc8c __46-[UIView(Geometry) resizeSubviewsWithOldSize:]_block_invoke + 120
30 CoreFoundation                 0x19c3251d0 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 16
31 CoreFoundation                 0x19c289478 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 460
32 UIKitCore                      0x19f0fbbe8 -[UIView(Geometry) resizeSubviewsWithOldSize:] + 184
33 UIKitCore                      0x19f02e19c -[UIView(AdditionalLayoutSupport) _is_layout] + 148
34 UIKitCore                      0x19f1038ac -[UIView _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 1000
35 WavesUIKit                     0x10a7df2f8 UIView.swizzled_shadow_layoutSubviews() + 36 (UIView+Shadow.swift:36)
36 WavesUIKit                     0x10a7df46c @objc UIView.swizzled_shadow_layoutSubviews() + 14324 (<compiler-generated>:14324)
37 UIKitCore                      0x19f116398 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2468
38 QuartzCore                     0x19f61bdf4 -[CALayer layoutSublayers] + 288
39 QuartzCore                     0x19f622398 CA::Layer::layout_if_needed(CA::Transaction*) + 520
40 QuartzCore                     0x19f62d6e8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 140
41 QuartzCore                     0x19f578d7c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 416
42 QuartzCore                     0x19f5a2f40 CA::Transaction::commit() + 728
43 UIKitCore                      0x19ec29984 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 80
44 CoreFoundation                 0x19c321950 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
45 CoreFoundation                 0x19c320bd8 __CFRunLoopDoBlocks + 404
46 CoreFoundation                 0x19c31b3f4 __CFRunLoopRun + 796
47 CoreFoundation                 0x19c31aba0 CFRunLoopRunSpecific + 572
48 GraphicsServices               0x1b3080598 GSEventRunModal + 160
49 UIKitCore                      0x19ec0c2f4 -[UIApplication _run] + 1052
50 UIKitCore                      0x19ec11874 UIApplicationMain + 164
51 Exchange                       0x104ab5478 main + 35 (AppDelegate.swift:35)
52 libdyld.dylib                  0x19bff9568 start + 4

**Comment by bruno-garcia** [comment]
The code base was heavily changed in version 4 of the SDK. Could you please update it and see if the error persists?

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.
