### ISSUE TITLE
Add an option to opt-out of HTTP breadcrumbs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1336]
We need a way for users to opt-out of having these breadcrumbs.

https://github.com/getsentry/sentry-cocoa/blob/468e7da4df2cb05bf29ec9d28ec9f2828be48e09/Sources/Sentry/SentryNetworkTracker.m#L144-L168

Documentation currently doesn't include `SentryNetworkTrackingIntegration`

https://docs.sentry.io/platforms/apple/configuration/integrations/default/

**Comment by tmm1** [comment]
Wasn't SentryOptions.enableNetworkTracking added for this?

**Comment by philipphofmann** [comment]
Currently, you can use `SentryOptions.enableNetworkTracking` to disable the breadcrumbs, but this feature should only be related to performance monitoring. It should be possible for you to disable network tracking but still get HTTP breadcrumbs. @tmm1.

https://github.com/getsentry/sentry-cocoa/blob/4499a316e36d7dfb355678e97303bacb32e8949f/Sources/Sentry/SentryNetworkTrackingIntegration.m#L12-L17

**Comment by philipphofmann** [comment]
Add the flag `enableNetworkBreadcrumbs` to SentryOptions default is `true`. When `SentryOptions.enableNetworkTracking` is disabled or no tracesSampleRate is set, the SDK still adds breadcrumbs for network requests. When `enableSwizzling` is disabled the SDK doesn't add breadcrumbs for network requests.
