### ISSUE TITLE
Possible memory leak of several objects

### ISSUE THREAD

**Issue by nimrods-lemonade** [getsentry/sentry-cocoa#1351]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Swift 7.3.0

### Steps to Reproduce

1. Initializing the SDK
2. Navigate to a new page

### Expected Result

We would hold the same amount of objects before navigating to the new page and afterwards.

### Actual Result

The following objects are piling up in the memory:
* SentryBreadcrumb
* SentrySpan
* SentrySpanContext
* SentrySpanID

Here is a screenshot of the count of those objects. Those numbers go up every time we go to a new page.

<img width="1500" alt="Screen Shot 2021-09-29 at 11 23 34" src="https://user-images.githubusercontent.com/90557127/135231410-99c08104-7e9d-4925-a8ad-8d666617376c.png">

**Comment by philipphofmann** [comment]
Thanks for reporting this, @nimrods-lemonade. The profiler for allocations doesn't warn us about leaking memory, but I also see an increase of the objects you described in the Debug Memory Graph. We are going to look into this.

**Comment by philipphofmann** [comment]
I think I found the problem. It seems like we have a strong reference cycle between `SentryTracer` and `SentrySpan`.
