### ISSUE TITLE
Crash in SentrySpan

### ISSUE THREAD

**Issue by FelixHerrmann** [getsentry/sentry-cocoa#1358]
### Environment

Which SDK and version?
sentry-cocoa 7.4.0 & 7.4.1

### Steps to Reproduce

1. Start app with Sentry SDK (7.4.1)

### Expected Result

No crash.

### Actual Result

App crashes immediately when the first viewDidAppear get's called by the system, no issue with 7.3.0 and lower.
Tested it with iOS 13.5, 14.8 and 15.0!

<img width="1657" alt="Bildschirmfoto 2021-10-01 um 22 48 44" src="https://user-images.githubusercontent.com/42500484/135685128-17976cbc-3276-4277-abf8-62d782980158.png">

**Comment by marandaneto** [comment]
could it be related to #1355?

**Comment by FelixHerrmann** [comment]
> could it be related to #1355?

No, this crash is iOS independent and is not happening on 7.3.0. I think [this change](https://github.com/getsentry/sentry-cocoa/commit/4e0c971a2eb503e4bdae2362dc9a707a3118601a) is the problem.

**Comment by Md-Mahfuzur-Rahman** [comment]
I am also getting this crash

**Comment by vincentisambart** [comment]
I also get this crash, but not in all view controllers.

It's crashing in `KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED`. Looking at the backtrace and console messages, it seems that:
- `SentryTracer` observes its `SentrySpan` children's `timestamp`
- for some reason `SentryTracer` gets released while still observing, without calling `removeObserver:`.
- `-[UIViewController viewDidAppear]` gets called, leading to `-[SentrySpan finish]` being called.
- `-[SentrySpan finish]` modifies the `SentrySpan`'s `timestamp`. The system sees the KVO in place so it tries to call the observer (`SentryTracer`), but that observer has already been released so you get a crash.

It seems to me that `SentryTracer` should call `removeObserver:` when it's released, and/or you should make sure that `SentryTracer` does not get released if it is still waiting for a `SentrySpan` that might still finish.

**Comment by marandaneto** [comment]
thanks for reporting, we'll be looking into it shortly.

**Comment by philipphofmann** [comment]
Thanks @vincentisambart for the detailed report. We removed KVO and replaced it with a simple method call. This again reminds me, that you really only should use KVO when you don't have an alternative. Sorry about the trouble we caused.

**Comment by philipphofmann** [comment]
Still `SentryTracer` shouldn't be deallocated before it's children are finished, but it can happen and this is a different problem.
