### ISSUE TITLE
Setting `diagnosticLevel` to `.info` doesn't prevent `.debug` events from being uploaded

### ISSUE THREAD

**Issue by bdrelling** [getsentry/sentry-cocoa#1364]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
iOS SDK v7.4.2

### Steps to Reproduce

Set the `diagnosticLevel` to `.info`, per the documentation [here](https://docs.sentry.io/platforms/apple/guides/watchos/configuration/options/#diagnostic-level).

```swift
SentrySDK.start { options in
    // Set the diagnostic level to info at a minimum.
    options.diagnosticLevel = .info
}
```

### Expected Result

The Sentry SDK should not report `.debug` events to Sentry.io.

### Actual Result

All events are being reported to Sentry.io.

**Comment by bdrelling** [comment]
Now I'm getting all jumbled up, I don't see `options.logLevel`, but I see it stated [here](https://docs.sentry.io/platforms/apple/guides/ios/usage/set-level/).

I can tell now that `diagnosticLevel` is a property for what gets logged if `options.debug` is `true`, but now I don't understand how to filter the events properly. I thought I used to be able to set the minimum level to report right in this initializer?

**Comment by philipphofmann** [comment]
Sorry, @bdrelling for the late response. The `diagnosticLevel` is only about the SDK diagnostics logs. It has nothing to do with what gets sent to Sentry. You can use [`beforeSend`](https://docs.sentry.io/platforms/apple/configuration/filtering/) to filter events. 

I consider your question as answered and therefore close this issue. Please open it again if you need more information.
