### ISSUE TITLE
Call must be made on main thread

### ISSUE THREAD

**Issue by JCTec** [getsentry/sentry-cocoa#1366]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-cocoa 7.4.3

### Steps to Reproduce

1. iOS 15
2. Sentry 7.4.3
3. As a workaround we forked and replaced `self.queue` with `dispatch_get_main_queue()`
4. In the SDK initialisation:
`SentrySDK.start { $0.dsn = sentryDSN }`

### Expected Result
I now you just release the update 7.4.3 but instead of creating a new serial queue that creates the View Controllers I think it should be done on the main thread.

### Actual Result
The UIViewControllers are created on thread `sentry-default`.

Stack trace:
![Screen Shot 2021-10-07 at 3 44 42 p m](https://user-images.githubusercontent.com/25288448/136459410-98db347d-dcd0-411e-b794-0728635a3ab1.png)

![Screen Shot 2021-10-07 at 3 46 03 p m](https://user-images.githubusercontent.com/25288448/136459701-5549fa4b-ed82-4211-903c-7a377ed9d81e.png)

*Update*:
_The fork at my GitHub account has been deleted._

**Comment by dyegos** [comment]
Hello again, it seems to be a problem with App Center + Sentry.
When I copy the error from the crash, there's this line

#8	0x000000010db64e1c in +[MSACAlertController initialize] at /Users/runner/work/1/s/AppCenterDistribute/AppCenterDistribute/MSACAlertController.m:47

For some reason, while swizzling, the MSACAlertController is initialized in the background thread.
Could the last version sending a message that can trigger that?

**Comment by JCTec** [comment]
@brustolin Sadly I don't, but to give a little bit more context seems I have the same error as @dyegos and my timeline is the next:

- Xcode 12, version 7.0.0 the app didn't crash.
- Xcode 13 version 7.0.0 the app did crash
- Xcode 13 version 7.4.3 the app did crash

I will try version 7.4.2 to see if it crash or not to give a bit more context on what's happening.

**Comment by JCTec** [comment]
I'm sorry @brustolin I ask my superiors apparently we are using AppCenter! I'm sorry, but gladly this means that is exactly the same error as @dyegos.

I'll keep you posted about more insights!!

**Comment by dyegos** [comment]
@philipphofmann Thank you very much for the update. I am glad we were able to find the issue :)
We are looking forward to it. Have a nice day.

**Comment by dyegos** [comment]
@philipphofmann update. I ran the app and it's not crashing anymore in our project as well. 👍🏽

**Comment by JCTec** [comment]
Thank you very much @philipphofmann @brustolin for your work and also thank you @dyegos for the input that actually was the key to solving it, this have being a real save for our team. It is now working corretly with SPM in our project too with commit `953414914f7546894ad90b582f4e926db45a362e`.

**Comment by philipphofmann** [comment]
Thanks for the good news, @JCTec. I'm happy it works now.
