### ISSUE TITLE
Change the default finish status for transactions

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1411]
Based on @dashed comment in #1350, the `Undefined` status of a transaction is consider an error.

Should we change default finish status in SentryTracer and PerformanceTracker to `Ok`?

@bruno-garcia, @marandaneto, @philipphofmann

**Comment by brustolin** [comment]
@dashed @marandaneto 

I realize that the undefined status is not in the documentation, we included it because objc has no nullable enum.
When the status is undefined we simple does not serialize it.

The documentation says that status is optional, so I guess if we don't send it, this is no treated as an error right?

Should UIViewController performance transactions and IO transactions have a status anyway? Or just leave as it is?

**Comment by dashed** [comment]
> The documentation says that status is optional, so I guess if we don't send it, this is no treated as an error right?

@brustolin I think if you do not explicitly set the `status`, it will not be treated as an error.
