### ISSUE TITLE
SwizzlingError - Original method not called

### ISSUE THREAD

**Issue by sambeedell** [getsentry/sentry-cocoa#1435]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm unable to reproduce locally but we are getting crash reports on this issue. When our UICollectionView applies its UICollectionViewDiffableDataSource a Sentry method is invoked during the layout of sublayers which causes a crash.

I have updated our Swift Packages in case this has already been resolved.

### Expected Result

A collection view of items

### Actual Result

<img width="1666" alt="Screenshot 2021-10-28 at 16 41 15" src="https://user-images.githubusercontent.com/6514503/139297515-adb90cec-b8c8-4fb1-9f61-0855dd59c5d8.png">

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.
