### ISSUE TITLE
Confusing transaction tag

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1437]
### Environment

Cocoa 7.5.0 on iOS

### Steps to Reproduce

1. Open the SwiftUI Sample app. 
2. Click on Lorem Ipsum
3. Click on captureMessage

### Expected Result

Don't have a confusing tag in the event.

### Actual Result

The tags of the event show a tag transaction with the value UIInputWindowController.

<img width="847" alt="Screen Shot 2021-10-29 at 14 21 53" src="https://user-images.githubusercontent.com/2443292/139433506-bbd4ff91-d2db-42b6-8514-48e3ef86baf3.png">

**Comment by philipphofmann** [comment]
Ah, I get it. It's a different transaction not related to performance. The wording is pretty confusing. Yes, `__sentry_transaction` then turns into `transaction`, which [Java](https://github.com/getsentry/sentry-java/blob/2d8a74aff519a99f44b49d3172ff66775662f9eb/sentry/src/main/java/io/sentry/SentryEvent.java#L50-L56) has.

```Java
  /**
   * Transaction name of the event.
   *
   * <p>For example, in a web app, this might be the route name (`"/users/<username>/"` or
   * `UserView`), in a task queue it might be the function + module name.
   */
  private @Nullable String transaction;
```

Wow, this is confusing in [Java](https://github.com/getsentry/sentry-java/blob/2d8a74aff519a99f44b49d3172ff66775662f9eb/sentry/src/main/java/io/sentry/Scope.java#L166-L181):
```Java
/**
   * Sets the Scope's transaction.
   *
   * @param transaction the transaction
   */
  public void setTransaction(final @NotNull String transaction) {
    if (transaction != null) {
      final ITransaction tx = this.transaction;
      if (tx != null) {
        tx.setName(transaction);
      }
      this.transactionName = transaction;
    } else {
      options.getLogger().log(SentryLevel.WARNING, "Transaction cannot be null");
    }
  }
```

I'm going to update the code docs on transaction for scope and event in Cocoa and maybe we can do something in the SentryUI to make it clearer that the transaction tag is something different.

**Comment by philipphofmann** [comment]
I think we shouldn't remove setting the extra value `__sentry_transaction` in SentryBreadcrumbTracker but instead point out in the UI somehow which transaction that is.

**Comment by philipphofmann** [comment]
Todos:

- [ ] Fix code docs here https://github.com/getsentry/sentry-cocoa/blob/b08f27f7ad9d4fdb3c1f2558da9b8ad70f5a21a2/Sources/Sentry/Public/SentryEvent.h#L78-L81
- [ ] Add transaction to Scope

**Comment by marandaneto** [comment]
@philipphofmann the reason is https://develop.sentry.dev/sdk/performance/#scope-changes

See:

> Setting the transaction property on the Scope (legacy) should overwrite the name of the Transaction stored in the Scope, if there is one. With that we give users the option to change the transaction name even if they don't have access to the instance of the Transaction directly.

Since the `transaction` String is a legacy thing, we could discuss if we should do it, cc @bruno-garcia

**Comment by philipphofmann** [comment]
This produces an ugly long transaction tag for SwiftUI see
<img width="723" alt="Screen Shot 2021-11-02 at 15 46 35" src="https://user-images.githubusercontent.com/2443292/139870393-ea7c74f8-28f6-4683-8893-a76d157cdfc5.png">

**Comment by philipphofmann** [comment]
Let's not add it to the scope. 

If you capture an error or message event and there is a transaction event on the scope (`scope.span`), the `event.transaction` should match the name of the transaction on the scope (`scope.span`).
When the transaction completes make sure to restore the previous value.

**Comment by brustolin** [comment]
Its not clear to me what we need to do in this issue.

Regarding event.transaction, we're doing the same as other sdks, so I think there is nothing else to do in that matter.

**Comment by philipphofmann** [comment]
We would need to start a discussion about removing the `event.transaction` property. It's a legacy thing, and as we have now performance, it's confusing. Is that something you can clarify, @brustolin?

**Comment by marandaneto** [comment]
> event.transaction

We cannot remove `event.transaction`, that's where the transaction name is set, it's not deprecated.
Using the `event.transaction` without the `event.contexts.trace` is a deprecated feature, but the field is still needed.

**Comment by brustolin** [comment]
> Using the event.transaction without the event.contexts.trace is a deprecated feature

I guess we could make this property private then and only use it inside the SDK.
But does it really matter?

**Comment by marandaneto** [comment]
I don't think we should remove nor make it private, it's still part of the unified API, and it's only soft deprecated internally.
iOS never had `scope.transaction` so it's not confusing because this feature never existed (for iOS).
`event.transaction` is likely a feature never used before by iOS events unless people set it on `beforeSend` or something.

For me, what needs to be done in order to close this is already written a few comments above, example:
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-965355554 (needs to be done?)
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-957736714 (already done?)
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-957407846 (clarify the docs?)

**Comment by brustolin** [comment]
> For me, what needs to be done in order to close this is already written a few comments above, example:
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-965355554 (needs to be done?)
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-957736714 (already done?)
https://github.com/getsentry/sentry-cocoa/issues/1437#issuecomment-957407846 (clarify the docs?)

I just checked and the first two are ok.

It boils down to the transaction property documentation, and Im thinking of just coping from develop docs.

`The name of the transaction which caused this event.`

**Comment by brustolin** [comment]
After understanding better what's happening with `__sentry_transaction` I think we should remove it.
It's confusing, not precise and pretty much don't make sense.

**Comment by philipphofmann** [comment]
Completed with https://github.com/getsentry/sentry-cocoa/pull/2574.
