### ISSUE TITLE
`tracesSampler` is `NSNull` when passing object from RN

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1441]
Context https://github.com/getsentry/sentry-react-native/issues/1864

https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryOptions.m#L229-L231 has to use `isKindOfClass` as a safeguard since the RN SDK uses `initWithDict` and JS options get synced down to the Native SDKs.

ideally, all the options should check its class type to avoid new issues like this.

**Comment by philipphofmann** [comment]
I guess we have the same issue with `beforeSend` then as well.

**Comment by philipphofmann** [comment]
Unfortunately, the best we can do is to check if the passed-in value is of type block, but we can't check if the arguments of the block properly match. I didn't find an easy straightforward way to check if a block matches a given type of block.
