### ISSUE TITLE
Suggestions: Expose `currentHub` getter

### ISSUE THREAD

**Issue by mokagio** [getsentry/sentry-cocoa#1451]
## Question

Since [version 7.x removed the `currentHub` and `setCurrentHub` from `SentrySDK`](https://docs.sentry.io/platforms/apple/migration/#migrating-from-6x-to-7x), what's the way to get a reference to the current hub now?

## Context
 
With version 6, we use the hub to get a reference to the current client and current scope in order to attach stack traces to events we log manually.

This relates to https://github.com/getsentry/sentry-cocoa/issues/660.

I suspect that, if there was an SDK-provided way to attach stack traces to events, we wouldn't need to access the hub.

## Suggestion

Would it perhaps be possible to reintroduce the `currentHub` getter on `SentrySDK`? Being only a getter method, it should be "harmless" for users to grab a reference and inspect its properties, right? I can see why you wouldn't want users to override the hub, as your docs say "The hub you are unlikely to be interacting with directly unless you are writing an integration or you want to create or destroy scopes," but, for us at least, having the ability to read what's in the hub is crucial.

Thank you for your help 😄

**Comment by philipphofmann** [comment]
Hey @mokagio, 

how do you currently attach the stacktrace to the event?

Can't you do something like?
```Swift
let event = Event()
event.stacktrace = Stacktrace(frames: [Frame], registers: [String : String])
SentrySDK.capture(event: event)
```

I would be interested in why you attach stacktraces manually.

**Comment by philipphofmann** [comment]
Any updates @mokagio?

**Comment by diegoreymendez** [comment]
Hey @philipphofmann, I'm working on the same codebase as @mokagio and we're still stuck to using Sentry 6.

In your snippet, which I'm copying below, you're suggesting that we set the stack trace manually:

```swift
let event = Event()
event.stacktrace = Stacktrace(frames: [Frame], registers: [String : String])
SentrySDK.capture(event: event)
```

Do you offer any mechanism to get the current `Stacktrace` without having to manually craft it ourselves?

**Comment by diegoreymendez** [comment]
I used a hack to obtain the stack trace in the PR referenced above, but it involves accessing private methods through selectors.  It would be ideal to have a way to get the current threads for filling in the event. ☝️

**Comment by philipphofmann** [comment]
Why do you want to manually attach a stacktrace to an event, @diegoreymendez? Can't you use the [`attach-stacktrace`](https://docs.sentry.io/platforms/apple/configuration/options/#attach-stacktrace) option?

**Comment by diegoreymendez** [comment]
@philipphofmann - Because Sentry doesn't offer [a callback after sending an event](https://github.com/getsentry/sentry-cocoa/issues/660) to know when sending the event succeeded, so [we have to send the event manually](https://github.com/Automattic/Automattic-Tracks-iOS/blob/79fc1521ce8c03162ad84793e20cdf95f34421fc/Sources/Remote%20Logging/Crash%20Logging/CrashLogging.swift#L186-L199) to implement the callback ourselves.

Ideally this would all be resolved rather easily if [what was originally requested here](https://github.com/getsentry/sentry-cocoa/issues/660) would be implemented.

**Comment by philipphofmann** [comment]
I just started the implementation of flush with https://github.com/getsentry/sentry-cocoa/issues/1013. Would that be sufficient for you? Or do you really need a callback after the event was sent? If so, can you please elaborate on your use case, @diegoreymendez?

**Comment by diegoreymendez** [comment]
I'm guessing it could be enough.  Thoughts @mokagio ?

**Comment by mokagio** [comment]
@philipphofmann thank you for following up on this!

> Why do you want to manually attach a stacktrace to an event, @diegoreymendez? Can't you use the [attach-stacktrace](https://docs.sentry.io/platforms/apple/configuration/options/#attach-stacktrace) option?

We've been sending manual events as a way to track a certain type of runtime error within our apps to which the only followup was to force a crash.

We achieve that behavior by _manually serializing events and sending them to Sentry via HTTP call to the DNS `getEnvelopeEndpoint()` API._

The code pre-dates me, but I assume the reason for manually attaching the stack trace to the event is that it wasn't available at the time. I can check if it would be useful for you.

> I just started the implementation of flush with #1013. 

+1 on @diegoreymendez's comment. I left [a question about adding a completion closure](https://github.com/getsentry/sentry-cocoa/issues/1013#issuecomment-1243187391).

**Comment by philipphofmann** [comment]
Thanks for the info. Yes, with flush, you will know that the event(s) have been successfully sent.
