### ISSUE TITLE
test: Add different types of UIViewControllers to Sample App

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1469]
Add the following to the iOSSwift sample app with some content:

* NavigationController
* SplitViewController
* TableViewController
* UIViewController initialized with a convenience init

Please add a back button, so the UITests can easier navigate back from each of the UIViewControllers.

If possible also add some of the above view controllers to the tvOS sample.

**Comment by brustolin** [comment]
Our tvOS sample uses SwiftUI.
I believe we should create another sample with Storyboard and ViewControllers to properly test this interactions.

**Comment by philipphofmann** [comment]
> Our tvOS sample uses SwiftUI. I believe we should create another sample with Storyboard and ViewControllers to properly test this interactions.

I agree. Can you please create an issue for that and add it to the list in https://github.com/getsentry/sentry-cocoa/issues/1468.
