### ISSUE TITLE
Signals are still reported as error even if they are ignored

### ISSUE THREAD

**Issue by alokedesai** [getsentry/sentry-cocoa#1472]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry.cocoa 7.0.3

### Steps to Reproduce
1. Explicitly ignore `SIGIPE`: `signal(SIGPIPE, SIG_IGN)`
2. Send `SIGPIPE` to the process (`kill -SIGPIPE {pid}`)

### Expected Result

No crash in sentry--the signal was explicitly ignored by Sentry.

### Actual Result

A fatal crash in Sentry--I think this because Sentry sets a custom signal handler but doesn't check if the previous handler is SIG_IGN first: https://github.com/getsentry/sentry-cocoa/blob/c06c857ff90589996b75f63ce289038ffbb29c24/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c#L165

**Comment by philipphofmann** [comment]
Thanks for reporting this issue, @alokedesai. Would you please elaborate on why you want to ignore `SIGIPE` explicitly?

**Comment by alokedesai** [comment]
I work at [warp.dev](https://www.warp.dev/)--our app is written in Rust with a very thin layer of Objective C. Rust by default ignores Sigpipe (see https://github.com/rust-lang/rust/pull/13158), so it's not even something we're configuring directly it's more a function of our stack. Generally, my understanding is that you should be ignoring `SIGPIPE` unless you're writing a CLI app since you don't want a broken pipe to terminate your app (see [here](https://stackoverflow.com/questions/108183/how-to-prevent-sigpipes-or-handle-them-properly) as an example).

In practice this means that sending a `SIGPIPE` to our application does nothing (since `SIGPIPE` is ignore) but does cause Sentry to report an "unhanded", fatal Sigpipe crash even though the app ignored the signal and continued to run just fine.

**Comment by philipphofmann** [comment]
Thanks, @alokedesai, for the detailed explanation.

@Swatinem, you know more about signal handlers than me. Does this change make sense to you?

**Comment by Swatinem** [comment]
I think thats a reasonable thing to do (check the previous signal handler, and essentially forward the *ignore*)

**Comment by philipphofmann** [comment]
We will put this on our backlog @alokedesai. This seems like a quick win, but we can't give you an ETA at the moment. Of course, we are happy to accept PRs 😀.

**Comment by alokedesai** [comment]
I'm happy to send a PR for this, @Swatinem though just to confirm we're on the same page--it's not that we need to forward the ignore, it's that we should check if the existing handler is `SIG_IGN` and, if so, not intercept the signal or try to send a crash.

**Comment by Swatinem** [comment]
Ah okay, maybe there was a bit of confusion. Checking the current handler and skipping registering our own would be good as well.

**Comment by alokedesai** [comment]
I'

**Comment by alokedesai** [comment]
Just sent out a very simple diff for this https://github.com/getsentry/sentry-cocoa/pull/1489. Would love ideas/links on how to add tests for this since it requires a real executable for correct signal handling.
