### ISSUE TITLE
Environment setting

### ISSUE THREAD

**Issue by MihaelIsaev** [getsentry/sentry-cocoa#152]
How can I set environment?

**Comment by MihaelIsaev** [comment]
Anyone?

**Comment by HazAT** [comment]
Hey,
Sorry for the late reply ... this will be included in the new version `3.0.0`

**Comment by HazAT** [comment]
Hey,
We've just released version `3.0.0` which support this feature, check out the docs and consider updating.
`SentryEvent` now has a property call environment.
