### ISSUE TITLE
Flaky `Integration Web Requests`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1527]
Attempt 4 failed with Integration Web Requests:

https://github.com/getsentry/sentry-cocoa/actions/runs/1551189543/attempts/4

```

Alamofire_iOS_Tests.AuthenticationInterceptorTestCase
  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("Optional("***")") is not equal to ("Optional("***")")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:602
  ```
            let response = responses[index]
            XCTAssertEqual(response?.request?.headers["Authorization"], "***")
            XCTAssertEqual(response?.result.isSuccess, true)
  ```

  testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses, XCTAssertEqual failed: ("2") is not equal to ("1")
  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/AuthenticationInterceptorTests.swift:610
  ```
        XCTAssertEqual(authenticator.applyCount, 12)
        XCTAssertEqual(authenticator.refreshCount, 1)
        XCTAssertEqual(authenticator.didRequestFailDueToAuthErrorCount, 6)
  ```


	 Executed 707 tests, with 3 tests skipped and 7 failures (0 unexpected) in 28.304 (30.507) seconds
2021-12-07 21:52:50.936 xcodebuild[9706:36907] [MT] IDETestOperationsObserverDebug: 83.335 elapsed -- Testing started completed.
2021-12-07 21:52:50.936 xcodebuild[9706:36907] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2021-12-07 21:52:50.936 xcodebuild[9706:36907] [MT] IDETestOperationsObserverDebug: 83.335 sec, +83.335 sec -- end
Failing tests:
	Alamofire iOS Tests:
		AuthenticationInterceptorTestCase.testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses()
		AuthenticationInterceptorTestCase.testThatInterceptorTriggersRefreshWithMultipleParallelRequestsReturning401Responses()

** TEST FAILED **

Error: Process completed with exit code 65.
```

**Comment by philipphofmann** [comment]
Running the tests twice in a row with https://github.com/getsentry/sentry-cocoa/pull/1516 is one mitigation.

**Comment by philipphofmann** [comment]
The tests now point to the commit hash of the [`5.5.0` Alamofire release](https://github.com/Alamofire/Alamofire/releases/tag/5.5.0). Let's see if these tests are more stable. I will close this now and keep an eye on the integration tests.
