### ISSUE TITLE
Getting lots of warnings from Sentry in XCode

### ISSUE THREAD

**Issue by margusholland** [getsentry/sentry-cocoa#153]
_Platform:_ 
- [x]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [x]  Yes, version 3.1
- [ ]  No

_sentry-swift installed with:_
- [x] Cocoapods
- [ ] Carthage
- [ ] Manually

Version of sentry-swift:
**2.1.9**

---
I have following issue:

I added Sentry to my project and after upgrading to Swift 3.1 and Xcode 8.3.2 I get multiple warnings

**Actual result:**

/Users/margusholland/Development/cocoa/AppName-iOS/Pods/Sentry/Sources/BreadcrumbStore.swift:32:75: String interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/margusholland/Development/cocoa/AppName-iOS/Pods/Sentry/Sources/BreadcrumbStore.swift:32:68: Use 'String(describing:)' to silence this warning
/Users/margusholland/Development/cocoa/AppName-iOS/Pods/Sentry/Sources/BreadcrumbStore.swift:32:68: Provide a default value to avoid this warning

**Expected result:**

No warnings.

<img width="312" alt="screen shot 2017-05-02 at 12 44 37" src="https://cloud.githubusercontent.com/assets/581561/25613365/99f97a30-2f36-11e7-91a3-143c41ec84c7.png">

**Comment by Ben305** [comment]
Same here

**Comment by HazAT** [comment]
Thanks for reporting, these will be fixed when we drop support for swift 2.3

**Comment by HazAT** [comment]
Hey,
We've just released version `3.0.0` which is a rewrite in objc, please consider upgrading the errors should be gone.
