### ISSUE TITLE
Make sure to send timestamps in RFC 3339

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1553]
Make sure to stop sending timestamps with ISO-8601 and only send [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) or a[ numeric (integer or float) value representing the number of seconds that have elapsed since the Unix epoch](https://en.wikipedia.org/wiki/Unix_time).

See https://develop.sentry.dev/sdk/event-payloads/

**Comment by kevinrenskers** [comment]
ISO-8601 allows for many many formats, of which a few are also valid RFC 3339 formats (see https://ijmacd.github.io/rfc3339-iso8601/). As far as I can tell, we're only using the version that is also valid RFC 3339? Do we even need to do anything here?

**Comment by kevinrenskers** [comment]
As far as I can see, it's all fine. Closing this.
