### ISSUE TITLE
Expose Installation ID for Hybrid SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1554]
Related to https://github.com/getsentry/sentry-react-native/issues/1280#issuecomment-979973426

The Android SDK sets the `userId` if none is provided by merging the user object, if the client provides an user `email` but not the `id`, the SDK still sets the installation id to the `userId`

**Comment by philipphofmann** [comment]
@marandaneto, I don't fully understand what we need to change in the Cocoa SDK. Can you please elaborate?
