### ISSUE TITLE
Please expose an API to check if there are pending crash reports

### ISSUE THREAD

**Issue by st3fan** [getsentry/sentry-cocoa#156]
In *Firefox for iOS* we would like to know,when the application starts, if the application has crashed the previous run, and if there are pending reports to send.

We would like to know for two reasons:

- We would like to give users the opportunity to not restore all the tabs they have open after they experience a crash; sometimes WKWebView crashes because of a specific web page, and if we do not give people the opportunity to close all tabs, they may end up in a crash loop since the web view will reload when you start the browser again.
- We would like to give people an opportunity to opt-in to crash reporting. And not call `startCrashHandler()` until they have gone through a confirmation dialog. But that question only makes sense if there is something to report.

Previously we used `PLCrashReporter.shared().hasPendingCrashReport()` .. is it possible to expose a similar method in Sentry?

**Comment by st3fan** [comment]
I don't know if this is a good request. I just found out about `KSCrash.sharedInstance().crashedLastLaunch` so that solves my immediate problem. It may have a place in `SentryClient` to abstract away the underlying crash reporter?

**Comment by HazAT** [comment]
Hey, 
This absolutely makes sense and since this shouldn't be to hard to expose we definitely will add this  👍 
We're currently in the process of a big code overhaul but since your problem is solved for now we will add this in the next major release.

**Comment by HazAT** [comment]
Hey,
We've just released version `3.0.0` which support this feature, check out the docs and consider updating.
