### ISSUE TITLE
Attach SwiftUI hierarchy to Events

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1560]
Attaching the hierarchy of SwiftUI to events can be helpful for debugging. Check out this excellent use case on [Twitter](https://twitter.com/sowenjub/status/1471927629745848320). 

We still need to discuss and find out how such a feature can look.

**Comment by philipphofmann** [comment]
Maybe this library https://github.com/domesticcatsoftware/DCIntrospect can be helpful.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by brustolin** [comment]
A way to retrieve the view hierarchy: https://www.fivestars.blog/articles/inspecting-views/

**Comment by philipphofmann** [comment]
@brustolin, please add a short comment on why this is currently not possible.

**Comment by brustolin** [comment]
Right now is not possible to retrieve SwiftUI view hierarchy on demand, not in an official way anyways.

If Apple ever updates its API we reopen this issue.
