### ISSUE TITLE
UITests testSplitView fails on iOS 13 on SauceLabs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1564]
testSplitView continues to fail with `XCTAssertTrue failed - Transaction did not complete. Expecting 11 spans, got 15`.

**Comment by brustolin** [comment]
Im changing the UI tests to not expect a certain number of spans. Different iOS versions have different ui life cycle runs.
I thing that verify whether specifics spans exists in the transaction is enough.
