### ISSUE TITLE
UITests testSplitView fails on iOS 12 on SauceLabs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1566]
`testSplitView` continues to fail with `XCTAssertTrue failed - Assertion Message Not Found`. When you watch the recording of the video of the test indeed no assertion messages pops up.

**Comment by philipphofmann** [comment]
@brustolin didn't we fix this already?

**Comment by brustolin** [comment]
I'm not really sure.
I remember trying to solve this, but I don't know the result since we remove all  SouceLabs tests for real devices.

I also made this tests a little simpler in the latest PRs, so maybe this helped too.

**Comment by philipphofmann** [comment]
We don't run UI tests on iOS 12 because of this see https://github.com/getsentry/sentry-cocoa/blob/440bf64c8037b1168dd2d37969c9b6d5e2ba5377/.github/workflows/ui-tests.yml#L64

**Comment by philipphofmann** [comment]
The UI tests currently run on iOS 12.
