### ISSUE TITLE
is there any way to send crash report when crash on boot.

### ISSUE THREAD

**Issue by thphu** [getsentry/sentry-cocoa#158]
_Platform:_ 
- [x]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version? 
- [x]  No

_sentry-swift installed with:_
- [x] Cocoapods
- [ ] Carthage
- [ ] Manually

Version of sentry-swift:
**2.x.x**

---
I have following issue:

Hi there, some of iOS users report that the app crash when launch app, but I didn't see any crash report. So I try to simulate a crash in `didFinishLaunchingWithOptions` and see that I can't receive any crash report. Is there any way to get it? 

**Steps to reproduce:**
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 [SentryClient setShared:[[SentryClient alloc] initWithDsnString:sentryDsn]];
  [[SentryClient shared] startCrashHandler];
 [[SentryClient shared] crash];
...
}
```

**Actual result:**
-Didn't see any report

**Expected result:**
- See crash report

**Comment by thphu** [comment]
Hi,

Is there any update?

**Comment by HazAT** [comment]
Hey, 
sorry for not responding earlier.
I wasn't able to reproduce this if you call the crash function later a report will be sent right?

**Comment by thphu** [comment]
yes, I call the function later, a report will be sent. Let say my project using a hybrid platform (react-native), it load bundle in didFinishLaunchingWithOptions and somehow is crash when load this bundle. I need to add a native crash report to investigate the root cause. As you see `[[SentryClient shared] crash];` will replace by load bundle code. If somehow it crash there, the report will not be sent right?
I guess it crash so fast (just a second when load app) so can't send any report.

**Comment by HazAT** [comment]
If it's stuck in a "crashloop" then there is not time for sending the request, right.

**Comment by thphu** [comment]
yea, seem it's a crashloop. So no way to get log?

**Comment by HazAT** [comment]
The logs are on the device, but there is no time to send them.
It's kind of hard to solve this right now, not sure how I can help.
