### ISSUE TITLE
Swizzle test fails when running locally

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#1595]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
N/A

Which SDK and version?
`master` `HEAD`

### Steps to Reproduce

`make run-test-server && make test`

### Expected Result

All tests pass locally on `master` branch.

### Actual Result

A single test case fails in `SentrySwizzleTests.m`. This doesn't seem to depend on the local machine's architecture, as I've reproduced it on both an Intel and M1 MacBook Pro. This doesn't appear to happen in CI.

```shell
SentrySwizzleTests
  testSwizzleDontCallOriginalImplementation, (([a methodForSwizzlingWithoutCallOriginal]) throws) failed: did not throw
  /Users/andrewmcknight/Work/Sentry/_sdks/sentry-cocoa/Tests/SentryTests/Helper/SentrySwizzleTests.m:353

    XCTAssertThrows([a methodForSwizzlingWithoutCallOriginal]);
}


	 Executed 1228 tests, with 1 failure (0 unexpected) in 14.862 (15.104) seconds
```

**Comment by philipphofmann** [comment]
I can reproduce this also on my MacBook Pro with Intel. @brustolin, as you wrote the test, can you please have a look?
