### ISSUE TITLE
Feature request: Add support for passing "Authorization" header

### ISSUE THREAD

**Issue by haimwaking** [getsentry/sentry-cocoa#161]
_Platform:_ 
- [x]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 3.1
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [ ] Carthage
- [x] Manually

Hi,

I am using self-hosted sentry and would like to place it behind a Google Cloud Computer IAP (Identity Aware Proxy). This means that in order for the client to send crashes, I will need to also set the "Authorization" header.

How difficult would it be to support this use case?

Thank you

**Comment by HazAT** [comment]
Hey,
We've just released version `3.0.0` which support this feature, check out the docs and consider updating.
https://docs.sentry.io/clients/cocoa/advanced/#change-request-before-sending-it

**Comment by haimwaking** [comment]
Excellent news, thank you @HazAT !
