### ISSUE TITLE
test: UI test for file IO span

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1612]
Add an UITest to validate that a span for NSData is added properly similar to the already existing [UI tests](https://github.com/getsentry/sentry-cocoa/blob/6c4db1d3ce71ba663b77598326dae1f32eb3dff3/Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift#L27-L31).

**Comment by brustolin** [comment]
Instead of creating a new view controller that does some IO operation, and trying to assert it by verifying the value on a label, we added SentrySDK to UITest. This way we could run some NSData integration tests directly on the device. 

See #1637
