### ISSUE TITLE
Failing testSwizzle_fromScene on iOS 12

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1614]
### Description

Investigate and fix failing test `testSwizzle_fromScene` and remove from skipped tests in here https://github.com/getsentry/sentry-cocoa/blob/f1f2a3b2b9befccaf4594c1d343129e28b2cd638/scripts/xcode-test.sh#L48

**Comment by brustolin** [comment]
UIScene is available from iOS 13 and above. This test should not run on iOS 12
