### ISSUE TITLE
feat: Add DiagnosticLogger

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1617]
### Problem Statement

The options have `diagnosticLevel` and `debug`, see We have diagnosticLevel and Debug see https://github.com/getsentry/sentry-cocoa/blob/7cf0f7441aed40e4c344404d10172547fb3edd4a/Sources/Sentry/Public/SentryOptions.h#L33-L39, but we don't have the possibility for a custom implementation, but not `DiagnosticLogger` as, for example, [.NET](https://docs.sentry.io/platforms/dotnet/configuration/diagnostic-logger/).

### Solution Brainstorm

Add DiagnosticsLogger to the Cocoa SDK and also update the docs.

**Comment by bruno-garcia** [comment]
I'm not sure it's all that useful for Cocoa since it's pretty standard: It logs on xcode and also on the Mac console.
The other SDks vary a lot (IIS has no console to see logs, WPF either) so there a custom implementation is often used by customers
