### ISSUE TITLE
A huge amount of OOM events

### ISSUE THREAD

**Issue by kolyan94** [getsentry/sentry-cocoa#1618]
### Environment

How do you use Sentry? 
- Sentry SaaS (sentry.io)

Which SDK and version?
- "@sentry/react-native": "3.2.10"

### Steps to Reproduce
We getting a huge amount of "The OS most likely terminated your app because it overused RAM." events (part of them were from a simulator). 
We didn't find any issue with RAM, but fortunately found one easy way to reproduce it (may not that triggers most of the events):
1. Launch the app from the Home screen
2. While the app is open try to build it through Xcode
3. When Xcode reopens the app we should get a new OOM event.

We don't think that this way is the main one, but unfortunately, we found only this one  =(
### Expected Result

These events shouldn't trigger.

### Actual Result

We got a huge amount of OOM events

Similar issues:
[#1830](https://github.com/getsentry/sentry-react-native/issues/1830)
[#1338](https://github.com/getsentry/sentry-cocoa/issues/1338)

**Comment by nomi9995** [comment]
I am also using the same version and have the same issue.
`"@sentry/react-native": "3.2.10"`

**Comment by philipphofmann** [comment]
When there is no debugger attached and you click run in Xcode for an already running app, Xcode kills the app and the SDK thinks it is an OOM. Checking [`previousAppState.isDebugging`](https://github.com/getsentry/sentry-cocoa/blob/9854751b5b685a0126a88a76ce4b04f0e5f4515c/Sources/Sentry/SentryOutOfMemoryLogic.m#L62) or the `previousAppState` wouldn't work, because the debugger is not attached. Ideally, we should find a way to know if Xcode killed the app.

**Comment by philipphofmann** [comment]
We also get false OOMs for our UI tests in Saucelab. Maybe this is related.
<img width="1275" alt="Screen Shot 2022-01-26 at 16 20 56" src="https://user-images.githubusercontent.com/2443292/151191643-c9ab3553-4f4b-4f66-aa61-95c2f3a2a262.png">

**Comment by TomasSestak** [comment]
happens on 3.2.13 version, could it be by defining tracesSampleRate in options of init function?
or by adding package `date-fns` ?

**Comment by philipphofmann** [comment]
The `tracesSampleRate` has no impact on OOM events. You can use `beforeSend` to drop OOMs events if you want, @TomasSestak.

**Comment by TomasSestak** [comment]
> 

Thanks for clarification. In our case it crashes the app so I will try to debug it somehow

**Comment by TomasSestak** [comment]
> The `tracesSampleRate` has no impact on OOM events. You can use `beforeSend` to drop OOMs events if you want, @TomasSestak.

Thanks for clarification. In our case it crashes the app so I will try to debug it somehow

**Comment by philipphofmann** [comment]
@TomasSestak, @numandev1, @namvoeh, @kolyan94, we didn't see any updates for a long time on this issue, and we did plenty of fixes for OOM. I consider this to be fixed. Please reopen the issue or create a new one if you still experience problems.
