### ISSUE TITLE
Stackframe by address

### ISSUE THREAD

**Issue by PaulWoitaschek** [getsentry/sentry-cocoa#1623]
### Problem Statement

I want to integrate kotlin multiplatform crashes with sentry.
Currently the support is not good as it just shows all issues labeled as "OutOfMemory" without any helpful message and with no stacktrace.

### Solution Brainstorm

To workaround that it should be possible to use create stacktrace frames by address.

Here is how it's currently possible with firebase:
[stackFrameWithAddress](https://github.com/touchlab/Kermit/blob/805f2cab43aefadb406bb10943300e0f68d9e80e/kermit-crashlytics/src/darwinMain/kotlin/co/touchlab/kermit/crashlytics/CrashlyticsLogWriter.kt#L58)

On firebase you can now see the actual stacktrace coming from kotlin.

**Comment by philipphofmann** [comment]
Thanks for opening up this issue. We already have an issue for this see https://github.com/getsentry/sentry-cocoa/issues/924. Please upvote there so we can give it a higher priority.
