### ISSUE TITLE
Crash inside SentryCrashJSONCodec

### ISSUE THREAD

**Issue by Overcot** [getsentry/sentry-cocoa#1628]
### Platform

iOS

### installed

Swift Package Manager

### Version

7.7.0

### Steps to Reproduce

1. Receive reports from MXMetricManagerSubscriber
2. Send them to Sentry using addBreadcumb like this:
```swift
  // Receive daily metrics
  #if os(iOS)
  public func didReceive(_ payloads: [MXMetricPayload]) {
    guard SentrySDK.isEnabled else { return }
    for payload in payloads {
      let breadCumb = Breadcrumb(level: .info, category: "MetricKit")
      breadCumb.message = "Did Receive metric payloads"
      let json = try? JSONSerialization.jsonObject(with: payload.jsonRepresentation(), options: []) as? [String: Any]
      breadCumb.data = json
      SentrySDK.addBreadcrumb(crumb: breadCumb)
    }
  }
  #endif
```
3. Sometimes (not always) I receive crash inside encoding

### Expected Result

Doesn't crash

### Actual Result
<img width="983" alt="Screenshot 2022-01-13 at 14 40 34" src="https://user-images.githubusercontent.com/13967242/149323899-cf1b47f7-332f-468d-86cd-d5ef3bb1a110.png">

Logs: [crash.txt](https://github.com/getsentry/sentry-cocoa/files/7862416/crash.txt)

**Comment by brustolin** [comment]
Hello @Overcot. Thanks for reporting this.

Do you mind sharing the content of the payload when the crash happens?
Would be easier to investigate the problem if we know what is in the `data` property of the breadcrumb.
