### ISSUE TITLE
Internal crash on SentryNetworkTrackingIntegration

### ISSUE THREAD

**Issue by 39otrebla** [getsentry/sentry-cocoa#1633]
### Platform

iOS

### installed

CocoaPods

### Version

7.7.0

### Steps to Reproduce

Integrate Sentry in ReactNative using default settings and run the app making sure to do some network requests.

### Expected Result

Sentry shouldn't have internal crashes.

### Actual Result

The following internal crash happens:
```
EXC_BAD_ACCESS
CXX: calling C++ destructors for class %s > release >
Attempted to dereference null pointer.
```

It does seem to come from `SentryNetworkTrackingIntegration.m:83`. We are quite sure It appeared on version 7.7.0 as we are using Sentry for over a year by now (with dozens millions of sessions) and we never experienced it. Please find the trace attached.

[47fc6663115349b59aceef89536f39ae-symbolicated.crash.zip](https://github.com/getsentry/sentry-cocoa/files/7871124/47fc6663115349b59aceef89536f39ae-symbolicated.crash.zip)

**Comment by brustolin** [comment]
@39otrebla  Thanks for letting us know.

I'll investigate this.

**Comment by brustolin** [comment]
Hey @39otrebla. Sorry for the delay, I cannot reproduce this problem. Is this happening in production or during development? Do you know how often this happens?

**Comment by philipphofmann** [comment]
@39otrebla can you maybe reply to the question above, please?

**Comment by philipphofmann** [comment]
@39otrebla, do you still see the issue in the latest release? We did some fixes, and I think your problem should be solved already.

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we will close this issue. Feel free to open it again.
