### ISSUE TITLE
Is Event.fetchStacktrace() no longer required in 3.0.1?

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cocoa#164]
Trying to upgrade to Sentry 3.0.1...is this code no longer required to get stacktraces on crash reports?

```
		sentryClient.beforeSendEventBlock = { event in
			event.fetchStacktrace()
		}
```

**Comment by HazAT** [comment]
Hey, it works a bit different now.
https://docs.sentry.io/clients/cocoa/advanced/#adding-stacktrace-to-message

**Comment by edenman** [comment]
@HazAT thanks, that makes sense for manually-sent messages.  For crashes, does Sentry now automatically attach the stacktrace?

**Comment by HazAT** [comment]
yeah, it always did. So there is nothing todo here.
