### ISSUE TITLE
3.0.1: "KSCrashHandler not started - Make sure you added KSCrash as a dependency"

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cocoa#165]
_Platform:_
- [X]  iOS

_Swift:_
- [X]  Yes -> If yes, which version? 3.0

_sentry-swift installed with:_
- [X] Cocoapods

Version of sentry-swift:
**3.0.1**

---
I have following issue:

Trying to upgrade to 3.0.1 using cocoapods.

Podfile.lock has these two versions:
```
  - Sentry (3.0.1):
  - KSCrash (1.15.8):
```
AppDelegate is doing this:
```
		let sentryClient = try! Client(dsn: "https://3abf4e0e22a54be38b7300ea5d713616:df00fe703107459a905fe2d13f6edf33@sentry.io/71464")
		Client.shared = sentryClient
		sentryClient.breadcrumbs.maxBreadcrumbs = 100
		try! sentryClient.startCrashHandler()
```
Logs:
```
2017-06-02 17:18:36.246 recharge-consumer-ios[95962:1090086] Sentry Started -- Version: 3.0.1
2017-06-02 17:18:36.247 recharge-consumer-ios[95962:1090086] Sentry - Error:: KSCrashHandler not started - Make sure you added KSCrash as a dependency
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=SentryErrorDomain Code=101 "KSCrashHandler not started - Make sure you added KSCrash as a dependency" UserInfo={NSLocalizedDescription=KSCrashHandler not started - Make sure you added KSCrash as a dependency}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.51/src/swift/stdlib/public/core/ErrorType.swift, line 182
```

Do I need to call something to actually initialize KSCrash?  From looking at the code it's just doing `#if __has_include(<KSCrash/KSCrash.h>)`, which _should_ work?

**Comment by edenman** [comment]
Tried adding a call to `KSCrash.initialize()` before the sentry initialization code: still no luck.

**Comment by HazAT** [comment]
Hey, thx for reporting.
Working on a fix for that.

**Comment by HazAT** [comment]
Can you make sure you `Podfile` looks something like this ...
```
pod 'Sentry', :subspecs => ['Core', 'KSCrash']
```
It's important that you install sentry with KSCrash a subspec.

**Comment by edenman** [comment]
Yup, that was totally it.  Missed that in the new docs.  Maybe worth putting together a migration doc for 3.0?

**Comment by HazAT** [comment]
yeah will do that.

**Comment by RayoRavi** [comment]
I'm trying to integrate Sentry into my framework and having the same issue. The problem is that I can not use the Cocoapod. I have manually included both Sentry and KSCrash into my framework but seems like I have missed something. Any suggestions?
