### ISSUE TITLE
Is there a way to access the options if not initing the SDK automatically for Hybrid SDKs? 

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1665]
### Problem Statement

See https://github.com/getsentry/sentry-react-native/blob/b8169cf6ceee8a2df5b138091e8d8766943a2574/ios/RNSentry.m#L75
and https://github.com/getsentry/sentry-react-native/blob/b8169cf6ceee8a2df5b138091e8d8766943a2574/ios/RNSentry.m#L130-L137

So options are only cached if the SDK is inited. automatically by the Hybrid SDK.
The thing is, the Hybrid SDK allows to not init. the SDK automatically, See https://github.com/getsentry/sentry-react-native/blob/b8169cf6ceee8a2df5b138091e8d8766943a2574/src/js/options.ts#L27-L38

So every feature that depends on the `options` to be cached, won't work.
The same for Flutter, found out by PoCing https://github.com/getsentry/sentry-dart/issues/265

### Solution Brainstorm

Java has the concept of `HubAdapter` which can be achieved by `HubAdapter.getInstance().getOptions()`, this is not considered a Public API.

**Comment by philipphofmann** [comment]
Sorry, I don't fully understand what we want to achieve here. What exactly do you mean by caching the options? What does `HubAdapter.getInstance().getOptions()` return if you don't initialize the SDK. Some default options without a DSN?

**Comment by marandaneto** [comment]
@philipphofmann `HubAdapter.getInstance().getOptions()` returns an [empty](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/NoOpHub.java#L176-L179) options since the Hub is also `NoOpHub`.
If the SDK is inited. then it returns the real options from the Hub.

We'd like to support the [manual Native initialization](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) and for that, we'd need to know the cache dir path that comes from the native SDK, but if somebody has to init. the Native SDK manually, we don't have access to the options nor to the cache dir path.

**Comment by brustolin** [comment]
Would a new function in `PrivateSentrySDKOnly` class that returns the current option or an empty one solve this?

**Comment by marandaneto** [comment]
> Would a new function in `PrivateSentrySDKOnly` class that returns the current option or an empty one solve this?

Yes, that's the goal of this issue.
