### ISSUE TITLE
How to access the installation ID for Hybrid SDKs?

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1666]
### Problem Statement

Context https://github.com/getsentry/sentry-dart/issues/759
Related to https://github.com/getsentry/sentry-react-native/issues/2084

https://github.com/getsentry/sentry-dart/issues/759#issuecomment-1044205048
https://github.com/getsentry/sentry-dart/pull/761/files#r810656571

The `installation ID` isn't set in the Scope, nor I can access it.

This affects Hybrid SDKs, as RN and Flutter

### Solution Brainstorm

Ideally, either there's a Hybrid Public API to access this info, or the installation id is already set in the scope as a fallback.

**Comment by brustolin** [comment]
We could add this to `PrivateSentrySDKOnly` class

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-cocoa/pull/1680
