### ISSUE TITLE
Setting traces sample rate results in accent color of SwiftUI app not being respected

### ISSUE THREAD

**Issue by Obbut** [getsentry/sentry-cocoa#1668]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.9.0

### Steps to Reproduce

1. Set a custom accent color via the asset catalog by setting a build option like `ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor`
2. Add `options.tracesSampleRate = 1.0` in call to `SentrySDK.start { options in`
3. Open a SwiftUI sheet
4. Observe the accent color of the views in the sheet

### Expected Result

Setting the traces sample rate does not change the accent color of the app.

### Actual Result

When setting the traces sample rate to `1.0`, the accent color of the app is set to the iOS default (blue). After commenting the traces sample rate, with no other changes to the project, the accent color works correctly again.

Due to NDA of the project I'm working on, I'm not able to share a screenshot/video at this moment but if required I can try to reproduce this in a self-contained project later.

**Comment by bruno-garcia** [comment]
Until we can debug through a repro, to help us narrow down what can be happening here: Does this happen on a simulator or real device or both?
What iOS version?

**Comment by caseybutatwork** [comment]
I am having this issue, as well. Here is a [sample project](https://github.com/caseybutatwork/SentrySwiftUIAccentColor/tree/main).

Please let me know how to resolve this issue. It is appearing simply by initializing Sentry in my app.
