### ISSUE TITLE
dyld: Library not loaded: /Library/Frameworks/Sentry.framework/Sentry

### ISSUE THREAD

**Issue by st3fan** [getsentry/sentry-cocoa#167]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 3.1 / Xcode 8.3.2
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [x] Carthage
- [ ] Manually

Version of sentry-swift:
**3.0.1**

---
I have following issue:

I replaced sentry-swift with sentry-cocoa in my Cartfile and modified our integration code to match the new naming (Client vs SentryClient). THings build and link without errors, but when I start the application in the Simulator, I get:

```
dyld: Library not loaded: /Library/Frameworks/Sentry.framework/Sentry
  Referenced from: /Users/sarentz/Library/Developer/CoreSimulator/Devices/0C0A4BF2-FE4D-4C60-9C88-60BA155D1D3E/data/Containers/Bundle/Application/D898F826-5DDD-406C-B2AB-3BB9F9B180EB/Client.app/Client
  Reason: image not found
```

It is a bit suspicious that the path is `/Library/Frameworks/` .. not sure what to do ..

**Comment by HazAT** [comment]
Hey, thx for reporting.
Working on a fix for that.

**Comment by MihaelIsaev** [comment]
The same here.. :(

**Comment by HazAT** [comment]
Hey, I've just released `3.0.3` which fixes the framework and includes KSCrash.
Please note that if you use Carthage you no longer need KSCrash as a separate dependency because we had to bundle it into `Sentry.framework` to work.
This is also the preferred way if you include Sentry manually.

**Comment by st3fan** [comment]
@HazAT What do I do now with the following code that I have:

```
    var crashedLastLaunch: Bool {
        return KSCrash.sharedInstance().crashedLastLaunch
    }
```

KSCrash is not a framework that I can link against anymore, so how do I access the `KSCrash` singleton?

**Comment by st3fan** [comment]
Oh nevermind, I see `crashesLastLaunch` moved into `Client`.

**Comment by HazAT** [comment]
Please feel free to close the issue if it's working, ty.

**Comment by HazAT** [comment]
I will close this for now since I am pretty sure this is fixed by now.
