### ISSUE TITLE
Offline caching improvements - Delay between and backoff when 429 is on

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1671]
### Description

The SDK guideline has a couple of new items regarding offline caching: https://github.com/getsentry/develop/pull/509

1. If rate-limit was hit, make sure the caching transport is aware. Meaning: don't read all files from disk to send to the HTTP transport when that's basically dropping everything due to rate-limit
2. Add a delay when reading from disk to avoid bursts of events which could trigger rate limit
3. Once the device is back online, read events preciously cached (as opposed to send only on restart or when a new event is captured)

Relates to:
* https://github.com/getsentry/sentry-dotnet/issues/1504 
* https://github.com/getsentry/sentry-java/issues/1926

**Comment by philipphofmann** [comment]
> If rate-limit was hit, make sure the caching transport is aware. Meaning: don't read all files from disk to send to the HTTP transport when that's basically dropping everything due to rate-limit

I think one central point of rate-limiting is that if one is active, we should read all files from disk and throw them away. Otherwise, we going to hit another rate limit the next time we try to send all envelopes. @marandaneto, do you agree?

**Comment by marandaneto** [comment]
> we should read all files from disk and throw them away.

I don't think we should throw them away, the comment is about making the transport aware that there's rate limiting going on, so you should back off for a while and don't even try to read/send them for a while.

**Comment by philipphofmann** [comment]
> > we should read all files from disk and throw them away.
> 
> I don't think we should throw them away, the comment is about making the transport aware that there's rate limiting going on, so you should back off for a while and don't even try to read/send them for a while.

The envelopes could pile up if you keep them in the cache while a rate limit is active. Once the rate limit times out, the SDK could spam the server with the piled-up envelopes, leading to another rate limit. Then you end up in a vicious cycle. @marandaneto
