### ISSUE TITLE
Try to capture memory footprint for OOMs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1672]
### Description

We could register for [applicationDidReceiveMemoryWarning](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623063-applicationdidreceivememorywarni) and store the memory footprint to the [AppState](https://github.com/getsentry/sentry-cocoa/blob/cb117ceaf5bb343a72635e3079269185a75b09b8/Sources/Sentry/SentryAppState.m). When creating the OOM event we could attach the memory footprint.

**Comment by bruno-garcia** [comment]
The problem is that this value is very likely to be incorrect, we'd need to be very clear that's the "last detected memory footprint". And test this works well enough: Allocate until the event is raised. Then go way beyond it until it crashes: What's the memory usage that caused the crash vs what we stored?

**Comment by philipphofmann** [comment]
Because of 

> The problem is that this value is very likely to be incorrect, we'd need to be very clear that's the "last detected memory footprint"

we close this feature and try to add breadcrumbs to OOMs with this feature https://github.com/getsentry/sentry-cocoa/issues/1759.

**Comment by eric** [comment]
This still would be very helpful to have the last known memory usage, even if it is 1 second old, it would be useful in understanding if something actually was likely a memory usage issue or not.

The sorts of leaks we see in our app tend to be slow leaks, not situations where we go from 200mb used to 2gb used within a second.

In our own app logs we log the current memory usage on each log line and have found some OOM crashes in Sentry that are from situations where there's only 400mb of memory used right before the crash which make us believe it wasn't actually memory related. 

Being able to separate actual memory issues from others would be very helpful for us.

**Comment by philipphofmann** [comment]
Thanks for the input, @eric. I'm not sure if you can guarantee that it was no OOM if you only use 400MB of memory. I agree that capturing the memory footprint for memory leaks could help as they tend to grow slowly, as you pointed out. Wouldn't periodically storing breadcrumbs on disk and attaching them to OOMs help more as pointed out here https://github.com/getsentry/sentry-cocoa/issues/1759? We could add the current memory footprint when receiving `UIApplicationDidReceiveMemoryWarningNotification`.
