### ISSUE TITLE
IP sent when isSendDefaultPii disabled

### ISSUE THREAD

**Issue by ennioma** [getsentry/sentry-cocoa#1673]
### Platform

iOS

### Installed

CocoaPods

### Version

7.9.0

### Steps to Reproduce

We have set the following option

```
options.isSendDefaultPii = false
```

even though by default it should be false.

### Expected Result

IP address not shown in event details

### Actual Result

IP address is shown in event details

**Note:** Same implementation for Android worked fine.

**Comment by bruno-garcia** [comment]
Sentry is using the IP address of the connection.
You can turn that off in Sentry in the project settings:

![image](https://user-images.githubusercontent.com/1633368/156222516-935c0753-5f41-4f1b-b34d-f55745b075fc.png)

Sentry does that for JavaScript and iOS events out of the box, the other platforms this is not done on the server so the client-side `SendDefaultPii` toggles a `{{auto}}` string the SDK adds to the `user.ipAddress` field which instructs the server to use the IP address or not.

It seems we haven't documented the specific case for iOS here yet: v

**Comment by philipphofmann** [comment]
We have this documented in code, see https://github.com/getsentry/sentry-cocoa/blob/1c5c95da2ee12e9b075a947c2956916773d98c45/Sources/Sentry/Public/SentryOptions.h#L170-L174

I'm going to add a note to the docs as well.

**Comment by philipphofmann** [comment]
PR for docs https://github.com/getsentry/sentry-docs/pull/4786.

**Comment by philipphofmann** [comment]
Does this sum it up @bruno-garcia? https://github.com/getsentry/sentry-cocoa/pull/1674
