### ISSUE TITLE
Add an option to choose which view controllers should be swizzled 

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1677]
### Problem Statement

The SDK is arbitrarily swizzling only (and all) view controllers classes in which name contains 'ViewController'.

### Solution Brainstorm

Would be nice to have an option, maybe a callback, to configure which view controller classes would be swizzled.

**Comment by philipphofmann** [comment]
Callback could be maybe costly. We can't control what users do in that callback. The callback will be called for every class in the app image. Maybe a string or a list of strings that the class name should contain would be better.

**Comment by philipphofmann** [comment]
Why did you close this @brustolin? If we can prevent them from writing lousy code, I think we should.

**Comment by brustolin** [comment]
> Why did you close this @brustolin? If we can prevent them from writing lousy code, I think we should.

Wrong button. Sorry.

**Comment by philipphofmann** [comment]
We don't think that this is necessary right now. If we hear from users, that this is needed, we can easily open this issue again or open a new one.
