### ISSUE TITLE
crash reports not being sent from M1 macs running macOS Monterey

### ISSUE THREAD

**Issue by jeffpferreira** [getsentry/sentry-cocoa#1679]
### Platform

macOS

### Installed

CocoaPods

### Version

7.10.0

### Steps to Reproduce

I have three test machines:

1) M1 Mac Mini running Monterey
2) M1 Mac Mini running Big Sur
3) 2020 13-inch Intel MacBook Pro running Monterey

My app is written in Swift. I added some code to my app such that it would dereference a `nil` pointer when I clicked a button. I then installed the app on each test machine. I launch the app and click the button to cause a crash. On each machine the app crashes as expected. I then re-open the app.

### Expected Result

I expect each machine to send 1 crash report.

### Actual Result

On machines (2) and (3) I can see a crash report sent, and the crash report does appear in the backend when I log into Sentry in my web browser. The macOS logs look like this:

```
(Sentry) Sentry - debug:: SDK initialized! Version: 7.10.0
(Sentry) Sentry - debug:: Reading from session: /Users/user/Library/Caches/io.sentry/<uuid>/session.current
(Sentry) Sentry - debug:: Integration installed: SentryCrashIntegration
< lots of output from Sentry follows >
(Sentry) Sentry - debug:: Sent 1 crash report(s)
```

But on machine (1), running the same app, no crash report is sent:

```
(Sentry) Sentry - debug:: SDK initialized! Version: 7.10.0
(Sentry) Sentry - debug:: Reading from session: /Users/user/Library/Caches/io.sentry/<uuid>/session.current
(Sentry) Sentry - debug:: Sent 0 crash report(s)
(Sentry) Sentry - debug:: Integration installed: SentryCrashIntegration
```

Notice that the `Sent N crash report(s)` message is appearing significantly earlier in the log output on the machine which doesn't send the crash report.

**Comment by brustolin** [comment]
Hello @jeffpferreira. Thanks for reaching out.
I could not reproduce this behavior. 
Can you share this test project with us?

**Comment by jeffpferreira** [comment]
Hi @brustolin. After some further testing, it appears the bug only happens with certain types of crashes.

```
// This DOES produce an error report
let error = NSError(domain: "MyErrorDomain", code: 1, userInfo: nil)
SentrySDK.capture(error: error)

// This DOES produce an error report
let a: [String] = []
let b = a[0]

// This does NOT produce an error report
let a: NSView! = nil
let b = a.isHidden
```

My app is built with Xcode 13.1 and I have reproduced this on two different Macs:

- M1 Mac Mini, macOS 12.2.1
- M1 Pro MacBook Pro, macOS 12.1

Are there any logs I can gather for you? Can you recommend any debugging steps I can take to help diagnose the issue?

**Comment by brustolin** [comment]
That is trick. I don't know a way to debug the capture of this type of error. 
And I still can't reproduce the problem even with the code you suggested.
If you could share with us some test project that you can reproduce the problem would help a lot.

@philipphofmann any suggestion?

**Comment by jeffpferreira** [comment]
@brustolin @philipphofmann I will work on getting you a test project this week. In the meantime I wanted to provide you with a quick update that may help your debugging. I updated my app to use Sentry 7.10.2 and I still see the problem. Except now the Sentry debug log output is slightly different:

```
Sentry - debug:: SDK initialized! Version: 7.10.2
Sentry - debug:: Reading from session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.current
Sentry - debug:: Writing session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.crashed
Sentry - debug:: Deleting session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.current
Sentry - debug:: Sent 0 crash report(s)
Sentry - debug:: Integration installed: SentryCrashIntegration
```

As you can see, Sentry did write the `session.crashed` report, but it didn't send it. If I look at the referenced file I see this (some information redacted)

```
{
  "errors": 0,
  "status": "crashed",
  "started": "2022-03-14T22:30:07.411Z",
  "did": "my-did",
  "duration": 35.86991202831268,
  "sid": "my-sid",
  "attrs": {
    "release": "<my app's bundle ID and build version>"
  },
  "timestamp": "2022-03-14T22:30:43.281Z",
  "seq": 2
}
```

I suspect the issue I am seeing is some kind of race condition between the part of Sentry that creates the crash report and the part of Sentry which looks for crash reports to send. Sometimes a `session.crashed` file is created, sometimes not. And in both cases no crash reports are sent to the backend.

As I create the test project for you I will try to add some tracing to better understand if there is a race condition.

**Comment by philipphofmann** [comment]
Thanks for the update @jeffpferreira. We end the current session as crashed if there was a crash or an OOM (out of memory) on the previous run
https://github.com/getsentry/sentry-cocoa/blob/4bd575aeb9949363c33af2a4bfcfd9328c6f39a6/Sources/Sentry/SentrySessionCrashedHandler.m#L30-L33

The following logs originate from the method above.
```
Sentry - debug:: Reading from session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.current
Sentry - debug:: Writing session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.crashed
Sentry - debug:: Deleting session: /Users/jeff/Library/Caches/io.sentry/<uuid>/session.current
```

`Sentry - debug:: Sent 0 crash report(s)` stems SentryCrashInstallationReporter.
https://github.com/getsentry/sentry-cocoa/blob/4bd575aeb9949363c33af2a4bfcfd9328c6f39a6/Sources/Sentry/SentryCrashInstallationReporter.m#L44-L45

It can be that our OOM logic detected an OOM on a previous run. This is also going to end the current session as crashed. When we detect an OOM we don't send a crash report from SentryCrash and the log output is `Sentry - debug:: Sent 0 crash report(s)`. Instead, we send an OOM here https://github.com/getsentry/sentry-cocoa/blob/4bd575aeb9949363c33af2a4bfcfd9328c6f39a6/Sources/Sentry/SentryOutOfMemoryTracker.m#L77-L92

**Comment by jeffpferreira** [comment]
@philipphofmann Thanks for the suggestion about the OOM tracker. My app is a macOS app, and according to Sentry's documentation the OOM tracker is not enabled for macOS apps. To be sure, I now start the Sentry SDK with `options.enableOutOfMemoryTracking = false`. I also updated Sentry to version 7.11.0.

With both of these changes made, I am still experiencing the issue of some crash reports not being generated and/or sent to the crash reporting service backend on my M1 Mac computers.

I did take some time to develop a test project, but in the test project the problem could not be reproduced. I think this lends evidence that the issue is some timing or race condition that is triggered by some unknown set of conditions in my main app.

As a separate experiment, I compiled my main app as Intel only rather than as a Universal bundle. Since it was compiled as Intel only, the app would run through Rosetta on my M1 mac mini. In this configuration, the problem could not be reproduced. The timing or race condition must be different under Rosetta.

I'll continue to refine my test project and also collect more information about a possible race condition in my main app. In the meantime if anything should come to your mind about what I can try then please let me know.

**Comment by philipphofmann** [comment]
Thanks for the update, @jeffpferreira. It could be that somehow SentryCrash is not able to find the crash report `Sentry - debug:: Sent 0 crash report(s)`. We have to do some further investigations. I'm not sure yet what is causing this.

**Comment by philipphofmann** [comment]
@jeffpferreira, we have trouble reproducing this. Do you have any updates on the test project?

**Comment by jeffpferreira** [comment]
This week I will update my test project, as well as my real app, to Sentry version 7.13 and try to reproduce the issue.

**Comment by jeffpferreira** [comment]
@philipphofmann @brustolin I just updated my main app to Sentry 7.13.0 and this issue is gone. I am now getting all the crash reports I expect from the M1 Macs I have tested on. Thank you so much for your time.
