### ISSUE TITLE
WITH_KSCRASH is dependent on SentryDefines - but is often imported before it

### ISSUE THREAD

**Issue by orta** [getsentry/sentry-cocoa#168]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-swift installed with:_
- [x] Cocoapods
- [ ] Carthage
- [ ] Manually

Version of sentry-swift:
**3.x.x**

---
I have following issue:

With react-native-sentry (0.11.6) and sentry (core + KSCrash, 3.0.2) installed as pods using static libraries I get a lot of build errors. I'll take one file which looks a bit like this:

![screen shot 2017-06-05 at 09 39 39](https://cloud.githubusercontent.com/assets/49038/26776925/3487370c-49d3-11e7-8ba6-e3522972dc4e.png)

I first thought to add this flag [via CocoaPods](https://github.com/getsentry/sentry-cocoa/compare/master...orta:orta-podspec-use-xcconfig?expand=1) but when that didn't work I dug in.

This is because `#if WITH_KSCRASH` is not passing the first time and `KSCrashInstallation+Private` is not being read, but later it is passing and the code is expected to be there.

This is because `WITH_KSCRASH` is defined inside `SentryDefines` which isn't added into the compiler settings until something inside the `Sentry/XXX` dependencies refers to it.

---

I initially thought that moving the KSCrash imports below would fix it,

```objc
#if __has_include(<Sentry/Sentry.h>)

#import <Sentry/SentryKSCrashInstallation.h>
#import <Sentry/SentryKSCrashReportSink.h>
#import <Sentry/SentryLog.h>

#else
#import "SentryKSCrashInstallation.h"
#import "SentryKSCrashReportSink.h"
#import "SentryLog.h"
#endif

#if WITH_KSCRASH
#import <KSCrash/KSCrash.h>
#import <KSCrash/KSCrashInstallation+Private.h>
#endif
```

but that didn't, which was a bit odd to me: `Sentry/SentryLog.h`does refer to `SentryDefines`. Long answer short, I needed to explicitly include `#import <Sentry/SentryDefines.h>` _at the top_ of the imports inside the `__has_include`.

Honestly, I'm not 100% sure why that's important. However it does fix it, and I'm going to make a PR now 👍

**Comment by luka1995** [comment]
Please push this commit to master branch, I can't pull... 👍  :)
