### ISSUE TITLE
SDK Rate limit handling

### ISSUE THREAD

**Issue by gscalzo** [getsentry/sentry-cocoa#1684]
### Problem Statement

This isn't a feature request, but asking for a behaviour clarification.
My understanding is that the plan has a rate limit: what happens if this limit is hit? the events are parked to be sent later?
Can the SDK configured to skip the events for example?
Or skip events if the same message has already been sent multiple time "recently"?
I'm thinking of a potential bung where the same message is sent in a loop, hitting quickly the rate limit for all the clients.

### Solution Brainstorm

No solution here, but I'd like to know your thoughts on this scenario, and if it something that was raised by other users of Sentry for mobile

**Comment by philipphofmann** [comment]
Sorry for the late reply, @gscalzo. I guess you should find the answer here https://docs.sentry.io/product/accounts/quotas/.

**Comment by philipphofmann** [comment]
@gscalzo, did the docs answer your question?

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we will close this issue. Feel free to open it again.
