### ISSUE TITLE
Crash on sentry launch

### ISSUE THREAD

**Issue by HugoSay** [getsentry/sentry-cocoa#1690]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.10.1

### Steps to Reproduce

Launching the SDK causes a crash since we updated from 7.10.0 to 7.10.1

here is the exception: 
```
2022-03-11 16:18:50.351486+0100 REDACTED-[25432:10134020] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithCString:encoding:]: NULL cString'
*** First throw call stack:
(0x180d890fc 0x1995d9d64 0x1825448b4 0x10435f420 0x10435f1c8 0x104342760 0x104346940 0x10434502c 0x1043450d0 0x10253c048 0x10253bd8c 0x10253ceb4 0x102561f8c 0x198987134 0x1989fa3e4 0x102561e08 0x19898e3a0 0x19899474c 0x19897052c 0x198981b14 0x1989941c8 0x198981b14 0x1989941c8 0x198981b14 0x1989941c8 0x198981b14 0x1989941c8 0x198981b14 0x1989941c8 0x198981b14 0x19898ce2c 0x19899474c 0x19897052c 0x198981b14 0x198975434 0x1989793d4 0x1989732bc 0x1989936e4 0x1989b31b0 0x19897cc74 0x1989760bc 0x198997034 0x198986938 0x198970218 0x198971714 0x10270980c 0x10270b120 0x1022f6ccc 0x10acb86d4 0x10acba3b4 0x10acca898 0x180d41d84 0x180cfbf5c 0x180d0f468 0x19c8b338c 0x1836b25d0 0x183430f74 0x1024d5d94 0x10ad6daa4)
libc++abi: terminating with uncaught exception of type NSException
		dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
		*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithCString:encoding:]: NULL cString'
		terminating with uncaught exception of type NSException
```

### Expected Result

No crash

### Actual Result

crash

**Comment by HugoSay** [comment]
looks related to https://github.com/getsentry/sentry-cocoa/pull/1670 ^^'

**Comment by bruno-garcia** [comment]
Thanks for raising this @HugoSay, we'll get to this asap. We could really benefit from a repro.
Came up on Discord too: https://discord.com/channels/621778831602221064/817382542935457793/951791239420858438

**Comment by jam90** [comment]
@bruno-garcia here the files you requested on discord, just a small recap:

We face this crash too, specifically on ios 12 (from ios 13 and above works like a charm).
We subclass the UIApplication in file `main.swift` and we have configured the AppDelegate as the files attached.
[main.swift+AppDelegate.zip](https://github.com/getsentry/sentry-cocoa/files/8243063/main.swift%2BAppDelegate.zip)

**Comment by philipphofmann** [comment]
Thanks, @jam90. I think the problem should be around here https://github.com/getsentry/sentry-cocoa/blob/14cd42138c6ee51d2b2957f780fe15c916e9b531/Sources/Sentry/SentryUIViewControllerSwizzling.m#L124-L125.

**Comment by jam90** [comment]
> Thanks, @jam90. I think the problem should be around here
> 
> https://github.com/getsentry/sentry-cocoa/blob/14cd42138c6ee51d2b2957f780fe15c916e9b531/Sources/Sentry/SentryUIViewControllerSwizzling.m#L124-L125

Yes it's exactly there the problem, it gets nil with `stringWithCString`

**Comment by philipphofmann** [comment]
I wonder why `class_getImageName([app.delegate class]` returns `NULL.` I'm close to opening up a PR to fix the crash, but we won't be able to swizzle when this happens.

**Comment by philipphofmann** [comment]
Hey @jam90, we are going to fix the crash with https://github.com/getsentry/sentry-cocoa/pull/1692, but with this solution we won't be able to swizzle your UIViewControllers on iOS 12. Can you maybe add more information here https://github.com/getsentry/sentry-cocoa/issues/1693 to let us know how we can reproduce `class_getImageName([app.delegate class]` returning `NULL`.
