### ISSUE TITLE
Ability to pass stacktrace

### ISSUE THREAD

**Issue by orbitekk** [getsentry/sentry-cocoa#1691]
### Problem Statement

Hello, I have an app and I'm working on error handling. I need a feature to pass stacktrace to SentrySDK.

The architecture of my app looks like below:
```
ViewController -> ViewModel -> UseCase -> Repository -> Endpoint
```

Every class in this chain may throw an error. I'd like to log that error and show proper message to a user. I think the best place to put this code is a service that is used by view model but there is a problem: when I try to log that error using `record(error:)` method I don't have a proper stacktrace if the error comes from endpoint (or any other layer such as repository or use case) because stacktrace is gathered when we call `record(error:)`. Endpoints and repositories are located in separate libraries and I don't want to import Sentry.framework to those libraries.

I need a feature that will give me ability to pass stacktrace that is gathered when the error occurs. Currently it' not possible :(

### Solution Brainstorm

`SentryStacktrace` can be attached to `Event` but `SentryStacktraceBuilder` isn't public so creating `SentryStacktrace` is quite difficult. Even if `SentryStacktraceBuilder` is public, I need a dependency to Sentry.framework.

I think the best way is to use `Thread.callStackSymbols` and build a `SentryStacktrace` based on the response from this method. Do you think it is possible? I know Firebase Crashlytics does it.

**Comment by philipphofmann** [comment]
This is related to https://github.com/getsentry/sentry-cocoa/issues/741.

**Comment by philipphofmann** [comment]
@orbitekk, can you please reply to my question above?

**Comment by orbitekk** [comment]
Yes, it's exactly what I need. Do I have to wait for v8.0?

**Comment by philipphofmann** [comment]
I'm not sure why we put https://github.com/getsentry/sentry-cocoa/issues/741 on v 8.0.0. Maybe because we are afraid of having an impact on grouping. I think we can also come up with a solution that doesn't impact grouping so we can ship it sooner. I'm going to mark this as a duplicate of https://github.com/getsentry/sentry-cocoa/issues/741.
