### ISSUE TITLE
Not able to swizzle app image UIViewControllers on iOS 12

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1693]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.10.2

### Steps to Reproduce

Enable auto performance monitoring and launch the app on iOS 12. Sadly, we don't have more details at the moment.

This issue leads to a crash on 7.10.1, see https://github.com/getsentry/sentry-cocoa/issues/1690.

### Expected Result

Somehow get the app image name to be able to swizzle its UIViewControllers.

### Actual Result

https://github.com/getsentry/sentry-cocoa/blob/14cd42138c6ee51d2b2957f780fe15c916e9b531/Sources/Sentry/SentryUIViewControllerSwizzling.m#L124-L125

`class_getImageName([app.delegate class])` returns `NULL`, we are not able to the the image name and therefore we can't swizzle the UIViewControllers.

**Comment by brustolin** [comment]
We can try to go deeper. Get the window from the delegate, then the root view controller, and then the image name from the view main view controller.

**Comment by philipphofmann** [comment]
Sadly we were not able to reproduce this on iOS 12.4, and this is not causing crashes. We are going to close this.

**Comment by philipphofmann** [comment]
We had a customer complain about this issue. Should be fixed with @2124.
