### ISSUE TITLE
Capture Screenshots for Crashes

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1721]
### Problem Statement

It would be nice to attach a screenshot when a crash occurs to the crash event.

### Solution Brainstorm

The onCrashCallback of SentryCrash points out that we can only call async-safe functions from this function and must not call Objective-C methods

https://github.com/getsentry/sentry-cocoa/blob/87f19367e052d1274ce37406e686b0a19868f976/Sources/SentryCrash/Recording/SentryCrash.h#L148-L157

Therefore, it seems to be impossible to capture a screenshot when we are crashing, especially within a signal handler. Even if we were to find C APIs that could capture the screen (e.g. CoreGraphics might have something) that still wouldn't qualify as "async safe" as the number of APIs that have that guarantee are small and they're usually very primitive APIs -- this list is for Linux and is not strictly accurate since Darwin has some differences: https://man7.org/linux/man-pages/man7/signal-safety.7.html

There might be a certain subset of crash cases where we could capture a screenshot realtime -- for example, if the crash was caused by an Objective-C exception and you're able to catch the exception (which happens outside a signal handler), it's totally safe to capture a screenshot at that point. 

One approach could be to capture screenshots in a regular time interval while the app is running, storing the screenshot in C memory and writing it to disk when crashing. We could also continuously save a screenshot to disk, but this would cause lots of IO. We need to figure out how expensive it is to store the screenshot in C memory.

**Comment by brustolin** [comment]
I think we can try to do the screen shot at the end of the error handling. If calling into objc causes the app to exit, it would exit anyway and the crash is already saved in disk.

**Comment by philipphofmann** [comment]
We should find a way to track how many users use this feature.

**Comment by brustolin** [comment]
Syncing screenshots with a UIDisplayLink, saving a copy of the image for every frame uses 10% of CPU. That's definitely a no go.

**Comment by brustolin** [comment]
iPad app has an option to allow multiple screens. 
There is no way to know which screen called the screenshot capture function from Sentry SDK automatically.

**Comment by philipphofmann** [comment]
We could try to get the screenshot after writing the crash report to disk, but we would violate the contract on [signal safety](https://man7.org/linux/man-pages/man7/signal-safety.7.html), meaning we could break other signal handlers, and the outcome of that scenario would be undefined. Such an approach is not acceptable, I think.
