### ISSUE TITLE
Include title in some events, like touch?

### ISSUE THREAD

**Issue by matthewreimer** [getsentry/sentry-cocoa#1723]
### Problem Statement

Right now when e.g. a button is tapped, it takes some sleuthing to figure out which button was tapped. Is it possible to include e.g. a view's title or tag in order to make identification easier?

### Solution Brainstorm

Right now we get this in the breadcrumb:

```
{
view: <UIButton: 0x160be6d90; frame = (0 0; 368 44); opaque = NO; tintColor = UIExtendedSRGBColorSpace 0.447059 0.670588 0.74902 1; layer = <CALayer: 0x2824adec0>>
}
```

It would be helpful if e.g. `title` and/or `tag` could be included, if not nil or 0, like this:

```
{
view: <UIButton: 0x160be6d90; frame = (0 0; 368 44); opaque = NO; tintColor = UIExtendedSRGBColorSpace 0.447059 0.670588 0.74902 1; layer = <CALayer: 0x2824adec0>>,
title: "Start",
tag: 1234
}
```

**Comment by brustolin** [comment]
This is a good idea. 
If the button does not have a title like an image button, we could use the accessibility identifier.

Thanks for the suggestion

**Comment by philipphofmann** [comment]
Yes, I think the accessibility identifier would make sense. Thanks, @matthewreimer, for the suggestion.

**Comment by matthewreimer** [comment]
Glad you like the suggestion. It could also be useful to include titles/accessibility identifiers for things like view and navigation controllers, because these titles (if present) might give more breadcrumb-like clues about what the user was doing when the crash happened.

**Comment by philipphofmann** [comment]
Yes, we could add more information for breadcrumbs on UIViewControllers. I'm going to create an extra issue for this. Thanks, @matthewreimer.

**Comment by philipphofmann** [comment]
I created an extra issue https://github.com/getsentry/sentry-cocoa/issues/1727
