### ISSUE TITLE
More information for UIViewController breadcrumbs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1727]
### Problem Statement

Right now a breadcrumb for an UIViewController.viewDidAppear only contains the name of the UIViewController. We could add more information.
<img width="523" alt="Screen Shot 2022-03-28 at 17 33 19" src="https://user-images.githubusercontent.com/2443292/160434046-f736da0d-b4ca-45a6-aab5-563f0a5e6ff2.png">

### Solution Brainstorm

Add more information like maybe accessabilityIdentifier as added with https://github.com/getsentry/sentry-cocoa/pull/1724. @brustolin can you maybe add some ideas?

**Comment by brustolin** [comment]
More ideas:
- Title

- Parent ViewController

- Presentation mode

**Comment by armcknight** [comment]
Nice, didn't know about the beforeBreadcrumb callback. That should be fine I think.

As for all the navigation related stuff, I was just thinking it could be helpful to have more context around how a user arrived at a particular VC, but I agree that just showing hex addresses of nav controllers won't be very helpful; I was thinking about a larger feature there, which I'll write a separate proposal for.

As for the window context, like which window a vc belongs to, if that's the key window, or if a VC is the root of a window, that could help provide info on if this is the first VC that was displayed after launch, or if it's visible on screen at all. That can give some context as to how important a VC is; the first one displayed after launch is much more important than one that's rendering something off screen in an invisible window; and something rendering off-screen can potentially be kicked further down the QoS ladder to a background thread if it's adversely affecting performance. 

I edited my last comment to add is `screen` the `UIScreen.mainScreen` and/or `windowScene` (both of those have headerdocs mentioning performance intensivity) and `windowLevel` to the UIWindow list. 

I agree that's some niche stuff but could potentially be helpful, I'd be interested to hear feedback on that from someone with a complex app architecture.

**Comment by armcknight** [comment]
Totally, I was just dumping some brainstorm here 👍🏻
