### ISSUE TITLE
problem with latest

### ISSUE THREAD

**Issue by pvinis** [getsentry/sentry-cocoa#173]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 3.1
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.0.7**

---
I have following issue:

Description goes here ...
I try to compile and I get a `Header 'SentryBreadcrumbTracker.h' not found, in a `module.modulemap` file.
This leads to an error to the file where I `import Sentry`, saying `Could not build Objective-C module 'Sentry'`.

**Comment by HazAT** [comment]
Hmm, that's strange
It's in the tag
https://github.com/getsentry/sentry-cocoa/blob/3.0.7/Sources/Sentry/Sentry.modulemap
And when I download the zip from releases it's also in the framework.

**Comment by pvinis** [comment]
for me the breadcrumb store was there, but not the tracker. hm

**Comment by thevest** [comment]
I'm having the same issue, any suggestions? I'm using Carthage, I also tried the version available in the tags with the same result.

**Comment by HazAT** [comment]
I've made a new release, please upgrade to `3.0.9` and tell me if it's working.
Thx

**Comment by pvinis** [comment]
seems like its working fine now with 3.0.8
