### ISSUE TITLE
Auto instrumentation for NSViewControllers

### ISSUE THREAD

**Issue by kardeslik** [getsentry/sentry-cocoa#1731]
### Problem Statement

If there's no implementation limitations, it'd be very helpful to have Automatic NSViewControllers Instrumentation feature for macOS apps too.
Do you have any plan about providing that feature?

**Comment by philipphofmann** [comment]
We started with UIViewControllers because our user base for iOS is way bigger. Yes, we have plans on also supporting NSViewControllers, but we can't give you an ETA yet.

**Comment by philipphofmann** [comment]
We haven't tackled this in the last two years, and with SwiftUI becoming more popular, we don't see this happening soon. We're going to close this. We can always reopen this or create a new issue if we plan on adding this functionality.
