### ISSUE TITLE
Make Transport Public

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1736]
### Description

According to the [unified API](https://develop.sentry.dev/sdk/unified-api/) the [transport](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryTransport.h) should be public so users can implement their own custom transport.

Befor making [SentryTransport.h](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryTransport.h) public we need to discuss how the interface should look like, because at the moment it contains methods which shouldn't be public.

**Comment by bruno-garcia** [comment]
We've gotten this far without this so important to continue to ask what's the desired outcome from users who ask for this feature (e.g: Send data to 2 Sentries?) Because often there's a better way to achieve that then a custom transport.

**Comment by philipphofmann** [comment]
Closing this again as a customer found a workaround. We can create a new issue if we need this again.
