### ISSUE TITLE
No support for iOS extensions

### ISSUE THREAD

**Issue by ramunasjurgilas** [getsentry/sentry-cocoa#174]
_Platform:_
- [ ]  iOS

_Swift:_
- [ ]  Yes -> 3.x

_sentry-cocoa installed with:_
- [ ] CocoaPods

Version of sentry-cocoa:
**3.0.7**

---
I have following issue:

When I added Sentry to my extension target I can not compile code it generates two errors:
First:
**/Users/ProjectName/Pods/KSCrash/Source/KSCrash/Reporting/Sinks/KSCrashReportSinkEMail.m:140:41: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.**

Second:
/Users/ProjectName/Pods/KSCrash/Source/KSCrash/Reporting/Sinks/KSCrashReportSinkEMail.m:250:31: 'initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:' is unavailable: not available on iOS (App Extension) - Use UIAlertController instead.

I was expecting to use Sentry in the extensions.

**Comment by HazAT** [comment]
Hey,
I will look into this.

**Comment by HazAT** [comment]
Hey, please update to `3.0.9` the issue should be fixed.
