### ISSUE TITLE
[iOS] Getting "OutOfMemory" event when restart application via react-native-restart

### ISSUE THREAD

**Issue by Deodes** [getsentry/sentry-cocoa#1741]
### Platform

iOS

### Installed

CocoaPods

### Version

7.5.4

### Steps to Reproduce

1. Restart application via react-native-restart

### Expected Result

Sentry SDK doesn't send "OutOfMemory" event

### Actual Result

Sometimes SDK send "OutOfMemory" event

**Comment by philipphofmann** [comment]
Thanks for reporting this, @Deodes. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/1618.
