### ISSUE TITLE
Discarded Events: Handle HTTP error codes

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1753]
### Description

The develop docs state that 

> SDKs can put a simple optional check for HTTP status codes in place where any code `>= 400` except `429` will be recorded as `network_error`.

See https://github.com/getsentry/develop/pull/554/files and https://develop.sentry.dev/sdk/client-reports/#sdk-side-recommendations.

The Cocoa SDK doesn't comply yet with the rule above. This is where we need to change the code 
https://github.com/getsentry/sentry-cocoa/blob/673aaa416b0eee6c439140a4a7bf791fb0565e0f/Sources/Sentry/SentryHttpTransport.m#L241-L254

**Comment by kevinrenskers** [comment]
I am looking into this, but I am not sure I totally understand what needs to happen. When I trigger HTTP requests I can see that breadcrumbs are added. 

![Screen Shot 2022-07-08 at 12 56 34](https://user-images.githubusercontent.com/229384/177984484-477d0b78-555f-4b73-96b8-14bd728319b1.png)

But in the code that's linked to from here it talks about discarded events, not sure what that is?

I asked Dhiogo if he can maybe walk me through the architecture a bit and while he agrees that talking about this in person is better and faster, it would be good to have this explanation documented for future reference, so to ask in the ticket. Maybe we can do both?

**Comment by kevinrenskers** [comment]
We'll discuss on Monday and I'll add the explanation to the ticket.
