### ISSUE TITLE
Create a breadcrumb when system timezone changes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1763]
### Problem Statement

The OS fired a notification: https://developer.apple.com/documentation/foundation/nsnotification/name/1387256-nssystemtimezonedidchange

### Solution Brainstorm

Log a breadcrumb, that can help users diagnose. Ideally we persist previous runs breadcrumbs so steps from a previous run can help diagnose issues related to time changing.

Additionally from the notification that can track changes at runtime, we could store the current TZ and compare when initializing the SDK

**Comment by philipphofmann** [comment]
For the first iteration, I think we don't have to persist timezone changes across previous runs. I think it's not worth the effort.

**Comment by brustolin** [comment]
> For the first iteration, I think we don't have to persist timezone changes across previous runs. I think it's not worth the effort.

It's unlikely for an app to receive the change timezone notification because the app must be open for that.
IMO we should stick to persisting timezones to report the change.

**Comment by kevinrenskers** [comment]
I'm curious what kind of problems developers could run into, if the timezone changes while the app isn't open anyway. 

And how would the breadcrumbs help in that case? A breadcrumb is only logged to Sentry as part of a message or a crash, right? (Please do correct me if I'm wrong, I am a bit of a Sentry noob and never used breadcrumbs before.) So if nothing gets logged after the timezone got changed, that breadcrumb will also never make into Sentry?

**Comment by kevinrenskers** [comment]
But would an automatic transaction include such a breadcrumb? And as a developer running into a user with date and time problems, how would I even find that particular transaction or session with that breadcrumb?

**Comment by kevinrenskers** [comment]
Also I would assume that wrong calculations would only happen if that happens while the app is alive. In 12 years I've never run into such problems if the change happened while the app wasn't alive anyway 🤔

But ok, let's discuss your method by storing things - can we brainstorm on Discuss how to go about doing this? Where to store it, when to check the value, when/how to send it, etc.

**Comment by brustolin** [comment]
> But ok, let's discuss your method by storing things - can we brainstorm on Discuss how to go about doing this? Where to store it, when to check the value, when/how to send it, etc.

Sure, you can call me any time
