### ISSUE TITLE
Missing line number on some stack elements

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cocoa#177]
_Platform: iOS
_Swift: 3.0
_sentry-cocoa installed with: CocoaPods
Version of sentry-cocoa:
**3.0.1**

---
I have following issue:

https://sentry.io/recharge/consumer-ios/issues/294456777/

the most relevant stack entry doesn't have a line number, which in this case makes it really hard to track down what the issue is:
```
  recharge-consumer-ios0x100192c90  specialized static LocationActions.updateNearbyPlaces(([String : NearbyPlacePopulated]) -> ()?) -> () (recharge-consumer-ios/LocationActions.swift)
```
I uploaded debug symbols using sentry-cli 1.8.0, if that matters.

**Comment by HazAT** [comment]
Hey, sorry for not replying so long.
We do not get this information out of the debug symbols, but somewhere in the frames below, there should be the right line number.

**Comment by edenman** [comment]
@HazAT but it's not.  The full stack:
```
libobjc.A           0x183ab5474  lookUpImpOrForward
  libobjc.A           0x183ac0478  _objc_msgSend_uncached
  recharge-consumer-ios0x100116c90  specialized static LocationActions.updateNearbyPlaces(([String : NearbyPlacePopulated]) -> ()?) -> () (recharge-consumer-ios/LocationActions.swift)
  recharge-consumer-ios0x1001a28ec  updateNearbyPlaces (recharge-consumer-ios/ActionGroups.swift)
  recharge-consumer-ios0x1001a28ec  updateNearbyPlaces (recharge-consumer-ios/ActionGroups.swift:174)
  recharge-consumer-ios0x1001a28ec  specialized static ActionGroups.interval() -> () (recharge-consumer-ios/ActionGroups.swift:70)
  recharge-consumer-ios0x1001792c4  interval (recharge-consumer-ios/AppDelegate.swift)
  recharge-consumer-ios0x1001792c4  AppDelegate.(application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : protocol<>]?) -> Bool).(closure #3) (recharge-consumer-ios/AppDelegate.swift:113)
  recharge-consumer-ios0x10017939c  AppDelegate.(application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : protocol<>]?) -> Bool).(closure #3).(closure #1) (recharge-consumer-ios/AppDelegate.swift:119)
  Async               0x10086a9d4  static AsyncBlock.((async in _E687294E1917D2F98ED787A27C7576C6)<A> (after : Double?, block : () -> A1, queue : (GCD in _E687294E1917D2F98ED787A27C7576C6)) -> AsyncBlock<(), A1>).(closure #1) (AsyncSwift/Sources/Async.swift:264)
  libdispatch         0x183f0ed04  _dispatch_block_async_invoke
  libdispatch         0x183f029a0  _dispatch_client_callout
  libdispatch         0x183f0f604  _dispatch_continuation_pop
  libdispatch         0x183f1bc1c  _dispatch_source_latch_and_call
  libdispatch         0x183f048a0  _dispatch_source_invoke
  libdispatch         0x183f12a50  _dispatch_root_queue_drain
  libdispatch         0x183f127d0  _dispatch_worker_thread3
  libsystem_pthread   0x18410b1d0  _pthread_wqthread
```

`LocationActions` is only mentioned in the one stack entry and it doesn't have a line number.

**Comment by HazAT** [comment]
Isn't that the function call?
`updateNearbyPlaces (recharge-consumer-ios/ActionGroups.swift:174)`

**Comment by edenman** [comment]
@HazAT Nope.  LocationActions.swift has the `updateNearbyPlaces` function and that's the line number that is missing.  `ActionGroups.swift` is a different file.

**Comment by edenman** [comment]
@HazAT also, if it helps, `ActionGroups.swift` doesn't even have a line 174.  file is only 81 lines long.

**Comment by HazAT** [comment]
@edenman Thx for clearing that up.
We have to look into this, it seems to be a bug in our symbolizer.
Would it be possible for you to share just this file with me? So we can create a similar scenario we can test against. I suppose it's some kind of enum with functions or so ...
If possible, please send the source code of the file to daniel@sentry.io
Thx

**Comment by edenman** [comment]
ok so this is _really_ weird: the line numbers in the Sentry notification email that I get are _different_:
```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x317f9bec8.
  File "recharge-consumer-ios/LocationActions.swift", line 67, in location.get
  File "recharge-consumer-ios/LocationActions.swift", line 180, in specialized static LocationActions.updateNearbyPlaces(([String : NearbyPlacePopulated]) -> ()?) -> ()
  File "recharge-consumer-ios/ActionGroups.swift", in updateNearbyPlaces
  File "recharge-consumer-ios/ActionGroups.swift", line 173, in updateNearbyPlaces
  File "recharge-consumer-ios/ActionGroups.swift", line 71, in specialized static ActionGroups.interval() -> ()
...
(28 additional frame(s) were not displayed)```

This is for https://sentry.io/recharge/consumer-ios/issues/308345567/ but it's the same issue, and it's particularly perplexing that there's a line# for LocationActions here but the linked issue doesn't have a LocationActions line#.

**Comment by HazAT** [comment]
Ok, that's definitely something we have to fix.

**Comment by edenman** [comment]
@HazAT fwiw, I think the line numbers from the email are the correct ones (or at least they pointed me at a line of code that hadn't previously seemed suspect, and now I think I know what the problem is)

**Comment by edenman** [comment]
In case another data point would help, this just happened to another crash of mine: https://sentry.io/recharge/consumer-ios/issues/310224524/

Stacktrace in the email (this mostly makes sense):
```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x200000038.
  File "recharge-consumer-ios/BaseLabel.swift", in attributedText.set
  File "recharge-consumer-ios/BaseLabel.swift", line 118, in specialized BaseLabel.refreshText(NSAttributedString?) -> ()
  File "recharge-consumer-ios/PlaceCardView.swift", in refreshText
  File "recharge-consumer-ios/PlaceCardView.swift", line 60, in refreshText
  File "recharge-consumer-ios/PlaceCardView.swift", line 27, in text.didset
...
(39 additional frame(s) were not displayed)
```
Stacktrace on the Sentry web UI (this makes no sense whatsoever):
<img width="1005" alt="screen shot 2017-07-13 at 10 34 22 am" src="https://user-images.githubusercontent.com/1063557/28179471-ea99830a-67b6-11e7-8a1e-314436266e72.png">

**Comment by HazAT** [comment]
Hey, just checked this crash specifically. 
If you switch to Thread 0 in the UI you get the stacktrace from the email.
Still, we will check why the content in the email and the UI do not correlate.

**Comment by edenman** [comment]
@HazAT ha, nice.  yeah, I just assumed the link in the email would go to the same thread#.  thanks!

**Comment by HazAT** [comment]
@edenman 
So this issue seems unrelated to the cocoa SDK itself, I've created an issue here https://github.com/getsentry/symsynd/issues/14
I hope to switch threads is a workaround for the confusion the emails caused.

We will look into improving the "crashed thread" detection even though the example you sent me is rather complex.

If you need anything else, just let me know.
