### ISSUE TITLE
Fix stitchAsyncCode

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1786]
### Description

StichAsyncCode was added with https://github.com/getsentry/sentry-cocoa/pull/998, but on some devices, the stacktraces were incomplete; see comments in #998.

We should fix these problems and ideally turn on `stichAsyncCode` by default. Be aware that this would have an impact on grouping.

Related issues:

- https://github.com/getsentry/sentry-cocoa/issues/1919
- https://github.com/getsentry/sentry-cocoa/issues/2318

**Comment by bruno-garcia** [comment]
Relevant/related info:


> It in turn calls [setAsyncCallStackDepth](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setAsyncCallStackDepth) which will "stitch" the stack whenever an async call is done (you can see how in v8/src/inspector/v8-debugger.cc in the chromium repo).

V8: https://stackoverflow.com/questions/68375903/how-does-v8-reconstruct-async-stacktraces-with-requestanimationframe

> IntelliJ 2017.1 included a feature called Capture Points. This feature lets us stitch together stack frames so that the order of functions in the stack trace respects the order in which they were called.
https://finagle.github.io/blog/2017/11/02/async-stack-traces/

> Stacktrace recovery tries to stitch asynchronous exception stacktrace with a stacktrace of the receiver by copying it, providing not only information where an exception was thrown, but also where it was asynchronously rethrown or caught.

https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md#stacktrace-recovery

**Comment by philipphofmann** [comment]
Docs PR https://github.com/getsentry/sentry-docs/issues/5215
