### ISSUE TITLE
Missing `SentryScreenShot.h` file

### ISSUE THREAD

**Issue by wmalloc** [getsentry/sentry-cocoa#1803]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.14.0

### Steps to Reproduce

Build on case sensitive file system.

'SentryScreenShot.h' file not found in `SentryScreenshot.m` file

you need to change the import to 

`#import "SentryScreenshot.h"`

### Expected Result

Compile and link correctly

### Actual Result

Error linking

**Comment by brustolin** [comment]
Hello @wmalloc. We appreciate your contact.

This was fixed in #1794. We'll have a new release coming soon, or you can point your Swift Package Manager to master for now.

**Comment by wmalloc** [comment]
🖖🏼
