### ISSUE TITLE
Apple SwiftUI Support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1814]
- [x] https://github.com/getsentry/sentry-cocoa/issues/1737
- [x] ~~Collect breadcrumbs for navigation/route changes~~ (Not possible as SwiftUI doesn't provide a proper API)
- [x] New Wizard

https://getsentry.atlassian.net/browse/MOBILE-84

**Comment by philipphofmann** [comment]
We don't want that these issues keep this issue open:
* https://github.com/getsentry/sentry-cocoa/issues/2572
* https://github.com/getsentry/sentry-cocoa/issues/1560

We track them separately and close this issue.
