### ISSUE TITLE
Xcode warning due to duplicate header file

### ISSUE THREAD

**Issue by lokae0** [getsentry/sentry-cocoa#182]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 3
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.0.11**

---
I have following issue:

Getting an Xcode warning due to duplicate header file in project source:
`Warning: Multiple build commands for output file /Sentry.framework/Headers/NSDictionary+Sanitize.h`

**Steps to reproduce:**
- Install via Cocoapods
- Build project
- Receive warning

**Actual result:**
- Received Xcode warning

**Expected result:**
- Don't receive Xcode warning

**Comment by lokae0** [comment]
Not sure if I have to file an issue to surface a PR, so doing this just in case! https://github.com/getsentry/sentry-cocoa/pull/181

**Comment by HazAT** [comment]
Ty, this has been fixed in the latest release.
