### ISSUE TITLE
Unprefixed selectors are added in categories on Foundation classes

### ISSUE THREAD

**Issue by cysp** [getsentry/sentry-cocoa#183]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [x] Carthage
- [x] Manually

Version of sentry-cocoa:
**3.1.0**

---
I have the following issue:

There seem to be a few methods being added to Foundation classes in categories:
- [NSData](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/NSData%2BCompression.h)
- [NSDate](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/NSDate%2BExtras.h)
- [NSDictionary](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/NSDictionary%2BSanitize.h)

The selector names being added seem quite generic, e.g. `-sanitize`, which could result in name clashes with other categories or private methods.

Apple's guidance is to prefix the names of methods added in categories.
[Customizing Existing Classes – Avoid Category Method Name Clashes](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4)

**Steps to reproduce:**
- Integrate `sentry-cocoa`

**Actual result:**
- All `NSDictionary` instances respond to `-sanitize`, possibly clashing with any existing implementations of that method.

**Expected result:**
- Not that.

**Comment by HazAT** [comment]
Good catch, will add that.
