### ISSUE TITLE
`NSUnderlyingError` is not included in the error report

### ISSUE THREAD

**Issue by sindresorhus** [getsentry/sentry-cocoa#1831]
### Platform

macOS

### Installed

Swift Package Manager

### Version

7.15.0

### Steps to Reproduce

- Look at this report: https://sentry.io/organizations/sindresorhus/issues/3273975164/events/544bc3bddb634d9bb80276e4350660d1/

### Expected Result

I expected to see a `NSUnderlyingError` key in the USER INFO section.

### Actual Result

I don't see such key. However, I tried manually logging it to check that it's actually there.

I also see the key in the "exception" summary in the BREADCRUMBS:

> com.sindresorhus.blear - NSItemProviderErrorDomain.Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.image" UserInfo={NSLocalizedDescription=Cannot load representation of type public.image, NSUnderlyingError=0x...: Code: -1000

**Comment by philipphofmann** [comment]
Thanks, @sindresorhus, for raising this. Our code doesn't look for the `NSUnderlyingError` in the user info section. What you see there is a memory address, I think. We could easily extract it in the `SentryClient` with the [`NSUnderlyingErrorKey`](https://developer.apple.com/documentation/foundation/nsunderlyingerrorkey?language=objc) and attach it to the user info section, as you pointed out. 

```objc
NSError *underlyingError = [userInfo objectForKey:NSUnderlyingErrorKey];
```

**Comment by sindresorhus** [comment]
> Our code doesn't look for the NSUnderlyingError in the user info section.

I don't get it though. Are you not copying everything over from `.userInfo`? Why is this key missing?

I actually noticed other built-in keys are missing too. `NSURL` is missing. See: https://sentry.io/organizations/sindresorhus/issues/3277236955/events/984fe951839545f986a74cc65b52af55/ I manually log out `.userInfo` and it's included in the key `nsError_userInfo`.

Sentry should include all the built-in keys.

**Comment by philipphofmann** [comment]
We call `sentry_sanitize` on the userInfo dictionary
https://github.com/getsentry/sentry-cocoa/blob/259a468b2c13f0d905ad2c4a1e5344f57ed3c6b4/Sources/Sentry/NSDictionary%2BSentrySanitize.m#L25-L37

Hm, I don't get it either. If we don't the type, we just use `.description`. This should actually work.

**Comment by philipphofmann** [comment]
I just tried this
```Swift
do {
    // something that throws
} catch {
    let url = URL(string: "https://www.google.com")
    let userInfo = [NSUnderlyingErrorKey: error, "url": url] as [String : Any]
    let nserror = NSError(domain: "SomeError", code: 1, userInfo: userInfo)
    SentrySDK.capture(error: nserror)
}
```
and it ends up in Sentry
<img width="805" alt="Screen Shot 2022-05-16 at 16 35 04" src="https://user-images.githubusercontent.com/2443292/168617613-234d0214-f585-4057-b7b5-dfce9708d843.png">


Can you maybe provide a small code snipped for a repro, @sindresorhus, please?

**Comment by philipphofmann** [comment]
No worries, @sindresorhus. It's valuable feedback, as others might have the same issue because of #1442.
