### ISSUE TITLE
Change debug type from `apple` to `macho`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1833]
### Description

A change was done already to affect profiling: 
* https://github.com/getsentry/sentry-cocoa/pull/1830/
We should change the crash reporting side to align with profiling, and to drop the legacy format.

**Comment by smeubank** [comment]
> We should change the crash reporting side to align with profiling, and to drop the legacy format.
why is there still product value is keeping this open?

**Comment by philipphofmann** [comment]
Done with https://github.com/getsentry/sentry-cocoa/pull/2701.
