### ISSUE TITLE
Stop reporting pre warmed app starts

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1849]
### Description

Measuring the app start time could be unreliable on iOS 15, see 
 - https://github.com/MobileNativeFoundation/discussions/discussions/146
 - https://www.emergetools.com/blog/posts/iOS15LaunchTime
 - https://github.com/MobileNativeFoundation/discussions/discussions/37

Because of 

> Starting with iOS 15, the system might decide to “pre-warm” your app before the user actually tries to open it

https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466

Investigate if our logic in [SentryAppStartTracker](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryAppStartTracker.m) is impacted by that.

**Comment by matthewreimer** [comment]
This guy (an Apple dev I think) [says to use `MetricKit`](https://github.com/MobileNativeFoundation/discussions/discussions/146#discussioncomment-1731074) to time things like this.

**Comment by philipphofmann** [comment]
I can confirm that we have an issue with iOS 15 with measuring the app start time. Since iOS 15, the OS might decide to prewarm your app before a user opens it to speed up app start. A quick investigation of app start data of a big customer of ours showed me that the app start is greater than 1 minute on around 5% of transactions containing app start measurements.

Ideally, we should switch to [MetricKits MXAppLaunchMetric](https://developer.apple.com/documentation/metrickit/mxapplaunchmetric), which is available for iOS 13 and above. We could drop app start measurements if their duration is bigger than a defined threshold for a quick fix.
