### ISSUE TITLE
Device details not populated

### ISSUE THREAD

**Issue by raajvijay** [getsentry/sentry-cocoa#185]
Version: SentryCocoa 3.1.2
Platform: iOS
_sentry-cocoa installed with: Carthage

Device details not populated in the error logs with SentryCocoa. It used to work fine with SentrySwift

**Actual result:**
- Device name and family populated as unknown in logs

**Expected result:**
- Device name populated part of the logs

**Comment by HazAT** [comment]
I've just tried it with a clean project and installed version `3.1.2` and it worked.
Can you make a clean build and make sure you use the bundled version from the releases section.

**Comment by raajvijay** [comment]
I used Xcode 8.3.3 and it does not work even after clearing Carthage cache.

**Comment by HazAT** [comment]
Do you see something like this in your log when you start your app?
```
2017-07-05 09:02:53.743106+0200 test[28287:54009540] Sentry Started -- Version: 3.1.2
2017-07-05 09:02:53.744430+0200 test[28287:54009540] Sentry - Debug:: KSCrashHandler started
    ************************ Crash Handler Notice ************************
    *     App is running in a debugger. Masking out unsafe monitors.     *
    * This means that most crashes WILL NOT BE RECORDED while debugging! *
    **********************************************************************
```

**Comment by raajvijay** [comment]
Below is from the logs. And I don't use sentry crash handler.
2017-07-05 09:45:40.846 test[75605:3417293] Sentry Started -- Version: 3.1.2

**Comment by HazAT** [comment]
Oh ok, that might be the problem.
Currently, we rely a lot on KSCrash for this kind of information, when we have time we will move this into the Sentry library itself.

**Comment by raajvijay** [comment]
Yeah I tried with startCrashHandler() and I can see the device details populated. In that case I will add the device details as tags manually. Thanks
