### ISSUE TITLE
SentrySpan searchable tags

### ISSUE THREAD

**Issue by ZeroOnet** [getsentry/sentry-cocoa#1850]
### Description

Self-hosted: Version 21.11.0
Sentry Version: 7.10.2

I want to set a searchable transaction tag, but failed. The code as follows:

```
let trace = SentrySDK.startTransaction(name: "name", operation: "operation")
trace.context.setTag(value: "value", key: "key")
// or
trace.setTag(value: "value", key: "key")
```

Something else?

**Comment by philipphofmann** [comment]
We just merged #1826 and plan a release next week. Please reopen if the problem still persists.
