### ISSUE TITLE
SentrySpan Confusing timestamp

### ISSUE THREAD

**Issue by ZeroOnet** [getsentry/sentry-cocoa#1851]
### Description

```
- (void)finishWithStatus:(SentrySpanStatus)status
{
    self.context.status = status;
    self.timestamp = [SentryCurrentDate date];
    if (self.transaction != nil) {
        [self.transaction spanFinished:self];
    }
}

```

SentrySpan finish invocation will override timestamp even if I setted customized value.

**Comment by marandaneto** [comment]
@ZeroOnet why do you need your own `timestamp`? what's the use case?
On Java, we have `boolean finish(SpanStatus status, Double timestamp)` which allows a custom timestamp but its package-private.

**Comment by ZeroOnet** [comment]
> @ZeroOnet why do you need your own `timestamp`? what's the use case?
> On Java, we have `boolean finish(SpanStatus status, Double timestamp)` which allows a custom timestamp but its package-private.

Because I want to upload metric time data by SentrySpan, eg: network stage metric time.

```
let transaction = SentrySDK.startTransaction(name: "Networking", operation: "response")
transaction.startTimestamp = metric.responseStartDate
// Maybe named endTimestamp is better.
transaction.timestamp = metric.responseEndDate
transaction.finish()
```

**Comment by philipphofmann** [comment]
Adding a `finish(SpanStatus status, Double timestamp)` to Cocoa, would be easy.

**Comment by philipphofmann** [comment]
Let's only set the timestamp in `finish` if it's nil.
