### ISSUE TITLE
SentryEvent with customized stack trace

### ISSUE THREAD

**Issue by ZeroOnet** [getsentry/sentry-cocoa#1858]
### Description

Sentry Version: 7.10.2

I got unsymbolicated stack trace, such as: 

```
0 libdispatch.dylib       0x00000000181cfd1e8 0x181cf4000 + 37352
1 VideoToolBox            0x000000001859b47d0 0x185955000 + 391120
```

It's my customized stack trace with binary name, UUID, address and loadAddress for multiple threads. I noticed that SentryEvent includes threads, stacktrace and debugMeta properties to modify stack trace information. But how do I use them to attach? Set UUID by debugMeta? And then formatted stack trace to SentryThread?

**Comment by philipphofmann** [comment]
If your stacktrace is not symbolicated properly, could it be that you didn't upload the dSYMS, see https://docs.sentry.io/platforms/apple/dsym/?

**Comment by ZeroOnet** [comment]
I uploaded dSYM to Sentry Server. I try to integrate MetricKit to analyze my app performance. It provides unsymbolicated stack trace for hang, crash and exception diagnostics. I want to symbolize by Sentry. So I should format these to SentryEvent stack trace, How do I finish it?

**Comment by philipphofmann** [comment]
Do you also attach the debugMeta to the event, like we do this for the client?
https://github.com/getsentry/sentry-cocoa/blob/93ed599eeea87ad5f2cb8f7d213f637cedb503df/Sources/Sentry/SentryClient.m#L477-L481

I'm not sure how you would do this with MetricKit. `SentryDebugImageProvider` is internal and we don't have plans to make it public at the moment.

**Comment by ZeroOnet** [comment]
> Do you also attach the debugMeta to the event, like we do this for the client?
> 
> https://github.com/getsentry/sentry-cocoa/blob/93ed599eeea87ad5f2cb8f7d213f637cedb503df/Sources/Sentry/SentryClient.m#L477-L481
> 
> I'm not sure how you would do this with MetricKit. `SentryDebugImageProvider` is internal and we don't have plans to make it public at the moment.

For example:

```
struct MyFrame {
    let binaryName: String
    let binaryUUID: String
    /// Address of stack frame.
    let address: Int
    /// Address of loaded image or binary.
    let imageLoadAddress: Int

    // ？？？
    var toSentryDebugImage: DebugMeta {
        let result = DebugMeta()
        result.type = "macho"
        result.uuid = binaryUUID
        result.name = binaryName
        result.imageAddress = toHex(with: imageLoadAddress)

        return result
    }
    
    // ？？？
    var toSentryFrame: Frame {
        let result = Frame()
        result.package = binaryName
        result.instructionAddress = toHex(with: address)
        result.symbolAddress = toHex(with: imageLoadAddress)

        return result
    }
}
```

How do I convert MyFrame to SentryDebugMeta and SentryFrame?

**Comment by philipphofmann** [comment]
You can create instances of `SentryDebugMeta` and `SentryFrame` yourself. These classes are public. You just need to map the data of `MyFrame` to both of them.
