### ISSUE TITLE
Could not build Objective-C module 'Sentry'

### ISSUE THREAD

**Issue by dasmer** [getsentry/sentry-cocoa#186]
_Platform:_
- [ X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ X]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.x.x**

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by HazAT** [comment]
Does this still happen in the latest version?
If yes I would need a bit more context, could you send me your build log?

**Comment by dasmer** [comment]
Fixed in the latest version. Thanks!
