### ISSUE TITLE
crash for sentry

### ISSUE THREAD

**Issue by wlwZLP** [getsentry/sentry-cocoa#1864]
### Platform

iOS

### Installed

CocoaPods

### Version

7.5.4

### Steps to Reproduce

This problem occurs when you open a mobile app and are already switching pages

### Expected Result

Is this bug fixed in the latest version?

### Actual Result

![image](https://user-images.githubusercontent.com/14145693/172101166-184de8f0-6f85-45df-81d1-0038e0bd3d7c.png)

**Comment by philipphofmann** [comment]
>  are already switching pages
What exactly do you mean by that, @wlwZLP? I'm not sure how I could reproduce your issue.

> Is this bug fixed in the latest version?
It could be. Updating to the latest version is worth a shot.

**Comment by philipphofmann** [comment]
This could be related to https://github.com/getsentry/sentry-cocoa/issues/1892.
