### ISSUE TITLE
when enableOutOfMemoryTracking=YES ,(default is YES) ,the sdk recognizes a cold start that is not installed for the first time as a warm start

### ISSUE THREAD

**Issue by yufanghui** [getsentry/sentry-cocoa#1866]
### Platform

iOS

### Installed

CocoaPods

### Version

7.13

### Steps to Reproduce

1. use default integration(OOM is enable)
2. A cold start can be counted for the first installation
3. A cold start after the initial installation is incorrectly identified as a warm start

After oom detection is enabled, Appstate will be cached locally and will not be cleared after the APP is killed. As a result, Appstate exists locally when the app is started next time, and the following condition judgment fails all the time
```Objective-C
- (SentryAppStartType)getStartType
{
    // App launched the first time
    if (self.previousAppState == nil) {
        return SentryAppStartTypeCold;
    }
}
```

### Expected Result

Identify cold start as cold start

### Actual Result

Non-initial installation, cold start is identified as warm start

**Comment by philipphofmann** [comment]
We never deleted the app state when the app is killed even before the OOM tracking. I don't understand why the OOM tracking should change that. We two other conditions for checking if the app start is a cold start, see https://github.com/getsentry/sentry-cocoa/blob/89525830558140998ebcfa069b0dc02e511fa071/Sources/Sentry/SentryAppStartTracker.m#L163-L176

> A cold start after the initial installation is incorrectly identified as a warm start

I just tried installing an app for the first time, and the sentry-cocoa SDK correctly identified it as a cold start. Are there maybe other steps that could lead to a wrongly reported warm start?

**Comment by brustolin** [comment]
I heard something about iOS 15 pre-warming apps. That's something we should investigate. But im not 100% sure if this is really a thing.

**Comment by yufanghui** [comment]
> We never deleted the app state when the app is killed even before the OOM tracking. I don't understand why the OOM tracking should change that. We two other conditions for checking if the app start is a cold start, see
> 
> https://github.com/getsentry/sentry-cocoa/blob/89525830558140998ebcfa069b0dc02e511fa071/Sources/Sentry/SentryAppStartTracker.m#L163-L176
> 
> > A cold start after the initial installation is incorrectly identified as a warm start
> 
> I just tried installing an app for the first time, and the sentry-cocoa SDK correctly identified it as a cold start. Are there maybe other steps that could lead to a wrongly reported warm start? Please also make sure to understand the difference between warm and cold start, see https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation.

Thank you very much for your reply. I have seen the judgment of cold and hot startup below, but I don't quite understand the relationship between cold startup and system restart time

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/16069335/172520394-4cc6e52d-bee1-4598-a8af-7f52d142333c.png">

**Comment by yufanghui** [comment]
Sorry, I have checked the official documents of WWDC again. It is my own fault that I have misunderstanding about Cold Start and warm Start

**Comment by philipphofmann** [comment]
> Sorry, I have checked the official documents of WWDC again. It is my own fault that I have misunderstanding about Cold Start and warm Start

No worries, @yufanghui. Better to double-check such issues.
