### ISSUE TITLE
fatalError message is lost

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cocoa#187]
_Platform:_
- [X]  iOS

_Swift:_
- [X]  Yes -> If yes, which version? 3.0

_sentry-cocoa installed with:_
- [X] CocoaPods

Version of sentry-cocoa:
**3.0.11**

---
I have following issue:

`fatalError("message goes here about what went wrong")` produces a Sentry issue that doesn't include the message text.

Example issue: https://sentry.io/recharge/consumer-ios/issues/308295368/

**Comment by martindufort** [comment]
Is this bug back in ? Looks like any of my fatalError calls are missing the descriptions...

CocoaPods 
macOS 15.x
Sentry-Cocoa: 5.1.4

**Comment by philipphofmann** [comment]
Thanks @martindufort for reaching out to us. Can you give us more context on when you experience the issue? It would be nice if you would open up another issue for this and reference this issue here.

**Comment by martindufort** [comment]
Thanks for your reply @philipphofmann. Was sure I opened up an issue for this here. Upon further investigation, it was opened in the general Sentry repo: https://github.com/getsentry/sentry/issues/19870

Do you want me to create a new one here and delete the other one ?
Thanks

**Comment by philipphofmann** [comment]
I transferred the issue to this repo @martindufort https://github.com/getsentry/sentry-cocoa/issues/662. Thanks for opening it.

**Comment by martindufort** [comment]
Thanks for looking into this...
