### ISSUE TITLE
Fix pre warmed app start measurement 

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1897]
### Description

Since iOS 15, the system might decide to pre-warm your app before the user tries to open it. In such cases, we can't reliably measure the app start, and we started to drop reporting app start measurements with https://github.com/getsentry/sentry-cocoa/pull/1896. Otherwise, we would get app start times ranging from one minute to even days.

[According to a former Apple engineer](https://github.com/MobileNativeFoundation/discussions/discussions/146#discussioncomment-1731074), you should use [MetricKit](https://developer.apple.com/documentation/metrickit/mxapplaunchmetric) to collect statistics on app start because MetricKit uses internal OS values, which are not exposed otherwise. MetricKit works on iOS 13 and above. Maybe it's time to replace our own [SentryAppStartTracker](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryAppStartTracker.m).

See also https://github.com/getsentry/sentry-cocoa/issues/1661. [Internal Notion page] (https://www.notion.so/sentry/Detecting-iOS-15-App-Prewarming-c892f118bdd34b558eb187796ed5e424) on how to detect pre-warmed app starts with data we can't share in public, and another [Notion page for a DACI](https://www.notion.so/sentry/Cocoa-Report-Prewarmed-App-Starts-2a48da2973364728b7ee769daee34064#8109159ee5bd411c9c281a26e1c95607) on how to report pre-warmed app starts again.

Related PRs:
- [x] https://github.com/getsentry/sentry-cocoa/pull/1896
- [x] https://github.com/getsentry/sentry-cocoa/pull/1899
- [x] https://github.com/getsentry/sentry-cocoa/pull/1927
- [ ] https://github.com/getsentry/sentry-cocoa/pull/1969

**Comment by bruno-garcia** [comment]
Can we get values from MetricKit about the startup related to the transaction that launched the app?

**Comment by philipphofmann** [comment]
> Can we get values from MetricKit about the startup related to the transaction that launched the app?

No, we can't.

This is roughly how you can subscribe to the data of MetricKit. 

```
class AppMetrics: NSObject, MXMetricManagerSubscriber {
    func receiveReports() {
       let shared = MXMetricManager.shared
       shared.add(self)
    }

    func pauseReports() {
       let shared = MXMetricManager.shared
       shared.remove(self)
    }

    // Receive daily metrics.
    func didReceive(_ payloads: [MXMetricPayload]) {
       // Process metrics.
        let enumerator = payloads.first?.applicationLaunchMetrics?.histogrammedTimeToFirstDraw.bucketEnumerator
        
        while let object = enumerator?.nextObject() {
            let bucket = object as! MXHistogramBucket<UnitDuration>
            
            // ...
        }
        
    }

    // Receive diagnostics immediately when available.
    func didReceive(_ payloads: [MXDiagnosticPayload]) {
        
    }
}
```

There are daily metrics [MXMetricPayload](https://developer.apple.com/documentation/metrickit/mxmetricpayload) and real-time metrics  [MXDiagnosticPayload](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload).

## MXMetricPayload
Daily

* [cellularConditionMetrics: MXCellularConditionMetric](https://developer.apple.com/documentation/metrickit/mxmetricpayload/3114372-cellularconditionmetrics)
* [cpuMetrics: MXCPUMetric](https://developer.apple.com/documentation/metrickit/mxmetricpayload/3114373-cpumetrics)
* [applicationLaunchMetrics: MXAppLaunchMetric](https://developer.apple.com/documentation/metrickit/mxmetricpayload/3131908-applicationlaunchmetrics)
* [applicationResponsivenessMetrics: MXAppResponsivenessMetric](https://developer.apple.com/documentation/metrickit/mxmetricpayload/3131910-applicationresponsivenessmetrics)
* ...

## MXDiagnosticPayload
Realtime

* [crashDiagnostics: [MXCrashDiagnostic]](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552309-crashdiagnostics)
* [cpuExceptionDiagnostics: [MXCPUExceptionDiagnostic]](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552308-cpuexceptiondiagnostics)
* [appLaunchDiagnostics: [MXAppLaunchDiagnostic]](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3951242-applaunchdiagnostics)
* [hangDiagnostics: [MXHangDiagnostic]](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552312-hangdiagnostics)
* [diskWriteExceptionDiagnostics: [MXDiskWriteExceptionDiagnostic]](https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552311-diskwriteexceptiondiagnostics)

**Comment by philipphofmann** [comment]
According to the [Apple docs](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence#3894431)

> Prewarming an app results in an indeterminate amount of time between when the prewarming phase completes and when the user, or system, fully launches the app. Because of this, use [MetricKit](https://developer.apple.com/documentation/metrickit) to accurately measure user-driven launch and resume times instead of manually signposting various points of the launch sequence.

**Comment by philipphofmann** [comment]
Prewarming can execute code up to `viewDidLoad` of a UIViewController, and keep your app in the background. It can pause at any stage from creating the process up to `viewDidLoad` of a UIViewController or something similar  This is a contradiction to the Apple docs `Prewarming executes an app’s launch sequence up until, but not including, when main() calls UIApplicationMain(::::).`

I dug into some transactions of customers and found a few transactions similar to this one:

<img width="914" alt="Screen Shot 2022-06-20 at 09 39 34" src="https://user-images.githubusercontent.com/2443292/174549832-6bd24cd9-b9c6-4b73-8277-eef9f03d76da.png">

The above screenshot shows missing instrumentation of around 4 hours in between `viewDidLoad` and `viewWillAppear`. This can't be the case if the app was in the foreground because the watchdog would kill the app.

Discover query to reveal such transactions: `event.type:transaction measurements.app_start_warm:>500 measurements.app_start_warm:<2000 transaction.duration:>10000`

An [answer on StackOverflow](https://stackoverflow.com/a/71073401/1702958) supports this claim.

### More screenshots
Discover query used:`event.type:transaction measurements.app_start_warm:>10000 `

**Pausing after process creation**

<img width="914" alt="Screen Shot 2022-06-20 at 09 48 49" src="https://user-images.githubusercontent.com/2443292/174551542-479caa6a-288c-4a8f-87e3-833cdc3424b1.png">

<img width="914" alt="Screen Shot 2022-06-20 at 09 53 40" src="https://user-images.githubusercontent.com/2443292/174552457-c6bead12-015f-410c-8b6b-22b1ed687d2f.png">

**Pausing after process creation and runtime init**
<img width="914" alt="Screen Shot 2022-06-20 at 09 54 16" src="https://user-images.githubusercontent.com/2443292/174552583-e0e44b24-04cf-4b0a-bb06-31df2938038a.png">

**Comment by philipphofmann** [comment]
Maybe using `__mod_init_func` in the data section of Mach-O binary could help. [An example](https://stackoverflow.com/a/30703178/1702958) of how to use it.

**Comment by philipphofmann** [comment]
It seems like we can use, see https://eisel.me/startup
```
if ([[NSProcessInfo processInfo].environment[@"ActivePrewarm"] isEqual:@"1"]) {
      // The ActivePrewarm variable indicates whether the app was launched via pre-warming.
      // Based on this, for example, you can choose whether or not to include the pre-main time in your calculation based on that.
}
```

**Comment by philipphofmann** [comment]
@mitsuhiko, @k-fish, and I agreed on reporting the app start type in the app context as  `start_type : cold | cold.prewarmed | warm | warm.prewarmed`. [Internal Notion Page](https://www.notion.so/sentry/Cocoa-Report-Prewarmed-App-Starts-2a48da2973364728b7ee769daee34064#8109159ee5bd411c9c281a26e1c95607) for more context.

**Comment by bruno-garcia** [comment]
To sum up: latest sdk version doesn't send bogus app start anymore. The startup time metric is accurate. It doesn't send pre warn info yet. It's the last pending feature we want to add to this.
