### ISSUE TITLE
Threading issue between swizzled and manually-added breadcrumbs.

### ISSUE THREAD

**Issue by aayers-agrible** [getsentry/sentry-cocoa#190]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? Swift 3
- [ ]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.1.2**

---
I have following issue:

Occasionally we receive Sentry alerts for crashes that happen when the app is trying to add breadcrumbs to the store. See below:

`Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]`

I believe this to be a threading issue adding breadcrumbs to the Sentry Client from both swizzled methods and manually-created breadcrumbs at the same time. 

Description goes here ...

Inside our app we have a singleton class that wraps access to the Sentry Client, stores the DSN strings, and adds some convenience functions for constructing breadcrumbs. I added a method to create breadcrumbs for the API requests that the app makes to our server. I had a previous issue with crashes from the Sentry Client where too many network request threads were all adding breadcrumbs at the same time. I solved this issue by adding a dispatch queue that executed all of the functions to add breadcrumbs for api requests. Now I am seeing the issue again, but this time only happening when one thread is executing a UI action (that would be swizzled), and another is adding an API request breadcrumb. 

**Steps to reproduce:**
- Have the UI thread execute a swizzled action while another thread is attempting to add breadcrumbs to the store. (Very hard to reproduce reliably.)

**Actual result:**
-  See above error.

**Expected result:**
- Expected that access to the sentry breadcrumb store would be thread safe.

**Comment by HazAT** [comment]
Hey, I've just released `3.2.1` which should fix the issue.
Please upgrade and see if it works.
