### ISSUE TITLE
Fix slow frames calculation

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1904]
### Description

We need to fix the frame rate calculation to take into account dynamic frame rate and/or manually configured frame rate.

Might be related to https://github.com/getsentry/sentry-cocoa/issues/1881

**Comment by philipphofmann** [comment]
@brustolin, I think you could add more context to this issue, please?

**Comment by philipphofmann** [comment]
Was fixed with https://github.com/getsentry/sentry-cocoa/pull/1915.
