### ISSUE TITLE
Swift name for SentryClient collides with our internal Client model

### ISSUE THREAD

**Issue by colinhumber** [getsentry/sentry-cocoa#193]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? Swift 3.1.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.2.1**

---
I have following issue:
Provided Swift alias for Objective-C class collides with internal model

Description goes here ...

The `NS_SWIFT_NAME` provided for the Objective-C class `SentryClient` collides with our internal `Client` model and crashes when initializing, as our model doesn't have an -initWithDsn:didFailWithError:` method.

Since `Client` is a very common term, it would be more interoperable if the aliased class name either had a prefix, or wasn't aliased at all. `SentryClient` is more descriptive anyway, and has much less chance of colliding with internal names.

Typealiasing or initializing with a fully qualified name doesn't work.

**Steps to reproduce:**
- start Sentry in a project that has an Objective-C class named `Client`

**Actual result:**
- Sentry starts up with no issues

**Expected result:**
- App crashes with the error `-[Client initWithDsn:didFailWithError:]: unrecognized selector sent to instance`

```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        _ = Client()
        
        do {
            Client.shared = try Client(dsn: "https://274f0eef7ba64b84bc5e0edaa8e4e184:89ed937489e74708ad63510723d15723@sentry.io/170131")  // <--- crash happens here
            try Client.shared?.startCrashHandler()
        }
        catch let error {
            print("Error initializing Sentry: \(error)")
        }
        return true
    }
```

**Comment by colinhumber** [comment]
The same issue would occur with the `SentryUser` object aliased in Swift as `User`.

**Comment by HazAT** [comment]
Hey, you should be able to prefix everything with `Sentry.` in that case.
Swift has namespacing so this should work.
`Sentry.Client`

**Comment by colinhumber** [comment]
That was my first thought, but it's still colliding. I've attached the test project I've been working with. Build and run to see the collision.
[SentryTest.zip](https://github.com/getsentry/sentry-cocoa/files/1173393/SentryTest.zip)

**Comment by HazAT** [comment]
Sooo I've looked into this now in more detail, your example is very interesting.

Since Objc does not provide any namespacing, your specific example does not work. 
Even though I think this is probably a bug in how Xcode creates Swift code out of non framework code in your projects.

A few things I found out:
If you move the local client initialization below Sentry's, it works.
```
        do {
            Sentry.Client.shared = try Sentry.Client(dsn: "")
            try Sentry.Client.shared?.startCrashHandler()
        }
        catch let error {
            print("Error initializing Sentry: \(error)")
        }
        
        _ = Client()
```
Which is very strange that it works.

Also if you run this in the debugger:
```
(lldb) po NSStringFromClass(Client.classForCoder())

"Client"

(lldb) po NSStringFromClass(Sentry.Client.classForCoder())

"SentryClient"
```
This also seems to load the correct class.

And of course, if you remove the `Client.m` and create a `Client.swift` it's also working since the namespacing in Swift works.
I assume there is a bug in the namespacing of local Objc code.
Because logically this has to work `_ = SentryTest.Client()` but it doesn't.

So the tl;dr would be in order to fix this I would have the keep the `Sentry` prefix for all Swift classes 
OR
You would have to rename your Objc Class 
OR
You have to use Swift only for clashing names

tbh I am not sure if we are gonna leave the `Sentry` prefix for all classes since this is again a huge public API break.

Would like to hear your feedback on this.

**Comment by colinhumber** [comment]
What's odd is the class that we load the Sentry code in our main app doesn't have any direct references to our ```Client``` class, but it does use other Objective-C class that internally imports ```Client.h```, which could be causing the issue. That's very interesting that moving the local initialization below works.

For now I just created an Objective-C helper class that sets up everything up that we can safely call from our Swift code.

Considering the API breakage that could occur I totally understand not being able to make that change. Maybe things will work better with Swift 4 and Xcode 9, which I haven't tested this on yet. It's a very minor issue that we have a workaround for, so it's nothing critical. :D At the very least we all learned something interesting here haha. Feel free to close this off.

**Comment by HazAT** [comment]
I've tested it with Xcode 9 and Swift 4, also no luck there.
But as you said, thanks for pointing this out, I definitely learned something :)

**Comment by sauravexodus** [comment]
Using Firebase and Sentry in the same project reproduces this break. I get a crash while creating a User object

`[FIRUser initWithUserId:]: unrecognized selector sent to instance 0x1742d9670`

**Comment by colinhumber** [comment]
I had to create a utility class in Obj-C that I could call from Swift where I could create a `SentryUser` object since I wasn’t able to create a `Sentry.User` object in Swift.

**Comment by HazAT** [comment]
@sauravexodus So you are also using `Sentry` in a Swift project and it conflicts with `FIRUser` ?

**Comment by abellee** [comment]
so any solutions?
why do you guys use this so common name?
you should know every project has User.

**Comment by pondorasti** [comment]
> The same issue would occur with the SentryUser object aliased in Swift as User.

What's the resolution here?

**Comment by brustolin** [comment]
Hello @pondorasti what are you trying to do and what's the error?

This should be solution in case of a collision:

```swift
SentrySDK.setUser(Sentry.User(userId: "John"))
```

**Comment by pondorasti** [comment]
> Hello [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/32957606?s=64&amp;u=8ddf372677adc365796cc26cd34890d724d0f33e&amp;v=4">@pondorasti](https://github.com/pondorasti) what are you trying to do and what's the error?
> 
> This should be solution in case of a collision:
> 
> SentrySDK.setUser(Sentry.User(userId: "John"))

Thanks @brustolin! I ended up doing something along the same lines, where I created a `typealias SentryUser = Sentry.User`.
