### ISSUE TITLE
Make `PrivateSentrySDKOnly#getDebugImages` static as well if possible

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1940]
### Description

Needed for https://github.com/getsentry/sentry-dart/pull/823#discussion_r847325236
Not a blocker since we can just `let sentryIOSPrivate = PrivateSentrySDKOnly()` but it'd be nice to align either all instance methods or static methods.

**Comment by vaind** [comment]
in the meantime it already is static: https://github.com/getsentry/sentry-cocoa/pull/1769
