### ISSUE TITLE
Fix flaky test SentryFileManagerTests.testDefaultMaxEnvelopesConcurrent()

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1949]
### Description

I see this test casually failing during CI

**Comment by armcknight** [comment]
Could you link to a failure?

**Comment by brustolin** [comment]
It's being a while to be honest that I dont see this now.

**Comment by philipphofmann** [comment]
Should we close it then @brustolin? Please link some failing tests in the future.

**Comment by philipphofmann** [comment]
Didn't see this for a while. Going to close this.
