### ISSUE TITLE
The program crashed here [reasons addObject:[content objectForKey:@"value"]]

### ISSUE THREAD

**Issue by boxkim** [getsentry/sentry-cocoa#196]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:

I use the version is **3.2.0**
Discover the problem and upgrade to **3.4.1**
But the problem still exists

---
I have following issue:

When the program starts crashing. See below:

<img width="1314" alt="2017-08-07 10 52 08" src="https://user-images.githubusercontent.com/22275930/29053258-88cbd4a0-7c21-11e7-84c6-5180a1ad6985.png">

<img width="1041" alt="2017-08-07 11 06 09" src="https://user-images.githubusercontent.com/22275930/29053254-7cb496a2-7c21-11e7-97dd-993a5ed4a5f6.png">

Q1:
i find self.exceptionContext[@"nsexception"][@"reason"] = nil

Q2:
When the above code is changed to：self.exceptionContext[@"reason"] 
The following code error
`if ([[[content objectForKey:@"value"] componentsSeparatedByString:@"/"] count] < 3) `
i find `[content objectForKey:@"value"] = xxx,xxx,xxx not xxx/xxx/xxx`

finally, the program crashed here:
`[reasons addObject:[content objectForKey:@"value"]];`

`[content objectForKey:@"value"]` always equal to nil

I can only change this way to ensure that the program starts normally
`
id value = [content objectForKey:@"value"];
if (value) {
    [reasons addObject:value];
}
`
Please forgive my bad English! I wish you better and better!

**Steps to reproduce:**

It is not clear what is the cause

**Actual result:**

The program can not start normally

**Expected result:**

Hope not to crash

**Comment by HazAT** [comment]
Can you upgrade to `3.4.2` this should be fixed.
