### ISSUE TITLE
Disable ANR detection in benchmarks 

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-cocoa#1961]
### Description

There are a lot of issues per day (~3.3k for the last 24 hours) seemingly related to benchmarks. I'd suggest disabling ANR detection in the benchmark run. See https://sentry.io/organizations/sentry-sdks/projects/sentry-cocoa/?issuesType=all&project=5428557&statsPeriod=24h

Besides the obvious number of issues, there is also about 250 KB of attachments associated with each issue, totalling about 800 MB per day, which are pretty useless in those issues.

cc @armcknight

**Comment by bruno-garcia** [comment]
We discussed a flag to control the "quality" of screenshots. It seems we need that already for ourselves. We already ran out of quota. I wonder if we should add a "low" quality option to be a fraction of the current one and use that instead. Current quality/size can be default.

**Comment by armcknight** [comment]
Added it to the current benchmarking update omnibus PR 😄

**Comment by philipphofmann** [comment]
So this will be fixed by https://github.com/getsentry/sentry-cocoa/pull/1926, @armcknight?

**Comment by armcknight** [comment]
Correct.

**Comment by vaind** [comment]
resolved by https://github.com/getsentry/sentry-cocoa/pull/1926/files#diff-489e20902b3b8cb67d406ba71c59e123294eead63461fd69a475859ad75a6309R31-R37
