### ISSUE TITLE
Remove values from Core Data queries in transactions

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1972]
### Description

When creating an automatic CoreData transaction, we are including the value of the variable in the query.

We should have only placeholders instead of actual values.

**Comment by brustolin** [comment]
Should we use the actual value if `enableDefaultPII` is true?

**Comment by philipphofmann** [comment]
> Should we use the actual value if `enableDefaultPII` is true?

I would say so.
