### ISSUE TITLE
Create UI Event Transaction for Scrolls, Swipes and other gestures

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1977]
### Problem Statement

This is a follow up of the _UI Event Transaction for Clicks_ feature added #1784 

General SDK tracking issue: 
* https://github.com/getsentry/team-mobile/issues/4

SDK Spec is to be created following: 
* https://github.com/getsentry/develop/issues/647

**Comment by GirugaCode** [comment]
@philipphofmann Thank you! I'll keep a look out on the issues if related issues to this pop up. When it comes to the _Spans First_ approach, How will the new span-based tracing model be able capture events such as Scrolls, Swipes and other gestures?

Found this article too on the effort if it relates: https://blog.sentry.io/dont-observe-debug/

**Comment by GirugaCode** [comment]
Of course, I'd imagine in my case I could just manually add BreadCrumbs to help detect scrolls / gestures. Thank you for the response @philipphofmann really appreciate it!
