### ISSUE TITLE
LastContext *user* not loaded if previous session didn't set either *tags* or *extra*

### ISSUE THREAD

**Issue by mberube09** [getsentry/sentry-cocoa#198]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.4.3**

---
I have following issue:

While playing around the iOS sdk I came accross the issue where all my reports sent didn't include user information. After digging through, I discovered that the method `restoreContextBeforeCrash` didn't restore the context properly. In my case, I had only set the `SentryClient.sharedClient.user` property as I didn't need the tags and extra properties.

The reason is simple:

```
self.lastContext = [[NSDictionary alloc] initWithObjectsAndKeys:
                        [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.tags"], @"tags",
                        [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.extra"], @"extra",
                        [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.user"], @"user", nil];
```
The `initWithObjectsAndKeys` method is a `nil` terminated variable list. In my case `[[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.tags"]` was actually `nil`, thus preventing from going further.

Now there would be two solutions that I would propose you. One is to force the creation of NSUserDefaults entry in your initializer by calling `[self setExtra:[NSDictionary new]];`. Just like you do in the `clearContext` method.

The other solution would be to avoid the nil terminated varargs and use a mutable dictionary instead :

```
    NSMutableDictionary *lastContext = [NSMutableDictionary dictionary];
    lastContext[@"tags"] = [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.tags"];
    lastContext[@"extra"] = [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.extra"];
    lastContext[@"user"] = [[NSUserDefaults standardUserDefaults] objectForKey:@"sentry.io.user"];
    self.lastContext = lastContext.copy;
```

Hope I didn't miss any details, feel free to ask otherwise, thanks!

**Comment by HazAT** [comment]
👏 

This bug report is superb, thank you for pointing that out.
I've created a PR to fix that.

**Comment by mberube09** [comment]
Thank you for the fix 🤗
