### ISSUE TITLE
Compilation fails when Address Sanitizer enabled

### ISSUE THREAD

**Issue by davidrothera** [getsentry/sentry-cocoa#1990]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.21.0

### Steps to Reproduce

* Enable Address Sanitizer on build
* Try to build
* Observe compilation fails with:
```
ld: Assertion failed: (index < orderedInitOffsetAtoms.size()), function doPass, file inits.cpp, line 131.
```

Simple repro at https://github.com/davidrothera/CrashTest with ASAN enabled

### Expected Result

Compilation works

### Actual Result

Compilation fails

**Comment by bruno-garcia** [comment]
Does it work on the latest? 7.21.0?

**Comment by davidrothera** [comment]
Sorry I got the versions wrong:

* Working: `7.20.0`
* Broken: `7.21.0`

**Comment by philipphofmann** [comment]
Thanks for reporting this, @davidrothera. I can reproduce this with your sample project and have to look into what's causing this. I'm surprised that our CI didn't catch this.

**Comment by davidrothera** [comment]
It took me a while to catch it myself as it's not super clear what causes it and I wasn't seeing it in all projects or in all build modes and it wasn't until I went over them with a magnifying glass that I remembered I had ASAN enabled the one which was failing.

I'm guessing most of your CI projects don't have ASAN enabled.

**Comment by bruno-garcia** [comment]
> I'm guessing most of your CI projects don't have ASAN enabled.

If we enable it in one of our samples, would that do the job @philipphofmann @bruno-garcia ?

**Comment by philipphofmann** [comment]
Yep, it's related to https://github.com/getsentry/sentry-cocoa/blob/678172142ac1d10f5ed7978f69d16ab03e801057/Sources/Sentry/SentrySysctl.m#L14-L20

I just removed this code, and it compiles again. I wonder why that is. 

We have ASAN enabled in CI for the Sentry project, but not for the samples. Enabling it for our sample projects doesn't fail the build.

Maybe we can use 
```
__used __attribute__((constructor)) static void recordProcessStartTime() {
    moduleInitializationTimestamp = [NSDate date];
}
```
Instead of the `__mod_init_func`.
