### ISSUE TITLE
Propagated `sentry-trace` should include correct parent span id

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#1994]
### Platform

iOS

### Installed

Swift Package Manager

### Version

all

### Steps to Reproduce

Make a call from the iOS SDK to a backend.

### Expected Result

The parent of the server transaction is the span that created the request, and not the root span (`ui.load`)

### Actual Result

![image](https://user-images.githubusercontent.com/1633368/180260026-d7a21afc-14d9-451f-baea-1fe3f8f01a1f.png)

Note: This image also has an issue with what it seems to be clock drift, but the issue is that the 
![image](https://user-images.githubusercontent.com/1633368/180260206-8990e96d-da63-4084-b015-816ecf473118.png) icon expanded on the top span instead of under 
![image](https://user-images.githubusercontent.com/1633368/180260269-9cfd7467-c632-4b1d-8304-30d3377b203a.png)

The `http.server` transaction shows up as a child of `ui.load` (the root span, transaction)

**Comment by brustolin** [comment]
We could try to use associated object to store span id into the request

**Comment by brustolin** [comment]
This is already done.

**Comment by philipphofmann** [comment]
@brustolin, could you please link the PR that closed this issue please?

**Comment by bruno-garcia** [comment]
@brustolin this was done in which PR? Nothing shows up linked here unless I'm missing something

**Comment by bruno-garcia** [comment]
Reopening as it seems this is still broken. This isn't related to previously addressed 'cached trace_id' but instead, the parent span id being the incorrect one.
