### ISSUE TITLE
UI Test testSplitView fails on iOS 12

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2000]
### Description

`testSplitView` keeps failing locally. This is how it looks like on iOS 12 vs iOS 15:

<img src="https://user-images.githubusercontent.com/229384/180423682-7a12133c-6d13-4c2b-b155-583aa86e8bbc.png" width="45%" /> <img src="https://user-images.githubusercontent.com/229384/180423687-9416b3ef-4ff6-4425-9536-afd77d2b9573.png" width="45%" />

I'm also getting literally endless errors in the console in iOS 12 on the split view:

```
Sentry - debug:: Failed to get pthread handle for mach thread 5123
Sentry - error:: thread_suspend(handle_) failed with kern return code: 268435459, description: Unknown error.
```

The exact same thing runs fine from iOS 13 and up though, without these errors. 

This test failure might have started with #1978? When looking at test failures in master that might be the case.

**Comment by kevinrenskers** [comment]
See also https://github.com/getsentry/sentry-cocoa/issues/1566 I guess?

**Comment by philipphofmann** [comment]
Thanks for adding this info to this issue, @kevinrenskers. As a workaround, we could disable profiling on iOS 12 for now to make the tests stable again. @indragiek, it seems like https://github.com/getsentry/sentry-cocoa/pull/1978 could break things on iOS 12. How bad is that for profiling?

**Comment by indragiek** [comment]
@philipphofmann @kevinrenskers Sorry for the slow response - I'm working on a fix for this and will have it up soon!

**Comment by indragiek** [comment]
https://github.com/getsentry/sentry-cocoa/pull/2013 is the fix
