### ISSUE TITLE
Add `transaction` to scope

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#2005]
SDKs allow for setting a transaction name to the scope. This goes out in error events and help identify where an event comes from:

https://docs.sentry.io/platforms/android/enriching-events/transaction-name/

**Comment by philipphofmann** [comment]
There are discussions now to remove this API https://github.com/getsentry/sentry-javascript/issues/5660.

**Comment by cmanallen** [comment]
This was deprecated in the javascript sdk.
