### ISSUE TITLE
Fix flaky testDefaultMaxEnvelopesConcurrent

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2017]
### Description

The test is flaky and disabled for now.

**Comment by kevinrenskers** [comment]
I ran `testDefaultMaxEnvelopesConcurrent` repeatedly (1000 times) without failure, and ran the entire test class `SentryFileManagerTests` repeatedly (100 times) without failure as well. Not sure there is an actual problem? Going to create a PR so that I can see what happens on CI.
