### ISSUE TITLE
`user.id` should be nullable

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#2035]
### Description

The spec defines all fields to be optional: https://develop.sentry.dev/sdk/event-payloads/user/

But we have the `id` to be non-nullable:

https://github.com/getsentry/sentry-cocoa/blob/398f6b24ebd37db618feb74cfb3643e3ff3d003d/Sources/Sentry/Public/SentryUser.h?rgh-link-date=2022-08-02T05%3A25%3A41Z#L12

This means we end up having to pass an empty string as `id` if we want to send a user with only `username`, for example.

**Comment by mattjohnsonpint** [comment]
I think perhaps this was missed in #201?

**Comment by mattjohnsonpint** [comment]
As a workaround, I can avoid setting an empty string by just never setting the userid in case of null.

If I understand correctly, null (or `nil` rather) is the default the is being used anyway and we're just missing the `_Nullable` annotation.
