### ISSUE TITLE
Support two instances of sentry

### ISSUE THREAD

**Issue by shwetashendage** [getsentry/sentry-cocoa#2037]
### Problem Statement

Hi Guys,
I want to send an event to two different Sentry dashboards using single application. How can I configure two instances of Sentry with different DSNs.

**Comment by brustolin** [comment]
Hey @shwetashendage. Thanks for your input. Right now is not possible to use two different DSNs at the same time.

**Comment by shwetashendage** [comment]
> 

I believe it is feasible in Android. See https://github.com/getsentry/sentry-java/issues/993
Can we not achieve the same thing in iOS?

**Comment by brustolin** [comment]
Well. Theoretically you can manually create a SentryHub with a SentryClient with different options than you can manually send events to different DSNs. But this way you lose all the automatic stuff like errors and crashing reports, automatically transactions and breadcrumbs. 

This is only for manually created events.

**Comment by armcknight** [comment]
Hi @shwetashendage, I'm curious to know more about your use case. Do you have one org with two different projects, or do you want to send these events to projects in multiple orgs? Are you using this setup to control user access to dashboards, separate events for different variants of your project, or something else?

I'm wondering if it's multiple projects in one org, if it would be possible to use a single project with different environments: https://docs.sentry.io/product/accounts/getting-started/#5-define-environments? Even in that case today, I think you could only set one environment at a time, but I think it would be a smaller effort to allow sending events to multiple environments vs different projects/orgs.

If it's multiple orgs set up to control user access, it's possible that using org/user roles could help there: https://docs.sentry.io/product/accounts/membership/

I realize you probably can't easily change how you have structured your projects/orgs at this time, but I just want to see if the underlying use case is something we have solutions for today; we could improve our docs, and this may help future customers if they hit this issue when searching.

**Comment by philipphofmann** [comment]
@shwetashendage, can you please answer the questions above?
