### ISSUE TITLE
Clean up SentryOptions integration 

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2043]
We should clean up `SentryOptions` and get rid of `enabledIntegrations`, `disabledIntegrations`, `defaultIntegrations` and `integrations`. All that `enabledIntegrations` is used for is for sending a list to Sentry, but we already have a list of enabled integrations: `SentrySDK.currentHub.installedIntegrations`.

`defaultIntegrations` should be moved to `SentrySDK`, and can just be named `integrations`.

And all integrations should be turned on/off using `enable*` options, not by modifying these arrays. That means we should add new options for those integrations that currently don't have an `enable*` option: 

SentryAppStartTrackingIntegration
SentryFramesTrackingIntegration
SentryCrashIntegration

I also think we should rename `enableUserInteractionTracing` to `enableUserInteractionTracking`.

Obviously these will be breaking changes, so wait until v8. But before v8 hits we could introduce the missing `enable*` options and mark the arrays as deprecated.

**Comment by bruno-garcia** [comment]
@kevinrenskers please remove the Untriaged label after creating an issue.

Worth noting w e might add some integrations after "start" is called so the collection should be COW or another safe way to give us mutability concurrently

**Comment by kevinrenskers** [comment]
SentryAppStartTrackingIntegration and SentryFramesTrackingIntegration are both controlled by `enableAutoPerformanceTracking`, which seems fine. No need to split that into two new options.

**Comment by kevinrenskers** [comment]
> Worth noting w e might add some integrations after "start" is called so the collection should be COW or another safe way to give us mutability concurrently

It's not possible to change the installed integrations after start is called - that is not possible currently, and won't change with this new PR. The installed integrations are immutable after the SDK has started.
