### ISSUE TITLE
Optional debug symbol file missing warning

### ISSUE THREAD

**Issue by alardizabal** [getsentry/sentry-cocoa#205]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.6.1**

---
I have following issue:

My account is linked to al@goposse.com. I am having trouble with the setup for iOS. The Dart and Android implementations seem to work well.

I am using the new Flutter framework (http://flutter.io). Sentry is integrated on the Dart side and separately on the native sides (iOS and Android). I have been able to upload the required debug symbols file using the run script (project does not use bitcode). However, I am unable to resolve the missing optional debug file warning.

**Steps to reproduce:**
1. Follow instructions for setup without bitcode.
2. Cause crash.
3. You'll see a partially symbolicated trace. Run script uploads required symbol file (I used to see a warning but now that's fixed).
4. I see an optional debug symbol file missing warning. I've attempted to follow the manual upload instructions.

**Actual result:**

<img width="1007" alt="screen shot 2017-08-31 at 10 38 41 am" src="https://user-images.githubusercontent.com/3614291/29929479-9eb5c12a-8e39-11e7-9bea-f172b5f0f2e3.png">

```
{
  "image_arch": "arm64",
  "image_uuid": "60c0470c-7643-3f23-8e7c-a34c32c00d2a",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/C53AC04A-2BA2-405C-B108-CB177BE0B222/Runner.app/Frameworks/Flutter.framework/Flutter"
}
```

**Expected result:**
Fully symbolicated trace and no optional debug symbol file missing warning.

**Comment by HazAT** [comment]
Hey, can you make sure that `DWARF and dSYM file` is enabled for your `Flutter.framework` target?

<img width="521" alt="screenshot 2017-09-01 09 18 10" src="https://user-images.githubusercontent.com/363802/29959222-9994d6a0-8ef6-11e7-8ec1-275a0307f31c.png">

Then the dsyms should be generated and you should be able to upload them.

**Comment by alardizabal** [comment]
I only have one target and my release configs are set to DWARF with dSYM

<img width="511" alt="screen shot 2017-09-01 at 10 07 45 am" src="https://user-images.githubusercontent.com/3614291/29973964-5510ae38-8eff-11e7-83ac-b10c85d0a882.png">

**Comment by alardizabal** [comment]
When I build I get a notification on my MacBook that the debug symbols are being uploaded by Sentry. When I try to upload manually I get the following.

```
Batch 1
> Found 1 debug symbol files.
> Checking for missing debug symbol files on server
> Nothing to compress, all symbols are on the server
> Nothing to upload
```

**Comment by eseidelGoogle** [comment]
FYI @yjbanov

**Comment by yjbanov** [comment]
@cbracken to chime in with iOS expertise. I wonder if our iOS engine build is missing the necessary symbols.

**Comment by HazAT** [comment]
When you download Sentry (from the releases page) you get something like this:

<img width="425" alt="screenshot 2017-09-04 14 35 39" src="https://user-images.githubusercontent.com/363802/30026719-6e86c4de-917e-11e7-8a6c-58b73ae56a73.png">

so we include the dSYM and BCSymbolMap files (in case you want to strip the symbols).
So could be they are missing in the Flutter build.
I never used Flutter so not really sure if that's the case.

**Comment by HazAT** [comment]
I will close this for now since this problem is probably related to Flutter. 
Frameworks have to provide their debug symbols in order for Sentry to provide full stack traces.
