### ISSUE TITLE
Create more logs for automatic transactions

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2050]
### Description

We need more debug log for automatic transactions such as UIVIewController life cycle, network request, IO and Core Data.

This will help us during customer support. We need to know when a automatic transaction started, ended and what other automatic spans were created in between. 

Network request, IO and Core Data spans relies on some transaction being bound to the scope, we might add a log saying that those were not created because there is no transaction in the scope. But Im afraid this could be very verbose.

**Comment by bruno-garcia** [comment]
> But Im afraid this could be very verbose.

SDKs like [Flutter](https://docs.sentry.io/platforms/flutter/configuration/options/#diagnostic-level), [.NET](https://docs.sentry.io/platforms/dotnet/configuration/options/#diagnostic-level) and [Android/Java](https://docs.sentry.io/platforms/android/configuration/options/#diagnostic-level) have DiagnosticLevel

> `diagnosticLevel`
> Enabling debug mode makes the SDK generate as much diagnostic data as possible. However, if you'd prefer to lower the > verbosity of the Sentry SDK diagnostics logs, configure this option to set the appropriate level:
> 
> debug: default The most verbose mode
> info: Informational messages
> warning: Warning that something might not be right
> error: Only SDK internal errors are printed
> fatal: Only critical errors are printed

In .NET you can even swap out the Sentry SDK diagnostic logger, to print to a file or other place (like the Unity console), for example: https://docs.sentry.io/platforms/dotnet/configuration/diagnostic-logger/

**Comment by brustolin** [comment]
Cocoa has diagnosticLevel, but the default is already debug.

**Comment by bruno-garcia** [comment]
> Cocoa has diagnosticLevel, but the default is already debug.

That's OK, but users can raise the level to warn if `debug` is too spammy. But for us to get logs from them to debug issues, we can get the default, verbose level.
