### ISSUE TITLE
Can we remove line 7 from MAKEFILE?

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2053]
Can we remove line 7 from MAKEFILE?
```
cd Samples/TrendingMovies && carthage update --use-xcframeworks
```

It makes init unnecessary long f0r SDK development.

_Originally posted by @brustolin in https://github.com/getsentry/sentry-cocoa/issues/2025#issuecomment-1207772947_

**Comment by armcknight** [comment]
We can put this behind a separate makefile task like `make init-samples`

**Comment by bruno-garcia** [comment]
When skipping the template, please add `Platform: Cocoa` so it shows up on the GH project and we can discuss on our weekly sync (in case no one replied already due to notifications)

**Comment by armcknight** [comment]
👍🏻 FWIW, I tried this for the first time, which doesn't pre-populate the issue template 😞 : 
<img width="249" alt="image" src="https://user-images.githubusercontent.com/3241469/183733927-aeb9b504-2dc7-41da-9b97-75d517f88ff7.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/3241469/183733964-648f02d1-f1b0-4fb1-acb4-94e3381b9031.png">

Guess I won't use that again 😅
