### ISSUE TITLE
Setting timestamp on SentryTracer causes traces to fail to submit

### ISSUE THREAD

**Issue by amonshiz** [getsentry/sentry-cocoa#2054]
### Platform

macOS

### Installed

Swift Package Manager

### Version

7.23.0

### Steps to Reproduce

1. Open new transaction with `SentrySDK.startTransaction`
2. Begin and end some subspans
3. Set `timestamp` on transaction
4. Call `finish` on transaction

In our case we are keeping the transaction and all subspans in a collection of `Sentry.Span` that we operate on via that interface and do not inspect the actual type.

### Expected Result

The transaction should appear on Sentry. Though this can be verified by setting a `beforeSend` closure on the `SentrySDK` and it should be called after step 3 above.

### Actual Result

The transaction never appears on Sentry and the `beforeSend` closure is never invoked.

**Comment by brustolin** [comment]
Hello @amonshiz thanks for report this. We actually use the setTimestamp internally in the SDK, we never saw a problem with this. Can you provide a minimum repro? It would help a lot to investigate this. Thanks again!!!

**Comment by brustolin** [comment]
This may be related to #2059. @amonshiz Can you try this now with the master branch?

**Comment by amonshiz** [comment]
Will do!

**Comment by amonshiz** [comment]
Just tested this change and it seems to address our issue. Thank you for the fast turn around!
