### ISSUE TITLE
Unrecognized platform name macCatalyst

### ISSUE THREAD

**Issue by muizidn** [getsentry/sentry-cocoa#2057]
### Platform

iOS

### Installed

CocoaPods

### Version

7.23.0

### Steps to Reproduce

1. Create Standard iOS Project
2. Import Sentry using CocoaPods

```
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.23.0'
```

3. Build project using Swift 5.5.1. I use Xcode Version 13.4.1 (13F100) with Toolchain: Swift 5.5.1 Release 2021-10-25 (a)

### Expected Result

Project built successfully.

### Actual Result

![Screen Shot 2022-08-10 at 13 16 26](https://user-images.githubusercontent.com/19355715/183828875-c6a6fe2a-82f4-44ff-a6d3-77a32dd412d5.png)
![Screen Shot 2022-08-10 at 13 16 36](https://user-images.githubusercontent.com/19355715/183828933-f4f5a165-eb7c-4df5-93dc-a44043507099.png)
[Build SampleSentryRepro_2022-08-10T13-15-26.txt](https://github.com/getsentry/sentry-cocoa/files/9297284/Build.SampleSentryRepro_2022-08-10T13-15-26.txt)

**Comment by bruno-garcia** [comment]
@mattjohnsonpint mayr not a Maui thing, it's not really there for Apple in general

**Comment by bruno-garcia** [comment]
@muizidn thaboabfor raising. We need to dig.

**Comment by kevinrenskers** [comment]
I can't reproduce this with Xcode 13.4.1 (13F100) using the standard toolchain. I then downloaded the Swift 5.5.1 (2021-10-25) toolchain from https://www.swift.org/download/ and yeah then I get the same error. Same for Swift 5.5.3.

Just curious: is there a reason you're using Swift 5.5 instead of 5.6?

**Comment by muizidn** [comment]
Yup. The reason is that I need to downgrade toolchain because a main third party sdk requires me to use Swift 5.5.1. Need to wait for long before they can rebuild using newest swift. Bureaucracy thing 🙈. They deliver the sdk in binary framework.
