### ISSUE TITLE
App required to have NSAppleMusicUsageDescription key in Info.plist

### ISSUE THREAD

**Issue by Shiaulis** [getsentry/sentry-cocoa#2065]
### Platform

iOS

### Installed

CocoaPods

### Version

7.23.0

### Steps to Reproduce

With latest Sentry version our app cannot pass check during upload in Appstore Connect since we do not have `NSAppleMusicUsageDescription` in `Info.plist` file so we needed to revert to previous Sentry version:
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required.

Is it suppose to work like that? Do you expect your customers to add this key? 

### Expected Result

App doesn't required to have `NSAppleMusicUsageDescription`

### Actual Result

Application failed to upload to Appstore

**Comment by brustolin** [comment]
Hey @Shiaulis We definitely not expect the user to add this key. We check for permission, but we dont try to request permission. 
It's odd to me that apple doesn't even allow to check whether the permission exists. We gonna rollout this change. 

Thanks for letting us know this.

**Comment by kevinrenskers** [comment]
The SDK reads `MPMediaLibrary.authorizationStatus`, which normally should not require that key to present. After all, we're not actually requesting authorization. But it seems App Store Connect's automatic checks have a different opinion. We need to revert this feature. Sorry for the inconvenience!

**Comment by kevinrenskers** [comment]
@Shiaulis when did you get that error? When you uploaded your archive to App Store Connect? Or when you submitted the app for review?

I just uploaded a small sample app that includes the Sentry SDK to App Store Connect, and I did not get any errors 🤔

**Comment by Shiaulis** [comment]
we uploading our builds every day and starting from Monday when we updated our sentry to latest release we receive this error i've mentioned earlier on uploading build. So I cannot even see the build in list of uploaded builds. As soon as I reverted latest Sentry version, upload were successful without any errors

**Comment by Shiaulis** [comment]
Maybe Appstore has different level of checks for your sample app and our app? 🤔

**Comment by kevinrenskers** [comment]
Maybe a silly question, but did you try uploading it a second time when you got that error? 

Could you please try to update the SDK again and upload a build? I'm really curious if that error you got was a fluke, as I am not able to reproduce it.

**Comment by Shiaulis** [comment]
@kevinrenskers i had about 5-6 failed attempts to upload

**Comment by Shiaulis** [comment]
Okay I will try once more with latest changes to upload once more. Is it possible that we had some version of SDK between releases? I wonder is it possible for us to rely only on release commits?

**Comment by kevinrenskers** [comment]
When you upload your build, do you have Bitcode and "strip Swift symbols" both selected?

**Comment by Shiaulis** [comment]
bitcode disabled, strip symbols enabled

**Comment by kevinrenskers** [comment]
I can add this code directly to my sample app:

``` swift
import CoreLocation
import UIKit
import MediaPlayer
import Photos

class PermissionsViewController: UIViewController {
    override func viewDidLoad() {
        let a = MPMediaLibrary.authorizationStatus()
        let b = PHPhotoLibrary.authorizationStatus()
        let c = CLLocationManager.authorizationStatus()
        print("!!!!", a, b, c)

        UNUserNotificationCenter.current().getNotificationSettings { settings in
            print("!!!!", settings)
        }
    }
}
```

Without adding any kind of permission key in the Info.plist file:

![Screen Shot 2022-08-11 at 12 08 13](https://user-images.githubusercontent.com/229384/184111371-79c8807c-ae82-4ab2-9f68-12b945b2f705.png)

Uploading the archive goes without a hitch, the build finished processing on App Store Connect. Of course I can't actually submit the sample app to Apple for review, but the upload at least goes through just fine.

I'm not sure if we should remove a very useful feature of the SDK at this moment without figuring out why you are getting this error. I'll try it with bitcode disabled as well.

**Comment by kevinrenskers** [comment]
With bitcode disabled or enabled, both upload fine.

**Comment by kevinrenskers** [comment]
> Is it possible that we had some version of SDK between releases? I wonder is it possible for us to rely only on release commits?

I'm not sure how you are integrating the SDK? If you use the master branch then yeah that is possible, but normal releases are immutable. So if you use Cocoapods or Carthage or SPM and stick to release numbers, you shouldn't get a weird in between version :)

**Comment by kevinrenskers** [comment]
For now I would advice you to simply add that `NSAppleMusicUsageDescription` key with a dummy text (something like "we don't actually need permission" or whatever). I think that would be the quickest route to new builds with an up-to-date SDK.

In the meantime we can investigate this issue more and see if anyone else is seeing the same problem.

**Comment by Shiaulis** [comment]
Regarding distribution looks like we were relying on your latest master instead of latest stable version. And I assume it was the core of the issue that we have. I still will check on your latest master if everything works well, but for now I will change the way we pick your changes and will rely only on latest stable version instead

**Comment by Shiaulis** [comment]
@kevinrenskers 
still received the same issue on commit a8a2317be9af05f5cc50bcc458edeffb5248d9c7
<img width="677" alt="image" src="https://user-images.githubusercontent.com/13601748/184120343-3402fbde-633d-42c4-883d-fe3a82342546.png">

**Comment by Shiaulis** [comment]
> For now I would advice you to simply add that `NSAppleMusicUsageDescription` key with a dummy text (something like "we don't actually need permission" or whatever). I think that would be the quickest route to new builds with an up-to-date SDK.
> 
> In the meantime we can investigate this issue more and see if anyone else is seeing the same problem.

For us we fixed this by relying on latest stable Sentry version that doesn't have this issue

**Comment by kevinrenskers** [comment]
Right, 7.23.0 doesn't include this feature yet. We'll make sure to thoroughly investigate this before creating a new release. Thanks for the info!

**Comment by kevinrenskers** [comment]
Hey @Shiaulis, I spoke to Apple about this issue, about whether or not us reading `MPMediaLibrary.authorizationStatus` would trip up any checks, and if this indeed requires that purpose string to be present. He's pretty much convinced it can't be the SDK:

> Based on the detailed description you’ve given, the likelihood is that the single developer who encountered the "Missing Purpose String” rejection did so for a reason unrelated to your SDK.
> 
> Specifically, it sounds like the developer might be using another 3rd party framework that (perhaps) contains music playback functionality that the developer isn’t using or even aware of, but is being detected at App Store Connect ingest. It’s even remotely possible that your SDK refers to some APIs that aren’t apparently music-playback-specific, but share the same privacy string as music. (Some of the media library APIs might work this way, for example.)
> 
> My recommendation is that you ask this developer to try uploading an app version that does not link your SDK, to see if the error persists. If it does, that suggests it’s their problem not yours.
> 
> If it doesn’t, the next step might be to ask the developer to open a TSI about the issue. We’d probably refer them initially to the App Review technical investigations team, but the request would need to come from the developer who controls the app.

I explained that the issue went away when you downgraded the Sentry SDK, so it can't be another SDK at fault here. I have 2 questions for you:

When you downgraded the SDK and uploaded a new build, was that the only change you made? Or did you happen to roll back some other changes in your own code maybe? Just making sure 😅

And the second question is a big favor to ask: would you be willing to open a [Technical Support Incident](https://developer.apple.com/support/technical/) with Apple? You only get two of these per year so we totally understand if you can't or don't want to do this, but it would greatly help us to figure out what exactly is triggering this error. We don't want to release a problematic feature in the SDK of course.

I've uploaded our own sample app to App Store Connect without triggering any errors so sadly we can't request this help ourselves.

**Comment by kevinrenskers** [comment]
Actually, a third question. In [this comment](https://github.com/getsentry/sentry-cocoa/issues/2065#issuecomment-1211844093) you posted the error you received, and that seems to be an email. When exactly did you get this? Not during the actual upload and validation of the build to App Store Connect, or it would be an error within Xcode. Do you get it after the build is processed? When you make it available to TestFlight? When you submit it for review?

**Comment by Max-Job** [comment]
I got this error today too when trying to submit an app to testflight.

Sentry 7.23.0

**Comment by kevinrenskers** [comment]
Sentry 7.23.0 doesn't include the feature yet where we read `MPMediaLibrary.authorizationStatus`, so I am not sure this is related to the SDK? Could you ask the App Review technical investigations team to look into this?

**Comment by Shiaulis** [comment]
@kevinrenskers 
1. The only thing I revert was Sentry. And the error is gone.
2. Sorry, not sure if I have time to open an incident with apple
3. This error was received to my email. Usually I receive them if anything wrong with particular build i'm trying to upload.

@Max-Job Can you check what commit of Sentry library did you have? Currently our app contains version 7.23.0 with commit a0d4563fa4ddacba31fdcc35daaa8573d87224d6

**Comment by Max-Job** [comment]
> @Max-Job Can you check what commit of Sentry library did you have? Currently our app contains version 7.23.0 and everything works well with it

@Shiaulis
Not sure how I can figure out a specific commit. This is how I install the dependency:
```pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :modular_headers => true```

After installation in podfile.lock:
```
PODS:
  - Sentry (7.23.0):
    - Sentry/Core (= 7.23.0)
  - Sentry/Core (7.23.0)

SPEC CHECKSUMS:
  Sentry: a0d4563fa4ddacba31fdcc35daaa8573d87224d6

```

**Comment by kevinrenskers** [comment]
Yeah that is just the 7.23.0 release 👍

**Comment by Max-Job** [comment]
I added the tag and the build loaded and is now available in testflight

 :tag => '7.21.0'

**Comment by Shiaulis** [comment]
Well, before we had in our Podfile such line

>   pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'


and target commit was f895f1b333e9cea6417e6d32284528a0896d66e4

Now I've removed git link to your repo and cocoapods just referencing the last stable version

**Comment by Max-Job** [comment]
> Well, before we had in our Podfile such line
> 
> > pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
> 
> and target commit was [f895f1b](https://github.com/getsentry/sentry-cocoa/commit/f895f1b333e9cea6417e6d32284528a0896d66e4)
> 
> Now I've removed git link to your repo and cocoapods just referencing the last stable version

And did it work? Did this solve the problem?

**Comment by Shiaulis** [comment]
Latest successful build was from this commit https://github.com/getsentry/sentry-cocoa/commit/29fe66621dfa7e0207f186bdb1d0f54420d0fa11
Later today I will be able to try upload with release version

**Comment by Shiaulis** [comment]
@Max-Job  Latest upload with this release works well 
```
Sentry: a0d4563fa4ddacba31fdcc35daaa8573d87224d6
```

**Comment by kevinrenskers** [comment]
@Max-Job gets the error with the 7.23 release
@Shiaulis does not get the error with the 7.23 release, but does get it with the master branch

I don't think we can pinpoint the exact reason behind this problem until one or both of you involves the App Review technical investigations team, or until we can trigger the same error with a sample app (which we haven't been able to do so far).

**Comment by kevinrenskers** [comment]
I've added sentry-cocoa to a real app (using the master branch), and it uploaded without errors, and it just finished processing as well. No errors. Same with one of our sample apps; it all uploads and processes just fine.

According to my conversation with Apple, our checking of `MPMediaLibrary.authorizationStatus` doesn't need the purpose string and shouldn't trigger any errors from App Store Connect either. At this point there is not a lot we can do here. Like I said on Friday: I don't think we can pinpoint the exact reason behind this problem until one or both of you involves the App Review technical investigations team.

**Comment by kevinrenskers** [comment]
Yeah but what's on the master branch will become the next release version of course. And it's the master branch that is triggering the error for you (but only you, so far).

**Comment by Shiaulis** [comment]
can it be that only we are affected just because the rest of apps are relying on latest stable release?

**Comment by kevinrenskers** [comment]
That is our fear. That once we create a new release, that we'll get many more reports. On the other hand I've now uploaded 6 builds across 2 apps with the master branch of sentry-cocoa and never get any errors, and Apple assures me it can't be our code. I'm pretty sure it's a bug in App Store Connect's validation, but we'll never find out for sure until someone challenges this error.

Our other option is to remove a [useful feature](https://github.com/getsentry/sentry-cocoa/pull/1984) from the upcoming release but even that might not be the solution as Max is getting the same error on release 7.23.0 which doesn't include any sort of music library code. We would really appreciate if you can open a TSI about this.

**Comment by Shiaulis** [comment]
I will keep TSI in my backlog 🙂 And maybe @Max-Job will also have time to file TSI 🙂

**Comment by armcknight** [comment]
I wonder if it's because we're simply linking the MediaPlayer/Photos/CoreLocation/UserNotifications frameworks. I found this [here](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources?language=objc):

> If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required for App Review.

**Comment by kevinrenskers** [comment]
The guy at Apple said that shouldn't be it, and then we'd also get those same validation errors, right? 🤔

**Comment by armcknight** [comment]
Yeah I actually misinterpreted that statement. I see no reason we are violating this rule.

**Comment by kevinrenskers** [comment]
This is what I heard from Apple today:

> I don’t see anything in that source file that would trigger that rejection. Do you have evidence that an API in that file is related to the rejection?
> 
> Perhaps the next step is for the developer with the rejection to contact App Review directly for clarification of what API is triggering the rejection. The developer can use the "Contact the App Review Team” form:
> 
> https://developer.apple.com/appstore/contact/?topic=clarification
> 
> When completing the form above, they should include the name of their app and its associated Apple ID.
> 
> Unless you can find a way to reproduce the problem on your own developer account, the developer who was rejected should start the investigation.

**Comment by choulepoka** [comment]
Continuation of original [comment](https://github.com/getsentry/sentry-cocoa/pull/2106#issuecomment-1235529687)

I have emailed Apple App Store Team, asking them to investigate this.

However, perhaps a stopgap measure would be to remove the feature completely, or at least make it optional somehow.

**Comment by kevinrenskers** [comment]
Or add `NSAppleMusicUsageDescription` to your Info.plist, even though it's not actually used. Reading the permissions does not trigger any dialog to the user.

**Comment by EdgarDegas** [comment]
Also having this issue with Sentry 7.24.0.

The build was uploaded successfully. But after a couple of minutes, I received an email about a _missing purpose string_:

> Dear Developer,

> We identified one or more issues with a recent delivery for your app, "<app name, censored>" 3.1.1 (2). Please correct the following issues, then upload again.

> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> Best regards,
> 
> The App Store Team

Then I downgraded Sentry to 7.23.0 and everything is OK now.

To sum up, I uploaded 3 builds, with no other changes but sentry's version.

- 3.1.1(1), with Sentry 7.1.3
- 3.1.1(2), 7.24.0
- 3.1.1(3), 7.23.0

In the end, in App Store Connect, I can see only 2 of them, the first one and the third one (app icon censored): 

<img width="363" alt="截屏2022-09-05 16 27 21" src="https://user-images.githubusercontent.com/12840982/188404966-c17425c5-2f2b-4051-8e95-c806fc778fda.png">

Reply if you need any more info.

**Comment by kevinrenskers** [comment]
Can you please use the "Contact the App Review Team” form: https://developer.apple.com/appstore/contact/?topic=clarification. That way hopefully we can get to the bottom of why the SDK is generating these errors, which should not be happening according to Apple themselves.

**Comment by EdgarDegas** [comment]
Sure.

**Comment by malcommac** [comment]
Same here with 7.24. Going back to 7.23, it's okay.

**Comment by Zandor300** [comment]
Experiencing the same with 7.24.0 but 7.23.0 is fine. Currently using 7.23.0 to get my builds through.

**Comment by choulepoka** [comment]
May I propose a solution that is to be implemented directly in the SentrySDK:

- Make the feature optional.
   - Create a secondary package that is essentially a plugin that when included / configured, will perform the permissions check
   - When absent, the package defaults to `unknown`

That way, people who actually _cares_ about permission being reported by Sentry will get them reported. And people like me who actually do not care for that information being reported by sentry won't get flagged by Apple.

**Comment by philipphofmann** [comment]
@brustolin, if removing the media permission check doesn't work, I think we can also discuss removing the whole permissions feature in general, as apps getting flagged by Apple is way worse than the value this tiny feature adds. I think adding an extra package is not worth the effort.

**Comment by EdgarDegas** [comment]
> Can you please use the "Contact the App Review Team” form: https://developer.apple.com/appstore/contact/?topic=clarification. That way hopefully we can get to the bottom of why the SDK is generating these errors, which should not be happening according to Apple themselves.

Sorry to bother you guys after this issue is closed. 

I did include this thread and pointed out all its worth-noticing details in my email. It seems that apple just ignored it.

They replied to my email with a bunch of cliche stating that any third-party lib that accessed any protected data would cause the app in need of purpose strings. We already know that. 

I'll reply to apple tough. *Beep* it.

**Comment by simondelphia** [comment]
Still have this in 7.24.0

**Comment by philipphofmann** [comment]
@EdgarDegas, and @simondelphia, please try with 7.24.1 and let us know if you still experience the issue. If you do, we are going to remove the whole permissions feature.

**Comment by Shiaulis** [comment]
7.24.1 works well for us

**Comment by RomanTysiachnik** [comment]
We have the same issue with `NSLocationAlwaysAndWhenInUseUsageDescription`, which we're not using.

cc: @philipphofmann

**Comment by philipphofmann** [comment]
Which version of the SDK are you using, @RomanTysiachnik?

**Comment by johnldeguzman** [comment]
It looks like we're also getting this same issue: `NSLocationAlwaysAndWhenInUseUsageDescription` despite not using locations. Using both 7.31.0 and 7.24.1

**Comment by philipphofmann** [comment]
Thanks for the info, @johnldeguzman. I created an issue for that https://github.com/getsentry/sentry-cocoa/issues/2528. Please upvote there.

**Comment by RomanTysiachnik** [comment]
Hey @philipphofmann, 

Sorry for taking so long. We have version `7.31.3`.

**Comment by kevinrenskers** [comment]
@RomanTysiachnik, @johnldeguzman out of curiosity: did you receive a warning, or actual rejections?

**Comment by johnldeguzman** [comment]
actual rejections

**Comment by maksudkhan7706** [comment]
Add This Line Your Info.plist file
**<key>NSAppleMusicUsageDescription</key>
<string>This app does not require access to your music library.</string>**
