### ISSUE TITLE
Add support to Swift in the SDK development

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2079]
### Description

With the rise of Swift adoption, Apple is starting to add Swift only features, having Swift as an option in the SDK will make development easier. 

We didn't do it before because of two reasons
 - ABI stability, but since Swift 5, the library is considered to be ABI stable.
 - Library size increase. Every project targeting iOS 12 or old needs to bundle Swift runtime in the project. We are already 3 years with the runtime in the OS itself, this is not a big problem anymore. There is not that many projects targeting iOS 12 or less.

However, one thing to keep in mind, is that due to cross-platform development binding, every public API needs to be written in OBJ-C.

**Comment by armcknight** [comment]
I'd say we could entertain this if there is a Swift-only feature we absolutely need and can't do in Objective-C. Do we have any examples of this so far?

The issue with some Swift-only features, like Swift enums, is that once you introduce them into an Objective-C codebase, they tend to require rewriting other areas as well. So we should be very careful if introducing Swift, because it can result in a lot of work for a small change.

**Comment by brustolin** [comment]
> o we have any examples of this so far?

- SwiftUI is already something that we can't property manipulate from obj-c.
- I get name demangle for "free"

> So we should be very careful if introducing Swift

I believe we should avoid coding in Swift for standard things, and use it only when really required.

**Comment by kevinrenskers** [comment]
How would we support SwiftUI anyway, if not via swizzling which needs Obj-C? Can't really hook into lifecycle calls and stuff any other way, right?

**Comment by kevinrenskers** [comment]
> I'd say we could entertain this if there is a Swift-only feature we absolutely need and can't do in Objective-C

Agreed. While I like Swift a hundred times more than ObjC, I am not so sure about mixing the two, where some internal things are done in Swift and all public API is done in ObjC. Unless it's something we really can't do in ObjC obviously.

**Comment by philipphofmann** [comment]
I agree with @kevinrenskers. I would start the discussion again once we have to build a feature in Swift and we can't use ObjC.
