### ISSUE TITLE
`dispatch_once` SDK init logic

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2081]
### Description

I noticed we track how many times the SDK start method is invoked, to only allow it to run once. Is there a reason we can't use `dispatch_once` to surround the logic that should only run once? We have a good bit of code/tests involved with this: 
![image](https://user-images.githubusercontent.com/3241469/185262752-77db153d-6460-4ff6-9e94-6caa4165600f.png)
and a comment on why we don't want multiple calls to run the same logic again:
>    // When calling SentrySDK.start twice we would wrongly report an OOM. We can only
>    // report an OOM when the SDK is started the first time.

**Comment by philipphofmann** [comment]
No, there is no real reason. If we use a wrapper for calling `dispatch_once`, so the tests keep working, we can refactor this.

**Comment by armcknight** [comment]
There was a workflow I wasn't considering. Originally I thought startInvocations guarded against multiple sequential calls to start the SDK, like so:
```
SentrySDK.start...
SentrySDK.start...
```
but it is actually there to fix our OOM reporting if consumers start, close and then start the SDK again:
```
SentrySDK.start...
// ...
SentrySDK.close()
// ... 
SentrySDK.start...
```
