### ISSUE TITLE
How to correctly pass CPU register values to the SentryStacktrace initialiser?

### ISSUE THREAD

**Issue by AlexanderKaraberov** [getsentry/sentry-cocoa#209]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.0?
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.7.1**

---
I have following issue/question:

I noticed new initialiser and a property `registers` were added to the `SentryStacktrace`after I had updated the library. Comment only says: `"Registers of the thread for additional information used on the server"` which is not that helpful unfortunately. If I understood correctly this property means CPU registers. I wonder how can I properly initialise stacktrace with registers values? Maybe there is something inside KSCrash to help me with this?

**Steps to reproduce:**
Currently I did this with inline assembly:

```assembly
    int W0;
    int W1;
    int W2;
#if TARGET_CPU_ARM64
    asm ("STR W0, %0\n"
              "STR W1, %1\n"
              "STR W2, %2\n" : "=m" (W0), "=m" (W1), "=m" (W2));
#endif
    SentryStacktrace *sentryStacktrace = [[SentryStacktrace alloc] initWithFrames:frames
                                                                        registers:@{@"W0":@(W0),
                                                                                        @"W1":@(W1),
                                                                                        @"W2":@(W2)}];
```
As you see this looks pretty cumbersome and tedious. I know it's a long shot, but hopefully there are better ways to initialise stacktrace with all AArch64 registers values, namely `X0`-`X30`/`W0`-`W30`, `SP_EL0`-`SP_EL3`, link registers and so on. Otherwise I don't really understand the purpose of this property.

**Comment by HazAT** [comment]
Hey,
This property will be filled by KSCrash crash reports, we use some of the registers to symbolicate frames. We don't show the registers anywhere in the UI and therefore there is actually no purpose filling it by yourself.
Could you explain what you are trying to achieve?

**Comment by AlexanderKaraberov** [comment]
@HazAT Thanks. Sometimes it may be useful to see register values for debugging purposes, but if Sentry doesn't show them in the UI then you are right and there is no purpose. I was just confused, because it is a public property and it is used in the initialiser, but I guess this was done intentionally to allow KSCrash to init stacktraces with register values?
So you recommend to always init this property with empty dictionary when I create a stacktrace?

**Comment by HazAT** [comment]
@AlexanderKaraberov Yeah I would call it with an empty dictionary since it requires specific registers (which we haven't documented)

**Comment by AlexanderKaraberov** [comment]
Thanks for the info! Closing issue.
