### ISSUE TITLE
Implement Culture Context

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2092]
### Description

Add culture context to the scope.

Specs [here](https://develop.sentry.dev/sdk/event-payloads/contexts/#culture-context).

Keep in mind to remove information from other contexts, like `timezone` from device context.

**Comment by kevinrenskers** [comment]
Isn't that just the same as https://github.com/getsentry/sentry-cocoa/pull/2036?

**Comment by brustolin** [comment]
Wow, this was made already, so we just need to remove timespan from device context, but not a priority.

**Comment by kevinrenskers** [comment]
We just need to make a new release 😅
