### ISSUE TITLE
Add tracingOrigins options to Performance instrumentation.

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-cocoa#2099]
### Problem Statement

The cocoa SDK currently attaches the `sentry-trace` header to all outgoing requests from the application. Users might want to restrict the header only to requests sent to their APIs, the same way it is done in JavaScript-based SDKs.

### Solution Brainstorm

An implementation similar to Browser SDK: https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracingorigins

**Comment by philipphofmann** [comment]
This concept was replaced by https://github.com/getsentry/sentry-cocoa/issues/2148.
