### ISSUE TITLE
Fix disabled `SentryClientTests` test to capture message

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2103]
### Description

We have a disabled test here: https://github.com/getsentry/sentry-cocoa/blob/86e8170960ad82b7f1ace0523d64dde5b751b5c5/Tests/SentryTests/SentryClientTests.swift#L135-L146

**Comment by kevinrenskers** [comment]
It's absolutely not reproducible locally. And while I have seen some test failures in https://github.com/getsentry/sentry-cocoa/pull/2142 for example, `testCaptureMessage` wasn't among them. I think we can reenable it? I'll create a PR, run the tests a few times, see what happens.

**Comment by brustolin** [comment]
This test is not disabled, so it must be working.

Let me know otherwise.
