### ISSUE TITLE
Fix flaky `SentrySystemEventBreadcrumbsTest` test case

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2114]
### Description

`testTimezoneChangeNotificationBreadcrumb`

See for example https://github.com/getsentry/sentry-cocoa/runs/8103678791?check_suite_focus=true#step:9:51

**Comment by philipphofmann** [comment]
@armcknight, please add the `Type: Flaky Test` label the next time so we can easily keep track of the flaky test issues.

**Comment by kevinrenskers** [comment]
This one isn't disabled, but yeah I've seen it fail a few times. But never locally.

**Comment by kevinrenskers** [comment]
I don't think I've seen it happen anymore, or we would've disabled the test by now. Probably the switch to the Notification Center wrapper fixed it? I think we close this one!
