### ISSUE TITLE
GA AppHangs, File I/O, CoreData, Screenshots, UI interaction events

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#2143]
### Description

We have 5 features opt-in atm:

```
    // Enable all experimental auto instrumentation features
    options.enableFileIOTracking = true
    options.enableCoreDataTracking = true
    options.enableUserInteractionTracing = true
    options.enableAppHangTracking = true
    options.attachScreenshot = true
```

- [ ] Release a major with all of them as GA.
- [x] Other than Screenshots, all of them should be opt-out.
- [x] Adjust wizard: https://github.com/getsentry/sentry-docs/blob/master/src/wizard/apple/ios.md#performance-monitoring
- [x] https://github.com/getsentry/sentry-cocoa/pull/2212
- [x] https://github.com/getsentry/sentry-cocoa/pull/2213

**Comment by philipphofmann** [comment]
App hangs is already GA but disabled per default.

**Comment by philipphofmann** [comment]
I think we could enable core data and file I/O per default also in a minor release once we know it doesn't break anyone. Those features only add spans, so no impact on quota. What we could do already know is to make them GA and keep them disabled per default.

**Comment by philipphofmann** [comment]
All done expect user interaction tracing. Created an extra item for this https://github.com/getsentry/sentry-cocoa/issues/2298
