### ISSUE TITLE
Xcode 14 issues

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2144]
### Description

We have some warnings, and some actual errors preventing the tests from running:

![Screen Shot 2022-09-13 at 10 09 19](https://user-images.githubusercontent.com/229384/189847357-b4b3cfaf-97e8-4735-80b4-1f07b4e763ed.png)

Do the warnings mean we can't use Xcode 14 to build the project? We might need to increase the minimum iOS version unless we want to keep old versions of Xcode around, which eventually won't work on newer macOS releases any more.

**Comment by philipphofmann** [comment]
Shouldn't this be fixed with #2146, @kevinrenskers?

**Comment by kevinrenskers** [comment]
The errors are fixed, but the warnings are still there so I didn't close the issue as my question above is still unanswered.

**Comment by philipphofmann** [comment]
Ah, sorry missed that. We can only bump the deployment target in a major release. So it's fine to ignore it for now.

**Comment by kevinrenskers** [comment]
Yes, but my real question was if we can even create a release using Xcode 14, or if we need to stick to Xcode 13 for that. If we need to stick to Xcode 13, that major release bump should come sooner rather than later because as soon as the next major macOS version releases, it's pretty likely that Xcode 13 won't run on it.

**Comment by philipphofmann** [comment]
I don't think we need to bump that. It's just a warning. I think iOS 9 was also a warning already for Xcode 13.
