### ISSUE TITLE
Support tracePropagationTargets

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2148]
### Description

According to https://github.com/getsentry/team-mobile/issues/49, we need to add an option to users provide tracePropagationTargets in order to send trace_id header only to this targets.

See https://develop.sentry.dev/sdk/performance/#tracepropagationtargets for more information.

**Comment by kevinrenskers** [comment]
@brustolin Do we actually send a `trace_id` header? Or is the `trace_id` only sent as part of the `baggage` header? As far as I can tell we only add one header inside of `addTraceHeader`, just wanted to make sure this is correct.

**Comment by brustolin** [comment]
[Here](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryNetworkTracker.m#L123-L150)
