### ISSUE TITLE
Build error on 'captureMessage'

### ISSUE THREAD

**Issue by ramunasjurgilas** [getsentry/sentry-cocoa#215]
_Platform:_
- [ ]  iOS

_Swift:_
- [ ]  Yes -> 3.2

_sentry-cocoa installed with:_
- [ ] CocoaPods

Version of sentry-cocoa:
**3.8.1**

Error on code line: Client.shared?.captureMessage("Error!", level: .error)
/Users/Wrapper.swift:167:26: Value of type 'Client' has no member 'captureMessage'

What to use instead?

**Comment by HazAT** [comment]
https://docs.sentry.io/clients/cocoa/advanced/#sending-events
We removed some of the public api on the last major version bump to keep it as small as possible.

**Comment by ramunasjurgilas** [comment]
Thanks!
