### ISSUE TITLE
Issue Ownership

### ISSUE THREAD

**Issue by embassem** [getsentry/sentry-cocoa#2156]
### Platform

iOS

### Installed

CocoaPods

### Version

7.24.1

### Steps to Reproduce

1. Create a new Framework and have a crash func inside it
2. use this package from an example app and call the func to crash the app 
3. create an issue onwnership on the dashboard using type `module: FRAMEWORK_NAME` and assign it to member/team

### Expected Result

the crash should be suggested or assigned to the member/team

### Actual Result

this is not happening because 
Sentry on Dashboard is using `stacktracke.module` values  for the issue ownership rule `module` but  the reported stack from the iOS SDK is Ignoring the  `SentryFrame.module` and only sends `SentryFrame.package` 

https://github.com/getsentry/sentry-cocoa/blob/2168cdc3bd2dbbe520316513015af1fb547c9bfc/Sources/Sentry/Public/SentryFrame.h#L25-L34

<img width="403" alt="Screen Shot 2022-09-14 at 10 45 22 AM" src="https://user-images.githubusercontent.com/6951824/190106765-d4033a73-a861-4838-b228-ab4f12a7c0a8.png">

**Comment by philipphofmann** [comment]
Thanks for pointing that out, @embassem. While we could start sending `module`, I first have to check what implications that would trigger.

I need to clarify the exact difference between module and package, as our develop docs https://develop.sentry.dev/sdk/event-payloads/stacktrace/ don't give me a clear answer. 

The Android SDK sends module, but not package. Same for the Python SDK. Maybe the solution is also that issue ownership would work with package as well. I will clarify that and get back to you.

**Comment by philipphofmann** [comment]
For reference, [internal Slack discussion](https://sentry.slack.com/archives/GA1BA7076/p1664370935505289).

**Comment by philipphofmann** [comment]
The SDK uses the imageName as `package`. The imageName contains the full path to the image, such as

- "/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore"
- "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation"
- "/private/var/containers/Bundle/Application/ED1CA0BB-A6D4-45AB-9232-9EE2802D9C7F/iOS-Swift.app/iOS-Swift"

Although the SDK sends the full path to Sentry, the JSON payload in Sentry only contains the last path components, such as UIKitCore, or iOS-Swift. So we strip the path somewhere in Sentry.

I think we could start sending `module` with the same value, which Sentry doesn't strip. So it would be the whole image path, which would align with our develop docs: `Platform-specific module path (e.g. sentry.interfaces.Stacktrace)`.

**Comment by philipphofmann** [comment]
Unfortunately, setting `SentryFrame.module` impacts grouping; see [docs](https://docs.sentry.io/product/data-management-settings/event-grouping/#grouping-by-stack-trace) and screenshot:

<img width="781" alt="Screenshot 2023-02-28 at 09 05 11" src="https://user-images.githubusercontent.com/2443292/221791243-09239831-6a0b-485a-af6d-87eebdd9bfef.png">

I have to validate if we can make some changes on the backend to make this a nonbreaking change. Even if we do this in a major bump, it'd be highly annoying to users as every issue grouped by stacktrace would end up in a new group.

**Comment by brustolin** [comment]
> Unfortunately, setting `SentryFrame.module` impacts grouping; 

I believe is high unlikely that issues created by different modules have the same stacktrace, so they will end up in a new group anyway.

**Comment by philipphofmann** [comment]
@brustolin, have a look at https://sentry-sdks.sentry.io/issues/?project=5428557&query=is%3Aunresolved+captured+a+message&referrer=issue-list&statsPeriod=14d.

<img width="983" alt="Screenshot 2023-02-28 at 11 31 42" src="https://user-images.githubusercontent.com/2443292/221828239-61ce935b-b273-4fa3-b44e-1476fc7b019a.png">

### Existing Grouping 

https://sentry-sdks.sentry.io/issues/2895893229/events/b3a2e3a1132c43a6a5fefe8dd9e58171/?project=5428557
<img width="821" alt="Screenshot 2023-02-28 at 11 34 41" src="https://user-images.githubusercontent.com/2443292/221829027-e4cf737b-d0d1-4833-9242-d76ab4299ec0.png">


### New Group 1
https://sentry-sdks.sentry.io/issues/3963189205/events/1c3b5d72e9004849b54ba3a7128eb5b0/?project=5428557
<img width="649" alt="Screenshot 2023-02-28 at 11 32 17" src="https://user-images.githubusercontent.com/2443292/221828377-51424300-aa04-44cb-b832-fa27aaf95dd3.png">

### New Group 2 


https://sentry-sdks.sentry.io/issues/3963200633/events/a9bebe6f64da4a2ab31968d46d4d1ef4/?project=5428557
<img width="823" alt="Screenshot 2023-02-28 at 11 33 41" src="https://user-images.githubusercontent.com/2443292/221828783-0c302192-8e21-44da-9d89-94118f501d05.png">

**Comment by brustolin** [comment]
You mean, errors will change from one group to another when we add modules, but then the groups will be consistent in the new rule? 

IMO this is not a problem.

**Comment by philipphofmann** [comment]
> IMO this is not a problem.

It will trigger tons of alerts, and the same issues will end up in different groups depending on the Cocoa SDK version. That's why it's a problem.

**Comment by philipphofmann** [comment]
@embassem, until we support module for issue ownership, you should be able to paths, as the SDK sends these, see https://docs.sentry.io/product/issues/issue-owners/#methods.

**Comment by philipphofmann** [comment]
@embassem, is it working correctly for you? Anything we can improve?

**Comment by kahest** [comment]
I'm gonna close this now as it is stale. Please let us know if this is still relevant for you.
