### ISSUE TITLE
Pre compiled binary does not have app-safe-extension-api checked

### ISSUE THREAD

**Issue by mxcl** [getsentry/sentry-cocoa#217]
<img width="1072" alt="screen shot 2017-09-28 at 10 38 26 pm" src="https://user-images.githubusercontent.com/58962/30998597-d35cb10c-a49d-11e7-8d4d-4657f09e07ef.png">

Please check the box so when we use your framework in extensions we don't get this warning. Thanks.

**Comment by HazAT** [comment]
@mxcl I will release a new release today with your PR.
Thanks

**Comment by HazAT** [comment]
`3.8.2` is released 👍
