### ISSUE TITLE
Sentry in Framework and App - Duplicate Symbols

### ISSUE THREAD

**Issue by cosmicvarion** [getsentry/sentry-cocoa#2171]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.X.X

### Steps to Reproduce

1. Create a framework
2. Add Sentry as Swift package dependency
3. `@_implementationOnly import sentry`
4. Archive framework -> create Xcframework -> add as `binaryTarget` in Swift package
5. Create an iOS app and add the Swift package as a dependency
6. Add Sentry as Swift package in iOS app
7. Run the app and you will see runtime errors from duplicate symbols from Sentry in the framework overlapping with Sentry in the iOS app
Different versions of Sentry in our framework and a customer app may introduce subtle bugs.

### Expected Result

No runtime errors due to duplicate symbols. 

### Actual Result

Runtime errors in Xcode console:
```
Class <some Sentry class> is implemented in both <framework> and <app>. One of the two will be used. Which one is undefined.
...
```

**Comment by brustolin** [comment]
Hello @cosmicvarion. Thanks for you interest in using Sentry, but our SDK is not meant to be used in Framework/Libraries. In fact, we do not support two instances of the SDK running in the same project pointing to different DSNs.
