### ISSUE TITLE
HTTP Calls included in breadcrumb when opted out. 

### ISSUE THREAD

**Issue by martindufort** [getsentry/sentry-cocoa#2191]
### Platform

macOS

### Installed

Swift Package Manager

### Version

7.25.1

### Steps to Reproduce

When starting the Sentry SDK in debug mode, we can see http calls being added to the breadcrumbs even if we have stated not to track them.

See below for our init:

```swift
		SentrySDK.start { options in
			options.dsn = "https://xxxxxx"
			options.releaseName = AppDelegate.appVersion
			options.dist = "macos"

			// No instrumentation tracking please....
			options.enableAutoPerformanceTracking = false
			options.enableAutoSessionTracking = false
			options.enableNetworkTracking = false	// No reporting of HTTP calls
			
			// Number of bread crumbs for reporting
			options.maxBreadcrumbs = 10
			#if DEBUG
			options.environment = "development"
			options.debug = true
			#else
			options.environment = "production"
			options.debug = false
			#endif
		}
```

Anything we are not seeing?

### Expected Result

HTTP Calls tracking should **not** be reported

### Actual Result

HTTP Calls are included in the breadcrumbs **and** visible in the Sentry console.

**Comment by philipphofmann** [comment]
There is an extra option for breadcrumbs `enableNetworkBreadcrumbs`.  `enableNetworkTracking` is only for auto-generated spans for HTTP requests for performance monitoring. I just saw that the code docs are misleading. I'm going to update them.

**Comment by martindufort** [comment]
Thanks @philipphofmann. Working perfectly now.
