### ISSUE TITLE
Fix flaky test_DataConsistency_readPath

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2199]
### Description

Starting today I am seeing this one in multiple PRs, completely unrelated to any code changes in those PRs. Rerunning helps.

```
Failing tests:
	iOS-SwiftUITests:
		SentryFileIOTrackingIntegrationTests.test_DataConsistency_readPath()
```

**Comment by philipphofmann** [comment]
Also `SentryFileIOTrackingIntegrationTests.test_DataConsistency_readUrl` sometimes fails

**Comment by kevinrenskers** [comment]
I'm not really sure what `test_DataConsistency_readUrl` even tries to test. It writes to a file and immediately reads from it, and checks if the values are equal. I don't think we need to test data writing to and reading from disk? Same with `test_DataConsistency_readPath`, it really doesn't seem to actually test any SDK logic.

**Comment by philipphofmann** [comment]
Those tests ensure that our swizzling logic for NSData doesn't break NSData.

**Comment by kevinrenskers** [comment]
Yup that is what @brustolin said in #2531 and I ended up closing the PR.
