### ISSUE TITLE
Carthage build failed on Carthage 0.26

### ISSUE THREAD

**Issue by alphatroya** [getsentry/sentry-cocoa#221]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> Swift 4
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.8.2, 3.8.3**

---
I have following issue:

Impossible to build framework after latest carthage update (0.26). On the previous version build finished fine

**Steps to reproduce:**
- Add `github "getsentry/sentry-cocoa"` entry to the Cartfile
- Invoke `carthage update --platform iOS --no-use-binaries sentry-cocoa`

**Actual result:**
- Carthage build failed with message ``` Failed to read file or folder at /Users/alphatroya/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/sentry-cocoa/3.8.3/Build/Intermediates.noindex/ArchiveIntermediates/Sentry/BuildProductsPath/Release-iphoneos/Sentry.framework ```

**Expected result:**
- Carthage build succeed

**Comment by alphatroya** [comment]
Looks like a carthage bug https://github.com/Carthage/Carthage/issues/2208 but maybe you may suggest a temporary workaround

**Comment by HazAT** [comment]
Can you try it with version `0.24` of carthage?
Otherwise, I will release a new version built with `0.26` and see if that fixes the problem.

**Comment by jan-auer** [comment]
Also just happened on https://travis-ci.org/getsentry/sentry-cocoa/jobs/286900859

**Comment by alphatroya** [comment]
Looks like the bug was fixed in 0.26.1
