### ISSUE TITLE
App Hang Tracker thread still running even if configuration is turned off.

### ISSUE THREAD

**Issue by martindufort** [getsentry/sentry-cocoa#2214]
### Platform

macOS

### Installed

Swift Package Manager

### Version

7.25.1

### Steps to Reproduce

We have setup our Sentry install so it will not track `app hangs`. 

This is our complete config setup

```swift
		SentrySDK.start { options in
			options.dsn = "https://xxxx"
			options.releaseName = AppDelegate.appVersion
			options.dist = "macos"

			// No instrumentation tracking please....
			options.enableAutoPerformanceTracking = false
			options.enableAutoSessionTracking = false
			options.enableNetworkTracking = false
			options.enableNetworkBreadcrumbs = false
			options.enableSwizzling = false
			options.enableAppHangTracking = false
			
			// Number of bread crumbs for reporting
			options.maxBreadcrumbs = 10
			#if DEBUG
			options.environment = "development"
			options.debug = true
			#else
			options.environment = "production"
			options.debug = false
			#endif
		}
```

### Expected Result

The list of running threads **should not** contain the Sentry app-tracker thread.

### Actual Result

The Sentry app hand-tracker thread is still running. 

<img width="500" alt="CleanShot 2022-09-22 at 13 21 15" src="https://user-images.githubusercontent.com/28934641/191812479-95978fa9-641f-4901-b372-52495340a048.png">

We are expecting this thread to **not be started at all**

Thanks

**Comment by philipphofmann** [comment]
If you have out of memory tracking enabled, which is enabled per default, we also need the ANRTracker, because our OOM logic would otherwise assume that ANRs leading to crashes are OOMs; see #1695.

**Comment by philipphofmann** [comment]
Opened a PR to clarify this in the docs https://github.com/getsentry/sentry-docs/pull/5553. I think that should answer your question, @martindufort. Please reopen if it doesn't.

**Comment by martindufort** [comment]
Thanks @philipphofmann. That clarifies everything. Good job.
