### ISSUE TITLE
Unit test or try building on earliest supported platform versions in CI

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2218]
### Description

I had the podspec validation fail due to 

> warning: 'scheduledTimerWithTimeInterval:repeats:block:' is only available on iOS 10.0 or newer
> warning: 'scheduledTimerWithTimeInterval:repeats:block:' is only available on macOS 10.12 or newer

but this error didn't happen anywhere else. It would be nice to have minimum API checks for all the platforms. Usually this happens in Xcode, I'm not sure why this wasn't caught.

Relatedly, I noticed that the github action image providing Xcode 10 is deprecated and will no longer be supported as of 1 Dec 2022 ([source](https://github.com/actions/runner-images/issues/5583)). We should either figure out a way to continue testing on that platform, or consider bumping up our minimum supported platform versions to things we can actually test.

**Comment by philipphofmann** [comment]
I investigated a few options on how to solve this problem.

## Saucelabs
As we already use Saucelabs, I checked if it supports running unit tests on Simulators. Sadly, I didn't find anything in their [docs](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/). 

## Firebase Test Lab

According to [their docs](https://firebase.google.com/docs/test-lab/ios/run-xctest) you can run unit tests, but this would mean we need to setup another service.

## Keep using GH actions

According to [this comment](https://github.com/actions/runner-images/issues/551#issuecomment-788822538) GH concluded some time ago to not add additional installed simulators:

> after long and hot internal discussions, we come up to a conclusion to not install additional simulators due to several reasons:
> 
> 1. Workaround provided in https://github.com/actions/virtual-environments/issues/551#issuecomment-669226983 allows using simulators of different Xcode versions without any noticeable build time increase.
> 2. We cannot afford to install more simulators for each Xcode due to maintenance, image generation time and image space concerns.

Therefore, we would need to install our simulators manually, which could take some time. We would need to download them and then call something like 
```
xcrun simctl runtime add "~/Downloads/watchOS 9 beta Simulator Runtime.dmg"
```
We could put the simulator runtime into the GH actions cache to speed up the process.

Useful resources:
* https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
* https://github.com/actions/runner-images/issues/551
* https://zeeshankhan.github.io/posts/github-action/
