### ISSUE TITLE
NSDebugDescriptionErrorKey does not change the error description on the Issues page

### ISSUE THREAD

**Issue by imjamesim** [getsentry/sentry-cocoa#2223]
### Core or SDK?

Platform/SDK

### Which part? Which one?

ios/usage/#customizing-error-descriptions

### Description

Excerpt from [Customizing Error Descriptions section on the Usage for iOS page](https://docs.sentry.io/platforms/apple/guides/ios/usage/#customizing-error-descriptions):

> By default, Sentry will display the error code as the error description. For custom error types, you may want to provide a custom description that makes it easier to identify the error in the Issues page. You can provide a custom description for NSError values by adding a description to the userInfo dictionary with the key NSDebugDescriptionErrorKey.

Although I've added a description to the userInfo dictionary with `NSDebugDescriptionErrorKey`, I'm not seeing the description anywhere on the Issues page. I do, however, see the description under the User Info section once I click into the specific issue's details page.

### Suggested Solution

Show the custom descriptions on the Issues page.

**Comment by brustolin** [comment]
@imjamesim Thanks for pointing this out. We going to investigate.

**Comment by philipphofmann** [comment]
@imjamesim, can you please share a code snippet for us to reproduce your issue?

**Comment by imjamesim** [comment]
@philipphofmann here's a snippet that shows how we're using `NSDebugDescriptionErrorKey` to provide a custom debug description for Apollo's `GraphQLError`:

```
extension GraphQLError: CustomNSError {

    ...

    public var errorUserInfo: [String: Any] {
        var userInfo = [String: Any]()
        if let message = message {
            userInfo[NSDebugDescriptionErrorKey] = message
        }
        return userInfo
    }
}

```

**Comment by philipphofmann** [comment]
Docs PR https://github.com/getsentry/sentry-docs/pull/5583.

**Comment by imjamesim** [comment]
@philipphofmann ah we were on 7.23.0. I just confirmed this works as expected on 7.27.0. Thanks for the clarification!
