### ISSUE TITLE
Transmit crashes using background requests

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2231]
### Description

Sometimes the app crashes and the user don't open it again.

We could check if the app supports background requests, and if so, we try to send the envelope in the background. This way the OS is responsible for uploading the envelope, the app does not need to be open.

**Comment by kevinrenskers** [comment]
But once the app is crashed you can't start a new background request, can you?

**Comment by brustolin** [comment]
Its dangerous to tap into objc during signal handling but its is possible. 
And we also could schedule all the upload during initialisation before the app crashes again or the user closes the app.

**Comment by brustolin** [comment]
This is apples documentation

>If an iOS app is terminated by the system and relaunched, the app can use the same identifier to create a new configuration object and session and to retrieve the status of transfers that were in progress at the time of termination. This behavior applies only for normal termination of the app by the system. If the user terminates the app from the multitasking screen, the system cancels all of the session’s background transfers. In addition, the system does not automatically relaunch apps that were force quit by the user. The user must explicitly relaunch the app before transfers can begin again.

In summary, this feature will no work if the app crashes or the users kills the app.
It may be helpful to transmit crashes if the user quickly switch apps after reopening.

**Comment by philipphofmann** [comment]
> It may be helpful to transmit crashes if the user quickly switch apps after reopening.

Thanks for looking into that, @brustolin. I think it's not worth the effort for that edge case. I would close the issue.

**Comment by kevinrenskers** [comment]
I agree with @philipphofmann
