### ISSUE TITLE
'SentryPerformanceTracker+Private.h' file not

### ISSUE THREAD

**Issue by lewis-smith** [getsentry/sentry-cocoa#2240]
### Platform

iOS

### Installed

CocoaPods

### Version

7.26.0

### Xcode Version

14.1.0 b 2

### Steps to Reproduce

1. install 7.26.0 via pods
2. do clean + build
3. see compile error

This may somehow be specific to my project, but the compile failure is inside the pod

### Expected Result

Should compile

### Actual Result

Compiler error

`'SentryPerformanceTracker+Private.h' file not found`

https://cln.sh/1XUYUq

**Comment by lewis-smith** [comment]
I downgraded to Sentry 7.25.1 and the build issues go away.

**Comment by kevinrenskers** [comment]
Strange, it works fine when I create a brand new Xcode project, add Sentry via Cocoapods, and build & run.

Can you check if `SentryPerformanceTracker+Private.h` is missing from the Sentry pod? (Should be in Pods > Sources > Sentry > includes).

**Comment by lewis-smith** [comment]
you are right. I ran pod update again (I had rolled back to the previous sentry) and everything worked. must have been a glitch in Xcode or cocoapods. thanks for looking into it, sorry to have taken your time.

**Comment by kevinrenskers** [comment]
No problem at all, just glad it wasn't a horrible bug 😅

**Comment by philipphofmann** [comment]
No worries, @lewis-smith, if this would have been a bug, it would be horrible, like @kevinrenskers already pointed it out.
