### ISSUE TITLE
Could not decode report: Data too long (React Native)

### ISSUE THREAD

**Issue by elliottkember** [getsentry/sentry-cocoa#2258]
### Platform

iOS

### Installed

CocoaPods

### Version

7.27.0

### Steps to Reproduce

- Trigger an error in a React Native application using Sentry with `Sentry.nativeCrash()`
- No error shows up in Sentry dashboard

I have minimal data in my `userInfo`, but this `objectPath` in FixupContext keeps causing the data to be too long.

### Expected Result

The error should show up in Sentry

### Actual Result

It doesn't!

Logs indicate that the data is too long. On a breakpoint, I get indications that there are a lot of empty `\0` characters in the data that is trying to be sent. I believe these contribute to the problem. 

I think it may also be related to the Sentry `reduxEnhancer` that is storing a bit of state data.

Adding a 0 to `SentryCrashMAX_STRINGBUFFERSIZE` seems to alleviate the problem, as does increasing `MAX_DEPTH`.

```
ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
ERROR: SentryCrashC.c (277): char *sentrycrash_readReport(int64_t): Failed to fixup report ID da800000
```
![image](https://user-images.githubusercontent.com/42827/193927968-e305815e-2452-464e-8aa4-470a425b8077.png)
<img width="1234" alt="image-1" src="https://user-images.githubusercontent.com/42827/193927975-0b18a0bc-f9e7-46a7-86d8-5e39853a2483.png">

**Comment by brustolin** [comment]
Hey @elliottkember. Thanks for pointing this out. Can you give us more information about your project? Like, what kind of information are you adding into the SDK before trigging the error? What other dependencies does your project have? Can you provide us with a small repro?

@krystofwoldrich can you help trying to reproduce this?

**Comment by krystofwoldrich** [comment]
@brustolin Ofc, I've checked with our sample app, and that one is sending native crashes.

We will need some steps/repo on how to reproduce. Also, a version of RN and RN SDK could be helpful.

**Comment by elliottkember** [comment]
> Hey @elliottkember. Thanks for pointing this out. Can you give us more information about your project? Like, what kind of information are you adding into the SDK before trigging the error? What other dependencies does your project have? Can you provide us with a small repro?
> 
> @krystofwoldrich can you help trying to reproduce this?

Sorry, I only just saw this. In our case it was due to our redux enhancer. We were accidentally sending through a part of the store that contained lots of state data.

This was our mistake - but it was quite hard to spot. The only clue we had was in the native Xcode logs while the app started up, where sentry quietly logs that the native crash data was too large, and then doesn’t report the crash. 

I don’t think there are any other dependencies involved - adding too much data to sentry in JS just causes a silent loss of native crashes. We missed a few native crashes. 

It would be ideal if we could either discard some of the data before submitting, report the failure as an error, or warn somehow. I would be happy to help fix this if you think it is fixable.

**Comment by philipphofmann** [comment]
> This was our mistake - but it was quite hard to spot. The only clue we had was in the native Xcode logs while the app started up, where sentry quietly logs that the native crash data was too large, and then doesn’t report the crash.

Which log message did you get, @elliottkember? 

I think we could do a better job of communicating that the SDK drops such events. An idea would be to add it to the dropped events of client reports so you would see it in Sentry https://develop.sentry.dev/sdk/client-reports/#envelope-item-payload.

**Comment by elliottkember** [comment]
> ```
> ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
> ERROR: SentryCrashC.c (277): char *sentrycrash_readReport(int64_t): Failed to fixup report ID da800000
> ```

**Comment by elliottkember** [comment]
@philipphofmann With a `Sentry.createReduxEnhancer` ([docs here](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/redux/)) using a `stateTransformer` that wasn't scoped accurately enough.

**Comment by philipphofmann** [comment]
Thanks, @elliottkember, for the update. To solve the issue, we could increase the limit of `SentryCrashMAX_STRINGBUFFERSIZE`.

**Comment by philipphofmann** [comment]
`SentryCrashMAX_STRINGBUFFERSIZE` ensure doesn't exceed the envelope limits of Relay.

**Comment by elliottkember** [comment]
> `SentryCrashMAX_STRINGBUFFERSIZE` ensure doesn't exceed the envelope limits of Relay.

I think that would be an improvement! People might still hit this issue when inadvertently adding too much data. 

A better solution might be to report to sentry that a crash error was reported that cannot be uploaded because it's too big? That way the error will at least come through to the Sentry dashboard and will be seen.

**Comment by philipphofmann** [comment]
> A better solution might be to report to sentry that a crash error was reported that cannot be uploaded because it's too big? That way the error will at least come through to the Sentry dashboard and will be seen.

That's something we don't do because we don't want to eat up your quota because of SDK errors.

**Comment by elliottkember** [comment]
> That's something we don't do because we don't want to eat up your quota because of SDK errors.

The original error was a real error, and was not reported. So it would not be eating quota, just reporting an error that can't be submitted - this is what the quota is for especially if I can catch the error during testing and fix it before a release.

I wouldn't even consider this an SDK error, more of a bad configuration. And I would much rather see an error from the SDK about a bad configuration, than never receive a crash report. It's entirely possible to **never receive native crash reports** and not be aware it's happening. That's pretty much the worst case scenario, and this is the situation I was in.

Ideally, it would strip the excess data and report the error message, with a warning that the data was too big. But squashing the crash report entirely is really bad.

**Comment by philipphofmann** [comment]
> Ideally, it would strip the excess data and report the error message, with a warning that the data was too big. But squashing the crash report entirely is really bad.

Yes, that's what we are aiming for.
