### ISSUE TITLE
A required debug symbol file was missing. 

### ISSUE THREAD

**Issue by MohitSinghal** [getsentry/sentry-cocoa#226]
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> If yes, which version? 3.1

_sentry-cocoa installed with:_
- [x] CocoaPods

Version of sentry-cocoa:
**3.9.1**

---
**I have following issue:**

I am working on Xcode 8.1. A required & optional debug symbol file was missing after uploading all DSYM's through terminal. I have added info.plist path for version. 

A required debug symbol file was missing.
{
  "image_arch": "arm64",
  "image_uuid": "05a61416-96c4-3a83-94d1-ffa5dc23c613",
  "message": "None",
  "image_path": "/var/containers/Bundle/Application/453A60B1-2C74-44F5-9FBC-E94B5A451A02/ABC.app/ABC"
}

An optional debug symbol file was missing
{
  "image_arch": "arm64",
  "image_uuid": "535d167c-155d-3f9d-8848-8d1a9d2ca922",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/453A60B1-2C74-44F5-9FBC-E94B5A451A02/ABC.app/Frameworks/KSCrash.framework/KSCrash"
}

Both issues are showing in Sentry log. I do not found debug symbols for more clarification over issue.
![screen shot 2017-11-28 at 6 14 29 pm](https://user-images.githubusercontent.com/5165660/33320683-10b5fea0-d469-11e7-8981-2750335b67a8.png)
What is missing here further after putting DWARF and dSYM file?

**Steps to reproduce:**
Upload the all DSYM's and info.plist through terminal. 

**Actual result:**

![screen shot 2017-11-28 at 6 20 48 pm](https://user-images.githubusercontent.com/5165660/33320634-e77c050c-d468-11e7-84ad-743dce4e44b6.png)

**Expected result:**
Fully symbolicated trace and no required & optional debug symbol file missing warning.

**Comment by HazAT** [comment]
What command are you running in your terminal?

**Comment by MohitSinghal** [comment]
Here is the command:

sentry-cli --auth-token 395d7e6ce5e84803bb6e972b5b2705a01249a9941de64e72b9162d2c7e02e252 upload-dsym --org XYZ --project ABC-ios /Users/mohit.kumar1/Library/Developer/Xcode/Archives/2017-11-28/ABC\ 28-11-17\,\ 4.58\ PM.xcarchive/dSYMs --info-plist /Users/mohit.kumar1/ABC-ios/ABC/Info.plist

**Comment by HazAT** [comment]
Can you make sure you enabled reprocessing in your project?
You can find it in Project Settings > Processing Issues ... this will make sure events with a required debug symbol missing will be held back until you upload the symbols later.
