### ISSUE TITLE
snapshotStacktrace without automatic crash handling

### ISSUE THREAD

**Issue by ldiqual** [getsentry/sentry-cocoa#227]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? **4.0**
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.9.1**

---
**Issue:**

We use Crashlytics to collect crashes but use Sentry to collect errors that don't lead to a crash (invalid state, error from API, etc). This is why we disable Sentry's automatic crash collection.

However we'd like to add a stack trace to our error events:

```
sentryClient.snapshotStacktrace {
    let event = Event(level: severity)
    event.message = message
    event.extra = cleanedExtras
    
    sentryClient.appendStacktrace(to: event)
    sentryClient.send(event: event, completion: nil)
}
```

However this causes this issue:

```
2017-11-30 17:49:14.752562-0800 App[66086:10305488] Sentry - Error:: KSCrash has not been initialized, call startCrashHandlerWithError
```

**Steps to reproduce:**
- Disable crash collection with Sentry
- Try to capture a stack trace for a regular error event

**Actual result:**
- `KSCrash has not been initialized, call startCrashHandlerWithError`

**Expected result:**
- Stacktrace is captured

**Comment by HazAT** [comment]
Hey,
So I just tried to work around this quickly, sadly KSCrash has no easy way of not starting the crashhandler but use all of the other functionality.

So it's a bigger change which also involves updating KSCrash.
The workaround for you now would be either send the stack trace with 
`Thread.callStackSymbols`
or
 start the crash handler and also send crashes to Sentry (which should work without problems).

**Comment by HazAT** [comment]
I am going to close this for now since we are not gonna implement this in the near future.
I hope you are to work around the problem.
