### ISSUE TITLE
Improve Sauce Labs workflows

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2273]
### Description

I see these 3 workflow fail so so often, usually because of timeouts after like 50 minutes. Restarting almost always works. Can we fix the underlying issue, and if not, decrease the timeout and enable automatic restarts or something? And how useful are these benchmarking tests to begin with?

**Comment by philipphofmann** [comment]
Which workflows exactly are you talking about? The [benchmarking workflows](https://github.com/getsentry/sentry-cocoa/actions/workflows/benchmarking.yml), @kevinrenskers?

**Comment by kevinrenskers** [comment]
Yes

**Comment by philipphofmann** [comment]
We don't see this happening that often anymore. We can always open an issue if this is a problem again.
