### ISSUE TITLE
Add Code docs with jazzy

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2278]
### Description

Use https://github.com/realm/jazzy to create code docs similar to, for example, https://alamofire.github.io/Alamofire/. CI should automatically update these.

**Comment by philipphofmann** [comment]
Maybe consider https://developer.apple.com/documentation/docc instead.

**Comment by philipphofmann** [comment]
Did you try the `xcodebuild docbuild` command, see https://developer.apple.com/documentation/xcode/distributing-documentation-to-external-developers?

**Comment by kevinrenskers** [comment]
That only creates the documentation archive, not the rendered website.

**Comment by philipphofmann** [comment]
Maybe worth checking out @kevinrenskers https://stackoverflow.com/questions/71199393/how-can-i-publish-on-github-using-docc

**Comment by kevinrenskers** [comment]
The problem is that it doesn't seem to work for Obj-C projects.

**Comment by philipphofmann** [comment]
Oh now 🙈

**Comment by philipphofmann** [comment]
> The DocC documentation compiler converts Markdown-based text into rich documentation for Swift and Objective-C projects, and displays it right in the Xcode documentation window. 

https://developer.apple.com/documentation/docc. At least their docs state it should work.

**Comment by kevinrenskers** [comment]
Did you look at https://stackoverflow.com/questions/74263875/using-docc-for-an-objective-c-project, which I posted a while ago?

**Comment by kevinrenskers** [comment]
I'll try it with `xcodebuild` instead with the `--transform-for-static-hosting` flag, see if that makes a difference

**Comment by philipphofmann** [comment]
> https://stackoverflow.com/questions/74263875/using-docc-for-an-objective-c-project

Nope sorry I didn't 😁

**Comment by kevinrenskers** [comment]
It sorta works and I have a PR: https://github.com/getsentry/sentry-cocoa/pull/2445. But my recommendation is to probably use Jazzy after all as DocC really works a lot better with Swift projects.

**Comment by philipphofmann** [comment]
Investigation PR https://github.com/getsentry/sentry-cocoa/pull/2490.

**Comment by philipphofmann** [comment]
Maybe a useful blog post on DocC: https://pspdfkit.com/blog/2024/generating-api-documentation-for-multiple-targets-with-docc/.

**Comment by philipphofmann** [comment]
We haven't tackled this in a long time. We can either open a PR or another issue when we want to tackle this.
