### ISSUE TITLE
Remove PrivateSentrySDKOnly.h from Sentry.h

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2279]
### Description

We should remove PrivateSentrySDKOnly.h from Sentry.h. This way we hide it from customers, and hybrids SDK could import it explicitly.

This need to be sync with hybrids SDK.

**Comment by philipphofmann** [comment]
@brustolin, I think that was fixed with https://github.com/getsentry/sentry-cocoa/pull/2349. Please, reopen otherwise.
