### ISSUE TITLE
Sentry.Event.extra not getting sent

### ISSUE THREAD

**Issue by mxcl** [getsentry/sentry-cocoa#228]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.0
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.9.1**

---

I am specifying extras for my events like so:

```swift
    let event = Sentry.Event(level: .error)
    event.message = (error as? LocalizedError)?.errorDescription ?? "\(error)"
    event.extra = ["file": file, "function": function, "raw-error": "\(error)"]
    Sentry.Client.shared?.send(event: event)
```

But my events do not show these extra data items. The `message` turns up.

**Comment by HazAT** [comment]
Can you make sure, the stuff you pass in the `extra` dict is JSON serializable?
I am not sure if `file` / `function` are JSON serializable also try it with

```
event.extra = ["file": "\(file)", "function": "\(function)", "raw-error": "\(error)"]
```

Let me know if that helps, probably have to update our docs to make this more clear.

**Comment by mxcl** [comment]
These are type `StaticString`, and I verified they are JSONSerializable in a playground just now.

However these extras are getting sent, I was mistaken, sorry. Closing!
