### ISSUE TITLE
EXC_BREAKPOINT [SentryNetworkTrackingIntegration swizzleURLSessionTask] threading violation: expected the main thread

### ISSUE THREAD

**Issue by nicolascabaret** [getsentry/sentry-cocoa#2282]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.27.1

### Steps to Reproduce

No exact pattern to reproduce but it happens while using background thread for networking

### Expected Result

No crash

### Actual Result

<img width="1321" alt="screenshot" src="https://user-images.githubusercontent.com/49147771/195546611-aa51b476-b3e7-4120-9444-9b76e60ba813.png">

**Comment by philipphofmann** [comment]
It could be that `SentryNetworkTrackingIntegration swizzleURLSessionTask` is not responsible for the crash you see. Our SDK swizzles network requests. So basically, we intercept almost all requests you do. Can it be that some of your network request code tries to update some UI on a background thread after it's finished? Could you maybe share the full stacktrace here?

**Comment by nicolascabaret** [comment]
Well after investigations, we noticed the SDK is started twice in a row. It crashes because while the first instance is logging network task, instantiation of the 2nd start call dealloc of the first one on the background queue associated with the url session. And when dealloc `SentryClient`, you also dealloc `SentryUIDeviceWrapper` which call `[UIDevice.currentDevice endGeneratingDeviceOrientationNotifications];`on a background thread

**Comment by nicolascabaret** [comment]
I think multiple starts should not be possible. That would be really helpful to protect the start and even adding some console error and logs

**Comment by brustolin** [comment]
Hey @nicolascabaret, can you explain how the SDK is starting multiple times? Is this intentional? Being done manually? I just want to understand the context.

**Comment by philipphofmann** [comment]
So basically, you are starting and closing the SDK on different threads, @nicolascabaret? Can you give us a repro, please? While this is an edge case, we can fix the problems you pointed out.

**Comment by nicolascabaret** [comment]
Hi guys, sorry for answering late. Here are my answers:
- @brustolin, the SDK is started manually and it was not intentional. By manually, I mean it's started at app launch and also by network events and user inputs (We let the user being able to stop analytics and crash collection). We add some conditions on the event to avoid multiple starts.
- @philipphofmann, exactly. As mentioned, SDK is started on network event which are basically on background threads. When `SentryClient` is deallocated (still on background thread), it seems to call `[UIDevice.currentDevice endGeneratingDeviceOrientationNotifications];` which must be main threaded.
Hope I'm clear enough. Don't hesitate to ask if not

**Comment by philipphofmann** [comment]
Thank you, @nicolascabaret, for the update.

I think the fix should be relatively easy. We need to ensure that the code https://github.com/getsentry/sentry-cocoa/blob/7d3d1a3b950e9ecf05d278fde3b4a4285b5fc8ab/Sources/Sentry/SentryUIDeviceWrapper.m#L33-L41

runs on the main thread. Maybe also be worth checking the other interactions with `UIDevice` in `SentryUIDeviceWrapper`.

**Comment by philipphofmann** [comment]
@kevinrenskers, is this something you could look into ⬆️ ?
