### ISSUE TITLE
Update specs regarding http status code

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2297]
### Description

SentryNetworkTracker saves the http status in the span's `tag` collection. We should update the specs to reflect this.

**Comment by philipphofmann** [comment]
Which specs are you referring to, @brustolin?

**Comment by brustolin** [comment]
Network performance tracker. We need to list the properties we extract from the response, and where to save it.

**Comment by philipphofmann** [comment]
Sorry, I still don't get it. Why do we need to update a spec, if we need to update the `NetworkPerformanceTracker`?

**Comment by brustolin** [comment]
Oh, I understand the miscommunication here.

By specs I mean develop.sentry.io, We need to reflect there the things we're already doing with `NetworkPerformanceTracker`.

**Comment by philipphofmann** [comment]
This issue doesn't belong in this repo. @brustolin will create a new issue on the develop repository.
