### ISSUE TITLE
XCFramework: Missing Bitcode for iOS

### ISSUE THREAD

**Issue by StefanOltmann** [getsentry/sentry-cocoa#2304]
### Platform

iOS

### Installed

Carthage

### Version

7.28.0

### Steps to Reproduce

Replaced Sentry.xcframework in my lib folder with the one provided on the GitHub release page.

Creation of XCArchive fails. That's how I call it using GitHub Actions:
```
      - name: Create XCArchive
        run: |
          xcodebuild \
            -sdk iphoneos \
            -project apple/MyApp.xcodeproj \
            -configuration Release \
            -scheme iOS \
            -derivedDataPath apple/build/iOS \
            -archivePath apple/build/iOS/archive \
            archive
```

### Expected Result

Compile without issue like 7.25.1 did.

### Actual Result

`
ld: '/Users/runner/work/myapp/apple/build/iOS/Build/Intermediates.noindex/ArchiveIntermediates/iOS/BuildProductsPath/Release-iphoneos/Sentry.framework/Sentry' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/runner/work/myapp/apple/build/iOS/Build/Intermediates.noindex/ArchiveIntermediates/iOS/BuildProductsPath/Release-iphoneos/Sentry.framework/Sentry' for architecture arm64
`

**Comment by brustolin** [comment]
Hey @StefanOltmann, thanks for pointing this out, XCode 14 changed the default value for "enable BitCode". We're gonna fix this.

**Comment by StefanOltmann** [comment]
@brustolin Thank you for sorting this out quickly. I was able to update and build with the current library.

Normally I don't care so much if my libraries are a bit older, but you have this nagging 
`We recommend you update your SDK from sentry.cocoa@v7.25.1 to sentry.cocoa@v7.28.0 (All sentry packages should be updated and their versions should match)` hint on the report page and I always want it to go away. I guess that might be your intention. ;)

**Comment by philipphofmann** [comment]
> Normally I don't care so much if my libraries are a bit older, but you have this nagging
We recommend you update your SDK from sentry.cocoa@v7.25.1 to sentry.cocoa@v7.28.0 (All sentry packages should be updated and their versions should match) hint on the report page and I always want it to go away. I guess that might be your intention. ;)

Do you find the hint annoying, @StefanOltmann? Do you think we should change it or keep it as it is?

**Comment by brustolin** [comment]
Hello @StefanOltmann unfortunately we will need to revert this change in future releases. You can follow the reasoning in this PR #2341

**Comment by StefanOltmann** [comment]
> Do you find the hint annoying, @StefanOltmann? Do you think we should change it or keep it as it is?

Keep it. Otherwise I would forget to update. ;)

**Comment by StefanOltmann** [comment]
> Hello @StefanOltmann unfortunately we will need to revert this change in future releases. You can follow the reasoning in this PR #2341

Ok, thank you for the hint. That's okay with me, because I have bitcode enabled because previously Apple wanted me to. If they accept my app submission without bitcode in the future this is fine. :)
