### ISSUE TITLE
Crash on launch: NSRangeException -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array

### ISSUE THREAD

**Issue by samsonjs** [getsentry/sentry-cocoa#231]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Version 4
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.10.0** (Looking at code the bug exists in 3.11.0 too)

---
I have following issue:

Some of our users are getting a crash on launch in `-[SentryKSCrashReportConverter enhanceValueFromNotableAddresses:]`. This method doesn't check the array bounds first.

**Steps to reproduce:**
- I'm not certain, only seen reported in the wild

**Actual result:**
- Sentry crashes on launch

**Expected result:**
- Sentry does not crash

[7487D0F75E5042C196ABDA7BCC480B54-symbolicated.crash.txt](https://github.com/getsentry/sentry-cocoa/files/1595478/7487D0F75E5042C196ABDA7BCC480B54-symbolicated.crash.txt)

**Comment by HazAT** [comment]
Hey, thank you for reporting this!
I am currently looking into this.

**Comment by samsonjs** [comment]
Thank you!
