### ISSUE TITLE
stitchAsyncCode crashes at launch for macOS app on Intel machines

### ISSUE THREAD

**Issue by sindresorhus** [getsentry/sentry-cocoa#2318]
### Platform

macOS

### Installed

Swift Package Manager

### Version

7.28.0

### Steps to Reproduce

Compile my app on macOS 13 RC and Xcode 14.1 RC with Sentry, on an MacBook M1 Pro (Apple silicon).

I know the fault is Sentry as I sent a build with and without Sentry to a user that had the crash and the crash only occurred when Sentry was present: https://github.com/sindresorhus/Pasteboard-Viewer/issues/16

Here's the Sentry config I used: https://github.com/sindresorhus/Pasteboard-Viewer/blob/6757dff9fca8087c8b2318abad1e56418dbd9212/Pasteboard%20Viewer/Utilities.swift#L63-L67

### Expected Result

I expected my app to launch successfully on all machines.

### Actual Result

I runs successfully on Apple silicon machines, but crashes at launch on all Intel-based machines. Both macOS 12.6 and macOS 13.

Stack trace: https://sentry.io/organizations/sindresorhus/issues/3495177992/events/1c14b1a796e94ffd894185759d6ecafa/

**Comment by sindresorhus** [comment]
I have tracked down the cause to be `.stitchAsyncCode = true`. Without it, it does not crash on Intel machines.

**Comment by philipphofmann** [comment]
Thanks, @sindresorhus, for reporting this. `stickAsyncCode` is still experimental, and he might work on it in our next quarter, which lasts from November to January, to make it GA. This is related to https://github.com/getsentry/sentry-cocoa/issues/1786.

**Comment by philipphofmann** [comment]
Once we tackle https://github.com/getsentry/sentry-cocoa/issues/1786, we can revisit if it also fixes this bug.

**Comment by sindresorhus** [comment]
Please keep it open

**Comment by philipphofmann** [comment]
Could be fixed by using another approach for stitch async code as pointed out in https://github.com/getsentry/sentry-cocoa/pull/2983.

**Comment by brustolin** [comment]
We removed this feature as explained in [here](https://github.com/getsentry/sentry-cocoa/issues/1786#issuecomment-1542095892).
