### ISSUE TITLE
AppHangs events should set stacktrace.snapshot true

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2323]
### Description

The code for creating the event for an app hang should set `snapshot=true`

https://github.com/getsentry/sentry-cocoa/blob/64225be5808d92970f1efab0da188427fed632f8/Sources/Sentry/SentryANRTrackingIntegration.m#L56-L74

`snapshot=true` means it's a synthetic exception, meaning the current state of the thread rather than the stack trace of a real exception; this changes the grouping behavior.

**Comment by brustolin** [comment]
Solved by #2441
