### ISSUE TITLE
Could not decode report: Invalid character

### ISSUE THREAD

**Issue by simonas-mixedinkey** [getsentry/sentry-cocoa#2327]
### Platform

macOS

### Installed

Carthage

### Version

7.28.0

### Steps to Reproduce

Without the debugger attached, force a crash using CFRelease(NULL);

### Expected Result

The crash report is submitted to Sentry

### Actual Result

Crash is saved in ~/Library/Caches/SentryCrash
On next launch error is logged in debug area (log below)

p.s. I see that other crashes are successfully reported. But this exact one - is not.

Sentry - debug:: SDK initialized! Version: 7.28.0
Sentry - debug:: Reading from session: Sentry - debug:: Writing session: /Users/username/Library/Caches/io.sentry/0696845b14b4b76675d37667c428663cfe8eba92/session.crashed
Sentry - debug:: Deleting session: /Users/username/Library/Caches/io.sentry/0696845b14b4b76675d37667c428663cfe8eba92/session.current
ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Invalid character
ERROR: SentryCrashC.c (304): char *sentrycrash_readReport(int64_t): Failed to fixup report ID 91000000
Sentry - debug:: Sent 0 crash report(s)

**Comment by simonas-mixedinkey** [comment]
Investigated json a bit.
I think this is the value that is not acceptable:
```
"stack@0x31027f888": {
    "address": -3,
    "type": "objc_object",
    "class": "NSDate",
    "value": nan
},
```

**Comment by philipphofmann** [comment]
I wonder how our SDK ends up writing `"address": -3`. I just tried `CFRelease(NULL)`, and the SDK reported the error successfully to Sentry. On which device did you try this, @simonas-mixedinkey?

**Comment by simonas-mixedinkey** [comment]
I'm using MacBook Pro (2021) wtih macOS Monterey (12.4)

I tried calling `CFRelease(NULL)` in other places of the project and the crash report seems valid.
So it's more of an edge case. I'm still not sure what causes it, but it's 100% reproducable when called in specific project place.

Having the route cause solved would be perfect, but not having invalid data written into json report or at least just skipping the invalid part instead of whole crash report sounds like acceptable.

Could that be an easy fix? I'm just thinking how many crashes are skipped because of this bug.

**Comment by brustolin** [comment]
> but it's 100% reproducable when called in specific project place

Can you help us reproduce this? What specific part of the project are you calling this? 
Is from a button click? A life-cycle method? Is this the main thread?
Can you reproduce this in a new clean project?

**Comment by simonas-mixedinkey** [comment]
@brustolin I created a new clean project that has only couple of empty windows and two buttons

I removed custom dns from `SentrySDK.startWithConfigureOptions` method, so it needs to be filled first

Click "Button" to open sheet and then click "Crash" button by holding down cmd and option key at the same time : )

Here is the project:
https://www.dropbox.com/sh/1sbjjgk3peyr7r8/AAAYvG1EKelmBSgSlFvsj7Uma?dl=0

Let me know how that goes : )

**Comment by brustolin** [comment]
Thank you very much. I will try this and get back to you asap.

**Comment by simonas-mixedinkey** [comment]
Tested 7.30.1 and this is fixed 🥳 Thank you : )

**Comment by philipphofmann** [comment]
Thanks for the great news @simonas-mixedinkey 😀
