### ISSUE TITLE
I don't see KSCrash headers inside Sentry .framework starting from 3.8.4 version

### ISSUE THREAD

**Issue by AlexanderKaraberov** [getsentry/sentry-cocoa#233]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.0.3
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.8.4 - 3.11.1**

---
I have following issue:

I noticed that when I use `carthage update` or simply download sentry from the release page there is no KSCrash headers inside and the actual size is much smaller: 14.3 vs 9 MBs. How should I include KSCrash? I'm sorry if there are new steps to install Sentry since 3.8.4. In this case could you please point me to the description of those?

**Steps to reproduce:**
- Use `carthage update` to install Sentry

**Actual result:**
- Observe there is no KSCrash bundled in the .framework

**Comment by HazAT** [comment]
OK, so we do not expose KSCrash on purpose since we had issues with duplicate import headers.
Is there a reason why you want to have them exposed?

The app should still work just fine.

**Comment by AlexanderKaraberov** [comment]
@HazAT No there is no actual reason. I was just concerned that KSCrash isn't there and crash reporting will not work. I didn't know that you are not exposing it anymore. Thanks for the clarification!

**Comment by HazAT** [comment]
If you run your app in debug, and see something like this in your logs you should be safe :) 
```
2018-01-08 14:52:41.257164+0100 sentry-ios-carthage[44493:18330360] Sentry Started -- Version: 3.11.1
    ************************ Crash Handler Notice ************************
    *     App is running in a debugger. Masking out unsafe monitors.     *
    * This means that most crashes WILL NOT BE RECORDED while debugging! *
    **********************************************************************
INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
```
