### ISSUE TITLE
Bitcode error in 7.29.0

### ISSUE THREAD

**Issue by cmuphobk** [getsentry/sentry-cocoa#2332]
### Platform

iOS

### Installed

Manually

### Version

7.29.0

### Steps to Reproduce

1. Build project with Sentry.xcframework as vendored_framework in one of local DevPod in our app
2. On bitcode recompile step error produced

### Expected Result

Archive succeed

### Actual Result

Archive failed
<img width="685" alt="image" src="https://user-images.githubusercontent.com/12449923/198071944-8c1b9179-0f39-4528-8e0d-c09f8b6f747d.png">

**Comment by philipphofmann** [comment]
@cmuphobk, did it still work for you on 7.28.0 or prior?

**Comment by philipphofmann** [comment]
You also pointed out that you installed it manually, but then you wrote about a _local DevPod in our app_. Do you use CocoaPods, then? Could you maybe share a small sample project with us to reproduce the issue?

**Comment by brustolin** [comment]
We believe this issue will be fixed with the PR #2341 which will be available in the next release.
If the error persist, you can reopen it.
