### ISSUE TITLE
React Native app with Sentry freezes on the app launch with "Debug executable" turned off

### ISSUE THREAD

**Issue by morishin** [getsentry/sentry-cocoa#234]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.0
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.11.1**

---
I have following issue:

https://forum.sentry.io/t/react-native-rootview-blank-on-boot/3059

When using Sentry-Cocoa 3.11.1 with React Native 0.52.0 and `Debug executable` of build scheme is turned off, it breaks the app. It shows a blank screen and freezes on the app launch.

**Steps to reproduce:**
- Run an app using Sentry-Cocoa and React Native with “Debug executable” turned off

**Actual result:**
- It shows a blank screen and freezes on the app launch.

**Expected result:**
- It does not freeze.

**Comment by HazAT** [comment]
Isn't there any debug output in Xcode at all?
Can you enable exception breakpoints and see if it gets stuck there?

**Comment by morishin** [comment]
The app did not pause though I enabled exception breakpoint.

- When `Debug executable` turned on, the app does not freeze and shows the following logs.
   ```
   2018-01-30 19:05:27.584427+0900 MyAppName[99249:23632155] Sentry Started -- Version: 3.11.1
    ************************ Crash Handler Notice ************************
    *     App is running in a debugger. Masking out unsafe monitors.     *
    * This means that most crashes WILL NOT BE RECORDED while debugging! *
    **********************************************************************
   INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
   ```


- When `Debug executable` turned off, the app freezes and shows the only following logs.
   ```
   2018-01-30 19:05:27.584427+0900 MyAppName[99249:23632155] Sentry Started --
   Version:3.11.1
   ```

**Comment by HazAT** [comment]
@morishin Ok, I am a bit clueless here.
If you do not call `install()` the app does not freeze?

**Comment by morishin** [comment]
Yes, the app does not freeze if I do not call `install()`, or set `disableNativeIntegration: true`.

```js
Sentry.config('<URL>', {
  disableNativeIntegration: true
}).install();
```

**Comment by HazAT** [comment]
@morishin 
Do you use any other plugin/pod that could interfere with Sentry (that installs another crash handler or something?)

**Comment by morishin** [comment]
Here is my Podfile. I think I do not use any other crash handler 😖 

```ruby
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs'

target 'MyAppName' do
  use_frameworks!

  pod 'Sentry', '~> 3.10.0'
  pod 'Sentry/KSCrash', '~> 3.10.0'
  pod 'KeychainAccess', '~> 3.1.0'
end
```

**Comment by HazAT** [comment]
Hey,
I've just tried it with a clean setup of react-native

```
react-native init AwesomeProject
cd AwesomeProject
yarn add react-native-sentry
react-native link react-native-sentry
```

Build and run release with `Debug executable` turned off and it did not freeze.
I need a reproducible case otherwise there is nothing I can do.

**Comment by morishin** [comment]
hmm 🤔 
It seems that there is a problem other than react-native-sentry.
Thank you for your investigation!
