### ISSUE TITLE
Crash `SentryProfiler must be initialized on the main thread`

### ISSUE THREAD

**Issue by RuiAAPeres** [getsentry/sentry-cocoa#2342]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.29.0

### Steps to Reproduce

I set up the SDK like this:

```
    SentrySDK.start { options in
      options.dsn = ...
      options.enableAppHangTracking = true

#if DEBUG
      options.debug = true
      options.tracesSampleRate = 1.0
      options.profilesSampleRate = 1.0
      options.environment = "development"
#else
      options.debug = false
      options.tracesSampleRate = 0.1
      options.profilesSampleRate = 0.1
      options.environment = "production"
#endif
    }
```

At some point later on, from a non-main thread I call:

```
      let transaction = SentrySDK.startTransaction(
        name: "Read_From_HealthKit",
        operation: resource.logDescription
      )
```

### Expected Result

That calling that wouldn't crash the app. 

### Actual Result

The app crashes with an error on the logs:

`Sentry - error:: SentryProfiler must be initialized on the main thread`

![image](https://user-images.githubusercontent.com/949286/199049330-66a84b5d-5683-49aa-adcb-b259fb042ce9.png)

**Comment by armcknight** [comment]
Thanks @RuiAAPeres for bringing this to our attention. We're aiming to push out a new release tomorrow, stay tuned...

**Comment by RuiAAPeres** [comment]
@armcknight I can test this out against main.
