### ISSUE TITLE
Static analyzer identified conditions where nil can be passed to method expecting non-nil parameter value

### ISSUE THREAD

**Issue by patrickhartling** [getsentry/sentry-cocoa#235]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

Version of sentry-cocoa:
**3.11.1** (commit 804f3cbf7383fbc2e9361ac92c83e77818159239)

---
I have following issue:

When running the static analyzer from Xcode 9.2 against commit 804f3cbf7383fbc2e9361ac92c83e77818159239, the following problem was identified:

```
Sources/Sentry/SentryJavaScriptBridgeHelper.m:141:47: warning: nil passed to a callee that requires a non-null 1st parameter
                                              [self.class parseRavenFrames:jsStacktrace]];
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
**Steps to reproduce:**
- Run the static analyzer from Xcode 9.2 on the code

**Actual result:**
- The static analyzer identifies a scenario where `nil` gets passed to the `‑parseRavenFrames:` method.

**Expected result:**
- Ideally, there would be no issues flagged by the static analyzer

**Comment by HazAT** [comment]
Feel free to submit a PR fixing this :)
Otherwise please be patient, when there is time I will fix this.
