### ISSUE TITLE
Fix `relative_end_ns` in profile payloads

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2352]
### Description

We still have an issue trying to calculate start/end of each profiled transaction relative to the start of the profile. We assume `SentryTransaction.timestamp` to be the end timestamp, but sometimes when we compare it to the start timestamp we recorded for the profiler, it is actually _before_ it if the transaction is short enough, so we wind up with a situation like this:

```
v transaction start     v profile start
|--|--------------------|---|
   ^ transaction end        ^profile end
```

This winds up in a situation where `relative_end_ns` is set to 0 for transactions linked to profiles, because we perform a comparison that returns a negative time interval and then convert it to an unsigned integer. The 0 value then fails validation in the backend.

At least some of this is due to NSDate vs absolute time, see https://github.com/getsentry/sentry-cocoa/issues/2155. Other things could be the fact that we have to wait for `@synchronize`/locks in SentryProfiler, so we could try to set start timestamps as early as possible after transaction/tracer start and share that with the profiler.

**Comment by armcknight** [comment]
This may actually be caused by a different underlying issue that will adversely affect customers, if we have a very short transaction that finishes before the profiler can get started, then nothing that happens in that transaction will be represented in the profile.

**Comment by philipphofmann** [comment]
If the transaction is very short, maybe it's acceptable not to have a profile.

**Comment by armcknight** [comment]
Another strategy to consider, from @phacops:
> would a better workaround be to set it to whatever is the last timestamp for a sample?
