### ISSUE TITLE
Sentry-cocoa parsing the DSN.url in a different way compared to react-native-sentry

### ISSUE THREAD

**Issue by sahil290791** [getsentry/sentry-cocoa#236]
_Platform:_
- [x ]  iOS

_Swift:_
- [ x]  No

_sentry-cocoa installed with:_
[react-native-sentry](https://github.com/getsentry/react-native-sentry)

Version of sentry-cocoa:
**3.11.1**

---
I have following issue:
I am using react-native-sentry which internally uses sentry-cocoa. Our sentry sits behind a vpn so production apps cannot directly hit sentry for which we use nginx level routing, and hit a public endpoint: `https://mydomain.com/submit_errors`.

Sentry install happens this way in js:
```js
const DSN = 'xxx:yyy';

// normally we would directly give the sentry host url, but i give this:
const hostURL = 'mydomain.com/submit_errors';
const projectID = 1;

Sentry.config(`https://${DSN}@${hostURL}/${projectID}`, sentryOptions).install();
```

Now when this install happens in react native sentry android and even `raven-js` plugin its able to parse the url and make this out of it:

```js
https://mydomain.com/submit_errors/api/1/store/
```

Android and other sentry plugins take the part after last `/` as the `projectID` which is **1** from my above example, but in **sentry-cocoa** alone it considers the immediate next string as **projectID**  `mydomain.com/submit_errors`. So the **projectID** becomes `submit_errors`.

and finally the **apiURL** looks like this:
```
https://myDomain.com/api/submit_errors/store/
```
instead of 

```
https://myDomain.com/submit_errors/api/1/store/
```

Can you please do the fix and make it like all other plugins and consider the last part of the URL as projectID?

**Comment by sahil290791** [comment]
Thanks @HazAT for fixing this so quickly. :+1:  I just have one more question.

As I use react-native-sentry, do I need to open an issue over there so that **react-native-sentry** references the latest sentry-cocoa?

**Comment by HazAT** [comment]
I will also release a update for react-native-sentry :)

**Comment by sahil290791** [comment]
Thanks again @HazAT :smiley:
