### ISSUE TITLE
Why don't OOM reports include breadcrumbs

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2377]
### Problem Statement

When I get an OOM I don't see the breadcrumbs that happened before the crash. Instead I have to upload a log file to get the context of what happened.

**Comment by brustolin** [comment]
Hello @Eric.
#2347 Will solve this issue.

**Comment by philipphofmann** [comment]
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/1759.
