### ISSUE TITLE
Embedding in SDK

### ISSUE THREAD

**Issue by benjamingr** [getsentry/sentry-cocoa#238]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

---

I have following issue: I'm writing an SDK and would like to use sentry-cocoa - as an SDK writer I can't really have third party dependencies and I'd rather keep the size as small as possible.

Is there a way to embed sentry neatly in an SDK? Alternatively, is there a documented REST API for reporting errors?

Thanks!

**Comment by HazAT** [comment]
So there is a whole API documentation for Sentry, you can find it here:
https://docs.sentry.io/api/

But it should work without a problem if you use the Static Lib target we provide in our Xcode Project.
Just drag in our Project from the repo in your workspace/project into your SDK, it should work just fine when you are using the static lib target.

Keep in mind if you do that, you will not get KSCrash by default, there is a KSCrash subfolder which contains the Xcode Project including KSCrash. Note that KSCrash installs a crash handler which could interfere with other crash handlers installed by other SDKs.

So I never tried it myself but it should work without a problem.

Let me know if you need anything else.

**Comment by benjamingr** [comment]
@HazAT wouldn't that be problematic if the users of my SDK also use sentry and they use a different version?

**Comment by benjamingr** [comment]
Ping @HazAT

**Comment by HazAT** [comment]
Sorry, missed it.

So another quick question before answering yours, do you want to only send messages/custom events to your Sentry installation/account with your DSN?
OR
Do you want to send errors to the users Sentry if they are using Sentry in their app?

**Comment by benjamingr** [comment]
> do you want to only send messages/custom events to your Sentry installation/account with your DSN?

That one, that's what we do in Android and it works well, I want to explicitly catch and handle errors originating in my SDK

**Comment by HazAT** [comment]
OK, so this should work without interfering with users also using Sentry.
I would do something like:
```
SentryClient *client = [[SentryClient alloc] initWithDsn:@"__DSN__" didFailWithError:&error];
```
**But do not call:** 
```
[client startCrashHandlerWithError:&error]
```

Just use your instance without starting the crash handler.
Also, do not set the sharedInstance `SentryClient.sharedClient = client;` I would pass your instance of the client wherever you need it just to make sure.

**Comment by benjamingr** [comment]
@HazAT as an SDK, from what I understand, I can't really have dependencies since objective C class names are global - if someone else uses sentry cocoa and with a different version I'm not sure how it will break - I can clone the SDK and rename it but I was wondering if there is something simpler or if you have already considered this case.

**Comment by HazAT** [comment]
tbh we haven't considered this a common use case, that's why am struggling a bit to give you useful advice here because we never actually tried it.
Not really sure but I guess renaming it is your only choice ...

Also, I am not sure what kind of SDK you are building and if it's open source or not 
but I could imagine if users of your SDK suddenly notice that you make http requests to Sentry and your SDK is only doing "image processing" that could upset people.
Ultimately it's your decision just my 2 cents.

**Comment by benjamingr** [comment]
> but I could imagine if users of your SDK suddenly notice that you make http requests to Sentry and your SDK is only doing "image processing" that could upset people.

Our SDK does p2p video delivery for HLS video, we use sentry on all our platforms (Android, iOS, Web) and we're very upfront about the type of calls we make to our users and they have an opt-out. The SDK is not open source (although it's pretty tiny). I do appreciate you raising up that concern and I wouldn't want to do anything to surprise our users.

I guess renaming is pretty much my only choice - is there a REST API for error reporting in sentry I can use? That might be simpler for my use case

**Comment by benjamingr** [comment]
Ping? :)

**Comment by HazAT** [comment]
There are our API docs
https://docs.sentry.io/api/

Also you can look at the implementation of this SDK.
