### ISSUE TITLE
SentryKSCrashReportConverter Crashing

### ISSUE THREAD

**Issue by MaximusMcCann** [getsentry/sentry-cocoa#239]
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> 4

_sentry-cocoa installed with:_
- [x] CocoaPods

Version of sentry-cocoa:
  - Sentry/Core (3.12.2)
  - Sentry/KSCrash (3.12.2):
    - KSCrash/Core (~> 1.15.12)

---
I have following issue:
Fabric is reporting a decent number of crashes (over the past ~week).  This appears to be on app load, as none of our logging comes back for those crash instances in Fabric.
```
SentryKSCrashReportConverter.m line 208
-[SentryKSCrashReportConverter threadAtIndex:stripCrashedStacktrace:]
```

![image](https://user-images.githubusercontent.com/1643285/38052758-e58fad6a-3297-11e8-8e81-ab799c04c1b0.png)

**Comment by HazAT** [comment]
Hey, so this should be fixed in `3.12.3`
Sorry for this stupid bug.
