### ISSUE TITLE
 sessions sent without an environment when environment option is not set

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry-cocoa#2411]
### Description

If the environment is not set for the SDK errors will default to production. However, sessions are sent without an environment. 

Expected outcome - sessions would be sent with an environment
Actual outcome: sessions are sent without an environment set

Steps To Reproduce

1. set the environment and release options
2. Send an error event and session
3. Observe that session and error event with the correct environment
4. repeat without setting the environment option
5. Observe the error event with an environment of production
6. Observe the session with no environment

**Comment by philipphofmann** [comment]
We set the default environment for events here
https://github.com/getsentry/sentry-cocoa/blob/48c72110de904b91a793fea0d9a3e9117df4d756/Sources/Sentry/SentryClient.m#L572-L575

but not when starting the session

https://github.com/getsentry/sentry-cocoa/blob/48c72110de904b91a793fea0d9a3e9117df4d756/Sources/Sentry/SentryHub.m#L96-L99

Thanks for reporting this, @kerenkhatiwada.
