### ISSUE TITLE
Rename APM tracking feature flags to tracing

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2417]
### Description

The SDK contains a few performance feature flags containing tracking in their name. Instead, these should be renamed to tracing as these features trace certain things. Therefore, we mark the following features as deprecated and add new features with tracing in their name:

- enableAutoPerformanceTracking becomes enableAutoPerformanceTracing
- enableUIViewControllerTracking becomes enableUIViewControllerTracing
- enablePreWarmedAppStartTracking becomes enablePreWarmedAppStartTracing
- enableFileIOTracking becomes enableFileIOTracing
- enableCoreDataTracking becomes enableCoreDataTracing

Other features not related to performance must keep their name, such as enableAutoSessionTracking, enableOutOfMemoryTracking, enableNetworkTracking (both performance and breadcrumbs), enableAppHangTracking, enableAutoBreadcrumbTracking.

Please also update the docs.

**Comment by philipphofmann** [comment]
Ensure the properties have one source of truth.

**Comment by brustolin** [comment]
What is the rule to define whether use should use tracing or tracking?

**Comment by kevinrenskers** [comment]
What's even the difference between tracking and tracing something

**Comment by kevinrenskers** [comment]
Docs PR: https://github.com/getsentry/sentry-docs/pull/5859
