### ISSUE TITLE
Logs printed regardless of the logLevel

### ISSUE THREAD

**Issue by pepibumur** [getsentry/sentry-cocoa#242]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.0
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

Version of sentry-cocoa:
**3.12.4**

---
I have following issue:

Regardless of the logLevel set to the client, it prints stuff on the console. I'm using it from a command line tool app and I'd like to hide any messages from third party libraries. This is an example of what I get when I execute my tool with Sentry.

**Steps to reproduce:**
- Step: Setup SDK
```swift
Client.logLevel = .none
client = try Client(dsn: "xxx")
```
- Run the app.

**Actual result:**
<img width="738" alt="screen shot 2018-04-23 at 15 51 26" src="https://user-images.githubusercontent.com/663605/39131017-c2091242-470e-11e8-8137-18f679c5173e.png">

**Expected result:**
- Result: No outputs

**Comment by HazAT** [comment]
I will fix this, thanks for reporting.

**Comment by pepibumur** [comment]
Thanks @HazAT. There's an intruder `NSLog` in the constructor 😜

**Comment by HazAT** [comment]
Yeah, this is an easy fix.
The bigger problem is the KSCrash output :/

**Comment by pepibumur** [comment]
Doesn't it support defining the logging level?

**Comment by pepibumur** [comment]
Ouch, what exactly is KSCrash used for? I'd love to use Sentry on the command line tool that I'm building but printing does logs on the console is a bit weird if you are using the tool.

**Comment by HazAT** [comment]
Totally get that, KSCrash is used for catching all possible unhandled errors/crashes.
The SDK is basically an API to Sentry.

**Comment by HazAT** [comment]
@pepibumur I've submitted a PR to KSCrash to raise the bar there.
https://github.com/kstenerud/KSCrash/pull/282
Fingers crossed that this will be merged.

**Comment by HazAT** [comment]
ref: https://github.com/getsentry/sentry-cocoa/pull/243
