### ISSUE TITLE
Change "Yoda style" conditions

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2429]
### Description

Something like `if (nil == client)` is completely backwards to me. Like saying "if yellow equals jacket color", you'd never say that in real life either.

Both SwiftLint and SwiftFormat have rules for this: https://realm.github.io/SwiftLint/yoda_condition.html and https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#yodaConditions. Not sure if there is a rule for our formatter? The one in SwiftFormat is enabled by default by the way, which seems completely sensible to me.

What do you guys think?

**Comment by brustolin** [comment]
I also don't like this "Yoda style" (loved the name). 
I don't think is worth to go changing this everywhere, but if this happens in some code you're working on is fine to change.

**Comment by kevinrenskers** [comment]
Indeed, change as you come across it, or have the formatted do it if possible. But I wouldn't advocate doing this everywhere at once by hand 😀

**Comment by kevinrenskers** [comment]
Sadly there is no rule for this in https://clang.llvm.org/docs/ClangFormatStyleOptions.html. But I've added it for SwiftLint. Now that we're probably going to add more Swift code, we can at least automate it there.

**Comment by kevinrenskers** [comment]
Let's close this. There is nothing to automate here sadly, so we'll just do it by hand if we come across Yoda conditions in files we're working on.
