### ISSUE TITLE
Fix flaky test: `SentrySpanTests.testAddAndRemoveData()`

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2437]
### GitHub action Run Link

https://github.com/getsentry/sentry-cocoa/actions/runs/3530734813/jobs/5923080490

### Disabling PR

https://github.com/getsentry/sentry-cocoa/pull/2436

**Comment by brustolin** [comment]
This test was not disabled, it must be working.

Let me know otherwise.
