### ISSUE TITLE
Issues are being sent to Sentry even in Debug mode

### ISSUE THREAD

**Issue by bryanjclark** [getsentry/sentry-cocoa#245]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes, 4.1
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.12.4**

---
I have following issue:

In debug mode, `sentry-cocoa` is still reporting events to Sentry, even though the console printouts report otherwise:

```
2018-05-09 16:00:08.755-0700  /Users/bryanjclark/khan/mobile/ios/Model/AnalyticsReporter.swift:62 NOT sending event in debug mode (event would have been: /*Khan Academy event here*/))
```

**Steps to reproduce:**
1. Follow instructions from Sentry for setting up event-reporting through Sentry’s cocoa client.

**Actual result:**
- In debug mode, our events are showing up in Sentry’s webapp!

**Expected result:**
- Events should not be sent, since we’re in debug mode and the console says they’re not going to get sent!

**Comment by HazAT** [comment]
So we are always sending the events and we do not say in the logs that we don't.
The only thing we say is: if a debugger is attached that Xcode itself handles the crash and we can't.
But if no debugger is attached we still send it no matter if it's a DEBUG or RELEASE build.
Hope that clear things up.

**Comment by bryanjclark** [comment]
Thanks @HazAT! I made a mistake here - that “not sending in debug mode” bit is actually from our own code. Sorry for the confusion! Cheers.
