### ISSUE TITLE
Set Options after start

### ISSUE THREAD

**Issue by msnazarow** [getsentry/sentry-cocoa#2454]
### Problem Statement

I want to start catching events when app is launching, but after that i what to reconfigure SentryOptions
For example, set new beforeBreadcrumb callback

Is there a way to do it? And if not, what is the best solution? 

The reason to reconfigure is that i have my sentry configuration remotely and get it only after user has logged in

**Comment by brustolin** [comment]
The easiest solution right now is to stop Sentry and start it again with different options.

```Swift
SentrySDK.close();
SentrySDK.startWithConfigureOptions(...);
```

This will guarantee that every option is updated for every integration.

Other types of hack may have undefined behaviour.

**Comment by philipphofmann** [comment]
> The reason to reconfigure is that i have my sentry configuration remotely and get it only after user has logged in

Can you elaborate on what you need to reconfigure, @msnazarow? I would be interested in your use case.

**Comment by msnazarow** [comment]
As i said, Mostly i want to reconfigure beforeBreadcrumb callback, cause i filter breadcrumbs with my app-configuration file getting after user login

@brustolin Do i have to call SentrySDK.close(); ? I thought calling SentrySDK.startWithConfigureOptions(...) automatically close previous session and starts new one

**Comment by brustolin** [comment]
Yes, you need to call close before.
The SDK don't do this automatically, maybe is something we should think about it.

If its only `beforeBreadcrumb` you need to change, you can keep a reference from the `option` used to start the SDK, and then change it.

But I wouldn't go that far. All the change logic can be inside your callback code, no need to reset the SentrySDK.

**Comment by msnazarow** [comment]
Interesting. When i trying to change "enableSwizzling" i didn't succeed(

**Comment by philipphofmann** [comment]
> But I wouldn't go that far. All the change logic can be inside your callback code, no need to reset the SentrySDK.

Yes, the `beforeBreadcrumb` can point to whatever you want. Instead of restarting the SDK, I would do something like

```Swift
options.beforeBreadcrumb = { crumb in
    mybeforeBreadcrumb(crumb)
}

func mybeforeBreadcrumb(crumb: Breadcrumb) {
    // Do whatever you want. Just make sure this function call is fast.
}
```

**Comment by philipphofmann** [comment]
Your question should be answered, @msnazarow. If not, please clarify and reopen this issue.
