### ISSUE TITLE
AppStateManager doesn't unsubscribe correctly

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2455]
### Platform

iOS

### Installed

Manually

### Version

7.31.2

### Steps to Reproduce

1. Call SentrySDK.start two times
2. Call SentrySDK.close

### Expected Result

SentryAppStateManager should unsubscribe from notifications here
https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryAppStateManager.m#L95-L98

### Actual Result

SentryAppStateManager doesn't unsubscribe from notifications cause startCount is bigger than 0 https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryAppStateManager.m#L95

**Comment by philipphofmann** [comment]
@kevinrenskers, could you look into this? Should be an easy fix.

**Comment by kevinrenskers** [comment]
So calling close should always unsubscribe even though you started the SDK multiple times? Starting the SDK twice doesn't mean you need to call close twice?

**Comment by philipphofmann** [comment]
> So calling close should always unsubscribe even though you started the SDK multiple times? Starting the SDK twice doesn't mean you need to call close twice?

That's what I would expect. You not? We can also discuss this quickly in our sync today before you get started.

**Comment by kevinrenskers** [comment]
I guess that makes sense, it's not like you're running 2 separate instances when you call start. But I thought we had code in place that prevents you from calling start multiple times? To me that sounds like the root of the problem, and this ticket is about fixing the symptoms.

What's the use of calling start multiple times?
