### ISSUE TITLE
SDK reports OOM when crashing after calling close

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2457]
### Platform

iOS

### Installed

Manually

### Version

7.31.2

### Steps to Reproduce

1. Open iOS-Swift sample app
2. Call `SentrySDK.close`
3. Cause a crash by clicking the crash button

### Expected Result

No OOM in Sentry.

The OutOfMemoryTracker correctly calls stop on the `AppStateManager`
https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryOutOfMemoryTracker.m#L101

but the `AppStateManager.stop` doesn't modify the app state
https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryAppStateManager.m#L87-L118

Then the OOMLogic things the app didn't terminate properly cause wasTerminated is not set https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryOutOfMemoryLogic.m#L77-L80

We could solve this by adding an extra property to the AppState called `wasSDKRunning`, and only report OOMs if this property is `true`.

### Actual Result

The SDK reports an [OOM](
https://sentry.io/organizations/sentry-sdks/issues/2291658301/events/072af7d2c41d44cf8b9fc65e4bdbea26/?project=5428557) to Sentry.

**Comment by kevinrenskers** [comment]
I'm happy to pick this up, goes perfectly with #2460.
