### ISSUE TITLE
Enable performance by default

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2464]
### Description

Set `tracesSampleRate` to 1.0 and maybe add another flag called `enablePerformance` for controlling if performance is on or off. 

Still blocked by final decision in https://github.com/getsentry/develop/issues/769.

**Comment by kevinrenskers** [comment]
How would that new flag be different from the existing `enableAutoPerformanceTracing`? This sounds pretty confusing to me.

**Comment by philipphofmann** [comment]
`enablePerformance` impacts also manual transactions, `enableAutoPerformanceTracing` only auto-generated transactions by the SDK.

**Comment by kevinrenskers** [comment]
Well it's still starting to feel like we really have a bunch of options and it's not getting any clearer what all of them mean 😅

If we don't need to add yet another option then I would really not do it. Like, what does it mean if `tracesSampleRate` is 1, but `enablePerformance` is `false`? Or the other way around? Let's reduce the options where possible.

**Comment by brustolin** [comment]
Im not sure about the `enablePerformance` flag. Setting `tracesSampleRate` to 0 again do the trick

**Comment by philipphofmann** [comment]
We don't want this. People should copy `tracesSampleRate = 1.0` from the code snippet from the docs, see https://github.com/getsentry/develop/issues/769#issuecomment-1332400662
