### ISSUE TITLE
Remove viewAppearing span for UIViewController APM

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2510]
### Description

We once added a `viewAppearing` span to auto-generated transactions for UIViewControllers. As this method doesn't exist for UIViewControllers, and we only added it because the transaction detail view in Sentry displayed missing instrumentation, we should remove it as it's confusing to users. We should fix the missing instrumentation problem in Sentry and not create a span in the SDK.

Please update the screenshots in the [docs](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#uiviewcontroller-tracking).

**Comment by kevinrenskers** [comment]
> Please update the screenshots in the docs.

How was this screenshot created? When I open the sample app and navigate to the Lorum Ipsum page for example, where in Sentry can I find that?

**Comment by brustolin** [comment]
>How was this screenshot created? When I open the sample app and navigate to the Lorum Ipsum page for example, where in Sentry can I find that?

You take a screenshot of the transaction in the `Performance` page

**Comment by kevinrenskers** [comment]
Basically all the traces that I can find have "Missing instrumentation" in there somewhere which doesn't look very good in screenshots. 

For example:

![Screenshot 2022-12-12 at 14 40 02](https://user-images.githubusercontent.com/229384/207059098-afa6dedb-735d-4b55-8632-027bbef2fd76.png)

(https://sentry.io/organizations/sentry-sdks/performance/sentry-cocoa:85e022100b584757bab7338c4a16d7ff/?project=5428557&query=transaction.duration%3A%3C15m&referrer=performance-transaction-summary&statsPeriod=24h&transaction=LoremIpsumViewController&unselectedSeries=p100%28%29)

I don't know where to get a pristine screenshot as the one from the docs?
