### ISSUE TITLE
Package manager smoke tests

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2517]
### Description

We should have a way to automatically ensure that no changes would result in breaking customers' builds due to breakage in how we ship our SDK via different package managers.

The thing that just came up was here, https://github.com/getsentry/sentry-cocoa/pull/2493#discussion_r1045991093, where not including a header file in the right place might break an SPM build.

**Comment by brustolin** [comment]
We already have tests to try to compile with every package manager.

**Comment by philipphofmann** [comment]
Yes, we do this with https://github.com/getsentry/sentry-cocoa/blob/a8ac44f43021a49fd2ed7917facab54377a7a7dd/.github/workflows/build.yml#L83-L136

and https://github.com/getsentry/sentry-cocoa/blob/a8ac44f43021a49fd2ed7917facab54377a7a7dd/.github/workflows/lint.yml#L43-L69

Do you think any further actions are required, @armcknight?
