### ISSUE TITLE
Serialize permissions to disk

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2527]
### Description

Save every permission change in the disk to be able to use it with crash reports.

**Comment by philipphofmann** [comment]
If we remove permissions cause of https://github.com/getsentry/sentry-cocoa/issues/2528, this issue becomes obsolete.

**Comment by brustolin** [comment]
> If we remove permissions cause of #2528, this issue becomes obsolete.

What about manual permissions? I think this is would be a nice feature
.
