### ISSUE TITLE
iOS SDK - IDFA/IDFV integration

### ISSUE THREAD

**Issue by yeleleo** [getsentry/sentry-cocoa#253]
Hi,

Is it possible to include passing IDFA/IDFV to the reports as _device.id_ and pass it to BI via WEBHOOKS' using macro?

Webhook e.g.
http://server-bi.com/report/?type=crash&device={device.id}&timestamp={timestamp}&crash_level={level}

Kind Regards,
Leo

**Comment by HazAT** [comment]
Hey, sorry for the late response.
So I am not really sure if I fully understand your question but you can add any info you want to events with `setExtraContext`.

About calling a webhook, pretty sure we do not support this on sentry.io, but you can always do it on the device.
