### ISSUE TITLE
Make SentryEnvelope internal

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2542]
### Description

There is no reason why SentryEnvelope should be public. Only the hybrid SDKs need access.

**Comment by kevinrenskers** [comment]
Isn't that already the case?

![Screenshot 2022-12-20 at 11 35 34](https://user-images.githubusercontent.com/229384/208646836-30b9a7df-fe30-4c96-98e6-477c44c648aa.png)

**Comment by philipphofmann** [comment]
Ah, yes, sorry, maybe I was on a wrong branch. Thanks for pointing that out, @kevinrenskers.
