### ISSUE TITLE
Undo Options initWithDict removal

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2547]
### Description

Undo #2404 because hybrid SDKs need to add now the code we removed with #2404; see [React-Native](https://github.com/getsentry/sentry-react-native/pull/2707/files#diff-dad1282b624b71cac21753744cb33f56a8eba8a8e10af18dacdca7c7f132881f). Make `initWithDict` only visible to hybrid SDKs though via `PrivateSentrySDKOnly`.

RN are the only ones using `initWithDict` at the moment. Maybe it's better to move the code removed in #2404 to the RN repo including tests.

**Comment by kevinrenskers** [comment]
If RN is the only one now using this code, it makes sense to me that they added the code we removed. Why add it back here? 

(Also, why don't they just use the options object and set properties, instead of working with the dict?)

**Comment by philipphofmann** [comment]
[Cordova](https://github.com/getsentry/sentry-cordova/blob/a156a550ab09ba47cdd2aca22bc5a83adcd05670/src/ios/SentryCordova.m#L26) and also [Unity](https://github.com/getsentry/sentry-unity/blob/8e51b7bac3fe57d896c525899685d66470725ac6/package-dev/Plugins/macOS/SentryNativeBridge.m#L69) use initWithDict. So we would need to add the code we removed in 3 different places. Therefore, I would rather add it again here.

**Comment by kevinrenskers** [comment]
That makes sense. But why do they even use it in the first place?
