### ISSUE TITLE
Crash: No space left on device exception not handled

### ISSUE THREAD

**Issue by pidjay-grammarly** [getsentry/sentry-cocoa#2548]
### Platform

macOS

### Installed

Carthage

### Version

7.31.2

### Steps to Reproduce

Hi Sentry team,

I could not reproduce the crash in a VM, but the stack traces I've seen point to a call to `[SentrySDK addBreadcrumb:]` leading to a write on disk and an unhandled exception.

From my investigation, the code responsible for this crash has been added to SentrySDK 7.31.0 by this PR (https://github.com/getsentry/sentry-cocoa/pull/2347) and can be found at [this line](https://github.com/getsentry/sentry-cocoa/pull/2347/files#diff-74c03f5955ee12301b06180607c004d40a2c54dc7ef07d3d78c589837de82b39R79).

The exception received is as follows, but despite what it implies, some systems had over 50GB of storage left—although most of them were in the low single-digit GB—which could potentially mean there could also be some permission issues(?).

```
NSFileHandleOperationException
*** -[NSConcreteFileHandle writeData:]: No space left on device
```

The fix should be straightforward (using `@try....@catch`), but I don't know how you want to handle any exception thrown by `[NSFileHandle writeData:]`, so I'll let you take it from here. 

Let me know if you need anything else or have questions.

Thank you!

### Expected Result

Sentry should handle any exception when writing breadcrumbs on disk.

### Actual Result

Sentry crashes after failing to handle an exception.

**Comment by philipphofmann** [comment]
@pidjay-grammarly, do you maybe add plenty of data to your breadcrumbs? How often does this happen?

**Comment by philipphofmann** [comment]
A fix would be to use `writeData:error:` here https://github.com/getsentry/sentry-cocoa/blob/b2eba678bb66d664bafd84c8d4b2a3985dee89bd/Sources/Sentry/SentryOutOfMemoryScopeObserver.m#L79

to handle errors.

**Comment by pidjay-grammarly** [comment]
> @pidjay-grammarly, do you maybe add plenty of data to your breadcrumbs? How often does this happen?
> 
> You can disable the OOMIntegration with
> 
> ```swift
> options.enableOutOfMemoryTracking = false
> ```
> 
> to stop your app from crashing for now.

`options.enableOutOfMemoryTracking` is already set to `false` in our code base. Most of our crashes are coming from breadcrumbs in networking calls, so we would have to disable `options.enableNetworkBreadcrumbs`.

> A fix would be to use `writeData:error:` here
> 
> https://github.com/getsentry/sentry-cocoa/blob/b2eba678bb66d664bafd84c8d4b2a3985dee89bd/Sources/Sentry/SentryOutOfMemoryScopeObserver.m#L79
> 
> to handle errors.

It would, but it's only available from macOS 10.15. Another approach is to use `@try...@catch` to capture and handle the exception thrown by `writeData:` to keep backward compatibility.

**Comment by pidjay-grammarly** [comment]
@philipphofmann, what kind of timeline are we talking about for a fix to land in a release build, given that the holiday season is right around the corner?

**Comment by philipphofmann** [comment]
@pidjay-grammarly, as the fix is easy, I try to push out a hotfix today, but it's not easy as most folks are already gone for the Christmas holidays. If it doesn't work, I can do a hotfix from the 28th to the 30th of December.

**Comment by pidjay-grammarly** [comment]
@philipphofmann, thank you!

**Comment by philipphofmann** [comment]
Hotfix is on the way https://github.com/getsentry/sentry-cocoa/commit/cf43eac1aa12017868c257ad3854ad87a5de0758/checks/ @pidjay-grammarly and @chaseklingelzen.

**Comment by philipphofmann** [comment]
Here you go https://github.com/getsentry/sentry-cocoa/releases/tag/7.31.5

**Comment by chaseklingelzen** [comment]
Great, thank you for the quick turnaround @philipphofmann 🙏

**Comment by philipphofmann** [comment]
No problem, this looked bad, so I wanted to fix it before my Christmas holidays 😁

**Comment by pidjay-grammarly** [comment]
That's awesome! Thanks a lot for that quick turnaround @philipphofmann 🙇‍♂️
