### ISSUE TITLE
Feature request to add demangling for Swift symbols in the crash reports.

### ISSUE THREAD

**Issue by AlexanderKaraberov** [getsentry/sentry-cocoa#255]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Any (4.0-4.1)?
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.0.1**

---
I have following issue:

Currently crash reports coming from Swift codebase contain stack traces with mangled names like `processResults029_8F0B61F033BE544CB6FA31DB7365L1BLLySS12resultString_tFySo25...`
I know that name mangling is not standardized across all C++ compilers, but with Swift demangling should be easier because we have only one compiler. And also Swift compiler mangling scheme is well documented and there is even a [demangler tool](https://github.com/apple/swift/tree/master/tools/swift-demangle) in the Swift repo. Can this be somehow integrated into Sentry to have clutter-free crash reports for Swift?
I can't say that this is a serious issue but still it would be nice to have clear crash reports.

**Steps to reproduce:**

Obtain crash report from the Swift project, observe mangled names which are hardly readable and you have to spent some time to decipher it visually.

**Comment by HazAT** [comment]
Hey, can you link me to an issue where we do not demangle correctly?
We should do this already, if it's not working it's a bug.

**Comment by AlexanderKaraberov** [comment]
Hi @HazAT 
I can't because currently all Swift crash reports that we receive from Sentry are with mangled symbols.
Maybe I should have turned on some flag in the `SentryClient` to enable this? As I said currently we are using 4.0.1. Maybe there is a newer version with this feature?

**Comment by AlexanderKaraberov** [comment]
Also we have a mixed Objective-C/Swift codebase, meaning the same `SentryClient` processes both Obj-C and Swift crashes

**Comment by HazAT** [comment]
@AlexanderKaraberov Are you using sentry.io?

**Comment by AlexanderKaraberov** [comment]
@HazAT This is what I'm using:
https://github.com/getsentry/sentry-cocoa/releases/tag/4.0.1

Also, I checked commit history and I don't see that full crash log/stack trace demangling has been actually implemented. I see only this:  [sanitizeViewControllerName](https://github.com/getsentry/sentry-cocoa/pull/251/files/96bc46fb98958881b5cfcf49f0587b257becb04b#diff-79099d807271a5ec576d48da75162a5fR112) which is not really what i meant.

**Comment by HazAT** [comment]
We removed the on-device demangling with `4.x.x` since we do it on the server anyway and it saves a lot of code we have to maintain.
Again, are you using sentry.io or self hosted?

**Comment by AlexanderKaraberov** [comment]
@HazAT 
Sorry misunderstood question first

> Again, are you using sentry.io or self hosted?

We are self-hosted. Will updating server-side Sentry stack(lib) help? Currently we have 8.17 and latest is 9.0 (afaik?)

**Comment by HazAT** [comment]
@AlexanderKaraberov OK so there lies the problem, you have to upgrade to Sentry 9.0 this should fix it
OR
use `< 4.x.x` and hope that on device symbolication works.
The latest `3.x.x` is basically the same as `4.x.x` we just moved KSCrash into our codebase and removed demangling + fixed a few rare KSCrash caused crashes.
