### ISSUE TITLE
Validate SPM for SwiftUI

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2551]
### Description

Validate in CI that the SwiftUI package compiles properly with a similar approach we already have for Sentry

https://github.com/getsentry/sentry-cocoa/blob/9e9266847f73a28fc238026ed26d24ebd213d042/.github/workflows/build.yml#L101-L119

**Comment by kahest** [comment]
fixed by https://github.com/getsentry/sentry-cocoa/pull/2632
