### ISSUE TITLE
Sentry 7.31.4 and redefinition in SentryDefines

### ISSUE THREAD

**Issue by malcommac** [getsentry/sentry-cocoa#2556]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.4

### Steps to Reproduce

I've updated from sentry 7.0.0 to 7.31.4 via SPM and I get the following errors all located inside SentryDefines.

### Expected Result

it should compile

### Actual Result

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/235645/209179432-0c7c2050-cd2b-43f9-a803-0d23c1fd7ab5.png">

**Comment by philipphofmann** [comment]
I just tried adding `7.31.4` to a sample app, and it compiles. We also have CI checking that SPM compiles https://github.com/getsentry/sentry-cocoa/actions/runs/3706616983/jobs/6282049068

Can you try cleaning your project?

**Comment by salqueng** [comment]
@malcommac Are you using Tuist for managing SPM dependencies?
I tried sentry@7.31.5 with Tuist Dependencies and got the same result.

I could fix the problem by adding `"Sentry": ["USE_HEADERMAP": "YES"]` to `targetSettings` of `Dependencies.swift`

**Comment by malcommac** [comment]
@salqueng yes I'm using Tuist. Your fix works like a charm. Thank you very much!
@philipphofmann Just tried the suggestion above and I can confirm it works fine. You can close this issue, thank you very much for your prompt support.

**Comment by philipphofmann** [comment]
Thanks for the update, @malcommac. We will close the issue once we update the docs.

**Comment by brustolin** [comment]
We added this to the troubleshooting information. 
Thanks all!!

**Comment by philipphofmann** [comment]
Related docs PR https://github.com/getsentry/sentry-docs/pull/6557.

**Comment by keunghyeong123** [comment]
Version 8.8.0 reproduces this issue. I am also using tuist.

**Comment by brustolin** [comment]
Hello @keunghyeong123.
This is a problem with tuist, please see our [troubleshooting page](https://docs.sentry.io/platforms/apple/troubleshooting/#i-use-tuist-and-the-project-crashes-when-i-update-sentry).
