### ISSUE TITLE
Fetch view hierarchy on main thread

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2565]
### Description

The SDK fetches the view hierarchy on the calling thread, which is not guaranteed to be the main thread.

https://github.com/getsentry/sentry-cocoa/blob/04beb80384b82c9d19b4b849d98fc820fcca83de/Sources/Sentry/SentryViewHierarchyIntegration.m#L59-L60

**Comment by brustolin** [comment]
The `fetchViewHierarchy` function can be called from any thread, it guarantees to only use UI objects in the main thread.

https://github.com/getsentry/sentry-cocoa/blob/04beb80384b82c9d19b4b849d98fc820fcca83de/Sources/Sentry/SentryViewHierarchy.m#L64-L68
