### ISSUE TITLE
Introduce separate targets per platform

### ISSUE THREAD

**Issue by willemfrishert** [getsentry/sentry-cocoa#257]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.0.1**

---
I have following issue:
I'm integrating Sentry-cocoa in my iOS-specific framework and want to use `xcodebuild build-for-testing` following by `xcode test-without-building` and run the tests on multiple iOS simulators destinations. Once we integrate Sentry.xcodeproj into my own .xcodeproj, the number of destinations grows to include `MacOS`, `watchOS` and `tvOS` and executing `xcodebuild build-for-testing` seems to ignore a destination at the time of invocation.

A potential fix for this is to keep the currently Sentry target and make specific Sentry targets for each platform available and limit the `SUPPORTED_PLATFORMS` and `TARGETED_DEVICE_FAMILY` in the associated .xcconfig-file. Keeping the currently Sentry target will avoid breaking changes to existing consumers of sentry-cocoa and allows the SentryTests to run all tests.

**Steps to reproduce:**
1. Add sentry-cocoa to Cartfile;
2. Checkout sentry-cocoa with Carthage (`carthage update --platform iOS --no-build --no-use-binaries`);
3. Drag and drop Sentry.xcodeproj onto a iOS-specific framework .xcodeproj;
4. Add the Sentry target as a dependency and add it to `Linked frameworks and libraries`;
5. Close Xcode
6. Reopen Xcode and check on available destinations
7. Open up a terminal
8. Invoke xcodebuild with `build-for-testing`, e.g.: `xcodebuild -scheme ExampleFramework -project ExampleFramework.xcodeproj -destination 'platform=iOS Simulator,name:iPhone X' build-for-testing`

**Actual result:**
At step 6, Xcode will show `MacOS`, `watchOS` and `tvOS` as potential destinations
At step 8, Xcode will attempt to build the x86_64 version of Sentry and instead of using the iOS simulator as a destination (`iPhone X`), it will target the MacOS causing compilation issues for the `ExampleFramework` iOS-specific project.

**Expected result:**
- To be able to build the iOS specific target of Sentry when executing `xcodebuild build-for-testing`

**Comment by philipphofmann** [comment]
I think this should be fixed already. Please open it again @willemfrishert if you still experience the issue.
