### ISSUE TITLE
SwiftUI APM GA

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2572]
### Description

List of tasks before making SwiftUI GA

- [x] https://github.com/getsentry/sentry-cocoa/issues/2537
- [x] https://github.com/getsentry/sentry-docs/issues/5966
- [x] Docs mention SwiftUI in wizard and getting started
- [x] https://github.com/getsentry/sentry-cocoa/issues/2550
- [x] https://github.com/getsentry/sentry-cocoa/issues/2551
- [x] https://github.com/getsentry/sentry-cocoa/issues/2581
- [x] https://github.com/getsentry/sentry-cocoa/issues/2608
- [x] Validate data

**Comment by brustolin** [comment]
> Validate data

By November 15, 2023, we have 1382616 transaction from SwiftUI.

**Comment by kahest** [comment]
let's update the docs to remove the experimental note and then close this
