### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by lemon-li** [getsentry/sentry-cocoa#2576]
### Platform

iOS

### Installed

CocoaPods

### Version

7.10.2

### Steps to Reproduce

I don't know how to reproduce..

### Expected Result

No Error.

## Issue 1
![image](https://user-images.githubusercontent.com/16426343/210718816-05b6c726-af4b-40c1-84ca-cce7291a61da.png)

## Issue 2
![image](https://user-images.githubusercontent.com/16426343/210719182-32b9353b-f99d-4092-bfd5-5943460b6389.png)

The devices I've found to be having issues are all  OS version 16+

**Comment by philipphofmann** [comment]
This crash seems familiar. I think we already fixed that in a previous version, but I can't narrow down the release. Can you please retry with our latest version 7.31.5, and reopen this issue, if the problem still persists?

**Comment by lemon-li** [comment]
> This crash seems familiar. I think we already fixed that in a previous version, but I can't narrow down the release. Can you please retry with our latest version 7.31.5, and reopen this issue, if the problem still persists?

Thanks. I will give you feedback when I upgrade the version.
