### ISSUE TITLE
Do Events purge when internet connection unavailable for extended periods of time?

### ISSUE THREAD

**Issue by GeorgeL9** [getsentry/sentry-cocoa#258]
_Platform:_
- [+ ]  iOS
- [+ ]  tvOS
- [ +]  MacOS
- [ +]  watchOS

_Swift:_
- [ +]  Yes -> If yes, which version? 4.1
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ +] Manually

Version of sentry-cocoa:
**4.0.1**

---
I have following issue:

If our users are out in the field with no internet connection for n-number days, how long do crashes / events get stored locally?
Do they ever get purged from the device?

**Steps to reproduce:**
- Step 1: Cause an event to be logged on any Apple device while not connected to the internet for 1+ days
- Step 2: Reconnect to internet
- Step 3: Events that were logged during that time get uploaded when the device is reconnected to the internet and the app is opened.

**Actual result:**
- Untested

**Expected result:**
- All events are logged to the Sentry server, and removed from local storage.

**Comment by HazAT** [comment]
Hey,

So we store the events indefinitely but only up to 10 events.
After that, we would overwrite the oldest event.

Hope that answers the question :)

**Comment by GeorgeL9** [comment]
I see that this is a constant:
```
NSInteger const maxEvents = 10;
```
in the SentryFileManger.m, is there a way this number can be adjusted without forking the library?

**Comment by HazAT** [comment]
@GeorgeL9 Not yet, but after we merge this it is possible :)
https://github.com/getsentry/sentry-cocoa/pull/259
Will make a release today, stay tuned.
