### ISSUE TITLE
Read scenes in the main thread

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2586]
### Description

View hierarchy and Screenshots needs to read the connected scenes in the main thread, if is not a crash, to avoid warnings.

**Comment by philipphofmann** [comment]
Is this related to https://github.com/getsentry/sentry-cocoa/issues/2571, @brustolin?

**Comment by brustolin** [comment]
> Is this related to https://github.com/getsentry/sentry-cocoa/issues/2571, @brustolin?

A little bit.
Im not sure if this will solve #2571, but I got the problem from there.
