### ISSUE TITLE
It don't work in swift

### ISSUE THREAD

**Issue by Jack-wrs** [getsentry/sentry-cocoa#260]
_Platform:_
- [ ]  iOS

_Swift:_
- [ ]  Yes -> 4.0

_sentry-cocoa installed with:_
- [ ] CocoaPods

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- Add Pod:  `pod 'Sentry'`
- Init Sentry ` func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        do {
            Client.shared = try Client(dsn: "xxxx")
            try Client.shared?.startCrashHandler()
        } catch let error {
            print("\(error)")
            // Wrong DSN or KSCrash not installed
        }

        
        return true
    }`
- Set Build to Release
- Add button click: `  @IBAction func btnAction(_ sender: Any) {
         Client.shared?.crash()
    }`
- It didn't work, I receive no crash. Why??

**Comment by vdphong** [comment]
I am having same trouble with you. I have no idea how to get crash report!

**Comment by adeelnoor** [comment]
It returns error "Project ID path component of DSN is missing" swift 4

**Comment by HazAT** [comment]
Closing this because of missing info, it works just fine in Swift.
Please also make sure to copy the correct DSN.
