### ISSUE TITLE
Fix flaky `testGetRequest_SpanCreatedAndBaggageHeaderAdded`

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2605]
### Description

Noticed it was skipped in the Xcode scheme but there was no associated issue for it.

**Comment by brustolin** [comment]
This test is enable for a while now and seen to be ok.
If this fails again please ping me so I can investigate.

**Comment by brustolin** [comment]
My Xcode that was flaky and the context menu was showing `disable test` when in fact it was disabled already.
I will enable it to be able to monitor it.
