### ISSUE TITLE
Package dropped out of Swift Package Index

### ISSUE THREAD

**Issue by finestructure** [getsentry/sentry-cocoa#2615]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.0.0

### Steps to Reproduce

Apologies if this isn't the proper place to raise this - it's not actually an issue with the package but rather it currently being unavailable in the [Swift Package Index](https://swiftpackageindex.com).

Is it possible that you've changed your default branch a short while ago?

If so, everything should sort itself out again soon.

It'd be great to know for us if that's the case so we know where to direct our attention in addressing this.

See this issue for details: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2217#issuecomment-1384503245

Thank you!

### Expected Result

-

### Actual Result

-

**Comment by finestructure** [comment]
It appears that's indeed what happened, sorry for the noise!

https://github.com/getsentry/sentry-cocoa/commit/feba2be7751fb57d122800cd1964eeef43aaac61

**Comment by philipphofmann** [comment]
Thanks for looking into it, @finestructure. No need to apologize.
