### ISSUE TITLE
Only add referenced binary images to crash report

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2617]
### Description

When writing the crash report, we can only add the binary images referenced in the stack traces of all threads

https://github.com/getsentry/sentry-cocoa/blob/56ec5d04c9b2d9c989dfc5e55f904c537bdc2956/Sources/SentryCrash/Recording/SentryCrashReport.c#L1727-L1728

We already do this when getting the stack trace when capturing not fatal events and ANRs in `getDebugImagesForThreads`:

https://github.com/getsentry/sentry-cocoa/blob/56ec5d04c9b2d9c989dfc5e55f904c537bdc2956/Sources/Sentry/SentryDebugImageProvider.m#L42-L65

We must ensure to call `writeAllThreads` before `writeBinaryImages`.

https://github.com/getsentry/sentry-cocoa/blob/56ec5d04c9b2d9c989dfc5e55f904c537bdc2956/Sources/SentryCrash/Recording/SentryCrashReport.c#L1727-L1744

**Comment by kahest** [comment]
Should be done in `SentryCrashReportConverter` during converting the crash report to `SentryEvent`.

**Comment by philipphofmann** [comment]
The SDK only sends referenced binary images for crash events with https://github.com/getsentry/sentry-cocoa/pull/1767. It's not worth the effort to only write referenced binary images when writing the crash report when we remove them when converting the crash report to a Sentry event. The benefit would be that the stored crash report would be a bit smaller, but usually, only one crash report is stored to disk at a time.
