### ISSUE TITLE
Duplicate symbols with separate KSCrash static lib

### ISSUE THREAD

**Issue by tyleralves** [getsentry/sentry-cocoa#264]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:

I have to include a separate static lib of KSCrash(1.4.6) for another project, and am getting a duplicate symbols linker error for 9 symbols.

**Expected result:**
- SentryCrash class needs to be fully prefixed and some functions need to be made static. I forked and made the changes so that it'll work with my project, so hopefully you'll pull it back in the the main project.

**Comment by heyaj19** [comment]
Why was this closed without any resoltutions?

**Comment by HazAT** [comment]
It was closed without a resolution, see https://github.com/getsentry/sentry-cocoa/pull/265
