### ISSUE TITLE
Support `connectionTimeoutMillis` and `readTimeoutMillis`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#2658]
### Problem Statement

Context: https://github.com/getsentry/sentry-dart/issues/1149
For places with slow or unstable internet, the connection/read default timeout might not be enough (5s) by default.
With these settings, people would be able to increase the timeouts, this already exists for Java/Android.

### Solution Brainstorm

Support `connectionTimeoutMillis` and `readTimeoutMillis`.

**Comment by brustolin** [comment]
For cocoa, the default timeout is 60 seconds, we never had a complain about this. We dont see a benefit of implementing this.
