### ISSUE TITLE
Setting logLevel to Verbose produces unwanted console logs

### ISSUE THREAD

**Issue by appmagnetics** [getsentry/sentry-cocoa#266]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.x 
- [ ]  No

_sentry-cocoa installed with:_
- [x ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**latest**

---
I have following issue:
If I'm using kSentrySeverityError for sending events, events go through. 
If I'm using kSentrySeverityInfo - they do not. Then I go and set Client.logLevel = kSentryLogLevelVerbose 
Then the messages go through but I have a heavy debug print output in the console. Is the setting the logging level of Sentry itself or filter for the client app logs? I cannot do both, right? 

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
Info messages go through but no extended logs is seen on the app console.

**Comment by HazAT** [comment]
So setting `Client.logLevel` is only setting it for Sentry internal debug log messages, it is not interfering with sending event.
There is no setting that tells Sentry to only send events, that are higher than let's say `kSentrySeverityInfo`.
All events will be sent, setting the level of an event just changes the level of the event.
Hope this helps.

**Comment by appmagnetics** [comment]
Thank you for such fast response. I cannot explain the root cause why it was seemed to not working at my side but now it's working, sorry for troubling.
