### ISSUE TITLE
Using SentrySDK with Swift concurrency - missing user/contexts

### ISSUE THREAD

**Issue by lukeredpath** [getsentry/sentry-cocoa#2668]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.4

### Steps to Reproduce

We recently refactored our client wrapper around the Sentry SDK to use Swift concurrency, which means SentrySDK methods can be called from any thread (whichever thread in the concurrency thread pool executes our async task). Is this safe to do?

I ask because since we shipped our latest update, I've noticed that our errors are no longer showing the correct user information, or a bunch of custom contexts and tags that we set on the client.

I've been testing this locally in the simulator and strangely, I am seeing errors arrive in Sentry with the data intact. I can also set a breakpoint in the SDK just before the point before it uploads the event and inspect it and I can see the error event has the correct user/contexts/tags.

I'm wondering if I'm seeing non-deterministic behaviour due to multiple threads calling the Sentry SDK or there's some other issue at hand?

### Expected Result

Errors should have correct user and metadata.

### Actual Result

Errors do not have the correct user - they seem to have anonymous user UUIDs. Custom contexts and tags are missing.

**Comment by lukeredpath** [comment]
I have got to the bottom of this - it was less a thread safety issue but more a concurrency/race condition issue.

We call the `start()` method in the app delegate's app did finish launching - because our wrapper's function is async we do this in a `Task`. Separately on launch we were setting up the session and configuring the user and tags/context. Unfortunately it looks like this was happening _before_ the `start()` call executed, causing the metadata to be lost when the client is initialised in `start()`.

The solution was to ensure that `start()` and all of the session setup happen within a single `Task` so their order can be guaranteed.

**Comment by philipphofmann** [comment]
Thanks for the detailed explanation, @lukeredpath.
