### ISSUE TITLE
Missing Include in SamplingProfiler

### ISSUE THREAD

**Issue by thekief** [getsentry/sentry-cocoa#2678]
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.3

### Steps to Reproduce

1. use a self-built nightly toolchain of swift
2. have a project that includes sentry-cocoa
3. build the project

### Expected Result

The project builds without any problems.

### Actual Result

The project does not properly build and following error is printed:

```
/Users/obfuscator-builder/Library/Developer/Xcode/DerivedData/test_app-gqrwiwirbosixfekearlrdjcqwng/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/include/SentrySamplingProfiler.hpp:67:14: error:
      missing '#include "/Library/Developer/Toolchains/swift-LOCAL-2023-02-01-a.xctoolchain/usr/bin/../include/c++/v1/atomic"';
      'atomic_uint64_t' must be declared before it is used
        std::atomic_uint64_t numSamples_;
             ^
In module 'std' imported from /Users/obfuscator-builder/Library/Developer/Xcode/DerivedData/test_app-gqrwiwirbosixfekearlrdjcqwng/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/include/SentrySamplingProfiler.hpp:7:
/Library/Developer/Toolchains/swift-LOCAL-2023-02-01-a.xctoolchain/usr/bin/../include/c++/v1/atomic:2651:26: note:
      declaration here is not visible
typedef atomic<uint64_t> atomic_uint64_t;
                         ^
1 error generated.
```

### Are you willing to submit a PR?

Yes

**Comment by philipphofmann** [comment]
@armcknight, could you please have a look at this one ⬆️ ?

**Comment by thekief** [comment]
I just re-tested it with the `release/5.8` branch of Swift (commit bc62e307899) and the associated sub-projects and it seems to be fine now. The problem stemmed from including the `include` folder of the snapshot version to search for headers instead of using the default one. 

Either way, I am not sure if this issue should be closed. I think it still be good that an explicit `#include <atomic>` is added rather than relying on the standard library to hopefully include it somewhere else.
