### ISSUE TITLE
How do you set environment for a crash?

### ISSUE THREAD

**Issue by GLJeffery** [getsentry/sentry-cocoa#268]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> If yes, which version? 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:

Unable to set environment for crashes

**Steps to reproduce:**
```
            Client.shared?.beforeSerializeEvent = { event in
                event.environment = "DEBUG"
            }
```

**Actual result:**
No environments are sent for crashes, so in the sentry dashboard none of the crashes have environment, and they are not filterable based on environment

**Expected result:**
Crashes would have environment set on them, so I know which environment the crash occurred on. I realize the above code sets an environment for events, but is there a way to set environment for crashes?

**Comment by HazAT** [comment]
So I just tried it, wrote a test and sent an example event 
both had `"environment" : "DEBUG",` in it also the event had the tag
<img width="164" alt="screenshot 2018-11-22 09 08 11" src="https://user-images.githubusercontent.com/363802/48889428-30d96b80-ee36-11e8-87c6-4d8933ec6c12.png">

So I need a reproducation case for this, it seems to work just fine.

**Comment by HazAT** [comment]
Closing this since it's inactive if you are still having this issue feel free to post again.

**Comment by GLJeffery** [comment]
Sorry, @HazAT I missed your comment in my emails somewhere, I'm not trying to attach it to an event, but rather the Crash reporting that Sentry automatically sends already, since I am not sending events in the app but rather letting the automatic crash reporting send crashes.

**Comment by GLJeffery** [comment]
`        do {
            Client.shared = try Client(dsn: "--hidden--")
            Client.shared?.enableAutomaticBreadcrumbTracking()
            Client.shared?.beforeSerializeEvent = { event in
                event.environment = "DEBUG"
            }
            try Client.shared?.startCrashHandler()
        } catch let error {
            print("\(error)")
        }
`
