### ISSUE TITLE
Add enableTracing option

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-cocoa#2680]
A new simplified options for configuring to turn tracing & performance on should be added to all SDKs. For each SDK the default sample rate should be agreed upon.  

Docs do not need to be updated yet, nor the onboarding wizard. This can wait until the top level options are added to a number of SDKs and we decide if we want to configure the default onboarding experience, for all new users.

See [develop docs](https://develop.sentry.dev/sdk/performance/#enabletracing) for more information. This is a non-breaking change to be clear. Any of the three options should enable performance, alone or in combination

### Open point:
recommend default it 1.0 or 100%. Can discuss if it should be less.

**Comment by smeubank** [comment]
I am not familiar with sdks for iOS 😅 I will lean on your expertise @kahest as to how this should be added

**Comment by philipphofmann** [comment]
The default value of the `tracesSampleRate` is `nil`:
https://github.com/getsentry/sentry-cocoa/blob/8f397a72ebc82923bd173410e0902c7cd70c7ba0/Sources/Sentry/SentryOptions.m#L91-L92

We can add `enableTracing` with a default `true`, which has no impact. If the user sets `enableTracing` to `false` the SDK won't collect any traces no matter what the `tracesSampleRate` is.

`isTracingEnabled` needs an update as well
https://github.com/getsentry/sentry-cocoa/blob/8f397a72ebc82923bd173410e0902c7cd70c7ba0/Sources/Sentry/Public/SentryOptions.h#L286

Also update the code docs on the following to clearly communicate what the default value is: https://github.com/getsentry/sentry-cocoa/blob/8f397a72ebc82923bd173410e0902c7cd70c7ba0/Sources/Sentry/Public/SentryOptions.h#L267-L273

**Comment by philipphofmann** [comment]
Related to https://github.com/getsentry/sentry-cocoa/issues/2685.

**Comment by kahest** [comment]
For clarification:
- `enableTracing` should be added as a new, optional setting, defaulting to nil, in which state it doesn't have any effect whatsoever, therefore it's considered a non-breaking change
- if `enableTracing` is explicitely set to `true` **and** `tracesSampleRate` is unset (`nil`), `tracesSampleRate` should be set to a default `>0` (likely `1.0`) and `isTracingEnabled` should return `true`
- if `enableTracing` is explicitely set to `false`, it should deactivate tracing, i.e. `isTracingEnabled` should return `false`

See also the PHP PR for this: https://github.com/getsentry/sentry-php/pull/1458
