### ISSUE TITLE
Dont create breadcrumbs for keys pressed in a textview/textfield

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2682]
### Description

Every key pressed in a input field creates a new breadcrumb for `textChanged` and this is very spammy.

We could avoid create this breadcrumbs, or try to aggregate those in a single breadcrumb with the amount of times it was changed.

**Comment by brustolin** [comment]
This happens when the textfield has a target for `UIControlEventEditingChanged` which is a common think to do.
A simple character count would trigger this behavior.

**Comment by armcknight** [comment]
We should also call this out at https://docs.sentry.io/platforms/apple/enriching-events/breadcrumbs/#automatic-breadcrumbs. We should probably have a separate bullet point for `UIControlEvents`, and then list this as excluded.

What does this mean?

> A simple character count would trigger this behavior.

We could also consider making a SentryOption entry to let devs create a list of UIEvent types to either allow or block. I can see how observing editingChanged could be useful for like a targeted RCA. Although that is probably better done by developers themselves with custom breadcrumbs in their own action handler or delegate callback. Might be worth specifically explaining that in headerdocs and/or our web docs.

I like your idea of aggregating as well. Could do something between editingDidBegin and editingDidEnd[OnExit].
