### ISSUE TITLE
Create `User` and `Breadcrumb` data classes from a dictionary

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#2687]
### Description

We have a lot of duplicate code across Hybrid SDKs, as most of them need to create the native data classes from a map.

- https://github.com/getsentry/team-mobile/issues/59

The goal is to add the following:
`[[SentryBreadcrumb alloc] initWithDict:dictionary]`
`[[SentryUser alloc] initWithDict:dictionary]`

As all the hybrid SDKs can use this.

**Comment by brustolin** [comment]
IMO at first glance this looks nice, to create this once in the cocoa SDK and every other project make use of it. 
But tbh, once every other SDK has its own code you don't change it anymore.
And by implementing this on the hybrid SDK, you will receive a compilation error if you trying to access invalid property. 
If we do this in the cocoa side, the hybrid SDK will pass a dictionary and any invalid property (removed or renamed) will be swallowed and you wont know about it.

**Comment by philipphofmann** [comment]
@brustolin, we could return `nil` if an error occurs or use `NSError` to communicate the error.

**Comment by brustolin** [comment]
Then we would need to check every entry in the dictionary to confirm the property name. Its doable, but i don't think is worth it.
