### ISSUE TITLE
Add `lastEventId`

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#2705]
Add and set `lastEventId` for `captureEvent`, `captureException`, `captureMessage`.

See https://github.com/getsentry/team-mobile/issues/61#issuecomment-1436492761

**Comment by philipphofmann** [comment]
We don't see a good use case except for user feedback at the moment, but our capture methods already return the eventId so users can map their feedback to a previously captured event. We can always add `lastEventId` in the future if needed.
