### ISSUE TITLE
Unable to find a specification for 'SentrySwifUI'

### ISSUE THREAD

**Issue by nguyenquocdathcmus** [getsentry/sentry-cocoa#2719]
### Platform

iOS

### Installed

CocoaPods

### Version

8.2.0

### Steps to Reproduce

I try with this doc but can not pod install.
https://docs.sentry.io/platforms/apple/guides/ios/performance/instrumentation/swiftui-instrumentation/
1. update pod file 
platform :ios, '13.0'
use_frameworks! # This is important

target 'YourApp' do
  pod 'SentrySwifUI', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.2.0'
end
2. pod install

### Expected Result

Can install success!

### Actual Result

[!] Unable to find a specification for 'SentrySwifUI'.

**Comment by philipphofmann** [comment]
There is a typo in the docs. Can you try `SentrySwif**t**UI`, @nguyenquocdathcmus ?

**Comment by philipphofmann** [comment]
Docs PR https://github.com/getsentry/sentry-docs/pull/6354.

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/sentry-docs/pull/6354.
