### ISSUE TITLE
Automatic Instrumentation not working.

### ISSUE THREAD

**Issue by nguyenquocdathcmus** [getsentry/sentry-cocoa#2722]
### Platform

iOS

### Installed

CocoaPods

### Version

8.2.0

### Steps to Reproduce

1. I refer to this channel, download the example, and then change my DNS sentry.
https://www.youtube.com/watch?v=J0tAK6dKY3Y
https://github.com/getsentry/sentry-cocoa/tree/main/Samples

Are there any limitations or conditions on the plan account?
My account plan:  Developer plan

### Expected Result

Automatic Instrumentation can working.

### Actual Result

It can capture a message. Automatic Instrumentation does not display the result

**Comment by philipphofmann** [comment]
@nguyenquocdathcmus did you also set a sample rate, as pointed out in the [docs](https://docs.sentry.io/platforms/apple/performance/)? 

```swift
import Sentry

SentrySDK.start { options in
    options.dsn = "https://3d91f10f1d184515b3d434bdc0d906a4@o19635.ingest.sentry.io/7130"

    options.tracesSampleRate = 1.0
}
```

**Comment by nguyenquocdathcmus** [comment]
> 

Thanks . My account has been a full quota for transactions. I have tried with a new account, It works well.
