### ISSUE TITLE
I would like to have stack traces that cross Objective-C and cgo boundaries

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2730]
### Problem Statement

We make calls to a cgo library that we build and we just got an "App Hanging" alert with a full golang stack trace (cool!). Unfortunately the stack trace ends at `crosscall2`. It would be nice if it could also include what the Objective-C stack frames were that called into the cgo code.

**Comment by philipphofmann** [comment]
@eric, could you share a small sample project with us so we can reproduce this or explain how exactly you include the cgo code into your project? Is this again tvOS?

**Comment by eric** [comment]
I've added a cgo library to the cocoa sample app and a button to make it hang for 3 seconds:
https://github.com/fancybits/sentry-demos-cocoa/tree/sample-with-cgo

> Is this again tvOS?

tvOS and iOS

**Comment by philipphofmann** [comment]
Thanks, @eric. We have to investigate this and get back to you. I can't give you an ETA at the moment.

**Comment by eric** [comment]
I would still like this

**Comment by philipphofmann** [comment]
We don't see a large user base for cgo users at the moment. Therefore, we can be honest and close this issue, as we would never get to it with all the other items on our backlog. @eric or anybody, if you can convince us that there is a large enough user base backed by some data, feel free to reopen the issue, and we're going to reconsider.
