### ISSUE TITLE
SentrySDK.capture(Event) message error

### ISSUE THREAD

**Issue by ShrinkLynn** [getsentry/sentry-cocoa#2733]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

```swift
let sentryMessage = SentryMessage(formatted: "title")
sentryMessage.message = "testMessage"
sentryMessage.params = ["params"]

let event = Event(level: .info)
event.message = sentryMessage
SentrySDK.capture(event: event)
```

### Expected Result

show a message like "testMessage" in Sentry issue detail.
by the way ,  params is expectable

### Actual Result

now，message display like title：

**my request：**
title is different with message
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7589500/221805742-35f5504d-bc16-487c-a655-69929afd6f21.png">

**Sentry issue Detail request：**
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7589500/221806752-6a2393c8-0afb-413e-aa94-55bdd23571fb.png">

**Sentry issue Detail Show**
<img width="586" alt="image" src="https://user-images.githubusercontent.com/7589500/221806392-d1f55b2d-4174-42fc-8ce6-affac79339ef.png">

**Comment by philipphofmann** [comment]
@ShrinkLynn, why don't you use?
```
SentrySDK.capture(message: "testMessage")
```

It basically does what you do manually see https://github.com/getsentry/sentry-cocoa/blob/6ad07aeec64a329291486db577163df3007244b3/Sources/Sentry/SentryClient.m#L159-L169

**Comment by ShrinkLynn** [comment]
@philipphofmann  

I thought `SentryMessage - formatted` is issue title and `SentryMessage - message` is issue message before；
Maybe it‘s a misunderstand，it just like ，"formatted" is display message and "message" is original message ?

However，when I send different texts to "formatted" & "message"，it seems "formatted" is higher priority than "message" displaying in issue detail page.
so how is the different between "formatted" & "message" when designing the properties?

https://github.com/getsentry/sentry-cocoa/blob/f128c160353566a6cabf5a4bcca7172b4475d501/Sources/Sentry/Public/SentryMessage.h#L24-L35

**Comment by philipphofmann** [comment]
Does this explain it https://develop.sentry.dev/sdk/event-payloads/message/?

**Comment by ShrinkLynn** [comment]
Thank for answer me.

So, now there’s no way to display different text in two red areas below？

![image](https://user-images.githubusercontent.com/7589500/221840040-71bce296-9fdd-4deb-8a8b-da3ac57c96bb.png)

**Comment by philipphofmann** [comment]
@ShrinkLynn, no, it's the same message. The top one is the title of the issue, which is the message, and below we again show the message.
