### ISSUE TITLE
upload Dsym file

### ISSUE THREAD

**Issue by omerCoosto** [getsentry/sentry-cocoa#274]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.1**

Version of sentry server:
**9.0.0**

---
I have following issue:

Hi,
I'm trying to upload my dsym file to sentry (on our own server) but unfortunately the process enter in an infinite loop while uploading.

**Steps to reproduce:**
`sentry-cli --auth-token XXX_TOKEN_XXX --url https://company_sentry.com upload-dsym --org sentry --project ios-app appDsyms.zip 
`

**Actual result:**
It recognise the Dsym zip and find all the information files inside (42), then it try to upload it with the following request `request POST https://company_sentry.com/api/0/projects/sentry/ios-app/files/difs/assemble/`

I do receive a 200 from this call but it enter in a loop (all of them 200) and the file is never uploaded.
I also see this as a progress bar on my terminal but nothing change.
> Processing files... 0/42

**Expected result:**
Expect to see a debug symbols file for my project (in "Debug Information Files" settings)

**Comment by HazAT** [comment]
Which version of sentry are you running?

**Comment by omerCoosto** [comment]
Hi, just to know if you have any new ideas.

Some more info when i try to upload i have this warning i don't know if it's relevant. 
`  WARN    2019-01-17 14:11:20.791596 +01:00 section #1 size 2279871 out of bounds  (from goblin)
  WARN    2019-01-17 14:11:20.793883 +01:00 section #1 size 2247143 out of bounds  (from goblin)
  WARN    2019-01-17 14:11:20.798388 +01:00 section #1 size 28733363 out of bounds  (from goblin)
  WARN    2019-01-17 14:11:20.806596 +01:00 section #1 size 28172395 out of bounds  (from goblin)`

**Comment by Eysner** [comment]
We have same problem. 

**Uploading log:**
[17:01:05]: sentry-cli 1.49.0 installed!
[17:01:05]: Starting sentry-cli...
[17:01:14]: > Found 77 debug information files
[17:01:15]: > Prepared debug information files for upload
[17:01:16]: > Nothing to upload, all files are on the server
[17:01:16]: > No new debug symbols to associate.
[17:01:17]: Successfully uploaded dSYMs!

But in website, we didn't see any dsym
<img width="1209" alt="Screenshot 2020-01-13 at 00 32 19" src="https://user-images.githubusercontent.com/7359263/72222965-dc92cd00-359c-11ea-9b26-edc050bdabcf.png">
It reproduce only in company sentry.

**Comment by momoAI** [comment]
We have same problem.

**Comment by eyuxin** [comment]
Any process？

**Comment by philipphofmann** [comment]
As we didn't receive any new input we are going to close this issue. Please feel free to open it again if you have more information.
