### ISSUE TITLE
Initializing Sentry in a SwiftUI app results in accent color not being respected

### ISSUE THREAD

**Issue by caseybutatwork** [getsentry/sentry-cocoa#2741]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.2.0

### Steps to Reproduce

1. Set a custom accent color (e.g., red) by modifying the `AccentColor` in `Assets.xcassets`
2. Create a view that uses the above accent color in some way (e.g., the `foregroundColor` of a `Text` view)
3. Add the following line to the `init` of the `App`-conforming struct identified by `@main`
`init() { SentrySDK.start { _ in } }`
5. Run the app

OR

Download and run this [sample project](https://github.com/caseybutatwork/SentrySwiftUIAccentColor)

### Expected Result

The text is red (the custom accent color)

### Actual Result

The text is blue (the default accent color)

### Are you willing to submit a PR?

Unfortunately, I do not have the time

**Comment by caseybutatwork** [comment]
Originally, I found [this](https://github.com/getsentry/sentry-cocoa/issues/1668), but it was marked closed, so I opened this new issue

**Comment by philipphofmann** [comment]
Thanks for reporting this and adding a sample project, @caseybutatwork. We are going to have a look at this tomorrow and get back to you.

**Comment by brustolin** [comment]
I find the problem, which seems to be a SwiftUI bug.
I report the bug to Apple, but Im not to confident that they will do something (or when), so I will try to figure it out some workaround.
