### ISSUE TITLE
Environment for Crashes specifically do not appear in Sentry Dashboard

### ISSUE THREAD

**Issue by GLJeffery** [getsentry/sentry-cocoa#275]
How do you set an environment for Crashes (not events)? I am familiar with how to send environment as part of an event, but a crash that is recorded by Sentry doesn't seem to be an event, and so environment is not sent with it.

_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> If yes, which version? 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [X] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:

Unable to set environment for crashes

**Steps to reproduce:**
```
            Client.shared?.beforeSerializeEvent = { event in
                event.environment = "DEBUG"
            }
```

**Actual result:**
No environments are sent for crashes, so in the sentry dashboard none of the crashes have environment, and they are not filterable based on environment

**Expected result:**
Crashes would have environment set on them, so I know which environment the crash occurred on.

This is my setup method
```
        do {
            Client.shared = try Client(dsn: "--hidden--")
            Client.shared?.enableAutomaticBreadcrumbTracking()
            Client.shared?.beforeSerializeEvent = { event in
                event.environment = "DEBUG"
            }
            try Client.shared?.startCrashHandler()
        } catch let error {
            print("\(error)")
        }
```

**Comment by GLJeffery** [comment]
Should I be using _SentryCrash.sharedInstance.onCrash_ instead?

**Comment by GLJeffery** [comment]
Anyone can help with this?

**Comment by HazAT** [comment]
Hey, sorry for not replying earlier.
This should work, I will check whats going on.

**Comment by HazAT** [comment]
OK, I just tried it out in a clean example using the latest version and it works for both `captureMessage` as well as hard crashes and after restart sent events.

```swift
            Client.shared = try Client(dsn: "DSN")
            try Client.shared?.startCrashHandler()
            Client.logLevel = .verbose
            Client.shared?.beforeSerializeEvent = { event in
                event.environment = "production"
            }
```

**Comment by GLJeffery** [comment]
looks like we call beforeSerializeEvent in different places (yours after startCrashHandler(), mine before) I will give that a shot.

is logLevel verbose needed for it to work as well?

**Comment by HazAT** [comment]
No, `logLevel` should not influence it, also the order when you set `beforeSerializeEvent` shouldn't matter 🤔

**Comment by GLJeffery** [comment]
are you crashing from a Sentry forced crash? or something like

```
let foo: String? = nil
print("\(foo!)") // app crash
```

and relaunching the app after and receiving the environment in sentry?

**Comment by HazAT** [comment]
From a Sentry forced crash  `Client.shared?.crash()`

**Comment by GLJeffery** [comment]
any ideas @HazAT?

**Comment by HazAT** [comment]
I am really sorry, but I need a repro case.
Could you create a small sample project showing this behavior?

**Comment by GLJeffery** [comment]
Closing, the way to do it is after initializing client,

`Client.shared?.environment = "Production"`
