### ISSUE TITLE
[Question] Sentry (might be) causing iOS App to show a "connect to local devices" permission request

### ISSUE THREAD

**Issue by zettlunic** [getsentry/sentry-cocoa#2750]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.2.0

### Steps to Reproduce

1. Start Sentry SDK
2. :shrug

### Expected Result

Sentry would not unexpectedly cause the app to show a connect to local devices permission request.

### Actual Result

Our iOS App to shows a "connect to local devices" permission request. We're not sure if Sentry is causing this, but we've recently updated from 7.31.4 to 8.2.0. The permission dialogue shows up after app start, seemingly random, not for every user/session.

I'm aware this is a very general report and possibly totally unrelated to Sentry. I just would be very grateful for any hints if the SDK _could_ be causing this. See [apple dev forums](https://developer.apple.com/forums/thread/663858) for a good overview of what could be causing this. TIA!
 
![IMG_0706](https://user-images.githubusercontent.com/2598984/222710351-78922e47-db01-4920-ad47-4dcbb6e777c4.jpg)

### Are you willing to submit a PR?

Sure

**Comment by brustolin** [comment]
According to [apple dev forums](https://developer.apple.com/forums/thread/663858), if you make a local network request this message appears. Maybe there is something in your app doing this?
