### ISSUE TITLE
__CFRunLoopServiceMachPort + 160

### ISSUE THREAD

**Issue by shenyinghao** [getsentry/sentry-cocoa#2757]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

Stack information of crashed platform statistics：
SentryCrashCachedData.c - 第 144 行
monitorCachedData + 144

SentryCrashMonitor_MachException.c - 第 305 行
handleExceptions + 305

### Expected Result

No crash.

### Actual Result

Crash.

**Comment by brustolin** [comment]
Do you have more information on this crash?
The error message or a way to reproduce would help.

**Comment by shenyinghao** [comment]
com.apple.main-thread
0
libsystem_kernel.dylib
mach_msg2_trap + 8
3
libsystem_kernel.dylib
mach_msg + 24
4
CoreFoundation
__CFRunLoopServiceMachPort + 160
5
CoreFoundation
__CFRunLoopRun + 1232
6
CoreFoundation
CFRunLoopRunSpecific + 612
7
GraphicsServices
GSEventRunModal + 164
8
UIKitCore
-[UIApplication _run] + 888
9
UIKitCore
UIApplicationMain + 340
10
libswiftUIKit.dylib
UIApplicationMain(_:_:_:_:) + 104

**Comment by philipphofmann** [comment]
@shenyinghao, the stack trace you provided doesn't contain any frames of Sentry. Unfortunately, the information you provided doesn't give us enough insight to solve this crash. Please post a proper stack trace with the error message you receive.
