### ISSUE TITLE
Fatal Exception: NSGenericException *** Collection <__NSArrayM: 0x2802de5b0> was mutated while being enumerated.

### ISSUE THREAD

**Issue by shenyinghao** [getsentry/sentry-cocoa#2758]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

0
CoreFoundation
__exceptionPreprocess
2
CoreFoundation
-[__NSSingleObjectEnumerator init]
3

SentryTracer.m - 第 700 行
-[SentryTracer toTransaction] + 700
4

SentryTracer.m - 第 639 行
-[SentryTracer finishInternal] + 639
5
SentryTracer.m - 第 344 行
-[SentryTracer spanFinished:] + 344
6

SentrySpan.m - 第 149 行
-[SentrySpan finishWithStatus:] + 149
7

SentryNSDataTracker.m - 第 257 行
-[SentryNSDataTracker finishTrackingNSData:span:] + 257
8

SentryNSDataTracker.m - 第 117 行
-[SentryNSDataTracker measureNSDataFromFile:options:error:method:] + 117
9

SentryNSDataSwizzling.m - 第 100 行
__38+[SentryNSDataSwizzling swizzleNSData]_block_invoke_2.43 + 100
10
Foundation
+[NSData(NSData) dataWithContentsOfFile:options:error:]
11

GDTCORPlatform.m - 第 246 行
GDTCORDecodeArchiveAtPath + 246
12

GDTCORFlatFileStorage.m - 第 209 行
__75-[GDTCORFlatFileStorage batchWithEventSelector:batchExpiration:onComplete:]_block_invoke_2 + 209
13
libdispatch.dylib
_dispatch_call_block_and_release
19
libsystem_pthread.dylib
start_wqthread

### Expected Result

no crash

### Actual Result

crash

**Comment by brustolin** [comment]
This was fixed here https://github.com/getsentry/sentry-cocoa/pull/2744. New release soon.
