### ISSUE TITLE
SentryTracer.m - 第 515 行 -[SentryTracer setMeasurement:value:] + 515

### ISSUE THREAD

**Issue by shenyinghao** [getsentry/sentry-cocoa#2759]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

0
CoreFoundation
-[__NSDictionaryM setObject:forKeyedSubscript:] + 432
1

SentryTracer.m - 第 515 行
-[SentryTracer setMeasurement:value:] + 515
2

SentryTracer.m - 第 874 行
-[SentryTracer addMeasurements:] + 874
3

SentryTracer.m - 第 714 行
-[SentryTracer toTransaction] + 714
4

SentryTracer.m - 第 639 行
-[SentryTracer finishInternal] + 639
5

SentryTracer.m - 第 344 行
-[SentryTracer spanFinished:] + 344
6

SentrySpan.m - 第 149 行
-[SentrySpan finishWithStatus:] + 149
7

SentryNetworkTracker.m - 第 290 行
-[SentryNetworkTracker urlSessionTask:setState:] + 290
8

SentryNetworkTrackingIntegration.m - 第 72 行
__57+[SentryNetworkTrackingIntegration swizzleURLSessionTask]_block_invoke_2.27 + 72
9
CFNetwork
_CFNetworkErrorGetLocalizedRecoverySuggestion + 4168
24
libsystem_pthread.dylib
start_wqthread + 8

### Expected Result

no crash

### Actual Result

crash

**Comment by brustolin** [comment]
Can you try version 8.2.0?

**Comment by shenyinghao** [comment]
I'll try, thank you

**Comment by brustolin** [comment]
Hello @shenyinghao 
Do you have a repro to share with us?

**Comment by philipphofmann** [comment]
@shenyinghao, thanks for opening up all these issues. Please share the error / crash / exception message with us. The stack trace is not enough for us.
