### ISSUE TITLE
Separate Enum Based Errors

### ISSUE THREAD

**Issue by braker1nine** [getsentry/sentry-cocoa#2760]
### Problem Statement

In our application we use a variety of enum based error objects to group similar errors in a domain, but still let us handle different types differently.

```swift
enum SyncError: Error {
    case networkError(Error)
    case invalidToken
    case oopsOhNo
}
```

But when capturing this to sentry, they're all grouped together as just `SyncError` in the sentry backend. They seem to all have the same title. This makes it hard to easily tell which type of error we're seeing.

### Solution Brainstorm

It would be nice if these errors were automatically separated based on the case in the enum? So something like `SyncError.networkError` would show up as the title and each case would be automatically separated.

### Are you willing to submit a PR?

Of course!

**Comment by braker1nine** [comment]
@philipphofmann I think I tried that. But as I understand it. It only customizes the description of the error. Not the title. Am I wrong?

But every error in this enum ends up with the same title and seems to get grouped together. It's definitely I'm just not understanding how to use that feature 😅

**Comment by philipphofmann** [comment]
Each of your enum values in `SyncError` should end up in an extra group in Sentry.

We have SampleError in our sample app with three different values:

https://github.com/getsentry/sentry-cocoa/blob/20163bbb741f4984e55f1f971d68a9105dcaebc1/Samples/iOS-Swift/iOS-Swift/Tools/RandomErrors.swift#L3-L7

Each of them ends up in a different group in Sentry.

<img width="329" alt="Screenshot 2023-03-20 at 10 04 08" src="https://user-images.githubusercontent.com/2443292/226293262-5c078313-2dc6-4c88-bf34-32881c0ef340.png">

**Comment by philipphofmann** [comment]
I now updated our sample app to also have error descriptions, see https://github.com/getsentry/sentry-cocoa/pull/2813.

Furthermore, I improved the code sample for custom error descriptions see https://github.com/getsentry/sentry-docs/pull/6495

**Comment by braker1nine** [comment]
@philipphofmann ahh thank you! I wondered where those code values were coming from. That clarifies it a little more.

One more question just for clarity. Maybe it's not this simple. I'm not sure. Are they grouped then by the enum case? Or by the description. In particular I'm wondering if I have an enum case with a somewhat dynamic description or even wrapping another error type, would I get multiple groups if they had slightly differing descriptions.

Going back to my example
```swift
enum SyncError: Error {
    case networkError(Error)
    case invalidToken
    case oopsOhNo
}

extension SyncError: CustomNSError {
    var debugDescription: String {
        switch self {
        case .networkError(let error):
            return "networkError: \(error.localizedDescription)"
        case .invalidToken:
            return "invalidToken"
        case .oopsOhNo:
            return "oopsOhNo"
        }
    }
    var errorUserInfo: [String: Any] {
        [NSDebugDescriptionErrorKey: self.debugDescription]
    }
}
```
Would I get a single networkError "issue" with them all grouped together. Or would I get one for each error description? Does that make sense?

**Comment by philipphofmann** [comment]
Thanks for asking the question. It helps us to improve our docs, @braker1nine.

The description doesn't impact grouping. Sentry will still group by enum case. I updated the docs https://github.com/getsentry/sentry-docs/pull/6524. Is it clear now?

**Comment by braker1nine** [comment]
Yep! Thank you for the clarifications! I've closed this issue because I think I've got everything I need
