### ISSUE TITLE
`testStacktraceHasFrames_forEveryThread_withStitchAsyncOn` hangs locally for iPhone simulator

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2775]
### Description

Happens when I run the test suite for the Sentry framework target against an iPhone simulator destination in Xcode 14.1, but not against macOS.

**Comment by philipphofmann** [comment]
Related to https://github.com/getsentry/sentry-cocoa/issues/1786.

**Comment by philipphofmann** [comment]
I just tried in locally, and it didn't hang for me.
