### ISSUE TITLE
Specify whether to report test failures to Sentry with environment variable

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2776]
### Description

We have two build configurations that both deal with test runs: TEST and TESTCI. The only actual difference between them is that we conditionally compile SentryTestObserver under TESTCI to send test failures to our Sentry dashboard.

I propose injecting an environment variable from xcode-test.sh to accomplish this instead of choosing one or the other build configuration.

Then we can use the two different build configurations to achieve different behaviors when running tests locally versus running tests in CI, whether those CI tests are running for a pull request or for post merge runs on the main branch.

Prior PRs that led to the current strategy: 
- https://github.com/getsentry/sentry-cocoa/pull/1815
- https://github.com/getsentry/sentry-cocoa/pull/1823

**Comment by philipphofmann** [comment]
I don't see any issues in [Sentry](https://sentry-sdks.sentry.io/issues/?project=5428557) from `SentryTestObserver`. Neither, you @armcknight nor @brustolin ever complained. I'm also not using it at the moment. Instead, of fixing it, I vote for removing the `SentryTestObserver`.

**Comment by armcknight** [comment]
I'm good with that 👍🏻

**Comment by armcknight** [comment]
I think we can keep them both and use them as I originally thought: `TEST` for local testing, `TESTCI` for GitHub actions runs, which we could maybe set through the yml specs for those by injecting into xcode-test.sh.

**Comment by philipphofmann** [comment]
But we currently don't have a use case for `TESTCI` as we removed the `SentryTestObserver`. That's why I don't understand why we should keep something we don't use at the moment.

**Comment by philipphofmann** [comment]
@armcknight, can you please reply to my question above ⬆️

**Comment by kahest** [comment]
The initial issue was solved (see https://github.com/getsentry/sentry-cocoa/issues/2776#issuecomment-1468032178). @armcknight please create a new issue for https://github.com/getsentry/sentry-cocoa/issues/2776#issuecomment-1468487628 if you believe we should do it.
