### ISSUE TITLE
enableNetworkTracking = NO still reports HTTPClientError

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2780]
### Platform

iOS

### Installed

CocoaPods

### Version

8.2.0

### Steps to Reproduce

Initialize Sentry with:

```
  [SentrySDK startWithConfigureOptions:^(SentryOptions * _Nonnull options) {
    options.enableNetworkTracking = NO;
    options.enableNetworkBreadcrumbs = NO;
```

### Expected Result

I expect not to see `HTTPClientError` reports.

### Actual Result

I get `HTTPClientError` reports.

**Comment by brustolin** [comment]
Hello @eric.
You're using the wrong setting.
`enableNetworkTracking` measures network request performance.
`enableCaptureFailedRequests` creates issues out of network request failures.
You need to disable the second one.

**Comment by kahest** [comment]
For more information please see https://docs.sentry.io/platforms/apple/configuration/http-client-errors/. If you feel this hasn't answered or addressed your reported issue, please reopen or create a new ticket.

**Comment by eric** [comment]
Great. Thanks. I was lookin for options that contained "network" somewhere in them to match the other settings.
