### ISSUE TITLE
Validate safe usage of return values of vsnprintf

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2784]
### Description

Validate that our code base doesn't use the return value of [`vsnprintf`](https://github.com/search?q=repo%3Agetsentry%2Fsentry-cocoa+vsnprintf&type=code) to determine where to null-terminate the string or to determine how many bytes to copy from the string at a later time.

[Apple Secure Coding Guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1) :
> **Security Note for snprintf and vsnprintf:** The functions `[snprintf](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/snprintf.3.html#//apple_ref/doc/man/3/snprintf)`, `[vsnprintf](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/vsnprintf.3.html#//apple_ref/doc/man/3/vsnprintf)`, and variants are dangerous if used incorrectly. Although they do behave functionally like `[strlcat](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/strlcat.3.html#//apple_ref/doc/man/3/strlcat)` and similar in that they limit the bytes written to `n-1`, the length returned by these functions is the length that would have been printed *if n were infinite*.
> 

> For this reason, you *must not* use this return value to determine where to null-terminate the string or to determine how many bytes to copy from the string at a later time.

Related security issue: [CWE-676](https://cwe.mitre.org/data/definitions/676.html).

**Comment by brustolin** [comment]
We do use the return of `vsnprintf` in here:

https://github.com/getsentry/sentry-cocoa/blob/257c2a998df2f9a0e257802d69d4268d4a83c560/Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c#L468-L478

But we also check whether the value is valid, so I believe this is safe and we could close this issue.


Thoughts @philipphofmann @armcknight ?

**Comment by philipphofmann** [comment]
If you are sure that is the only usage of the return value of `vsnprintf`, then we can close this yes, @brustolin. Thanks for looking into it.

**Comment by brustolin** [comment]
This was validate and pose no risk to the project.
