### ISSUE TITLE
More strict semver adherence

### ISSUE THREAD

**Issue by jacobhzen** [getsentry/sentry-cocoa#2787]
### Problem Statement

Could 8.3.0 have been 8.2.1? Trying to limit our versioning in order to maximize safety. We've been bitten a few times now by too aggressively upgrading Sentry and would love to see more bug-fix versions if there are no features present.

**Comment by philipphofmann** [comment]
Thanks for pointing that out, @jacobhzen. `8.3.0` should have been `8.2.1` as it only contains fixes. We are sorry about that. We will follow [semver](https://semver.org/) for the next release. cc @brustolin and @armcknight.
