### ISSUE TITLE
Danger failing on changelog check job

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2790]
### Description

Due to a 403, e.g.: https://github.com/getsentry/sentry-cocoa/actions/runs/4403587841/jobs/7712145746#step:4:58

Possibly related to https://github.com/danger/danger-js/issues/1031

**Comment by philipphofmann** [comment]
@armcknight, how often do you see this happening? What can we do to fix it?

**Comment by armcknight** [comment]
Not sure really. It actually does seem like it's running, because it left a comment on my [current PR](https://github.com/getsentry/sentry-cocoa/pull/2786) and keeps editing it. (On that PR, I actually did add a changelog entry so I'm not sure why it keeps warning about that.)

Someone mentioned it could be related to trying to edit a comment it's already left, but again that's working so I'm not sure what's up.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/3241469/225091014-a30f7932-7508-44c3-a03d-98ac4c213996.png">

The end of the linked issue mentions token permissions, maybe we need to double check whatever token we provide to it?

**Comment by philipphofmann** [comment]
> maybe we need to double check whatever token we provide to it?

Could you do that, please, @armcknight? Karl has access to the tokens, so you could ping him.

**Comment by armcknight** [comment]
It doesn't look like it's still an issue, so let's leave it for now and repoen this if it crops up again.

**Comment by armcknight** [comment]
Done @philipphofmann , sorry I missed this.

**Comment by kahest** [comment]
For danger, we use the default GITHUB_TOKEN created for workflow runs, with the [“Default access (permissive)” scope](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). Seems like some API usages of danger are not covered by this. The log output is pretty bad though - looks like it manages e.g. to update the changelog comment, but fails on some other thing with a 403.

We have 2 options:
- create a bot and use a PAT with the least permissions needed (might be a lot of trial & error, also might be that it would require permissions we don’t want to give it)
- [modify the permissions of GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) in the workflow file

We discussed to go with the second option.

**Comment by cmanallen** [comment]
I doubt this auth issue has persisted for a year without resolution.  Feel free to re-open if this was closed incorrectly.
