### ISSUE TITLE
Sentry complains missing debug info for events from DEBUG builds

### ISSUE THREAD

**Issue by prassyy** [getsentry/sentry-cocoa#2801]
### Platform

iOS

### Installed

Carthage

### Version

8.2.0 and above

### Steps to Reproduce

1. A self hosted Sentry instance
2. Run the iOS app with a build for which Debug files are not separately uploaded in Sentry. E.g a local simulator build
3. When calling the capture method `func capture(message: [String], block: @escaping (Scope) -> [Void]) -> SentryId` to record an issue, the events are not processed and we see the error "There are X issues blocking event processing". 
4. Clicking on See Details gives us "A required debug information file was missing."

### Expected Result

Sentry instance should process the events for those builds and display the stacktrace with readable symbols like it used to.

### Actual Result

In Sentry versions lower than 8.2.0 we used to see the symbols in stacktrace reasonably clear. From 8.2.0 we see the errors
- There are X issues blocking event processing. 
- A required debug information file was missing.
<img width="1075" alt="Screenshot 2023-03-16 at 00 38 30" src="https://user-images.githubusercontent.com/14272178/225469761-54b59347-9cf3-48e5-8d38-f2a7c94c5b60.png">
<img width="846" alt="Screenshot 2023-03-16 at 00 45 31" src="https://user-images.githubusercontent.com/14272178/225469764-2882847e-e540-41f6-8da9-e9c62c348739.png">

**Comment by prassyy** [comment]
Could this have something to do with this PR, that changed the debug_meta type to machO: https://github.com/getsentry/sentry-cocoa/pull/2701 ?

**Comment by philipphofmann** [comment]
When I try this a normal hosted instance I get the following error

<img width="845" alt="Screenshot 2023-03-16 at 17 14 51" src="https://user-images.githubusercontent.com/2443292/225683858-176792bd-2100-488a-a0fb-20ca2fa6a410.png">


but I still get a somewhat useful stacktrace

<img width="861" alt="Screenshot 2023-03-16 at 17 15 50" src="https://user-images.githubusercontent.com/2443292/225684132-5318aaec-cf60-40ac-896e-5ba1bfb5e593.png">

Yes, it's somewhat broken and we'll fix it, but I would be interested in your stack trace. Yes, it could be related to https://github.com/getsentry/sentry-cocoa/pull/2701.

**Comment by kahest** [comment]
The error message is shown by design now, but we should find a way to make it more actionable and to give better guidance on how to upload debug symbols.

**Comment by lvandal** [comment]
I have this issue as well but no way to remedy it. I somehow need to fix this but the error is not telling me how. Symbols have been uploaded to Sentry.

<img width="990" alt="Screenshot 2024-06-14 at 10 58 22 AM" src="https://github.com/getsentry/sentry-cocoa/assets/157723/c62eeb43-c6aa-4593-98b4-5850ce04abe4">

**Comment by philipphofmann** [comment]
@lvandal, we didn't tackle the underlying issue (https://github.com/getsentry/sentry/issues/47323) yet. You can try to use `sentry-cli debug-files find` as pointed out in https://github.com/getsentry/sentry-docs/issues/6721 to solve your problem maybe.

**Comment by YagnikBavishi04** [comment]
@philipphofmann I have facing the same issue related **A required debug information file was missing (1)**. I have tried to upload log details using [Xcode Build Phase](https://docs.sentry.io/platforms/apple/guides/macos/dsym/#xcode-build-phase) but the logs are not uploaded properly. Also, I have lower down my pod version to 7.31.5 in that case warning is gone but logs are not uploded. Is there any other way we can fixes this issue in letest version?

**Comment by philipphofmann** [comment]
You don't need to change the pod version for the debug symbol files. The sentry-cocoa SDK doesn't upload them. Instead, you can either use sentry-cli of our fastlane plugin: https://docs.sentry.io/platforms/apple/guides/macos/dsym/#xcode-build-phase. Do you get an error message or something, @YagnikBavishi04?

**Comment by YagnikBavishi04** [comment]
@philipphofmann  We have followed the same steps as mentioned in https://docs.sentry.io/platforms/apple/guides/macos/dsym/#xcode-build-phase but we are getting an error while sharing archives with others, an error message **A required to debug information file was missing (1)**.  When we build an app using XCode it works fine and we do not get any errors related to missing dSYM files.

**Comment by philipphofmann** [comment]
@YagnikBavishi04, you should be able to upload the dSYMS of the archive by uploading the dSYMS with sentry-cli for it. Something like 
```
sentry-cli debug-files upload --auth-token "Your auth token" \
  --org your-ord \
  --project your-project \
  PATH_TO_ARCHIVE
```
