### ISSUE TITLE
Add support for changing the log level of a AppHang event

### ISSUE THREAD

**Issue by CraigSiemens** [getsentry/sentry-cocoa#2817]
### Problem Statement

Currently all AppHangs are reported with the level `error`. For our app, this level is higher than we'd like it to be for a couple reasons.
- Many hangs we're receiving are out of our control. Our most common ones are from the keyboard and share sheets waiting on a response from an XPC connection.
- 
- It complicates to updating and maintaining our integrations that alert on errors to specifically ignore AppHangs.

### Solution Brainstorm

1. Add a property to `Sentry.Options` to set the log level that should be used of app hang events.
2. Add a more convenient way for `beforeSend` to detect an app hang event. Currently it requires going through multiple fields an using a hard coded string based on the ANR implementations.
```swift
let isAppHang = event.exceptions?.contains { $0.mechanism?.type == "AppHang" }
?? false
```

### Are you willing to submit a PR?

Yes

**Comment by brustolin** [comment]
Thanks @CraigSiemens to point this out. We gonna discuss this within the team. Unfortunately I cant give you an ETA.

**Comment by dmregister** [comment]
We are interested in this as well. Given that all "App Hangs" are reported as an error, is there anyway to know if an app hang resulted in watchdog or the user killing the app?

For instance, though I hate to compare this to another product, [this is the functionality](https://docs.bugsnag.com/platforms/ios/reporting-app-hangs/#fatal-app-hangs) we were interested in when we were comparing products.

**Comment by philipphofmann** [comment]
There is a workaround to change the level in `beforeSend` with something like
```Swift
let isAppHang = event.exceptions?.contains { $0.mechanism?.type == "AppHang" }
```

We don't see a high demand for this feature at the moment, and therefore we don't have plans to implement it or accept a PR. If you still want this feature please upvote, and we can reconsider.
