### ISSUE TITLE
We are facing a lot of SDK crashes that have occurred after upgrading to version 8.x.x.

### ISSUE THREAD

**Issue by zhgchgli0718** [getsentry/sentry-cocoa#2832]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.3.1

### Steps to Reproduce

unknown, seem to be random crashes.

### Expected Result

The app was stable before we updated to version 7.3.1, but we're experiencing issues now.

Our current crash-free rate is around `98.X%`, which is lower than our previous rate of `99.98%` before we upgraded the SDK version. :(

### Actual Result

We have received a lot of fatal issues as shown below, but unfortunately, the crash log doesn't provide any useful information, and we have no idea how to fix it:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/33706588/227419180-75300fe5-565b-46e2-8e52-bdc42cedd22a.png">

### EXC_BAD_ACCESS
Exception 1, Code 1, Subcode 0 > Attempted to dereference null pointer.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/33706588/227418832-544b34db-df4d-40f2-8e3a-c3813aadb797.png">

### EXC_BAD_ACCESS -> The most one
3c8a24d6f isn't waiting on children and needs idle timeout dispatched. >
KERN_INVALID_ADDRESS at 0xc41c9bf20.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/33706588/227418705-ddc7bf62-672c-4d81-a0b7-4d47ef9cae1d.png">

---

- While we can't be sure that the Sentry SDK is responsible for all of our crashes, we have received many similar crashes since upgrading to version 8.x.x.
- We noticed that upgrading to the latest SDK version helped to reduce the crash rate
- We also found an interesting message in the crash logs that said 'isn't waiting on children and needs idle timeout dispatched' this messsage which is actually came from the Sentry SDK

As mentioned above, we believe that this message is related to the SDK and may be the source of the problem, If there is anything we can do to help, please let us know.

### Are you willing to submit a PR?

yes

**Comment by philipphofmann** [comment]
This could be related to https://github.com/getsentry/sentry-cocoa/issues/2769.
