### ISSUE TITLE
SentryJavaScriptBridgeHelper.m is ignoring 'environment' property

### ISSUE THREAD

**Issue by erlendfh** [getsentry/sentry-cocoa#285]
https://github.com/getsentry/sentry-cocoa/blob/930720b95a78f92fd4b33793acece5e4935c99ce/Sources/Sentry/SentryJavaScriptBridgeHelper.m#L120

Somewhere around here I would have expected to find 
```
    if (jsonEvent[@"environment"]) {
        event.environment = jsonEvent[@"environment"];
    }
```

Has this been left out on purpose or can it just be added?

**Comment by HazAT** [comment]
Thanks for making the PR
