### ISSUE TITLE
Migrate from `xcode-install`

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2862]
### Description

We use [`xcode-install`](https://github.com/xcpretty/xcode-install) to install some older iOS simulators for test runs [here](https://github.com/getsentry/sentry-cocoa/blob/ff5c1d83bf601bbcd0f5f1070c3abf05310881bd/.github/workflows/test.yml#L174) and [here](https://github.com/getsentry/sentry-cocoa/blob/ff5c1d83bf601bbcd0f5f1070c3abf05310881bd/.github/workflows/test.yml#L343)

That project is being sunset, so we'll have to upgrade to the recommended fastlane [xcodes](https://github.com/RobotsAndPencils/xcodes) tool or other alternative. See https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md

**Comment by philipphofmann** [comment]
Thanks for pointing that out @armcknight 👍.
