### ISSUE TITLE
Issue reports show only a part of userInfo

### ISSUE THREAD

**Issue by krotoff** [getsentry/sentry-cocoa#2878]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.3.3

### Steps to Reproduce

1. Create NSError manually with userInfo, contains `["instance": String(describing: object), "function": function, "comment": comment, "type": "manual", "property1": 1, "property2": "some string"]`
2. Send it to Sentry

### Expected Result

Issue Report shows all properties of userInfo from the example

### Actual Result

Issue Report shows only 3 first properties of userInfo from the example

**Comment by philipphofmann** [comment]
@krotoff, why did you close the issue? Did you solve your problem?

**Comment by krotoff** [comment]
Hello @philipphofmann 

Yes, I solved it. It was my blindness, 'cause I used the wrong error.

Sorry for spoiled stats with extra issue

**Comment by philipphofmann** [comment]
No worries, I'm glad it works now 😃.
