### ISSUE TITLE
'NSError+SimpleConstructor.h' file not found

### ISSUE THREAD

**Issue by gouravgupta72** [getsentry/sentry-cocoa#288]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? swift 3.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.3**

---
I have following issue:

Description goes here ...
'NSError+SimpleConstructor.h' file not found issue is coming while adding framework using cocoa

**Steps to reproduce:**
- Pod install 
**Actual result:**

**Expected result:**

**Comment by HazAT** [comment]
Can you try to use the latest version `4.2.1`?

**Comment by gouravgupta72** [comment]
I tried still the same error.

**Comment by HazAT** [comment]
Did you try to make a full clean build? I can't reproduce this problem.
Also CI didn't say anything.
Are you upgrading from an older version?

**Comment by gouravgupta72** [comment]
I tried full clean build, and this is the first time i'm trying to use sentry.

**Comment by gouravgupta72** [comment]
I found that this file is already available in one of my POD library.
It could be the issue. If yes is there any way to over come this.

**Comment by HazAT** [comment]
Oh, ok that could be the case. The error message is definitely misleading then ^^
We can rename the category and prefix it with `Sentry`, should be an easy fix.

**Comment by gouravgupta72** [comment]
Thanks,

Can you give any time frame for that, coz we are waiting to use this in our product since 2 months.

**Comment by HazAT** [comment]
Working on a fix.

**Comment by gouravgupta72** [comment]
Thanks for the quick fix,

There is one more library which is used by KSCrashAblyFork as well with same name

Container+DeepSearch.h

Can you guys fix that one as well.

Thanks

**Comment by HazAT** [comment]
xD
Will do.

**Comment by HazAT** [comment]
`4.3.1` should fix your issue
