### ISSUE TITLE
I have an app that integrates our own SDK and when there's a crash in the SDK, I'm only seeing redacted

### ISSUE THREAD

**Issue by ima-tech** [getsentry/sentry-cocoa#289]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:
I have an app that integrates our own SDK and when there's a crash in the SDK, I'm only seeing redacted.

I'm guessing that since I also install my own SDK using Carthage, that Sentry cannot resolve the symbols and/or the DSYM file. What should I do?

Should I?:
* Add a build step to my SDK's project to send the DSYM file to the different sentry projects that integrate the SDK?
* Integrate Sentry and start the crash handler in the SDK as well as in the applications (I'm guessing this will cause some conflicts)
* Upload for each app the SDK's DSYM built from Carthage to the apps' Sentry projects

Or something else?

**Comment by philipphofmann** [comment]
This issue is pretty old. We are already on v 6.x.x. If you still experience the issue @ima-tech, please add more info on this ticket or open up a new issue.
