### ISSUE TITLE
Change `Client` to `Sentry` for naming conventions.

### ISSUE THREAD

**Issue by santiagoprieto** [getsentry/sentry-cocoa#293]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.3.1**

---
**I have following issue:**
Hi! I just installed the Sentry SDK and it's all working well. I use Sentry in other platforms and love it so I'm sure it will be great for iOS as well! 

My issue pertains to naming conventions. Your SDK uses `Client` as the class name for initializing Sentry. This can be a big problem because `Client` is normally used for e-commerce sites as the user's name. It is also used internally in many other cases.

I would suggest using something less generic like `Sentry` or `SentrySystem` or even `SentryClient` so that there are no compatibility issues AND so that the code is understood more easily. When I see `Client` in there I can't tell to what it pertains. 

Also... I just encountered the same with your `User` where this naming will surely conflict with many people's local naming. I suggest `SentryUser` or something similar.

Anyway, great work with the SKD!

**Comment by HazAT** [comment]
Hey, thanks for the Feedback.
So you should be able to use namespaced names for all Sentry related classes like `Client` and `User`.

```swift
Sentry.Client.shared = try Sentry.Client(dsn: "DSN")
try Sentry.Client.shared?.startCrashHandler()
let user = Sentry.User(userId: "1234")
user.email = "hello@sentry.io"
Sentry.Client.shared?.user = user
```

Hope this helps :)
