### ISSUE TITLE
Files missing in v4.3.1 cocoapod?

### ISSUE THREAD

**Issue by lschwe** [getsentry/sentry-cocoa#295]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
trying to go from **4.1.0** to **4.3.1**

---
I have following issue:
Im trying to update the pod to v4.3.1, to see if it improves uploading symbols (im debugging information even thought all the dSYM files needed are already uploaded), but unfortunately v4.3.1 wont build successfully like v4.1.0.

**Steps to reproduce:**
- Update Podfile from: `pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'` to `pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.3.1'`

**Actual result:**
- I get the following compiling errors:
```
.../Pods/Sentry/Sources/Sentry/include/NSDictionary+Sanitize.h: No such file or directory
.../Pods/Sentry/Sources/Sentry/include/NSDate+Extras.h: No such file or directory
.../Pods/Sentry/Sources/Sentry/include/NSData+Compression.h: No such file or directory
...//Pods/Sentry/Sources/SentryCrash/Reporting/Filters/Tools/Container+DeepSearch.h: No such file or directory
```

**Expected result:**
- v4.3.1 should build fine like the v4.1.0 did. Especially since there is no migration necessary or anything like that. 
- Also Im wishfully hoping this would fix the "A required debug information file was missing" errors on the Sentry dashboard.

**Comment by HazAT** [comment]
Did you do a clean build? These files got renamed.

**Comment by lschwe** [comment]
O shoot. thanks @HazAT
