### ISSUE TITLE
Would like to add switches to make `attachScreenshot` and `attachViewHierarchy` applicable to user feedback.

### ISSUE THREAD

**Issue by rakuyoMo** [getsentry/sentry-cocoa#2962]
### Problem Statement

In the current version, if you want to use the attachScreenshot and attachViewHierarchy properties while reporting user feedback, you can only do it via capture(error:) (I can change the level to info)

However, reporting user feedback via the capture(message:) method should be a better option.

I would like attachScreenshot and attachViewHierarchy to work for user feedback.

### Solution Brainstorm

Or we could add an attribute, e.g. "alwaysCarryAttachments", to give the user the choice of whether to upload attachments or not.

Only very minor changes to `SentryScreenshotIntegration` and `SentryViewHierarchyIntegration` are required. Other platforms should be similar.
### Are you willing to submit a PR?

Yes, but only for iOS and Android platforms.

**Comment by brustolin** [comment]
I think the easier solution would be to have a property in SentryEvent to indicate the need of capturing the screen, and then it would be possible to use `SentrySDK.captureEvent`


Thanks for opening this. We will discuss it and get back to you.

**Comment by rakuyoMo** [comment]
> I think the easier solution would be to have a property in SentryEvent to indicate the need of capturing the screen, and then it would be possible to use `SentrySDK.captureEvent`
> 
> Thanks for opening this. We will discuss it and get back to you.

Yes, we can add the property to the SentryEvent object and it feels better to do so.

**Comment by philipphofmann** [comment]
@rakuyoMo, this issue will be solved once we finish https://github.com/getsentry/sentry-cocoa/issues/3007. We can't give you an ETA for it, but we will close this issue here to avoid duplication.
