### ISSUE TITLE
Duplicate HTTP breadrumbs

### ISSUE THREAD

**Issue by looneytsci** [getsentry/sentry-cocoa#2971]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.3.2

### Steps to Reproduce

1. enable network breadcrumbs
2. make fatal error

Similar events were caught on iOS 14.8/14.8.1 only with crashes

<img width="872" alt="Снимок экрана 2023-04-27 в 14 42 15" src="https://user-images.githubusercontent.com/82817544/234852048-7ab4016d-b06b-4125-b221-e57344095954.png">

### Expected Result

Similar HTTP Requests breadcrumbs appear once

### Actual Result

Similar HTTP Requests breadcrumbs appear twice

**Comment by looneytsci** [comment]
Hello, I have checked with Proxyman that we make only one request, so It could not be duplicated by requests. I could not reproduce this issue too, but on prod env we are getting such problems. It looks similar with this [issue](https://github.com/getsentry/sentry-react-native/issues/1409)

**Comment by looneytsci** [comment]
this issue does not have a 100% chance of reproducing

**Comment by philipphofmann** [comment]
@looneytsci, thanks for the update. Does it only happen for HTTP requests or also other breadcrumb types?

**Comment by philipphofmann** [comment]
Again @looneytsci, I'm not able to reproduce your problem. Thanks for pointing out https://github.com/getsentry/sentry-react-native/issues/1409, but the problem there was that all breadcrumbs were duplicated. I doubt we have a similar problem in how we attach the breadcrumbs, as this problem only happens for network breadcrumbs. Can you maybe check timestamps of the breadcrumbs of the event JSON? You can do this by clicking on the JSON button of an event
<img width="1262" alt="Screenshot 2023-05-02 at 14 17 38" src="https://user-images.githubusercontent.com/2443292/235663942-86d50ec8-6d70-4438-b576-281f6d762be6.png">

The JSON looks something like this:
```json
"breadcrumbs": {
  "values": [
    {
      "timestamp": 1683029337.71,
      "type": "debug",
      "category": "started",
      "level": "info",
      "message": "Breadcrumb Tracking"
    },
    {
      "timestamp": 1683029337.737,
      "type": "navigation",
      "category": "device.orientation",
      "level": "info",
      "data": {
        "position": "portrait"
      }
    }
  ]
}
```

If the timestamps are the same, we know they are duplicate breadcrumbs. If they are different, we know that the SDK created two.

Furthermore, if you could somehow reproduce this, it would be great if you could attach your debugger in SentryNetworkTracker, as it adds network breadcrumbs here:

https://github.com/getsentry/sentry-cocoa/blob/14a11017fca0d2f366ade2bd13bb35be7fcecdc8/Sources/Sentry/SentryNetworkTracker.m#L415-L444

**Comment by alex93133** [comment]
@philipphofmann same one
<img width="381" alt="1" src="https://user-images.githubusercontent.com/58854670/235879706-cc1641f7-81a5-4772-9755-54c29a311cea.png">

**Comment by looneytsci** [comment]
timestamps are the same

**Comment by philipphofmann** [comment]
Thanks, @looneytsci and @alex93133, for the update. @alex93133 do you also only experience this for HTTP breadcrumbs?

**Comment by philipphofmann** [comment]
I found a possible cause for this problem. We swizzle the `setState` of `NSURLSessionTask` here https://github.com/getsentry/sentry-cocoa/blob/fd6a31ce3940224432d2ece19de8c052bec3c3d2/Sources/Sentry/SentryNetworkTrackingIntegration.m#L72-L78

If the `NSURLSessionTask` sets the state twice in a row to `NSURLSessionTaskStateRunning`, we could end up creating two breadcrumbs and also possibly capture two failed requests.

https://github.com/getsentry/sentry-cocoa/blob/fd6a31ce3940224432d2ece19de8c052bec3c3d2/Sources/Sentry/SentryNetworkTracker.m#L275-L278

@brustolin, as you wrote most of the network tracking logic, does this sound plausible to you? If yes, debounce mechanism or something similar could help us to solve this problem.

**Comment by brustolin** [comment]
@philipphofmann  It does make sense, theoretically its possible. I never saw NSURLSession doing this, but our code it is open to this possibility.
