### ISSUE TITLE
Fix navigation breadcrumb

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2978]
### Description

Currently we're using `viewDidAppear` to create a navigation breadcrumb.
https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/SentryBreadcrumbTracker.m#L193-L222

This is a problem because multiple view controllers in the same screen would trigger multiple navigation breadcrumbs, which is not accurate. 

We should track UINavigationController pushs an pops, and UITabViewController changes.

**Comment by philipphofmann** [comment]
This aligns with the behavior of Android. It's supposed to be this way. We never had any complaints about this behavior. So let's keep it.

iOS
<img width="1265" alt="Screenshot 2023-05-03 at 14 44 48" src="https://user-images.githubusercontent.com/2443292/235919645-516fb4de-85bf-44a0-a53e-8924b53bcbe1.png">

Android
<img width="1268" alt="Screenshot 2023-05-03 at 14 45 12" src="https://user-images.githubusercontent.com/2443292/235919767-ad601533-3ba2-47b3-bd24-273907c6536b.png">
