### ISSUE TITLE
Does not build on Xcode 10.2

### ISSUE THREAD

**Issue by hannseman** [getsentry/sentry-cocoa#298]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> **5.0**
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage (**0.32.0**)
- [ ] Manually

Version of sentry-cocoa:
**4.3.1**

---
I have following issue:

Does not build with Xcode 10.2

**Steps to reproduce:**
Create a `Cartfile` with the following content:
```
github "getsentry/sentry-cocoa" ~> 4.3
```

Then run:
`carthage update --platform iOS --no-use-binaries`

**Actual result:**
```
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'CrashLibiOS')
** ARCHIVE FAILED **
```

**Expected result:**
Build succeeds.

**Comment by zachwaugh** [comment]
I was seeing the same issue and noticed it was failing on building a project within `Sources/KSCrash`, which doesn't exist anymore. Appears it was a submodule removed a few months back - https://github.com/getsentry/sentry-cocoa/commit/db259bad0e5c576bc74c5593646dd9caaf6022ef. Removing `Carthage/Checkouts/sentry-cocoa` and doing another `carthage update` fixed it for me. I didn't dig much further, but possibly a Carthage bug with removing submodules

**Comment by hannseman** [comment]
@zachwaugh you're right! Thank you very much for pointing this out. Closing this issue.
