### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by vaibhavTM** [getsentry/sentry-cocoa#2980]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

Just run the app

### Expected Result

No memory leaks.

### Actual Result

<img width="1368" alt="Screenshot 2023-05-02 at 2 29 56 PM" src="https://user-images.githubusercontent.com/83169376/235624692-aea6ee96-8e93-4aa0-ab90-473d628a6dd6.png">

### Are you willing to submit a PR?

No

**Comment by brustolin** [comment]
Thanks @vaibhavTM for reaching out. We going to investigate this.

**Comment by vaibhavTM** [comment]
Thankyou @brustolin  for quick response.

**Comment by brustolin** [comment]
Hello @vaibhavTM.
I experience a few leaks when profiling is enabled (@armcknight can you check this?).
But In the latest version of the SDK I could not produce any of the leaks in your screenshot.

Can you update your Sentry SDK version and let us know please?

**Comment by vaibhavTM** [comment]
Okay.

**Comment by brustolin** [comment]
Out of curiosity I tried the SDK 8.1 and I was able to see the leaks.
So, Im confident that the leaks in the screenshot are fixed. 

We need to fixed leaks regarding profiling tho.

**Comment by philipphofmann** [comment]
@vaibhavTM, try run `pod repo update` and try again, please.

**Comment by armcknight** [comment]
Thanks for writing in @vaibhavTM . I'm looking at the possible leaks from the profiler now. I tried an instruments run with our Swift-iOS test app, and started a manual transaction with profiling and let it go until the profiler timed out. There are some symbols for me to investigate related to profiling: 
<img width="1112" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3241469/c7ace62b-8364-4843-b08b-69bcc00508e5">

I hope to get updates on this today.

**Comment by vaibhavTM** [comment]
@armcknight okay.

**Comment by indragiek** [comment]
@armcknight @brustolin I made some progress tracking this down. Basically what appears to be happening is that we're capturing `SentryProfilingState` (previously just a bunch of arrays/dictionaries, but same idea) in the `std::function` that we pass to the `SamplingProfiler` initializer, but that captured `state` is never deallocated. It's not clear what's holding the reference to it - in the Xcode memory graph it looks like this:

<img width="1550" alt="CleanShot 2023-05-15 at 23 45 20@2x" src="https://github.com/getsentry/sentry-cocoa/assets/353158/10826eec-5061-4abb-b852-59789bd40f8c">

Some memory that we can't identify (represented by the `malloc`) is holding a ref to it. I still have to dig deeper on this but if you have time to take a look this would be where to focus - I think it might be some weirdness with how C++ holds references to Objective-C objects.

**Comment by indragiek** [comment]
#3055 fixes all of these except for 1 leak

**Comment by indragiek** [comment]
@vaibhavTM We are cutting a new release with this fix soon.

**Comment by brustolin** [comment]
This was solved in 7.8.3
