### ISSUE TITLE
Sentry seems to cause crash at random points

### ISSUE THREAD

**Issue by hyouuu** [getsentry/sentry-cocoa#3002]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.5.0

### Steps to Reproduce

No specific repros but crash happened at different places, usually 3-5 secs after some user actions

### Expected Result

No crash

### Actual Result

Crash with the following stack:

![screenshot_2023-05-04_at_12 35 21_am_720](https://user-images.githubusercontent.com/5061867/236272252-5962e9ba-dfe0-4b19-86a5-be23ac4f3f00.png)

### Are you willing to submit a PR?

No plan

**Comment by philipphofmann** [comment]
@hyouuu, I'm sorry about that. What is the error message of the crash? To prevent such crashes from happening disabling `options.enableUserInteractionTracing = false` should help.

**Comment by brustolin** [comment]
Hello @hyouuu
Thanks for the stack trace. Do you also have the error message?

**Comment by hyouuu** [comment]
@philipphofmann we don't have any other information than the crash stack trace. Have you gotten other reports of user interaction tracing caused crashes?

**Comment by philipphofmann** [comment]
@hyouuu, no, we don't have other reports at the moment, but only the `enableUserInteractionTracing` leads to the stack trace you pointed out.

**Comment by AndrewSB** [comment]
we've disabled that option, we'll let you know if we see any other crashes in sentry

**Comment by philipphofmann** [comment]
More stacktraces can be found here https://github.com/getsentry/sentry-cocoa/issues/3032.
