### ISSUE TITLE
Capture Screenshot and ViewHierarchy for single events

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3007]
### Description

We could add an API similar to the following:
```Swift
Attachment.captureScreenshot()
Attachment.captureViewHierarchy()
```

Then users could use the local scope to capture screenshots and view hierarchy for single events like this
```Swift
SentrySDK.captureMessage(message: "my message", block: { scope in
	scope.addAttachment(Attachment.captureScreenshot())
})
```

Consider creating issues for all mobile platforms to have a consistent API.

Also, update the docs:

1. https://docs.sentry.io/platforms/apple/enriching-events/attachments/
2. https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/screenshots/https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/viewhierarchy/

Please upvote if you want this feature.

**Comment by rakuyoMo** [comment]
This feature is still important to me, and I understand that it seems like there are already other implementations for other platforms, but only iOS doesn't have it yet? If so that's pretty bad, looking forward to seeing it on iOS soon.

**Comment by kahest** [comment]
Hi @rakuyoMo - this specific feature is generally not available yet. We use this issue to track demand and might bump priority if it receives more upvotes.

On other platforms, `Hints` can be used to conditionally send Screenshots and/or View Hierarchies by filtering based on `Hints` in `beforeSend`. We have an issue open for implementing `Hints` on `sentry-cocoa`: https://github.com/getsentry/sentry-cocoa/issues/2325

**Comment by kahest** [comment]
Related issue to add a `beforeCapture` callback: https://github.com/getsentry/sentry-cocoa/issues/3137

**Comment by cmanallen** [comment]
This closed: https://github.com/getsentry/sentry-cocoa/issues/3137
