### ISSUE TITLE
App hanging events should have the current view controller in the name

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-cocoa#3029]
### Problem Statement

In order to have an easier time figuring out where the app hanging events come from, they should have their current page in the name. So instead of having a lot of `App Hanging` there should be `App Hanging on SettingsViewController` or `App Hanging on CheckoutViewController` or something like that.

### Solution Brainstorm

Add current ViewController name to the description.

For cross platform frameworks like Flutter or ReactNative, the name should come from the the respective SDKs, since it's probably always the same on Flutter apps for example.

### Are you willing to submit a PR?

No

**Comment by brustolin** [comment]
Thanks @ueman for this suggestion.
The problem is that UIKit has no concept of "current UIViewController".
But we can try an heuristic approach, which would be able to detect the "current" UIViewController in most cases.

**Comment by philipphofmann** [comment]
The app hang events have breadcrumbs for the UIViewControllers. Aren't they enough for your use case, @ueman? If not, please elaborate.

**Comment by ueman** [comment]
I would like to be able to group those app hangs, and I would like to be able to glance at least somewhat from which area the issues are coming without having to open each one. This would help with triaging those events, as the severity and impact is much clearer just from the name of them.

The generic description of those events are making those events look like noise. I've also noticed my coworkers being confused about them not being grouped, because they have the same name and sometimes an identical preview in list on the overview.

Just for some more context: I'm a user of this via the Flutter SDK.
