### ISSUE TITLE
Unable to set event title

### ISSUE THREAD

**Issue by sashabaranov** [getsentry/sentry-cocoa#304]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes → 4.2, 5
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
4.1.0

---
I have following issue:
All events I send to sentry are displayed as `<unlabeled event>`, I've compared event JSONs between different projects and it seems that sentry-cocoa does not set title field. Digging source code confirms it.

**Comment by HazAT** [comment]
Hey, can you please post a link to an issue in sentry.io ?

**Comment by sashabaranov** [comment]
Would the event id be sufficient? 34f77cef9e8a4f698a49f624bdd6d150

Here is a code to reproduce such behaviour:

```swift
import Sentry


func sendToSentry(_ error: Error?, _ msg: String) {
    let evt = Event(level: SentrySeverity.error)
    evt.extra = [
        "error": error?.localizedDescription ?? "nil error",
        "message": msg
    ]
    Client.shared?.send(event: evt, completion: nil)
}
```

**Comment by HazAT** [comment]
You need to set the message on the event directly:
```swift
evt.message = "msg"
```
This is expected behavior if you are not setting an `evt.exception` or `evt.message`
