### ISSUE TITLE
Investigate performance of `symbolicate_internal`

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#3043]
### Description

A user reported this at [twitter](https://twitter.com/chrisvasselli/status/1659460805853847553?s=20): 
![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/9d47496b-cba2-44ee-bd2d-09e151627326)

![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/3c4c9fd3-f0e7-4fa3-bdf3-3161243fb62a)

We should consider improvements to the symbolicate process.

**Comment by chrisvasselli** [comment]
@brustolin I tried disabling Core Data tracing and the impact mostly went away, but I was still seeing some impact from NSData swizzling, also via symbolicate_internal. I disabled enableFileIOTracing as well, and now I don't see any significant impact. And when I filter for symbolicate_internal, I don't see any calls to that, even after navigating through most of the common workflows in my app.

**Comment by chrisvasselli** [comment]
Diving into symbolicate_internal, it's mostly `findClosestSymbol`
![CleanShot 2023-05-19 at 17 02 17@2x](https://github.com/getsentry/sentry-cocoa/assets/227043/a85ac1d3-d769-4e0e-a32a-154a74be3d9d)

**Comment by chrisvasselli** [comment]
Here is that trace
[sentry-iphone-x.trace.zip](https://github.com/getsentry/sentry-cocoa/files/11514835/sentry-iphone-x.trace.zip)

**Comment by brustolin** [comment]
So, after a little bit more investigation I realize this is happening because we added a new feature that flags performance issues (I understand the irony).
Since you're doing IO and core data operations in the main thread, we need to symbolicate the stack trace to show you where this operations are happening.

**Comment by brustolin** [comment]
Thanks @chrisvasselli for all the information, we gonna work to improve this.

**Comment by chrisvasselli** [comment]
Happy to help! If there's anything else I can provide just let me know.

**Comment by brustolin** [comment]
>Since you're doing IO and core data operations in the main thread, we need to symbolicate the stack trace to show you where this operations are happening.

Which means that if you move these operations to a background thread, symbolication won't occur.

**Comment by chrisvasselli** [comment]
Yeah, that makes sense. Unfortunately it's a 10-year old app with lots of I/O on the main thread. A good goal to move it off, but not practical in the short term unfortunately.

**Comment by brustolin** [comment]
>Diving into symbolicate_internal, it's mostly findClosestSymbol

`dladdr` is a system function, we have no control over it.

My suggestion to improve this is to capture the stack trace addresses, but only symbolicate it later, before sending the event to Sentry, that happens on a background thread.

**Comment by philipphofmann** [comment]
Thanks for the input, @chrisvasselli. I'm worried about the experience for users trying Sentry for the time. They most likely do that in development with debug builds. If their first stacktraces in Sentry look cryptic, it's not the best experience.

**Comment by chrisvasselli** [comment]
Yeah, I'm coming from Crashlytics which only does server-side symbolication, so honestly until this conversation I didn't realize that it was doing client-side symbolication as well! But agreed that the client-side symbolication would make for a better first time experience.
