### ISSUE TITLE
Option to make start up crash reporting non-blocking

### ISSUE THREAD

**Issue by threema-jarem** [getsentry/sentry-cocoa#3044]
### Problem Statement

https://github.com/getsentry/sentry-cocoa/pull/2220 introduced a feature to report crashes on the main thread if they were considered to be start up crashes. This in turn causes `beforeSend` of `Sentry.Options` to run on the main thread as well.

Our implementation requires user interaction before sending any crash reports which is currently implemented by blocking the thread `beforeSend` is running on. This doesn't work if it is running on the main thread.

### Solution Brainstorm

An option to make start up crash reporting non-blocking / best effort would solve our issue.

### Are you willing to submit a PR?

We'd be happy to submit a PR

**Comment by philipphofmann** [comment]
The purpose of start-up crashes is that the SDK init waits synchronously for up to 5 seconds to flush out events if the app crashes within 2 seconds after the SDK init to ensure sending a crash report before your app crashes again. Making it asynchronous doesn't make any sense for this feature, as it's basically disabling it. Anyways, maybe you could find a workaround by grabbing the event from `beforeSend` and return `nil`, so it doesn't get sent, store it in memory and once you get the confirmation, call `captureEvent`, which is basically disabling the feature with a workaround. Another idea would be to add an option to disable this feature. What would work for you, @threema-jarem?
