### ISSUE TITLE
Option to not add CPU state from registers to crash report

### ISSUE THREAD

**Issue by threema-jarem** [getsentry/sentry-cocoa#3045]
### Problem Statement

For our crash analysis, it is sufficient to have the back trace for a given crash, and we do not need the CPU state read out from the registers. In order to not keep more data than necessary, we don't want the registers to be part of our crash reports.
At the moment we maintain a patch that simply removes the relevant lines, but it would be great to be able to upstream this.

### Solution Brainstorm

We could add an option which skips this line https://github.com/getsentry/sentry-cocoa/blob/98713e686d91e6b883edd404dc9b7dbc982abf67/Sources/SentryCrash/Recording/SentryCrashReport.c#LL1091C16-L1091C16

### Are you willing to submit a PR?

We'd be happy to submit a PR

**Comment by philipphofmann** [comment]
@threema-jarem, you can drop the registers or any other unwanted data in [beforeSend](https://docs.sentry.io/platforms/apple/configuration/filtering/#using-platformidentifier-namebefore-send-) with something like 
```Swift
options.beforeSend = { event in
    event.threads?.forEach { $0.stacktrace?.registers = [:] }
    return event
}
```

We don't plan on adding an option for only dropping register data, as we would have to add dozens of them.

If you can't solve your use case with `beforeSend`, please reopen the issue with an explanation.
