### ISSUE TITLE
SentryBreadcrumb description crash

### ISSUE THREAD

**Issue by jadenQue** [getsentry/sentry-cocoa#3048]
### Platform

iOS

### Installed

CocoaPods

### Version

8.6.0

### Steps to Reproduce

just cold start and the App crash
please help with this crash, Thanks.

<img width="1472" alt="截屏2023-05-22 15 07 43" src="https://github.com/getsentry/sentry-cocoa/assets/134045713/2077fcd5-36d0-45d4-aef1-5a2ccc16a27a">

### Expected Result

no crash

### Actual Result

signal SIGABRT

**Comment by brustolin** [comment]
Hello @jadenQue thanks for reaching out.

I could not reproduce the problem. Do you have any special configuration for your project? Can you reproduce this problem in a clean new project?

Can you share your Sentry initialization options?
Also, it would help if you turn enable debug and share the log output.
Like this:

```swift
SentrySDK.start { options in
    //...
    options.debug = true
}
```
