### ISSUE TITLE
Error building Sentry 4.3.3

### ISSUE THREAD

**Issue by schjonhaug** [getsentry/sentry-cocoa#305]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 5
- [ ]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.3.3**

---
I have following issue:

Trying to update from 4.3.2 to 4.3.3, and I get the following errors when building:

`'SentryNSUIntegerValue.h' file not found`
`Could not build Objective-C module 'Sentry'`

It works as excepted in 4.3.2, and I have not changed anything else in my app. I did try to clean before build.

**Steps to reproduce:**
- Update from 4.3.2 to 4.3.3

<img width="375" alt="Skjermbilde 2019-04-23 kl  14 39 55" src="https://user-images.githubusercontent.com/84225/56581688-cccdf580-65d5-11e9-8d2f-a1c95ba517b0.png">
<img width="830" alt="Skjermbilde 2019-04-23 kl  14 40 11" src="https://user-images.githubusercontent.com/84225/56581675-c5a6e780-65d5-11e9-94f4-e59528fb1e2b.png">
<img width="790" alt="Skjermbilde 2019-04-23 kl  14 40 22" src="https://user-images.githubusercontent.com/84225/56581682-c93a6e80-65d5-11e9-916c-d2419c639a8a.png">

**Comment by HazAT** [comment]
The linked PR should fix it, will make a new release `4.3.4` today that should fix it.
