### ISSUE TITLE
Handle underlyingError property from NSError

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#3063]
### Description

We should add the `underlyingError` of an NSError to the event exception list as defined by the [documentation](https://develop.sentry.dev/sdk/event-payloads/exception/).

**Comment by armcknight** [comment]
I have a first pass at a solution in #3230, but i'm not sure if they're being serialized the right way. I don't really understand where they're supposed to go, just reading the docs–it's not clear to me where they should go and there is no example.

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/sentry-cocoa/pull/3230.
