### ISSUE TITLE
Crash report is not being sent - app just freezes and doesn't crash.

### ISSUE THREAD

**Issue by hanabrychtova** [getsentry/sentry-cocoa#307]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.3.3**

---
**I have following issue:**
App freezes instead of crashing - and crash report is not being sent.
I tried sending events and it works fine, so is uploading debug symbols.
When the debugger is attached the app crashes as expected.

**Steps to reproduce:**
- Add the client setup to the AppDelegate
- Add the Client.shared?.crash() code to exec after a button is tapped
- Build the app, detach debugger 
- Restart app and tap the crash button

**Actual result:**
- App just freezes and needs to be killed. Report is not sent when the app is restarted.

**Expected result:**
- App crashes. Report is sent when the app is restarted.

**Comment by HazAT** [comment]
Can you confirm that if you start the app without the debugger even attached that crash reports will be sent?
Because we have no live detection if the debugger is attached or not, we check this one during startup so if the debugger was there during startup we do not detect once the debugger is detached.

**Comment by hanabrychtova** [comment]
Hello, thank you for your reply!

The problem was caused by the deprecated Firebase/Crash pod, it probably froze the app and so Sentry couldn't detect the crash. Removing it fixed the problem with Sentry.
