### ISSUE TITLE
[CodeReview]is there a mistake?

### ISSUE THREAD

**Issue by lecai** [getsentry/sentry-cocoa#308]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

Version of sentry-cocoa:
**4.3.0**

---
I have following issue:

Is there a mistake in this class? SentryThread should modify to SentryException
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryEvent.m

![image](https://user-images.githubusercontent.com/3724555/57213222-bafa4280-7018-11e9-8637-523cab171a99.png)

**Steps to reproduce:**
- none

**Actual result:**
- none

**Expected result:**
- none

**Comment by HazAT** [comment]
Good catch, thx, will be fixed with #306
