### ISSUE TITLE
Closing Sentry when my xcframework close

### ISSUE THREAD

**Issue by javokhirsavriev** [getsentry/sentry-cocoa#3084]
### Problem Statement

I use sentry sdk in my ios xcframework. Users use my xcframework in their ios parent app. If there is some kind of error in the parent app, the sentry in my xcframework work. But I don't want it. How can I catch errors only inside the xcframework?

**Comment by brustolin** [comment]
Hello @javokhirsavriev, thanks for reaching out. 
We don't support and we even discourage the use of Sentry SDK in other frameworks.
There is no solution for what you want and we don't plan to support.
