### ISSUE TITLE
contexts.trace.sampled: Discarded invalid value  

### ISSUE THREAD

**Issue by LRH-iOS** [getsentry/sentry-cocoa#3095]
### Description

My code has set tracesSampleRate=@1.0

`

     [SentrySDK startWithConfigureOptions:^(SentryOptions *options) {        
            options.dsn = @"https://xxxxx@xxxxxxx";
            options.tracesSampleRate = @1.0;
            options.sampleRate = @1.0;
        }];
`

However, it shows the error，why？
![截屏2023-06-14 10 25 52](https://github.com/getsentry/sentry-cocoa/assets/10429251/7f0547fc-3e38-4a75-bcc8-2b1ff2584d29)

sentry version = ‘8.7.2’

**Comment by brustolin** [comment]
Hello @LRH-iOS, thanks for reaching out. 
This was fixed with #3067 and will be release soon!

**Comment by LRH-iOS** [comment]
> Hello @LRH-iOS, thanks for reaching out. This was fixed with #3067 and will be release soon!

Hello, which tag is this bug planned to be fixed in? specific time?

**Comment by brustolin** [comment]
it will be 8.7.4 later today.
