### ISSUE TITLE
Allow CA-Bundle to be provided (for self signed cert)

### ISSUE THREAD

**Issue by guilh22** [getsentry/sentry-cocoa#3107]
### Problem Statement

Hello,

I would like to be able to use self signed cert with your awesome SDK.

Right now, it doesn't seems to allow usage of self signed certificate from a private trusted certificate authority.

I was wondering if I am alone that hit this issue and if maybe someone know how workaround the issue (if we really need to use this self signed cert).

Thanks in advance!

**Comment by brustolin** [comment]
Hello @guilh22, thanks for reaching out.

Can you explain in more details what do you need?
I didn't get it how do you plan to use a self-signed certificate.
Are you using self-hosted and want to connect to your server with this certificate?

**Comment by guilh22** [comment]
Hello,

Here are the full explanation of our issue:

We are using a product called FreeIPA for our internal LDAP/DNS/Certificates etc.

FreeIPA create a self signed Certificate Authority that is used to sign all internal company certificates for all our internal DNS.

Our production app is connecting to a public url with letsencrypt certificate which work #1 with the SDK, but for our dev environment where all urls are replaced with our company.internal domain, we can't have the certificate created from our internal Certificate Authority to be validated by the SDK. Having a way to provide the CA certificate that should be use on the connection to make the validation process work would be awesome.

I am available to provide more details if required

**Comment by brustolin** [comment]
Thanks for you explanation.
We don't have plans to support self-signed certificates in the SDK. However, there are two alternative approaches you can take to achieve what you want.

1. Install the server certificate in the development devices (IMO the best option).
2. During development, use a URLSessionDelegate to allow the requests, and implement `urlSession(_:didReceive:completionHandler:)`
   
```swift
SentrySDK.start { options in
      // ... rest of the configuration
      #if DEBUG
      options.urlSessionDelegate = self
      #endif
}
```
```swift
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        if let trust = challenge.protectionSpace.serverTrust {
            let credential = URLCredential(trust: trust)
            completionHandler(.useCredential, credential)
        } else {
            completionHandler(.performDefaultHandling, nil)
        }
    }
   ```
