### ISSUE TITLE
How many crashes are kept?

### ISSUE THREAD

**Issue by pvinis** [getsentry/sentry-cocoa#311]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
sentry react native but anyway (**0.42.0**)

---
If a crash happens when I have no network. Then I open the app and a second, different crash happens. Then I open the app again and a third crash happens. Then I connect to wifi and open the app. Will it report all three crashes? Only the last one? Something else?

**Comment by HazAT** [comment]
It ringbuffers 10 events. So it would send up tp 10 events.
