### ISSUE TITLE
Crash EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by JohanAlbrectsen** [getsentry/sentry-cocoa#3112]
### Platform

iOS

### Installed

Swift Package Manager

### Version

No version, just `main` branch

### Steps to Reproduce

No specific steps, I just run the App and it crashes 25% of the time.

### Expected Result

For it not to crash

### Actual Result

![Screenshot 2023-06-20 at 15 37 37](https://github.com/getsentry/sentry-cocoa/assets/109629518/d1c5246d-3179-4042-91f5-1432bfa3ec12)

![Screenshot 2023-06-20 at 15 38 12](https://github.com/getsentry/sentry-cocoa/assets/109629518/59c10d78-a190-4dbb-ad0a-afeb7403207c)

**Comment by JohanAlbrectsen** [comment]
Hey, yes, absolutely.

Here's how I initialise the SDK:

```swift
SentrySDK.start { options in
    options.dsn = "https://19554ac0a1cc4fb9b5fcad4ab9497ecb@o1332190.ingest.sentry.io/4505350897795072"
    options.debug = isLoggingEnabled
    
    Task {
        let user = try await AuthenticatedUserKit.authenticatedUserKit().getMe()
        
        let sentryUser: Sentry.User = Sentry.User(userId: user.id.uuidString)
            sentryUser.email = user.email
        
        self.sentryClient = SentryClient(options: options)
        SentrySDK.setUser(sentryUser)
    }
}
```

iOS version: 16.3.1

I've attached the crash-log:

[2023-07-05_11-32-18.7743_+0200-948548e3d8c34ee9f76257598057de92edb972db copy.crash.zip](https://github.com/getsentry/sentry-cocoa/files/11956410/2023-07-05_11-32-18.7743_%2B0200-948548e3d8c34ee9f76257598057de92edb972db.copy.crash.zip)

Here's what ChatGPT says about the crash:

Based on the provided crash report, here is an analysis of the crash:

Incident Identifier: 5A45DD8E-131F-40C8-97BB-639D230E9FDA
This is a unique identifier for the crash incident.
Hardware Model: iPhone11,2
The crash occurred on an iPhone model with identifier iPhone11,2.
Process: App-QA [5090]
The crash occurred in the process with the identifier 5090, named App-QA.
Identifier: AppGroup.App.QA
The identifier of the crashed application is AppGroup.App.QA.
Version: 1.3.2 (137)
The version of the application at the time of the crash is 1.3.2 with build number 137.
Date/Time: 2023-07-05 11:32:18.7743 +0200
The crash occurred on July 5, 2023, at 11:32:18 local time.
OS Version: iPhone OS 16.3.1 (20D67)
The operating system version on the device is iPhone OS 16.3.1 with build number 20D67.
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
The exception type indicates a segmentation fault, which means the application attempted to access an invalid memory address.
Exception Subtype: KERN_INVALID_ADDRESS
The exception occurred due to an invalid memory address.
Exception Codes: 0x0000000000000001, 0x0000c96e14955270
The exception codes provide additional information about the crash.
Termination Reason: SIGNAL 11 Segmentation fault: 11
The termination reason confirms that the crash occurred due to a segmentation fault.
Triggered by Thread: 5
The crash was triggered by Thread 5.
Thread 0:
The stack trace for Thread 0 shows the sequence of function calls leading up to the crash. In this case, the crash occurred in the libsystem_kernel.dylib library during a call to the writev function.
Termination Process: exc handler [5090]
The process with ID 5090 was terminated due to the exception.
Based on the available information, it seems that the crash occurred during the execution of the App-QA application, specifically in the SentryFileManager class. The crash is related to memory access, which suggests a potential issue with memory management or a null pointer dereference.

To further investigate and pinpoint the cause of the crash, it would be helpful to have access to the application's source code and any relevant crash logs or error messages. Without additional information, it is challenging to provide a more specific analysis or solution to the problem.

**Comment by brustolin** [comment]
Thank you!! We will investigate this this.

**Comment by JohanAlbrectsen** [comment]
About the hang issue, I've recorded a video displaying the problem:
https://drive.google.com/file/d/1ceWQukooT82IdFM1g-bA9ggrXiBh3pJF/view?usp=sharing

**Comment by JohanAlbrectsen** [comment]
I've implemented your suggestion and it seems to work, I'll reopen the issue if it's not the case! Thanks

**Comment by philipphofmann** [comment]
We have a [Cocoa SDK crash](https://sentry.sentry.io/issues/4303369089/events/6d06cf9ff31641a48758c9a99835f583/) that looks a bit similar to this one. In case this pops up again.
