### ISSUE TITLE
Warning: non-portable path to file '"SentryDsn.h"'

### ISSUE THREAD

**Issue by matthewreimer** [getsentry/sentry-cocoa#3115]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.8.0

### Steps to Reproduce

1. Build the app, which triggers the Sentry SDK to be built. The warning is printed whenever the SDK is built.

Note that my filesystem is "APFS (Encrypted)" running on macOS 13.4 (22F66).

### Expected Result

No build warning about a non-portable path

### Actual Result

```
~/Library/Developer/Xcode/DerivedData/ESV-advndesdksdvogccggcrlpbvnnxm/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryNetworkTracker.m:5:9: warning: non-portable path to file '"SentryDsn.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#import "SentryDSN.h"
        ^~~~~~~~~~~~~
        "SentryDsn.h"
1 warning generated.
```

**Comment by brustolin** [comment]
Hello @matthewreimer, thanks for reaching out.
This was fixed in #3109 and will be available at the next release.
