### ISSUE TITLE
Frame has missing debug files

### ISSUE THREAD

**Issue by akapate** [getsentry/sentry-cocoa#3117]
### Platform

iOS

### Installed

CocoaPods

### Version

7.28.0

### Steps to Reproduce

1. Successfully upload dSYMs to self-hosted sentry
<img width="628" alt="Снимок экрана 2023-06-23 в 10 09 17" src="https://github.com/getsentry/sentry-cocoa/assets/59023939/a0e85942-93ca-4dc8-9c7f-eb20bb0bb2a8">

2. Produce a crash at a runtime.
3. Open issue.
4. Look at stacktrace.

### Expected Result

Stacktrace is symbolicated

### Actual Result

Stacktrace is not symbolicated
<img width="291" alt="Снимок экрана 2023-06-23 в 10 10 59" src="https://github.com/getsentry/sentry-cocoa/assets/59023939/3feb8cf1-3ea8-4d56-951c-8e1d42b6be7f">

**Comment by brustolin** [comment]
Hello @akapate thanks for reaching out.
Can you share with iOS version is this, and if it is simulator or device?

**Comment by akapate** [comment]
@brustolin reproduces on real devices with any iOS version

**Comment by brustolin** [comment]
We're working on this problem. You can track the progress in a previous issue [here](https://github.com/getsentry/sentry-cocoa/issues/3033#issuecomment-1608498716)
