### ISSUE TITLE
Clarification User id vs. app.device

### ISSUE THREAD

**Issue by bb-git** [getsentry/sentry-cocoa#3118]
### Platform

iOS

### Installed

CocoaPods

### Version

7.7.3

### Steps to Reproduce

always happening

### Expected Result

The app.device stays the same, but the User id is changing. The SDK reports 5 users experiencing a crash, because of different user ids, but the app.device has only 2 different values. Looking at all the other data (iOS version, device, etc.) it looks like there are really only 2 users affected. How is it possible these values differ? Shouldn't both values be deleted with the app and remain the same as long as the app is installed?

### Actual Result

more user ids than app.device values

**Comment by brustolin** [comment]
Hello @bb-git, thanks for reaching out.

I'm a little confused with your expectation which describes "The app.device stays the same, but the User id is changing"
and this is also the actual result "more user ids than app.device values"

This is exactly as designed, if the user deletes the app, the app.device remains the same because we calculated it according to device informations but the user id is random generated again for the new installation.

**Comment by bb-git** [comment]
Ah great, thanks for clarifying. This is a very valuable metric. In #1541 it was stated differently. 

Does it change when updating iOS?

**Comment by brustolin** [comment]
> Does it change when updating iOS?

No, the iOS version is not taken in account for this informations.

**Comment by brustolin** [comment]
If you need more help let me know.

**Comment by lhunath** [comment]
@brustolin would you be able to indicate whether there is API in sentry-cocoa to obtain the device identifier which Sentry is using? I'd like to use it to create a dev link to the current device's list of sentry issues. I expected it to be `UIDevice.current.identifierForVendor`, but this appears to not be the case. IMO all information obtained from my customer's device should be accessible to me.

**Comment by herrernst** [comment]
I am also interested where the value of `app.device` is derived from.

**Comment by philipphofmann** [comment]
`app.device` is the `device_app_hash` field. It's computed once in [`getDeviceAndAppHash()`](https://github.com/getsentry/sentry-cocoa/blob/main/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L390-L431) as the **SHA-1 hex digest** of the concatenation of these bytes, in order:

1. `UIDevice.current.identifierForVendor` (16 bytes) on UIKit platforms — or, as a fallback, the `en0` MAC address (6 bytes)
2. `hw.machine` (sysctl, UTF-8)
3. `hw.model` (sysctl, UTF-8)
4. the app's bundle identifier (UTF-8), if present

So it is *not* `identifierForVendor` itself; that's just one input, hashed together with the device model identifiers and bundle ID.

A couple of notes:
- It's produced by the crash reporter and mapped into the `app` context by `SentryCrashReportConverter`, so this value is attached to **crash (fatal) events**.
- Its stability tracks `identifierForVendor`: stable across app updates and iOS updates, but per Apple's docs `identifierForVendor` is regenerated once all apps from the same vendor are removed from the device, so it can change after a full uninstall/reinstall.
