### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by MihaelIsaev** [getsentry/sentry-cocoa#312]
Could you please implement Swift Package Manager support?
It's easily possible just by creating `Package.swift`.

I can't wait for it since I started switching my projects to SPM cause Xcode11 support SPM out-of-the-box finally 🙂

**Comment by CatalinMustata** [comment]
I'd really like to see this happen, as all dependencies I've used so far support SPM and it makes life so much easier than using either Carthage or CocoaPods.

**Comment by owzzz** [comment]
We're in the same situation as @CatalinMustata. Any plans to support SPM in the near future?

**Comment by HazAT** [comment]
Short answer is Yes we will support it. 
The little longer answer is, we will not start working on in right away but there is already an open PR https://github.com/getsentry/sentry-cocoa/pull/321
We will try to base the work off of that, so stay tuned it's on our list.

**Comment by makoni** [comment]
Any progress?

**Comment by fetzig** [comment]
#352
