### ISSUE TITLE
crash with -[SentryTracer toTransaction]

### ISSUE THREAD

**Issue by okki-jk** [getsentry/sentry-cocoa#3126]
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

sorry，i can't reproduce this crash，it's collected by Xcode organizer.

### Expected Result

no exception

### Actual Result

![image](https://github.com/getsentry/sentry-cocoa/assets/125631608/bd0323e7-5a88-4ba3-9503-57cccfda80a5)
![image](https://github.com/getsentry/sentry-cocoa/assets/125631608/0deb4a28-19d2-4dea-970e-45e5e7337e62)

**Comment by philipphofmann** [comment]
This should be fixed with https://github.com/getsentry/sentry-cocoa/pull/2744 released in [8.3.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.3.0). Please reopen the issue if it persists after updating to at least 8.3.0.
