### ISSUE TITLE
Test Apple Major OS releases 2023

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3129]
### Description

iOS 17, tvOS 17, watchOS 10, and macOS 14 are about to GA in September 2023. We should test whether our SDK works appropriately on these new OS versions.

# Other tasks

```[tasklist]
### Must-have
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3192
- [x] Provide Privacy/Data use manifest (see [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)) [#3259](https://github.com/getsentry/sentry-cocoa/pull/3259) [#3206](https://github.com/getsentry/sentry-cocoa/pull/3206)
- [x] Test plan manual test (ex tvOS) (see below)
- [x] Test plan manual test tvOS (see below)
- [x] Test plan check with customer data (see below)
- [x] [Test watchOs support](https://github.com/getsentry/sentry-cocoa/pull/3204)
```

```[tasklist]
### Optional / TBD
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3105
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3103
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3100
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3104
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3101
```

# Test plan manual test 

| Feature                         | iOS | macOS | tvOS | MacCatalyst |
|---------------------------------|-----|-------|------|-------------|
| Crashes with symbolication      |   ✅   |   ✅    |    ✅   |         ✅     |
| Error events with symbolication |   ✅   |   ✅    |   ✅    |        ✅       |
| OOMs                            |  ✅  | ╳     |    ✅   |      ╳       |
| App hangs                       |  ✅   | ╳     |   ✅    |     ✅         |
| Release health                  |     |       |       |               |
| View hierarchy                  |  ✅   | ╳    |    ✅   |         ✅      |
| Screenshots                     |   ✅  | ╳    |   ✅    |          ✅     |
| Auto-generated breadcrumbs      |  ✅   |   ✅    |   ✅    |         ✅     |
| Attachments                     |  ✅   |   ✅    |    ✅   |         ✅     |
| App start                       |  ✅   | ╳     |    ☑️   |          ✅     |
| Slow & frozen frames            |  ✅   | ╳     |   ✅     |         ✅      |
| UIViewController tracking       |  ✅   | ╳     |   ✅    |        ✅       |
| TTID/TTFD                       |   ✅  | ╳     |     ✅   |        ✅       |
| Network tracking                |  ✅   | ╳     |   ✅    |        ✅      |
| File I/O tracking               |  ✅   | ╳     |     ✅   |         ✅      |
| Core data tracking              |   ✅  | ╳     |   ☑️    |        ✅       |
| User interaction tracking       | ✅    | ╳     |  ✅     |       ✅       |
| Swift UI tracking               |   ✅  |  ✅     |   ✅     |       ✅        |
| MetricKit                       |  ✅   |       |  ☑️     |       ✅        |
| Profiling                       |   ✅  | ╳     |  ☑️     |      ✅         |

╳ = not available
☑️ = works on another platform. Not needed to put in the effort to test on this platform, because we are going to validate the feature with customer data.

# Test plan check with customer data

Check features with customer data once iOS 17 is released. We only check iOS with customer data as things breaking there would have the most significant negative impact because we have, by far, the most projects on iOS. For the other platforms, the manual test above is sufficient. 

| Feature                         | iOS | 
|---------------------------------|-----|
| Crashes with symbolication      |     |
| Error events with symbolication |     |
| OOMs                            |     |
| App hangs                       |     |
| Release health                  |     |
| View hierarchy                  |     |
| Screenshots                     |     |
| Auto-generated breadcrumbs      |     |
| Attachments                     |     |
| App start                       |     |
| Slow & frozen frames            |     |
| UIViewController tracking       |     |
| TTID/TTFD                       |     |
| Network tracking                |     |
| File I/O tracking               |     |
| Core data tracking              |     |
| User interaction tracking       |     |
| Swift UI tracking               |     |
| MetricKit                       |     |
| Profiling                       |     |   

--- 
Similar to https://github.com/getsentry/sentry-cocoa/issues/2116

**Comment by brustolin** [comment]
- Test watchOs support

Tested with #3204

**Comment by kahest** [comment]
@philipphofmann most of the tvOS tests are still pending, we deprioritized them a bit

**Comment by brustolin** [comment]
@philipphofmann can you check customer data?

**Comment by philipphofmann** [comment]
@brustolin, what about we do it together and I show you how I do it so that you can do it as well next time?
