### ISSUE TITLE
Why is SIGPIPE reported as a fatal?

### ISSUE THREAD

**Issue by garvankeeley** [getsentry/sentry-cocoa#313]
I see it is part of this list of fatal exceptions: 
https://github.com/getsentry/sentry-cocoa/blob/cf20875d74904708d86fdfe9fa13aa6e03380e52/Sources/SentryCrash/Recording/Tools/SentryCrashSignalInfo.c#L130

We are seeing dozens of SIGPIPE 'fatals' reported by Sentry, but no matching crash in Xcode organizer. SIGPIPE should not be fatal AFAIK, they are a common runtime error state in writing to a socket or file.

**Comment by eakoli** [comment]
@garvankeeley Did you ever find a resolution to the SIGPIPE being caught by sentry and terminating the app ?
