### ISSUE TITLE
Conflict in [NSDictionary valueForKeyPath:]

### ISSUE THREAD

**Issue by jkmassel** [getsentry/sentry-cocoa#314]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.3.4**

---
I have following issue:

Conflict in `[NSDictionary valueForKeyPath:]`

**Steps to reproduce:**
- Use `sentry-cocoa` in a project as a statically linked pod.
- Use https://github.com/wordpress-mobile/NSObject-SafeExpectations as a statically linked pod. (we maintain this pod, but I'd imagine we're not the only ones with a library adding this sort of path lookup).
- Call `objectForKeyPath` on a valid dictionary using a dot format like `meta.links.web` (rather that Sentry's preferred `meta/links/web`). 

**Actual result:**
- The result is `nil`. 

**Expected result:**
- The result would be whatever the value of `meta/links/web` would be.

Two possible solutions:

1) Support dot notation in the `objectForKeyPath` methods in `Container+SentryDeepSearch`.
2) Namespace the extension functions used by Sentry to avoid collisions (it looks like these exist as convenience methods for Sentry, rather than being designed for library users the way that `NSObject-SafeExpectations` is).

**Comment by philipphofmann** [comment]
`NSDictionary valueForKeyPath:]` doesn't exist anymore, but we still had two categories for `NSArray` and `NSDictionary` that had methods not prefixed. We fix this with https://github.com/getsentry/sentry-cocoa/pull/555.
