### ISSUE TITLE
Report as app context what's the current screen during the error

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#3140]
see https://github.com/getsentry/team-sdks/issues/18

**Comment by brustolin** [comment]
- For UIKit, we can navigate the view controller hierarchy to found out to top most UIViewController, we need to take in account UINavigationControllers and UITabViewControllers, we can ignore this ones and get the view controller being presented.

- For SwiftUI or unconventional navigation systems we should offer a manual API to set the current screen name.
