### ISSUE TITLE
Memory leak detection on macOS

### ISSUE THREAD

**Issue by aleclarson** [getsentry/sentry-cocoa#315]
Are there any strategies for memory leak detection that Sentry could add to this library, or are there other tools (possibly not Sentry-related) that can be easily integrated with Sentry?

**Comment by aleclarson** [comment]
Maybe something like [this](https://stackoverflow.com/a/6370802/2228559) would be useful.

**Comment by philipphofmann** [comment]
As far as I know, we currently don't detect memory leaks. You can use the instruments of Xcode to detect memory leaks. You can open them like this

https://user-images.githubusercontent.com/2443292/103299085-0c302480-49fc-11eb-8ed9-8b6e1be941ce.mov

You can also check out this talk https://developer.apple.com/videos/play/wwdc2019/411/
