### ISSUE TITLE
Not possible to compile iOS app with watchOS app in Xcode 15

### ISSUE THREAD

**Issue by michaello** [getsentry/sentry-cocoa#3169]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.9.1

### Steps to Reproduce

1. Create iOS project
2. Add watchOS companion app
3. Add sentry to both targets

### Expected Result

App compiles on real device

### Actual Result

Compilation fails:
<img width="606" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/4096232/ed4679b7-46a3-4ec5-ad9d-7539d45e58fc">
[Build SentryTest_2023-07-19T14-13-09.txt](https://github.com/getsentry/sentry-cocoa/files/12091004/Build.SentryTest_2023-07-19T14-13-09.txt)

**Comment by brustolin** [comment]
Thanks @michaello for pointing this out.
Xcode 15 issues will be track at #3122
