### ISSUE TITLE
Feature request: Support for Catalyst (iOSKit for Mac)

### ISSUE THREAD

**Issue by vadimtrifonov** [getsentry/sentry-cocoa#317]
`Sentry` dynamic framework target is explicitly configured with `No SDK` as **Base SDK** (`SDKROOT = ""`), which prevents it from being compatible with Catalyst projects. Resetting it back to the default value of `iOS` solves the issue. 

If I understand correctly setting it to `iOS` will make it incompatible with other platforms. However, can we consider splitting it into multiple targets or some other approach to support Catalyst?

**Comment by ndmanvar** [comment]
![image (4)](https://user-images.githubusercontent.com/314061/62890591-a48b1380-bcf8-11e9-9fba-d760f71d2886.png)
