### ISSUE TITLE
iOS SDK imports UIKit which conflicts with FileProvider

### ISSUE THREAD

**Issue by rpropst** [getsentry/sentry-cocoa#3174]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.9.1

### Steps to Reproduce

1. Have a project that implements FileProvider
2. Add Sentry iOS SDK
3. Fails to compile

- Incorporating sentry using our modified fork of buck, with their own spec file based on Sentry's `spm/cocoapods` specs

- We have operational reasons to disinclude uikit from the extension. so while it's technically fine, we cannot have anything linking it :confused:

- we have a 20 or 25 mb limit for a file provider ext after which apple watchdog kills the process, this is part of the reason they don't link UIKit
![image (1)](https://github.com/getsentry/sentry-cocoa/assets/3869147/6ac66741-8b71-4ea2-a52c-08d9071127a6)

### Expected Result

Compiles

### Actual Result

Fails compilation

**Comment by armcknight** [comment]
Let's try to get this complete by end of September.
