### ISSUE TITLE
Adding to an SDK

### ISSUE THREAD

**Issue by philmartin83** [getsentry/sentry-cocoa#318]
HI, 
I'm writing an SDK and want to try out Sentry, I'm having problems adding it as a dependancy, I noticed an old issue raised from 2018 and wondered if anything had changed, I noticed from the Change log that you use your own version KSCrash which was mentioned in the 2018 question.

I'm getting the crash 

dyld: Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: /private/var/containers/Bundle/Application/733E4AAD-70B6-427F-8963-AAED5032B664/TestApp.app/Frameworks/MyFramework.framework/MyFramework
  Reason: image not found

I've tried using both carthage and cocoapods to install sentry as a dependancy in my framework and I get the same result I've also tried the example given in the post from 2018 regarding checking out the project and dragging and dropping the sentry.xcodeproj into my work space and I get the same result. If anyone could help that would be great.

Just one other question, if an app using my framework is using sentry will there be a conflict? 

Thanks

**Comment by philmartin83** [comment]
Sorry I've worked this out now.

**Comment by joseconstela** [comment]
What was the fix?

**Comment by philmartin83** [comment]
@joseconstela add it as a dependency to your framework.
