### ISSUE TITLE
Do you need SentryPrivate.xcframework when using Carthage?

### ISSUE THREAD

**Issue by rickharrison** [getsentry/sentry-cocoa#3185]
### Description

Installing Sentry with carthage results in 3 frameworks being generated:
```
Sentry.xcframework
SentryPrivate.xcframework
SentrySwiftUI.xcframework
```

The Sentry docs were not clear on how to install using Carthage. Do I need to drag all these frameworks into my project? Or just `Sentry.xcframework` Thanks!

**Comment by brustolin** [comment]
Hello @rickharrison 

You don't need `SentryPrivate` if you don't change the Carthage build process to create a static Framework.

And you should also add SentrySwiftUI if you want to use SwiftUI-specific performance measurement tools.
