### ISSUE TITLE
Events are not symbolicated on Sentry.io

### ISSUE THREAD

**Issue by AlanSpillane** [getsentry/sentry-cocoa#3189]
### Platform

macOS

### Installed

Manually

### Version

8.0.0

### Steps to Reproduce

Upload symbols using a python script
> sentry-cli upload-dif -o '[TEAM]' -p '[PROJECT]' --auth-token '[TOKEN]' [FILE]

### Expected Result

Uploaded the same symbol file previously it successfully completed 

<img width="1235" alt="Ok" src="https://github.com/getsentry/sentry-cocoa/assets/175099/e6e1ba4a-573f-4f86-986a-7e58941dd322">

### Actual Result

Since some time earlier this month all our daily release versions of this symbol file upload fail. I also created a new test project and uploaded the same symbol file that completed successfully (above) last month but that now also fails.

<img width="1251" alt="Failed" src="https://github.com/getsentry/sentry-cocoa/assets/175099/c760be93-8947-479f-b451-67043b3d1060">

Debug ID: 
> cb07f0e0-1948-36f7-899c-302516037e2e

<img width="1104" alt="error" src="https://github.com/getsentry/sentry-cocoa/assets/175099/8e7b27e3-d544-44be-a229-3d690d981c93">

Any help on why this is occurring would be appreciated

**Comment by AlanSpillane** [comment]
Looks like a dupe of https://github.com/getsentry/sentry/issues/52516

**Comment by AlanSpillane** [comment]
Hey @ashwoods any status update on this issue?

**Comment by frost-asabri** [comment]
Any updates here?  This has been ongoing for 3 weeks now and when it does occur it's very impactful to our ability to react to issues.

**Comment by AlanSpillane** [comment]
I noticed there were changes referenced as merged in https://github.com/getsentry/sentry/issues/52516 however this is still a big issue impacting us @ashwoods

**Comment by ashwoods** [comment]
@AlanSpillane we rolled out a fix last week. Could you confirm that it now works?

**Comment by AlanSpillane** [comment]
> @AlanSpillane we rolled out a fix last week. Could you confirm that it now works?

Thanks for your work on this @ashwoods - not an easy one to find a root cause, all seems to be good on our end for the past few days. Will let you know if I notice anything.

**Comment by armcknight** [comment]
Hi @AlanSpillane , glad to hear things are better on your end. I'm going to close this issue for now in that case, but feel free to reopen it or file a new one if anything comes up!
