### ISSUE TITLE
Support for Swift Vapor apps

### ISSUE THREAD

**Issue by tonyarnold** [getsentry/sentry-cocoa#3191]
### Problem Statement

I'd like to use Sentry to monitor my applications written using [Swift Vapor](https://vapor.codes/).

### Solution Brainstorm

This potentially gets back to needing a pure Swift version of the Sentry library (free of dependencies on Apple's frameworks). I'm happy to help out here, but would need some guidance. 

### Product Area

Unknown

**Comment by brustolin** [comment]
Hello @tonyarnold, thanks for reaching out.

If you're interested in porting Sentry to a Swift only SDK, you can follow the documentation to our unified [API here](https://develop.sentry.dev).

Apart from that, you could also read our objc code to translate it to Swift, the parts that are universal at least.
We don't have enough bandwidth right now to actively engage in such project, but we will be happy to answer your questions.
I suggest you join our [Discord server](https://discord.com/channels/621778831602221064/817382542935457793), where the conversation can be more fluid.

**Comment by ptrkstr** [comment]
@tonyarnold did you end up with a solution to a swift only version?

**Comment by tonyarnold** [comment]
@ptrkstr I had the best of intentions, but no, work wasn't keen to invest my time in doing this.

**Comment by ptrkstr** [comment]
No worries, thank you for responding so quickly 🙏
Seems like there's a gap in the market for this type of monitoring. Has also been requested for Rollbar: https://github.com/rollbar/rollbar-apple/issues/282

**Comment by petrpavlik** [comment]
Here's Sentry error reporting SDK that works on linux https://github.com/petrpavlik/swift-sentry

Here's how to integrate it with a Vapor backend https://github.com/petrpavlik/vapor-saas-backend-template/blob/main/Sources/App/entrypoint.swift

**Comment by ptrkstr** [comment]
@petrpavlik I thought that looked familiar and just realised that you spoke about that at your Swift Server talk. Thank you for generously sharing your findings in  that talk and for publishing this package (and the mixpanel one) 🥹

**Comment by petrpavlik** [comment]
❤️
