### ISSUE TITLE
New required reason API

### ISSUE THREAD

**Issue by michaelmcguire** [getsentry/sentry-cocoa#3192]
### Problem Statement

I was doing scans of the newly marked API from Apple and found that the Sentry SDK makes use of a few.

From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will Sentry be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple around this issue?

**Comment by brustolin** [comment]
Hello @michaelmcguire, thanks for reaching out.

If I got this right, Sentry would need the following API reasons:
- [System boot time APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394)
-  [Disk space APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397)

Did you noticed any other API that requires a reason?

We will discuss internally how to address this, but adding the manifest in the SDK may be the way to go.

We will probably need a [data usage](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) manifest as well

**Comment by michaelmcguire** [comment]
> Did you noticed any other API that requires a reason?

@brustolin AFAIK the full list of API is on that page. I didn't try searching the entire repo for all of the API listed, but those two did stick out to me when I think about what I see in Sentry reports.

> We will probably need a [data usage](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) manifest as well

Yeah, that'd be great and I think will become a requirement shortly.

**Comment by brustolin** [comment]
We need:

- [ ] Remove the Disk available space information from the device context
- [ ] Create the Manifest and add the required reason for System boot time API
- [ ] Update the docs to reflect this change.
