### ISSUE TITLE
`The OS watchdog terminated your app, possibly because it overused RAM.` seemingly shown in iOS app store automated testing

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-cocoa#3193]
### Platform

iOS

### Installed

CocoaPods

### Version

latest

### Steps to Reproduce

Hi thanks for the package! However, I see `The OS watchdog terminated your app, possibly because it overused RAM`. The app version that sentry reports is the one that I submit to apple store soon ago, and has not been released yet. Therefore, I think it may be caused by an automated testing machine.

Therefore, I wonder whether someone has seen this before? Does it indicate a real bug (but indeed sentry does not give me any further information to debug...), or is it normal behavior (i.e. my app is OK, it is just how the automated tester makes sentry confused)?

### Expected Result

-

### Actual Result

-

### Are you willing to submit a PR?

yes

**Comment by brustolin** [comment]
Hello @fzyzcjy. Thanks for reaching out. 
Our Watchdog termination report is based on heuristics (you can read more [here](https://docs.sentry.io/platforms/apple/configuration/watchdog-terminations/)), and its possible to have a false possible during automatic tests because the app will be terminated by another process.

**Comment by fzyzcjy** [comment]
@brustolin I agree it can be a false positive. However, do you have any suggestions / is there any ways to know whether this is a false positive or my app really has a bug? Thanks!

**Comment by brustolin** [comment]
If the tests are passing but will still receiving this message it probably means its a false positive. If your app had a bug that caused the app to be killed by the OS, the test would not pass. 
I have no other suggestion for you to check during automatic tests.

**Comment by fzyzcjy** [comment]
You are right. Thank you!

**Comment by nabilfreeman** [comment]
I had the same error reported while my app was "In Review" and the IP address was San Jose, California. Shortly after the app was approved by Apple. Treating as a false positive for now as well.

**Comment by philprime** [comment]
Hi @bryanhpchiang, I do not believe this something to do with the App Review allowing/disallowing a feature of the SentrySDK but instead their automated review utilities forcefully restarting your app, therefore causing our heuristics to trigger a watchdog warning.

I don't see any actionable item here, therefore we'll keep this issue closed for now.
