### ISSUE TITLE
Compilation errors when using Xcode 15 Beta (wachOS, device build)

### ISSUE THREAD

**Issue by AlexHadfield** [getsentry/sentry-cocoa#3203]
### Platform

watchOS

### Installed

Swift Package Manager

### Version

8.9.3

### Steps to Reproduce

When I try to build and run my app on a physical device when I include the watchOS target I get these symbol build errors.

The app builds and runs fine to the simulator, just not to a physical device.

When I remove the watchOS target from the iOS target, the app builds and runs fine on the physical device.

### Expected Result

App should build and run on a physical device (iPhone and Apple Watch) without build errors.

### Actual Result

<img width="957" alt="Screenshot 2023-08-03 at 3 50 41 PM" src="https://github.com/getsentry/sentry-cocoa/assets/25065732/dbcdbae5-50e9-4355-ab3e-2cd85b262341">

### Are you willing to submit a PR?

If required to fix the issue

**Comment by brustolin** [comment]
Thanks @AlexHadfield for reporting this. 
We're aware of this and investigating it.

**Comment by AlexHadfield** [comment]
I just wanted to say that it looks like the project is building and running fine in Xcode 14 beta 6.  Looks like Apple fixed their bugs in the watchOS SDK.

**Comment by kahest** [comment]
Hey @AlexHadfield, thanks for letting us know! I assume you're talking about Xcode 15 beta 6 that was released yesterday :)
