### ISSUE TITLE
Duplicated crash reports: regular and WatchdogTermination

### ISSUE THREAD

**Issue by kean** [getsentry/sentry-cocoa#3207]
### Platform

iOS

### Installed

CocoaPods

### Version

8.9.2

### Steps to Reproduce

In some scenarios, but not all, a single crash gets reported twice:

- Once with an actual stacktrace
- Once as an arbitrary WatchdogTermination

### Expected Result

A crash results in a single even on Sentry. The crash rate is accurate.

### Actual Result

The reported crash rate is inaccurate.

Occasion #1

<img width="951" alt="Screenshot 2023-08-04 at 16 46 27 (1)" src="https://github.com/getsentry/sentry/assets/1567433/7ac18d6d-582d-434b-8d31-461cc66b5dfa">

Occasion #2

<img width="1240" alt="image" src="https://github.com/getsentry/sentry/assets/1567433/9a6294c3-e3c7-4ccd-9955-a06ae3523fd8">

**Comment by kean** [comment]
The main issue with these events is that we can no longer accurately tell the real app's crash rate.

It seems there is already some logic that should take care of the duplicates, but it apparently doesn't work all the time.

```swift
  // The app crashed on the previous run. No Watchdog Termination.
  if (self.crashAdapter.crashedLastLaunch) {
    return NO;
  }
```

I checked one of the events from the screenshots I provided, and they contain identical breadcrumbs and timestamps. Maybe Sentry could check and ignore the crashes with the same timestamp?

**Comment by kahest** [comment]
Hi @kean, thanks for the report! We'll investigate. Please note that due to current vacations and holidays we may be slower to response.

**Comment by brustolin** [comment]
Hello @kean. Is this a React Native project?

**Comment by kean** [comment]
Hey, @brustolin. Yes, parts of it are, and I think both of these crashes happened in the RN part.

**Comment by brustolin** [comment]
@krystofwoldrich do you have any idea what may cause this? Can you take a look?

**Comment by krystofwoldrich** [comment]
The WatchDog issue is created based on a heuristic, are you or some library call `exit(0)` when the fatal error happens?

Is it the [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS/issues/20989) app that you linked the issue to? Are you able to reproduce it locally?

**Comment by kahest** [comment]
@kean could you provide more information and ideally answer above questions? Does it still occur?

**Comment by kean** [comment]
> The WatchDog issue is created based on a heuristic, are you or some library call exit(0) when the fatal error happens?

The crashes I originally reported were all coming the React Native part of the app.

> it the https://github.com/wordpress-mobile/WordPress-iOS/issues/20989 app that you linked the issue to? Are you able to reproduce it locally?

Yes, that's the correct repo. 

This issue is currently much less of a concern as we managed to bring the overall number of the `WatchdogTermination` events significantly down. We suspect that disabling Sentry's app hang monitoring was the main reason why we saw the reduction, but it's hard to verify as there were many other changes that could've contributed to it.

**Comment by philipphofmann** [comment]
> as we managed to bring the overall number of the WatchdogTermination events significantly down.

@kean, what did you do to achieve this?

> We suspect that disabling Sentry's app hang monitoring was the main reason why we saw the reduction

Disabling app hang monitoring only stops the SDK from reporting app hangs, but the app hang tracker still runs to avoid tracking app hangs that get killed as watchdog terminations. I would be surprised if that would be the main reason.
