### ISSUE TITLE
No member named '__fp' in 'struct __darwin_arm_thread_state64'

### ISSUE THREAD

**Issue by cjwl0106** [getsentry/sentry-cocoa#3210]
### Platform

iOS

### Installed

CocoaPods

### Version

7.9.0

### Steps to Reproduce

1、cocoapod add sentry
2、run

### Expected Result

null

### Actual Result

![Xnip2023-08-07_08-54-49](https://github.com/getsentry/sentry-cocoa/assets/5037850/2e73b32a-c722-4daa-bc57-ec10557c8232)
![Xnip2023-08-07_08-56-11](https://github.com/getsentry/sentry-cocoa/assets/5037850/dc4a2168-f3d8-46b0-926d-6f07c7982a4f)

fix:
change context->machineContext.__ss.__fp
 to __darwin_arm_thread_state64_get_fp(context->machineContext.__ss)

**Comment by armcknight** [comment]
Thanks for reporting @cjwl0106 ! I think using those macros are the right approach in any case. I just wanted to ask you a couple questions out of curiosity to get more context around what's happening.

1. Did you try this with the latest version of the Sentry SDK and receive the same results?
2. Which version of iOS/Xcode are you building for/with?

**Comment by kahest** [comment]
Just transferring some information from another channel:

XNU/mach header reveals: https://github.com/apple-oss-distributions/xnu/blob/main/osfmk/mach/arm/_structs.h#L130-L135

```
/*
 * By default, the pointer fields in the arm_thread_state64_t structure are
 * opaque on the arm64e architecture and require the use of accessor macros.
 * This mode can also be enabled on the arm64 architecture by building with
 * -D__DARWIN_OPAQUE_ARM_THREAD_STATE64=1.
 */
```

so we can also check (at compile-time) against __DARWIN_OPAQUE_ARM_THREAD_STATE64. 

cc @supervacuus

**Comment by brustolin** [comment]
Hello @cjwl0106. Can you please inform us which Xcode version and which target platform architecture. 
To make sure the macro will solve the problem we need to reproduce this.

**Comment by kahest** [comment]
Reopening this - it still makes sense to investigate/implement this, once we know how to reproduce/test the specific scenario that led to the error above so that we can be sure we fixed it.
