### ISSUE TITLE
Crash with placeholder message NSException > terminating due to %s exception of type %s > terminating due to uncaught exception of type NSException > XTUM

### ISSUE THREAD

**Issue by squarefrog** [getsentry/sentry-cocoa#3249]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.9.1

### Steps to Reproduce

Not sure how this is reproduced. I'm not sure if it's relevant but all of the reports look like there was an HTTP breadcrumb error before the report was triggered. Typically, this would be `Invalid JSON data: Data too long`. We're going to turn off `enableNetworkBreadcrumbs` for the next release to see if this clears up these reports.

### Expected Result

I'd expect the error report to be populated pointing at the source of the bug.

### Actual Result

There's very little context in the crash report, giving us not much to go on.  Here's an [example report](https://the-beans-group.sentry.io/issues/3712611277/events/e60315d8cd0446e9bb66ec43ff829c8e/?project=5224073&query=release%3Acom.studentbeans.studentbeans%405.15.0%2B207&referrer=previous-event). 

I'm lead to believe this was marked as fixed in 8.1.0, however we're still experiencing it in 8.9.0.

Looks like it's linked to the following:

- https://github.com/getsentry/sentry-cocoa/issues/2835
- https://github.com/getsentry/sentry-cocoa/issues/2795
- https://github.com/getsentry/sentry-cocoa/issues/1533

**Comment by brustolin** [comment]
Hello @squarefrog, thanks for reporting this.
We will investigate.

**Comment by squarefrog** [comment]
Has there been any movement on this? This is by far our most significant crash, and is still happening as of v8.13.0.

**Comment by squarefrog** [comment]
I haven't seen any more reports of this since we stopped Snowplow from exception logging. Sorry if I've wasted your time!

**Comment by philipphofmann** [comment]
@squarefrog, no worries. We're happy that your issue is resolved 😃. Please continue to open issues if something doesn't work.
