### ISSUE TITLE
iOS MetricKit integration using large amounts of RAM

### ISSUE THREAD

**Issue by diarmaidr** [getsentry/sentry-cocoa#3263]
### Platform

iOS

### Installed

CocoaPods

### Version

8.8.0

### Steps to Reproduce

Seeing intermittent large usage of data by sentry in MetricKit integration. 

I have been unable to get consistent repro steps as Metric Kit is sending the diagnostic payload from the OS to SentryMetricKitIntegration.  

From apple docs: "The system delivers metric reports about the previous 24 hours to a registered app at most once per day, and delivers diagnostic reports immediately in iOS 15 and later and macOS 12 and later. "

https://developer.apple.com/documentation/metrickit

From from iPad A1893. 
iPad 6th Gen (2GB Ram)
iPadOS Version 16.6

### Expected Result

Sentry does not use a large amount of data. 

### Actual Result

XCode Instruments: Created and Persistent, All Heap and Anonymous VM

![image](https://github.com/getsentry/sentry-cocoa/assets/127780174/061ddcac-b956-46ea-80de-913bb4c1a5c7)

<img width="793" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/127780174/e37e5c04-b154-4a53-a35b-e86b68b759f9">

**Comment by brustolin** [comment]
Thanks @diarmaidr for reporting this. We will investigate the problem.

**Comment by brustolin** [comment]
Hello @diarmaidr.
We cant reproduce this, do you have more information to help us out?
Is this still happening?

**Comment by brustolin** [comment]
Exactly. The few times I got metrikit notification the memory was fine.

**Comment by philipphofmann** [comment]
From checking your heaviest stack trace, @diarmaidr, I assume that the Sentry event generated from the MetricKit report could be around 400MB, as our code adds 15MB to the used bytes, and the used bytes are around 400MB when calling the `NSFileManager contentsAtPath`, or am I getting it wrong? Do these MetricKit events end up in Sentry? If they are 400MB big they shouldn't, as our backend would drop such big events.

**Comment by diarmaidr** [comment]
The application crashed (oom) when we got the 400mb event coming through. That was the memory size of sentry before the crash.

**Comment by philipphofmann** [comment]
@diarmaidr, I'm not sure. The last function call of the heaviest stacktrace `_NSReadBytesFromFileWithExtendedAttributes` allocated 417MB, or are there frames below missing? If frames are missing, our SDK code would only be responsible for allocations from 417 to 432MB, which are 15MB and would be fine. How did you conclude that the MetricKit integration uses large amounts of RAM?

**Comment by philipphofmann** [comment]
Hmm, thanks for the info @diarmaidr. We have to do further investigation and have to get back to you.

**Comment by diarmaidr** [comment]
TY
