### ISSUE TITLE
Sentry fails to report exceptions when userInfo has too much information

### ISSUE THREAD

**Issue by koke** [getsentry/sentry-cocoa#327]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.0.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.0**

---
I have following issue:

I was trying to report to Sentry an error when a `NSManagedObjectContext` failed to save:

```swift
let reason = reasonForError(error)
let exception = NSException(name: "Core Data save error", reason: reason, userInfo: error.userInfo)
exception.raise()
```

In this case, `error.userInfo` contains a lot of information about why Core Data couldn't save, which properties didn't validate, and the contents of the objects that failed validation.

After the app crashed, I wasn't seeing the errors in the Sentry interface, and the noticed this in the Xcode console:

```
ERROR: SentryCrashReportFixer.c (272): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
ERROR: SentryCrashC.c (281): char *sentrycrash_readReport(int64_t): Failed to fixup report ID ef000000
```

It looks to me that [SentryCrashMonitor_NSException](https://github.com/getsentry/sentry-cocoa/blob/cf20875d74904708d86fdfe9fa13aa6e03380e52/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException.m#L91) will just convert the `userInfo` dictionary to a string, and that won't fit in the [10KB buffer](https://github.com/getsentry/sentry-cocoa/blob/cf20875d74904708d86fdfe9fa13aa6e03380e52/Sources/SentryCrash/Recording/SentryCrashReportFixer.c#L250) reserved by `sentrycrashcrf_fixupCrashReport`.

I don't have an easy way to reproduce, but I've uploaded the JSON file that `sentrycrashcrf_fixupCrashReport` is trying to process to https://gist.github.com/51855a1a942e835375412cca2cacbbcc

In there you can see that the exception `userInfo` string is almost 17KB:

```
$ cat WordPress-report-0000000080000000.json | jq '.crash.error.nsexception.userInfo | length'
16946
```

I understand you might not want to allow any arbitrary data length into `userInfo`, but I'd rather see the property set to nil or trimmed than have the crash go completely unreported.

**Comment by jadar** [comment]
I'm running into a similar issue, right now. We're running into CD exceptions when faults cannot be fulfilled, and I'd love to have some more context in Sentry. The user info doesn't seem to be included in the event. Any updates on this issue?

**Comment by bruno-garcia** [comment]
This issue was raised for our SDK version 4.
We're about to release 6.0.0 (it's on beta now).

Since 4.0 we've added support to `userInfo` from both NSError and NSException. Could you please try the latest 5.x or if possible our latest beta?

**Comment by jadar** [comment]
I am currently shipping v5.2.2. I guess the hard part is that I don't if the data is being missed or if it's even there in the first place. I presume that if there's a localized description, it would appear in the `userInfo` dictionary. I'm also not sure where that data would potentially appear in the Sentry event view.

**Comment by philipphofmann** [comment]
We add the user info to the [context of the event](https://github.com/getsentry/sentry-cocoa/blob/b5bf9769a158c66a34352556ade243e55f163a27/Sources/Sentry/SentryClient.m#L332-L344) and you should find it at the bottom of your issue view: 

<img width="754" alt="Screenshot 2020-09-29 at 13 06 00" src="https://user-images.githubusercontent.com/2443292/94550812-ab564c00-0254-11eb-9834-726caffcc795.png">

**Comment by philipphofmann** [comment]
Do you still experience this issue @koke and @jadar? Can we close this?

**Comment by koke** [comment]
@philipphofmann thanks for letting me know. I'm not working on that project anymore, but I'll pass it along to the developers so they can test it

**Comment by philipphofmann** [comment]
As we didn't receive any input for over a month I'm going to close this issue. Please feel free to open it again @koke if you have more input.
