### ISSUE TITLE
ticksSinceUiUpdate is not thread safe

### ISSUE THREAD

**Issue by iDevPro** [getsentry/sentry-cocoa#3274]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.11.0

### Steps to Reproduce

0) Install Xcode 15b8
1) Install Sentry
2) Enable ThreadSanitizer
3) Configure Sentry in code as usual
4) Run app
5) Get stop on `Data race in -[SentryANRTracker detectANRs] `

### Expected Result

Without stop on Data racing

### Actual Result

Stopped on Data racing

![Снимок экрана 2023-09-11 в 08 59 15](https://github.com/getsentry/sentry-cocoa/assets/1888230/1dc40b56-4c09-4ea3-ac3a-78c7a4c4de24)

**Comment by iDevPro** [comment]
Also so strange code here:
![Снимок экрана 2023-09-11 в 09 03 41](https://github.com/getsentry/sentry-cocoa/assets/1888230/80b17be8-53f0-4990-a723-1a220bd16110)

84: have change ticksSinceUiUpdate in any thread
87: have change ticksSinceUiUpdate in main thread async

**Comment by armcknight** [comment]
Hi iDevPro, I've actually asked the same question the first time I saw this code :D What this is doing is counting how many ticks elapse before the main queue can service that block again. If the main queue can't service it, then we assume it is blocked and thus report the ANR later in the method: https://github.com/getsentry/sentry-cocoa/blob/881a95561aedd5bac232089866de9a476d18c85a/Sources/Sentry/SentryANRTracker.m#L127

and if the main queue _is_ able to service that block, then the tick count gets reset to 0 so that we don't report the ANR.

I'll look into the data race though. Let me see if I can reproduce it.

**Comment by vvbutko** [comment]
I see the same issue with the ThreadSanitizer data race.
This issue also reproduces on a clean UIKit project, just checked now with Sentry 8.11.0.

**Comment by armcknight** [comment]
@vvbutko or @iDevPro , could you share the configuration you use to start the SDK? I'm curious which combinations of options might lead to this.

**Comment by iDevPro** [comment]
> @vvbutko or @iDevPro , could you share the configuration you use to start the SDK? I'm curious which combinations of options might lead to this.

I have more then simple config
```
SentrySDK.start { options in
    options.dsn = dsn
    options.environment = Self.environment
    options.sendClientReports = false

    // Set debug options
    options.debug = Self.isDebug
    options.enableAppHangTracking = Self.isDebug
    options.enableFileIOTracking = Self.isDebug
    options.enableCoreDataTracking = Self.isDebug
    options.enableNetworkTracking = Self.isDebug

    // Disable stacktrace for debug build
    options.attachStacktrace = !Self.isDebug

    // Breadcrumbs
    options.enableAutoBreadcrumbTracking = !Self.isDebug
    options.maxBreadcrumbs = Self.isDebug ? .zero : 25

    // OOM detection
    options.enableOutOfMemoryTracking = true

    // Additionals fix report before send
    options.beforeSend = { event in

        // Remove some info for thinning reports
        switch event.level {
        case .info, .warning:
            event.debugMeta = nil

        default:
            break
        }

        let stackTraceNotCaptured = event.tags?[Tag.stacktraceCaptured, default: "false"] == "false"
        let isEvent = event.tags?[Tag.eventType, default: "error"] == "event"

        if stackTraceNotCaptured || isEvent {
            event.threads = []
            event.stacktrace = nil
            event.exceptions = []
        }

        return event
    }
}
```

**Comment by kahest** [comment]
Thanks all for the information, a fix is in the works
