### ISSUE TITLE
UIWindow called from background thread

### ISSUE THREAD

**Issue by lukeredpath** [getsentry/sentry-cocoa#3280]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.11.0

### Steps to Reproduce

Running the app after updating to 8.11.0 and I'm seeing a main thread checker error due to accessing `UIWindow.screen` on a background thread.

### Expected Result

This API should not be called from a background thread and there should be no warnings.

### Actual Result

```
Main Thread Checker: UI API called on a background thread: -[UIWindow screen]
PID: 39691, TID: 573072, Thread name: (none), Queue name: com.apple.root.user-initiated-qos.cooperative, QoS: 25
Backtrace:
4   Community                           0x0000000108e4caac +[SentryCrashIntegration enrichScope:crashWrapper:] + 2316
5   Community                           0x0000000108e4bfbc __40-[SentryCrashIntegration configureScope]_block_invoke + 140
6   Community                           0x0000000108e7eab7 -[SentryHub configureScope:] + 199
7   Community                           0x0000000108e4beb0 -[SentryCrashIntegration configureScope] + 160
8   Community                           0x0000000108e4b958 -[SentryCrashIntegration installWithOptions:] + 584
9   Community                           0x0000000108eb9942 +[SentrySDK installIntegrations] + 1634
10  Community                           0x0000000108eb7863 +[SentrySDK startWithOptions:] + 947
11  Community                           0x0000000108eb79b4 +[SentrySDK startWithConfigureOptions:] + 132
```

**Comment by lukeredpath** [comment]
![Screenshot 2023-09-13 at 13 21 25](https://github.com/getsentry/sentry-cocoa/assets/613/d1910673-9b16-40a4-8695-e13cecc95259)

On further inspection it seems that Sentry is using multiple APIs on a background thread. I have reverted to 8.10.0 to see if that resolves the problem.

**Comment by lukeredpath** [comment]
@armcknight looks like this might not be a new issue but one that was only showing up when I ran the app in Xcode 15, perhaps the main thread checker wasn’t picking it up before. 

Looks like the problem is occurring because our SentryClient wrapper around the SDK was converted to use Swift concurrency and the async code that calls the SDK is not running on the main actor. 

I will see if annotating this code as requiring main actor fixes the problem, but I guess this requirement should be documented. I think I’d rather the SDK asserted if it was initialised off the main queue so this can be caught more easily.

**Comment by armcknight** [comment]
Thanks for the followup info @lukeredpath , that is very helpful information. We'll figure out what to do about this next week when more of my teammates return.
