### ISSUE TITLE
Increased 'App Hanging' Sentry Reports with Background Updates

### ISSUE THREAD

**Issue by mikelehen** [getsentry/sentry-cocoa#3287]
### Platform

iOS

### Installed

CocoaPods

### Version

8.6.0

#### Background
We recently added "background update" support to our app based on [Apple's docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).  Most notably, we add `content-available` to our push notification payload and then handle the [application(_:didReceiveRemoteNotification:fetchCompletionHandler:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) delegate function, which iOS will call when the app is in the background.

#### Observation
Since releasing this feature we've seen a huge rise in "app hanging" sentry reports:
![image](https://github.com/getsentry/sentry-cocoa/assets/206364/02bb1214-109c-41f4-a538-c4b97c0db442)

#### Details
But all of our background update code runs asynchronously off of the main queue, and the callstacks in the sentry events are widespread and mostly not in our app code at all.  Here's an [example callstack](https://gist.github.com/mikelehen/c7d3e35efba24bf30379517701a37da0) with 607 hits (~28% of the total hits from the chart above). The entire callstack except for the root main() function is iOS internal code, not our app code.  It's also worth noting that the "background update code" we're running (to fetch some network data and persist it to disk) is the same code we run routinely when the app is in the foreground, and it doesn't seem to trigger "app hang" reports in that case.

#### Analysis
My guess is what's happening is that the app is being CPU throttled since it's running in the background, and this causes the queue to be blocked for >2s even though it's doing "normal" things.  Another possibility is that iOS is scheduling work on the main queue more aggressively since the app is in the background and the UI is not expected to be interactive (total speculation).

The net result is we're getting tons of app hang reports via sentry, but not a single user complaint. And I expect these are all "red herrings."  I'm wondering if this is a known issue and/or if there is any suggested workaround.

#### Suggestion:
Naively, maybe the app hang detection logic should be conditioned on `UIApplication.shared.applicationState == UIApplication.State.active` since it doesn't matter if the app is not very responsive when it is running in the background.

### Expected Result

App hangs should only be reported when the app is in the foreground?

### Actual Result

Lots of app hangs reported when running in the background.

### Are you willing to submit a PR?

Maybe?  If it's as simple as conditioning on `UIApplication.shared.applicationState == UIApplication.State.active` then I could try.

**Comment by armcknight** [comment]
@mikelehen , thanks for the detailed and thoughtful report. Your guess sounds plausible, let us try to reproduce it and investigate.

**Comment by mikelehen** [comment]
Thank you! 🙏

**Comment by ichbinjon** [comment]
Any update on this issue? we've ran into the same thing.

**Comment by mikelehen** [comment]
I believe it was fixed (https://github.com/getsentry/sentry-cocoa/pull/3298) and we stopped seeing the sentry issue after upgrading.
