### ISSUE TITLE
BeforeScreenshotCapture for filtering out screenshots

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-cocoa#3289]
### Problem Statement

Hello, need a way to drop certain screenshots from being sent, similar to functionality in Android. Can you please add this method?

https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/screenshots/ I don't see it in iOS documentation
<img width="915" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/8920574/a3e583b6-19aa-479d-bab2-1dcd1a8b3e9d">
here it is in Android
https://docs.sentry.io/platforms/android/enriching-events/screenshots/#customize-screenshot-capturing
<img width="1086" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/8920574/949f34b1-12cf-4965-ab9e-7293fe79a930">

**Comment by brustolin** [comment]
You can track this feature at #3137
