### ISSUE TITLE
Uncaught exception in `profilerForFinishedTracer`

### ISSUE THREAD

**Issue by jpsim** [getsentry/sentry-cocoa#3299]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.13.0

### Steps to Reproduce

Will work on more comprehensive steps to repro async, but for now at least wanted to get this on your radar.

### Expected Result

Ability to call `-[SentryTracer finishWithStatus:]` without triggering internal exceptions. This was working in 8.8.0, but tracing has been broken for us since that release for various reasons, first being a deadlock then with 8.13 we hit this exception.

### Actual Result

> Expected a profiler to be associated with tracer id dfd99f76d40d4af38488db3fff789426.

```
#0  __exceptionPreprocess ()
#1  objc_exception_throw ()
#2  -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] ()
#3  profilerForFinishedTracer at /<redacted>/sentry-cocoa/Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm:118
#4  +[SentryProfiler collectProfileBetween:and:forTrace:onHub:] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryProfiler.mm:394
#5  +[SentryProfiler createProfilingEnvelopeItemForTransaction:] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryProfiler.mm:363
#6  -[SentryTracer captureTransactionWithProfile:] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryTracer.m:540
#7  -[SentryTracer finishInternal] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryTracer.m:528
#8  -[SentryTracer canBeFinished] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryTracer.m:428
#9  -[SentryTracer finishWithStatus:] at /<redacted>/sentry-cocoa/Sources/Sentry/SentryTracer.m:400
```

### Are you willing to submit a PR?

Yes, if I can figure out a fix

**Comment by jpsim** [comment]
Still no repro steps, but I've bisected the issue to this PR: https://github.com/getsentry/sentry-cocoa/pull/3145

**Comment by brustolin** [comment]
Hello @jpsim, thanks for report this. 
Can you share the exception message please.

**Comment by jpsim** [comment]
The exception message is:

> Expected a profiler to be associated with tracer id dfd99f76d40d4af38488db3fff789426.

**Comment by jpsim** [comment]
Even though I don't have a minimal repro, I do have a _reliable_ repro, but it's with our large closed source project. So unfortunately I don't have a sample project to share, but I can easily test a patch, whether with more logging or with a potential fix.

**Comment by armcknight** [comment]
Thanks for digging into this @jpsim . It looks like it's crashing on an `NSCAssert`: https://github.com/getsentry/sentry-cocoa/blob/7fa1b2f9254f7fc4336496140cf6363c5d3db02c/Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm#L118

which I would expect to be compiled out of at least Release builds. Is this from a build in which you're using our Release configuration? I need to look more into SPM to see how it could change that setting.
![image](https://github.com/getsentry/sentry-cocoa/assets/3241469/c3d1b2ec-6ce1-462a-abc3-97fea3ba27b6)

Maybe we need to use something besides asserts if this doesn't play nicely with SPM.

Beyond that, it sounds like our concurrency model still has a flaw, where a span ends that should get some profiling data but there is no profiler, or at least it was already deallocated by that point.

**Comment by jpsim** [comment]
> which I would expect to be compiled out of at least Release builds. Is this from a build in which you're using our Release configuration? I need to look more into SPM to see how it could change that setting.

This was when building our app with the Debug flavor, and since we're building Sentry as a SwiftPM package from source, I believe it's our setting of `ENABLE_NS_ASSERTIONS` that gets propagated when building Sentry, and we have that set to `YES` for Debug builds and `NO` for Release builds of our app.

So I think the assertion machinery is all working as expected. I think it's likely that you're right that there's a race condition in which a span ends where its profiler is already deallocated or gone.

**Comment by armcknight** [comment]
@jpsim sorry for the delay on this, but can you tell me if you're running a flutter app or native app? those are the two codepaths into this function and would require pretty different approaches to solving.

**Comment by jpsim** [comment]
This is in a completely Swift-based app.

By set the SDK’s debug mode to true, so you mean compiling with a `-DDEBUG` compiler flag or something else?

**Comment by armcknight** [comment]
Thanks for confirming the type of codebase you're in. By debug mode, I mean setting the `debug` option to true when you initialize the SDK, like
```
SentrySDK.start { options in
    options.debug = true
    ....
}
```

**Comment by philipphofmann** [comment]
@armcknight, I maybe found something. 

### Problem 1
The logic in `SentryProfiledTracerConcurrency` assumes that the `traceID` of a tracer never changes, but it actually can. The `traceID` is mutable, see https://github.com/getsentry/sentry-cocoa/blob/dd0557fb0fec40f5527e4f40ead6f82e092fde0f/Sources/Sentry/Public/SentrySpanProtocol.h#L15

So users can do something like:
```Swift
let transaction = SentrySDK.startTransaction(name: "Some Transaction", operation: "Some Operation")
transaction.traceId = SentryId(uuidString: "my-uuid")
```

### Problem 2
I found one more problem that could lead to some crashes, but not many. In `SentryProfiler.startWithTracer`, we never call `trackProfilerForTracer` when `[[SentryProfiler alloc] init]` returns `nil`.

https://github.com/getsentry/sentry-cocoa/blob/dd0557fb0fec40f5527e4f40ead6f82e092fde0f/Sources/Sentry/SentryProfiler.mm#L325-L344

As `profilerForFinishedTracer` always expects a profiler for a `traceId`, we sometimes can run into situations where our assert here fails https://github.com/getsentry/sentry-cocoa/blob/dd0557fb0fec40f5527e4f40ead6f82e092fde0f/Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm#L118-L121

**Comment by jpsim** [comment]
8.15 doesn’t trigger the exception for us anymore. 🙌 

thanks for figuring this out even without a repro project from me 🙏

**Comment by philipphofmann** [comment]
@jpsim, async stuff is often hard to reproduce. Thanks for opening the issue to raise awareness so we could investigate and fix it.
