### ISSUE TITLE
Sentry not capturing events

### ISSUE THREAD

**Issue by rehatkathuria** [getsentry/sentry-cocoa#3300]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.13.0

### Steps to Reproduce

let event = Event(level: .warning)
event.fingerprint = [UUID().uuidString]
if let description { event.message = .init(formatted: description) }
let identifier = SentrySDK.capture(event: event) { scope in
    for screenshot in screenshots {
        guard let data = imageToData(screenshot) else { continue }
        scope.addAttachment(.init(data: data, filename: UUID().uuidString + ".jpg"))
    }
}
let feedback = UserFeedback(eventId: identifier)
feedback.comments = comments ?? .init()
SentrySDK.capture(userFeedback: feedback)

### Expected Result

Expected to see an event captured in the sentry console.

### Actual Result

Nothing being reported in the console

**Comment by brustolin** [comment]
Hello @rehatkathuria, thank you for getting in touch. I tried your code and received the report as expected. 
Could you please provide a reproduction case to help us in identifying the issue?

**Comment by rehatkathuria** [comment]
I think it was related to the attachment ingestion issues that occurred yesterday.
