### ISSUE TITLE
Report OS name + version for every issue

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3305]
### Description

We currently report the platform for crash events: https://github.com/getsentry/sentry-cocoa/blob/533859f7bae4a14f6c535a2ec7aef4f526f01e83/Sources/Sentry/SentryCrashIntegration.m#L204-L212

But not for performance transactions. We should add it there. Need to align on any necessary backend changes to ingest the new field.

**Comment by armcknight** [comment]
Also, OS version.

**Comment by philipphofmann** [comment]
@armcknight, the SentryCrashIntegration enriches the scope with the osData here 

https://github.com/getsentry/sentry-cocoa/blob/e32423038e99f0c5d868744421d664cdd55c7383/Sources/Sentry/SentryCrashIntegration.m#L174C1-L175

Everything in enrichScope ends up in the global scope
https://github.com/getsentry/sentry-cocoa/blob/e32423038e99f0c5d868744421d664cdd55c7383/Sources/Sentry/SentryCrashIntegration.m#L199C9-L199C20

As a transaction is an event, the client also applies the scope to transactions. Therefore, osData also ends up in the context of transactions, see [sample transaction](https://sentry-sdks.sentry.io/performance/sentry-cocoa:705797ccfef1462583ce7d5222d4e245/?project=5428557&query=&referrer=performance-transaction-summary&statsPeriod=24h&transaction=ViewController&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29):

<img width="1283" alt="Screenshot 2023-10-03 at 08 53 40" src="https://github.com/getsentry/sentry-cocoa/assets/2443292/7d91a919-3fa8-432d-8cb5-8ece788a98e7">

If I'm not mistaken, we can close this issue.

**Comment by philipphofmann** [comment]
One problem, though, is that if the SentryCrashIntegration is not installed, the SDK doesn't add the context above to the scope.

**Comment by armcknight** [comment]
Sounds like we need to hoist this data collection above the integration level so it applies throughout the SDK.

**Comment by philipphofmann** [comment]
Yes, indeed, but disabling the SentryCrashIntegration isn't that typical.

**Comment by philipphofmann** [comment]
Was fixed with https://github.com/getsentry/sentry-cocoa/pull/3699.
