### ISSUE TITLE
Add iOS 17 unit tests to matrix

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3329]
### Description

Tried doing this a bit in #3283 but had some issues with test job length. We should wait until github updates their macOS image's Xcode version once 15.1 goes GA to see if this bug is what was causing it:
> Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776)

**Comment by philipphofmann** [comment]
> Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776)

The fix is in [Xcode 15.0.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes), which is available in the latest [macos-13 GH image](https://github.com/actions/runner-images/releases/tag/macos-13/20231018.14). So we can tackle this issue now.

**Comment by armcknight** [comment]
https://github.com/getsentry/sentry-cocoa/pull/3433 removed iOS 17 from test runs, so reopening this issue until we get them back in.
