### ISSUE TITLE
Make build_type searchable

### ISSUE THREAD

**Issue by swizzlr** [getsentry/sentry-cocoa#3330]
### Problem Statement

I want to filter issues of a given build that occur between different deployment methods. Build numbers help, but a TestFlight or internal build cannot be distinguished from the same App Store build except by manually viewing the field in an event. I would like to be able only view issues on TestFlight or on App Store to help me track the extent to which a problem occurs.

### Solution Brainstorm

Maybe the build types could be tags, like the build number?

### Are you willing to submit a PR?

Yes!

**Comment by armcknight** [comment]
Hi @swizzlr, you should be able to filter based on build/version numbers in the dashboard like so: 
![image](https://github.com/getsentry/sentry-cocoa/assets/3241469/53a062b7-d8bc-4296-9659-3c9b2cffcc82)

Are you adding metadata to your build or version number for testflight/internal builds, like 1.2.3 for appstore and 1.2.3+beta or 1.2.3+rc3, or 1.2.3+4BC037D for an internal build? (I like to put the commit hash on those.) Or is that not getting you far enough?

**Comment by swizzlr** [comment]
Well, we test our release candidate builds in TestFlight and then when we’re happy with it we send that same build to the App Store. I suppose we could start doing that, but it’s pretty inefficient - the SDK is already capable of detecting build types, right? Is there a way that could be filtered on, somehow?

**Comment by philipphofmann** [comment]
We currently don't index the build type, and therefore you can't use it in your search. To make this work, we need to align across all mobile platforms and come up with a field that works for all. Android, for example, currently doesn't send build type. Then we need to index it on our backend and make it searchable. We agreed internally to not use tags to make things searchable for our users, cause it's expensive. I won't bore you with the details. Anyway, I will create a meta issue and discuss this with the team. I can see value in such a feature, but I can't give you an ETA for this.

What you could do to make this work for you right now, would be to query the build type from the app scope https://github.com/getsentry/sentry-cocoa/blob/39b1c353b26407f787556148d2c9ef35d6a394f5/Sources/Sentry/SentryCrashIntegration.m#L301

and then set it as a tag manually. Something like this could work, after initializing the SDK
```Swift
SentrySDK.configureScope { scope in
    let dict = scope.serialize()
    let context = dict["context"] as? [String:Any]
    let appContext = context?["app"] as? [String:Any]
    let buildType = appContext?["build_type"] as? String
    
    scope.setTag(value: "build_type", key: buildType ?? "")
}
```

**Comment by swizzlr** [comment]
This is a great workaround, thank you! I do like the meta issue, thank you for considering it!
