### ISSUE TITLE
Why is WatchdogTermination backtrace info not that good?

### ISSUE THREAD

**Issue by goodones-mac** [getsentry/sentry-cocoa#3335]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.8.0

### Steps to Reproduce

1. Get a watchdog termination
2. See in the sentry webui that all you get is one thread's callstack, not all thread's callstacks
3. Go to a phone which experienced a watchdog termination, get the full crash report from the phone manually in the settings app and see all thread stacks are there for the same WatchdogTermination
4. Look at competitors such as firebase crashlytics in other apps, see that they have all thread stacks for watchdog terminations.
5. Notice that sentry hasn't implemented the new crash diagnostics in metrickit, which might have this extra info: https://github.com/getsentry/sentry-cocoa/issues/2627
6. Wonder why there is an info gap

### Expected Result

All threads have their backtraces 

### Actual Result

Only the sentry init thread has a callstack
<img width="869" alt="Screenshot 2023-10-06 at 11 57 32 AM" src="https://github.com/getsentry/sentry-cocoa/assets/123040996/1dd64cbe-09b3-47c5-926d-85c5c4e196af">

### Are you willing to submit a PR?

probably not

**Comment by philipphofmann** [comment]
Hey, @goodones-mac, watchdog terminations of our SDK don't have any stack traces. We explain why in [our docs](https://docs.sentry.io/platforms/apple/guides/ios/configuration/watchdog-terminations/):

> When a typical unhandled error occurs, the Apple SDK writes a report to disk with the current state of your application, with details like the stack trace, tags, breadcrumbs, and so on, before the app terminates. When the watchdog terminates your app this happens without further notice, which means the SDK can't write a report to disk.

How do you get the watchdog termination? Can you provide us with a repro? Maybe you are referring to something different than a watchdog termination.

**Comment by philipphofmann** [comment]
The question should be answered with https://github.com/getsentry/sentry-cocoa/issues/3335#issuecomment-1757666982. If not, please reopen the issue.
