### ISSUE TITLE
SPM release candidate check run

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3350]
### Description

Following on from #3348 , we need a check in CI to run on either/both PRs/Release, which will be able to integrate Sentry via SPM in the same way that a customer would. Our current job `validate-spm` in `build.yml` isn't good enough because it misses edge cases that are only present when you pin us as a dependency using our version, which most people will do (and should!). See current implementation: https://github.com/getsentry/sentry-cocoa/blob/7672856d70630d92a580600cd97348974461c3c1/.github/workflows/build.yml#L125-L143

But because we pin to a commit, we missed a breakage and wound up releasing it to customers: https://forums.swift.org/t/override-for-unsafeflags-in-swift-package-manager/45273/2

> `unsafeFlags` are allowed for SPM dependencies specified with a commit hash instead of a version

Which is what we'd used [in PR](https://github.com/getsentry/sentry-cocoa/pull/3175/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR22): https://github.com/getsentry/sentry-cocoa/blob/98cca71ab965606c68f46b2f6a0a9c710ce6cdb2/Package.swift#L22

Look into tagging the version to check in CI with a release candidate version like 8.14.2-RC1. If that works at all with SPM, then we can think about how to increment that RC number.

**Comment by brustolin** [comment]
Hello @armcknight.
We have changed the way we distribute with SPM. I believe this is no longer required.

Can you double check it if we can close this issue?

**Comment by armcknight** [comment]
Hey @brustolin , how would the changes avoid the issue I described here?

**Comment by brustolin** [comment]
Our SPM is a pre-built framework now. We dont have a sample test pointing to the same Package.swift that our users will use. I dont see how pinning a version could have any different outcome.
