### ISSUE TITLE
Add visionOS to SPM Package definition

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3366]
VisionOS has been available since Swift tools version 5.9, [see PR](https://github.com/apple/swift-package-manager/pull/6663). We can only add it as an official platform to our SPM definition when bumping the Swift tools version to 5.9. Our current version is

https://github.com/getsentry/sentry-cocoa/blob/2124551ae0a2da085c69d3f0838e9be646fa4a70/Package.swift#L1

**Comment by brustolin** [comment]
Since visionOS is in its first version, we don't need to add it to the Package definition, Its already working properly.
