### ISSUE TITLE
App Launch Profiling

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3380]
### Description

Internal documentation: https://www.notion.so/sentry/App-Launch-Profiling-a2c290334168466980bedc445f1fe237?pvs=4

**Comment by philipphofmann** [comment]
We should consider adding more app start spans for transactions with the new data we collect with this issue. Doesn't have to be done in the same issue, but worth considering.

**Comment by armcknight** [comment]
Could you elaborate? What else do you envision besides the app start spans we already gather? Are you talking about just starting them earlier?

**Comment by philipphofmann** [comment]
> What else do you envision besides the app start spans we already gather?

I don't know. I was just wondering if you get new data with profiling that we could attach as spans.

**Comment by armcknight** [comment]
We're just going to start the profiler as early as possible from a `+[load]` call, so whatever data we already gather today will be included with the app start spans.
