### ISSUE TITLE
Allow tweaking whether to capture stacktrace per event 

### ISSUE THREAD

**Issue by marcelofabri** [getsentry/sentry-cocoa#3386]
### Problem Statement

In our app, we've decided to not capture stacktraces by default, but allow developers to opt-in into capturing them on a per event basis.

We've been doing it by exposing this private method:

```objc
NS_ASSUME_NONNULL_BEGIN

@interface SentryClient(Additions)

- (SentryId *)sendEvent:(SentryEvent *)event
             withScope:(SentryScope *)scope
alwaysAttachStacktrace:(BOOL)alwaysAttachStacktrace;

@end

NS_ASSUME_NONNULL_END
```

We'd want for this to be officially supported so we can remove this fragile workaround.

### Solution Brainstorm

This probably could be a property on `SentryEvent` instead?

**Comment by brustolin** [comment]
We appreciate your suggestion @marcelofabri, we will discuss this with the team.

Valeu!

**Comment by philipphofmann** [comment]
We shouldn't add an extra parameter just for capturing the stacktrace for a single event. We have a similar use case for screenshots and view hierarchy. Other SDKs solve this by hints. I think we should add typed hints for these use cases.

**Comment by kahest** [comment]
Related: https://github.com/getsentry/sentry-cocoa/issues/2325

**Comment by philipphofmann** [comment]
For clarification, we will solve this problem with hints in #2325.
