### ISSUE TITLE
Add VisionOS Support for Carthage

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3410]
We don't have an xrOS slice in our xcframework deliverable as of Sentry 8.15.2. 

Support for VisionOS was added in Carthage 0.39.1 to add xrOS slices to xcframeworks. 

~The VisionOS SDK is still only delivered in the latest Xcode beta (15.1b3 released 14 Nov) and not the latest GA release version (15.0.1), and we don't currently use betas in our release job. (In fact, we're still running Xcode 14.3 for building the xcframework: https://github.com/getsentry/sentry-cocoa/issues/3411.)~ UPDATE: there is movement on this front, now that Xcode 15.2 is out with GA support for VisionPro/xrOS, and GitHub has a prerelease actions runner with the requisite OS/toolchains: https://github.com/getsentry/sentry-cocoa/issues/3410#issuecomment-1895609078

Part of us upgrading to Xcode 15.2 in CI will overlap with https://github.com/getsentry/sentry-cocoa/issues/3329

After we support VisionOS for Carthage, we need to update the docs https://github.com/getsentry/sentry-docs/pull/8496/.

**Comment by brustolin** [comment]
All we need to do is start using a Xcode that has visionOS support, but I don't recommend using a beta one to release our official XCFramework artefact.

**Comment by philipphofmann** [comment]
> Xcode that has visionOS support

Only Xcode beta has support, which doesn't run on GH actions.

**Comment by philipphofmann** [comment]
For now our users can do the following to build their own XCFramwork with visionOS support by using Xcode beta:

1. Download Xcode beta
2. Ensure to have all bet platforms installed you want for Xcode (iOS 17.2, tvOS 17.2, vision 1.0)
3. Select the Xcode beta version with something like `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/`
4. Checkout the Sentry Cocoa GH repository
5. Call `make init`
6. Then call `make build-xcframework` which will compile the XCFramework

**Comment by marksands** [comment]
We're trying to build locally, but keep running into this issue:

```
/path/to/Sources/Sentry/include/SentrySwift.h:4:9: fatal error: module 'SentryPrivate' not found
@import SentryPrivate;
 ~~~~~~~^~~~~~~~~~~~~
1 error generated.
```

Any advice on how to fix this? We're running the Makefile commands as given in the instructions, with the downloaded source, so there shouldn't be any differential here.

**Comment by marksands** [comment]
Ok interesting finding...

This succeeds:
```
xcodebuild -workspace /Users/mark.sands/Downloads/sentry-cocoa-8.3.2/Sentry.xcworkspace -scheme Sentry -configuration Release -sdk iphoneos archive
```

This fails:
```
xcodebuild -workspace /Users/mark.sands/Downloads/sentry-cocoa-8.3.2/Sentry.xcworkspace -scheme Sentry -configuration Release -sdk xros archive
```

So we're currently looking for an incompatibility with some xros setting.

**Comment by marksands** [comment]
We figured it out! For some reason, `$(SDKROOT__CARTHAGE_$(CARTHAGE))` wasn't being fully defined for us, so we hardcoded `SDKROOT = macosx` locally to get the intermediate frameworks to build for xros. I'm not sure if this had to do with a Carthage change, since we had to use 0.39.1 to build with it. Hope that helps!

**Comment by samwu888** [comment]
Mark is out today but this was another issued we encountered 

We were able to work around that issue, but another one that came up is when we were trying to link the SentrySwiftUI framework to our app targets.
"ld: linking against a dylib which is not safe for use in application extensions: /Users/jenkins/workspace/ios_Dominguez_PR-14846/build/Build/Products/Debug-appletvsimulator/SentrySwiftUI.framework/SentrySwiftUI"
This error came up for all of our platform targets except visionOS, which was odd. It definitely could be related to how we built it with our workaround above, but just in case, I'm adding that to the discussion. Thanks!

**Comment by kahest** [comment]
Hi @marksands & @samwu888 - thank you for the details! To clarify, are you currently blocked, and if so, on which platform(s)? Also, is the version in the snippet above (`sentry-cocoa-8.3.2`) correct? Did you try using a more recent version of the SDK?

**Comment by kahest** [comment]
> All we need to do is start using a Xcode that has visionOS support, but I don't recommend using a beta version to release our official XCFramework artefact.

Xcode 15.2 GM has been [released yesterday](https://xcodereleases.com/), which is the first official Xcode release with full visionOS support. We can now test and work towards supporting this.

**Comment by kahest** [comment]
There's a pre-release macos-13 runner-image with Xcode 15.2 available now: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240114.1
