### ISSUE TITLE
Filter emails in URLs correctly

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3417]
### Description

Before tackling this, check if we already do this by checking the test cases in https://github.com/getsentry/team-sdks/issues/39.

See https://github.com/getsentry/team-sdks/issues/39.

**Comment by brustolin** [comment]
We already remove user and password from the URL with this class: https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Swift/Tools/UrlSanitized.swift
