### ISSUE TITLE
Crash due to Sentry Profiler

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry-cocoa#3426]
### Platform

iOS

### Environment

Production, Develop

### Installed

Swift Package Manager

### Version

8.13.0

### Steps to Reproduce

1. Enable Sentry Profiler
2. Instrument span manually
3. Call SentrySpan.finish()

### Expected Result

Span finishes 

### Actual Result

Fatal crash -> EXC_BAD_ACCESS 

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1996) by [Unito](https://www.unito.io)

**Comment by philipphofmann** [comment]
The crash happens in `sliceGPUData`. We have a few crashes the SDK crashes: https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+sliceGPUData&referrer=issue-list&sort=user&statsPeriod=14d

**Comment by kahest** [comment]
@philipphofmann as far as I see [no instances of this in 8.14/8.15](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+sdk.version%3A%5B8.14.1%2C8.14.2%2C8.15.0%2C8.15.1%2C8.15.2%2C8.13.0%5D+sliceGPUData&referrer=issue-list&sort=freq&statsPeriod=90d). Most events only showed up in 8.13.0

**Comment by philipphofmann** [comment]
Okay, I marked this crash as resolved in Sentry. @gid-sentry, please tell the user to update to the latest SDK version and please reopen the issue if it persists.
