### ISSUE TITLE
Transactions Missing for ViewControllers

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-cocoa#3434]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.15.2

### Steps to Reproduce

sdk setup

```
      let sampleRate = NSNumber(value: self.configurationProvider.sampleRateNormalized)
      options.dsn = self.configurationProvider.dsn
      options.dist = self.configurationProvider.buildNumber
      options.environment = self.configurationProvider.environment
      options.releaseName = self.configurationProvider.releaseName
      options.sampleRate = sampleRate
      options.sendDefaultPii = self.configurationProvider.sendDefaultPII
      options.enableTracing = true
      options.attachStacktrace = true
      options.tracesSampleRate = sampleRate
      options.enableAutoSessionTracking = true
      options.enableAutoPerformanceTracing = true
      options.debug = true // Enabled debug when first installing is always helpful
```

"seeing log messages like: 
(contact me for details as it lists their App's ViewController names)"
```
The following UIViewControllers will generate automatic transactions: 
...
```

"Couple of strange things here:
1. there are by my count >200 VC files in the app and immediate MyApp's dependencies.
2. The [docs for automatic view controller ](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/)tracing say However, the SDK doesn't capture transactions for UIViewControllers of third-party libraries or SwiftUI. But a few of these are from the third party Google Places pod (the ones starting with GMS)"

"I suspect part of this is that Sentry thinks that some of MyApp's own cocoapods are external dependencies and is thus excluding them. When I exclude VCs from these modules from the count there are about 40 VCs total in the main part of the app. However only 18 of these are showing up in the list of automatically instrumented VCs"

"Also some of the items in the list above are from MyApp's pods, so I'm a bit confused"

"I'm also seeing quite a lot of `Was waiting for timeout for UI event trace but it had no children, will not keep transaction.` in the logs when I navigate around the app."

"I also had set up some filters on the integrations using options.integrations , but I've removed that for now."

"Also tried options.enableUIViewControllerTracing = true"

"Ok I think part of it is that we need to add includes for the VCs not part of the main app bundle. This still doesn't fully explain the patterns we're seeing though"

### Expected Result

Transactions for their ViewControllers

### Actual Result

Transactions for 18 out of 40 ViewControllers.

**Comment by kahest** [comment]
> "I'm also seeing quite a lot of Was waiting for timeout for UI event trace but it had no children, will not keep transaction. in the logs when I navigate around the app."

We start transactions for certain UI events and wait for other traceable events (e.g. core data queries, http requests, other things we instrument) to happen, and attach these traceable events as spans to the transaction. If there are no traceable events (because there are none or we don't instrument them), the transaction is dropped because it does not have child spans. Depending on how the app is built, this can account for VCs not showing up.

**Comment by brustolin** [comment]
Hello @thinkocapo thanks for reaching out.

Can you test the following code snippet with one of the View controllers that should be tracked but it's not:

```swift
         if let c_vcBinary = class_getImageName(ViewController.self), //View controller to test
           let c_appBinary = class_getImageName(AppDelegate.self) //You app delegate, assuming it is in the main bundle
        {
            let vcBinary = String(cString: c_vcBinary)
            let appBinary = String(cString: c_appBinary)
            if vcBinary != appBinary {
                print("View controller not in the main bundle")
            }
            print("View controller binary = \(vcBinary) \nApp Binary = \(appBinary)")
        } else {
            print("Could not get classes image name")
        }
```

**Comment by brustolin** [comment]
I verified that we're not swizzling view controller in external binaries, even if those binaries are included in the `inAppIncludes` options. But we do start transactions based on this vcs because we swizzle `[UIViewController LoadView:]`. So the transaction hangs forever.
