### ISSUE TITLE
Unable to find a specification for `Sentry (~> 8.16)`

### ISSUE THREAD

**Issue by haripacewisdom** [getsentry/sentry-cocoa#3444]
### Platform

iOS

### Environment

Production

### Installed

CocoaPods

### Version

8.16

### Steps to Reproduce

target 'MyApp' do
  pod 'Sentry', '~> 8.16'
end

pod install -> run in terminal

### Expected Result

Need to install pod successfully 

### Actual Result

<img width="575" alt="Screenshot 2023-11-23 at 10 51 57 AM" src="https://github.com/getsentry/sentry-cocoa/assets/106529932/2d17946f-ff37-4120-8c5f-9ba08a3cd15b">

**Comment by philipphofmann** [comment]
@haripacewisdom, please try running `pod repo update` or `pod install --repo-update` and try again. If it doesn't work, please reopen the issue.
