### ISSUE TITLE
Why is the stack fragment missing and the function doesn't know what to call?

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3449]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

Directly launch the app and read the log。Cold start time, complete restart of the app is not statistics, under what conditions will trigger the cold start？

### Expected Result

<img width="764" alt="截屏2023-11-27 17 28 27" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/de050af5-54c1-4c67-99c0-e826885b5733">
<img width="1137" alt="截屏2023-11-27 17 29 04" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/cd99ba88-c2ee-47c8-a208-ac3a3e202668">

### Actual Result

<img width="899" alt="截屏2023-11-27 16 53 15" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/5a83ef76-9f2b-435c-8d8d-10eb6457c7e2">
<img width="1299" alt="截屏2023-11-27 16 53 58" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/5f20f102-961f-4735-9f86-c106008c3734">

**Comment by brustolin** [comment]
Hello @zhou934381967 Can you explain a little bit more what are you looking for? I did not get your problem.

PS: `Missing span instrumentation` in the transaction only means there's is nothing happening that is being tracked at the moment. Usually is an animation happening before `uiViewDidAppear` is called

**Comment by zhou934381967** [comment]
1. It is found that this piece of information in the statistical problem is lost because it takes a long time to think that there is a performance problem?
2. Cold start time. In what scenario will this statistic be triggered?
3. There are a lot of UnKnown in the function call stack, why is this one?

**Comment by zhou934381967** [comment]
The console keeps printing the "CPU usage:" log. Is there any way to turn it off?

**Comment by brustolin** [comment]
> 1. It is found that this piece of information in the statistical problem is lost because it takes a long time to think that there is a performance problem?

There is nothing lost in here, you can ignore this `missing span instrumentation` warning. 

> 2. Cold start time. In what scenario will this statistic be triggered?

Cold start happens when the app start from scratch. When no part of it is residing in the memory.

> 3. There are a lot of UnKnown in the function call stack, why is this one?

Did you upload the debug symbols from your project? Can you share a print screen of this happening so I have more context to help you.

**Comment by zhou934381967** [comment]
2. Delete the App from the phone, but the restarted App still does not report the cold start time. What is the reason? Is there a reporting mechanism for this?
3. Upload debugging symbol.

**Comment by zhou934381967** [comment]
Do you need special configuration for reporting problems in China? At present, we have not received the reported data.

**Comment by brustolin** [comment]
@philipphofmann do you have any idea on item 2: Cold start info not appearing.

> 3. Upload debugging symbol.

I believe that those "unknown" frames in your profiling graph don't belong to the app itself.

**Comment by zhou934381967** [comment]
Hello, the interface in China reported a data timeout. This DSN cannot be accessed. Do you still need to do data transfer processing?

**Comment by brustolin** [comment]
> Hello, the interface in China reported a data timeout，This DSN cannot be accessed， Do you still need to do data transfer processing?

If I understand this right, there is some problem for you app to send the data to Sentry. Is this the problem?

**Comment by zhou934381967** [comment]
> > 您好，国内接口报数据超时，无法访问该DSN，请问还需要做数据传输处理吗？
> 
> 如果我理解正确，那么您的应用程序将数据发送到 Sentry 时存在一些问题。这是问题所在吗？

The data cannot be sent normally due to the network limitation in China, can it only be solved through the relay server?

**Comment by brustolin** [comment]
Im not sure how this DNS problem can affect you. Your project seems to work fine since you're getting some issues at Sentry.io.
