### ISSUE TITLE
Cold start and hot starts are inaccurate

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3457]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

1. If no App is installed on the phone, start the App.
2. The App has been installed in the mobile phone, start the App;

### Expected Result

See cold start and hot start times in performance monitoring。

### Actual Result

Do not see the cold start time and hot start time, do not know what the statistical rule is, every start will be counted?

**Comment by brustolin** [comment]
Hello @zhou934381967 you can try this experimental feature to get app start information: https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#app-start-tracing
