### ISSUE TITLE
Provide a sentry SPM package without UIKit

### ISSUE THREAD

**Issue by Descartess** [getsentry/sentry-cocoa#3460]
### Problem Statement

We use sentry over SPM and we would like an out-of-the-box sentry package without UIKit available.  Is this possible?

### Solution Brainstorm

We could duplicate the current target in` Package.swift` and set relevant GCC_PRE_PROCESSOR_DEFINITIONS as follows 

```
.target(
            name: "SentryNoUIKit",
            dependencies: ["SentryPrivate"],
            path: "Sources",
            sources: [
                "Sentry/",
                "SentryCrash/"
            ],
            publicHeadersPath: "Sentry/Public/",
            cxxSettings: [
                .define("SENTRY_NO_UIKIT", to: "1"),
                .define("GCC_ENABLE_CPP_EXCEPTIONS", to: "YES"),
                .headerSearchPath("Sentry/include"),
                .headerSearchPath("Sentry/include/HybridPublic"),
                .headerSearchPath("Sentry/Public"),
                .headerSearchPath("SentryCrash/Installations"),
                .headerSearchPath("SentryCrash/Recording"),
                .headerSearchPath("SentryCrash/Recording/Monitors"),
                .headerSearchPath("SentryCrash/Recording/Tools"),
                .headerSearchPath("SentryCrash/Reporting/Filters"),
                .headerSearchPath("SentryCrash/Reporting/Filters/Tools"),
                .headerSearchPath("SentryCrash/Reporting/Tools")
            ]
        ),
        ```

### Are you willing to submit a PR?

Yes

**Comment by philipphofmann** [comment]
Since v [8.14.1](https://github.com/getsentry/sentry-cocoa/blob/main/CHANGELOG.md#8140), you should be able to use the SDK without linking UIKit. You shouldn't have to use an extra SPM package. Please reopen the issue if that doesn't solve your problem.

**Comment by philipphofmann** [comment]
@armcknight, you came up with the fix. I think nothing is required from the user side if I'm not mistaken. If not, can you please explain? We must put this info into the docs as well if we didn't do this already.

**Comment by philipphofmann** [comment]
Yes, changelog makes sense 👍. 

> We might have to refactor UIKit-based code into a separate target from the Sentry framework target, something like SentryUIKit, as we initially had discussed as a possibility, so it can be omitted from SPM linkages.

Yes, the proper way to do this is to split Sentry into a core version without UIKit or other dependencies, something like SentryCore (I'm sure there could be a better name), and then have the default with UIKit. But that's a more significant refactoring.
