### ISSUE TITLE
Crashed when SentrySDK.start in iOS

### ISSUE THREAD

**Issue by jimmy-sqe** [getsentry/sentry-cocoa#3462]
### Platform

iOS

### Environment

Production

### Installed

CocoaPods

### Version

8.13.0

### Steps to Reproduce

1. Call SentrySDK.start

And crash happens

This is the logs
```
Fatal Exception: NSRangeException
0  CoreFoundation                 0x9cb4 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  CoreFoundation                 0x1aff84 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x25534 -[__NSArrayM objectAtIndexedSubscript:]
4  GarasiDealer                   0x4cacf0 -[SentryBinaryImageCache binaryImageAdded:] + 48 (SentryBinaryImageCache.m:48)
5  GarasiDealer                   0x4cab88 binaryImageWasAdded + 107 (SentryBinaryImageCache.m:107)
6  GarasiDealer                   0x4d5690 binaryImageAdded + 111 (SentryCrashBinaryImageCache.c:111)
7  ???                            0x1e0668aec (Missing)
8  ???                            0x1e0662e84 (Missing)
9  ???                            0x1e069fefc (Missing)
10 GarasiDealer                   0x4d559c sentrycrashbic_startCache + 166 (SentryCrashBinaryImageCache.c:166)
11 GarasiDealer                   0x524384 +[SentrySDK startWithOptions:] + 154 (SentrySDK.m:154)
12 GarasiDealer                   0x524484 +[SentrySDK startWithConfigureOptions:] + 166 (SentrySDK.m:166)
13 GarasiDealer                   0x599488 SqeIdSDK.init(clientId:mobileClientId:env:analytic:) + 64 (SqeIdSDK.swift:64)
```

### Expected Result

Not crashed

### Actual Result

Crashed when start SentrySDK

**Comment by philipphofmann** [comment]
I also see this happening in our [internal SDK crashes](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+binaryImageAdded&referrer=issue-list&sort=user&statsPeriod=7d) from time to time. I can reproduce this. PR is here https://github.com/getsentry/sentry-cocoa/pull/3468

**Comment by jimmy-sqe** [comment]
Thank you @philipphofmann for notifying and responding this, can it be released soon? in which version of Sentry? since we have tight deadline for making it work, Thank you.

**Comment by philipphofmann** [comment]
@jimmy-sqe, I plan on doing a hotfix today. This will be in 8.17.1.

**Comment by philipphofmann** [comment]
@jimmy-sqe, release is out https://github.com/getsentry/sentry-cocoa/releases/tag/8.17.1.
