### ISSUE TITLE
Set operation app.start.* for app start transaction

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3466]
### Description

See https://github.com/getsentry/team-mobile/issues/161.

For the next major, we could even consider making this the default behavior.

**Comment by markushi** [comment]
FYI: Based on our [internal discussions](https://sentry.slack.com/archives/C05U0THDQMD/p1701781027839679) we decided to not change the txn op, avoiding this breaking change in behavior.

**Comment by philipphofmann** [comment]
So, I guess we can close this @markushi? If not, please reopen.
