### ISSUE TITLE
Allow null or omitted DSN

### ISSUE THREAD

**Issue by rk-for-zulip** [getsentry/sentry-cocoa#347]
Per the [meta-SDK docs](https://docs.sentry.io/development/sdk-dev/overview/#usage-for-end-users), an "empty" DSN should be accepted in order to disable the SDK. (Or at least to set a no-op client as the default client.)

Taken literally, I suppose that means the empty string; but most languages' SDKs seem to be okay with some flavor of null:

* The Java SDK [explicitly accepts `null`](https://github.com/getsentry/sentry-java/issues/574), but also [happens to allow the empty string](https://github.com/getsentry/sentry-java/blob/dae5e1326a512f229488e382899ee63b204739b3/sentry/src/main/java/io/sentry/dsn/Dsn.java#L101).
* The Python SDK is okay with [either an empty string or None](https://github.com/getsentry/sentry-python/blob/44b8949fe2ff0f6319dd586d15c3e76b239971d6/sentry_sdk/transport.py#L260).
* The Rust SDK doesn't take a string option directly, but [does explicitly accept `None`](https://github.com/getsentry/sentry-rust/blob/fdba3279124ec129457c6a830cef927825b5d232/src/client.rs#L50), and [converts empty strings to that](https://github.com/getsentry/sentry-rust/blob/78c7c025fb2cc3c7a9464c54763b9542f685b45d/src/client.rs#L282).
* The JavaScript SDK [just lets you omit the `dsn` option entirely](https://github.com/getsentry/sentry-javascript/blob/feb00cfe71c964a7fdfc742377f8f67433e1eda9/packages/types/src/options.ts#L25).

**Comment by fetzig** [comment]
You’re right. We are currently working on the next major release (5.x), which will be in line with the so-called “Unified API” (https://docs.sentry.io/development/sdk-dev/unified-api/).
For clarification: What you call “meta-SDK docs” are the SDK Developer docs/guides.

see the #339 PR to check how things are going with the 5.x version.

**Comment by philipphofmann** [comment]
This works since at least `5.1.6`. You can do the following and the SDK won't send any events:
```
SentrySDK.start { options in
    // options.dsn = "DSN"
    options.beforeSend = { event in
        return event
    }
    // ...
}
```
