### ISSUE TITLE
Configurable number of call stack frames beyond the set limit for the crashing thread

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry-cocoa#3475]
### Problem Statement

Often the call stack frames on the crashing thread may contain hundreds of frames. The cocoa SDK limits the stack by default to 100 frames and drops the other frames the middle of the stack.
We would like to have the option to retain as many frames as possible (perhaps at the expense of other threads).

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2019) by [Unito](https://www.unito.io)

**Comment by philipphofmann** [comment]
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/1923, @idosun. If an important customer needs this, we can have a chat about that to bump the priority.
