### ISSUE TITLE
In non-debug mode, log is always displayed

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3484]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

options.debug = false，Direct run item

### Expected Result

Don't keep printing this log。 "CPU usage: "

### Actual Result

log "CPU usage: ". Keep printing this log, which is very difficult to debug。Which version can be resolved？
<img width="616" alt="截屏2023-12-06 18 29 00" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/d00146d2-365c-45a8-a7ed-762bcb571ca3">

**Comment by philipphofmann** [comment]
We fixed this with #3227 released in [8.10.0](https://github.com/getsentry/sentry-cocoa/blob/main/CHANGELOG.md#8100).
