### ISSUE TITLE
Spotlight support

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#3491]
### Description

Project board: https://github.com/orgs/getsentry/projects/165/views/1

Support for: https://spotlightjs.com/

Other SDK implementations for reference:
- Ruby: https://github.com/getsentry/sentry-ruby/pull/2175/
- Python: https://github.com/getsentry/sentry-python/pull/2524
- PHP: https://github.com/getsentry/sentry-php/pull/1647
- Node https://github.com/getsentry/sentry-javascript/pull/9629
- .NET https://github.com/getsentry/sentry-dotnet/pull/2961

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3642
```

**Comment by buenaflor** [comment]
FYI: screenshots cannot be processed currently by the spotlight overlay, on flutter we currently remove the attachment item from the envelope before sending it. https://github.com/getsentry/spotlight/issues/274
