### ISSUE TITLE
Manually handled sessions do not automatically get state marked

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry-cocoa#3498]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.17.0

### Steps to Reproduce

1. Sessions are manually created as app comes into foreground.
2. Sessions are manually ended as app goes into background if media playback isn't ongoing, after 30 seconds.
3. Unhandled crashes occur.

### Expected Result

Manual sessions get marked as crashed automatically/ other states dependent on crash.

### Actual Result

Manual sessions remain healthy/ potentially aren't being finished when crashes occur.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2040) by [Unito](https://www.unito.io)

**Comment by philipphofmann** [comment]
When the SDK calls the hub to capture crash events, it only updates the session state if `autoSessionTracking` is enabled.

https://github.com/getsentry/sentry-cocoa/blob/e02158b007e2c4bca924ca25c5b75d8860a22c43/Sources/Sentry/SentryHub.m#L246-L269

When users manually start and end sessions, the SDK doesn't mark sessions as crashed when capturing crash events. That's a bug and we need to fix it.
