### ISSUE TITLE
slicedProfileSamples(NSArray<SentrySample*>*, unsigned long long, unsigned

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3509]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

Have a Crash

### Expected Result

no crash

### Actual Result

Have a Crash。
<img width="1070" alt="截屏2023-12-19 12 07 54" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/872e07f6-83e3-469e-bd8e-bdb0331d34c6">

**Comment by philipphofmann** [comment]
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3486, which still needs to be fixed.
