### ISSUE TITLE
-[SentryProfilerState appendBacktrace:]_block_invoke

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3510]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

have a crash.

### Expected Result

no crash 

### Actual Result

Have a Crash.
<img width="1082" alt="截屏2023-12-19 12 09 13" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/3ee3e9c9-e50e-4681-bec4-ec05d25221d7">

**Comment by zhou934381967** [comment]
Authentication error: The domain for your Google account (gmail.com) is not allowed to authenticate with this provider. Yes You cannot view the internal SDK crashes.

**Comment by kahest** [comment]
@zhou934381967 This is intended, it's a Sentry internal resource with additional context for this issue - you will not be able to open this.

**Comment by zhou934381967** [comment]
I can't see these internal crashes, and I don't know what other crashes are at present, and whether the crashes encountered by our project have been solved. Is there another way to get it? I also found that v8.17.2 performance monitoring data is not reported. What is the cause of this?

**Comment by kahest** [comment]
@zhou934381967 Correct, you cannot see these internal crashes. Currently, no further action is required from your side for the crashes you reported. We will investigate and let you know if we need more information from you.

If you miss performance data with 8.17.2, you can create a new issue, but make sure you provide sufficient information and be as specific as possible.

**Comment by philipphofmann** [comment]
@indragiek, could https://github.com/getsentry/sentry-cocoa/pull/3522 could also fix this issue?

**Comment by zhou934381967** [comment]
Has the problem been solved?

**Comment by philipphofmann** [comment]
@zhou934381967, yes, I think #3522 should fix the issue, which will be in the next release 8.19.0. Please reopen if it doesn't fix the issue.
