### ISSUE TITLE
[SentryFramesTracker recordTimestamp:value:array:]

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3511]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.9.6

### Steps to Reproduce

Direct use will appear.

### Expected Result

no crash.

### Actual Result

Have a Crash.
<img width="1074" alt="截屏2023-12-19 13 55 55" src="https://github.com/getsentry/sentry-cocoa/assets/13718172/5d7fb36f-0c97-4c2b-92ff-e53482b6dffc">

**Comment by philipphofmann** [comment]
Thanks again @zhou934381967.[ Internal SDK crashes reference](https://sentry.sentry.io/issues/4681246552/?project=4505469596663808&query=is%3Aunresolved+recordTimestamp&referrer=issue-stream&sort=user&statsPeriod=14d&stream_index=0).

**Comment by zhou934381967** [comment]
Authentication error: The domain for your Google account (gmail.com) is not allowed to authenticate with this provider. Yes You cannot view the internal SDK crashes.

**Comment by kahest** [comment]
@zhou934381967 This is intended, it's a Sentry internal resource with additional context for this issue - you will not be able to open this.

**Comment by zhou934381967** [comment]
Has the problem been solved?

**Comment by philipphofmann** [comment]
@zhou934381967, no we didn't fix the issue yet.
