### ISSUE TITLE
v8.17.2 Data is not reported  

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-cocoa#3517]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.17.2

### Steps to Reproduce

The Sentry version of the App is upgraded from v8.9.6 to v8.17.2, and No performance monitoring data is reported when the App is used normally?
 

### Expected Result

There are data reports, and all functions are functioning normally
 

### Actual Result

No performance monitoring data is reported?

**Comment by kahest** [comment]
Hey @zhou934381967, did you change any parts of how you configure Sentry? Can you post your Sentry initialization code? Also, do you use sentry.io or a self-hosted instance?

**Comment by zhou934381967** [comment]
No initial configuration is modified. Data is displayed in the Crash, but no data is displayed in the performance monitoring. Procedure I have emailed you feedback on the initial configuration that there is no problem, using Sentry.io。

**Comment by kahest** [comment]
Can you send that feedback to karl.struggl@sentry.io? And if you can, please also include a link to your project on sentry.io. Thank you!

**Comment by zhou934381967** [comment]
Feedback has been received, hope to investigate as soon as possible.

**Comment by kahest** [comment]
@zhou934381967 I replied to your email

**Comment by zhou934381967** [comment]
Could you please reply to the new question?

**Comment by zhou934381967** [comment]
Could you please reply to the new question?

**Comment by kahest** [comment]
As discussed via mail, the Performance Units quota was exceeded, no new Performance data will come in until volume is available again.
