### ISSUE TITLE
Expose Span baggage API

### ISSUE THREAD

**Issue by kabiroberai** [getsentry/sentry-cocoa#3519]
### Problem Statement

Sentry's server-side SDKs support [manually](https://docs.sentry.io/platforms/node/usage/distributed-tracing/custom-instrumentation/) tapping into Distributed Tracing, so long as you can pass along the `trace-header` and `baggage` values from the client. Unfortunately it seems that the Cocoa SDK only supports [automatic](https://github.com/getsentry/sentry-cocoa/blob/3297d6e29cd37151f68e9c605aea8b44e5e432cb/Sources/Sentry/SentryNetworkTracker.m#L206) injection of these headers into URLSession HTTP requests. This precludes the use of distributed tracing when swizzling is disabled / using a different HTTP mechanism / using non-HTTP transport (the latter being our use case.)

### Solution Brainstorm

sentry-cocoa has `-[SentrySpan toTraceHeader]` which gets us halfway there, but the other half — namely `SentryBaggage` — is currently private. It would be great if this were made public, just like sentry-python's [Span.to_baggage](https://github.com/getsentry/sentry-python/blob/647006398228a3d75128fb0471ec701e93884acf/sentry_sdk/tracing.py#L393) and sentry-node's [dynamicSamplingContextToSentryBaggageHeader](https://github.com/getsentry/sentry-javascript/blob/eadfd615f2461e395d3992b7345413e7420190e0/packages/utils/src/baggage.ts#L85).

We're currently working around this with some runtime spelunking:
```swift
extension Span {
    var baggage: String? {
        (self as? NSObject)?.value(forKeyPath: "tracer.traceContext.toBaggage.toHTTPHeader") as? String
    }
}
```
but of course it would be ideal if this were a stable, public API.

### Are you willing to submit a PR?

Happy to submit a PR if you're good with this being public! Just want to be sure of the API surface — whether you'd rather expose all of SentryBaggage or just the NSString representation.

**Comment by philipphofmann** [comment]
If I got it right, all you need is  `SentryBaggage`, `SentryTraceContext` and `SentryTraceContext.toBaggage` being public, @kabiroberai? [Baggage](https://github.com/getsentry/sentry-java/blob/937879e7bffe6eceeb2ed339971da869fd0df542/sentry/src/main/java/io/sentry/Baggage.java#L27) and [TraceContext](https://github.com/getsentry/sentry-java/blob/937879e7bffe6eceeb2ed339971da869fd0df542/sentry/src/main/java/io/sentry/TraceContext.java#L14) are also public on Java. @brustolin, can you think of any reason for keeping these two classes private?

**Comment by kabiroberai** [comment]
> all you need is `SentryBaggage`, `SentryTraceContext` and `SentryTraceContext.toBaggage` being public

I think you'll also want to expose a way to obtain `SentryTraceContext` from a `SentrySpan` (`tracer.traceContext` / `-[SentryTraceContext initWithSpan:]` / etc) but that's about it yep!

**Comment by brustolin** [comment]
>  @brustolin, can you think of any reason for keeping these two classes private?

No, I don't see why this could not be public.

**Comment by denrase** [comment]
Here's an example on how this might be used. The sample assumes that a custom http request is made, without sentry amending it automatically. Also this is creating a new transaction, but users might also use `SenrySDK.span` if they want to get the info from there.

```swift
func requestWithManualTraceAndBaggageHeader() async {
    let span = SentrySDK.startTransaction(name: "manual", operation: "op")
    
    let traceHeader = span.toTraceHeader().value()
    
    guard let baggageHeader = span.baggageHttpHeader() else {
        return
    }
    
    var request = URLRequest(url: URL(string: "https://example.com/api/a")!)
    request.httpMethod = "GET"
    request.setValue(traceHeader, forHTTPHeaderField: SENTRY_TRACE_HEADER)
    request.setValue(baggageHeader, forHTTPHeaderField: SENTRY_BAGGAGE_HEADER)

    do {
        let (data, response) = try await URLSession.shared.data(for: request)
        ...
    } catch {
        print("Error: \(error)")
    }
    
    span.finish()
}
```

\cc @kahest
