### ISSUE TITLE
Allow both error domain and description customization

### ISSUE THREAD

**Issue by fluomonkey** [getsentry/sentry-cocoa#3521]
### Problem Statement

Following the documentation (at https://docs.sentry.io/platforms/apple/usage/#capturing-errors) I figured out how to implement a custom error description, but in a realistic scenario where errors come from dependencies/modules, implement CustomNSError protocol for all the errors of all the app dependencies is impossible.

This result in 2 problems:
1. I have no control over error domain name (resulting in no control over the error grouping in Sentry UI)
2. I can't customize the description avoiding the implementation of CustomNSError protocol for all the errors of my app

I want to automatize this process so my current implementation consist of a wrapper that convert the original Swift Error (coming from a dependency) in a CustomNSError, but here I fount a problem: CustomNSError.errorDomain is static and I can't dynamically assign it.

### Solution Brainstorm

A possible solution consist of set CustomNSError.errorDomain property as non static.

Another good solution consist of a new method `SentrySDK.captureError(domain: description:)`

**Comment by brustolin** [comment]
Thanks @fluomonkey  for reaching out. We will discuss your suggestions with the team.

**Comment by philipphofmann** [comment]
> I want to automatize this process so my current implementation consist of a wrapper that convert the original Swift Error (coming from a dependency) in a CustomNSError, but here I fount a problem: CustomNSError.errorDomain is static and I can't dynamically assign it.

You can also build your own NSError object from the error object of your external libraries. The following code changes the domain but keeps the original error code and it adds a custom description:

```Swift
do {
    // Something that throws
} catch {
    let nsError = error as NSError
    let myError = NSError(domain: "your domain", code: nsError.code, userInfo: [NSDebugDescriptionErrorKey : "my custom description"])
    SentrySDK.capture(error: myError)
}
```

This then looks like this in Sentry:
![CleanShot 2024-01-02 at 10 25 53@2x](https://github.com/getsentry/sentry-cocoa/assets/2443292/0751ec50-a242-4d8d-975c-2e24654c1593)


We will add a section to the docs to explain this scenario. I don't think a new method such as `SentrySDK.captureError(domain: description:)` makes sense as you can pass in an NSError object that contains all the required information. Please reopen the issue if the response doesn't solve your problem.

**Comment by philipphofmann** [comment]
Related docs PR https://github.com/getsentry/sentry-docs/pull/8784.
