### ISSUE TITLE
Ability to modify tracesSampleRate in runtime.

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry-cocoa#3527]
### Problem Statement

Using a remote config to modify the tracesSampleRate, but that requires the app to be relaunched in order for Sentry to be re-initialized and then set a new sampling rate. 

A possible workaround would be using `beforeSend`, at least before it splits up into `beforeSendTransaction`, but that requires implementing a custom sampling solution and would be more work than just calling an API if it were possible.

### Solution Brainstorm

Something like a modification to: https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/SentryTracesSampler.m#L67-L68 to:

```
   if (updatedTracesSampleRate != nil) {
            return [self calcSample:updatedTracesSampleRate.doubleValue];
        }
        else if (_options.tracesSampleRate != nil) {
            return [self calcSample:_options.tracesSampleRate.doubleValue];
        }
```

Where updatedTracesSampleRate is a property that is initialized from the value in _options but provides some api to be updated at runtime after initialization.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2058) by [Unito](https://www.unito.io)

**Comment by gid-sentry** [comment]
Internal JIRA ticket: https://getsentry.atlassian.net/browse/FEEDBACK-2059

**Comment by armcknight** [comment]
The workaround I'm imagining is to call `SentrySDK.close()` and then `SentrySDK.startWith...` and supply the new sample rate in the options block. 

To change the sample decision of a span that is in flight or already completed, yes, they could use `beforeSend`, they could look at `SentryEvent.type` to check if it is `"transaction"`.

Doesn't seem like it should be so hard to open up an API like `SentrySDK.setTransactionsSampleRate(...)`, though.

**Comment by philipphofmann** [comment]
They can use the tracesSampler to change the sample rate dynamically, also see [docs](https://docs.sentry.io/platforms/apple/performance/). Users must ensure that the call to `MyRemoteConfig.currentSampleRate` is fast because this will be called for every transaction.

```Swift
options.tracesSampler = { _ in
    let sampleRate = MyRemoteConfig.currentSampleRate
    return sampleRate
}
```
