### ISSUE TITLE
SwiftData: NSCompoundPredicate predicateOperatorType: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by sowenjub** [getsentry/sentry-cocoa#3553]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.18

### Did it work on previous versions?

no

### Steps to Reproduce

Use a SwiftData predicate that generates a ternary operator, in my case the code looks something like this

```swift
       let kinds: [AwardKind] = [.firstTime, .nightOwl]
       var descriptor = FetchDescriptor<Award>()
        let rawKinds = kinds.map(\.rawValue)
        
        descriptor.predicate = #Predicate<Award> { award in
            if let rawKind = award.rawKind {
                award.claimDate == nil && rawKinds.contains(rawKind)
            } else {
                award.claimDate == nil
            }
        }
```

### Expected Result

Not crash

### Actual Result

`Crash in - (NSString *)comparisonPredicateDescription:(NSComparisonPredicate *)predicate because - (NSString *)predicateOperatorTypeDescription:(NSPredicateOperatorType)operator doesn't support TERNARY operator`

**Comment by kahest** [comment]
Hey @sowenjub - I don't see a reason to believe this is caused by Sentry, can you explain? Did you try to reproduce without Sentry? To me it looks like the predicate and/or how it's used to query might be incorrect.

**Comment by sowenjub** [comment]
The query worked fine before I added Sentry, and still does if I don't init Sentry or if I disable Core Data tracing in the Sentry options.

The interruption points to Sentry code, the predicate includes a TERNARY operator which is not part of the supported operators in the function that crashes.

**Comment by kahest** [comment]
Ah yes you're right - we'll fix this, thanks for bringing it to our attention

**Comment by kahest** [comment]
Internal data points: https://sentry.sentry.io/issues/?project=4505469596663808&query=comparisonPredicateDescription&referrer=issue-list&statsPeriod=90d

**Comment by saulrodeo** [comment]
I also have this issue using SwiftData and compound Predicates: 

https://letsrodeo.sentry.io/issues/5092468581/?referrer=alert_email&alert_type=email&alert_timestamp=1711126918556&alert_rule_id=15065067&notification_uuid=663b00cb-dd71-4ded-84cd-86543d085aec&environment=production

It works when sentry is removed
