### ISSUE TITLE
Continuous profiling

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3555]
Today, a profile can last up to 30 seconds and must be transmitted attached to a transaction that ran concurrently with it. This was done in part to keep memory growth of the profiling data constrained.

This body of work will transition the SDK to being able to run the profiler continuously. Periodically, profiling data will be chunked and transmitted where it can be stitched together later in the backend using a profiling "instance" ID that is set each time the profiler is started. The profile payloads will record information about root spans that were active during the profile.

This will require refactoring the profiler itself, the interface between the profiler and the tracer, and the profile payload schema.

Internal tracking: https://www.notion.so/sentry/Continuous-Profiling-iOS-d354219c683545a6b2806de8eb8bde67?pvs=4

Planning doc: https://www.notion.so/sentry/Continuous-Profiling-9d64a809ed2d487b89e4aa0358bfac18?pvs=4

**Comment by cmanallen** [comment]
Closing due to being marked as done in the SDK project board.
