### ISSUE TITLE
Build fails when setting Apple Vision Pro as run Destination

### ISSUE THREAD

**Issue by 3no-mark** [getsentry/sentry-cocoa#3560]
### Platform

visionOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.18.0

### Did it work on previous versions?

Not tested

### Steps to Reproduce

1. Set Apple Vision Pro as a Supported Destination
2. Set Apple Vision Pro as run destination
3. Analyze

### Expected Result

Successful build

### Actual Result

"No such module Sentry" error

**Comment by philipphofmann** [comment]
I wasn't able to reproduce your problem, @3no-mark. I just tried adding Sentry 8.18.0 to an empty sample project with CocoaPods and running it on a visionOS simulator, and it worked. Also, running `Analyze` didn't throw any errors. Please provide more details so we can reproduce the issue.

**Comment by Fwang36** [comment]
hey @philipphofmann ,

The user here provided a minimal repro to me here in support.  [SentryVisionOSTest.zip](https://github.com/getsentry/sentry-cocoa/files/13992074/SentryVisionOSTest.zip)

They also explain that it -

> builds and runs with an iPhone simulator run destination, but with a run destination of Apple Vision Pro throws a build error of “No such module Sentry”.

I did a quick run and I believe the repro shows the error as the user describes. 

<img width="1000" alt="Screenshot 2024-01-19 at 12 06 07 PM" src="https://github.com/getsentry/sentry-cocoa/assets/96670625/d1b67fc9-65ce-4968-b56d-ea57cd91ee5a">

Can you take a look?

**Comment by 3no-mark** [comment]
Philip- I have been using CocoaPods for years and am well aware of Xcode opening via xcworkspace. Please open the attached repro. It throws a No such module 'Sentry' error. Mark
[SentryVisionOSTest.zip](https://github.com/getsentry/sentry-cocoa/files/14010766/SentryVisionOSTest.zip)

**Comment by 3no-mark** [comment]
Note that the same file compiles and builds successfully when an iOS simulator is selected as run destination.
<img width="1527" alt="Screenshot 2024-01-22 at 8 47 50 AM" src="https://github.com/getsentry/sentry-cocoa/assets/82984402/c252cdb2-1667-4924-bde1-0b41d441983a">

**Comment by philipphofmann** [comment]
You need to change the platform in the Podsfile to `platform :visionos, '1.0'`. Then it works. Setting up multiple platforms in a Podfile needs some special handling see
* https://github.com/CocoaPods/CocoaPods/issues/9566
* https://github.com/CocoaPods/CocoaPods/issues/11538

**Comment by 3no-mark** [comment]
That works. Thank you.

On Jan 23, 2024, at 7:10 AM, Philipp Hofmann ***@***.***> wrote:



You need to change the platform in the Podsfile to platform :visionos, '1.0'. Then it works. Setting up multiple platforms in a Podfile needs some special handling see

  *   CocoaPods/CocoaPods#9566<https://github.com/CocoaPods/CocoaPods/issues/9566>
  *   CocoaPods/CocoaPods#11538<https://github.com/CocoaPods/CocoaPods/issues/11538>
