### ISSUE TITLE
Client.shared?.reportUserException function does not work

### ISSUE THREAD

**Issue by christopherney** [getsentry/sentry-cocoa#357]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 4.0
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.1**

---
I have following issue:
Client.shared?.reportUserException function does not work

The following code send a catched error to Sentry Cocoa SDK

**Steps to reproduce:**
```swift
    /**
      Log an Error
      - Parameter error: Error to log
     */
    public static func error(error: NSError, file: String = #file, function: String = #function, line: Int = #line) {

        let name = String(describing: type(of: error))
        let fileName = (file as NSString).lastPathComponent
        let lineOfCode = "\(function) in file \(fileName) at line \(String(line))"
        let message = error.localizedDescription
        let stackTrace = Thread.callStackSymbols
        
        // Sentry.io
        Client.shared?.reportUserException(name,
                                           reason: message,
                                           language: "swift",
                                           lineOfCode: lineOfCode,
                                           stackTrace: stackTrace,
                                           logAllThreads: true,
                                           terminateProgram: false)
    }
```
**Actual result:**
- No error in client side whem calling the function reportUserException, but we never receive the error in Sentry web dashboard.

**Expected result:**
- We are expected to receive the error in our project dashboard.

**Comment by HazAT** [comment]
I just tried it and it worked just fine:

![screencapture-sentry-io-organizations-sentry-test-issues-1396408246-2019-12-19-13_03_03](https://user-images.githubusercontent.com/363802/71172265-07b92380-2260-11ea-8c87-d0bce2fb3705.png)

```swift
 let name = "test"
        let fileName = "test.swift"
        let lineOfCode = "bla in file \(fileName) at line 10"
        let message = "testmessage"
        let stackTrace = Thread.callStackSymbols
        
        // Sentry.io
        Client.shared?.reportUserException(name,
                                           reason: message,
                                           language: "swift",
                                           lineOfCode: lineOfCode,
                                           stackTrace: stackTrace,
                                           logAllThreads: true,
                                           terminateProgram: false)
```

Can you try to enable debug logging and see what's going on?
` Client.logLevel = .verbose`

**Comment by christopherney** [comment]
Thanks for your feedback, we will activate verbose log for next test.

In your side, did you call the *startCrashHandler* method before send an error ?

```swift
 try Client.shared?.startCrashHandler()
```
In our side, didn't call this *startCrashHandler* method, because we doesn't want track uncaught Exception. Is it possible ?

**Comment by fetzig** [comment]
@christopherney, you're right. using `reportUserException` required `startCrashHandler`. That's most definitely not the best interface. API will change in 5.x and improve for this particular use-case. But currently, that's all we got.
