### ISSUE TITLE
Xcode 15.3 reports that sentry is performing I/O on the main thread, which can lead to app hangs

### ISSUE THREAD

**Issue by erichoracek** [getsentry/sentry-cocoa#3575]
### Platform

iOS

### Environment

Production, Develop

### Installed

Swift Package Manager

### Version

8.19.0

### Steps to Reproduce

Initialize Sentry using an app built with the Xcode 15.3 Beta.

### Expected Result

Sentry initializes without runtime warnings emitted by Xcode.

### Actual Result

When initializing Sentry on apps built with the Xcode 15.3 Beta, we get the following runtime warning:

> This code path does I/O on the main thread underneath that can lead to Ul responsiveness issues. Consider ways to optimize this code path
>
> There are reports with code path containing +[SentryInstallation idWithCacheDirectoryPath:]
causing Ul hangs for AppStore and Testflight users

<img width="990" alt="Screenshot 2024-01-25 at 9 30 28 PM" src="https://github.com/getsentry/sentry-cocoa/assets/438313/34d5f404-f28e-4b00-a24d-fb3ad1c4333b">

**Comment by brustolin** [comment]
Thanks @erichoracek for reporting this.
We'll discuss the better way to solve this with the team.

**Comment by philipphofmann** [comment]
The SDK uses `SentryInstallation idWithCacheDirectoryPath` in three locations:

https://github.com/getsentry/sentry-cocoa/blob/30f88719192689aa16af26a608618b857f59b9c5/Sources/Sentry/SentryHub.m#L109-L110

https://github.com/getsentry/sentry-cocoa/blob/30f88719192689aa16af26a608618b857f59b9c5/Sources/Sentry/PrivateSentrySDKOnly.mm#L64-L67

https://github.com/getsentry/sentry-cocoa/blob/30f88719192689aa16af26a608618b857f59b9c5/Sources/Sentry/SentryClient.m#L748-L757

The file IO operation only happens once when starting the SDK. In most cases in `SentryHub startSession`. I guess around 99% of the time our users interact with the static API `SentrySDK`. In that case, we could call `SentryInstallation idWithCacheDirectoryPath` in `SentrySDK start` on a background thread to cache the value. All subsequent calls will then call the cache; no file IO will happen. Adding something like to `SentrySDK start` and tests could solve the issue:
```
[SentryDependencyContainer.sharedInstance.dispatchQueueWrapper dispatchAsyncWithBlock:^{
        [SentryInstallation idWithCacheDirectoryPath:options.cacheDirectoryPath];
    }];
```
