### ISSUE TITLE
Could not get NSFileTypeDirectory, Couldn't load files in folder [envelopes]

### ISSUE THREAD

**Issue by lockieluke** [getsentry/sentry-cocoa#3577]
### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.19.0

### Steps to Reproduce

1. Start a sentry session using the following configuration
```swift
SentrySDK.start { options in
    options.dsn = Bundle.main.object(forInfoDictionaryKey: "SENTRY_DSN_URL") as? String
    #if DEBUG
    options.debug = true
    options.diagnosticLevel = .warning
    #endif
	// Diagnostic.isDebug is simply a #if DEBUG macro
    options.environment = Diagnostic.isDebug ? "debug" : "production"
    
    // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
    // We recommend adjusting this value in production.
    options.tracesSampleRate = 1.0
    
    options.attachStacktrace = true
    options.enableMetricKit = true
    options.enableTimeToFullDisplayTracing = true
    options.swiftAsyncStacktraces = true
}
```
2. Run your app
3. Look at the logs

### Expected Result

These errors should not exist

### Actual Result

```
[Sentry] [warning] [SentryFileManager:175] Could not get NSFileTypeDirectory from /Users/[username]/Library/Caches/io.sentry/.DS_Store
[Sentry] [error] [SentryFileManager:231] Couldn't load files in folder /Users/[username]/Library/Caches/io.sentry/[id]/envelopes: Error Domain=NSCocoaErrorDomain Code=260 "The folder “envelopes” doesn’t exist." UserInfo={NSFilePath=/Users/[username]/Library/Caches/io.sentry/[id]/envelopes, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x600000f1d0b0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
```

### Are you willing to submit a PR?

I have no idea what's causing this, I'm sorry I don't think I'll be able to fix this

**Comment by brustolin** [comment]
Hello @lockieluke, thanks for reporting this. Does your project have any function that cleans the cache folder during runtime?

**Comment by philipphofmann** [comment]
Hey @lockieluke, thanks for reporting this. I fixed the warning log for the `.DS_Store` file with https://github.com/getsentry/sentry-cocoa/pull/3584. For the second error message, answering the question of @brustolin (https://github.com/getsentry/sentry-cocoa/issues/3577#issuecomment-1914132798 )might be relevant.

**Comment by lockieluke** [comment]
> Hello @lockieluke, thanks for reporting this. Does your project have any function that cleans the cache folder during runtime?

Yes but I didn’t use that function when I was testing sentry, I mean except for the error in the logs, sentry seems to be working perfectly fine
