### ISSUE TITLE
Add `tunnel` option (sets the url used by transport)

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#3583]
### Description

Sets the URL that will be used to transport captured events. This can be used to work around ad-blockers or to have more granular control over events sent to Sentry.

- More details about the option in JS docs https://docs.sentry.io/platforms/javascript/configuration/options
- Related RN issue https://github.com/getsentry/sentry-react-native/issues/3258
- Related Java issue https://github.com/getsentry/sentry-java/issues/3174

**Comment by brustolin** [comment]
@krystofwoldrich 

It's possible for the user to use their own endpoint as DSN. The only requirement is that this endpoints contains a user, such like `https://user@myendpoint.com/sentrytunnel`

Can we close this issue?

**Comment by krystofwoldrich** [comment]
@brustolin I see, they can supply any URI that will parse as DSN, but that's more of a workaround.

We should either decide not to implement this in mobile SDKs, or add the `tunnel` option for users' convenience.

I'm for the latter since it should be a small change.

**Comment by pquerner** [comment]
Hi!
Is there any news regarding this?
We're using the Javascript SDK with the tunnel option and want to use it on our apps now aswell.

Thing is, our Sentry instance is not hooked up to the public internet.
A tunnel option comes to mind, just like for our Javascript.

On the javascript side everything is nice documentation on how to enable this, but here (and on the Android) SDK its missing.

**Comment by brustolin** [comment]
Hello @pquerner, thanks for reaching out.

Sentry for iOS now has a `urlSession` option that allows you to set your own request session. You can set delegates, a proxy, or any other configuration you want to add to it.

```swift
SentrySDK.start { option in
    // ... rest of the options
	option.urlSession = mySession
}
```

We believe `urlSession` option solves this request. If that is not the case we can reopen the issue.

**Comment by pquerner** [comment]
Hi @brustolin 

thanks for getting back to me.
However, I am stuck on how to use it and I am not really getting it when reading the original PR for it (#3811).

Is it possible to add information for this to the official docs?

Do I understand it correctly that when something is network transfered, it'll use this configuration. But how does the data look like? What do I have to do in the backend (the host that gets this data), to forward it to sentry? Is that exactly the same as described as in the JS SDK for `tunnel` ?

**Comment by pquerner** [comment]
Thanks brustolin,
however I think this is getting out of scope here.

I've created a disussion here https://github.com/getsentry/sentry-cocoa/discussions/4047
