### ISSUE TITLE
[Sentry] [error] [SentryCoreDataTracker:53] managedObjectContext:executeFetchRequest:error:originalImp: fetchSpan is nil.

### ISSUE THREAD

**Issue by Sathyan-KM** [getsentry/sentry-cocoa#3586]
### Platform

iOS

### Environment

Production, Develop

### Installed

CocoaPods

### Version

8.15.2

### Steps to Reproduce

1. integrate sentry into the app
2. Launch the app from Xcode
3. Check the logs on Xcode
After integration when I try to run the app in Xcode, I am getting the log `[Sentry] [error] [SentryCoreDataTracker:53] managedObjectContext:executeFetchRequest:error:originalImp: fetchSpan is nil.`
 continuously

### Expected Result

This should not happen

### Actual Result

Getting the error log in loop

**Comment by brustolin** [comment]
Hello @Sathyan-KM thanks for reporting this. 
Could you please explain a little bit about how you are using Core Data in your project? If possible, providing a reproduction would be very helpful for us to identify the problem.

**Comment by Sathyan-KM** [comment]
@brustolin I am using below function

```swift

        SentrySDK.start { options in
               options.dsn = "url"
               options.debug = true // Enabled debug when first installing is always helpful
                options.tracesSampleRate = 1.0

           }
```

nothing else

**Comment by Sathyan-KM** [comment]
@brustolin  There is one more issue,
A particular API is failing due to its size

```swift
https://o4506195255230464.ingest.sentry.io/api/4506222903427072/envelope/
```

error 
```
{
  "detail": "envelope exceeded size limits for type 'event' (https://develop.sentry.dev/sdk/envelopes/#size-limits)"
}
```

**Comment by brustolin** [comment]
> @brustolin I am using below function
> 
> ```swift
>         SentrySDK.start { options in
>                options.dsn = "url"
>                options.debug = true // Enabled debug when first installing is always helpful
>                 options.tracesSampleRate = 1.0
> 
>            }
> ```
> 
> nothing else

So you're not using core data in your project? It's just a new project with sentry added to it?

**Comment by Sathyan-KM** [comment]
Hi @brustolin ,
Yes nothing else. I have integrated sentry via cocoapod
```
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.15.2'
```
But I can see from podfile.lock that sentry core is added . but there is no other ref to sentry core in my project.

Thanks

**Comment by brustolin** [comment]
Since this is an empty project do you mind sharing it with us? It will be easier to reproduce the problem.

**Comment by michaeldcruz** [comment]
Hi - we're also running in to this same issue where the logs are printing out an error that fetchSpan is nil in `SentryCoreDataTracker` even though we are not using CoreData at all.

```
[Sentry] [error] [SentryCoreDataTracker:53] managedObjectContext:executeFetchRequest:error:originalImp: fetchSpan is nil.
[Sentry] [error] [SentryCoreDataTracker:53] managedObjectContext:executeFetchRequest:error:originalImp: fetchSpan is nil.
[Sentry] [error] [SentryCoreDataTracker:53] managedObjectContext:executeFetchRequest:error:originalImp: fetchSpan is nil.
```

I did have a CoreData model added to this project a while back but had removed it since. My SentrySDK initialization is fairly standard

```
        SentrySDK.start { options in
            options.debug = debug
            options.diagnosticLevel = .info
            options.dsn = sentryId
            options.environment = environmentName
            options.tracesSampleRate = debug ? 1.0 : 0.2
            options.swiftAsyncStacktraces = true
        }
```

We're running 8.24.0

Any other info I can provide to help debug this further?

**Comment by brustolin** [comment]
Hello @michaeldcruz, core data tracking is enabled by default. 
If you dont want to use it you have to set `enableCoreDataTracing` to false.

There is probably some OS core data fetch going on that does not have the Span. We will check how to deal with this.
