### ISSUE TITLE
Total Time to Initial Display is inaccurate for some views

### ISSUE THREAD

**Issue by mbabin** [getsentry/sentry-cocoa#3588]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.19.0

### Did it work on previous versions?

First time integrating Sentry into app with performance monitoring enabled.

### Steps to Reproduce

1. Added Sentry SDK to our project.
2. Configuration options:
```swift
    SentrySDK.start { options in
      options.dsn = <dsn>
      options.environment = <environment>
      options.tracesSampleRate = 0.1
      options.attachViewHierarchy = true
      options.enablePreWarmedAppStartTracing = true
      options.swiftAsyncStacktraces = true
    }
``` 
3. Ran app a few times to record performance information.

### Expected Result

Event details for a transaction recorded for our screens (Welcome -> Environment -> Login -> Select Workplace) would record total time to initial display for each screen.

### Actual Result

Event details show a total time for initial display for the initial screen, Welcome, as 30 seconds (does not match actual experience is use).

### Are you willing to submit a PR?

Not at this time.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2086) by [Unito](https://www.unito.io)

**Comment by mbabin** [comment]
Tried the same exercise with 8.17.2 and do not see the long TTID times reported. Interestingly, I do not see any transaction reported for the Welcome view with that version. I do see transactions reported for subsequent views (Environment, Login, Select Workplace).

No, we do not currently manually interact with the auto-generated transaction with `SentrySDK.span`.

**Comment by philipphofmann** [comment]
Thanks for the update, @mbabin.

**Comment by philipphofmann** [comment]
@mbabin, I checked the transaction of your `WelcomeViewController`, and it only displays spans for `loadView` and `viewDidAppear`. Our instrumentation didn't capture any spans for `viewDidLoad`, `viewWillAppear`, `viewDidAppear` that it usually does. That's unusual, and I'm having trouble understanding how that could be. How do you present your `WelcomeViewController`? From which UIViewController does it inherit? Do you see long-lasting TTID spans also for other UIViewControllers? If yes, please answer the same questions I asked for the `WelcomeViewController`.

I already made a fix with https://github.com/getsentry/sentry-cocoa/pull/3610 to get rid of the long-lasting TTID span, but it could be that there is another issue, and the long-lasting TTID span is only a side effect.
