### ISSUE TITLE
Remove usage of NSFileSystemFreeSize and NSFileSystemSize

### ISSUE THREAD

**Issue by tamwei** [getsentry/sentry-cocoa#3590]
### Problem Statement

According to the [Apple Docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) we can't use these APIs for our purpose of sending system file size information along with events to Sentry, and therefore have to remove them.

https://github.com/getsentry/sentry-cocoa/blob/720779678ec34ec3e7773ca28019a8d7a0ef2c27/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L497-L513

**Comment by brustolin** [comment]
The following reason is the closest we could use:


>7D9E.1
Declare this reason to include disk space information in an optional bug report that the person using the device chooses to submit. The disk space information must be prominently displayed to the person as part of the report.
Information accessed for this reason, or any derived information, may be sent off-device only after the user affirmatively chooses to submit the specific bug report including disk space information, and only for the purpose of investigating or responding to the bug report.

But the bug report is not optional, and not displayed to the user. 
So, I believe we will need to remove the storage size information which is not good.

**Comment by philipphofmann** [comment]
> I believe we will need to remove the storage size information which is not good.

I think 7D9E.1 doesn't apply to us. I agree that we have to remove the storage size information. It's not good, but it's better than some apps not getting accepted by the App Store anymore because of us.

**Comment by tamwei** [comment]
Well, even derived information is not available. Removing these APIs is an appropriate solution at the moment.
