### ISSUE TITLE
App Store: Describing use of required reason API

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3596]
### Description

We have to remove and change some functionality of our SDK due to [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc/).

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3597
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3590
``` 

The following usages of APIs are acceptable and align with [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc/).

### System boot time APIs
We access system boot time APIs, which is acceptable as we only use that information to calculate exact durations; we don't send the raw value to Sentry; see 35F9.1. 

https://github.com/getsentry/sentry-cocoa/blob/f2daa680e1552830fd789d47831965cb614eb472/Sources/Sentry/SentryTime.mm#L24-L31

We have that defined in the `PrivacyInfo.xcprivacy`
https://github.com/getsentry/sentry-cocoa/blob/f2daa680e1552830fd789d47831965cb614eb472/Sources/Resources/PrivacyInfo.xcprivacy#L54-L61

### User defaults APIs

We use them here https://github.com/getsentry/sentry-cocoa/blob/f2daa680e1552830fd789d47831965cb614eb472/Sources/Sentry/SentryCrashExceptionApplication.m#L12

We use `CA92.1` as required reason
https://github.com/getsentry/sentry-cocoa/blob/f2daa680e1552830fd789d47831965cb614eb472/Sources/Resources/PrivacyInfo.xcprivacy#L46-L53

**Comment by armcknight** [comment]
> We access system boot time APIs, which is acceptable as we only use that information to calculate exact durations; we don't send the raw value to Sentry

I went looking just to confirm, and here are the spots where we convert raw times to elapsed durations: https://github.com/getsentry/sentry-cocoa/blob/7bbb7c3a08a5cf332c7c289296813ee5c0dd58cc/Sources/Sentry/SentryProfiler.mm#L158-L159

and https://github.com/getsentry/sentry-cocoa/blob/7bbb7c3a08a5cf332c7c289296813ee5c0dd58cc/Sources/Sentry/SentryMetricProfiler.mm#L68

and finally https://github.com/getsentry/sentry-cocoa/blob/7bbb7c3a08a5cf332c7c289296813ee5c0dd58cc/Sources/Sentry/SentryProfiler.mm#L129

which are the only instances of the value returned from `absluteTime()` being recorded. They are all converted to elapsed times.

**Comment by philipphofmann** [comment]
We fixed all issues in the task list. We can close this.
