### ISSUE TITLE
Explain usage of NSFileCreationDate

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3597]
According to [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) we shouldn't use `[NSFileCreationDate](https://developer.apple.com/documentation/foundation/nsfilecreationdate?language=objc)` for deleting old envelopes here

https://github.com/getsentry/sentry-cocoa/blob/72f0262c12a37d0997c0bdc760d186b756c2d2cb/Sources/Sentry/SentryFileManager.m#L202-L207

We can avoid using the API by adding the file creation date to the filename of the envelopes.

**Comment by brustolin** [comment]
We need to investigate if makes sense to keep this feature. We dont need to delete envelopes based on date.
