### ISSUE TITLE
Add screenshot to User Feedback

### ISSUE THREAD

**Issue by lionel-alves** [getsentry/sentry-cocoa#3602]
### Problem Statement

```[tasklist]
### Blocked by
- [ ] https://github.com/getsentry/sentry/issues/63749
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3007
``` 

Would be great to be able to add a screenshot to the User Feedback using the SDK / API. See [this epic](https://github.com/getsentry/sentry/issues/63749)

### Solution Brainstorm

Add UIImage screenshot param to the UserFeedback model.

**Comment by philipphofmann** [comment]
The Cocoa SDK doesn't offer a UI for sending user feedback. Instead, it has a method `SentrySDK.captureUserfeedback`. It seems like the user feedback pulls the screenshot as an attachment from the correlated event. When https://github.com/getsentry/sentry/issues/63749 is complete, we would need https://github.com/getsentry/sentry-cocoa/issues/3007 to make this happen. I agree it makes sense to add this feature, but I can't give you an ETA.

**Comment by armcknight** [comment]
This should be covered as part of https://github.com/getsentry/sentry-cocoa/issues/4187

**Comment by philipphofmann** [comment]
As mentioned above, this will be covered by https://github.com/getsentry/sentry-cocoa/issues/4187.
