### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#3609]
### Problem Statement

Hi, was wondering if/when you would be adding the privacy manifest to the Sentry SDK as per https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by philipphofmann** [comment]
It's already there see https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Resources/PrivacyInfo.xcprivacy. We have some related open issues for upcoming privacy changes see https://github.com/getsentry/sentry-cocoa/issues/3596.
