### ISSUE TITLE
Validate how App Hangs work with widgets

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3616]
### Description

Add a widget to our iOS-Swift sample and validate if App Hangs work correctly. Then update the docs accordingly https://docs.sentry.io/platforms/apple/configuration/app-hangs/.

If App Hangs doesn't work correctly for widgets, we could disable App Hangs by default by detecting if the SDK runs on a widget, which we could do with something as pointed out [here](https://stackoverflow.com/a/64073922/1702958).

**Comment by philipphofmann** [comment]
As Widgets run in their own process and Live Activities in their own sandbox, app hangs could be useful for some special setups. Therefore, it's safer to disable app hangs for Widgets and Live Activities by default in the next major: https://github.com/getsentry/sentry-cocoa/issues/3901.

**Comment by brustolin** [comment]
After playing with Widgets (and I believe this is true for other extensions), my understanding is that an App hang does not make sense at all for it. 

We should not even allow app hangs detection to be started for widgets.
I also don't think we need to wait for a major release, since the concept of App Hangs + Widgets does not make sense.

**Comment by philipphofmann** [comment]
> After playing with Widgets (and I believe this is true for other extensions), my understanding is that an App hang does not make sense at all for it.

That's also what I found out. I'm also fine with disabling them. We just need to find a way to identify that you run in a widget or a live activity.

**Comment by jboulter11** [comment]
> (and I believe this is true for other extensions)
What makes you say this?  We've not seen nearly as much noise on app extensions or file provider as we have on widgets.

**Comment by brustolin** [comment]
@jboulter11, I was thinking about other non UI extensions like some `Actions Extensions` and `Intent Extensions`

**Comment by philipphofmann** [comment]
Anyway, I think it's better to disable app hangs by default in the next major. I'm going to close this now. I added considering disabling app hangs for Actions Extensions and Intent Extensions to https://github.com/getsentry/sentry-cocoa/issues/3901.
