### ISSUE TITLE
Detecting Crash Loops (crashes on launch)

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry-cocoa#3639]
### Problem Statement

In Bugsnag, there's a feature which can provide information about the last app run.  If the last run crashed within a configurable amount of time (~2s default I think) then it's marked that the last run crashed on launch.

Docs: https://docs.bugsnag.com/platforms/ios/identifying-crashes-at-launch/#recovering-after-launch-crashes

We can use this to try and recover in the app.

I do not see something equivalent for Sentry.

I do see that there's a mechanism described in the docs as:
> Start-up crashes. The SDK init waits synchronously for up to 5 seconds to flush out events if the app crashes within 2 seconds after the SDK init.

And I think this is it in the code: https://github.com/getsentry/sentry-cocoa/blob/3db3e35c43af949b9d27185b9c534adf0c38fdde/Sources/Sentry/SentryCrashReportSink.m#L52

However, this doesn't give us a way to tell it happened and react to the issue.  We're especially keen to get this detection for the Dropbox File Provider extension, where we can reset it's local state in order to ideally recover from the crash loop.

My question/ask:
Does something like this exist?  If so, please direct me towards it.  If not, how can we bridge the gap here?

### Solution Brainstorm

Ideally we can get a hook or variable we can check to see if Sentry detected a crash loop.

Bugsnag's interface looks like:
`Bugsnag.lastRunInfo?.crashedDuringLaunch` as a boolean variable we can check at startup.

Something similar may work well for us.

### Are you willing to submit a PR?

If the change is managable

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2109) by [Unito](https://www.unito.io)

**Comment by brustolin** [comment]
Thanks @jboulter11  for reaching out. We dont offer a way to act upon a startup crash, but it sounds like a good idea.
We will discuss it with the team.

**Comment by philipphofmann** [comment]
That's an interesting use case. I don't see any reason we shouldn't add an API to tell you that the SDK detected a start-up crash. We only need to come up with a proper API. As the SDK sends the crash event blocking in case of a startup crash, we can expose a flag. We already have `crashedLastRun` https://github.com/getsentry/sentry-cocoa/blob/83887aff6461a3c4738c6852d55faaef69cd1d98/Sources/Sentry/Public/SentrySDK.h#L251-L254

What about exposing a readonly flag called `detectedStartUpCrash` on `SentrySDK`. What do you think @brustolin?

**Comment by brustolin** [comment]
>What about exposing a readonly flag called detectedStartUpCrash on SentrySDK. What do you think @brustolin?

Good enough to me.

**Comment by jboulter11** [comment]
Since this property was introduced, we're now trying to adopt it, but we've run into an issue.

It's not set synchronously when we setup Sentry, so I'm not clear on when we are able to query this value.  Is there a hook that tells us when this becomes available? @philipphofmann @brustolin 🙏

**Comment by philipphofmann** [comment]
@jboulter11, what exactly do yo mean by?
> It's not set synchronously when we setup Sentry,

We set the flag here on the main thread if there was a startup crash. If not, we send the crash events on a background thread.

https://github.com/getsentry/sentry-cocoa/blob/b15521ec4775f623b296e1fca558ffac46447bb8/Sources/Sentry/SentryCrashReportSink.m#L48-L64

So you can do 
```swift
SentrySDK.start { 
    // Your option config
}

// When there is a start-up crash, the SDK start is blocking on the main thread until the SDK flushes
// the crash event to Sentry

if SentrySDK.detectedStartUpCrash {
    // do what you need to do
}

```
