### ISSUE TITLE
Links with libraries that aren’t present in macOS

### ISSUE THREAD

**Issue by tillkruss** [getsentry/sentry-cocoa#3648]
### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.20.0

### Did it work on previous versions?

I just started using this library, so not sure.

### Steps to Reproduce

When building using the latest version I get a warning from Xcode: `ITMS-90863: Macs with Apple silicon support issue - The app links with libraries that aren’t present in macOS`

**This prevents the app being built for macOS (Designed for iPad).** 

### Expected Result

No warning. 

### Actual Result

```
ITMS-90863: Macs with Apple silicon support issue - The app links with libraries that aren’t present in macOS:

/Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Ruddarr/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Sentry-Dynamic.framework/Sentry-Dynamic
```

### Are you willing to submit a PR?

I'm not capable.

**Comment by tillkruss** [comment]
The library is set to `Embed & Sign`:

<img width="577" alt="Screenshot 2024-02-17 at 11 41 27" src="https://github.com/getsentry/sentry-cocoa/assets/665029/a650ff1c-4467-4948-9959-a4453589df54">

**Comment by brustolin** [comment]
Hello @tillkruss, thanks for reaching out.

Im not sure what's happening, Sentry-Dynamic.framework should be bundled with the app and not available with macOS. Never saw Xcode behaving like this.

Does the app works stills? Can you open the app content to see if there is Sentry framework inside of it?

Using `Sentry` instead of `Sentry-Dynamic` produces the same problem?

**Comment by tillkruss** [comment]
@brustolin: I removed `Sentry-Dynamic` from list and now it builds again for macOS and simulators. Previously it did not. Is it fine to use this SDK without it?

**Comment by tillkruss** [comment]
Maybe that's the issue? Where can I read about which one to best pick?

**Comment by kahest** [comment]
@tillkruss this is the docs page explaining usage with SPM: https://docs.sentry.io/platforms/apple/install/swift-package-manager/
