### ISSUE TITLE
Improve EnvelopeItem to work with NSURL 

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#3667]
### Description

Attachments and ReplaySessions need to be loaded into memory to create an envelope item that will be written again to disk.
We could avoid loading large chunks of memory by directly copying the file into the destination envelope.

**Comment by philipphofmann** [comment]
This is related to https://github.com/getsentry/sentry-cocoa/issues/3630.

**Comment by brustolin** [comment]
Closing this in favor of https://github.com/getsentry/sentry-cocoa/issues/3630
