### ISSUE TITLE
Compile flutter project with clang.

### ISSUE THREAD

**Issue by shigomany** [getsentry/sentry-cocoa#3689]
## Introduction

I would like to integrate [ccache](https://ccache.dev/) into my flutter project, but I ran into a problem when compiling.

[There is also a discussion about this](https://github.com/invertase/firestore-ios-sdk-frameworks/discussions/82)

In a recent release, I thought this problem would disappear thanks to this PR #3538 

### Platform

iOS

### Environment

Production, Develop

### Installed

CocoaPods

### Version

8.20.0

### Did it work on previous versions?

No

### Steps to Reproduce

1. Change the Pod file configuration like this:

```
config.build_settings["CC"] = "clang"
config.build_settings["LD"] = "clang"
config.build_settings["CXX"] = "clang++"
config.build_settings["LDPLUSPLUS"] = "clang++"
```
2. In `ios` folder run:

```bash
pod update
```

3. In Flutter project run:

```bash
flutter build ios --no-codesign
```

[Flutter project example](https://github.com/shigomany/sentry_clang_build)

### Expected Result

Build succed

## Error log

```
[   +2 ms] Modules Issue (Xcode): Import of C++ module 'Darwin.POSIX.sys.types' appears within extern "C" language linkage specification
           /Users/shigomany/Documents/workingprojects/sentry_clang_build/ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashThread.h:31:0

[        ] Modules Issue (Xcode): Import of C++ module 'Darwin.POSIX.sys.types' appears within extern "C" language linkage specification
           /Users/shigomany/Documents/workingprojects/sentry_clang_build/ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor.h:30:0
```

## Full log with verbose mode

[log.log](https://github.com/getsentry/sentry-cocoa/files/14448277/log.log)

**Comment by shigomany** [comment]
> Hello @shigomany, thanks for reaching out. Can you try the following branch in your cocoapod file to see if it solves the problem: `fix/headers-out-of-strict`
> 
> ```ruby
> pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa', :branch => 'fix/headers-out-of-strict'
> ```

There's almost one mistake left:

```
Modules Issue (Xcode): Import of C++ module 'Darwin.POSIX.sys.types' appears within extern "C" language linkage specification
           /Users/shigomany/Documents/workingprojects/sentry_clang_build/ios/Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashThread.h:31:0
```

New log attached
[log.log](https://github.com/getsentry/sentry-cocoa/files/14452156/log.log)

**Comment by shigomany** [comment]
@brustolin if changed file `SentryCrashMonitor_CPPException.h` and my app builded)

From:

```c
#ifdef __cplusplus
extern "C" {
#endif

#include "SentryCrashMonitor.h"
```

To:

```c
#include "SentryCrashMonitor.h"

#ifdef __cplusplus
extern "C" {
#endif
```

**Comment by brustolin** [comment]
Thanks for the help @shigomany . I updated the branch with your input.
Please let us know if it works.
