### ISSUE TITLE
Make enriched Scope independent of SentryCrashIntegration

### ISSUE THREAD

**Issue by farfromrefug** [getsentry/sentry-cocoa#3694]
### Platform

iOS

### Environment

Production, Develop

### Installed

CocoaPods

### Version

8.20.0

### Steps to Reproduce

1. disable `SentryCrashIntegration` with `enableCrashHandler` or by removing the integration
2.  configure a scope
3. serialize the scope => empty

### Expected Result

The scope should still be augmented with all the device infos.

### Actual Result

empy scope

### Are you willing to submit a PR?

could be but not sure about the wanted refactor

**Comment by brustolin** [comment]
Hello @farfromrefug thanks for reaching out.
You have a good point and  we should separate scope information gathering from the crash integration.
