### ISSUE TITLE
Crash on SentryProfiler start

### ISSUE THREAD

**Issue by mr-grey** [getsentry/sentry-cocoa#3696]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

pod 'Sentry', '~> 8.2.0'

### Did it work on previous versions?

yes

### Steps to Reproduce

This crash i see at first time, Not Able  to provide steps. 
<img width="1510" alt="Screenshot 2024-03-01 at 09 49 15" src="https://github.com/getsentry/sentry-cocoa/assets/699148/0c7dc853-81e2-40f1-93d5-1cf9e1d30c8f">

### Expected Result

no crash.

### Actual Result

random Crash;

**Comment by philipphofmann** [comment]
@mr-grey, if you are using version 8.2.0, please update to the latest SDK version because we have done plenty of profiler fixes since then. Please reopen the issue if the issue persists after updating.
