### ISSUE TITLE
Generation of stack trace and breadcrumb is nil in clients created by user

### ISSUE THREAD

**Issue by ryan-noths** [getsentry/sentry-cocoa#370]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Swift 5.0
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

I have an application where I'd like to send Sentry events to two different Sentry projects (i.e. two separate instances of `Sentry.Client`)

I've got a singleton named `SentryManager` that handles all setup and subsequent events and was previously working perfectly fine when sending events to a single Sentry project by utilising the built-in shared instance `Client.shared`.

This was updated by creating two `Sentry.Client` instances with the relevant dsn values for each project at launch and storing them in the singleton, then choosing which client to use when firing an event and using that client to generate the stack trace and accessing the breadcrumbs

Also the Run Script was updated to run twice with two different `SENTRY_PROJECT` variables (this was purely to handle symbolication in the projects once events were working however)

The issues the arose were:
- Breadcrumbs were no longer being automatically recorded
- `snapshotStackTrace` was returning nil

**Steps to reproduce:**
- Manually create two instances of `Client` with different dsn values pointed at two separate projects
- Each client should have the following enabled:
    - enableAutomaticBreadcrumbTracking()
    - startCrashHandler()
- Send an event: 
    ```
    client.snapshotStacktrace { [weak client] in
            guard let client = client else { return }
            client.appendStacktrace(to: event)
            client.send(event: event, completion: completion)
        }
    ```

**Actual result:**
- `snapshotStacktrace` completes but there is no stacktrace
- The breadcrumb is empty (this was only the case with one of my two clients) 

**Expected result:**
- Stacktrace is populated as usual
- Breadcrumb is populated as usual

I suspect this may be a case of the SDK referencing it's own shared instance in these methods rather than using the client that it was called on and therefore being unable to generate this information with an essentially uninitialised client

**Comment by fetzig** [comment]
Hi @ryan-noths!

Thx for your issue. Will try and get back to you by the end of the week (or sooner, hopefully).

Regards,
@fetzig

**Comment by fetzig** [comment]
this sucks! we know. working hard on improving this in `5.x`. I hope you are one of the first to check it out when the alpha ships.

In `4.x` automated breadcrumb tracking and crash handler work only with `Client.shared`. Thus working on `5.x` aka. #339.

To give you a little sneak peek on how you could accomplish this with `5.x`. Init Sentry and create 2 Sentry Clients you retain yourself (one for every dsn/project). Use the `beforeSend` hook/callback to forward the Event to your Client(s) and don't send with the bound client (== `5.x` version of `Client.shared`). In this scenario, the actual bound client is just a receiver of Events created by integrations (in this case SentryCrash aka. KSCrash). This solution already works with `sentry-javascript` and might already work with the current `5.x` branch of sentry-cocoa. 

AFAIK this isn't possible with `4.x`. Not without monkey patching sentry-cocoa.

Will keep this issue open until `5.0a1` ships.

**Comment by philipphofmann** [comment]
Hi @ryan-noths, can you achieve your desired requirements with our 5.x.x release or do you still have trouble?

**Comment by philipphofmann** [comment]
As we didn't receive any input for around half a year we are going to close this issue. Feel free to open it again @ryan-noths if you need more input from our side.
