### ISSUE TITLE
SentryFramesTracker Background CPU Usage

### ISSUE THREAD

**Issue by abbottkilroy** [getsentry/sentry-cocoa#3700]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.20.0

### Steps to Reproduce

Run app in background

### Expected Result

Sentry seems to be taking a bunch of CPU time when our app is in the background. SentryFramesTracker seems to be the culprit. As our app is continuously running in the background this can be a significant issue.

### Actual Result

<img width="1706" alt="image001" src="https://github.com/getsentry/sentry-cocoa/assets/115741741/9628533a-226f-4613-ab0c-67f663d34338">

**Comment by philipphofmann** [comment]
We could stop the frames tracker when the app goes into the background, which we currently don't do. This should be an easy fix. Thanks for pointing that out, @abbottkilroy.
