### ISSUE TITLE
Data race in -[SentryFramesTracker displayLinkCallback] at 0x10cd42f70

### ISSUE THREAD

**Issue by qweluke** [getsentry/sentry-cocoa#3702]
### Platform

iOS

### Environment

Production, Develop

### Installed

Swift Package Manager

### Version

8.20.0

### Did it work on previous versions?

No

### Steps to Reproduce

After enabling `thread sanitizer` i see 3 different data race errors in the xcode.

### Expected Result

There should be no `data race` error when a `thread sanitizer` is enabled

### Actual Result

<img width="1667" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/193701/85300218-f692-4b0b-b537-1b9f76ce1208">

<img width="1659" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/193701/96b1cbc5-bba0-4185-912a-f1e8ffe8bc4b">

**Comment by brustolin** [comment]
Thanks @qweluke for reporting this. We will fix this, but I can give you an ETA right now.

**Comment by philipphofmann** [comment]
The `displayLinkCallback` should be called on the main thread. I wonder how we get data races in there. I can easily reproduce this problem by activating the thread sanitizer for our iOS-Swift sample app. Thanks for reporting this, @qweluke.

**Comment by philipphofmann** [comment]
The data races are false positives. We are going to disable them with https://github.com/getsentry/sentry-cocoa/pull/3922. For an explanation, visit https://github.com/getsentry/sentry-cocoa/pull/3922.
