### ISSUE TITLE
Version 8.22.1 Lacks Mac Catalyst support

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#3761]
### Platform

iOS, tvOS, macOS

### Environment

Production, Develop, TestFlight

### Installed

Swift Package Manager

### Version

8.22.1

### Did it work on previous versions?

8.21.0

### Steps to Reproduce

Integrated 8.22.1 via SPM
Xcode 15.3
Mac Catalyst target does not compile:

```SourcePackages/artifacts/sentry-cocoa/Sentry/Sentry.xcframework:1:1 While building for Mac Catalyst, no library for this platform was found in '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/SourcePackages/artifacts/sentry-cocoa/Sentry/Sentry.xcframework'.
```

### Expected Result

Expecting work on Mac Catalyst

### Actual Result

see above

**Comment by gabors** [comment]
`/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/SourcePackages/artifacts/sentry-cocoa/Sentry/Sentry.xcframework:1:1 While building for Mac Catalyst, no library for this platform was found in '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/SourcePackages/artifacts/sentry-cocoa/Sentry/Sentry.xcframework'.
`

**Comment by gabors** [comment]
Here is Sentry w/o Mac Catalyst 
<img width="472" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/8b28c94d-08ba-4223-b93a-f76ec762b571">

vs a another package that has catalyst:

<img width="505" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/cdb3d41c-540c-46c5-97aa-e95af064c91f">

**Comment by brustolin** [comment]
Thanks @gabors for reporting this. We will fixed this

**Comment by gabors** [comment]
Thanks very much
Works now as static framework.
However getting a runtime error when trying to use this a dynamic on Mac Catalyst in Xcode,

is it a signing problem?

`dyld[31816]: Library not loaded: @rpath/Sentry.framework/Versions/A/Sentry
  Referenced from: <56C2FE8C-A226-3E73-8DF3-A69B2DE114BA> /Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/Frameworks/WBDKit.framework/Versions/A/WBDKit
  Reason: tried: '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/Sentry.framework/Versions/A/Sentry' (code signature in <85240F3B-DDA3-3DE4-9F69-F1CB0CB9E3EE> '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/Sentry.framework/Versions/A/Sentry' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/Frameworks/WBDKit.framework/Versions/A/Frameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/../Frameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/PackageFrameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/../Frameworks/Sentry.framework/Versions/A/Sentry' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/Sentry.framework/Versions/A/Sentry' (no such file)`

**Comment by philipphofmann** [comment]
https://github.com/getsentry/sentry-cocoa/issues/3761#issuecomment-2007819092 is now a new issue https://github.com/getsentry/sentry-cocoa/issues/3770.
