### ISSUE TITLE
Ship an XCFramework without UIKit linked

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry-cocoa#3768]
### Problem Statement

At Dropbox, we currently build Sentry both with and without UIKit.  We require that Sentry in our File Provider extension not import UIKit because the UIKit symbols take up too much space in memory with FP's super low memory limitations.

We'd love to simplify our build by using your new XCFramework distributions instead, but we need both the ones you're releasing now and also ones built without the UIKit link in order to switch over.

### Solution Brainstorm

Build Sentry without a link to UIKit and provide those XCFramework(s) as well in your releases page.

### Are you willing to submit a PR?

Maybe

**Comment by brustolin** [comment]
We just need to update build-xcframeworks.sh script to include the no-uikit flag.

This will be only available as a downloadable asset in GH releases, and not SPM or Cocoapods.

**Comment by jboulter11** [comment]
Perfect, thank you! 😀

**Comment by jboulter11** [comment]
Please let me know when y'all have an ETA here.  We'll be sure to adopt the XCFs right away so we can resolve any issues that may arise.

**Comment by kahest** [comment]
Hey @jboulter11 we merged the required changes, we'll ship a new release with this early next week

**Comment by jboulter11** [comment]
Thank you, I'll set a reminder to check in and try and adopt the new XCFs.  I appreciate you getting to this quickly, we were worried we'd be blocked from updating in the future.
