### ISSUE TITLE
Xcode 15.3 and App Store Connect Issue

### ISSUE THREAD

**Issue by pedrocid** [getsentry/sentry-cocoa#3779]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.22.2

### Did it work on previous versions?

8.21.0

### Steps to Reproduce

1. Download Xcode 15.3
2. Add as a dependency the Sentry SDK
3. Upload a build to App Store Connect

### Expected Result

Processing of the application on the Appstore connect without issues.

### Actual Result

[Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (90208) Invalid Bundle. The bundle **[Redacted]/**Sentry.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by kahest** [comment]
Hey @pedrocid, thanks for the report - this is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3769, please check out the latest updates there.
