### ISSUE TITLE
SentryClient.sharedClient.extra setter side effect can cause recursive loop

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#378]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

When assigning a value to `SentryClient.sharedClient.extra`, a `NSUserDefaultsDidChangeNotification` is fired.  This is not ideal since it can easily trigger application code.  It is not wise for `Sentry` initialization or configuration to trigger application code since it causes undesired and unpredictable bleeding/side-effects in the application.

In my case, when the user defaults change, I want to reflect that change by updating Sentry's extras, so I save application configuration in Sentry's extras and update that whenever `NSUserDefaultsDidChangeNotification` fires, thereby leading to a recursive loop.

The fix is to be extremely vigilant in ensuring that Sentry is entirely (and not purely in the `extra` setter) self-contained and touching Sentry does not bleed into global hooks/triggers.

**Steps to reproduce:**
- Observe `NSUserDefaultsDidChangeNotification`
- Handle the notification by setting `SentryClient.sharedClient.extra`

**Actual result:**
- Recursive loop

**Expected result:**
- `extra` is updated with new values.

**Comment by philipphofmann** [comment]
As we stopped the support for 4.x.x, we are already on 6.x.x, and `SentryClient.sharedClient.extra` doesn't exist anymore, we are going to close this issue.
