### ISSUE TITLE
onCrashedLastRun block is called even if beforeSend sets the event to nil

### ISSUE THREAD

**Issue by ksuther** [getsentry/sentry-cocoa#3784]
### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.22.2

### Steps to Reproduce

Implement `beforeSend` and `onCrashedLastRun`:

```
[options setBeforeSend:^SentryEvent * _Nullable(SentryEvent *_Nonnull event) {
    return NO;
}];

[options setOnCrashedLastRun:^(SentryEvent *_Nonnull event) {
    // This is called with event = nil
}];
```

Looks like the relevant check is here: https://github.com/getsentry/sentry-cocoa/blob/742d4b693cfd3cf2b7b1d62930d16daaf505d367/Sources/Sentry/SentryClient.m#L667

### Expected Result

`onCrashedLastRun` shouldn't be called when `beforeSend` returns a nil event.

### Actual Result

onCrashedLastRun is called with `event = nil` even though `event` is nonnull.

### Are you willing to submit a PR?

If needed

**Comment by brustolin** [comment]
Thanks for reporting this @ksuther. It makes sense to me.
