### ISSUE TITLE
8.22.3 invalid Info.plist

### ISSUE THREAD

**Issue by jdanthinne** [getsentry/sentry-cocoa#3786]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.22.3

### Steps to Reproduce

Build and submit an app to Apple

### Expected Result

Build accepted

### Actual Result

ITMS-90060: This bundle is invalid - The value for key CFBundleShortVersionString '8.22.3-beta.0' in the Info.plist file at 'Payload/Metronotes.app/Frameworks/Sentry.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

ITMS-90058: This bundle is invalid - The value for key CFBundleVersion [8.22.3-beta.0] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

**Comment by kahest** [comment]
Hi @jdanthinne thanks for the report, we're on it. Which version of Xcode do you use, and do you build/submit to multiple platforms (iOS, macOS, etc.)?

**Comment by kahest** [comment]
@jdanthinne thank you! we'll have a fix ready likely later today

**Comment by kahest** [comment]
@jdanthinne the fix was released with [8.22.4](https://github.com/getsentry/sentry-cocoa/releases/tag/8.22.4) - please let us know in case you encounter any other problems.
