### ISSUE TITLE
Xcode Warning: Redistributable static libraries should never be built with module debugging enabled

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#3788]
### Platform

iOS, macOS

### Environment

Production, TestFlight

### Installed

Swift Package Manager

### Version

8.22.4

### Did it work on previous versions?

8.21.0

### Steps to Reproduce

Xcode 15.3
integrate static lib via spm

### Expected Result

Expect no warnings

### Actual Result

/Users/runner/work/sentry-cocoa/sentry-cocoa/Carthage/DerivedData/ModuleCache.noindex/B94P7YC5KI7O/Foundation-1EXJ537PQIF6H.pcm: No such file or directory

Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

<img width="1080" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/77eeb3f4-4ba1-4096-9f67-41d446026482">

**Comment by gabors** [comment]
I already replied to this question in the other thread. 
I never expected any scripts. 

This screen shot is from Xcode cloud.

**Comment by gabors** [comment]
Take a look at that gmodules flag in the warning from Xcode build 

It causes long delays with breakpoints when debugging

**Comment by gabors** [comment]
Some good info here. 

https://forums.swift.org/t/swift-behavior-of-gmodules-and-dsyms/23211

**Comment by brustolin** [comment]
> This screen shot is from Xcode cloud

Well, as pointed out, this `Carthage` folder is not part of the project,  so I believe any problem inside of it wont affect our library.
We also dont use  `-gmodules` flags anywhere.

We need to investigate if this is a Xcode cloud issue.

**Comment by gabors** [comment]
I get these warnings when building locally in xcode, when running a locally Xcodebuild in terminal and also on Xcode cloud. 
This happens on two separate unrelated projects. 
I worked hard not to have any build warnings in my projects so staring at 55 warnings is not making me happy. 

Safe to say it's due to how the static library was built. 

Feel free to try it yourself on a machine that doesn't have the module cache. 

Please read the link I added.

**Comment by gabors** [comment]
I don't fully understand your teams motivation for adding swift code to sentry. 

I appreciate that writing swift code is easier and if it was possible to have crash detection in pure swift it would be great but alas it is not. 

But this distribution method of binary targets via spm is causing a lot of time waste and frustration in the past week.

**Comment by brustolin** [comment]
We share the feeling of maintaining a project without any warning.
I can't reproduce this issue locally.

If you can help us with a repro it would help a lot.

**Comment by gabors** [comment]
Can you try with a Mac Catalyst target ? 

That's what xcode cloud was complaining about. 

Maybe try deleting the derived data folder.

**Comment by brustolin** [comment]
![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/d79dda56-f43f-48e4-b03b-9aa474c755d0)

![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/7ab7c754-47a8-4a87-bb5f-6ec7cae22bbc)

This is the command Im running:

```
xcodebuild -project SampleProject.xcodeproj -configuration Release -sdk iphoneos -destination 'platform=macOS,variant=Mac Catalyst'
```

No warning during the build.

**Comment by gabors** [comment]
Thanks. I'll try to replicate tomorrow.

**Comment by gabors** [comment]
I wonder if you disable DSYM files generation for the static framework will these warnings go away?

**Comment by brustolin** [comment]
> You need to set DEBUG_INFORMATION_FORMAT in the project to DWARF with dSYM

This did the trick.
Interesting that, for me, it only happen in the Xcode, but not when building from the terminal.

> I wonder if you disable DSYM files generation for the static framework will these warnings go away?

I believe you're on something here. We will investigate. Thanks for the help.

**Comment by gabors** [comment]
When's the next release coming? Eager to test it out.
