### ISSUE TITLE
Apple review warning ITMS-91053 problem handling （Disk space APIs）

### ISSUE THREAD

**Issue by caosuyang** [getsentry/sentry-cocoa#3789]
### Problem Statement

After Apple submitted the review, Apple restored a warning email. Currently, the review is not blocked. According to the official notice, it will be used as a condition for blocking the review around May.

Part of the warning email is as follows:
ITMS-91053: Missing API declaration - Your app’s code in the “--” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

After a global search, we can find:
1. Line 511 of the SentryCrashMonitor_System.mm file uses the systemFreeSize api.
2. Line 502 of the SentryCrashMonitor_System.mm file uses the systemSize api.

The current version of sentry used in our project is:
- SentryPrivate 8.20.0 -> 8.20.0 (latest version 8.22.0-alpha.0)

However, I read the source code and found that this privacy clause - NSPrivacyAccessedAPICategoryDiskSpace - does not exist in the PrivacyInfo.xcprivacy file of the latest version release: 8.22.4. The source code location is as follows:
https://github.com/getsentry/sentry-cocoa/blob/8.22.4/Sources/Resources/PrivacyInfo.xcprivacy

### Solution Brainstorm

- Add this privacy clause in the PrivacyInfo.xcprivacy file - NSPrivacyAccessedAPICategoryDiskSpace.

### Are you willing to submit a PR?

Yes I can submit a quick PR for this, it seems to be an easy fix.

**Comment by brustolin** [comment]
Hello @caosuyang, thanks for reaching out. We don't use NSPrivacyAccessedAPICategoryDiskSpace because we're no longer getting disk space since version 8.21.0, you can check it in [this PR](https://github.com/getsentry/sentry-cocoa/pull/3627/files#diff-4121562dc3763af4f284a26bd29193df219725fcb79a588fa18c5fc87c021fe5L497-L519).
