### ISSUE TITLE
Required reason API

### ISSUE THREAD

**Issue by sshnip** [getsentry/sentry-cocoa#3794]
### Description

Hi there, I have a question regarding new [Apple requirements towards privacy API use](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api). Does sentry falls into one of the cases that is described there?

**Comment by brustolin** [comment]
Hello @sshnip, thanks for reaching out. Yes. we do fall into some of the cases. But we're shipping the privacy manifest with the framework already, and it is updated since version 8.21.0.

So, make sure you're using at least 8.21.0.
