### ISSUE TITLE
`[NSError sentryErrorWithDomain:code:description:]` crash

### ISSUE THREAD

**Issue by sindresorhus** [getsentry/sentry-cocoa#3818]
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.22.4

### Steps to Reproduce

I'm not able to reproduce myself.

Crash: https://sindresorhus.sentry.io/share/issue/3c1e8d533b2f4c18bd29310c335da183/

### Expected Result

I expected Sentry to **never** crash my app.

---

The reference to `SSApp.initSentry` in the stack trace is:

```swift
enum SSApp {
	static func initSentry(_ dsn: String) {
		#if !DEBUG && canImport(Sentry)
		SentrySDK.start {
			$0.dsn = dsn
			$0.enableSwizzling = false
			$0.enableAppHangTracking = false
		}

		SentrySDK.configureScope { scope in
			scope.setContext(
				value: [
					"Launch Count": SSApp.launchCount // Int
				],
				key: "debugInfo"
			)

			var deviceDebugInfo = [String: Any]()

			#if os(macOS)
			deviceDebugInfo += [
				"Keyboard": SSApp._keyboardLayoutString, // String
				"Screen Count": Device.screenCount, // Int
				"Screens": NSScreen.screens.map(\.debugInfo), // Array<String>
				"Is Bartender Running": NSWorkspace.shared.isBartenderRunning, // Bool
				"Is Bartender-like Running": NSWorkspace.shared.isAnyMenuBarItemHidingAppRunning // Bool
			]
			#endif

			scope.setContext(
				value: deviceDebugInfo,
				key: "device 2"
			)
		}
		#endif
	}
}
```

---

Sidenote: I hope https://github.com/getsentry/sentry-cocoa/issues/3780 will be prioritized, because I have seen way too many crashes in my app caused by Objective-C code in Sentry.

### Actual Result

It crashes.

**Comment by philipphofmann** [comment]
Thanks for reporting this, @sindresorhus. A fix is on the way https://github.com/getsentry/sentry-cocoa/pull/3819.

> Sidenote: I hope https://github.com/getsentry/sentry-cocoa/issues/3780 will be prioritized, because I have seen way too many crashes in my app caused by Objective-C code in Sentry.

Thanks for the sidenote 😃. I didn't consider this big advantage when creating the issue. I added this as a big advantage for using more Swift code to the issue:
> Another big advantage of using Swift over ObjC is that Swift is [designed for safety](https://developer.apple.com/swift/#safety), so it should increase the stability of the SDK in the long run.
