### ISSUE TITLE
Cocoapods link returns error 503

### ISSUE THREAD

**Issue by vinamelody** [getsentry/sentry-cocoa#384]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [ x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.x**

---
I have following issue:
https://cocoapods.org/pods/Sentry returns HTTP error 503 causing new pod install stopped / error

<img width="957" alt="Screenshot 2020-02-18 at 11 14 44 AM" src="https://user-images.githubusercontent.com/990511/74700875-ef558d00-523f-11ea-89f0-247a0ff9e73a.png">

**Steps to reproduce:**
pod install

**Actual result:**
error on Sentry

**Expected result:**
no error

**Comment by HazAT** [comment]
Thanks, I think this is a problem with cocoapods.org

**Comment by martin-1337** [comment]
Hello, I am interest on a real solution and not on a work-a-round. This issues is still open.

**Comment by HazAT** [comment]
@martin-1337 You can reach out to cocoapods, we are not responsible for the reliability of their registry or website. The solution I posted is a perfectly fine solution and not really a workaround, sorry if I called it like this.

**Comment by martin-1337** [comment]
Hi, you are right. That have been not correctly addressed by my side, sorry!

And thanks for your rapid answer.

 

kr

martin-1337

 
 

Gesendet: Montag, 02. März 2020 um 10:03 Uhr
Von: "Daniel Griesser" <notifications@github.com>
An: getsentry/sentry-cocoa <sentry-cocoa@noreply.github.com>
Cc: martin-1337 <mschuermeyer@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [getsentry/sentry-cocoa] Cocoapods link returns error 503 (#384)


@martin-1337 You can reach out to cocoapods, we are not responsible for the reliability of their registry or website. The solution I posted is a perfectly fine solution and not really a workaround, sorry if I called it like this.
