### ISSUE TITLE
8.24.0 compile error missing swift classes miss public keyword

### ISSUE THREAD

**Issue by RayFor24** [getsentry/sentry-cocoa#3850]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.24.0

### Steps to Reproduce

 const char *viewClassName = [[SwiftDescriptor getObjectClassName:view] UTF8String];
error:
No known class method for selector 'getObjectClassName:'

After introducing 8.24.0, compile the error that the project report method cannot find. The project previously referenced version 8.22.0 without this error. After comparison, it was found that some swift classes were missing the public keyword, such as SwiftDescriptor, HTTPHeaderSanitizer, and so on.

### Expected Result

 const char *viewClassName = [[SwiftDescriptor getObjectClassName:view] UTF8String];
error:
No known class method for selector 'getObjectClassName:'

### Actual Result

 const char *viewClassName = [[SwiftDescriptor getObjectClassName:view] UTF8String];
error:
No known class method for selector 'getObjectClassName:'

**Comment by brustolin** [comment]
Hello @RayFor24, thanks for reaching out. 
Are you trying to use `SwiftDescriptor` into your project, or are these errors happening inside Sentry codebase?

**Comment by RayFor24** [comment]
I don't want to use SwiftDescriptor in my project, happening inside Sentry codebase.

**Comment by RayFor24** [comment]
> Hello @RayFor24, thanks for reaching out. Are you trying to use `SwiftDescriptor` into your project, or are these errors happening inside Sentry codebase?

I don't want to use SwiftDescriptor in my project, happening inside Sentry codebase.

**Comment by kahest** [comment]
Hey @RayFor24 thanks for confirming, we'll investigate and follow up here

**Comment by kahest** [comment]
@RayFor24 would you be able to provide a minimal repro? we're not able to reproduce this with our samples

**Comment by kahest** [comment]
Related issue via RN SDK: https://github.com/getsentry/sentry-react-native/issues/3765

**Comment by brustolin** [comment]
Hello @RayFor24 do you have any configuration on your pods file that disable "APPLICATION_EXTENSION_API_ONLY" for the pods you're using?

Can you share your pod file with us in case it does not contains any private information?

**Comment by krystofwoldrich** [comment]
@brustolin A users responded in https://github.com/getsentry/sentry-react-native/issues/3765 it was caused by the `APPLICATION_EXTENSION_API_ONLY` flag set to `NO`.
