### ISSUE TITLE
Update to 8.21.0 causes a crash in my app in runtime

### ISSUE THREAD

**Issue by iwan-ua** [getsentry/sentry-cocoa#3856]
### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.21.0

### Did it work on previous versions?

8.20.0

### Steps to Reproduce

(I know these aren't really steps, please see actual result)
1. Update the library
2. Launch tests that previously worked
3. Crash in NETunnelProvider

### Expected Result

tests succeed as before the update

### Actual Result

After updating to 8.21.0 I noticed this warning on my CI, that wasn't there before

ld: tentative definition of '_context' with size 296 from '/Users/distiller/Library/Developer/Xcode/DerivedData/MyCompany-elgqgghuekrytrhiucwhimezasdq/Build/Products/Debug Dev/libMyCompanyTunnelProviderMac.a(netbios.c.o)' is being replaced by real definition of smaller size 208 from '/Users/distiller/Library/Developer/Xcode/DerivedData/MyCompany-elgqgghuekrytrhiucwhimezasdq/Build/Products/Debug Dev/Sentry.o'

My NETunnelProvider crashes, probably because it uses sentry code instead of my own code

8.21.0 had this change, so I think it might be responsible, but I'm not sure
https://github.com/getsentry/sentry-cocoa/pull/3690

**Comment by iwan-ua** [comment]
I think [this part](https://github.com/getsentry/sentry-cocoa/blame/d9308fd7531e4b4a45e32ecb21406736ad9fd632/Sources/Sentry/Profiling/SentryLaunchProfiling.m#L95) conflicts with this part of our code:

struct {
    ....
} context;

We'll rename it and see if it fixes it. But I think for third-party libs it's better to give unique names to its global variables

**Comment by brustolin** [comment]
>I think [this part](https://github.com/getsentry/sentry-cocoa/blame/d9308fd7531e4b4a45e32ecb21406736ad9fd632/Sources/Sentry/Profiling/SentryLaunchProfiling.m#L95) conflicts with this part of our code:

Makes sense. context is a very generic symbol. We probably should rethink this. 
What do you think @armcknight ?

**Comment by iwan-ua** [comment]
Fixed by changing our
`struct {
....
} context;`
into
`static struct {
....
} context;`

**Comment by brustolin** [comment]
Thanks for the feedback @iwan-ua.

I believe we should change the name internally to avoid future naming conflict.
