### ISSUE TITLE
Xcode Build Phase not working

### ISSUE THREAD

**Issue by trevorturk** [getsentry/sentry-cocoa#3860]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.24.0

### Steps to Reproduce

Follow instructions in https://docs.sentry.io/platforms/apple/dsym/#xcode-build-phase and test if you see them uploaded here: https://ORG.sentry.io/settings/projects/PROJECT/debug-symbols/

### Expected Result

Seeing debug symbols have been uploaded

### Actual Result

Shell script is run for a 0.1 seconds then continues in background, but output file is empty. The same script runs successfully if run manually, but perhaps something is going wrong as it's being backgrounded?

![Screenshot 2024-04-16 at 4 17 16 PM](https://github.com/getsentry/sentry-cocoa/assets/402/994aa417-09d2-4b7a-9e10-a40674785269)

**Comment by trevorturk** [comment]
I was able to sort this out, but I'll leave the issue open in case it's helpful to consider documentation updates, perhaps?

* I enabled `--force-foreground` as per https://docs.sentry.io/product/cli/dif/#upload-options
* I set `ENABLE_USER_SCRIPT_SANDBOXING` to `No` as per https://github.com/getsentry/sentry-cli/issues/1915#issuecomment-1921339708

All seems well now, thank you!

**Comment by trevorturk** [comment]
Thanks for the quick reply! FWIW I also found the Info.plist comment and link a bit confusing, and the link takes you to a Medium article that's pay-to-read, which is annoying. I ended up with the following:

```
export SENTRY_ORG=example
export SENTRY_PROJECT=example
sentry-cli debug-files upload --force-foreground --wait --include-sources "$DWARF_DSYM_FOLDER_PATH"
```

...and the following config:

![Screenshot 2024-04-17 at 9 39 51 AM](https://github.com/getsentry/sentry-cocoa/assets/402/4ed5ab92-78c8-42df-bce3-158da03e3f68)

I confirmed `--force-foreground` isn't required, so I think any further changes here are optional, but I would suggest considering linking to the config docs and maybe even calling out `--force-foreground` and `--wait` as reasonable things to start with, just as you recommend configuring with `options.debug` to start when using the SDK in your app. 

It seems to me that backgrounding essentially obscures errors, and if you're only running `debug-files upload` when Archiving to submit to the App Store etc, then you'd want to know if something went wrong here. 

No worries either way, and apologies for the noise, this was essentially my fault, but I found it a bit hard to navigate and I think some tweaks to the docs would go a long way for future users. 

Thanks!

**Comment by brustolin** [comment]
Thank you very much for the update. I like your suggestions, I will amend the docs with it.

**Comment by armcknight** [comment]
Thanks for the feedback @trevorturk, this part especially is exactly the feedback I have provided in the past about this tool: 

> It seems to me that backgrounding essentially hides errors, and if you're only running debug-files upload when Archiving to submit to the App Store etc, then you'd want to know if something went wrong here. So, even beyond starting with those flags to ensure everything is working, I don't think it's a bad idea to keep them on?

I've alluded to this in some issues I raised in the past, but I think that we should explicitly demonstrate using that in our docs, at least for a release config. I opened an issue here: https://github.com/getsentry/sentry-docs/issues/9748
