### ISSUE TITLE
Swift Package Manager non-binary Target for "Sentry"

### ISSUE THREAD

**Issue by naftaly** [getsentry/sentry-cocoa#3864]
### Problem Statement

The main "Sentry" target in SPM is a binary download which makes it very difficult to make changes and quickly test them while using SPM.

### Solution Brainstorm

Remove the binary targets and change them to normal targets. It's not super simple right now due to the layout of the source code.

### Are you willing to submit a PR?

Not just yet.

**Comment by brustolin** [comment]
Hello @naftaly! Thanks for reaching out.
Unfortunately, this is no longer possible. SPM does not support multi-language projects, and our project uses both Swift and Objective-C, which are now in the same target.
You can follow our plans to eventually make the SDK Swift only [here](https://github.com/getsentry/sentry-cocoa/issues/3780).
