### ISSUE TITLE
Validate `inAppIncludes`/`inAppExcludes` behavior in a sample app

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#3871]
### Description

Recently had a question about tracking UIViewControllers from dynamic frameworks, which looks to be avoided by default: https://github.com/getsentry/sentry-cocoa/blob/676e429128a264d3ac61c2e90e26149580495fec/Sources/Sentry/SentryUIViewControllerPerformanceTracker.m#L63-L68. 

We should add a dynamic framework target to one of the sample app projects so we can validate that and other behavior that uses the option.

ETA: There are some unit tests that make use of `inAppIncludes` to ensure we swizzle a UIVC from a dynamic framework: https://github.com/getsentry/sentry-cocoa/blob/676e429128a264d3ac61c2e90e26149580495fec/Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift#L160-L166

But that doesn't test the _default_ behavior of _not_ swizzling that UIVC. So maybe just doing that would close the loop here.

Also: we could add more details on what exactly is governed by `inAppIncludes` and excludes, in SentryOptions.h and https://docs.sentry.io/platforms/apple/guides/ios/configuration/options/#in-app-include.

**Comment by philipphofmann** [comment]
I need more clarification on what the aim of this issue is. Is something not working, or do you think we need extra tests to validate the behavior?

**Comment by armcknight** [comment]
This was brought up because someone is delivering view controllers from a separate framework target that is linked by their main app target. I can't remember now if they were expecting to see it tracked but it isn't, or vide versa.

I'm a little confused about what that unit test I linked about is supposed to accomplish. Why does it add the view controller to inAppIncludes at https://github.com/getsentry/sentry-cocoa/blob/e19cca315a89dc377bdeeb5c9ed33d0038720eaa/Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift#L30-L33 ?

**Comment by philipphofmann** [comment]
@brustolin added these lines in https://github.com/getsentry/sentry-cocoa/pull/3440. My guess is to validate that the ExternalUIViewController from an external image gets swizzled, which is what the following test validates https://github.com/getsentry/sentry-cocoa/blob/e19cca315a89dc377bdeeb5c9ed33d0038720eaa/Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift#L160-L166

**Comment by armcknight** [comment]
I guess I'll close this unless it bubbles back up from support.
