### ISSUE TITLE
Filter out Screenshot Capture by Screen using a Callback

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-cocoa#3902]
### Problem Statement

can do it in other mobile sdk's but not in iOS

### Solution Brainstorm

offer callback function for it like in android
<img width="1171" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/8920574/53dc0fd0-9c76-4e06-a479-859523e20079">

**Comment by brustolin** [comment]
Thanks for reaching out. This feature makes sense and we will add it to our backlog.

**Comment by markushi** [comment]
Thanks for bringing this up again. Closing as dup of https://github.com/getsentry/sentry-cocoa/issues/3137
