### ISSUE TITLE
App Hang Report Allowlist 

### ISSUE THREAD

**Issue by kingnight** [getsentry/sentry-cocoa#3906]
### Problem Statement

Sentry App hang monitors whether there is an allowlist or denylist mechanism that can exclude certain classes of monitoring and do filter reporting.

**Comment by philipphofmann** [comment]
No there isn't an allow or denylist for app hang reports, but you can use [beforeSend](https://docs.sentry.io/platforms/apple/configuration/filtering/#filtering-error-events) to filter out unwanted app hang events:
```Swift
options.beforeSend = { event in
    if (event.exceptions?.first?.type == "App Hanging") {
        // do your stuff
    }
    
    return event
}
```

**Comment by philipphofmann** [comment]
PR for updating the docs https://github.com/getsentry/sentry-docs/pull/9822.

**Comment by philipphofmann** [comment]
We don't see a high demand for this right now. You can use the workaround specified in https://github.com/getsentry/sentry-cocoa/issues/3906#issuecomment-2078762754. We can close this.
