### ISSUE TITLE
`beforeSend` skipped if breadcrumbs > 100

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#3928]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.25.0

### Steps to Reproduce

1. set `SentryOptions.maxBreadcrumbs = 500`
2. add `SentryOptions.beforeSend = cb`
3. add many breadcrumbs, eg. `for i in 1 ... 150 { SentrySDK.addBreadcrumb(Breadcrumb(level: .debug, category: "test")) }`
4. send a message eg. `SentrySDK.capture(message: "testing")`
5. put a breakpoint in the beforeSend callback

### Expected Result

breakpoint is triggered when the event needs to get sent.

### Actual Result

no breakpoint is triggered and the event is sent as-is, without any `beforeSend` processing.

**Comment by lhunath** [comment]
Note:
- discovered here: https://github.com/getsentry/sentry-cocoa/issues/3925#issuecomment-2087187522
- restoring the `maxBreadcrumbs` cap to the default `100` allows the break-point to get fired again, we see only the last 100 breadcrumbs present in the event.

**Comment by kahest** [comment]
Thanks for opening this issue and the additional notes, we'll investigate and fix this 🙏

**Comment by brustolin** [comment]
Hello @lhunath. Do you have any other settings on your SentryOptions. I tried to follow your steps to reproduce and the app do stop in the breakpoint.

**Comment by lhunath** [comment]
open func sentry(options: Sentry.Options) {
        // TODO: https://github.com/getsentry/team-mobile/issues/24
        // options.enabled = false
        options.sendDefaultPii = true
        options.environment = AppInfo.shared.configuration.lowercased()
        options.enablePreWarmedAppStartTracing = true
        options.enableMetricKit = true
        options.swiftAsyncStacktraces = true
        options.initialScope = self.sentry(scope:)
        options.beforeSend = self.sentry(event:)
        options.attachScreenshot = true
        options.attachViewHierarchy = true

        switch AppInfo.shared.bundleIdentifier {
            case "com.netsoft.Hubstaff":
                options.dsn = <>
                options.tracesSampleRate = 0.01
                options.profilesSampleRate = 0.01
            default:
                options.dsn = <>
                options.tracesSampleRate = 0.1
                options.profilesSampleRate = 0.1
        }
    }

    open func sentry(scope: Sentry.Scope) -> Sentry.Scope {
        scope.setTag(value: AppInfo.shared.build, key: "app.build")
        scope.setTag(value: AppInfo.shared.version, key: "app.version")
        scope.setTag(value: AppInfo.shared.configuration, key: "app.configuration")
        scope.setTag(value: AppInfo.shared.reference, key: "app.reference")
        scope.setTag(value: AppInfo.shared.revision, key: "app.revision")
        return scope
    }

**Comment by kahest** [comment]
@lhunath I tried to repro the described behavior with the above settings, but didn't manage to. `beforeSend` is called as expected and the number of breadcrumbs capped at 500. Where do you invoke `startCrashLogger` from?
