### ISSUE TITLE
Crash report contains breadcrumbs logged on next launch

### ISSUE THREAD

**Issue by ainopara** [getsentry/sentry-cocoa#393]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

Crash report contains breadcrumbs logged on next launch
Will this issue be automatically fixed when 5.x released?

**Steps to reproduce:**
- make sure we are adding breadcrumbs when app launch
- trigger a crash
- launch again
- see the crash report in sentry website

**Actual result:**
- some of breadcrumbs logged when app launch appears in crash report

**Expected result:**
- crash report only contains breadcrumbs before crash happen

**Comment by philipphofmann** [comment]
Thanks, @ainopara for opening this issue. We are already on v 6.x.x and did a lot of fixes for breadcrumbs since 4.4.3. Can you please let us know if you still experience the issue there?

**Comment by ainopara** [comment]
Thank you for your reply, I think this issue has been fixed since 5.0.0, just forget to close.
