### ISSUE TITLE
`SentryUser.name` & `.segment` properties ignored

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#3933]
### Platform

iOS

### Environment

Production, Develop

### Installed

Swift Package Manager

### Version

8.25.0

### Steps to Reproduce

1. Create a `SentryUser` with a certain identifier.
2. Set the user's `username` and `name` properties.
3. Report a Sentry event.

```
self.sentryUser = userId.flatMap(Sentry.User.init)
self.sentryUser?.email = userEmail
self.sentryUser?.username = userName
self.sentryUser?.name = userName
self.sentryUser?.segment = userManager == "yes" ? "manager" : "user"
SentrySDK.setUser(self.sentryUser)
```

Example event: [us.sentry.io.json](https://github.com/getsentry/sentry-cocoa/files/15194917/us.sentry.io.json)

### Expected Result

The event payload & web app reports the user's human readable name and segment.

### Actual Result

The event payload & web app only report the user's userId, email and userName.
<img width="1131" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/36948/5c6ea1e9-1289-4e58-870e-e753e247e06a">

**Comment by brustolin** [comment]
Hello @lhunath, thanks for reaching out.

I could reproduce this, but it seems that the behaviour is flaky. Sometimes it appear sometimes it does not,
More investigation needed.

**Comment by lhunath** [comment]
I have not seen the missing information appear on the issue page ([this is the issue page](https://hubstaff.sentry.io/issues/5278254369/events/863b8b8487bb46e08927cb2dfbc97d5b/) for the error event attached in the description). I should point out that the information is also missing from the event JSON, so it would be surprising to me if it did show up later.

**Comment by brustolin** [comment]
I cant reproduce this. The name appears, but sometimes I need to refresh the issue page to see it.

**Comment by lhunath** [comment]
Segment continues to be absent from the issue page.
[sentry.json](https://github.com/user-attachments/files/15826531/sentry.json)
<img width="557" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/36948/e0a5410c-bd05-44ec-a0d3-993425563281">

**Comment by kahest** [comment]
`user.segment` is going to be removed from the product side and isn't supported by the new Contexts view. We're going to [deprecate and remove the property](https://github.com/getsentry/team-sdks/issues/44) from all SDKs soon. Apologie for the confusion.
If you need to report segment information, you can use [Context](https://docs.sentry.io/platforms/apple/enriching-events/context/) or [Tags](https://docs.sentry.io/platforms/apple/enriching-events/tags/).
