### ISSUE TITLE
Sentry start causes system audio to stop playing?

### ISSUE THREAD

**Issue by molind** [getsentry/sentry-cocoa#3961]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.25

### Did it work on previous versions?

8.21

### Steps to Reproduce

1. Start music in Apple Music
2. Start the app and with sentry inside

### Expected Result

Music should keep playing without interruptions.

### Actual Result

Musics pauses.

### Are you willing to submit a PR?

Not sure.

**Comment by brustolin** [comment]
Hello @molind thanks for reaching out.
Can you easily reproduce this? 
I tried and it didn't happen.
If you could provide a repro it would help us a lot.

**Comment by molind** [comment]
Hi @brustolin! Do you need a sample project, which reproduces this bug?
If it's enough to see it in the app - it in production in my app Guru Maps v5.5.6. I've checked again. It happens when app switches between foreground and background state.

**Comment by molind** [comment]
My bad. Seems it's not caused by sentry. Sorry for the false alarm.

**Comment by philipphofmann** [comment]
No worries, @molind. Thanks for the update.
