### ISSUE TITLE
Cocoapods link returns error 503

### ISSUE THREAD

**Issue by martin-1337** [getsentry/sentry-cocoa#398]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.x.x**

---
I have following issue:

the webpage of cocoapods sends sometimes an error 503. example: https://cocoapods.org/pods/CryptoSwift this happened within a browser (safari, firefox) and also with cURL. Who know more about that and more important who know a solution?

**Comment by HazAT** [comment]
https://github.com/getsentry/sentry-cocoa/issues/384#issuecomment-587324232
