### ISSUE TITLE
invalid version number in '-target arm64-apple-ios9999-simulator

### ISSUE THREAD

**Issue by lionel-alves** [getsentry/sentry-cocoa#3980]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.26

### Did it work on previous versions?

It is after updating to Xcode 15.4

### Steps to Reproduce

1. Add sentry-cocoa dependency using SPM, version 8.26.
2. Add Sentry static framework
3. Compile

### Expected Result

Should compile without error

### Actual Result

```
clang: error: invalid version number in '-target arm64-apple-ios9999-simulator'
```

### Note

It works with Senty-Dynamic framework.

**Comment by philipphofmann** [comment]
This is related to https://github.com/getsentry/sentry-cocoa/issues/3947. You can try the following workaround while we're investigating this, as mentioned in https://github.com/getsentry/sentry-cocoa/issues/3947#issuecomment-2100299654.


Cocoa SDK version 8.21.0 works both for Sentry and Sentry-Dynamic.

If you can't downgrade to 8.21.0, you can try to use Sentry-Dynamic, as mentioned in https://github.com/getsentry/sentry-cocoa/issues/3769#issuecomment-2007854765: 

![CleanShot 2024-05-08 at 12 48 41](https://github.com/getsentry/sentry-cocoa/assets/2443292/36419fbd-a79c-4e0a-b1c4-c998ace78fe8)

**Comment by matthewreimer** [comment]
FWIW with Xcode 15.4 (15F31d) it compiles fine if I target a simulator running 17.5, but if I target a physical iPad running 17.5 I get "invalid version number in '-target arm64-apple-ios9999'".

**Comment by philipphofmann** [comment]
It's weird, compiling an empty SwiftUI project for both Sentry and Sentry-Dynamic works for me on an M2 MacBook Pro with Xcode 15.4 on macOS `14.4.1` for both running a SwiftUI app on a Simulator with iOS 17.5 and on a real iPhone 12 with iOS 15.4, but when trying to run the app for MacCatalysit I get the same error as mentioned in https://github.com/getsentry/sentry-cocoa/issues/3984: `invalid version number in '-target arm64-apple-ios10.15-macabi`

**Comment by philipphofmann** [comment]
@matthewreimer and @lionel-alves, maybe the steps pointed out here help to solve your problem: https://github.com/getsentry/sentry-cocoa/issues/3984#issuecomment-2112246277.

**Comment by fnazarios** [comment]
This is also happening on watchOS app with the same `-target arm64-apple-watchos9999-simulator` error

**Comment by philipphofmann** [comment]
@fnazarios, can you try if the steps explained it https://github.com/getsentry/sentry-cocoa/issues/3984#issuecomment-2112246277 solve your problem please?

**Comment by fnazarios** [comment]
@philipphofmann Unfortunately, it didn't have any effect.

**Comment by n8sters** [comment]
Similar boat over here. Some devs can build following the steps mentioned in issue 3984, but others cannot. We're also unable to run test targets. Sorry folks, the Xcode update break strikes again. :(

**Comment by farmer-dhi** [comment]
This issue is affecting me as well. Tried the fix mentioned here: [https://github.com/getsentry/sentry-cocoa/issues/3984#issuecomment-2112246277](url). It worked on my local machine, but not for the remote Mac Mini that acts as our test server.

**Comment by DevKarlKlein** [comment]
Same here, however using Sentry-Dynamic as suggested instead resolved the issue.

**Comment by philipphofmann** [comment]
[According to Apple staff in the Apple forum](https://forums.developer.apple.com/forums/thread/751573) this an issue with Xcode, and the recommendation is to stick to Xcode 15.3.

**Comment by brustolin** [comment]
If you were using Sentry version 8.25.0 or lower and got this error, then updated to version 8.26.0 and still got this error, it is due to some Xcode caching. I had to clean derived data folder and reopen Xcode in order to have it working.

**Comment by philipphofmann** [comment]
@brustolin, I already suggested that in https://github.com/getsentry/sentry-cocoa/issues/3984#issuecomment-2112246277, but it seems not to work for everybody; see https://github.com/getsentry/sentry-cocoa/issues/3980#issuecomment-2112612497.

**Comment by brustolin** [comment]
> @brustolin, I already suggested that in https://github.com/getsentry/sentry-cocoa/issues/3984#issuecomment-2112246277, but it seems not to work for everybody; see https://github.com/getsentry/sentry-cocoa/issues/3980#issuecomment-2112612497.

Strange, I can easily reproduce this.

**Comment by n8sters** [comment]
If it helps, all 14 of our devs have now been able to run against iOS 17.2 on Xcode 15.4. I'm not knowledgeable enough to know what may be specific about 17.2, but figured I'd share.

**Comment by gfpacheco** [comment]
I was on 8.24.0, upgrading to 8.26.0 fixed it for me

**Comment by theedov** [comment]
I was getting this before when trying to run on a simulator, 8.26.0 fixed it but now I'm getting the same error when trying to load a preview.

**Comment by munhitsu** [comment]
just tested on 8.26.0 after purging all Xcode related Caches & ~Library/Developer/Xcode/
- iOS builds fine
- macOS Catalyst fails

error: `clang:1:1 invalid version number in '-target arm64-apple-ios10.15-macabi'`


Apple clang version 15.0.0 (clang-1500.3.9.4)
Xcode Version 15.4 (15F31d)

**Comment by brustolin** [comment]
@munhitsu The maccatalist problem is a Xcode bug as explained in [this issue](https://github.com/getsentry/sentry-cocoa/issues/3984)

**Comment by choulepoka** [comment]
Going back to 8.21.0 seems to fixes the issue.

**Comment by philipphofmann** [comment]
As previously mentioned, this is a [bug in Xcode](https://forums.developer.apple.com/forums/thread/751573), and we can only wait for Apple to fix the bug and refer to our [troubleshooting docs](https://docs.sentry.io/platforms/apple/troubleshooting/#xcode-compiler-error-invalid-version) to solve this issue.
