### ISSUE TITLE
MacCatalyst build initially fails with: invalid version number in '-target arm64-apple-ios10.15-macabi'

### ISSUE THREAD

**Issue by jknlsn** [getsentry/sentry-cocoa#3984]
### Platform

iOS, macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.26.0

### Steps to Reproduce

Building always fails for MacCatalyst initially before succeeding on Xcode 15.4, whereas it succeeds on first try on 15.3.

**Steps**
1. Create a new iOS app.
2. Remove Mac for iPad, add MacCatalyst target.
3. Add Sentry SDK package from `https://github.com/getsentry/sentry-cocoa.git`, adding `Sentry` and `SentrySwiftUI` to target.
4. Clean build folder, build and run to Mac.

### Expected Result

Build succeeds and runs (happens on Xcode 15.3)

### Actual Result

Initially fails. Build and run again immediately after, works.

On Xcode 15.4, any time that I clean and then build, it first fails and then will succeed. After this the build will always succeed, unless cleaned in between. This has caused our Xcode Cloud builds that recently updated to using Xcode 15.4 to fail, as they just fail and don't try to build again.

I found this [related discussion on the Apple Developer Forums](https://forums.developer.apple.com/forums/thread/751573?page=1#787709022), and added this information there as well, as it may not be able to be fixed but I don't know if there is a workaround that could be implemented. In the meantime I am using Xcode 15.3 for Xcode Cloud.

### Are you willing to submit a PR?

No, I haven't figured out a fix!

**Comment by jaderyang-sms** [comment]
Same here.

**Comment by philipphofmann** [comment]
@jaderyang-sms and @jknlsn lets me run an empty iOS app on MacCatalyst:

1. Performa a build clean
2. Quit Xcode
3. Delete the derived data folder
4. Start Xcode and build the project
5. Xcode complains with the mentioned error above
6. Hit run app in Xcode. The build error persists, but I can run the app.

**Comment by philipphofmann** [comment]
[According to Apple staff in the Apple forum](https://forums.developer.apple.com/forums/thread/751573) this an issue with Xcode, and the recommendation is to stick to Xcode 15.3.

**Comment by choulepoka** [comment]
I do not know if this helps, but reverting to Sentry 8.21.0 seems to fix the issue.

**Comment by philipphofmann** [comment]
As previously mentioned, this is a [bug in Xcode](https://forums.developer.apple.com/forums/thread/751573), and we can only wait for Apple to fix the bug and refer to our [troubleshooting docs](https://docs.sentry.io/platforms/apple/troubleshooting/#xcode-compiler-error-invalid-version) to solve this issue.
