### ISSUE TITLE
Cannot see the logs on Sentry from live application

### ISSUE THREAD

**Issue by mrchauhan2802** [getsentry/sentry-cocoa#3990]
### Platform

iOS

### Environment

Develop, TestFlight

### Installed

CocoaPods

### Version

8.25.0

### Did it work on previous versions?

No

### Steps to Reproduce

So I have implemented the Sentry and tested from my device I can see very logs and my app have three environment which shows fine as well

The issue is when I released the stage and production app and other people have installed from AppCenter and TestFlight, I Can's their logs.

I can't see any logs from their device. 

Wanted to know what I am doing wrong.

### Expected Result

To see the logs from all devices 

### Actual Result

Cannot see any logs, only when I run from Xcode I can able to see logs.

### Are you willing to submit a PR?

No

**Comment by philipphofmann** [comment]
@mrchauhan2802, I'm unsure what you mean by logs. Please specify that or share some screenshots.

**Comment by mrchauhan2802** [comment]
> @mrchauhan2802, I'm unsure what you mean by logs. Please specify that or share some screenshots.

logs means I can't see any events on Sentry like in issues section for other devices. When I run from Xcode I can see events or logs in the issues section. But when I generate the app and release to AppCenter and TestFlight I can't see any logs. Is it something with the fast lane ?

**Comment by philipphofmann** [comment]
Can you share the options you pass to the SentrySDK without your DSN, of course? Maybe there's a problem in there.

**Comment by mrchauhan2802** [comment]
> Can you share the options you pass to the SentrySDK without your DSN, of course? Maybe there's a problem in there.

[SentrySDK startWithConfigureOptions:^(SentryOptions * options) {
        options.debug = NO; // Enabled debug when first installing is always helpful
        options.enableTracing = YES;
        options.environment = self.environment;

        options.attachScreenshot = NO; //This will add a screenshot to the error events
        options.attachViewHierarchy = YES; //This will add the view hierarchy to the error events
    }];

**Comment by mrchauhan2802** [comment]
The issue has been resolved. The logs always were there the issue with me the way I was looking was wrong. thank you for your reply. I am closing the issue.
