### ISSUE TITLE
Wrong value in "In Foreground" for every sentry event

### ISSUE THREAD

**Issue by ljql2001** [getsentry/sentry-cocoa#3991]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.24.0

### Did it work on previous versions?

I don't know. We are starting at this version.

### Steps to Reproduce

When app enters background and foreground, the context[@"app"][@"in_foreground"] field is wrong in every event. 

The value seems to remain the same value no matter it is YES or NO since app starts.

As I debug the codes, this issue seems to come from LN 634 in SentryClient.m: SentryAppState *appState = [manager loadPreviousAppState];

### Expected Result

The value of context[@"app"][@"in_foreground"] field is correct when app enters background and foreground.

### Actual Result

The value seems to remain the same value no matter it is YES or NO since app starts.

### Are you willing to submit a PR?

No

**Comment by philipphofmann** [comment]
That's a good catch thanks. The culprit is here https://github.com/getsentry/sentry-cocoa/blob/2b9e267bed9a82a1f7009846cfb10bf27840b836/Sources/Sentry/SentryClient.m#L633-L635

This is an easy fix.
