### ISSUE TITLE
"invalid destination port" in SentryCrashCPU.c when calling snapshotStacktrace

### ISSUE THREAD

**Issue by diesal11** [getsentry/sentry-cocoa#400]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> If yes, which version? 5.0
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

Occasionally when generating a stackTrace to attach to an event some threads will fail to generate a stack. 

**Steps to reproduce:**
This is the code we use to generate events for Sentry.

```swift
        let exception = Exception(
            value: errorStringReflection,
            type: nsError.domain
        )

        let event = Event(level: level)
        event.exceptions = [exception]
        event.message = errorStringReflection
        Client.shared?.snapshotStacktrace {
            Client.shared?.appendStacktrace(to: event)
            Client.shared?.send(event: event)
        }

```

**Actual result:**
Some threads have no stack trace, and the following error is logged to console multiple times:
```
ERROR: SentryCrashCPU.c (58): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
```

**Expected result:**
All threads have a stackTrace & no errors are logged.

**Comment by Fab1n** [comment]
Are there any updates on this issue? We have the same issue. Is this only a debug thing?

**Comment by philipphofmann** [comment]
We released version 5.x.x a few weeks ago. Since v 5.1.2 the SDK can attach stacktraces to custom events. Just make sure you have `attachStacktrace` enabled in the `SentryOptions` like this:
```
SentrySDK.start(options: [
    "dsn": "__PUBLIC_DSN__",
    "attachStacktrace": true
])
```
Is there a reason you can't update to 5.x.x?

**Comment by diesal11** [comment]
@philipphofmann do stacktraces in 5.x capture stacks for all threads or just the thread in which the error was raised?

Part of what has made a migration of our app from 4.x to 5.x difficult is the significant lack of documentation around what has changed. I know there is the Migration document but it doesn't cover everything. I.E. For a while there stack traces weren't even possible in 5.x and this newly added functionality still isn't documented anywhere within repo or official docs.

**Comment by philipphofmann** [comment]
Thanks for reaching out to us @diesal11. The stack trace is just attached for the current thread. I just opened up a PR for updating the code comment on `SentryOptions.attachStacktrace`, see #596. You can also check out our docs: https://docs.sentry.io/error-reporting/configuration/?platform=swift#attach-stacktrace

**Comment by philipphofmann** [comment]
Since 6.x.x attachStacktrace is enabled per default and we updated the comment. We are going to close this issue now.
