### ISSUE TITLE
Sentry-cocoa package can not be resolved. 

### ISSUE THREAD

**Issue by deepaksinghin** [getsentry/sentry-cocoa#4023]
### Description

I'm using SPM to integrate sentry-cocoa `https://github.com/getsentry/sentry-cocoa` version `8.26.0`
**sentry-cocoa.git could not be resolved**

`• @ giphy-ios-sdk
• @ Updating from https://github.com/Giphy/giphy-ios-sdk.git
• • Updating from https://github.com/Giphy/giphy-ios-sdk.git
v @ pipeable-ios
• @ Updating from https://github.com/PipeableHQ/pipeable-ios.git
• @ Updating from https://github.com/PipeableHQ/pipeable-ios.git
v @ sdk-ios-pkg
• Updating from https://github.com/anon-dot-com/sdk-ios-pkg
• • Updating from https://github.com/anon-dot-com/sdk-ios-pkg
<（• swift
• @ Updating from https://github.com/auth0/JWTDecode.swift
•@ Updating from https://github.com/authO/JWTDecode.swift
• @ Kingfisher
• • Updating from https://github.com/onevcat/Kingfisher.git v @ Updating from https://github.com/onevcat/Kingfisher.git
• • ScalingHeaderScrolIView
• @ Updating from https://github.com/exyte/ScalingHeaderScrollView.git
• Updating from https://github.com/exyte/ScalingHeaderScrollView.git
v @ analytics-swift
@ Updating from git@github.com:segmentio/analytics-swift.git @ Updating from git@github.com:segmentio/analytics-swift.git
@ git@github.com:segmentio/analytics-swift.git: An unknown error occurred. reference 'refs/remotes/origin/main' not found (-1)
• @ Updating from git@github.com:segmentio/analytics-swift.git
• @ Updating from git@github.com:segmentio/analytics-swift.git v @ sendbird-chat-sdk-ios
• @ Updating from https://github.com/sendbird/sendbird-chat-sdk-ios
• @ Updating from https://github.com/sendbird/sendbird-chat-sdk-ios
• @ Starscream
• @ Updating from https://github.com/daltoniam/Starscream.git
• @ Updating from https://github.com/daltoniam/Starscream.git
• @ swiftui-introspect.
• Updating from https://github.com/siteline/swiftui-introspect @ Updating from https://github.com/siteline/swiftui-introspect
• @ libwebp-Xcode
•@ Updating from https://github.com/SDWeblmage/libwebp-Xcode
@ Updating from https://github.com/SDWeblmage/libwebp-Xcode
v • sovran-swift
• @ Updating from https://github.com/segmentio/sovran-swift.git`

![Uploading Screenshot 2024-05-30 at 1.25.29 PM.png…]()

**Comment by brustolin** [comment]
Hello @deepaksinghin, thanks for reaching out. 
I didn't get the problem, the log dont even mention Sentry. 
Can you give more information? Maybe another log with the error. 
I cant reproduce the problem when adding Sentry with SPM.

**Comment by 0xhex** [comment]
same issue iOS 18 Xcode 16

**Comment by brustolin** [comment]
Hello @0xhex. Could you please provide more details about your problem?

Are your SPM log and the issue description identical?

If possible, could you share the log with us?

Also, please describe the steps you take to reproduce this error.
