### ISSUE TITLE
Unsymbolicated stack trace for Swift project

### ISSUE THREAD

**Issue by Molyakos** [getsentry/sentry-cocoa#405]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.1.3
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.1**

---
I have following issue:
When my app crashed, I getting unsymbolicated stack trace. But any library (RxSwift right now) is symbolicated. ObjC code also symbolicated. I.E. I getting unsymbolicated stack trace for my target only. All dsyms files from ITC was uploading to server. Why? How can I fix it?
<img width="848" alt="Снимок экрана 2020-03-07 в 16 26 50" src="https://user-images.githubusercontent.com/14042410/76144419-342b5180-6091-11ea-89b2-91d798a96bf2.png">

**Steps to reproduce:**
- Install sentry-cocoa 4.4.1
- Crash app from swift code

**Actual result:**
- Stack trace is unsymbolicated

**Expected result:**
- Stack trace is symbolicated

**Comment by philipphofmann** [comment]
Thanks @Molyakos for reaching out to us. Can you try to update to the latest 5.x.x version and let us know if you still experience this issue?

**Comment by philipphofmann** [comment]
As we didn't receive an update for this the last two weeks, I'm going to close this now. Please open it again @Molyakos if you need help.
