### ISSUE TITLE
Can't build with Xcode 16.0 Beta 1

### ISSUE THREAD

**Issue by enricenrich** [getsentry/sentry-cocoa#4050]
### Platform

iOS, iPadOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.28.0

### Xcode Version

16.0 (Beta 1)

### Did it work on previous versions?

15.4

### Steps to Reproduce

1. Install Xcode 16.0 (Beta 1).
2. Build the app.

### Expected Result

The app builds and runs as in Xcode 15.4.

### Actual Result

The process fails with multiple errors in Sentry's SDK. Concretely, the `SentryCrashMonitor_CPPException.cpp` file.

![screen-2024-06-10-23-09-TAT25TKF](https://github.com/getsentry/sentry-cocoa/assets/357265/7ebed655-050e-4b26-9d2a-3e9d8716e00f)

**Comment by josh150** [comment]
Updating to 8.28.0 fixed this compilation issue for me. Based on release notes 8.27.0 likely compiles as well.

**Comment by Zandor300** [comment]
@josh150 I tried compiling my app for iOS 18 with Sentry 8.28.0 and got the same compilation issue as OP.

**Comment by zhangpeibj01** [comment]
@Zandor300 This did not work for me either.

**Comment by zhangpeibj01** [comment]
@Brett-Best Thanks!

**Comment by enricenrich** [comment]
Thanks @Brett-Best. Please, let us know when a new release is made for us to update.

**Comment by andrescala** [comment]
It is failing to me using React native..
[!] CocoaPods could not find compatible versions for pod "Sentry/HybridSDK":
  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 5.23.1, which depends on
      Sentry/HybridSDK (= 8.27.0)

Trying to install 8.28 as well directly and says cocoapods cannot find such version.

**Comment by kahest** [comment]
@andrescala we will release the fix for sentry-cocoa today, our React Native SDK then needs to bump the dependency and release the fix separately. Please refer to https://github.com/getsentry/sentry-react-native/issues/3883 to check the status of this issue for our React Native SDK.

**Comment by brustolin** [comment]
New version (8.29.0) available with the solution for this problem.
Thank you all for bringing this up.

**Comment by enricenrich** [comment]
Thanks, @brustolin!

**Comment by hoangnk1701** [comment]
i fix it:
class: SentryCrashMonitor_CPPException
add: #include <exception>
try it. hope help

**Comment by SonlamNguyenBC** [comment]
Do we have a fix for sentry/angular-ivy? Also seeing the same issues

**Comment by kahest** [comment]
@SonlamNguyenBC do you use [sentry-capacitor](https://github.com/getsentry/sentry-capacitor)? If so, you can use release 0.19.0 or 1.0.0

**Comment by duynghiale** [comment]
> i fix it: class: SentryCrashMonitor_CPPException add: #include include exception try it. hope help

how do you fix it ?

**Comment by stamayo1** [comment]
> > i fix it: class: SentryCrashMonitor_CPPException add: #include include exception try it. hope help
> 
> how do you fix it ?

Hi, i fix it, following the next steps:

1. On cmd, you need to navigate to ios folder and App folder: **<project_name> ios > app**
2. Execute **pod install --repo-update**  
3. Later execute **pod update Sentry/HybridSDK**

Following that steps you can build the project

**Comment by duynghiale** [comment]
> > > i fix it: class: SentryCrashMonitor_CPPException add: #include include exception try it. hope help
> > 
> > 
> > how do you fix it ?
> 
> Hi, i fix it following the next steps:
> 
> 1. On cmd, you need to navigate to ios folder and App folder: **<project_name> ios > app**
> 2. Execute **pod install --repo-update**
> 3. Later execute **pod update Sentry/HybridSDK**
> 
> This is the result after you executed the commands.
> 
> ![Image](https://github.com/user-attachments/assets/8148ccd3-57ff-49dd-9f23-9afa3b9f087d)
> 
> Following that steps you can build the project

Currently in my project there is no Sentry/HybridSDK library, is there any other way?

**Comment by Prasang023** [comment]
What worked for me was:

- Open Xcode → Build Settings.
- Search for C++ Language Dialect.
- Set it to C++17 (-std=c++17).

The std::terminate_handler type was removed in C++20, which Xcode 16 may be enforcing.

**Comment by waseertanvir** [comment]
> Updating to 8.28.0 fixed this compilation issue for me. Based on release notes 8.27.0 likely compiles as well.

Just tried and tested. It worked.
