### ISSUE TITLE
5.0.0-beta.0 migration: not immediately clear how to set user

### ISSUE THREAD

**Issue by ristkof** [getsentry/sentry-cocoa#411]
As per [this migration guide](https://github.com/getsentry/sentry-cocoa/blob/5.0.0-alpha.0/MIGRATION.md), it is not immediately clear to me what the equivalent code will be for:

```
        let u = Sentry.User(userId: "")
        u.email = "a@b.com"
        Client.shared?.user = u
```

**Comment by HazAT** [comment]
Thanks for pointing this out, I've updated the samples
https://github.com/getsentry/sentry-cocoa/blob/master/MIGRATION.md

Also, this is how you set it globally:

https://github.com/getsentry/sentry-cocoa/blob/93651b8a8e19f53a912d8a50ae64e2c28f01b2ab/Example/Example-objc/ViewController.m#L21-L27

https://github.com/getsentry/sentry-cocoa/blob/93651b8a8e19f53a912d8a50ae64e2c28f01b2ab/Example/Example/ViewController.swift#L17-L23
