### ISSUE TITLE
Cannot install sentry using cocoapods

### ISSUE THREAD

**Issue by MageSantana** [getsentry/sentry-cocoa#4127]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.30.0

### Xcode Version

15.4

### Steps to Reproduce

pod update

### Expected Result

Sentry library is installed

### Actual Result

[!] Failed to load 'Sentry' podspec: 
[!] Invalid `Sentry.podspec` file: undefined method `visionos' for #<Pod::Specification name="Sentry">.

**Comment by kahest** [comment]
Hey, this might be an issue with an outdated Cocoapods version, see here: https://github.com/getsentry/sentry-react-native/issues/3547#issuecomment-1911991437

Please check your version with `pod --version` and try if updating Cocoapods solves the issue.

**Comment by kahest** [comment]
On second thought/sight, looks like we might [need to add this for sentry-cocoa](https://github.com/getsentry/sentry-react-native/pull/3548#issuecomment-1909837447) as well - @krystofwoldrich do you have more context?

**Comment by MageSantana** [comment]
Yes, you’re right. I updated cocoa and the problem is solved. Thanks for your help @kahest.

**Comment by krystofwoldrich** [comment]
> On second thought/sight, looks like we might https://github.com/getsentry/sentry-react-native/pull/3548#issuecomment-1909837447 as well - @krystofwoldrich do you have more context?

If we would like to keep support for older cocoapods versions, we can add it. That's the only reason.

**Comment by kahest** [comment]
@krystofwoldrich got it, thanks - no need to add it then

**Comment by ThomasBuresi** [comment]
Hey ! Would you mind also updating : https://github.com/lyra/ios-sdk
So it can be compatible with the new versions 
Thanks for your work !

**Comment by kahest** [comment]
Hey @ThomasBuresi - we cannot update this, please get in touch with the Lyra maintainers.
