### ISSUE TITLE
Disable App Hang report in low memory conditions

### ISSUE THREAD

**Issue by eaigner** [getsentry/sentry-cocoa#4130]
### Problem Statement

I have several users that run a 64GB dev machine and still somehow manage to fill up their entire RAM until the OS starts paging - thus appearing as a hang.

<img width="228" alt="PNG image" src="https://github.com/getsentry/sentry-cocoa/assets/112197/2c1b6444-9483-4c48-bd08-296f87891c82">

I propose to introduce a free memory limit for reporting app hangs.
Set it to a default of lets say `500MB` of memory that must be free for the hang to be reported.

**Comment by kahest** [comment]
Hey @eaigner thanks for the suggestion - we'll discuss if we want to add this. In the mean time, you could use `beforeSend` to filter App Hang events you don't want, like described in our [docs](https://docs.sentry.io/platforms/apple/guides/ios/configuration/app-hangs/). 

For example you could do the following:
```
options.beforeSend = { event in
  if (event.exceptions?.first?.type == "App Hanging") {
    if let freeMemory = event.context?["device"]?["free_memory"] as? UInt64, freeMemory < 50 * 1024 * 1024 {
      return nil
    }
  }
  return event
}
```
Note, however, that `free_memory` will contain the actual free memory as reported by the system (and in Sentry) and does not include quickly usable memory such as `inactive`.

**Comment by brustolin** [comment]
The snippet provided is the solution we suggest. 
The SDK has no way to detect whether the APP hang is caused by memory swap or a actual problem of the app.
