### ISSUE TITLE
Allow attachments to be uploaded to crash events

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-cocoa#4137]
### Problem Statement

Opening as the result of a customer conversation:

Currently [the docs say](https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/attachments/):
> Adding attachments to crashes is currently not supported.

It would be useful to be able to add attachments to crashes, for example log files.

### Notes:

This probably wouldn't be a simple change - Internally on slack, @armcknight noted:
> that’ll probably need something much more comprehensive like an RFC, because it would probably be a change to the SDK protocol and require backend/frontend changes

**Comment by brustolin** [comment]
Thanks @cstavitsky for reaching out.
This will be possible after we introduce #2325

**Comment by brustolin** [comment]
You can track the progress of this feature at https://github.com/getsentry/sentry-cocoa/issues/2325 and #1460
