### ISSUE TITLE
Session Replay: Fix redacting elements under translucent objects

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#4142]
### Description

Example from RN Sample app. The purple rectangle is above text, because it has translucent corners it reveals the text under itself.

![Screenshot 2024-07-02 at 18 15 02](https://github.com/getsentry/sentry-cocoa/assets/31292499/fd6513f6-5b7a-4511-ade0-77c07d47f69b)

https://sentry-sdks.sentry.io/replays/95c16035838a466c9fcaa7ceeb86533a/?project=5428561&query=&referrer=%2Freplays%2F&statsPeriod=30d&yAxis=count%28%29

Android for reference

![Screenshot 2024-07-02 at 18 19 54](https://github.com/getsentry/sentry-cocoa/assets/31292499/7db65254-5053-414a-9fc0-6af54d423c4b)

**Comment by brustolin** [comment]
This was fixed already
