### ISSUE TITLE
add `shellcheck` precommit hook

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#4149]
### Description

to lint shell scripts

**Comment by brustolin** [comment]
Our scripts are not part of the product but tools to automate things. 
Adding lint to them is just an extra unnecessary headache

**Comment by philipphofmann** [comment]
If ShellCheck improves the quality of our shell scripts our developer workflow should benefit and therefore make us more productive. I think we can give this a shot both as a pre commit hook and CI and see how it goes. We can always ditch it if it's a headache.
