### ISSUE TITLE
[SR] Elements with zPosition (zIndex) might brake redaction

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#4154]
### Description

If element is in the view hierarchy first before its background/frame and then moved in front of it using `zPosition` (`zIndex` in React Native) this element won't be redacted.

Example of this from Blsky client https://github.com/krystofwoldrich/bluesky-social-app/blob/9835d199bf080a877eaf4e53c816babfd0e5e254/src/components/forms/TextField.tsx#L172

Using https://github.com/getsentry/sentry-cocoa/releases/tag/8.30.0 and https://github.com/getsentry/sentry-react-native/pull/3930/commits/e9c611678d832d3d30ba674caf70ccd58cec8ab0

This example is from my build of https://github.com/krystofwoldrich/bluesky-social-app/pull/1

![Screenshot 2024-07-10 at 12 37 32](https://github.com/getsentry/sentry-cocoa/assets/31292499/f44153a0-791d-4daa-8bd9-5c306ec7f137)

**Comment by brustolin** [comment]
This was fixed with https://github.com/getsentry/sentry-cocoa/pull/4309
