### ISSUE TITLE
Replay: Redaction missing in some areas

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#4167]
When clicking on "High CPU" sample, thgere'a moment a few texts are exposes even though redaction is enabled:

https://sentry-sdks.sentry.io/replays/c18bcece0fd24d0b8762a46656d640f6/?project=5428557&query=&referrer=%2Freplays%2F&statsPeriod=30d&yAxis=count%28%29

![image](https://github.com/user-attachments/assets/c05dd4b4-a69c-410c-a31c-02759fbf3c21)

**Comment by cmanallen** [comment]
PII sensitive customer is reporting incorrect masking: https://sentry.slack.com/archives/C03USURCFBJ/p1734038144883999?thread_ts=1734036751.582039&cid=C03USURCFBJ

**Comment by brustolin** [comment]
> PII sensitive customer is reporting incorrect masking: https://sentry.slack.com/archives/C03USURCFBJ/p1734038144883999?thread_ts=1734036751.582039&cid=C03USURCFBJ

The issue in question was in the android environment.

**Comment by brustolin** [comment]
This was fixed in many PRs, the last one is #4574
