### ISSUE TITLE
Replay: One tap results in 9 navigation breadcrumbs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#4168]
Maybe related to:
* https://github.com/getsentry/sentry-cocoa/issues/4166

Replay: https://sentry-sdks.sentry.io/replays/c18bcece0fd24d0b8762a46656d640f6/?project=5428557&query=&referrer=%2Freplays%2F&statsPeriod=30d&yAxis=count%28%29

![image](https://github.com/user-attachments/assets/dea0fb44-271a-487d-991d-426d93711acc)

**Comment by cmanallen** [comment]
Still happening?

**Comment by brustolin** [comment]
Fixed with #4480
