### ISSUE TITLE
firebase Crash 

### ISSUE THREAD

**Issue by arronponyft** [getsentry/sentry-cocoa#4169]
### Platform

iOS

### Environment

Production

### Installed

CocoaPods

### Version

8.30.1

### Xcode Version

15.2

### Did it work on previous versions?

yes

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/c827af0f-323e-41aa-b570-f147521e4869)

### Expected Result

fix bug 

### Actual Result

fix bug

### Are you willing to submit a PR?

james

**Comment by brustolin** [comment]
This is related to  #3997.
Please add any new information there.
