### ISSUE TITLE
 Redefinition of module '_SentryPrivate'

### ISSUE THREAD

**Issue by ramprasadAnand** [getsentry/sentry-cocoa#4181]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.31.1

### Xcode Version

15.4

### Steps to Reproduce

- Adding the Sentry as cocoapod dependency to my framework project 
- Using the framework in a project which has sentry integrated already (using cocoapods)
- Building the project is giving this error.

### Expected Result

The build should succeed without any compiler errors

### Actual Result

 Redefinition of module '_SentryPrivate'

**Comment by brustolin** [comment]
Hello @ramprasadAnand thanks for reaching out.
This looks like a cocoapod restriction that is not aware of that two dependencies are the same, I don't have a suggestion on how to solve this.

That being said, Sentry SDK is not meant to be used in a framework. We don't support this, and the app should have only one instance of Sentry Running.

**Comment by ramprasadAnand** [comment]
@brustolin thanks for the quick revert. I would like to summarise our requirement.
We use sentry for real time error monitoring in our SDKs, We are using sentry's cocoapod as dependency. 
- We are able to build our frameworK
- We are able to use Sentry APIs which are exposed for capturing the exceptions.

Challenges :
We are setting Sentry as the spec dependency of our framework, While installing our framework as cocoapods, it will also install Sentry dependency in the App project. But while building the App project, we are getting this `Redefinition of module` error. 

Other cocoapod spec dependencies are seamlessly being used without any conflict in the App project, Sentry is the only dependency which is giving this error. 

Need your inputs on, how to use the Sentry in the iOS framework projects. and please suggest if there are any work around for this scenario.

**Comment by brustolin** [comment]
This is the first time I hear about this issue. Unfortunately, I don't know how you should proceed. The first thing that comes to mind is that maybe linking Sentry as a static library to your SDK may solve the problem.

But as mentioned before, we don't support this type of use, other frameworks should not have Sentry as dependency.

**Comment by brustolin** [comment]
If it works for you and it doesn't interfere with the app's own instance of Sentry, it's fine by us
