### ISSUE TITLE
Crash in Beta iOS Sentry replay

### ISSUE THREAD

**Issue by ShubhGar** [getsentry/sentry-cocoa#4185]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.31.1

### Xcode Version

15.1

### Steps to Reproduce

Just install sentry in app and it crash while app launch
Crash logs:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] Cannot call method when status is 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106949128 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000105bf012c objc_exception_throw + 56
	2   AVFCore                             0x0000000127a35ac4 -[AVAssetWriterInputHelper appendTaggedPixelBufferGroup:withPresentationTime:] + 0
	3   AVFCore                             0x0000000127a31718 -[AVAssetWriterInput _appendPixelBuffer:withPresentationTime:] + 64
	4   AVFCore                             0x0000000127a36198 -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] + 84
	5   PayU3DS2SwiftSample                 0x0000000104980d44 $s6Sentry0A11PixelBufferC6append5image16presentationTimeSbSo7UIImageC_So6CMTimeatF + 392
	6   PayU3DS2SwiftSample                 0x000000010499c170 $s6Sentry0A14OnDemandReplayC15createVideoWith9beginning3end13outputFileURL10completiony10Foundation4DateV_AkI0L0VyAA0aF4InfoCSg_s5Error_pSgtctKFyyYbcfU_ + 424
	7   PayU3DS2SwiftSample                 0x00000001048b0c28 $sIegh_IeyBh_TR + 48
	8   AVFCore                             0x0000000127a38eb0 -[AVAssetWriterInputMediaDataRequester requestMediaDataIfNecessary] + 60
	9   libdispatch.dylib                   0x000000010ac280f0 _dispatch_call_block_and_release + 24
	10  libdispatch.dylib                   0x000000010ac2993c _dispatch_client_callout + 16
	11  libdispatch.dylib                   0x000000010ac31bd8 _dispatch_lane_serial_drain + 916
	12  libdispatch.dylib                   0x000000010ac3291c _dispatch_lane_invoke + 420
	13  libdispatch.dylib                   0x000000010ac3f2f8 _dispatch_root_queue_drain_deferred_wlh + 324
	14  libdispatch.dylib                   0x000000010ac3e754 _dispatch_workloop_worker_thread + 488
	15  libsystem_pthread.dylib             0x000000010af67814 _pthread_wqthread + 284
	16  libsystem_pthread.dylib             0x000000010af665d4 start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException

### Expected Result

it must be send video

### Actual Result

Crash

**Comment by brustolin** [comment]
Thanks for reaching out @ShubhGar, we will investigate.
