### ISSUE TITLE
Cannot enable/disable after init.

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#419]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.0-beta**

---
I have following issue:

You can enable / disable Sentry on init using `SentryOptions`'s `enabled`.  However, it doesn't appear as though there is a way to change this setting after the fact (eg. after a user has given consent or revoked it).

I'm unsure of what this option does at all if there isn't a way to change it post init.  If it's an init-only thing, wouldn't you just either init or not init at all?  Does an init'ed Sentry that is not enabled differ in any way from a non-init'ed Sentry?

**Comment by lhunath** [comment]
Looks like I can perhaps do:
```[SentrySDK.currentHub getClient].options.enabled = @YES;```

**Comment by HazAT** [comment]
@lhunath Yes you can do that, we will think of a more convenient API
cc @philipphofmann This is also something we need to consider that enabling/disabling the SDK should work at any time.

**Comment by bruno-garcia** [comment]
Docs point to "disable the SDK by providing an empty string as DSN". 
Would this suffice? Sentry Android for example doesn't have a `enabled` flag.

**Comment by lhunath** [comment]
> disable the SDK by providing an empty string as DSN

Sounds pretty hacky – I'd prefer the https://github.com/getsentry/sentry-cocoa/issues/419#issuecomment-610594087 hack over that one.

**Comment by bruno-garcia** [comment]
I actually agree in a way, but it's the official Sentry way to disable an SDK and it works in all SDKs.

I'm honestly not a fan of a mutable property on the options to change the behavior at runtime since a few assumptions could come. A disabled SDK should cause little or no overhead (like callbacks aren't executed, breadcrumbs aren't stored). Some would expexct that once enabled, the SDK would have collected state in the scope while it was disabled. For that reason, ideally we'd respect the current, official Sentry way of enabling/disabling the SDK which is passing just an empty string.

**Comment by bruno-garcia** [comment]
@HazAT @marandaneto @philipphofmann I'd also suggest we delete `[SentrySDK.currentHub getClient]` API. 

Is there a way to expose the Hub? This API is needed in JS but we don't have on Android for example. There's no need to let a user hold the reference of the Hub outside of the SentrySDK class, right?

**Comment by marandaneto** [comment]
> @HazAT @marandaneto @philipphofmann I'd also suggest we delete `[SentrySDK.currentHub getClient]` API.
> 
> Is there a way to expose the Hub? This API is needed in JS but we don't have on Android for example. 

it's `package-private` on Android, so it's not considered public API.

> There's no need to let a user hold the reference of the Hub outside of the SentrySDK class, right?

**Comment by philipphofmann** [comment]
If we disable the SDK after the SDK was initialized, the crash handlers of SentryCrash are still active. It would write a report to disk, and the next time the SDK is initialized, convert those crash reports to events. We would need to sync the enabled/disabled state to SentryCrash. Or am I missing something?

**Comment by bruno-garcia** [comment]
Sounds like the solution for this is to get `SentrySDK.close()` to work as it should. Stop reports from being written to begin with, so on restart they are not sent to the server.

**Comment by philipphofmann** [comment]
A customer asked about disabling/closing the SDK when an app is shutting down. They get crash events when the app is terminating, and they would like to ignore them.

**Comment by philipphofmann** [comment]
Since 7.0.0 you can now use `SentrySDK.close()` to close / disable the SDK.

**Comment by tmm1** [comment]
> can now use `SentrySDK.close()` to close / disable the SDK.

What about to re-enable?

**Comment by marandaneto** [comment]
just use `SentrySDK.start` again
