### ISSUE TITLE
Update sample rate naming for iOS Replay

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-cocoa#4213]
` options.experimental.sessionReplay.errorSampleRate = 1.0` --> ` options.experimental.sessionReplay.onErrorSampleRate = 1.0`

**Comment by brustolin** [comment]
> lets update our docs too? :D https://docs.sentry.io/platforms/apple/guides/ios/session-replay/

Yes!! : https://github.com/getsentry/sentry-docs/pull/10946
But we need to make a release before merging the docs
