### ISSUE TITLE
Crash reports not generated on visionOS

### ISSUE THREAD

**Issue by miki-shapr** [getsentry/sentry-cocoa#4217]
### Platform

visionOS

### Environment

Production

### Installed

CocoaPods

### Version

8.32.0

### Xcode Version

15.4

### Did it work on previous versions?

No

### Steps to Reproduce

1. make the app crash
2. on next launch print `SentrySDK.crashedLastRun`

### Expected Result

The value printed should be `true`.

### Actual Result

`false` is printed.

I've found that the root cause of the issue is that even though visionOS supports signals, the `SENTRY_HAS_SIGNAL` is set to `0` and thus no signal handlers are installed. The resolution should be to set the value of the flag to `1` on visionOS as well.

### Are you willing to submit a PR?

Yes

**Comment by brustolin** [comment]
Thanks @miki-shapr for reaching out.
I could reproduce this. We will investigate.

**Comment by philipphofmann** [comment]
@miki-shapr, does only `crashedLastRun` return the wrong value, or do no crash events appear in Sentry, or both? Also, how exactly do you make the app crash?

**Comment by miki-shapr** [comment]
@philipphofmann There are no crashes appearing in Sentry either. I made the app crash with `SentrySDK.crash()`.

As I've mentioned, the issue is that the `SENTRY_HAS_SIGNAL` and friends are defined to be 0 on visionOS even though they are in fact supported.

So essentially in `SentryInternalCDefines.h` there's a few `|| SENTRY_HOST_VISION` missing from the conditions that define the Sentry internal flags.

**Comment by philipphofmann** [comment]
@miki-shapr, would you be open to opening a PR to fix this?

**Comment by miki-shapr** [comment]
@philipphofmann Yeah sure, I'll open a PR soon!

**Comment by miki-shapr** [comment]
Hey @philipphofmann, something seems to be messed up with my GitHub and I'm not able to push my branch. Could you open the PR please? Here's the diff:

```diff
diff --git a/Sources/Sentry/include/SentryInternalCDefines.h b/Sources/Sentry/include/SentryInternalCDefines.h
index 4b6144c6..b32762e9 100644
--- a/Sources/Sentry/include/SentryInternalCDefines.h
+++ b/Sources/Sentry/include/SentryInternalCDefines.h
@@ -59,7 +59,7 @@ typedef unsigned long long bytes;
 
 // Mach APIs are explicitly marked as unavailable in tvOS and watchOS.
 // See https://github.com/getsentry/sentry-cocoa/issues/406#issuecomment-1171872518
-#if SENTRY_HOST_IOS || SENTRY_HOST_MAC
+#if SENTRY_HOST_IOS || SENTRY_HOST_MAC || SENTRY_HOST_VISION
 #    define SENTRY_HAS_MACH 1
 #else
 #    define SENTRY_HAS_MACH 0
@@ -67,19 +67,19 @@ typedef unsigned long long bytes;
 
 // signal APIs are explicitly marked as unavailable in watchOS.
 // See https://github.com/getsentry/sentry-cocoa/issues/406#issuecomment-1171872518
-#if SENTRY_HOST_IOS || SENTRY_HOST_MAC || SENTRY_HOST_TV
+#if SENTRY_HOST_IOS || SENTRY_HOST_MAC || SENTRY_HOST_TV || SENTRY_HOST_VISION
 #    define SENTRY_HAS_SIGNAL 1
 #else
 #    define SENTRY_HAS_SIGNAL 0
 #endif
 
-#if SENTRY_HOST_MAC || SENTRY_HOST_IOS
+#if SENTRY_HOST_MAC || SENTRY_HOST_IOS || SENTRY_HOST_VISION
 #    define SENTRY_HAS_SIGNAL_STACK 1
 #else
 #    define SENTRY_HAS_SIGNAL_STACK 0
 #endif
 
-#if SENTRY_HOST_MAC || SENTRY_HOST_IOS || SENTRY_HOST_TV
+#if SENTRY_HOST_MAC || SENTRY_HOST_IOS || SENTRY_HOST_TV || SENTRY_HOST_VISION
 #    define SENTRY_HAS_THREADS_API 1
 #else
 #    define SENTRY_HAS_THREADS_API 0

```

Sorry, and thanks!
