### ISSUE TITLE
Replay: Continuous slow frames when replay is enabled

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4235]
### Description

Steps to reproduce:

1. Run the iOS-Swift sample app on an actual iPhone.
2. Navigate to Extra

The slow frame count at the bottom goes continuously up. When you disable SR the problem disappears.

![Image](https://github.com/user-attachments/assets/3d92338c-6154-4fc1-ab08-d37e30002d3d)

**Comment by brustolin** [comment]
The screenshot alone takes approximately 16ms, once every second. 
I would argue that this is part of the feature and unavoidable.

**Comment by philipphofmann** [comment]
@brustolin, the problem is that when you enable SR you get really bad frame statistics. If we can't speed it up, we can at least avoid reporting slow frames caused by SR.

**Comment by brustolin** [comment]
> we can at least avoid reporting slow frames caused by SR.

This was considered, but we would be masking "problems".

**Comment by kahest** [comment]
@brustolin as discussed pls create a docs issue to cover this and close this issue afterwards

**Comment by brustolin** [comment]
Follow up at #4283
