### ISSUE TITLE
Project is not compiling in Xcode 16 (beta 5)

### ISSUE THREAD

**Issue by Semty** [getsentry/sentry-cocoa#4247]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.32.0

### Xcode Version

16.0 (beta 5)

### Did it work on previous versions?

Works in Xcode 15

### Steps to Reproduce

1. Install the sentry sdk via CocoaPods 
2. Try to build the project w/ Xcode 16 (beta 5)

### Expected Result

The project is building 

### Actual Result

The project is **not** building with this error:

```
Missing '#include <sys/_types/_ucontext64.h>'; 'ucontext64_t' must be declared before it is used
```

![Image](https://github.com/user-attachments/assets/a1023b74-d349-42a4-99fc-0d29568160ea)

```
Declaration here is not visible
```

![Image](https://github.com/user-attachments/assets/8d21f023-83bc-4cb9-9fe3-68aecf98dd12)

**Comment by brustolin** [comment]
Solved with #4244
