### ISSUE TITLE
Emit `transaction.data` inside `contexts.trace.data`

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#4248]
- find out if we already do this
- if we don't implement it like this :)

**Comment by brustolin** [comment]
Cocoa already do this.

https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/SentrySpan.m#L365-L367

https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/SentryTransaction.m#L52-L60
