### ISSUE TITLE
User Feedback UI widget

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#4270]
### Description

Build the interface widget an end-user would tap to present the feedback capture form

**Comment by brustolin** [comment]
IMO, a UI widget is overkill. I believe a public API to open the feedback form is enough. The user can be responsible for creating the button, link, or action that opens the form, as each app has its own visual identity.

**Comment by philipphofmann** [comment]
@brustolin, I think that's the main point of this new feature. If I'm not mistaken, people on the web love it, but I'm also unsure if folks on native mobile apps would use it. @bruno-garcia or @armcknight, maybe you can elaborate on why it's worth the effort to build a UI widget.

**Comment by armcknight** [comment]
There will be a way for customers to BYOB (bring your own button) and hook it into the integration. They would be completely responsible for displaying that button, we just use the touch event to display our form.

I hadn't yet considered an option where we take a button from them, but manage displaying it. That could be another nice option, so they get their branding, but don't have to worry about the mechanics.

In any case, it's not a requirement to use the widget. It's another option, there may be people out there that feel differently than you about this. It doesn't make sense to withhold the option from them just because someone here doesn't like it. Ideally we can attach analytics to it and we can see how many people use each method in practice.

**Comment by philipphofmann** [comment]
@armcknight, yes, that makes sense. Thanks for explaining 😀.

**Comment by armcknight** [comment]
Current state of the widget:

using an all-default config (except positioning, which I used to nudge it out of the way of the tab bar):
![Image](https://github.com/user-attachments/assets/07c53108-27a1-400b-bd37-f7fb78f89dc5)

And with some [extreme] overrides:![Image](https://github.com/user-attachments/assets/489bda53-d098-49a8-8934-e5a4c672b8b5)

So there's a little more work to do to correctly size/align the megaphone with edge case-y font sizes (which will be a concern with accessibility settings).

**Comment by armcknight** [comment]
Working to get the icon and text perfectly vertically centered in the button, but it's tough because different font faces have different amounts of space inside the text bounding box, so i need to find the right combination of constraints that work generally across them all. See for instance `ChalkBoardSE-Regular`: ![Image](https://github.com/user-attachments/assets/65692fc8-580b-4d6e-92b9-0637f0106e8f)
vs `HelveticaNeue`:![Image](https://github.com/user-attachments/assets/67299339-c8b1-4fb8-8ae6-3baa438f81a9)

**Comment by armcknight** [comment]
I've got the font-lozenge centering complete, although it still results in slight variation in the top/bottom padding due to the differences in fonts' cap height and ascender values affects how text is drawn inside a UILabel:

|Font face|HelveticaNeue|ChalkboardSE-Regular|
|---|---|---|
|Demo|![Image](https://github.com/user-attachments/assets/3d7c47f9-9d40-4e34-aed5-ce7d2782a1dc)|![Image](https://github.com/user-attachments/assets/eac7cff1-f82d-44be-a0ee-9562f3f5c32a)|

And also scaling the megaphone with the size of the font:
|Font size|16|32|64|
|---|---|---|---|
|Demo|![Image](https://github.com/user-attachments/assets/1bb4526c-8388-4fd1-8fa0-c2615bdf8bf5)|![Image](https://github.com/user-attachments/assets/1400a47a-972c-4329-a6f3-01c82e03272b)|![Image](https://github.com/user-attachments/assets/a4d6b582-48cf-4b91-8050-03408e898f84)|


I got stuck for a while on the Damascus font. It has some inverted measurements that make it very difficult to generalize the approach. After looking some more, I found out that that font is actually meant to draw Arabic characters, and when it renders Latin characters is when it gets wonky. Looks fine with Arabic:
![Image](https://github.com/user-attachments/assets/5ada23c7-6ede-4918-b09b-4f6994236bb7)

![Image](https://github.com/user-attachments/assets/3ab91ab0-f200-4775-b351-b54b0bb71a85)

**Comment by philipphofmann** [comment]
> I think it's fine to avoid dealing with that edge case. If someone complains, we should probably just tell them "don't do that" but we can always try to fix it at that point.

If think it's OK to skip some edge cases in the first iteration. If people adopt the feature, use it, and complain, we can invest in fixing more edge cases.

**Comment by armcknight** [comment]
A couple other things I'll need to check:
- accessibility font sizes. i think there's another API i need to use so that our text actually scales with it.
- other interesting fonts like Damascus. I've been told Devenagari and Hebrew both have possibly inverted baselines/ascenders or other interesting vertical characteristics.
- we'll want the megaphone to flip and be on the other side for right-to-left languages like Hebrew, Arabic etc

**Comment by armcknight** [comment]
Question: do we want the vertical padding to scale with the font size, or keep it fixed? With fixed spacing, it looks weirder the smaller the font gets, because the negative space gets larger. But with scaling, the larger the font, the more negative space. Maybe we scale it below the system default, and keep it fixed above?

|Font size|8|14 (system default)|40|
|---|---|---|---|
|Fixed|![Image](https://github.com/user-attachments/assets/fd983091-6ca9-4449-b90a-8995e7937bcb)|![Image](https://github.com/user-attachments/assets/40433bc0-cc45-4b53-ae0b-a1b0c8d3cad5)|![Image](https://github.com/user-attachments/assets/d23e9bfb-df8f-40fd-bb8a-3f4280df7ca1)|
|Scaling|![Image](https://github.com/user-attachments/assets/26f2c59a-c66d-4bb6-bc9f-1f26c37db318)|![Image](https://github.com/user-attachments/assets/1378b28c-346e-4e82-b8d0-a78e08159367)|![Image](https://github.com/user-attachments/assets/1207a0d1-8c82-4ad3-92bf-20d42fb353e4)|

**Comment by armcknight** [comment]
Some right-to-left testing, to make sure the megaphone appears on the leading side, and faces the right way:
|Urdu|Hebrew|Arabic|
|---|---|---|
|![Image](https://github.com/user-attachments/assets/7391ef97-aacc-401f-a2f1-d004624c60e6)|![Image](https://github.com/user-attachments/assets/ff767879-dd26-433d-a6e7-b710f76a343f)|![Image](https://github.com/user-attachments/assets/078c3d71-b741-4498-b7d9-dc29cb47663c)|

Guess there's still an issue with fonts that have inverted ascenders that will need to be addressed, judging from the arabic example (using Damascus font)

**Comment by armcknight** [comment]
Working with dynamic type size with the stock button (and you can see the one button we have in the sample app that also supports it 😆 ): 
|settings|app|
|---|---|
|![Image](https://github.com/user-attachments/assets/bdeed775-cc47-4d9a-a953-01a95adc63e7)|![Image](https://github.com/user-attachments/assets/c2db4abd-9359-4a83-b86e-ac3ee97070d8)|

**Comment by armcknight** [comment]
We've decided to only offer this feature for iOS 13+ for now. If it becomes an issue we can always build in backwards compatibility.

**Comment by armcknight** [comment]
Think I got the vertical centering right for Damascus with arabic: 

|60pt|40pt|14pt (default)|8pt|
|---|---|---|---|
|![Image](https://github.com/user-attachments/assets/4dc2cdaa-0709-4624-bc3c-1d5308cd1783)|![Image](https://github.com/user-attachments/assets/afcbe3f9-dd5b-428d-a27e-4b8e7fd2a048)|![Image](https://github.com/user-attachments/assets/172c73d5-45d6-4638-9550-15e6fcd8a6f5)|![Image](https://github.com/user-attachments/assets/b60ddce9-a4ed-410b-ba81-a9aca26cae4a)|
