### ISSUE TITLE
Umbrella header is not including some headers

### ISSUE THREAD

**Issue by dskuza** [getsentry/sentry-cocoa#428]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes (5.2)
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.0-beta.1**

---
I have following issue:

When importing Sentry (`5.0.0-beta.1`) via Carthage, we are seeing build warnings in our CI environment due to the umbrella header not including some headers. Our CI environment is set up to treat warnings as errors, and as such, our builds are failing when using the aforementioned setup. Below is the output we are seeing:

```
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryBreadcrumbTracker.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryCrashExceptionApplication.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryCrashInstallation+Private.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryCrashInstallation.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryError.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryQueueableRequestManager.h'
    » #import "Headers/Sentry.h"
    » ^
    ⚠ <module-includes>:1:1: warning: umbrella header for module 'Sentry' does not include header 'SentryTransportFactory.h'
    » #import "Headers/Sentry.h"
    » ^
```

**Steps to reproduce:**
- Add `github "getsentry/sentry-cocoa" ~> 5.0.0-beta.1` to your `Cartfile`, update, and link as required
- Import Sentry
- Build

**Actual result:**
- Warnings appear 

**Expected result:**
- No warnings should appear

**Comment by HazAT** [comment]
Fixed in `beta.2` which is on the way right now

**Comment by dskuza** [comment]
Confirming that the fix worked for us. Thanks, @HazAT!
