### ISSUE TITLE
NSPrivacyTrackingDomains not included in Privacy Manifest but doesn't this use sentry domains for tracking data?

### ISSUE THREAD

**Issue by bryan1anderson** [getsentry/sentry-cocoa#4296]
### Platform

iOS, iPadOS

### Environment

Production, Develop, TestFlight

### Installed

Swift Package Manager

### Version

8.35.0

### Xcode Version

Xcode 15.4

### Steps to Reproduce

1. Link Sentry dynamically so that we can use the PrivacyInfo.xcprivacy manifest inside Sources/Resources
2. Does not include NSPrivacyTrackingDomains

### Expected Result

I would expect NSPrivacyTrackingDomains to be required since Sentry is calling domains that pass up data used for tracking. Am I missing something? Does Apple not count that as tracking data?

### Actual Result

NSPrivacyTrackingDomains is not included

**Comment by brustolin** [comment]
Hello @bryan1anderson, thanks for reaching out.

This is what Apple says about `NSPrivacyTrackingDomains`
>An array of strings that lists the internet domains your app or third-party SDK connects to that engage in tracking. If the user has not granted tracking permission through the App Tracking Transparency framework, network requests to these domains fail and your app receives an error.

Sentry does not do this kind of tracking.

[This](https://developer.apple.com/app-store/user-privacy-and-data-use/) is what Apple considers tracking:
> Tracking refers to the act of linking user or device data collected from your app with user or device data collected from other companies’ apps, websites, or offline properties for targeted advertising or advertising measurement purposes. Tracking also refers to sharing user or device data with data brokers.
