### ISSUE TITLE
Compiler Error with Xcode 16 Beta 6

### ISSUE THREAD

**Issue by dehlen** [getsentry/sentry-cocoa#4299]
### Platform

iOS

### Environment

Other

### Installed

CocoaPods

### Version

8.34.0

### Xcode Version

16.0 Beta 6

### Did it work on previous versions?

No issues in Xcode Version 15.4 (15F31d)

### Steps to Reproduce

1. Compile App with sentry-cocoa
2. Build Issues in Sentry target in the Pods project

### Expected Result

No compiler errors

### Actual Result

Build throws multiple errors:

![Image](https://github.com/user-attachments/assets/937b74a6-08e3-44aa-b81e-cd7c3b9eb1d7)

**Comment by brustolin** [comment]
Hello @dehlen, thanks for reaching out.
I was unable to reproduce this. 
Do you know if your project has any specific setup? 

Could you try to reproduce this in a new project?

**Comment by dehlen** [comment]
Nothing too fancy I am aware of. We have a bridging header which includes this line:
```
#import <Sentry/Sentry.h>
```

**Comment by brustolin** [comment]
@krystofwoldrich, can you give this a try on a RN sample?

**Comment by dehlen** [comment]
I just did.
1. Created a new project via `npx @react-native-community/cli init`
2. Ran yarn, bundle install, bundle exec pod install
3. Opened xcworkspace with Xcode 16 Beta 6

I am receiving the same build errors with this template project.

**Comment by dehlen** [comment]
Do you think it makes sense to forward this to the react-native-sentry repository? As it is a problem with Xcode and the error seems to be happening compiling the Sentry framework for me I thought it would be best to open this issue here. However if you think it might be related to the react-native-sentry SDK I can duplicate this issue in the other repo.

**Comment by dehlen** [comment]
I removed derived data, did another sentry update and rebuild my project and now it seems to be working 🤷‍♂️ Sorry for the time you invested in this. I could reproduce the issue. Not sure what ultimately fixed it but it seems Xcode just had some invalid caches causing it to build unsuccessfully.

**Comment by brustolin** [comment]
Thanks for the update @dehlen!!
