### ISSUE TITLE
Replay does not resume after returning from background (missing app state crumbs)

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#4302]
https://sentry-sdks.sentry.io/replays/c8171926005a4b38841400f84a697812
https://sentry-sdks.sentry.io/replays/d5b3927c103e4873b373b97d5f3b49ba

When the RN sample app is pushed to background/under lock screen the replay is paused but not resumed. 

Most of the times the app state breadcrumbs are missing (seems like a race condition).

When the app return to foreground a new replay is started.

**Comment by brustolin** [comment]
@krystofwoldrich, what is the `sessionTrackingIntervalMillis` value that you're using in the samples?

The replay is meant to start a new session after some time in the background.

**Comment by krystofwoldrich** [comment]
Thank you, I've not realized that, I'll double check.

**Comment by brustolin** [comment]
@krystofwoldrich any progress on this one?

**Comment by brustolin** [comment]
This is not an issue. It was a problem in the sample configuration where the time between sessions was very short.
