### ISSUE TITLE
Add branch name to device tests

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#4321]
### Description

We have replays and events in Sentry that are received as a result of device tests.
The user reported is `runner`, and we have the SDK version, which is always the last published SDK version.

That doesn't help us tell apart PRs that are running. We recently saw some replays that had issues with redaction. But we can't tell where they are coming from.

The suggestion is to pass the git branch name to the app bundle, and after initializing Sentry, setting it as a tag. This way we can always trace back events in Sentry with the branch/PR they were running on.

**Comment by armcknight** [comment]
Also note that I previously added automatically setting the `username` to help us filter issues by ones we generate locally during dev, and those generated on CI: https://github.com/getsentry/sentry-cocoa/pull/4117. Those with these pieces of git info should help us pinpoint things much more quickly 👍🏻

**Comment by kahest** [comment]
fixed in https://github.com/getsentry/sentry-cocoa/pull/4323
