### ISSUE TITLE
Sentry.SentrySDK.start error [SentryWatchdogTerminationScopeObserver:75] Couldn't open file handle for (null)

### ISSUE THREAD

**Issue by aFernandezEspinosa** [getsentry/sentry-cocoa#4330]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.28.0

### Xcode Version

15.4

### Did it work on previous versions?

yes 8.9.1

### Steps to Reproduce

Same code I had for 8.9.1 is not working on 8.28.0. I have the same implementation for AppleTV and that one works.

Basically just when launching the app and after 

`Sentry.SentrySDK.start { options in` 

Exits I see the following error code:
`[SentryWatchdogTerminationScopeObserver:75] Couldn't open file handle for (null)`

Then after I tried to set 

`Sentry.SentrySDK.configureScope` I get the following error:

```
[Sentry] [error] No option or release to start a session.
```

### Expected Result

SDK starts without issues.

### Actual Result

SDK Start fails with errors:

[Sentry] [error] [SentryWatchdogTerminationScopeObserver:75] Couldn't open file handle for (null)
[Sentry] [error] No option or release to start a session.

### Are you willing to submit a PR?

_Yes_

**Comment by brustolin** [comment]
Thanks @aFernandezEspinosa for reaching out. 
Can you share more of your terminal output?

We will investigate

**Comment by aFernandezEspinosa** [comment]
Hey I found out the issue, I had a dependency that was installing the SPM in a framework, looks like having the Sentry SPM added in two different locations a framework and the bundle of the app was causing the issue. 

Thanks
