### ISSUE TITLE
Build Error: Use of undeclared identifier 'SentryLog'

### ISSUE THREAD

**Issue by sof9816** [getsentry/sentry-cocoa#4339]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.36.0

### Xcode Version

16.0

### Did it work on previous versions?

Yes

### Steps to Reproduce

1. Put Sentry Pods
2. Pod Install
3. Run Project
Boom, not working

### Expected Result

1. Put Sentry Pods
2. Pod Install
3. Run Project
Boom, working

### Actual Result

![Image](https://github.com/user-attachments/assets/425e3c0e-e83f-4517-8a0e-35b567b08d32)
![Image](https://github.com/user-attachments/assets/a4cdddf1-7224-499e-86ae-92368e6176f7)
![Image](https://github.com/user-attachments/assets/3a988960-f7ae-4318-bbb1-0d151648960a)

### Are you willing to submit a PR?

No,

**Comment by brustolin** [comment]
Hello @sof9816, thanks for reaching out.
I couldn't reproduce this issue.

Does this also happen to you when you start a new project and add Sentry? 
If so, can you send us the test project?

**Comment by brustolin** [comment]
Thank you very much for your response, I believe the problem is because we added all the targets.

If I got it right you're using SPM for method number 1.
Sentry and Sentry-Dynamic cannot be used together. 
They are the same SDK with different linking.

Can you try adding just one of this two.

**Comment by leandrofavarin** [comment]
That works surely. However, that's not what's blocking me from using Xcode 16, as I mentioned merely as an example. My main issue is the example #2, with Kotlin Multiplatform. I am not sure if that would mean two different fixes -- if so, I'm happy to create a new issue on its repo.

**Comment by brustolin** [comment]
> I'm happy to create a new issue on its repo.

No need to, we can keep track of it in here.

@buenaflor Had you tried Xcode 16 already? Can you help us with this issue?

**Comment by buenaflor** [comment]
I haven't tried xcode 16 yet, I'll have a look

**Comment by buenaflor** [comment]
I'll try to get to this issue asap, I'm out for droidcon new york and the hotel internet is painfully slow for updating my mac and xcode..

**Comment by kahest** [comment]
This seems related: https://github.com/getsentry/sentry-react-native/issues/4095#issuecomment-2357747042

@sof9816 @leandrofavarin can you verify if adding this fixes the issue for you?

```
    target.build_configurations.each do |config|
      if target.name != "Sentry"
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
```

**Comment by carloscuba** [comment]
@kahest, after applying the changes in the `Podfile`, still getting the `Use of undeclared identifier 'SentryLog'` error

**Comment by kahest** [comment]
@carloscuba thanks for testing and reporting back 🙏

**Comment by buenaflor** [comment]
which Kotlin version are you using for KMP?

https://youtrack.jetbrains.com/issue/KT-71287 this may be related

especially `Most usually the issues are related to Kotlin/Native vendored and user-specified cinterops`

**Comment by leandrofavarin** [comment]
>@sof9816 @leandrofavarin can you verify if adding this fixes the issue for you?
>

Sadly it didn't change the result, and it seems like I got another error from this change:

![Image](https://github.com/user-attachments/assets/c3359a49-a74c-4599-a511-443ef9a089ea)


> which Kotlin version are you using for KMP?
> 

The latest 2.0.20, haven't tried the upcoming 2.0.21-RC with the fix _yet_.

**Comment by buenaflor** [comment]
@leandrofavarin could you try `2.1.0-Beta.1`

**Comment by leandrofavarin** [comment]
> [@leandrofavarin](https://github.com/leandrofavarin) could you try `2.1.0-Beta1`

I then get these issues instead:
![Image](https://github.com/user-attachments/assets/1ae23416-abb2-42a4-b676-e9f2eb9c4f73)

**Comment by buenaflor** [comment]
For testing, in Kotlin `2.0.20` can you compile your app with only using

```kotlin
cocopoads {
  // add sentry-cocoa
}
```

without the KMP dependency `implementation("io.sentry...")`

I want to find out if it is the KMP dependency that's breaking things or the cinterop through the cocoapods plugin

**Comment by leandrofavarin** [comment]
It still fails without the KMP dependency. To try that, I basically reverted to not using KMP and split the configuration from being on `commonMain`, to only on `iosMain`.

Kotlin v2.1.0-Beta1, Sentry 8.36.0 with `extraOpts = listOf("-compiler-option", "-fmodules")`

**Comment by tanmoy27112000** [comment]
I solved the issue by adding the following code in podFile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'Sentry'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
      else
        # configuration for other targets
      end
    end
  end
end
```
this is also present in the sentry docs
https://docs.sentry.io/platforms/apple/guides/ios/troubleshooting/

**Comment by brustolin** [comment]
@tanmoy27112000 [last comment](https://github.com/getsentry/sentry-cocoa/issues/4339#issuecomment-2394528899) seems to be the solution for this issue.

We saw this happening other times and the solution was the same.

If it does not fix the problem we can reopen the issue.

**Comment by sof9816** [comment]
[This comment](https://github.com/getsentry/sentry-cocoa/issues/4339#issuecomment-2394528899) solved it, thanks.
