### ISSUE TITLE
Crash reporting inside Libraries(Frameworks)

### ISSUE THREAD

**Issue by RajvinderPayU** [getsentry/sentry-cocoa#434]
Hi,

I want to use Sentry inside my frameworks, is there any way to do that?

**Comment by bruno-garcia** [comment]
Short answer is: No.

Although could technically be possible if not using the static `SentrySDK` class, Sentry SDK is designed to be used by applications. There are multiple reasons why, but mainly it's a decision of the app to instrument it and capture errors and stack traces that could span multiple libraries.

One thing you could do in your library is expose a way to add "breadcrumbs" to Sentry.

**Comment by RajvinderPayU** [comment]
@bruno-garcia can we send data to 2 different accounts, basically, if I have a dependency of Sentry in my SDK and my merchant is also integrating Sentry then is there any way by which both of us can get crash data in our sentry accounts?

**Comment by philipphofmann** [comment]
What could work @RajvinderPayU is that your merchant is using Sentry via the static API. That's the normal recommended way. The static API also installs all integrations for crashes, automatic breadcrumbs, auto session tracking etc. This means when you use the static API you get all these nice features.

What you can do in your SDK is to create your own instance of your hub with a different DSN and always interact with the hub instead of the static API. For more info on static API vs hub please checkout https://develop.sentry.dev/sdk/unified-api. The downside is that you don't receive hard crashes, automatic breadcrumbs, sessions, tags, device information, etc. This is not the main use case we designed the SDK for, but it might work for you.
```swift
// In the merchant application
SentrySDK.start { options in
    options.dsn = "Mearchant DSN"
}
SentrySDK.capture(message: "merchant message")
        
// In your SDK
let options = Options()
options.dsn = "SDK_DSN"

let hub = SentryHub(client: Client(options: options), andScope: nil)
hub.capture(message: "hub message")
```

**Comment by MageSantana** [comment]
Hi, 
I'm developing a custom swift framework and I'm using the Sentry version 6.0.9. I use Sentry as @philipphofmann proposed:

`// In your SDK
let options = Options()
options.dsn = "SDK_DSN"

let hub = SentryHub(client: Client(options: options), andScope: nil)
hub.capture(message: "hub message")`

but OS specific data are not included in events or messages send.

**Comment by philipphofmann** [comment]
The `SentryCrashIntegration` sets the OS-specific data. So what you could do is to init the other Hub with the scope of the Hub of the SDK. Something like this should work: 
```swift
// In the merchant application
SentrySDK.start { options in
    options.dsn = "Mearchant DSN"
}
SentrySDK.capture(message: "merchant message")
        
// In your SDK
let options = Options()
options.dsn = "SDK_DSN"

let hub = SentryHub(client: Client(options: options), andScope: SentrySDK.currentHub().getScope())
hub.capture(message: "hub message")
```
Still, you won't receive hard crashes, automatic breadcrumbs, and sessions, but you get the OS-specific data.

**Comment by philipphofmann** [comment]
I think the initial question has been answered. I'm going to close this now. Please open it again if you need more input.

**Comment by tobiasjordan** [comment]
@philipphofmann Unfortunately, since `-[SentrySDK currentHub]` is private I cannot use it in my project. Any plans for exposing this method? I'm using version 7.0.2.

**Comment by philipphofmann** [comment]
Hey @tobiasjordan, do you only use `[SentrySDK currentHub]` to get the scope with the device data? If so, maybe we should provide another way to initialize a scope with device data without having to expose `[SentrySDK currentHub]`.

**Comment by tobiasjordan** [comment]
Thanks for the swift response, @philipphofmann! Yes, exactly. I was trying to give your snippet a shot and there would be no other use case for having to call `+[SentrySDK currentHub]` for me so any alternative solution fulfilling this requirement would be nice to have publicly available.

**Comment by philipphofmann** [comment]
@marandaneto how do we put the device data into the event on Java? Maybe we can change it to a similar approach.

**Comment by marandaneto** [comment]
@philipphofmann via EventProcessors so every Sentry.capture(event) will enrich the event with the device context

**Comment by philipphofmann** [comment]
Thanks, @marandaneto. I think we should change this. I created an issue for this https://github.com/getsentry/sentry-cocoa/issues/1104. Can't give you an ETA though @tobiasjordan.

**Comment by tobiasjordan** [comment]
No problem, @philipphofmann and thanks for creating an issue. I'm already glad someone's going to look into this.
