### ISSUE TITLE
IOS Build failed in Xcode 16

### ISSUE THREAD

**Issue by jrodriguer** [getsentry/sentry-cocoa#4347]
### Description

I just updated my Mac to latest version, 15.0. And also updated the recommended Xcode setting for project and Pods dependencies but i started to get this build error in Xcode.

![Image](https://github.com/user-attachments/assets/e1058084-104d-4e0c-936e-e5f9b2211f71)

### My setup
- Sentry (8.21.0):
    - Sentry/Core (= 8.21.0)
    - SentryPrivate (= 8.21.0)
  - Sentry/Core (8.21.0):
    - SentryPrivate (= 8.21.0)
  - SentryPrivate (8.21.0)
  - SwiftKeychainWrapper (4.0.1)
  - SwiftUI-SimpleToast (0.6.2)
  - SwiftyBeaver (2.0.0)
- Xcode version 16.0 (16A242d)

**Comment by kahest** [comment]
@jrodriguer please see my reply here https://github.com/getsentry/sentry-react-native/issues/4095#issuecomment-2358560444 and let us know if the problem persists. Also if you're using `sentry-cocoa` directly, please make sure you use `8.35.0` or newer when building with Xcode 16.

**Comment by philipphofmann** [comment]
We fixed the issue with https://github.com/getsentry/sentry-cocoa/issues/4050 shipped in 8.29.0. As you're on version 8.21.0, updating the SDK should fix the problem. Please reopen if the issue persists.
