### ISSUE TITLE
EXC_BAD_MEMORY for TestCurrentDateProvider.systemDate() on Xcode 16

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4351]
### Description

Unit tests using `TestCurrentDateProvider`, such as SentryFramesTrackerTests or `SentryANRTrackerV2Tests`, fail with `EXC_BAD_MEMORY` when accessing `TestCurrentDateProvider.systemDate()`.
![Image](https://github.com/user-attachments/assets/ed3cef38-e89b-47f3-9623-ae019b9b0c09)

This is a known issue and some people report that a similar looking crash was fixed in Xcode Beta versions, see:
* https://github.com/aws-amplify/amplify-swift/issues/3806
* https://github.com/RevenueCat/purchases-ios/issues/3949

On this repository, the issue persists: https://github.com/RevenueCat/purchases-ios/issues/4177.

On Xcode 15.4, the unit tests run without failure.

**Comment by kahest** [comment]
IIUC this is blocked by fix in Xcode and we wanna keep this here for everybody's information

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/sentry-cocoa/pull/4433.
