### ISSUE TITLE
Fix beta release bundle info

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#4359]
### Description

It's not possible to release an app that links to a Beta release.

Here is the reason why:
![Image](https://github.com/user-attachments/assets/3271920c-0ee1-49f6-ba58-8b7f78266261)

**Comment by philipphofmann** [comment]
How did you fix the issue so you could release an app version?

**Comment by brustolin** [comment]
> How did you fix the issue so you could release an app version?

By using the static framework directly without embedding it.
