### ISSUE TITLE
Error is associated with incorrect transaction after crash

### ISSUE THREAD

**Issue by aellett** [getsentry/sentry-cocoa#4375]
### Platform

iOS

### Environment

Production

### Installed

Manually

### Version

8.36.0

### Xcode Version

15.2

### Steps to Reproduce

1. Start a scoped transaction (not sure if this step is necessary, but I had one running in my project).
2. Cause a fatal crash (I used index out of bounds).
3. After the app crashes, launch the app again.
4. Start a new scoped transaction in AppDelegate.init() (as soon as possible after Sentry is configured). In my screenshots, this transaction is called `LAUNCH_[obscured]`
5. Find the fatal crash in the Sentry console.

### Expected Result

I would expect to see either

The error has a `transaction` property that matches the name of the original scoped transaction (before the crash)

or

The error has a `transaction` property that is nil, or doesn't have a `transaction` property at all.

### Actual Result

The error is labeled with `transaction` of `LAUNCH_[obscured]` which was the transaction that I started after the second app launch.

I think that I would rather not see a transaction at all, if the alternative is to see the next transaction _after_ the crash. This is further misleading (for me) because it shows up in the title at the top of the screen on the view of the error (screenshot attached). If I ever wanted to count how many errors had some particular transaction value, I think this would throw off my calculations.

Note: I imagine this is sort of adjacent to https://github.com/getsentry/sentry-cocoa/issues/2306 so if it's more convenient to group these together, feel free, but this felt like a separate issue. Also felt like it might be able to be resolved even if 2306 can't be resolved.

**Comment by aellett** [comment]
Oops, forgot to attache the screenshots I mentioned.

![Image](https://github.com/user-attachments/assets/2f6732ea-fab1-4161-bf24-c96c8ed585c5)
![Image](https://github.com/user-attachments/assets/4146b9fb-164e-4cce-9783-76094c960803)

**Comment by philipphofmann** [comment]
Thanks for reporting this, @aellett. What exactly do you mean by 
> Start a scoped transaction (not sure if this step is necessary, but I had one running in my project).

I tried to reproduce the issue but I couldn't. I start a manual transaction directly after `SentrySDK.start` like this:
```
let t = SentrySDK.startTransaction(name: "after-crash", operation: "crash", bindToScope: true)
let shild = t.startChild(operation: "hello")

DispatchQueue.global().asyncAfter(deadline: .now() + 10.0) {
    shild.finish()
    t.finish()
}
```

Potential culprits could be that we have to ignore crash events here
https://github.com/getsentry/sentry-cocoa/blob/33c23d36ecbff99baacbc068b5a61311b76a8977/Sources/Sentry/SentryScope.m#L567-L586

and here

https://github.com/getsentry/sentry-cocoa/blob/33c23d36ecbff99baacbc068b5a61311b76a8977/Sources/Sentry/SentryClient.m#L383-L411

**Comment by aellett** [comment]
> Thanks for reporting this, [@aellett](https://github.com/aellett). What exactly do you mean by
> 
> > Start a scoped transaction (not sure if this step is necessary, but I had one running in my project).
> 
> I tried to reproduce the issue but I couldn't. I start a manual transaction directly after `SentrySDK.start` like this:
> 

I just meant that I wouldn't think that having a transaction running when the crash happens matters.

If I cause an error, but the `transaction` field of the error refers to a transaction (`LAUNCH_` in my case) that hasn't started yet, that seems wrong to me.

It looks to me like you're correct that if those places (maybe just the first one?) ignored crash events, it would resolve this.

**Comment by philipphofmann** [comment]
@aellett, we fixed the issue. We plan to release this fix early next week.
