### ISSUE TITLE
Failed to Build in XCode 16 using Sentry 8.17.1

### ISSUE THREAD

**Issue by jimmy-sqe** [getsentry/sentry-cocoa#4376]
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.17.1

### Xcode Version

16.0

### Steps to Reproduce

Hallo, in my project, I have to use Sentry 8.17.1, cannot be upgraded to newer, but I have to run on XCode 16 as well. Is there a way to support XCode 16 to be able to build the project without upgrading Sentry?  by using script or some other workaround, Thank you.

### Expected Result

Build successful using Sentry 8.17.1 and XCode 16

### Actual Result

cannot build project

### Are you willing to submit a PR?

Yes if may

**Comment by philipphofmann** [comment]
We fixed some errors in the last versions of Xcode 16. What error do you get exactly? Maybe we can find a workaround for 8.17.1.

**Comment by brustolin** [comment]
Most likely this is related to some missing headers. 

If that's the case you can download the 8.17.1 code source, apply the changes in [this PR](https://github.com/getsentry/sentry-cocoa/pull/4051/files) and the fix to `Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c` in [this PR](https://github.com/getsentry/sentry-cocoa/pull/4242)
