### ISSUE TITLE
MacOS with xcode 16: No type or protocol named 'MXMetricManagerSubscriber

### ISSUE THREAD

**Issue by MattJustMatt** [getsentry/sentry-cocoa#4388]
### Platform

macOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.36

### Xcode Version

16.0

### Did it work on previous versions?

Yes on Xcode 15

### Steps to Reproduce

When I build for Mac I was getting `Use of undeclared identifier 'kSentryLevelWarning'` errors, so I tried a fix we used for our iOS build and imported both Sentry and Sentry-Swift
```
#import <Sentry/Sentry.h>
#import <Sentry/Sentry-Swift.h>
```

But this led to 
```
/Headers/Sentry-Swift.h:535:40: No type or protocol named 'MXMetricManagerSubscriber'
```

### Expected Result

.

### Actual Result

.

**Comment by brustolin** [comment]
Hello @MattJustMatt, thanks for reaching out.

Can you share your Sentry.start code?
I tried to reproduce what you did but I got no error.

**Comment by MattJustMatt** [comment]
You led me down the right path! 

Even though we have metrics kit disabled in our start options, we needed to import metrics kit

`#import <MetricKit/MetricKit.h>`
fixed the issue!

**Comment by brustolin** [comment]
Im glad you found a solution.

I would like to investigate how to trigger this problem, any information that help me reproduce it.
