### ISSUE TITLE
Unable to fetch the Swift package

### ISSUE THREAD

**Issue by bourquep** [getsentry/sentry-cocoa#4403]
### Platform

iOS

### Environment

Other

### Installed

Swift Package Manager

### Version

8.36.0

### Xcode Version

16.0

### Did it work on previous versions?

don't know

### Steps to Reproduce

My Xcode project which references the Sentry Swift package started failing on CI, with the following error:

```
Fetching from https://github.com/getsentry/sentry-cocoa.git (cached)
Checking out 8.36.0 of package ‘sentry-cocoa’
Couldn’t check out revision ‘5575af93efb776414f243e93d6af9f6258dc539a’:
    fatal: bad object refs/remotes/origin/armcknight/feat/launch-profile-data-in-app-start-spans
fatalError
2024-10-03 21:07:19.234 xcodebuild[82426:2824149] Writing error result bundle to /var/folders/js/qx1srxgx0m5bn2ws_jxl0nw80000gn/T/ResultBundle_2024-03-10_21-07-0019.xcresult
xcodebuild: error: Could not resolve package dependencies:
  Couldn’t check out revision ‘5575af93efb776414f243e93d6af9f6258dc539a’:
    fatal: bad object refs/remotes/origin/armcknight/feat/launch-profile-data-in-app-start-spans
```

I have tried deleting the SPM caches on the CI machine, but the error still occurs.

If I checkout the `https://github.com/getsentry/sentry-cocoa.git` repository manually and checkout the `5575af93efb776414f243e93d6af9f6258dc539a` ref, I don't get any git error.

### Expected Result

The package should install without any errors.

### Actual Result

```
Fetching from https://github.com/getsentry/sentry-cocoa.git (cached)
Checking out 8.36.0 of package ‘sentry-cocoa’
Couldn’t check out revision ‘5575af93efb776414f243e93d6af9f6258dc539a’:
    fatal: bad object refs/remotes/origin/armcknight/feat/launch-profile-data-in-app-start-spans
fatalError
2024-10-03 21:07:19.234 xcodebuild[82426:2824149] Writing error result bundle to /var/folders/js/qx1srxgx0m5bn2ws_jxl0nw80000gn/T/ResultBundle_2024-03-10_21-07-0019.xcresult
xcodebuild: error: Could not resolve package dependencies:
  Couldn’t check out revision ‘5575af93efb776414f243e93d6af9f6258dc539a’:
    fatal: bad object refs/remotes/origin/armcknight/feat/launch-profile-data-in-app-start-spans
```

**Comment by brustolin** [comment]
Thanks for reaching out @bourquep.

I can't reproduce this problem.
I had very bad cache problem with Xcode 16 before, I had to clean all the cache and also the derivativeData folder after closing Xcode.

If this does not works, could you share a repro with us?

**Comment by bourquep** [comment]
> I had very bad cache problem with Xcode 16 before, I had to clean all the cache and also the derivativeData folder after closing Xcode.

That did the trick! I should have thought to try this before bothering you 😇.

Thanks for the quick and useful reply!
