### ISSUE TITLE
Xcode16.0 Compilation Fails

### ISSUE THREAD

**Issue by RayFor24** [getsentry/sentry-cocoa#4430]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.37.0

### Xcode Version

16.0

### Steps to Reproduce

Xcode 16 Compilation Fails

SENTRY_LOG_WARN(@"Current profiler is not running.");
Use of undeclared identifier 'SentryLog'

### Expected Result

Xcode 16 Compilation Fails

SENTRY_LOG_WARN(@"Current profiler is not running.");
Use of undeclared identifier 'SentryLog'

### Actual Result

Xcode 16 Compilation Fails

SENTRY_LOG_WARN(@"Current profiler is not running.");
Use of undeclared identifier 'SentryLog'

**Comment by RayFor24** [comment]
[https://imgur.com/a/H5WbBR8](url)

**Comment by brustolin** [comment]
Hello @RayFor24, thanks for reaching out.

Any change in your `podfile`, you're disabling `APPLICATION_EXTENSION_API_ONLY`?
Is it possible to share your `podfile` with us?

**Comment by RayFor24** [comment]
> 你好[@RayFor24](https://github.com/RayFor24)，感谢您的联系。
> 
> 您的 中有任何更改吗`podfile`？您要禁用它`APPLICATION_EXTENSION_API_ONLY`吗？ 可以`podfile`与我们分享您的更改吗？



> 你好[@RayFor24](https://github.com/RayFor24)，感谢您的联系。
> 
> 您的 中有任何更改吗`podfile`？您要禁用它`APPLICATION_EXTENSION_API_ONLY`吗？ 可以`podfile`与我们分享您的更改吗？

Yes, we set APPLICATION-EXETENSION_SPI-ONLY  NO

**Comment by brustolin** [comment]
> Yes, we set APPLICATION-EXETENSION_SPI-ONLY NO

I see. You can't disable it for Sentry.

If you’re interested in any changes related to this, you can check out the following issue: https://github.com/getsentry/sentry-cocoa/issues/4426. 

Let me know if you have any questions!
