### ISSUE TITLE
set user not work

### ISSUE THREAD

**Issue by MagicalAna** [getsentry/sentry-cocoa#4449]
### Platform

iOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.38.0-beta.1

### Xcode Version

16.0

### Did it work on previous versions?

no

### Steps to Reproduce

configure Sentry in application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool

        let user = User()
        user.userId = Purchases.shared.appUserID
        user.email = "test@test.com"
        SentrySDK.setUser(user)
        
        SentrySDK.start { options in
            options.dsn = "xxx"

            options.tracesSampleRate = 1.0
            options.profilesSampleRate = 1.0
        }

Purchases.shared.appUserID is an id from another framework and it works 

### Expected Result

I can see user's custom id in the website (or I can get user's Sentry id from App)

### Actual Result

custom user Id not work

![Image](https://github.com/user-attachments/assets/7bf177e2-1b46-4784-8838-6bd0a98f289e)

**Comment by brustolin** [comment]
Hello @MagicalAna Thanks for reaching out.
You need to set the user after initializing the SDK.
Can you try that and let me know whether it worked?

**Comment by philipphofmann** [comment]
Please reopen the issue if it doesn't work @MagicalAna.
