### ISSUE TITLE
enableAutoSessionTracking does not honor own release

### ISSUE THREAD

**Issue by xmanu** [getsentry/sentry-cocoa#447]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.0-beta.3**

---
I have following issue:
I have enabled the new Release session tracking feature by adding `"enableAutoSessionTracking": true`.
The automatic session tracking works fine, but it always reports with the default release Sentry.io.

I set my own release code like this:
```
SentrySDK.configureScope { scope in
	scope.setRelease(baseAppVersion)
}
```
This is never called, when the automatic tracking is sending data.
I also tried to set the release in the constructor like this:
```
_ = SentrySDK(options:
	["dsn": apiKey,
	 "debug": true,
	 "release": baseAppVersion,
	 "enableAutoSessionTracking": true])
```
This also seems to not produce the desired result.

**Steps to reproduce:**
- use enableAutoSessionTracking in the options during initialization.
- set own release
- publish to testflight

**Actual result:**
- the session is reported as BundleID@Version+Number

**Expected result:**
- the session should be reported as the version set for the scope (or set in the options)

**Comment by bruno-garcia** [comment]
We're addressing this issue through: #462 
This means your second snippet should work. The first snippet won't compile though since Scope  doesn't expose Release anymore.
