### ISSUE TITLE
Got different crash thread number from Sentry and System crash report

### ISSUE THREAD

**Issue by ShiBody** [getsentry/sentry-cocoa#4503]
### Platform

macOS

### Environment

Production

### Installed

Manually

### Version

8.0.0

### Xcode Version

15.4

### Steps to Reproduce

1. A user crashed and sent crash to sentry
2. At the same time, he got a system crash report in console
3. Could see different crash thread

### Expected Result

Should have same crash thread

### Actual Result

Crashed at thread 24 in ips file:
![Image](https://github.com/user-attachments/assets/873e0f7e-1a1d-4337-8bff-aaf31cb3bd1f)
![Image](https://github.com/user-attachments/assets/67f8fe3c-5b95-4dad-bee3-9737f1c50c17)
Crashed at thread 40 in Sentry:
![Image](https://github.com/user-attachments/assets/7f5003de-483d-448e-99c6-386f7513036b)

I have checked our app log, this user only crashed once. We are sure they are same crash

**Comment by philipphofmann** [comment]
@ShiBody, when looking at the stacktrace, it looks the same, or is there a difference? Why is the correct thread number important to you?

It can be that our logic for writing all the threads doesn't correctly handle the thread numbers: https://github.com/getsentry/sentry-cocoa/blob/522f8da1aef040a58ae580345895e2ec1c215d36/Sources/SentryCrash/Recording/SentryCrashReport.c#L1120-L1147

**Comment by ShiBody** [comment]
@philipphofmann  Thanks, got that.

**Comment by philipphofmann** [comment]
@ShiBody, thanks for the update. Is this issue fixed for you now or not?

**Comment by ShiBody** [comment]
> [@ShiBody](https://github.com/ShiBody), thanks for the update. Is this issue fixed for you now or not?

@philipphofmann Thanks for reply, it resolved.
