### ISSUE TITLE
Crash caused by inclusion of `beforeSend` option.

### ISSUE THREAD

**Issue by UniekLee** [getsentry/sentry-cocoa#4509]
### Platform

iOS

### Environment

TestFlight, Production, Develop

### Installed

Swift Package Manager

### Version

8.36.0

### Xcode Version

16.1

### Did it work on previous versions?

No

### Steps to Reproduce

1. Include a `beforeSend` block in SentrySDK initialisation.
2. Invoke a crash in the application.
3. Attempt to relaunch the application

It's worth calling out that this crash started appearing with Xcode 16.0 & Xcode 16.1 builds. Builds with Xcode 15 haven't shown this issue.
I've also tried updating Sentry to v8.39.0, but this doesn't resolve the issue.

Sample project for reproduction attached. 
This crash occurs intermittently in the supplied sample project, but ever time in our main project. 

[BeforeSendCrash.zip](https://github.com/user-attachments/files/17635843/BeforeSendCrash.zip)

### Expected Result

Application relaunches as usual and report is sent to Sentry.

### Actual Result

Application crashes on first attempted relaunch.
Application launches successfully on second attempt, and sends two crash reports to Sentry - the original crash and the SentrySDK crash.

![Image](https://github.com/user-attachments/assets/618e0bfd-6c0a-47f0-96ce-fdb5ac486c16)
![Image](https://github.com/user-attachments/assets/a561cc13-f4ac-4cb8-aa53-3e0910bbc9c2)

https://github.com/user-attachments/assets/465e3f5f-065b-4566-b626-cceda34cfbd4

### Are you willing to submit a PR?

No

**Comment by kahest** [comment]
@UniekLee I did a few runs of your sample app but didn't get the crash - you mention it occurs "intermittently", do you have a rough number?

**Comment by brustolin** [comment]
Hello @UniekLee, does your final project also use Swift 6 like the sample you sent?

**Comment by brustolin** [comment]
I could reliably reproduce this error only by capturing a message in a different thread. 
This only happens in Swift 6 mode because of all the extra concurrency checks.

The solution is simple:
```swift
options.beforeSend = { @Sendable event in //This closure needs to be marked as @Sensable
    // Process the event
    return event
}
```

Or you can use an external function
```Swift
    nonisolated func beforeSend(_ event: Event) -> Event? {
        return event
    }
//...

    options.beforeSend = self.beforeSend
```


I believe the compiler in Swift 6 mode should throw an error because this closure is not isolated. I will open an issue in the Swift repo to try to get more answers. In the meantime, I don’t think there’s anything we can do on the SDK side.

**Comment by UniekLee** [comment]
Hey folks 👋 Thanks for jumping onto this so quickly. I'll answer the questions, although I'm not sure the info is still useful.

> [@UniekLee](https://github.com/UniekLee) I did a few runs of your sample app but didn't get the crash - you mention it occurs "intermittently", do you have a rough number?

I'd say that it was periodic - at time it would crash 0% of the time, and sometimes it would cash >60% of the time. I couldn't figure out what made it more "crash prone". 


> Hello [@UniekLee](https://github.com/UniekLee), does your final project also use Swift 6 like the sample you sent?

Uhm, I want to say no because we've set the project to Swift 5. But we've seen a lot of Swift 6-style behaviour, so not quite sure whether something strange is happening.

> The solution is simple

Marking that closure as `@Sendable` seems to work - thanks so much for the fix 🙏

**Comment by brustolin** [comment]
> hm, I want to say no because we've set the project to Swift 5. But we've seen a lot of Swift 6-style behaviour, so not quite sure whether something strange is happening.

Interesting, because I could not make the error happen in Swift 5

> Marking that closure as @Sendable seems to work

That’s great! Please let us know if it occurs again.

**Comment by brustolin** [comment]
We need to update the documents.
