### ISSUE TITLE
Sentry package added via SPM is not resolving

### ISSUE THREAD

**Issue by fpena** [getsentry/sentry-cocoa#4537]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.40.1

### Xcode Version

16.1

### Did it work on previous versions?

7.12.0

### Steps to Reproduce

1. In Xcode and the project, go to "Package Dependencies"
2. Tap on "+" icon to add a new package.
3. Search for "sentry" in the search box and select the sentry package: `sentry-cocoa`
4. Tap "Add package", making sure dependency rule is "Up to Next Major Version" and version is 8.40.1

![Image](https://github.com/user-attachments/assets/01b85e37-8939-428c-98f9-13a40d1e3172)

### Expected Result

Add package without issues. 

### Actual Result

I get modal window with an error message: "sentry-cocoa.git could not be resolved"

![Image](https://github.com/user-attachments/assets/eeb1a751-5c37-4cca-9f09-06ea37fd9df6)

**Comment by brustolin** [comment]
Hello @fpena and thanks for reaching out.
I was not able to reproduce the problem.

I believe this was some temporary problem of GitHub servers.
Can you try again?

**Comment by fpena** [comment]
> Hello [@fpena](https://github.com/fpena) and thanks for reaching out. I was not able to reproduce the problem.
> 
> I believe this was some temporary problem of GitHub servers. Can you try again?

Hello! Thanks for the reply. I tried again and I still get the same error. For the record, this has been happening for a span of several days.

**Comment by danscan** [comment]
This is occurring for me as well. Same exact issue as OP's. Deleting Derived Data had no effect.

XCode: 16.2

<img width="1095" alt="Image" src="https://github.com/user-attachments/assets/264e24c3-4adc-4096-a5ac-da94d0a3be03" />

**Comment by danscan** [comment]
Running this, deleting Derived Data, and then restarting Xcode fixed it for me:
```
defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
```

Sentry is the only repo that has had this issue with SPM/Xcode in my experience.

**Comment by nyeu** [comment]
I'm having the same issue here and I am not able to install it via SPM

**Comment by philprime** [comment]
We did see this issue before, but most likely it's an issue in Xcode or GitHub, not the Sentry SDK. Please add the log displayed in the UI as a full text in this issue so we can take a closer look.
