### ISSUE TITLE
Conform `SentryId` to `Sendable`

### ISSUE THREAD

**Issue by ifabijanovic** [getsentry/sentry-cocoa#4545]
### Problem Statement

Hello!

I kindly request adding `Sendable` conformance to `SentryId`, seeing as it was refactored to Swift in #3708. Ideally this type would be a `struct` and this would be trivial, but as most of the SDK is still written in ObjC I understand why it is not.

Adding `Sendable` conformance should be really straightforward:
- make it a `final` class
- make the global `empty` a constant

Concrete use case I have for this is passing the `eventId` out of `onCrashedLastRun` in a Swift 6 app using strict concurrency. Right now I am falling back to passing the `sentryIdString` instead and then reconstructing the `SentryId` from that string once user feedback was collected.

Thank you!

### Are you willing to submit a PR?

Yes

**Comment by ifabijanovic** [comment]
Hey @brustolin , thanks for responding so quickly!

Would you like me to submit a PR or are you planning on tackling this internally?

**Comment by brustolin** [comment]
@ifabijanovic dont worry, I already [did](https://github.com/getsentry/sentry-cocoa/pull/4553).

Also, I created another [PR](https://github.com/getsentry/sentry-cocoa/pull/4554) to begin preparing to Swift 6 and its strict concurrency check. Feel free to give your inputs to help us move in this direction.
