### ISSUE TITLE
Crash in SentryViewPhotographer

### ISSUE THREAD

**Issue by MarekSlaninka** [getsentry/sentry-cocoa#4547]
### Platform

iOS, iPadOS

### Environment

TestFlight

### Installed

Swift Package Manager

### Version

8.41.0

### Xcode Version

16.1

### Did it work on previous versions?

Yes, 8.36.0

### Steps to Reproduce

Just using the app it seems

### Expected Result

Dont crash

### Actual Result

![Image](https://github.com/user-attachments/assets/4ee2a927-e08f-47df-b09a-21be23d7eb6e)

**Comment by MarekSlaninka** [comment]
Im sorry, I updated the picture

**Comment by brustolin** [comment]
Thanks for the quick reply, we will investigate this.

**Comment by philipphofmann** [comment]
This is duplicate of https://github.com/getsentry/sentry-cocoa/issues/4558.
