### ISSUE TITLE
Crash with Session Replay SentryViewPhotographer

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#4558]
### Platform

iOS, iPadOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.40.1

### Xcode Version

Not sure

### Steps to Reproduce

- We are using version 8.40.1 with SwiftUI
- Crash happens on all iphone versions and affects 2% of the sessions and 0.5% of the users. It also happens on iPad.
- It happens iOS version >= 17 & iPadOS version >= 17
- Crash count decreased to half after 3 days so I am guessing it is happening for the same group of users again and again so they stop using the app.

![Image](https://github.com/user-attachments/assets/f3122f26-7e0d-4659-ab68-dd6275c703c6)

### Expected Result

Doesn't crash

### Actual Result

Crashing 2% of users

**Comment by bruno-garcia** [comment]
Could this be related to: https://support.apple.com/en-us/105120 ?

**Comment by philipphofmann** [comment]
We also see this in our [internal SDK crash detection](https://sentry.sentry.io/issues/5919675839/?project=4505469596663808&query=is%3Aunresolved%20sentryviewphoto&referrer=issue-stream&sort=user&statsPeriod=14d&stream_index=0).

**Comment by kahest** [comment]
possibly related/duplicate: https://github.com/getsentry/sentry-cocoa/issues/4547

**Comment by philipphofmann** [comment]
> Crash happens on all iphone versions and affects 2% of the sessions and 0.5% of the users. It also happens on iPad.

@bruno-garcia, do you know how the customer came up with these numbers? If this is the case, we should see more crashes in our internal SDK crash detection. It could be that they have errors in the Cocoa SDK disabled or use a low sample rate for errors, but that's unlikely.

**Comment by Vladissqq** [comment]
> > Crash happens on all iphone versions and affects 2% of the sessions and 0.5% of the users. It also happens on iPad.
> 
> [@bruno-garcia](https://github.com/bruno-garcia), do you know how the customer came up with these numbers? If this is the case, we should see more crashes in our internal SDK crash detection. It could be that they have errors in the Cocoa SDK disabled or use a low sample rate for errors, but that's unlikely.

Hi! We have the same issue in our app. It might be worth considering the problem in connection with the @react-navigation libraries. In our app, crashes usually occur when navigating between screens that are in different navigation stacks, and when there’s a screen transition animation. I was able to reproduce the issue on an iPhone SE 3rd gen (iOS 16.2) emulator and on a real iPhone 12 Pro (iOS 16.1.1).

**Comment by brustolin** [comment]
Thanks for the extra information @Vladissqq 
We will investigate that too.

**Comment by kahest** [comment]
Internal note: we can use [internal tools](https://sentry.sentry.io/discover/results/?id=30602&project=4506155486085120&project=4505469596663808&statsPeriod=90d) to track this crash

**Comment by siliconivan** [comment]
Hi @brustolin we're currently running into this issue with the React-Native SDK, do we know by any chance when we might be able to see this included in a non-beta build of the react-native SDK? The beta version seems to be unstable. Thanks!

**Comment by brustolin** [comment]
Hello @siliconivan we found a solution for this problem and we're planning to do a new release ASAP.
