### ISSUE TITLE
Add "Is Foreground" to app tags

### ISSUE THREAD

**Issue by aellett** [getsentry/sentry-cocoa#4559]
### Problem Statement

I was comparing some events between our iOS and Android native apps recently, and I saw that our Android transactions had an automatic tag for `App.In Foreground`, but the iOS transactions didn't seem to have that. I looked around a little bit, but couldn't find the same tag; wondering if that could be surfaced in the cocoa sdk.

Looks like Android is using 7.15.0 of sentry.java.android and iOS is currently at 8.36.0 of sentry-cocoa.

**Comment by brustolin** [comment]
Hello @aellett, thanks for the suggestion.
We will discuss this in our internal meeting.

**Comment by philipphofmann** [comment]
We have `is_foreground` in the app context, which we already attach to an event. We only need to ensure that it is attached for transactions as well. 

https://github.com/getsentry/sentry-cocoa/blob/d70a7e8dffb0134d06d9c68f686951478b0e539a/Sources/Sentry/SentryClient.m#L675-L703

**Comment by philipphofmann** [comment]
PR is open: https://github.com/getsentry/sentry-cocoa/pull/4561

**Comment by philipphofmann** [comment]
@aellett, FYI we are aware you'd like to also have this field for crashes, so we created an issue: https://github.com/getsentry/sentry-cocoa/issues/4563.
