### ISSUE TITLE
Include stack trace when capturing events/errors/messages

### ISSUE THREAD

**Issue by ivasic** [getsentry/sentry-cocoa#456]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.0-beta5**

---

The legacy SDK had an API to include stack trace along with custom events (https://docs.sentry.io/clients/cocoa/advanced/#adding-stacktrace-to-message), however this seems to be missing in the new SDK.

Is it possible to add this functionality back? This is especially important when logging custom errors/exceptions, the `Error`/`NSError` doesn't provide much information on its own and would be great to know where exactly the error is coming from (by examining the stack trace). Breadcrumbs help somewhat but not as much as a stack trace would.

Thanks for your hard work!

**Comment by HazAT** [comment]
Thanks for the report, it's on our radar and we are working on it
https://github.com/getsentry/sentry-cocoa/pull/401

**Comment by ivasic** [comment]
Ah, missed that one somehow. Thanks a lot! 🙏🏻
