### ISSUE TITLE
enableGraphQLOperationTracking attaches invalid context to network errors

### ISSUE THREAD

**Issue by jmccance** [getsentry/sentry-cocoa#4560]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.40.1

### Xcode Version

16.1

### Did it work on previous versions?

Unknown

### Steps to Reproduce

1. Set `enableGraphQLOperationTracking = true` when configuring the Sentry SDK.
2. Ensure `enableNetworkTracking` is enabled
3. In a running app, make a GraphQL request that returns a 500

### Expected Result

An event should appear in Sentry with the `graphql_operation_name` in the context. Probably a "GraphQL" context with an "Operation Name" field.

(As a bonus, I'd love it for `graphql_operation_name` to show up in the tags so that it can be used to differentiate between different request errors. Right now all of our network errors to our API get lumped together into a single Sentry issue.)

### Actual Result

The Sentry event includes a warning indicating that the `graphql` context is invalid because it's a String instead of an object.

![Image](https://github.com/user-attachments/assets/d48ee5e8-f0c1-4a2e-a3b0-5b3cbcf2aaac)

From the event:

```json
"_meta": {
  "contexts": {
    "graphql_operation_name": {
      "": {
        "err": [
          [
            "invalid_data",
            {
              "reason": "expected an object"
            }
          ]
        ],
        "val": "Settings"
      }
    }
  }
}
```

### Are you willing to submit a PR?

Sure

**Comment by philipphofmann** [comment]
@jmccance, our GraphQL support currently is very minimal. We only attach the operation name.

https://github.com/getsentry/sentry-cocoa/blob/d70a7e8dffb0134d06d9c68f686951478b0e539a/Sources/Swift/Tools/URLSessionTaskHelper.swift#L4-L20

Can you maybe provide the GraphQL body and the expected outcome you would like to have? Similar to what this test does:

https://github.com/getsentry/sentry-cocoa/blob/d70a7e8dffb0134d06d9c68f686951478b0e539a/Tests/SentryTests/URLSessionTaskHelperTests.swift#L40-L56

**Comment by jmccance** [comment]
Yep, I understand that it's limited. The bug I'm calling out here is that the current implementation causes a warning in the Sentry dashboard when we use Sentry's built-in [HTTP client error tracking feature](https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/).

I don't think the issue is in URLSessionTaskHelper from what I can see — the method to get the GraphQL operation name works just fine and correctly enriches the breadcrumbs. I think the problem is in SentryNetworkTracker:

https://github.com/getsentry/sentry-cocoa/blob/d70a7e8dffb0134d06d9c68f686951478b0e539a/Sources/Sentry/SentryNetworkTracker.m#L458-L461

It adds a new value to the event context named `graphql_operation_name` but sets its value to `[URLSessionTaskHelper getGraphQLOperationNameFrom:sessionTask]`. From what I can see in the documentation that's not valid because that helper returns a String and [contexts have to be an object](https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/context/#structured-context).

I assume those lines need to be something more like this:

```objc
    if (self.isGraphQLOperationTrackingEnabled) {
        NSMutableDictionary<NSString *, id> *graphql = [[NSMutableDictionary alloc] init];
        context[@"graphql"] = graphql
        graphql[@"operation_name"] = [URLSessionTaskHelper getGraphQLOperationNameFrom:sessionTask];
    }
```

Forgive my rough knowledge of Objective-C. Happy to take a stab at implementing that change if we think it's correct, though.
