### ISSUE TITLE
Fix crash in SentryTracer cancelDeadlineTimer

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4565]
### Description

The SDK sometimes crashes in `SentryTracer cancelDeadlineTimer` with `EXC_BAD_ACCESS`. Sample stack trace from our [internal SDK crash detection](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved%20sdk.version%3A%5B8.39.0%2C8.40.1%2C8.40.0%5D%20deadline&referrer=issue-list&sort=user&statsPeriod=14d&viewId=35146):

```
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: SEGV_NOOP

Thread 0 Crashed:
0   libobjc.A.dylib                 0x18552bc20         objc_msgSend
1   Sentry.framework                0x10625e888         -[SentryTracer cancelDeadlineTimer] (Sentry.framework:249)
2   Sentry.framework                0x10625fa54         -[SentryTracer finishInternal] (Sentry.framework:427)
3   Sentry.framework                0x10625e280         __35-[SentryTracer dispatchIdleTimeout]_block_invoke (Sentry.framework:179)
```

Could be related to https://github.com/getsentry/sentry-cocoa/issues/3977.

**Comment by kahest** [comment]
@philipphofmann is this a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4510?

**Comment by philipphofmann** [comment]
Thanks, yes, it is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4510.
