### ISSUE TITLE
Update `Data` comparisons in tests to ignore dict entries order

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cocoa#4625]
### Description

https://github.com/getsentry/sentry-cocoa/pull/4622 and https://github.com/getsentry/sentry-cocoa/pull/4624 were closed and we could not continue with implementation in Swift as all tests comparing serialized data became super flaky after the changes.

The reason for the flakiness was `Data` comparison in tests which relies on stable deterministic order of serialized objects.

In theory this should be already issue in Obj-C but with conversion to Swift the issue exploded.

Possible solutions
- Update serialization to ensure deterministic order of dict entries
- Update test to compare deserialized values

**Comment by philprime** [comment]
We tackle this the next time when we write tests using dictionaries, to focus on higher priority issues for now.
