### ISSUE TITLE
No way to send HTTP request info related to the event.

### ISSUE THREAD

**Issue by youngliangzhang** [getsentry/sentry-cocoa#486]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.x.x**

---
I have following issue:
There is no way to send HTTP request info related to the event.
I can see it is possible on doc, but no. 
It is official doc 
https://develop.sentry.dev/sdk/event-payloads/request/

**Comment by bruno-garcia** [comment]
@youngliangzhang Could you please clarify what type of Request data are you looking to add?
Is this intended to support a web framework or library?

**Comment by youngliangzhang** [comment]
I want to add HTTP Method, url, parameters, data and headers. 
https://develop.sentry.dev/sdk/event-payloads/request/
As you can see in this documentation, doc says client SDKs can upload these info. but it is impossible in iOS SDK while Android SDK supports it.

**Comment by bruno-garcia** [comment]
The Android SDK already has the complete protocol implemented, we're missing it here indeed.

**Comment by gauravrane2212** [comment]
@bruno-garcia Shouldn't this be a bug and not an enhancement since it broke the ability to send HTTP data which was possible to do it in earlier versions?

**Comment by bruno-garcia** [comment]
Could you set the request to the scope like:

```objective-c
    [SentrySDK.currentHub configureScope:^(SentryScope *_Nonnull scope) {
            NSMutableDictionary *request = [NSMutableDictionary new];
            [request setValue:@"http://sentry.io" forKey:@"url"];
            [scope setContextValue:request forKey:@"request"];
```

Would that help until we have a typed Request?

**Comment by gauravrane2212** [comment]
@bruno-garcia  Thanks for your quick response 👍   I tried the swift variation of this logic and I am still not able to send any requests to the Sentry server.
```
SentrySDK.setUser(user)

SentrySDK.start(options: [
    "dsn": "XXX-sentry_url",
    "debug": true
])

let hub = SentrySDK.currentHub()

hub.configureScope { scope in
  var request: [String: Any] = [:]
  request["XXX-header-key"] = value
  request["url"] = "XXX-sentry_url" // I tried removing this key-value pair; that still didn't work.
  scope.setContext(value: request, key: "request")
}
```

Is there something else in the newer syntax that would be exactly equivalent to this older syntax?

```
Client.shared?.beforeSendRequest = { request in
       request.addValue(value, forHTTPHeaderField: "XXX-header-key")
}
```

**Comment by gauravrane2212** [comment]
@bruno-garcia Any updates on the above query? Thanks :)

**Comment by bruno-garcia** [comment]
@gauravrane2212 could you please paste a [link to a gist](https://gist.github.com/) with the JSON it created? 

Based on your example it should include:
```json
{ "contexts": { "request": { "url": "XXX-sentry_url" } } ... }
```

 And that shows up in Sentry. You can also download the JSON from the Sentry UI (there a `JSON` button at the top of the issue page).

We should add this to the API here anyway, PR's welcome!

**Comment by gauravrane2212** [comment]
@bruno-garcia With reference to the code I wrote above, it didn't send any entry to the Sentry Server (the UI doesn't reflect any logs). The reason is that the Sentry server is set up behind our corporate firewall and it needs the auth header to be attached to the sentry request for it to show up correctly in the UI dashboard. The previous 4.x Sentry API works fine as I can see logs triggered from that API so I have a strong feeling that it is the way the request headers are attached is not correct. Hence my question :)
I would love to contribute but I am not too familiar with the newer API changes! I will try to go over the logic this coming weekend and see if I can open up a PR.

**Comment by bruno-garcia** [comment]
Now I'm confused. [In this comment](https://github.com/getsentry/sentry-cocoa/issues/486#issuecomment-625903918) you mention you want to attach request data like URL and headers.

The snippet I pasted does that, by adding data to the Scope. Once an event is sent out (like `captureMessage` is called), that data is included in that event.

I'm not sure what do you mean by _I can see logs triggered from that API_? 
The API to send events are the `capture` methods.

**Comment by gauravrane2212** [comment]
@bruno-garcia Oh, sorry if there is a disconnect here! That [comment](https://github.com/getsentry/sentry-cocoa/issues/486#issuecomment-625903918) was from a different developer. 

For me, the issue has been finding a replacement for this API method in the 5.x version. 
```
Client.shared?.beforeSendRequest = { request in
       request.addValue(value, forHTTPHeaderField: "XXX-header-key")
}
``` 
This is required to intercept the Sentry requests just before sending to the Sentry Server and attaching the "Auth Token" header to go through our corporate firewall. 

> I'm not sure what do you mean by I can see logs triggered from that API?

By this, I meant that with the 4.x API, I can see the Sentry events (using the capture) methods being shown in the UI. It's just that, I haven't figured out how to intercept the Sentry requests and attach custom headers to each Sentry request with the 5.x API. I hope this clarifies my question.

**Comment by bruno-garcia** [comment]
So you want change the HTTP request the SDK sends to Sentry. Not the `request` object in the `context`.

Please raise a new issue requesting that. This is not what the original issue is about.

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.
