### ISSUE TITLE
SentrySDK.configureScope configured in Swift will cause JSON serialization to fail

### ISSUE THREAD

**Issue by adamwulf** [getsentry/sentry-cocoa#519]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes, 4.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
Sentry (5.0.2)

---
I have following issue:

I am setting the SentrySDK scope in Swift as such:
```
        SentrySDK.configureScope { (scope) in
            let user = User(userId: AppGroupSharedUserDefaults.deviceId)
            user.email = IdentityService.email
            user.username = IdentityService.email
            scope.setUser(user)
            scope.setTag(value: SubscriptionManager.shared.subscriptionState, key: "subscriptionState")
```

However, when forcing a low memory warning to send a memory event, I receive Invalid JSON in the console. If I force Sentry to attempt a JSON serialization by removing the `if` statement in `[SentrySerialization dataWithJSONObject:options:error:]`, I receive the error `Invalid type in JSON write (__SwiftValue)`

If I do not set any Sentry scope in my Swift app, then the memory event is serialized and sent just fine.

**Steps to reproduce:**
1. Swift app, with Sentry (5.0.2) pod
2. configure SentrySDK scope in Swift
3. Force a memory warning event (I did this by allocating /lots/ of `UIGraphicsBeginImageContext` between small delays

**Actual result:**
- Memory event is correctly triggered, does not serialize and is not sent

**Expected result:**
- Memory event to be serialized and sent

Thanks!

**Comment by adamwulf** [comment]
The issue appears to be the `setTag:` call in SentryScope.h#L32-L33

the `id` type will box up any Swift value, which will cause JSON serialization to fail.

**Comment by philipphofmann** [comment]
Thanks, @adamwulf for pointing this out. The tags are actually `NSDictionary<NSString *, NSString *> *`. `(void)setTagValue:(id)value forKey:(NSString *)key` should actually be `(void)setTagValue:(NSString *)value forKey:(NSString *)key`. Learn more about tags here: https://docs.sentry.io/enriching-error-data/additional-data/?platform=aspnetcore#tags
