### ISSUE TITLE
Duplicate symbol '_versionString'

### ISSUE THREAD

**Issue by fontesrp** [getsentry/sentry-cocoa#546]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.0**

---
I have following issue:

I have a React Native project which uses

```
"@sentry/react-native": "1.4.0",
"urbanairship-react-native": "6.1.3"
```

This libs include the following pods

```
pod 'Sentry', '~> 5.1.0'
pod 'Airship', '13.1.1'
```

When trying to run the project, I'm getting this error

```
duplicate symbol '_versionString' in:
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Airship/libAirship.a(UAirshipVersion.o)
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Sentry/libSentry.a(SentryMeta.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

There seems to be a conflict between the names of [this](https://github.com/getsentry/sentry-cocoa/blob/0523938387135009121d6c06cd57cb7c0076e4b4/Sources/Sentry/SentryMeta.m#L5) global variable declared in `SentryMeta.m` and [this](https://github.com/urbanairship/ios-library/blob/b8989daf22cfbdf98a87cee2e49b6c5ddefacbc0/Airship/AirshipCore/Source/common/UAirshipVersion.m#L5) one declared in `UAirshipVersion.m`.

**Steps to reproduce:**

1. `npx react-native init myapp`;
2. `cd myapp`;
3. `yarn add @sentry/react-native urbanairship-react-native`;
4. Open Xcode and try to run the app.

**Actual result:**

The build fails with the error

```
duplicate symbol '_versionString' in:
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Airship/libAirship.a(UAirshipVersion.o)
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Sentry/libSentry.a(SentryMeta.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected result:**

Project compiling with no error of duplicate symbols. I would suggest adding a prefix to global variables, something like `NSString *const Sentry_versionString = @"5.1.0";`.

I have also opened an [issue](https://github.com/urbanairship/ios-library/issues/247) on Airship.

**Comment by philipphofmann** [comment]
Thanks, @fontesrp for pointing this out. I just opened up a PR for this.
