### ISSUE TITLE
Cannot add package via Swift Package Manager

### ISSUE THREAD

**Issue by paulofierro** [getsentry/sentry-cocoa#550]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5.2.4
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [x] Swift Package Manager

Version of sentry-cocoa:
**3.x.x**

---
I have following issue:

Adding `https://github.com/getsentry/sentry-cocoa.git` ([as stated here](https://docs.sentry.io/platforms/cocoa/?platform=javascript)) to the Swift Packages for my project in Xcode results in an error: 

> An unknown error occurred.

This happens on Xcode 11.4.1 and Xcode 11.5 on macOS 10.15.4.

**Steps to reproduce:**
1. Create a new iOS project in Xcode
2. Navigate to the project's Swift Packages
3. Tap + to add a package
4. Enter `https://github.com/getsentry/sentry-cocoa.git` as the repository URL and tap Next

**Actual result:**
- Xcode displays a dialog stating "An unknown error occurred."

**Expected result:**
- Xcode asks which branch/version you want to use.

**Comment by philipphofmann** [comment]
Hey @paulofierro thanks for reaching out to us. I just tried exactly what you specified in the issue and for me adding sentry for the newest version of 5.1.0 works fine. You mentioned in the ticket you tried to install version **3.x.x**. We released version 4.0.0 almost 2 years ago and it also works fine with Swift Package Manager. Do you really need to use version **3.x.x**? If so can you please try to add it with CocoaPods.

**Comment by paulofierro** [comment]
@philipphofmann thanks for your feedback! I don't know what happened but this morning I can install the package without issue — I blame Xcode gremlins 😬

Regarding the version, that was the template default and I hadn't changed it 😓 

Thanks for your help!

**Comment by philipphofmann** [comment]
@paulofierro I'm happy your problem is solved. You are welcome!
