### ISSUE TITLE
C++ exceptions missing stacktrace

### ISSUE THREAD

**Issue by eakoli** [getsentry/sentry-cocoa#551]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [X] Manually

Version of sentry-cocoa:
**5.0.X**

---
I have following issue:
C++ exceptions don't include stack trace information.

I have trace the issue down this:
the CPPException monitor relies on providing an alternate __cxa_throw implementation that captures the stack. This does not work when dynamically linking to the sentry framework. If a static framework is used, everything works fine.

**Steps to reproduce:**
Throw any c++ exception

**Actual result:**
crash report should have stack trace indicating where the exception was thrown

**Expected result:**
No stack trace is associated with the crash report

**Comment by jadar** [comment]
I'm seeing a similar issue. We're getting some unhandled Core Data exceptions, but the stacktraces are next to useless. It just points to the line that enqueued the block where the exception was raised. It doesn't seem like Sentry captures any more information than the exception's type. I'm guessing that if I were to see the real logs, it would say something like "CoreData could not fulfill a fault for '..."

**Comment by bruno-garcia** [comment]
Thanks for raising this. We'll investigate this issue.

**Comment by eakoli** [comment]
FYI originally to work around this I made private static build of things, but later worked around it in a different manner.

We created a cpp file that dynamically loads the __cxa_throw from the next binary in the loader chain (which should be the sentry framework, as its linked before the libc++)

```
#include <dlfcn.h>
 
// CXX bridge as this no longer hooks as it should with dynamic linking.
typedef void (*cxa_throw_type)(void *, void *, void (*)(void *));
 
extern "C" {
    void __cxa_throw(void *thrown_exception, void *tinfo, void (*dest)(void *))
    __attribute__((weak));
     
    void
    __cxa_throw(void *thrown_exception, void *tinfo, void (*dest)(void *))
    {
        static cxa_throw_type orig_cxa_throw = NULL;
        if(orig_cxa_throw == NULL)
        {
            orig_cxa_throw = (cxa_throw_type)dlsym(RTLD_NEXT, "__cxa_throw");
        }
        orig_cxa_throw(thrown_exception, tinfo, dest);
        __builtin_unreachable();
    }
}
```

This was inspired by how were doing the cxx hooking in a sentry-native plugin I made, but I exported the 'hooked' version explicitly as __sentry_cxx_throw to ensure that it would pick up the hooked one and not the 'real' one from libc++ directly.

**Comment by bruno-garcia** [comment]
@eakoli that sounds like a good work around tbhq.

Sadly there's no solution that we can provide for linking dynamically to our framework.

There's more details for those who are unfamiliar with this and end up here:
https://github.com/kstenerud/KSCrash/issues/205#issuecomment-284391574

For that reason I'll close this issue and hope that the our work around can help others if they end up with this problem.

**Comment by eakoli** [comment]
@bruno-garcia One possible work around is that if there isn't an existing stack trace for where the exception was thrown, at least grab the current stack to show where it hit the std::terminate, then at least there would be somewhat of a stack trace.

it looks like KSCrash managed to work around it, although it looks like its a very backdoors-ish approach.
