### ISSUE TITLE
What is equivalent of `beforeSerializeEvent` in version 5?

### ISSUE THREAD

**Issue by vadimtrifonov** [getsentry/sentry-cocoa#554]
Version of sentry-cocoa:
**5.1.0**

---
I have following issue:

In version 4 there is `beforeSerializeEvent`, which allows to do add more parameters to an exception event that are not immediately available when starting tracking (for example, current session parameters).

I can no longer find equivalent functionality in version 5, is there any substitution for `beforeSerializeEvent`?

**Comment by philipphofmann** [comment]
You can use `beforeSend` of [SentryOptions](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryOptions.h#L70). You can do something like this:
```
SentryEvent * (^callback)(SentryEvent *event) =
    ^(SentryEvent *event) { return event; };

NSError *error = nil;
SentryOptions *options =
    [[SentryOptions alloc] initWithDict:
      @{ @"dsn": @"https://yourDSN", @"beforeSend" : callback }
        didFailWithError:&error];
```
We know that the SentryOptions have not the nicest usability right now as discussed in here https://github.com/getsentry/sentry-cocoa/issues/516 and we are going to improve this.

I'm going to close this issue now. Feel free to open it again, if your question is not answered.

**Comment by vadimtrifonov** [comment]
@philipphofmann  In my experience it doesn't send tags when reopening an app after a crash.

**Comment by philipphofmann** [comment]
@vadimtrifonov do you mean it doesn't send tags when you use `beforeSend`?

**Comment by vadimtrifonov** [comment]
@philipphofmann yes, when the app crashes tags are not sent. Tags are only sent for handled errors.

**Comment by philipphofmann** [comment]
Thanks for clarifying this. We are aware of that and have it on our list.
