### ISSUE TITLE
beforeBreadcrumb not called for ui.lifecycle breadcrumbs

### ISSUE THREAD

**Issue by flobories** [getsentry/sentry-cocoa#556]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [x] SPM

Version of sentry-cocoa:
**5.1.1**

---
I have following issue:
The `beforeBreadcrumb` block is not called for view controller's `viewDidAppear` automatic breadcrumb tracking.
I use view controller containment to trigger some behaviors in my app and compose my view controllers. I want to filter out breadcrumbs that are not useful but am not able to do so with the `beforeBreadcrumb` block.

![image](https://user-images.githubusercontent.com/7430239/83316729-6ce44e00-a1dc-11ea-9833-0d1b3bbfc0cb.png)
☝️ In the above example, I'd like to remove `LifecycleBehaviorViewController`, `AppCoreViewController`, `MainViewController` that are only containers, and do not render any data relevant to the user's journey.
I would be able to do so if I could implement a few simple static filtering rules on `breadcrumb.message`.

**Steps to reproduce:**
- Add a `beforeBreadcrumb` to your `SentryConfiguration`
- Set a breakpoint or log statement in your block
- Navigate around your app to trigger `viewDidAppear`

**Actual result:**
- The `beforeBreadcrumb` block is not executed for `viewDidAppear`

**Expected result:**
`beforeBreadcrumb` is called for all breadcrumbs, including the `ui.lifecycle` bread triggered by `viewDidAppear`

---
It appears that the view controller `viewDidAppear` swizzle adds the breadcrumbs directly to the `scope`: 
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryBreadcrumbTracker.m#L144

Without going through the `hub` which is the only one applying the `beforeBreadcrumb` callback: https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryHub.m#L209

**Comment by philipphofmann** [comment]
Thanks, @flobories for reporting this in such detail. This hopefully is going to be an easy fix.

**Comment by philipphofmann** [comment]
This was fixed with https://github.com/getsentry/sentry-cocoa/pull/815. I'm going to close this now.

**Comment by flobories** [comment]
Thank you for the follow up @philipphofmann !
