### ISSUE TITLE
How do I get source code in stack traces like android native?

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#557]
When looking at Sentry crashes that contain native code in an android build, it includes the source code around the line in the stack trace. Is there something I can do to get this for cocoa as well?

**Comment by philipphofmann** [comment]
Hi, @eric please check out our docs here find a way how to do this: https://docs.sentry.io/cli/dif/#creating-source-bundles

**Comment by philipphofmann** [comment]
As we didn't receive an update for over half a year, we are going to close this.
