### ISSUE TITLE
5.x replacements for beforeSerializeEvent and shouldSendEvent

### ISSUE THREAD

**Issue by tgreenman** [getsentry/sentry-cocoa#577]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [X ]  MacOS
- [ ]  watchOS

_Swift:_
- [ X]  Yes -> If yes, which version? 5
- [ ]  No

_sentry-cocoa installed with:_
- [ X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
5.1.4

---
I have following issue:
What is the replacement for Client.shared?.beforeSerializeEvent and Client.shared?.shouldSendEvent in sentry-cocoa 5.1.4?

In 4.x, you are able to do things before events are serialized like so.

```
        Client.shared?.beforeSerializeEvent = { event in
            if SentrySeverity.fatal == event.level {
                guard let mechanismType = event.exceptions?.first?.mechanism?.type else {
                    self.logger.error("Could not find crash mechanism")
                    return
                }
                ...
            }
        }
        Client.shared?.shouldSendEvent = { event in
            for message in BlacklistedMessages {
                if (String(event.message).contains(message)) {
                    return false
                }
            }
            return true
        }

```
These apis don't appear to exist in 5.x, but maybe I'm just blind.

**Comment by tgreenman** [comment]
There's SentryBeforeSendEventCallback but I'm not quite sure how it's supposed to be set with the current docs

**Comment by philipphofmann** [comment]
Hi @tgreenman thanks for reaching out to us.
You can use the `beforeSend` callback of [`SentryOptions`](https://github.com/getsentry/sentry-cocoa/blob/18ac05103b069113dc0836b43a10463ae0ade707/Sources/Sentry/include/SentryOptions.h#L70). 
You can use it like this 
```
let beforeSendCallback: SentryBeforeSendEventCallback = { event in
    return event
}

SentrySDK.start(options: [
    // ...
    "beforeSend": beforeSendCallback,
])
```
but we know that this is currently not working with Swift, as you can't pass in functions to a dictionary properly. 
We are aware that initializing the `SentryOptions` with a dictionary is not the most user-friendly way as already pointed out in https://github.com/getsentry/sentry-cocoa/issues/516.
