### ISSUE TITLE
Could not attach stacktrace to custom event

### ISSUE THREAD

**Issue by ainopara** [getsentry/sentry-cocoa#578]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.4**

---
I have following issue:

Could not attach stacktrace when using `[SentrySDK captureEvent:]` API

**Steps to reproduce:**

Create a custom event object and send it with
```swift
SentrySDK.capture(event: event)
```

**Actual result:**
No stacktrace attached.

**Expected result:**
Hope there is a way to attach stacktrace to a custom event.

**Comment by philipphofmann** [comment]
Hi @ainopara, do you have the `attachStacktrace` for the  `SentryOptions` enabled? 
```
SentrySDK.start(options: [
    // ...
    "attachStacktrace": true,
    // ...
])
```

**Comment by ainopara** [comment]
From implementation [here](https://github.com/getsentry/sentry-cocoa/blob/5.1.4/Sources/Sentry/SentryClient.m#L122):
Stacktrace will be attached when captureMessage / captureException / captureError is called.
But there is no way to attach stacktrace to a custom event when captureEvent is used.

**Comment by philipphofmann** [comment]
We can add the possibility to attach the stacktrace to a custom event as you suggested. This shouldn't be a complicated change.

**Comment by ainopara** [comment]
Hi, @philipphofmann I have a question about current implementation #583 .
Is there possible to override `attachStacktrace` option with a custom scope, so that stack trace can be attached only for some kind of events.
This is useful in this use case:
https://github.com/ainopara/Stage1st-Reader/blob/v3.17/Stage1st/Manager/EventTracker.swift#L17
I hope stacktrace can be attached to event when `EventTracker.recordError` is used, but not when `EventTracker.logEvent` is used.

**Comment by philipphofmann** [comment]
@ainopara the stacktrace is always attached when [logging an exception](https://docs.sentry.io/error-reporting/configuration/?platform=csharp#attach-stacktrace). So when you call `captureError`, `captureException` or `captureEvent` with an event that contains an exception. When you call `captureMessage` or `captureEvent`, with an event that doesn't contain an exception, the stacktrace is not attached. When you enable `attachStacktrace` the stacktrace is attached for all mentioned above.

**Comment by ainopara** [comment]
Hi @philipphofmann , thank you for your reply.
I hope there is a way to determine if stacktrace should be attached when assembling custom event. 

I am not logging an exception, because it is automatically handled by sentry sdk in cocoa platform. 
I am logging custom events which have variety levels from info to error.
For example:
 `assertionFailure` in swift will not trigger a crash if project is build for release. 
To collect logic error triggered in user's device, I create an event when assertion failure triggered in release build. And I'm expecting this event contains stacktrace.
But when I'm createing an event to record other issue in project, I may not need the stack trace and expecting it is not collected by sentry sdk.

It seems `attachStacktrace` option is part of unified api, which make it hard to change it's behavior.
Is it possible to expose this api so that developers can decide when to attach a stacktrace to their custom event?
```objc
event.debugMeta = [self.debugMetaBuilder buildDebugMeta];
// We don't want to add the stacktrace of attaching the stacktrace.
// Therefore we skip three frames.
event.threads = [self.threadInspector getCurrentThreadsSkippingFrames:3];
```

**Comment by philipphofmann** [comment]
@ainopara if you want more flexibility you can init your own `SentryHub` with your own `SentryClient` with different `SentryOptions`. The `SentrySDK` is just a [static wrapper](https://develop.sentry.dev/sdk/unified-api/#simplified-visualization).
