### ISSUE TITLE
`release` in `startWithOptions:` is ignored for crash reports

### ISSUE THREAD

**Issue by jjochen** [getsentry/sentry-cocoa#581]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.4**

---

When starting sentry with a custom release, the value is ignored in crash reports.

```
    [SentrySDK startWithOptions:@{
        @"dsn": @"___PUBLIC_DSN___",
        @"release": @"test release",
        @"environment": @"test environment",
    }];
```
will still use the default release
```
[NSString stringWithFormat:@"%@@%@+%@", appContext[@"app_identifier"],
appContext[@"app_version"], appContext[@"app_build"]];
```

**Comment by jjochen** [comment]
Btw. I think that's because the release name is not stored with the crash report user data (like it is the case for `environment`).

**Comment by philipphofmann** [comment]
Thanks, @jjochen for reporting this issue. I can reproduce it.

**Comment by philipphofmann** [comment]
@jjochen we are already working on a fix for this. As a work around until we release the fix you can override the `releaseName` with the `beforeSend` callback:
```
SentryEvent * (^callback)(SentryEvent *event) = ^(SentryEvent *event) {
    event.releaseName = @"...";
    return event;
};

[SentrySDK startWithOptions:@{
    // ...
    @"beforeSend": callback
}];
```
