### ISSUE TITLE
How to remove auto breadcrumb tracking

### ISSUE THREAD

**Issue by zachwaugh** [getsentry/sentry-cocoa#594]
_Platform:_
- [x ]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.4**

---
I have following issue:

How do I disable auto-breadcrumb tracking? There's a lot of junk there that's not very helpful. I'd rather disable that completely and track significant events manually. I can't find any documentation though on how to control integrations in the 5.0 SDK. I see the `enableAutoSessionTracking` option, but no equivalent for breadcrumbs. Looking at the code, guess I have to set the `integrations` parameter to an array of strings, but it's not clear what strings are available. I see this - https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryOptions.m, which makes it seem like if I set it to an empty array, not even crash detection will be enabled. So I have to do something like this:

```swift
SentrySDK.start(options: [
   "integrations": Sentry.Options.defaultIntegrations().filter { !$0.contains("Breadcrumb") }
 ])
```

which doesn't feel right at all. It's also fragile since it's depending on hard-coding the string. I'm hoping I'm missing something an there's a better way to do that.

**Comment by philipphofmann** [comment]
@zachwaugh yes that's the way to do it right now. I agree that this is fragile. 

We have `enableAutoSessionTracking` so we could add something like `enableBreadcrumbs`. What do you guys think @bruno-garcia, @marandaneto and @HazAT ?

**Comment by marandaneto** [comment]
@zachwaugh https://docs.sentry.io/platforms/cocoa/usage/?platform=swift#integrations

I'd be interested to learn which breadcrumbs you consider:

> There's a lot of junk there that's not very helpful

actually, those automatic breadcrumbs have been asked by customers and the community, I'd love to get your feedback.

**Comment by zachwaugh** [comment]
@philipphofmann @marandaneto thanks for the confirmation! Were those docs just added, or did I somehow completely miss that before? +1 for an option like `enableBreadcrumbs` for each integration over setting an array of strings.

Breadcrumbs have been hit or miss for me, but here's an example of what I'm talking about that I've seen a bunch. Recording these system classes (looks related to the keyboard), is too noisy and hides more relevant things. Besides that though, I generally prefer to keep swizzling to a minimum out of an abundance of caution so no potential bugs there cause issues in our app, so rather that be opt-in rather than opt-out.

<img width="1240" alt="Screen Shot 2020-07-02 at 9 50 42 AM" src="https://user-images.githubusercontent.com/21447/86367042-864c4000-bc49-11ea-97ac-8b2a2c25d731.png">

**Comment by marandaneto** [comment]
@zachwaugh docs were already there :)
 I understand, an option would be to also filter them using the `beforeBreadcrumb` callback by `type` or `category`, a high-level doc is here https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=csharp#breadcrumb-customization

Maybe a subset of the automatic breadcrumbs would be interesting, so, you'd filter what would make sense for your App.

Also +1 to `enableBreadcrumbs`
