### ISSUE TITLE
How to report crash on launch

### ISSUE THREAD

**Issue by CX3201** [getsentry/sentry-cocoa#597]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.6**

---
I have following issue:

I write the following code to raise an exception, but the crash never reported. Is there any way to do this?

**Steps to reproduce:**
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    [SentrySDK startWithConfigureOptions:^(SentryOptions *options) {
        options.dsn = @"___PUBLIC_DSN___";
        options.debug = @YES; // Helpful to see what's going on
    }];
    [SentrySDK crash];
    return YES;
}
```

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by philipphofmann** [comment]
@CX3201, did you replace `___PUBLIC_DSN___ ` with your DSN that you get from Sentry? If not please do so. If so, please check your log output, because it can be that the DSN is not valid.

**Comment by CX3201** [comment]
> @CX3201, did you replace `___PUBLIC_DSN___ ` with your DSN that you get from Sentry? If not please do so. If so, please check your log output, because it can be that the DSN is not valid.

Yes, I did. I think the resaon is the report request doesn't  have enough time to send. Is there any sync method?

**Comment by philipphofmann** [comment]
Please don't call `[SentrySDK crash];` directly after our SDK start and also not in `didFinishLaunchingWithOptions`. Instead, call it when the app is fully launched or even better call it when you click a button.
When a hard crash happens our SDK stores the crash on the disk. The next time the SDK is launched we read it from the disk and send it to Sentry. Right now the SDK hasn't enough time to do that, because your implementation always crashes directly after our SDK is started.

**Comment by CX3201** [comment]
> Please don't call `[SentrySDK crash];` directly after our SDK start and also not in `didFinishLaunchingWithOptions`. Instead, call it when the app is fully launched or even better call it when you click a button.
> When a hard crash happens our SDK stores the crash on the disk. The next time the SDK is launched we read it from the disk and send it to Sentry. Right now the SDK hasn't enough time to do that, because your implementation always crashes directly after our SDK is started.

That means Sentry will never send report if the app crashes directly in didFinishLaunchingWithOptions.  Is there something I can do to collect those exceptions?

**Comment by philipphofmann** [comment]
Sentry most likely will never send the report if the app always crashes in `didFinishLaunchingWithOptions`, because it doesn't get enough time to send the report. If it only happens a few times Sentry writes the error to the disk and sends it the next time.

**Comment by CX3201** [comment]
> Sentry most likely will never send the report if the app always crashes in `didFinishLaunchingWithOptions`, because it doesn't get enough time to send the report. If it only happens a few times Sentry writes the error to the disk and sends it the next time.

Thanks

**Comment by philipphofmann** [comment]
@bb-git, agree see https://github.com/getsentry/sentry-cocoa/issues/316
