### ISSUE TITLE
Crash reports lacking detail

### ISSUE THREAD

**Issue by RuiAAPeres** [getsentry/sentry-cocoa#598]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes - 5.2.4
- [ ]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.6**

---
Sentry SDK setup:

```swift
SentrySDK.start { options in
  options.dsn = environment.sentryDSN
  options.enableAutoSessionTracking = true
  options.environment = environment.name
  options.releaseName = "iOS \(versionNumber) (\(buildNumber))"

  #if DEBUG
  options.debug = true
  #endif
}
```

The crash report on the Sentry dashboard is not consistent across the same exception. Given the following code:

```swift
func please_crash() {
   let array: [String] = []
   array.first!
}
```

I am receiving different reports details for the same crash:

![image](https://user-images.githubusercontent.com/949286/86252283-eb9d2400-bbaa-11ea-986a-43ffc2f3cba7.png)

1. The first crash is on release build using TF (TestFlight).
2. The second crash is on debug build running on a real device.

You can find the shared report for the TF build here: https://sentry.io/share/issue/4b83322571f14fc4886bda2cce108f8b/
And for the debug version here: https://sentry.io/share/issue/a62617bf2736465db3f68dfac79869bc/

Although not symbolicated, the debug version is able to provide me more information than the symbolicated TF one.

Am I doing something wrong?

--- 

On a different account, the crash report doesn't really help by showing, by default, the thread's stack where Sentry is running:

![image](https://user-images.githubusercontent.com/949286/86251159-66fdd600-bba9-11ea-9e49-c33561a6ed05.png)

Could you please either not show this at all, or show the stack where the crash occurred by default?

**Comment by philipphofmann** [comment]
@RuiAAPeres thanks for reaching out to us. This link doesn't work for me: https://sentry.io/share/issue/a62617bf2736465db3f68dfac79869bc/. It says page not found. Can you please post a link that is working.

**Comment by philipphofmann** [comment]
> Could you please either not show this at all, or show the stack where the crash occurred by default?

It seems this stems from capturing an event. For that, we only attach the stack trace of the current thread, see [SentryOptions.attachStacktrace](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryOptions.h#L110-L114).

For a crash, we send a different event containing stack traces for all threads.

**Comment by HazAT** [comment]
Can you upgrade to `5.1.8` please, we fixed a bug there.

**Comment by philipphofmann** [comment]
@RuiAAPeres any updates on this issue?

**Comment by philipphofmann** [comment]
As we don't receive any updates from you @RuiAAPeres we assume this isn't an issue anymore. Feel free to open this again with more details if you still have problems.
