### ISSUE TITLE
debug_meta.images.X.debug_id: Discarded invalid value

### ISSUE THREAD

**Issue by nzhuk** [getsentry/sentry-cocoa#611]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Swift Package Manager
- [ ] Manually

Version of sentry-cocoa:
**5.1.6**

---
I have an iOS app, built with Xcode 11.5, including both Swift (5.2) and ObjC code. Crash reports for this app are reported correctly to Sentry, but Sentry is having problems with symbolication.

dSYM files have been uploaded as per Sentry documentation, and are listed correctly in Project settings -> Debug files.

However, when I open any issue, I see this:

<img width="658" alt="Screenshot 2020-07-09 at 13 24 36" src="https://user-images.githubusercontent.com/294154/87028640-92a34080-c1e7-11ea-8bbc-4f47fcbd5472.png">

All symbols coming from the app binary are marked as `<redacted>`.

So it looks like some kind of build identifier is missing from all binary images of the app, and Sentry is having trouble mapping binaries to dSYM files. 

How do I enable this "build id" in my builds? What build setting am I missing?

**Comment by philipphofmann** [comment]
Thanks for reaching out to us @nzhuk.
This could be related to #605, it was released with 5.1.8. Please try to update and let us know if this fixes the issue.

**Comment by nzhuk** [comment]
Thanks @philipphofmann . Will do!

**Comment by philipphofmann** [comment]
@nzhuk do you have any updates on this issue?

**Comment by nzhuk** [comment]
@philipphofmann Currently travelling, but I'll will check status of this once I'm back & update this issue.

**Comment by philipphofmann** [comment]
Thanks for the update @nzhuk. Safe travels!

**Comment by nzhuk** [comment]
@philipphofmann Yes, I can confirm that ```debug_meta.images.X.debug_id: Discarded invalid value``` issue was fixed by updating Sentry SDK to 5.2.0 🥳

**Comment by philipphofmann** [comment]
Thanks for the update @nzhuk.
