### ISSUE TITLE
How can I include custom file attachments to crash events in Swift (iOS 13.5) ?

### ISSUE THREAD

**Issue by sedwo** [getsentry/sentry-cocoa#624]
_Platform:_
- [✅]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [✅, 5.x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [✅] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.9**

---
I have following issue:
Your docs mention [Event Attachments](https://docs.sentry.io/enriching-error-data/attachments/#event-attachments), of which I'd like to try and include some custom log files.

But I can't seem to find a way to accomplish this in Swift.

Am I missing something?

**Comment by philipphofmann** [comment]
Hi @sedwo, this is not possible right now with the Cocoa SDK. This is going to be possible once we switch to sending all events with [envelopes](https://develop.sentry.dev/sdk/envelopes/), which gives us the possibility to add attachments. We have it on our backlog, but I can't give you a fixed date yet.
