### ISSUE TITLE
Feature: User Feedback

### ISSUE THREAD

**Issue by eaigner** [getsentry/sentry-cocoa#629]
I think what would give Sentry a huge edge would be the option to include user feedback. For instance, I have some crashes that I have no idea how to reproduce unless a user actually tells me what he did. Those traces are mostly from Apples system frameworks without any line of my apps code.

Here is my proposal:

In the config callback, let the user provide a `reportDelegate` like so

~~~
SentrySDK.start { options in
    options.dsn = "___PUBLIC_DSN___"
    options.crashReportDelegate = <MYDELEGATE>
}   
~~~

The delegate looks something like this

~~~
protocol SentryCrashReportDelegate {
    func sentryCreatedCrashReport(report: SentryCrashReport)
}
~~~

Now if this delegate was provided by the user, it is called when Sentry tries to upload a new crash report.

~~~
func sentryCreatedCrashReport(report: SentryCrashReport) {
    // The user/dev can open a custom report dialog here and could ask the user
    // if he wants to provide additional information.
    //
    // When he is done he calls `report.send()` or `report.discard()`
}
~~~

The `SentryCrashReport`s interface looks basically like this

~~~
protocol SentryCrashReport {

    var reportURL: URL { get }
    var userFeedback: String? { get set }

    // other sentry related fields...

    /// Called when the user is finished modifying the report and wants to upload it
    func send()

    /// In case we want to discard this report.
    func discard()
}
~~~

If the `userFeedback` field was set, it could be attached as the last breadcrumb.

**Comment by bruno-garcia** [comment]
Thanks for raising this.

Sentry supports Feedback and it's very common for JS users. It shows Sentry's user report modal.
There's a tab on the issues page solely for user feedback:
![image](https://user-images.githubusercontent.com/1633368/88056984-6b296d80-cb2f-11ea-8a66-f42a84cf4507.png)


It doesn't need to be sent with the event itself, it can actually be captured after the fact and linked via the event-id.

We're planning to add this to the mobile SDKs sooner rather than later. We will update this issue with the progress.

**Comment by eaigner** [comment]
Didnt know about that tab!

The important thing though would be that a) events and crashes can be associated with a certain feedback and b) the report interface can be completely customized and is not generated by the SDK itself.

**Comment by philipphofmann** [comment]
@eaigner we just opened up a PR https://github.com/getsentry/sentry-cocoa/pull/805 for manually capturing user feedback like this
```
let userFeedback = UserFeedack(eventId: eventId)
userFeedback.comments = "It broke on macOS-Swift. I don't know why, but this happens."
userFeedback.email = "john@me.com"
userFeedback.name = "John Me"
SentrySDK.capture(userFeedback: userFeedback)
```


So you could already manually take care of attaching user feedback to an event. We have plans on adding a proper way to attach that on crashes in a user-friendly way. Still, you could already do something like this now:

```
SentrySDK.start { options in
    options.beforeSend = { event in
        if (event.level == .fatal) {
            displayUserFeedback(eventId: event.eventId)
        }
        return event
    }
}

// Not a sentry function. Only wraps call to user feedback
func displayUserFeedback(eventId: SentryId) {
    // Display UI and get feedback from the user.
        
    // Then send feedback to Sentry
    let userFeedback = UserFeedack(eventId: eventId)
    feedback.comments = "It broke"
    feedback.name = "John Smith"
    feedback.email = "john@smith.com"
    SentrySDK.capture(userFeedback: feedback)
}
```

Any feedback on this is appreciated.

**Comment by philipphofmann** [comment]
We are currently working on a callback for crashes in https://github.com/getsentry/sentry-cocoa/pull/808. Together with user feedback, it would look like this:
```
SentrySDK.start { options in
    // ...
    
    options.onCrashedLastRun = { eventId in
        self.displayUserFeedback(eventId: eventId)
    }
}

// Not a sentry function. Only wraps call to user feedback
func displayUserFeedback(eventId: SentryId) {
		
    // Display UI and get feedback from the user. 

    // Then send feedback to Sentry
    let feedback = SentryUserFeedback(eventId: eventId)
    feedback.comments = "It broke"
    feedback.name = "John Smith"
    feedback.email = "john@smith.com"
    SentrySDK.capture(feedback: feedback)
}
```

Do you maybe have any inputs on this @eaigner ?

**Comment by philipphofmann** [comment]
We just released https://github.com/getsentry/sentry-cocoa/pull/805. I think you can achieve now what you asked for @eaigner. I'm going to close this now.
