### ISSUE TITLE
NXGetLocalArchInfo is marked as private API

### ISSUE THREAD

**Issue by vox-humana** [getsentry/sentry-cocoa#635]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.0**

---
Seems like Apple marked `NXGetLocalArchInfo`, which [used in the library to get arch name](https://github.com/getsentry/sentry-cocoa/blob/854ddb4bca43cfd7c1119ec1bf0a9caa452bd74d/Sources/SentryCrash/Recording/Tools/SentryCrashCPU.c#L40),  as private API. Since the end of the previous week we are getting this message when we are uploading our mac binaries to App Store Connect:

> ... ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/Frameworks/Sentry.framework/Versions/A/Sentry: _NXGetLocalArchInfo. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/ 

Thus, we cannot release our builds anymore. Even though I believe this an issue on Apple side because this method seems quite public to me, I think we should probably consider using a different method. Will try to reach App Store Review team while and will post an update here.

**Comment by philipphofmann** [comment]
Thanks, @vox-humana for reporting this. Firebase has a similar issue: https://github.com/firebase/firebase-ios-sdk/issues/6128 .

**Comment by vox-humana** [comment]
Thanks for the quick fix 🥳 
I've raised a feedback ticket right after I posted it here. Haven't got any response.
The feedback ticket number is FB8184586 is case somebody faces the same issue and finds this thread.

**Comment by philipphofmann** [comment]
@vox-humana do you by any chance have already a response from the App Store Review team?

**Comment by vox-humana** [comment]
@philipphofmann Apple has reached us once via feedback assistant to confirm the case, but after that unfortunately no news.

**Comment by philipphofmann** [comment]
Thanks for the update @vox-humana. So they confirmed the case. Does this sound like they are going to fix it?

**Comment by vox-humana** [comment]
@philipphofmann According to my personal statistics Apple never confirms bugs and gives developers any hope 😅 The same happens this time. They've just asked whether we could confirm this issue and that was all.

**Comment by vox-humana** [comment]
Unfortunately, I can't quickly check whether it is still an issue just by building and uploading binary with this symbol because we have quite strict process for publishing builds (don't have direct access to signing certificates).

**Comment by philipphofmann** [comment]
I wasn't expecting they would tell you they fix it 😁, but worth a shot. Thanks, a lot for the update @vox-humana.

**Comment by philipphofmann** [comment]
@vox-humana do you have maybe any updates if `NXGetLocalArchInfo` is stilled marked as private?

**Comment by vox-humana** [comment]
@philipphofmann Because we are using the library without this symbol I can't verify the issue anymore. Also, we didn't get any reply from Apple.
