### ISSUE TITLE
Prevent the iOS App to send the users IP address

### ISSUE THREAD

**Issue by mmalesevic** [getsentry/sentry-cocoa#663]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Swift 5.2.5 in a UIKit Project
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.10**

---
I have following issue:
The users IP-address cannot be removed entirely from the event data in iOS beforeSend callback or scope configuration callbacks... it has to be scrubbed on server side, i'd rather be able to not send it, then to have to remove it afterwards. Setting the flag, in the project settings -> https://sentry.io/settings/<organization>/projects/<projects>/security-and-privacy/ has no effect at all. 

Tried to remove it start as follows

```
 SentrySDK.start { options in
            options.dsn = "*******"
            
            options.beforeSend = { event in
                event.user = Sentry.User(userId: UUID().uuidString)
                if let user = event.user {
                    user.ipAddress = "0.0.0.0"
                }
                return event
            }
        }
```

...or tried to remove it via scope... result is the same... 

```
        SentrySDK.configureScope(){ (scope) in
            scope.removeTag(key: "ip_address")
            scope.removeExtra(key: "ip_address")
            scope.removeContext(key: "ip_address")
            scope.removeTag(key: "user.ip_address")
            scope.removeExtra(key: "user.ip_address")
            scope.removeContext(key: "user.ip_address")
        }
```
**Steps to reproduce:**
- add config
- add following code somewhere where it's called (e.g. after sentry config) and make the app crash on purpose
 
```
    let tmpArray = [String]()
    print(tmpArray[23])
 ```

- **start app with no debugger**
- remove the above code and start the app again

**Actual result:**
- The ip address remains in the event report json... although i have managed, it not to be visible in the UI, the json-file still contains it... so it obviously is sent...  

**Expected result:**
- not to send the ip address within the event at all

**Comment by philipphofmann** [comment]
Hi @mmalesevic and thanks for reaching out to us.

I just see that we miss `ip_address` totally in the serialization of [`SentryUser`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryUser.m#L39). This most likely is the reason, why your endeavors don't work. This is an easy fix.

If activating the setting `Prevent Storing of IP Addresses` in security and privacy doesn't work for you please open up an issue at https://github.com/getsentry/sentry/issues.
