### ISSUE TITLE
Not able to use Sentry in separate package

### ISSUE THREAD

**Issue by bardonadam** [getsentry/sentry-cocoa#674]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes (5)
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [x] Swift Package Manager

Version of sentry-cocoa:
**5.2.0**

---
I have following issue:
I'm not able to use Sentry in separate package. When importing Sentry, it gives following error:

`import Sentry // No such module 'Sentry'`

Here's my `Package.swift`:
```
let package = Package(
    ...
    dependencies: [
        .package(
            url: "https://github.com/getsentry/sentry-cocoa.git",
            .exact("5.2.0")
        ),
        ...
    ],
    ...
```

I see the Sentry package amongst the Swift Package Dependencies in the Project Navigator.

**Comment by philipphofmann** [comment]
Thanks @bardonadam for raising this issue. We did some fixes for header files in general and also some fixes for Swift Package Manager in 6.0.0. Can you please update and let us know if you still experience the issue?

**Comment by bruno-garcia** [comment]
Can you try adding a `name`:

```swift
    dependencies: [
        .package(
            name: "Sentry",
            url: "https://github.com/getsentry/sentry-cocoa.git",
            .exact("6.0.1")
        ),
        ...
    ],
```

[I needed to do that here](https://github.com/bruno-garcia/SentryCocoaLumberjack/blob/e30623b76a27647e87d8cba0752724b782ec40ab/Package.swift#L23-L26) but I had a compiler error IIRC.

**Comment by bardonadam** [comment]
@philipphofmann It works! Thank you!
