### ISSUE TITLE
add SentrySDK.isStarted?

### ISSUE THREAD

**Issue by d2vydov** [getsentry/sentry-cocoa#697]
I haven't found a convenient way for check was the sentry started on client or not.

it could be achieved in `4.4.x` via `Client.shared != nil`

what you think for add simple property `@property (nonatomic, class, readonly) BOOL isStarted;`?

**Comment by bruno-garcia** [comment]
That's fair and would be a good addition.

On Android we have `isEnabled`:
https://github.com/getsentry/sentry-android/blob/282d224739ee6536e7517821aab92f3587bed783/sentry-core/src/main/java/io/sentry/core/Sentry.java#L52

Would be happy to merge a PR adding this API if you're willing to open one.

**Comment by d2vydov** [comment]
https://github.com/getsentry/sentry-cocoa/pull/700

**Comment by d2vydov** [comment]
@bruno-garcia I've just opened a PR: #700

**Comment by philipphofmann** [comment]
Was fixed with https://github.com/getsentry/sentry-cocoa/issues/809
