### ISSUE TITLE
Permit nil in setExtraValue

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#701]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_Swift:_
- [ ]  Yes
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.0**

---
I have following issue:

`setExtraValue` is declared as:

```
- (void)setExtraValue:(id)value forKey:(NSString *)key NS_SWIFT_NAME(setExtra(value:key:));
```

In an `NS_ASSUME_NONNULL_BEGIN` block, this implies the extra value may not be `nil`.  Xcode's undefined behaviour sanitizer trips on this when submitting nil values.  Internally however, Sentry simply passes the value off to `NSMutableDictionary`'s `setValue:forKey:`, which accepts `nil` values just fine for the sake of removing the extra from the dictionary.

I would propose that Sentry permits `nil` values by simply adding `_Nullable` to the declaration.  Not doing so forces the application to juggle the case of nil values in special ways leading to excessive and unnecessary verbosity.

**Comment by bruno-garcia** [comment]
@lhunath Makes sense to allow 'unsetting' a value from the map.

An alternative API would be `unsetExtra(key)`. That's [the API in .NET](https://github.com/getsentry/sentry-dotnet/blob/d2c16b3f837ce24778f49bc73ec39ab74f9c8470/src/Sentry.Protocol/BaseScopeExtensions.cs#L216) but I don't think it's in the other SDKs.
I couldn't find it in the [unified API docs](https://develop.sentry.dev/sdk/unified-api/) either.

I'm OK with making the changes you propose. Maybe @philipphofmann or @HazAT have thoughts though.

Would you be willing to open a PR?

**Comment by philipphofmann** [comment]
Thanks, @lhunath for pointing this out. I think what you suggested makes sense. Also, the `NSMutableDictionary` allows `nil` for `setValue` and has a method `removeObjectForKey`.
