### ISSUE TITLE
incompatible with `-Werror,-Wquoted-include-in-framework-header`

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#702]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.0**

---
I have following issue:

```
/Users/lhunath/Library/Developer/Xcode/DerivedData/MasterPassword-gzrmwlqcifsvvrbdghsxyhbprygp/Build/Products/Debug-iphoneos/Sentry-iOS/Sentry.framework/Headers/Sentry-iOS-umbrella.h:13:9: error: double-quoted include "NSData+SentryCompression.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
#import "NSData+SentryCompression.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        <Sentry/NSData+SentryCompression.h>
```

Ideally, Sentry's header files should be proofed against all warnings to ensure they are maximally compatible with applications that choose to include them but also choose to have non-standard warnings enabled (possible in addition to `-Werror`).

**Comment by bruno-garcia** [comment]
Agree it shouldn't raise any warnings. We should take care of that somehow.
Is that something you could also fix in a PR? :)

**Comment by philipphofmann** [comment]
Thanks @lhunath for raising this issue. We did some fixes for the header files with 6.0.0 and also 6.0.1. Can you please update and let us know if you still experience this issue?

**Comment by joaomvfsantos** [comment]
I have updated to 6.0.1 and get the warnings. Basically every double quote import inside a framework raises a warning, which should be angle bracketed.

For the sake of example. In SentryUser.h, #import "SentryDefines.h" should be #import <SentryDefines.h> and so forth on every other file.

**Comment by philipphofmann** [comment]
> I have updated to 6.0.1 and get the warnings. Basically every double quote import inside a framework raises a warning, which should be angle bracketed.
> 
> For the sake of example. In SentryUser.h, #import "SentryDefines.h" should be #import <SentryDefines.h> and so forth on every other file.

Thanks for reporting this @joaomvfsantos. This is a different issue and is related to https://github.com/CocoaPods/CocoaPods/issues/9902. Can you please open up another issue for this?

**Comment by joaomvfsantos** [comment]
@philipphofmann I apologise for the mixup. I can confirm updating to CocoaPods `1.10.0-rc1` solves the issue I was reporting, so no need for further action. Thank you.

**Comment by philipphofmann** [comment]
No worries, it looked similar. Thanks for the update @joaomvfsantos.

**Comment by philipphofmann** [comment]
As we didn't receive any updates for this issue @lhunath I'm going to close it now. Please open it again, if you still experience the issue.
