### ISSUE TITLE
Particular iOS crash with iPhone 6 Plus w/ iOS 12.4 not being reported

### ISSUE THREAD

**Issue by kbokarius** [getsentry/sentry-cocoa#713]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5.2.4
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
5.2.2

---
I have following issue:

So we’ve integrated the sentry-cocoa SDK, and we’ve confirmed it is reporting crashes to the right project for several different types of crashes. However, there’s a particular crash from a user that we’ve been unable to reproduce that we do not get reports for. We had the user crash the app two other ways, and we did get those crash reports from their device.

Our app is built with Flutter (we have Sentry integrated on the Flutter side and do report unhandled exceptions there), the device is running iOS 12.4 and it is an iPhone 6 Plus.

Are there particular circumstances, or a particular type of crash where the sentry-cocoa SDK is unable to catch and report it? 

**Steps to reproduce:**
Unknown.

**Actual result:**
We would see the crash reported in our Sentry project like we do other crashes.

**Expected result:**
We don't see this particular crash reported.

**Comment by bruno-garcia** [comment]
Cross posted: https://github.com/getsentry/sentry-java/tree/main/sentry-samples

**Comment by philipphofmann** [comment]
As @bruno-garcia already mentioned in [here](https://forum.sentry.io/t/flutter-ios-sentry-cocoa-sdk-not-reporting-all-crashes/11082/4?u=philipp): 

> I believe OOM could be a reason, but other than that I don’t know what kind of error could happen that our sentry-cocoa SDK would not capture.

I'm also not aware of other types of crashes, that we are not able to report. 

FYI, we are building a proper SDK with Flutter in here: https://github.com/getsentry/sentry-dart. Do you maybe have more context about this problem, so we can reproduce it @kbokarius?

**Comment by kbokarius** [comment]
@philipphofmann we did confirm that the crash is an OOM crash. Closing this issue, thank you.
