### ISSUE TITLE
OS specific data not included in events captured by Client instances

### ISSUE THREAD

**Issue by tobiasjordan** [getsentry/sentry-cocoa#725]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x]  macOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.3
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.2.2**

---
I have following issue:

Since upgrading to Sentry 5, I can no longer send events that automatically have the OS specific data (such as the version) via a `Client` instance. The OS data is added automatically only for events captured using `SentrySDK` but since I'm sending events to two different Sentry projects in my target, I cannot use `SentrySDK.capture(…)` for both.

I know that I could probably add this information manually myself but since the code is already there in `SentryCrashIntegration` I'm wondering why I'd have to do this myself again. Am I missing something here?

**Steps to reproduce:**
- Create a new `Client` instance
- Send an event via the created instance

**Actual result:**
- The event gets sent to Sentry successfully but it does not contain OS data

**Expected result:**
- The event gets sent to Sentry successfully and contains OS data automatically

**Comment by philipphofmann** [comment]
Thanks @tobiasjordan for reaching out to us. If I call for example `captureMessage` is see some data about the OS in the corresponding issue:

<img width="880" alt="Screenshot 2020-10-05 at 17 30 05" src="https://user-images.githubusercontent.com/2443292/95099625-69d01000-0730-11eb-9775-65c7b73c3e3e.png">

Can you be more specific on which data you are missing?

**Comment by philipphofmann** [comment]
As we didn't receive any updates on this one @tobiasjordan, we are going to close this issue now. Please open it again, if you still have problems or more information for us to reproduce this. Upgrading to v 6.x.x might also help. The breaking changes are from 5.x.x to 6.x.x are way less than from 4.x.x to 5.x.x.

**Comment by MageSantana** [comment]
Hi, I'm using version 6.0.9 and OS specific data are not included in events or messages send.

**Comment by philipphofmann** [comment]
@MageSantana please see https://github.com/getsentry/sentry-cocoa/issues/434#issuecomment-738003464.
