### ISSUE TITLE
Attribute issues from enterprise builds with build_type "enterprise" instead of "test"

### ISSUE THREAD

**Issue by koenpunt** [getsentry/sentry-cocoa#778]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.0**

---

Currently apps signed and distributed as enterprise apps, are attributed with `build_type` `"test"`. I'm not completely sure if there's a good way for determining this, but I believe enterprise apps include the `embedded.mobileprovision` file in the bundle, so maybe that can be used to determine the app is an enterprise build?

**Comment by bruno-garcia** [comment]
Would it make sense to send that as an `environment` instead?
Are you currently setting `environment` programatically? We're evaluating how/what to send there automatically if nothing is set by the user.

**Comment by philipphofmann** [comment]
@bruno-garcia just as an internal note this comes from SentryCrash in [`SentryCrashMonitor_System` ](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L457-L472). We set the build_type to test when the build is a testing build as for example [Testflight](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L432-L436).

This data ends up in the `event.context`
https://github.com/getsentry/sentry-cocoa/blob/a0f1ed4298cf0fedd36fabc7ec17e220df8c59e7/Sources/Sentry/SentryCrashIntegration.m#L171-L173

@koenpunt  you could override `build_type` in `beforeSend` with something like this
```
SentrySDK.start { options in
    options.dsn = "Your DSN"
    options.beforeSend = { event in
        event.context?["app"]?["build_type"] = "enterprise"
        return event
    }
}
```

**Comment by koenpunt** [comment]
I already set environment to production, but the app is released both as enterprise deployment and the App Store, so it would be nice to have the sdk determine that automatically.

@philipphofmann I'll try and see if that works for us.

**Comment by bruno-garcia** [comment]
@koenpunt How do you currently detect if it was installed via enterprise deployment? Is there an OOTB way to detect that?

**Comment by philipphofmann** [comment]
@koenpunt, can you please reply to @bruno-garcia question:

> @koenpunt How do you currently detect if it was installed via enterprise deployment? Is there an OOTB way to detect that?

**Comment by koenpunt** [comment]
> @koenpunt How do you currently detect if it was installed via enterprise deployment? Is there an OOTB way to detect that?

I'm no longer working on the project that required this, but AppStore builds won't have a `embedded.mobileprovison` file in the app bundle, so that could be a way to distinguish them from enterprise builds.
