### ISSUE TITLE
Customized error grouping is broken after upgrade from 5.x to 6.x

### ISSUE THREAD

**Issue by paiv** [getsentry/sentry-cocoa#796]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

Version of sentry-cocoa:
**6.0.3**

---
I have following issue:

In Sentry SDK 5.x I was able to customize `localizedDescription` of reported `NSError`, so Sentry would group events based on my needs. Specifically, I could add failing URL endpoint, where code path (stack trace) is the same for several endpoints. Then I could see failed URL endpoint in the title (message) of Sentry issue. Thus the same HTTP error would be grouped based on failed URL endpoint.

In Sentry SDK 6.0.3 this is currently broken for me, after this change https://github.com/getsentry/sentry-cocoa/pull/750

Is there a workaround? How can I split further errors having the same stack trace, error domain, HTTP code, but coming from different URL endpoints?

The only workaround I found is to switch from `SentrySDK captureError` to `SentrySDK captureEvent`, and build `SentryEvent` myself, with `kSentryLevelError`. But this requires me to set `attachStacktrace = YES` in global SDK options.

**Comment by philipphofmann** [comment]
Hi @paiv and thanks to reach out to us. 

> The only workaround I found is to switch from SentrySDK captureError to SentrySDK captureEvent, and build SentryEvent myself, with kSentryLevelError. But this requires me to set attachStacktrace = YES in global SDK options.

Yes, that would be one workaround. As of 6.x `attachStacktrace` is enabled per default anyways. 

We now put `localizedDescription` into the `event.context`, which ends up almost at the bottom of the issue view at Sentry. So you could look into [issue grouping](https://docs.sentry.io/platforms/apple/data-management/event-grouping/) to achieve what you desire.

**Comment by philipphofmann** [comment]
Another idea just popped into my head. You could extract the `localizedDescription` in the `beforeSend` from the `event.context`, ditch it from the `event.context`, and override the `event.message` with it. Seems a bit hacky, but it would work I think.

**Comment by philipphofmann** [comment]
As we didn't receive any updates we are going to close this now. Please open it again @paiv if you need more input to solve this issue.
