### ISSUE TITLE
Capture envelopes written to disk

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#804]
To facilitate integration with other SDKs (like react-native, flutter, capacitor), we'd like to be able to capture envelopes written to disk.

Currently, when react-native captures an event and is about to crash, it needs to create an envelope object in the bridge code, access the `fileManager`, and write the envelope to disk. 
The Android integration on the other hand receives events from react-native or native (NDK) through a directory, used by the other layers that write an envelope into. The Android SDK uses a FileObserver to trigger an event in the Java layer and capture that event in real-time.

If capturing the event fails, the event is cached so another attempt is made once the app restarts.

Important to note:

* Scope data and device data that can change when the app restarts, cannot be applied if the envelope was read after the app restarts.
  * ie: release, sdk-name, changes between app restarts
* When an envelope is written to disk, the SDK should detect that immediately, read the envelope and call `captureEnvelope`, in a way that scope data/device data is applied to the event, and then the envelope is written to the normal event queue to be sent in order with envelopes capture directly via the Objective-C API.

**Comment by philipphofmann** [comment]
As we don't have this on our roadmap currently, I'm going to close this. We can open another issue when this again comes up.
