### ISSUE TITLE
Easily Enable/Disabling the SDK

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#809]
This affects every platform since **6.x.x**

---
I have following issue:
Can't easily toggle the enabled state of SDK. Before 6.x.x we could toggle this with `SentryOptions.enabled`. This was removed with https://github.com/getsentry/sentry-cocoa/pull/736.

As a user of Sentry, I want easily toggle the enabled state because I need this for use cases of consent management and user privacy to comply with GDPR and related privacy legislation.

Mentioned by @eric and @lhunath in https://github.com/getsentry/sentry-cocoa/pull/736 and https://github.com/getsentry/sentry-cocoa/pull/700#discussion_r509641998

**Comment by philipphofmann** [comment]
@eric and @lhunath a current way to achieve this is to set the DSN to `""` or `nil` to disable the SDK
```swift
SentrySDK.start { options in
    options.dsn = nil
    // ...
}
```

To enable the SDK afterwards do 
```swift
SentrySDK.currentHub().getClient()?.options.dsn = "DSN"
````

We are currently discussing internally how to offer a better API for user consent and privacy in general.

**Comment by philipphofmann** [comment]
We just decided to basically undo #736 and add the old functionality again, because the new API could take a while and we don't want other users to experience this regression without offering them a reasonable opportunity. I can't give you an ETA yet, but it should be soonish. @eric and @lhunath

**Comment by lhunath** [comment]
Fair enough, appreciate the attention to user concern!

**Comment by eric** [comment]
Thanks!

**Comment by eric** [comment]
Is this gone again?

**Comment by marandaneto** [comment]
no, its available SentryOptions#enabled

**Comment by eric** [comment]
How can I get a reference to `SentryOptions` to change `enabled` from the `SentrySDK` object at runtime after I've initialized the `SentrySDK`?

**Comment by philipphofmann** [comment]
@eric use `SentrySDK.isEnabled` to find out if it is enabled and use `SentrySDK.close()` to disable/close it.
