### ISSUE TITLE
Don't see WatchOS crashes

### ISSUE THREAD

**Issue by dbyst** [getsentry/sentry-cocoa#824]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [*]  watchOS 7.1

_Swift:_
- [*]  Yes -> Swift 5
- [ ]  No

_sentry-cocoa installed with:_
- [*] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
6.0.6

---
I have following issue:
I don't see crash reports.

**Steps to reproduce:**
- Install Sentry SDK for watchOS target with pod:
        target 'WatchKit Extension' do
                 platform :watchos, '6.0'
                use_frameworks!
                pod 'Sentry'
         end

- Init SDK in ExtensionDelegate, applicationDidFinishLaunching method: 
            SentrySDK.start { options in
                options.dsn = "https://3af8f47a892440d0ab1a654af9c1314d@o394511.ingest.sentry.io/5494459"
                options.environment = "alpha"
                options.logLevel = SentryLogLevel.verbose
            }
- Added Button, that triggers SentrySDK.crash()
- Uploaded applicaition to AppStoreConnect
- Downloaded dsym
- Uploaded dsym to Sentry
- Install Watch app
- Click on button that cause a crash
- Open watch app so it could upload crashlogs

In logs:
"Sent 0 crash report(s)"

**Actual result:**
- Nothing appear in "Issues" on Web about crashes.
- But SentrySDK.capture(message: "alpha_message") appears just fine

**Expected result:**
- I would like to see crash report

**Comment by philipphofmann** [comment]
Thanks for reporting this @dbyst, there is already an issue open for this problem https://github.com/getsentry/sentry-cocoa/issues/406. I'm going to close this now.
