### ISSUE TITLE
Some of our issues are missing BREADCRUMBS and user info

### ISSUE THREAD

**Issue by RoCry** [getsentry/sentry-cocoa#826]
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> Swift 5.3

_sentry-cocoa installed with:_
- [x] Swift Package Manager

Version of sentry-cocoa:
**6.0.6**

---
I have following issue:

Some of our issues are missing BREADCRUMBS and user info(only have uuid and ip, we did set the normal user.id)

**Comment by philipphofmann** [comment]
Thanks, @RoCry for reaching out to us. Can you please post your configuration of Sentry in here and give us more information on how you call Sentry so we can reproduce the issue.

**Comment by philipphofmann** [comment]
As we didn't receive any input for two months we are going to close this issue now. Please feel free to open it again if you have more information @RoCry.
