### ISSUE TITLE
Sentry 6.0.7 crashes

### ISSUE THREAD

**Issue by CodingAleCR** [getsentry/sentry-cocoa#834]
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 5.0
- [ ]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.7**

---
I have the following issue:

When initializing the Sentry SDK with options.debug crashes

**Steps to reproduce:**
- Initialize with:
```
    SentrySDK.start { options in
      options.dsn = "API-KEY"
      options.environment = "development"
      options.debug = true
    }
```

**Actual result:**
- Crashes on initialization.

**Expected result:**
- Initialization is successful and the app can continue without issues.

**Comment by philipphofmann** [comment]
Hi @CodingAleCR, 
thanks for reaching out to us. Do you set a valid DSN, as we explain it in the docs https://docs.sentry.io/platforms/apple/guides/ios/#configure?

**Comment by CodingAleCR** [comment]
Hi yes, I set the valid DSN as per the docs, it works fine with version 6.0.6.

**Comment by philipphofmann** [comment]
Can you maybe post the error you receive here @CodingAleCR?

**Comment by CodingAleCR** [comment]
For some reason I am not able to reproduce it again, it might have been on my side, sorry to call the false alarm. I'll close the issue now. Thanks @philipphofmann !

**Comment by philipphofmann** [comment]
Thanks for letting us know @CodingAleCR. I was already getting a bit nervous because this would be a really bad issue, that could have affected multiple people.
