### ISSUE TITLE
How to import iOS history crashes

### ISSUE THREAD

**Issue by LuXiong** [getsentry/sentry-cocoa#855]
_Platform:_iOS

_Swift:_NO

_sentry-cocoa installed with:_CocoaPods

Version of sentry-cocoa:
**3.x.x**

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by philipphofmann** [comment]
Hi @LuXiong, thanks for opening up this issue. This issue is missing a lot of details. Can you please add more information, so we can help you. Also please update to 6.x.x, if you are on 3.x.x.

**Comment by philipphofmann** [comment]
As we didn't receive any input for over a month for this issue, we are going to close this now. Please feel free to open it again @LuXiong if you have more context.
