### ISSUE TITLE
Breadcrumb lose precision when serialize

### ISSUE THREAD

**Issue by ainopara** [getsentry/sentry-cocoa#857]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [ ] Swift Package Manager
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.9**

---
I have following issue:

timestamp in `SentryBreadcrumb` is serizlized with 
```objc
[serializedData setValue:[self.timestamp sentry_toIso8601String] forKey:@"timestamp"];
```
and the date formatter it did not specify millisecond in the template
```objc
[isoFormatter setDateFormat:@"yyyy-MM-dd'T'HH:mm:ss'Z'"];
```

**Steps to reproduce:**
- Send an event with breadcrumb, and view it in sentry website

**Actual result:**
- show breadcrumb with second precision

**Expected result:**
- show breadcrumb with millisecond precision

**Comment by philipphofmann** [comment]
Thanks, @ainopara for reporting this. We just need to set the milliseconds in the template and make sure we don't break anything to fix this:
```objc
[isoFormatter setDateFormat:@"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"];
```
In sentry-java the `DateUtil` already adds the milliseconds
https://github.com/getsentry/sentry-java/blob/a5b28427ad61c8941e2384dc098870db4062675a/sentry/src/main/java/io/sentry/DateUtils.java#L18.

This should be an easy fix, but I can't give you an ETA. Feel free to open up a PR for this, if you need this.
