### ISSUE TITLE
fix: Capture envelope updates session state

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#861]
When calling `captureEnvelope` with an event that has an `event.level = error` or higher the SDK needs to increment the error count of the active session.

Currently `captureEnvelope` can only be called on the `SentryClient`. The `SentryHub` needs to also expose this method as the session is managed there.

**Comment by marandaneto** [comment]
worth noting: Java/Android sets `SentryLevel.info` for `captureMessage` by default.

also sets `SentryLevel.fatal` for `uncaughtException` handler.

but for normal `captureException` and `captureEvent` we don't, the server infers to `error` by default, so it'd be nice if `level=null` marks a session as `errored` as well as it's the default level written in the docs.

**Comment by bruno-garcia** [comment]
`level=null` marked as error is an excellent point.

**Comment by philipphofmann** [comment]
On sentry-java the `errorCount`of a session is updated in the [`SentryClient`](https://github.com/getsentry/sentry-java/blob/d2ebce9cffd211dd9d6f46e285f856caea968789/sentry/src/main/java/io/sentry/SentryClient.java#L254-L266). The `SentryClient` only increments the `errorCount`, if [`SentryEvent.isCrashed()`](https://github.com/getsentry/sentry-java/blob/d2ebce9cffd211dd9d6f46e285f856caea968789/sentry/src/main/java/io/sentry/SentryEvent.java#L372-L384) or [`SentryEvent.isErrored()`](https://github.com/getsentry/sentry-java/blob/d2ebce9cffd211dd9d6f46e285f856caea968789/sentry/src/main/java/io/sentry/SentryEvent.java#L391-L393). Both `isCrashed()` or `isErrored()` don't check the level of the event.
I'm confused now. Either I don't get it, we need to change this on sentry-java or we should propose a different approach for sentry-cocoa.

**Comment by marandaneto** [comment]
@philipphofmann yep that's true, the Android way of checking it is aligned with Python at least.

https://github.com/getsentry/sentry-python/blob/34d9d7307379933516e803fb9d76f590a00cc139/sentry_sdk/client.py#L271-L282

so I believe the way to go would be checking the `mechanism` and/or `exception` list, but this would require the full deserialization of the event.
if we are able to deserialize only the `event.level` for now, would be a win already, I guess that's what we meant, or I am also missing something.

**Comment by bruno-garcia** [comment]
Makes sense to me to increment the counter if level=error or higher.
Might not be very common on mobile but on Java and .NET it is due to widespread use of loggers.

So a session has errors if someone called `logger.error()`? I'd say yes. You?

**Comment by marandaneto** [comment]
yes, but I'd rather implement this to all mobile SDKs, I don't want session counting being different on Android and Flutter for example.
