### ISSUE TITLE
Sentry 6.0.9 don't report crashes

### ISSUE THREAD

**Issue by timarcngroup** [getsentry/sentry-cocoa#863]
_Platform:_
- [x ]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5
- [ ]  No

_sentry-cocoa installed with:_
- [x ] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.9**

---
In the SwiftUI app with Sentry 6.0.9, I can receive logged messages `SentrySDK.capture(message: "")`, but I can not receive any crash reports.
It still working correctly with the downgraded version Sentry 5.2.2.

iOS 13.6 iPhone 11 Pro Sentry 5.2.2 : Work
iOS 13.6 iPhone 11 Pro Sentry 6.0.9 : Don't report any issue
iOS 14.2 iPhone 12 Pro Sentry 5.2.2 : Work ( log as different issue but it is okay for me )
iOS 14.2 iPhone 12 Pro Sentry 6.0.9 : Don't report any issue

**Steps to reproduce:**
You can reproduce it with this part of code in AppDelegate
```
DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
    SentrySDK.crash()
}
```

**Comment by philipphofmann** [comment]
Thanks, @timarcngroup for opening up this issue. If you always crash your application after around 3 seconds in your AppDelegate, it could be that the Sentry SDK doesn't have enough time to send the crash event to Sentry. We moved more of converting crash events and sending them to Sentry to the background. So it could be that in 5.2.2 we were slowing down your app launch and also delay the call to your async call to `SentrySDK.crash()` a bit more, so we could actually send the event to Sentry. Can you please try to increase the deadline to 10 seconds or so or maybe try to manually call `SentrySDK.crash()` when you click a button for example?

**Comment by timarcngroup** [comment]
Good news @philipphofmann , today I will try it one more time with 6.0.10 and it looks it works. 
Thank You.
