### ISSUE TITLE
Sentry wont build for Apple Silicon

### ISSUE THREAD

**Issue by HelgeBecker** [getsentry/sentry-cocoa#866]
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 5
- [ ]  No

_sentry-cocoa installed with:_
- [ ] Swift Package Manager
- [ ] CocoaPods
- [x] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.0.10**

---
I have following issue:
Sentry wont build for Apple Silicon
I am aware what you did, but putting arm on ignore is no solution

**Steps to reproduce:**
Build sentry using carthage

**Actual result:**
Sentry framework has no arm slice

**Expected result:**
framework having an arm slice

**Comment by philipphofmann** [comment]
Hi @HelgeBecker thanks for reaching out to us. 
I'm sorry to tell you that we are aware of the issue. This is because Carthage has an open issue for this, see https://github.com/Carthage/Carthage/issues/3019. We also mention this in our known limitations: https://github.com/getsentry/sentry-cocoa#known-limitations.

**Comment by philipphofmann** [comment]
[Carthage 0.37.0 release](https://github.com/Carthage/Carthage/releases/tag/0.37.0)  introduced support for XCFrameworks, which are needed for Apple Silicons. This means you now can use Sentry via Carthage for Apple Silicon macs. This release does not support producing an XCFramework for GitHub dependencies, which downloads binaries. There is a workaround with using `--no-use-binaries` to make Carthage rebuild Sentry from source, which will produce an XCFramework. Please read the [release notes of Carthage](https://github.com/Carthage/Carthage/releases/tag/0.37.0) for more details.

Please let us know @HelgeBecker if you run into problems.

**Comment by philipphofmann** [comment]
We are going to add this info to known limitations, see https://github.com/getsentry/sentry-docs/pull/2996
