### ISSUE TITLE
Device info is Only available for crashes, but not for events

### ISSUE THREAD

**Issue by huluyige** [getsentry/sentry-cocoa#867]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [ ] Swift Package Manager
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.10**

---
I have following issue:

Hello, with the lastest version of iOS SDK, i found that device informations (freememory...) are only available for crashes, but not available for events, am i wrong? or Could you please support device informations for other types of captures? (event, error, exception..)?

thanks !

**Comment by philipphofmann** [comment]
Hi @huluyige thanks for reaching out to us and sorry for the late reply. 

We set the `deviceInfo` on the scope in here: https://github.com/getsentry/sentry-cocoa/blob/b2e8f9ea9af1e99c8573547fe2842427b7feba9a/Sources/Sentry/SentryCrashIntegration.m#L141-L156

It should be sent with every event. Do you maybe do any changes to the scope, like calling `scope.clear()` somewhere?

**Comment by huluyige** [comment]
yes @philipphofmann you are absolutely right ! it works after using scope.clear() properly

**Comment by philipphofmann** [comment]
Thanks for the update @huluyige. I'm glad it works.
