### ISSUE TITLE
Improve thread safety for SentryScope

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#880]
`SentryScope` is not 100% thread-safe. For example `initWithScope`, `isEqual`, `isEqualToScope` and `hash` could cause problems. Furthermore `@synchronized(self)` is used in many places used which is not necessary.

**Comment by philipphofmann** [comment]
isEqual, isEqualToScope, and hash were removed with https://github.com/getsentry/sentry-cocoa/pull/884.

**Comment by philipphofmann** [comment]
I'm not sure @bruno-garcia how we can improve `initWithScope`. If you pass a `scope` that is modified during `initWithScope` I don't think we can do anything inside `initWithScope` to avoid this. It is the responsibility of the caller to make sure the passed in scope is not modified if he wants that.
Currently, `initWithScope` is called in the `SentrySDK` for the methods that use a [local scope](https://docs.sentry.io/platforms/apple/enriching-events/scopes/#local-scopes). There we retrieve the scope from the hub before calling `initWithScope`. So it could happen if you call `SentrySDK.configureScope` from another thread while also calling `SentrySDK.capture(message: "message", block: { scope in /* some changes */ })` in the current thread, that the scope is modified while initializing it with `initWithScope`, which wouldn't lead to an error. I don't think this is a problem, because `SentrySDK.configureScope` could also be called shortly before you call `SentrySDK.capture(message: "message", block: { scope in /* some changes */ })`. You never know when the other threads are modifying the scope. Am I missing something?

**Comment by bruno-garcia** [comment]
> I'm not sure @bruno-garcia how we can improve initWithScope. If you pass a scope that is modified during initWithScope I don't think we can do anything inside initWithScope to avoid this. It is the responsibility of the caller to make sure the passed in scope is not modified if he wants that.


We shouldn't be reading the members of `scope` from the constructor I think. We should be getting a clone from it. We can then safely read the fields from the clone.

> You never know when the other threads are modifying the scope. Am I missing something?

Exactly, we don't know when but we know it's possible. So we just need to synchronize access.

**Comment by philipphofmann** [comment]
So @bruno-garcia you mean we should add `copy` to `SentryScope` and call it in `initWithScope` before reading from it?

**Comment by bruno-garcia** [comment]
@philipphofmann I think it's the only way to guarantee thread-safety. The object can clone itself where it can hold the right locks while it reads through its maps and lists (any thread trying to change things through our public API will block) and returns a new instance.
