### ISSUE TITLE
Sentry grouping considers only the error's domain

### ISSUE THREAD

**Issue by nburyak** [getsentry/sentry-cocoa#901]
_Platform:_
- iOS
- tvOS

_Swift:_
- 5

_sentry-cocoa installed with:_
- CocoaPods

Version of sentry-cocoa:
**6.0.10**

---
I have following issue:

In the 6.x version the title is the combination of the error domain and code, for ex: _NSURLErrorDomain -1009_

I found it confusing that the events with the same error domain _but different error code_ appear under the same entry on the Sentry portal. It looks, like the errors with the same domain get merged:
![image](https://user-images.githubusercontent.com/2462403/104461982-4f6bc500-55b0-11eb-8199-7e6be92f6658.png)
_(error.tag is our custom tag, which combines domain and code)_

Is it the expected behaviour? Every error with a different error code is unique and I expect to see it, as a separate entry.

**Comment by philipphofmann** [comment]
Hi @nburyak, thanks for reaching out to us.

Yes, errors with the same domain get merged if their stacktrace looks similar. You can find out more about grouping here: https://docs.sentry.io/product/sentry-basics/guides/grouping-and-fingerprints/.

You could use [SDK side fingerprinting](https://docs.sentry.io/platforms/apple/data-management/event-grouping/sdk-fingerprinting/) to custom it as you want. When you capture an error, we combine the domain and error code into the message of the event https://github.com/getsentry/sentry-cocoa/blob/8dc9d09a5a4393e3610b2ee5fd4c7a669c0162d4/Sources/Sentry/SentryClient.m#L168-L178

You could use [`beforeSend`](https://docs.sentry.io/platforms/apple/configuration/options/#before-send) to set a custom fingerprint. Something like this could work for you.
```swift
SentrySDK.start { options in
    options.dsn = "your dsn"
    options.beforeSend = { event in
        if (event.level == SentryLevel.error) {
            if (nil == event.fingerprint) {
                event.fingerprint = [event.message.formatted]
            } else {
                event.fingerprint?.append(event.message.formatted)
            }
        }
        return event
    }
}
```

We will keep an eye open if more users want this behavior.

**Comment by philipphofmann** [comment]
Please upvote this if you would like to have an extra issue per error domain and code. This means MyDomain 1 and MyDomain 2 would be different issues in Sentry, and they are not grouped.

**Comment by philipphofmann** [comment]
As we set the params of [`SentryMessage`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/Public/SentryMessage.h) for the event @mitsuhiko do you know if we could adapt the grouping on the server to achieve this?

**Comment by bruno-garcia** [comment]
Since the solution with Fingerprint on the SDK is the way around this, we're closing this issue. Feel free to reopen otherwise.
