### ISSUE TITLE
Drop 'SentryLogLevel' in favor of 'SentryLevel'

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#911]
Context: https://github.com/getsentry/sentry-dart/pull/274/files#r561677973

SDKs use the SentryLevel (diagnosticLevel) for debugging levels too, so it's easier to pass the configuration across hybrid SDKs.
Right now Cocoa has a debugging level (SentryLogLevel) with limited options, leading to the issue above where we can't really map from one to one.

**Comment by philipphofmann** [comment]
So this would mean we could entirely drop `SentryLogLevel` in the next version?
