### ISSUE TITLE
Fix sessions for hybrid SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#912]
Context: https://github.com/getsentry/sentry-dart/pull/274/files#r561682268

A hybrid SDK can post a `SentryHybridSdkDidBecomeActive` notification. `SentrySessionTracker.start()` registers to an internal notification `SentryHybridSdkDidBecomeActive` and calls `didBecomeActive` when receiving int. 

The NSNotificationCenter could post
* just SentryHybridSdkDidStart
* both SentryHybridSdkDidStart and didBecomeActiveNotification
* just didBecomeActiveNotification

**Comment by philipphofmann** [comment]
`SentrySessionTracker.start()` registers to an internal notification `SentryHybridSdkDidBecomeActive` and calls `didBecomeActive` when receiving int. 

The `NSNotificationCenter` could post 
* just `SentryHybridSdkDidStart`
* both  `SentryHybridSdkDidStart` and `didBecomeActiveNotification`
* just `didBecomeActiveNotification`
