### ISSUE TITLE
Support Kotlin Multiplatform

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#924]
There's an experiment here: https://github.com/getsentry/sentry-kotlin-multiplatform

Related to: https://github.com/getsentry/sentry-cocoa/issues/741

Goals:
* Make it work with CrashKiOS: https://github.com/prof18/CrashKiOS/tree/master/sample/iosAppSentry
* Make sure `sentry-cocoa` works directly on a KMM app.

**Comment by philipphofmann** [comment]
Related to https://github.com/getsentry/sentry-cocoa/issues/741

**Comment by bruno-garcia** [comment]
Kotlin Multiplatform Mobile support has been released: https://github.com/getsentry/sentry-kotlin-multiplatform/releases
