### ISSUE TITLE
Unable to build from source using Carthage 0.37.0

### ISSUE THREAD

**Issue by jadar** [getsentry/sentry-cocoa#930]
### Environment

I'm using Sentry in the cloud on iOS.
- Sentry 6.1.4
- Carthage 0.37.0
- Xcode 12.4

### Steps to Reproduce

1. Add sentry to Cartfile
2. Run `carthage update sentry-cocoa --no-use-binaries --use-xcframeworks`

### Expected Result

Sentry-cocoa would successfully build.

### Actual Result

The build fails because of the modulemap. It seems that it's conflicting with the framework's automagically generated modulemap.

```
{project-dir}/Carthage/Checkouts/sentry-cocoa/Sources/Sentry/include/module.modulemap:1:8: error: redefinition of module 'Sentry'
module Sentry {
       ^
{DerivedData}/12.4_12D4e/sentry-cocoa/6.1.4/Build/Intermediates.noindex/ArchiveIntermediates/Sentry/BuildProductsPath/Release-iphoneos/Sentry.framework/Modules/module.modulemap:1:18: note: previously defined here
framework module Sentry {
                 ^
1 error generated.
```

**Comment by philipphofmann** [comment]
Hi, @jadar, 
Thanks for reaching out to us. For me `carthage update sentry-cocoa --no-use-binaries --use-xcframeworks` in a sample project with Xcode 12.4, Sentry 6.1.4, and Carthage 0.37.0 works fine. Can you maybe try to clean your build cached, delete the build folder and try again?

**Comment by jadar** [comment]
Sorry for the radio silence. I was able to finally build, so this is no longer an issue.
