### ISSUE TITLE
Mark the calling thread as `something` when capturing event

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#931]
The grouping code relies on a single stack trace to apply grouping rules. To help the server figure out what stack trace to use when all threads are reported, we need to mark the `crashed` field to `true` to the calling thread (the one that captured the message).

Similar to what we do on Android:

https://github.com/getsentry/sentry-java/blob/305a4626549e418e45604011f10152a8a9725f4f/sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java#L195

Relates to:

https://github.com/getsentry/sentry/issues/23556
https://github.com/getsentry/sentry/issues/23559

**Comment by marandaneto** [comment]
consider https://github.com/getsentry/sentry-java/blob/b7b5523430dd666577339dc8588e634df20bfb13/sentry/src/main/java/io/sentry/SentryThreadFactory.java#L113-L123 instead, trace back the `crashed` boolean

**Comment by philipphofmann** [comment]
But then the name `crashed` seems a bit weird to me. If we change it we should document that it is not only about `crashed` but the server needs this to figure out which stacktrace to use. Maybe we should also update the [dev docs](https://develop.sentry.dev/sdk/event-payloads/threads/)?

**Comment by marandaneto** [comment]
> But then the name `crashed` seems a bit weird to me. If we change it we should document that it is not only about `crashed` but the server needs this to figure out which stacktrace to use. Maybe we should also update the [dev docs](https://develop.sentry.dev/sdk/event-payloads/threads/)?

yes, it's not the first time nor the last time people got confused about the naming, but we hardly will find a name that fits all the languages too, so it was decided to keep as it is, the naming of the fields, also, it'd be a huge breaking change.

https://develop.sentry.dev/sdk/event-payloads/threads/
already has a good description for `current`

I've tried to change it once the description for `crashed` and it got to a very long discussion, and we gave up.

the labels on the UI makes more sense though.

**Comment by bruno-garcia** [comment]
Currenly `crashed` field as Manoel said shows up in the UI as `erroed`: true

![image](https://user-images.githubusercontent.com/1633368/106771197-b65b2780-660c-11eb-84c2-1b5a62f1b7fc.png)

And in the threads selector (the fire icon 🔥 )

Since this is for a captureMessage with attachStacktrace. We likely need another field here

**Comment by bruno-garcia** [comment]
We need to sit and write a DACI about this:
https://www.notion.so/sentry/Empty-DSN-Transports-Threads-a99a15b1e8b044c5baf2e326511ce707#983388d0b60d446382d57708aab140fb

**Comment by brustolin** [comment]
Now we have the `current` property. Is this still relevant? Can we close this?

**Comment by philipphofmann** [comment]
We set the current property when capturing events here
https://github.com/getsentry/sentry-cocoa/blob/1e065bcccc0572b03c44fa943cd9e6080e42c820/Sources/Sentry/SentryThreadInspector.m#L87

For ANRs here 
https://github.com/getsentry/sentry-cocoa/blob/1e065bcccc0572b03c44fa943cd9e6080e42c820/Sources/Sentry/SentryThreadInspector.m#L152-L153


And we set the crashed property for the crashing thread so Sentry sets the fire icon
 https://github.com/getsentry/sentry-cocoa/blob/1e065bcccc0572b03c44fa943cd9e6080e42c820/Sources/Sentry/SentryCrashReportConverter.m#L245
<img width="506" alt="Screenshot 2023-03-20 at 11 23 06" src="https://user-images.githubusercontent.com/2443292/226312300-e8ca7be6-3a5c-4317-a45d-ea1d85f1114b.png">

So, yes, we can close this @brustolin.
