### ISSUE TITLE
SentryCrash marks almost all stack trace frames as inApp for crashes in Flutter

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#933]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Sentry 6.1.4

### Steps to Reproduce

Use the [iOS sample from Flutter](https://github.com/getsentry/sentry-dart/tree/main/flutter/example/ios) and trigger a crash.

### Expected Result

Mark most frames as not inApp as in Cocoa, see https://sentry.io/share/issue/46bf37bc7e4a42829805b1de9fabe6d2/

<img width="798" alt="Screenshot 2021-02-03 at 10 55 44" src="https://user-images.githubusercontent.com/2443292/106729987-5f565200-660e-11eb-9e14-7ca1f0e93ffb.png">

### Actual Result

Almost all frames are marked as inApp, see https://sentry.io/share/issue/fcb50e7ca1ec4431ae9faff444faa597/

<img width="797" alt="Screenshot 2021-02-03 at 10 56 15" src="https://user-images.githubusercontent.com/2443292/106730056-72692200-660e-11eb-95a8-9f1ea6542ec2.png">

**Comment by marandaneto** [comment]
Consider if we require a special rule for Flutter as we do for React native
https://github.com/getsentry/sentry/blob/c77db62203708bd10df72897179a97fb73ad3f2a/src/sentry/grouping/enhancement-configs/common%402019-03-23.txt#L62

it'd be [SwiftSentryFlutterPlugin](https://github.com/getsentry/sentry-dart/blob/main/flutter/ios/Classes/SwiftSentryFlutterPlugin.swift)

**Comment by philipphofmann** [comment]
It could be that the logic for [`SentryCrashStackEntryMapper.isInApp`](https://github.com/getsentry/sentry-cocoa/blob/88e893eed4ba7e51e0d82834f18b7bec5b56905c/Sources/Sentry/SentryCrashStackEntryMapper.m#L40-L43), that is called in [`SentryCrashReportConverter`](https://github.com/getsentry/sentry-cocoa/blob/88e893eed4ba7e51e0d82834f18b7bec5b56905c/Sources/Sentry/SentryCrashReportConverter.m#L250), needs to be adapted.

**Comment by marandaneto** [comment]
@philipphofmann did you manage to test the fix?
your PR template says `Could fix` and I am not entirely sure if it fixes or not, so up to you to close this issue or not :)

**Comment by philipphofmann** [comment]
Sorry didn't mean to close this. GH did. I will try on Monday and close it then.

**Comment by philipphofmann** [comment]
#942 certainly improves this issue, but there are still many frames marked as `inApp`, which shouldn't be https://sentry.io/share/issue/c867acd56ff948f1aef3de9aa4848197/.
<img width="789" alt="Screenshot 2021-02-16 at 09 51 23" src="https://user-images.githubusercontent.com/2443292/108039572-895f3980-703c-11eb-939e-d153578d40c1.png">

Maybe it would be better to move all the logic to [Sentry](https://github.com/getsentry/sentry/blob/master/src/sentry/grouping/enhancement-configs/common@2019-03-23.txt) instead and remove [the logic from the Cocoa SDK](https://github.com/getsentry/sentry-cocoa/blob/f0cf27040c6c8d8f7d38e7eddbd19641fd336c8b/Sources/Sentry/SentryCrashStackEntryMapper.m#L40-L54).

**Comment by marandaneto** [comment]
true, pretty much all the `Flutter` package frames should be inApp=false

**Comment by bruno-garcia** [comment]
The unified API includes a set of options that SDKs can include. A couple of those are: 

`inAppInclude` and `inAppExclude`: https://docs.sentry.io/platforms/android/configuration/options/#in-app-include

We could add this to sentry-cocoa and Flutter when initializing would pass `inAppInclude=Runner`

**Comment by philipphofmann** [comment]
Related issue for `inAppInclude` and `inAppExclude`: https://github.com/getsentry/sentry-cocoa/issues/954
