### ISSUE TITLE
Provide a way on how to opt-out of the signal handler (SentryCrash)

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#960]
https://github.com/getsentry/sentry-dart/issues/317
https://github.com/getsentry/sentry-react-native/issues/1362

Android has a flag for it https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java#L210-L213

**Comment by philipphofmann** [comment]
Isn't this the same as removing `SentryCrashIntegration`?

**Comment by marandaneto** [comment]
@philipphofmann if this would be possible right now, that would be great, I already do it with `SentryAutoBreadcrumbTrackingIntegration` btw, I will check that and later we offer a friendlier option like a boolean.

**Comment by philipphofmann** [comment]
Release health would still work. You won't have any crashed sessions. Offline Caching would still work as well.

**Comment by marandaneto** [comment]
@philipphofmann unfortunately you lose Device's context if you remove this integration :(

**Comment by philipphofmann** [comment]
Oh, I didn't think about that yet. Maybe we can init SentryCrash to get the device context still but not initializing the signal handlers.

**Comment by bruno-garcia** [comment]
Closing because it's possible to opt-out by removing the integration. But has the side effect of losing device context which is a separate issue.
