### ISSUE TITLE
Support for SSL pinning

### ISSUE THREAD

**Issue by joptriodos** [getsentry/sentry-cocoa#965]
For security reasons our application lets the SentrySDK send all data via our own server.  As an extra safety measure we would like to use SSL pinning and TrustKit. Will this be supported in the future? It would suffice to be able to get access to the url session used by the SentrySDK. Thanks!

**Comment by philipphofmann** [comment]
Hey @joptriodos, 
Thanks for reaching out to us. We don't support this in the Cocoa SDK right now. Other SDKs as [Java](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java#L233-L237) and [Python](https://github.com/getsentry/sentry-python/blob/1279eeca6763e119d97da5da8318f48a04d3adef/sentry_sdk/consts.py#L72) already have this feature. So we could also add it here. I can't give you an ETA, but feel free to open up a PR if you are blocked. If someone else also wants this feature, please upvote so we can prioritize this.

**Comment by joptriodos** [comment]
Hi all, I created a PR which makes it possible to set a delegate on the url session. Not sure what the best way is to invite reviewers, but maybe @philipphofmann or @bruno-garcia could have a look? It is a relatively simple addition and it would be great if this can be merged. If it still helps to upvote the original issue to speed things up, please let me know. Thanks!
