### ISSUE TITLE
Create transaction in sample app

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#970]
It was suggested [in this comment](https://github.com/getsentry/sentry-cocoa/pull/909/#issuecomment-789206757) to create a sample so we can easily see the performance feature in action.

This could be done on this [iOS-Swift sample](https://github.com/getsentry/sentry-cocoa/tree/master/Samples/iOS-Swift) that already gets pushed to test flight.

For reference, React Native sample with performance:
[React Native](https://github.com/getsentry/sentry-react-native/tree/master/sample/src)

**Comment by brustolin** [comment]
Take a look at PR #971.
