### ISSUE TITLE
Detect `environment` automatically

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#976]
Thoughts:

* Consider iOS: TestFlight as environment
* Consider build_type values as environment: https://github.com/getsentry/sentry-cocoa/issues/778
* KSCrash has some logic already which ends up on build_type: https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L457-L472
* simulator could be an environment. So we can easily opt-out of it, and even filter out with beforeSend events from simulators. Simulator vs Emulator might be odd but on the iOS world it's simulator and the protocol device.simulator is already a thing.

Relates to: https://github.com/getsentry/sentry-java/issues/1302
More context: https://app.asana.com/0/1162483910998154/1198217673079541

**Comment by brustolin** [comment]
For reference: https://stackoverflow.com/questions/26081543/how-to-tell-at-runtime-whether-an-ios-app-is-running-through-a-testflight-beta-i

**Comment by philipphofmann** [comment]
This code snipped might be useful https://gist.github.com/lukaskubanek/cbfcab29c0c93e0e9e0a16ab09586996.

**Comment by bruno-garcia** [comment]
We've closed the Android one: https://github.com/getsentry/sentry-java/issues/1302
The idea is to just report `flavor` but no mess with `environment`.
