### ISSUE TITLE
Unreal Engine Native Wrong thread / callstack

### ISSUE THREAD

**Issue by deathlyrage** [getsentry/sentry-cocoa#978]
### Environment

How do you use Sentry?
- Sentry SaaS.

Which SDK and version?
- All SDK versions but have tested and updated and reproduced it on the latest SDK. (6.2.1)

### Steps to Reproduce

1. Using a Unreal Engine project call Sentry Cocoa to init with a DSN.
2. Get a crash to happen such as deref nullptr.
3. Notice crash report in sentry callstack always uses the wrong thread and not the thread that crashed. For me all crashes crash on the PhysX thread.

![image](https://user-images.githubusercontent.com/3461558/110014458-ecf4a100-7d76-11eb-98aa-8d2610ff7a3c.png)

### Expected Result

The thread that caused the crash should be displayed in the crash log with a callstack provided.

### Actual Result

Here is a example report on sentry.io, but basicly happends to all of my crashes even if i send a non crash and just a sentry message the callstack is wrong.
https://sentry.io/share/issue/2aaddfcddfc443828b811766c40ed475/

### Solution Discussion
Is my best solution to try move to sentry native and call that instead? I'm not sure what state the breakpad handler is in, but currently all my crashes on iOS have been useless for the last 6 months or so.

**Comment by bruno-garcia** [comment]
@deathlyrage thanks for sharing the details.
Is Sentry marking the wrong thread as crashed so preselecting the wrong thread? Or is it not including the crashed thread at all somehow? I assume there's no easy repro you could share so we can peek with a debugger, right?

**Comment by deathlyrage** [comment]
The crashed thread doesn't appear to be listed, (which the crashed thread is in the game thread). Or at least I couldn't find it.
The physX thread its marked is a background worker thread that didn't crash at all.

The crash reports from apple's backend are all correct afaik, if i download the crash and load it in xcode it correctly picks up, but all the crashes found by sentry are wrong. 

I could try provide a unreal engine test project? would require some setup work but that might help.

**Comment by bruno-garcia** [comment]
Thanks for clarifying, sounds like a bug.

> I could try provide a unreal engine test project? would require some setup work but that might help.

We'd really appreciate so we can test things out on our end.
Only thing I tested UE4 so far was with Desktop apps (with the crash reporter):
https://github.com/getsentry/examples/tree/master/unreal-engine/GameOfBroken

But I'll give it a try and other folks at Sentry will likely be interested in seeing how this works.

**Comment by deathlyrage** [comment]
Yeah we used to use the default UE4 crash reporter but we couldnt use it to provide user information and proper sentry intergration, we are trying to use sentry directly. Sentry Native for Windows, Mac, Linux, Java for Android and Cocoa for iOS.

Win, Mac, Linux, Android callstacks and threads all work, however the callstacks are less useful on android but more accurate. The callstacks on iOS have been basicly effectively useless for programming action because they are all off.

**Comment by deathlyrage** [comment]
Here is another example where I call a sentry message directly and get a similar result, instead of via a native exception: 

https://sentry.io/share/issue/6f7fe20e864947b09b9bddbb850de940/

**Comment by deathlyrage** [comment]
@bruno-garcia if you can get in contact with me via discord or email I can send you a copy of the project that has the problem so you can attach the debugger.

matthew alderongames . com
discord: Alderon Matt#1479

**Comment by deathlyrage** [comment]
I figured out the root of the problem, Unreal engine strips debug symbols in a way that confuses sentry and the callstack. I managed to get the unstripped symbols on a HTTP server (as they are too big to upload to sentry) this results in the callstacks and threads to be correct.

**Comment by bruno-garcia** [comment]
> I figured out the root of the problem, Unreal engine strips debug symbols in a way that confuses sentry and the callstack. I managed to get the unstripped symbols on a HTTP server (as they are too big to upload to sentry) this results in the callstacks and threads to be correct.

That's great news. Would you be willing to describe it here the steps you took on UE4 to fix the problem so I can add to our docs?
