### ISSUE TITLE
Captured errors should include Trace information

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#990]
When a `CaptureEvent` is called, the event should include the trace information that exists on the scope.

i.e:

```
// assuming the span is bound to the scope like Sentry.configureScope(s -> s.setSpan(span));
var span = Sentry.startChild(); 

// This error should include the span information
Sentry.captureError(error); 
span.finish();

```

**Comment by brustolin** [comment]
Issue solved in PR #1065.

**Comment by marandaneto** [comment]
@bruno-garcia does this issue should address also setting errors to a span like we do on the other SDKs?

eg
span.throwable = my_throwable

https://docs.sentry.io/platforms/java/performance/custom-instrumentation/#connect-errors-with-spans

otherwise we'd have to create a new issue

**Comment by bruno-garcia** [comment]
> @bruno-garcia does this issue should address also setting errors to a span like we do on the other SDKs?
> 
> eg
> span.throwable = my_throwable
> 
> https://docs.sentry.io/platforms/java/performance/custom-instrumentation/#connect-errors-with-spans
> 
> otherwise we'd have to create a new issue

Exceptions are not as broadly used here as they are in .NET and Java so I think we can get away without that feature. Specially at first, while we evolve the performance API.

**Comment by philipphofmann** [comment]
I think this was solved with https://github.com/getsentry/sentry-cocoa/pull/1065.
