### ISSUE TITLE
Scope sync should be fine grained

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#991]
Today changes to the scope fire an event that doesn't indicate what in the scope changed.
That means we serialize the whole scope into the `SentryCrash` context on each scope change, for example when a breadcrumb is added. 

One approach we can consider is what was done in Java where there's observer pattern used by the scope so we can hook by integrations:

https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Scope.java#L169-L173

https://github.com/getsentry/sentry-java/blob/4a9b3cc961e74421b8c56b77cc4808c5ddae2d5b/sentry-android-ndk/src/main/java/io/sentry/android/ndk/NdkScopeObserver.java#L17

**Comment by philipphofmann** [comment]
Another straightforward approach would be to serialize the scope in [SentryCrash.onCrash](https://github.com/getsentry/sentry-cocoa/blob/2bfbbcdc11f84efd54498120e882d42e8bedd30e/Sources/SentryCrash/Recording/SentryCrash.h#L148-L157), but we absolutely must not call Objective-C code in this callback. 

At the time of the crash, the scope needs to be serialized and stored in memory accessible by C code. Therefore, the above-mentioned approach with an observer pattern and a fine-grained serialization is better.
